### ISSUE TITLE
open and login Bitwarden app on MacOS is very slowly

### ISSUE THREAD

**Issue by zhiweizh0ng** [bitwarden/clients#10002]
### Steps To Reproduce

1. Open 'Bitwarden' app on MacOS,
2. Input  'password' or touch id
3. Then the login interface does not appear for a long time, and I don’t know how long I have to wait.

### Expected Result

The password vault is displayed immediately after entering the fingerprint or password.

### Actual Result

After entering the fingerprint or password, the system still stays on the login interface. Sometimes, the password vault interface cannot be seen even after waiting for a long time, and sometimes, the system enters the password vault interface after several minutes.

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.0

### Installation method

Mac App Store

### Build Version

2024.6.4 (26239)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

I'd recommend uninstalling the desktop app, removing any leftover storage(https://bitwarden.com/help/data-storage/#on-your-local-machine), rebooting your device, and reinstalling the desktop app.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
