### ISSUE TITLE
Can't save new items to vault, "Failed to access token - token not found"

### ISSUE THREAD

**Issue by Atri7** [bitwarden/clients#10004]
### Steps To Reproduce

1. Create a new vault item
1. Save the item
An error appears saying "Failed to access token - token not found," and my item is not saved. 

### Expected Result

My item would be saved and I would return to the main Bitwarden vault

### Actual Result

The aforementioned error is displayed in a small red box in the upper right corner

### Operating System

Linux

### Operating System Version

Fedora 39

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.4 Shell 29.4.2 Renderer 122.2.6261.156 Node 20.9.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
@Atri7 thank you for the report!  A few questions to help guide diagnosis:

1. Did you download this version (`2024.6.4`) from bitwarden.com, or download a previous version that was upgraded to `2024.6.4`?
2. Have you attempted to log out of the desktop and back in to see if the behavior is fixed?
3. Do you have `gnome-keyring` or another Secret Service provider installed and enabled?

Thank you for your help.

**Comment by Atri7** [comment]
Thanks for your timely response.

- My previous version upgraded to this version yesterday.
- Yes, that didn't fix the problem.
- I have KDE Wallet installed.

**Comment by ionspin** [comment]
I am experiencing the same issue on Arch Linux:
- Bitwarden desktop 2024.6.4-1 installed from pacman
- Logging out didn't fix the problem
- I have gnome-keyring installed and enabled
- I'm using bitwarden cloud with premium subscription
- Creating new items or updating existing ones fails

**Comment by ionspin** [comment]
This is from the logs when trying to create a new item:
```
10:12:04.460 › mac required.
10:12:04.460 › Error: Failed to decode access token: Access token not found.
10:12:04.461 › Received API exception: Error: Failed to decode access token: Access token not found.
```

**Comment by MartinX3** [comment]
@ionspin The arch linux package is out of date.

**Comment by ionspin** [comment]
Hi @trmartin4, I have not experienced this problem since following @MartinX3 advice (which I could have sworn I initially tried :) )
I'm also now on latest Arch version  version, and I have not observed this issue.
```
Version 2024.8.0
Shell 31.4.0
Renderer 126.0.6478.234
Node 20.16.0
Architecture x64
```

Thanks!

**Comment by trmartin4** [comment]
Thank you.  We will continue to monitor if this behavior occurs again.  For now, we are closing this issue as we believe we have resolved the underlying cause.
