### ISSUE TITLE
 CLI asks for master password when using flag --session

### ISSUE THREAD

**Issue by MaxKeller12** [bitwarden/clients#10029]
### Steps To Reproduce

1. `bw config server {your_server}`
2. `bw login`
3. enter email address and master password
4. `bw unlock`
5. enter master password
6. `bw list items --session {your_session_key}`

### Expected Result

a list of items

### Actual Result

prompt for master password

### Screenshots or Videos
`bw unlock --check` gives unexpected output

![image](https://github.com/bitwarden/clients/assets/94543796/84236223-91b7-42a7-b38a-740aaee97d47)

### Additional Context

I am using version 2024.6.0 due to the bug in 2024.6.1 see https://github.com/bitwarden/clients/issues/9919. Last week, i did not have this issue.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Shell

Bash

### Build Version

2024.6.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MaxKeller12** [comment]
If anyone encounters the same issue. I had to remove the bw package and reinstall it in order to get it to work properly again.

**Comment by MatthiasGrandl** [comment]
Also facing this. Together with #9646 this basically completely bricks my usage of the CLI :(

**Comment by dashaun** [comment]
I'm unable to unlock using SNAP 66 or Linux x86 release 2024.7.1, on WSL 2/Ubuntu

Keep getting "Invalid master password."

I think my issue is related.

**Comment by DonSYS91** [comment]
> I'm unable to unlock using SNAP 66 or Linux x86 release 2024.7.1, on WSL 2/Ubuntu
> 
> Keep getting "Invalid master password."
> 
> I think my issue is related.

updating to 7.1 solved my issue. double check that you're removing data.json and letting the auth create a new one

**Comment by hkpD** [comment]
> I was unable to get the status "unlocked" even after login and export of the session key to my env.
> 
> I deleted the files `~/snap/bw/64/Bitwarden\ CLI/data.json` and `~/snap/bw/65/Bitwarden\ CLI/data.json` and then did a login again. (in my case i login using api key `bw login --apikey`)
> 
> Using version 2024.6.0 (aka 64 in snap)

Thank you very much. I was having constant issues until I deleted the data.json file that was made when I installed bw CLI through winget

**Comment by mixxor** [comment]
I can only second the data.json Problem, i tried out all versions before. I recommand adding this [in the CLI](https://bitwarden.com/help/cli/)

Cleaning up the data.json on `bw sync` could also help...

**Comment by lukens** [comment]
I'm using version 2024.11.0 and had the same issue as seems to be described here.

Deleting `~/.config/Bitwarden\ CLI/data.json` and logging in again resolved the issue.
