### ISSUE TITLE
Missing Add account translation in account switcher

### ISSUE THREAD

**Issue by kwiateusz** [bitwarden/clients#10051]
### Steps To Reproduce

1. Click on extension icon
2. Click on accunt avatar in right top corner

### Expected Result

Add account button should be translated

### Actual Result

Add account button always stays in english

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/924979/db91ebe6-8d1a-4469-99ab-64e5f4e580ab)

### Additional Context

One usage of i18n pipe is missing. I can fix that but I need help with place where should translated text land.

Missing pipe: https://github.com/kwiateusz/bitwarden-clients/commit/0426916ba425c3e92eb1de74996c80ea4c4a76da

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge

### Browser Version

126

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @kwiateusz thank you for your report and also offering your help to fix this.

The missing i18n pipe is likely part of the issue, and/or where the [value gets added](https://github.com/bitwarden/clients/blob/6d6785297b43e33ecf158c55b7d0b16ea9c589c7/apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts#L83)

The translation keys are added/updated in `en/messages.json`-file and only there as it's the basis for all translations. The translation are then done within Crowdin.

For desktop we already have https://github.com/bitwarden/clients/blob/6d6785297b43e33ecf158c55b7d0b16ea9c589c7/apps/desktop/src/locales/en/messages.json#L2093
which would also need to be added to https://github.com/bitwarden/clients/blob/6d6785297b43e33ecf158c55b7d0b16ea9c589c7/apps/browser/src/_locales/en/messages.json

In case you need any help setting up your dev environment: https://contributing.bitwarden.com/

I hope that helps and looking forward to see a pull request in case you decide to tackle this.

Kind regards,
Daniel

**Comment by djsmith85** [comment]
> @djsmith85 I found earlier that service you mentioned but what approach will be better, useage of pipe or injection of translate service to translate text during options array build?
> 
> I preffer pipe but maybe there're some rules for that?

The @bitwarden/team-auth-dev will make the final decision once you've opened the PR, as they own that part of the codebase. Using the i18n-pipe imho is fine, but the service (use translation key instead of literal for name) and the `en/message.json` will need to be changed either way.
