### ISSUE TITLE
Extension broken inside Firefox in OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by helaslo** [bitwarden/clients#10085]
### Steps To Reproduce

1. Install Bitwarden extension inside Firefox on OpenSuse Tumbleweed
2. Fill in your login details
3. Click login
4. Nothing happens
5. Close-then reopen the extension
6. The extension's window is empty

### Expected Result

The extension works properly

### Actual Result

Extension only works from right click menu

### Additional Context

In about: debugging I can see this:
```
Uncaught (in promise) TypeError: can't access dead object
[some log entry which has an access token]
[2024-07-11T23:37:45.155Z] Error: Failed to start the connection: Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled. [Utils.ts:185:29](webpack:///src/Utils.ts)
Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.
    onclose WebSocketTransport.ts:136
 ```
 
 Issue looks the same as #9582  (sorry if this counts as a duplicate, I am opening this because that one is closed)

### Operating System

Linux

### Operating System Version

20240704

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.6.3 (last updated on June 27)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by gombosg** [comment]
Same here, gray screen in extension window.
Autofill via right-click menu still works, preserving my previous login.
Firefox 128.0, Fedora 40.
As I was typing this, the window appeared 🤦🏽  But it took more than a minute.
Fortunately, the extension debug window was open so I'm attaching some info.

It looks like some error accessing network requests for some reason.

It's also happening that the left sidebar is good now, but the right popup menu doesn't appear. When I click on it, more of the 
![image](https://github.com/user-attachments/assets/70c595a3-5fa3-403a-9690-0581b2837f37)
error appears.

![image](https://github.com/user-attachments/assets/6ef53bec-bc6b-4188-a2cf-ed576c6cc3f4)


[68a8778f-0b42-4bb3-b85a-40aaa8e82c2d_Export-e01a646f-1e0b-4328-85a8-22581eb2ffad.zip](https://github.com/user-attachments/files/16189912/68a8778f-0b42-4bb3-b85a-40aaa8e82c2d_Export-e01a646f-1e0b-4328-85a8-22581eb2ffad.zip)
[console-export-2024-7-12_9-6-51.txt](https://github.com/user-attachments/files/16189925/console-export-2024-7-12_9-6-51.txt)

**Comment by helaslo** [comment]
Here are my system details:

Operating System: openSUSE Tumbleweed 20240704
KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.3.0
Qt Version: 6.7.2
Kernel Version: 6.9.7-1-default (64-bit)
Graphics Platform: X11
Processors: 12 × AMD Ryzen 5 5600G with Radeon Graphics
Memory: 30.6 GiB of RAM
Graphics Processor: llvmpipe

I have Packman packages installed, however I don't think that makes a difference.
I have the same setup, this occours in 2 out of 3, the common point between the two broken systems is that they are using an integrated GPU

**Comment by gombosg** [comment]
I could fix this by removing the extension, removing the directory
```
/home/<user>/.mozilla/firefox/<profile name>/storage/default/moz-extension+++f0573a9f-8d1d-44a2-9afc-09fc0a634e35^userContextId=<userId>
```
then reinstalling the extension. Now it's all good!

**Comment by gombosg** [comment]
Figured out the actual root cause - "it's always DNS". I had [1.1.1.1](https://one.one.one.one/) set as DNS resolver for my network connection, which has caused the issue. Resetting to automatic solved the extension issue.

**Comment by dave12311** [comment]
Same happening here on the current NixOS unstable. Re-installing the extension solves it for a while, but then it breaks again.

**Comment by ottotivadar** [comment]
Hello! I have the same issue, not just with the extension, but with the desktop app, and I have problem opening vault.bitwarden.com from MS Edge or Chrome.

After some investigation, it is indeed a DNS related issue.
Making a lookup using Cloudflare or Quad9 gives the following result:
```
; <<>> DiG 9.18.27 <<>> @1.1.1.1 vault.bitwarden.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43554
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;vault.bitwarden.com.           IN      A

;; ANSWER SECTION:
vault.bitwarden.com.    258     IN      CNAME   n.sni.global.fastly.net.
n.sni.global.fastly.net. 18     IN      A       151.101.193.91
n.sni.global.fastly.net. 18     IN      A       151.101.65.91
n.sni.global.fastly.net. 18     IN      A       151.101.1.91
n.sni.global.fastly.net. 18     IN      A       151.101.129.91

;; Query time: 33 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Wed Jul 24 13:55:28 CEST 2024
;; MSG SIZE  rcvd: 149
```

Making a lookup with the DNS of my ISP (Vodafone Hungary):
```
; <<>> DiG 9.18.27 <<>> @80.244.99.37 vault.bitwarden.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1373
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;vault.bitwarden.com.           IN      A

;; ANSWER SECTION:
vault.bitwarden.com.    62      IN      CNAME   n.sni.global.fastly.net.
n.sni.global.fastly.net. 10     IN      A       199.232.17.91

;; Query time: 13 msec
;; SERVER: 80.244.99.37#53(80.244.99.37) (UDP)
;; WHEN: Wed Jul 24 13:55:04 CEST 2024
;; MSG SIZE  rcvd: 101
```

If I switch to the DNS of my ISP, I can log in to the web vault, and the application, however everything is pretty slow. Strangely, everything was still working a few weeks ago using Quad9.

**Comment by gombosg** [comment]
>Vodafone Hungary

Hm, I'm at the same ISP, and experience the same. Interesting, that the ISP's DNS works while an external provider fails?

**Comment by dave12311** [comment]
Huh, I'm also at the same ISP.

The desktop app seems to be working when logging in for the first time, but once I'm logged in and I close and reopen it, the 'Unlock' button does nothing.

**Comment by trmartin4** [comment]
@helaslo are you still experiencing this with the latest release?  I want to make sure that your issue wasn't DNS-related, and that it is still occurring.

Thank you.

**Comment by gombosg** [comment]
Not OP, but Bitwarden is working fine for me now (both with custom DNS and ISP DNS), and it was probably something related to the DNS provider.
