### ISSUE TITLE
Can't switch server

### ISSUE THREAD

**Issue by rottmann** [bitwarden/clients#10090]
### Steps To Reproduce

1. click Bitwarden icon
2. click "login with"
3. select bitwarden.com works
4. select bitwarden.eu can not be clicked

### Expected Result

Switch server

### Actual Result

Switch not possible

### Operating System

Linux

### Operating System Version

Linux Mint 21.3 (Linux 6.5.0-41-generic #41~22.04.2-Ubuntu)

### Web Browser

Firefox

### Browser Version

128 (64-Bit)

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rottmann** [comment]
Even i use keyboard to select the field and press enter, nothing happen.
"self host" could be clicked.

**Comment by Krychaz** [comment]
Hello there, 

The installation most likely got corrupted. As the reinstall fixed the issue I will now close this issue.
