### ISSUE TITLE
Username generator doesn't show the user the generated alias

### ISSUE THREAD

**Issue by Segment0895** [bitwarden/clients#10091]
### Steps To Reproduce

1. Generate an alias via forwardemail.net
2. Check that a red square appears
3. Confirm that indeed the alias was created on forwardemail.net, thus proving the API working

See screenshot of "red square"
![image](https://github.com/user-attachments/assets/da25729e-c75d-4c10-bbde-d6969707aea3)

### Expected Result

I see the generated alias

### Actual Result

I don't see the generated alias

### Screenshots or Videos

please see "Steps to reproduce", pic included

### Operating System

Linux

### Operating System Version

Fedora 40

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.6.4 Shell 29.4.2 Renderer 122.0.6261.156 Node 20.9.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chappellkm** [comment]
Happening here as well on Windows 11 Microsoft Edge extension version 2024.6.2.
