### ISSUE TITLE
Extension closes instead of unlocking on enter key press

### ISSUE THREAD

**Issue by poka-IT** [bitwarden/clients#10106]
### Steps To Reproduce

1. Open the Brave browser.
2. Click on the Bitwarden extension icon.
3. Enter the master password.
4. Press the Enter key.

### Expected Result

The Bitwarden extension should unlock and display the vault.

### Actual Result

The Bitwarden extension closes immediately upon pressing the Enter key.

### Additional Context

This issue disrupts the user experience as it prevents smooth access to the vault. A temporary workaround is to click the unlock button with the mouse, but this is not an ideal solution.

### Operating System

Linux

### Operating System Version

Latest Manjaro with gnome

### Web Browser

Brave

### Browser Version

Version 1.67.123 Chromium: 126.0.6478.126 (Build officiel) (64 bits)

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by anonid64** [comment]
I have been same problem in latest version of Bitwarden extensions in chrome. While the another synced device not have this isssues.

**Comment by AtVe-B24** [comment]
Same problem on Edge!

**Comment by AtVe-B24** [comment]
> Hi there,
> 
> I attempted to reproduce your issue and was unable to do so.
> 
> We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
> 
> You can include a link to this issue in the message content.
> 
> Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).
> 
> The issue here will be closed.
> 
> Thanks!

Why do you close this? There is a BUG!
Please fix this.

**Comment by poka-IT** [comment]
I think this issue occurs in combination with another active extension, but I can't work out which one.
If you disable all other browser extensions, do you still have the problem?

**Comment by anonid64** [comment]
> I think this issue occurs in combination with another active extension, but I can't work out which one. If you disable all other browser extensions, do you still have the problem?
> 
> Anyway [@TroyBW](https://github.com/TroyBW) please open this issue again.

I already try to disable all another extensions and keep only Bitwarden extensions. But still have same issue.

But i have a new info, when i re-install with default setting of Chrome and install Bitwarden, it works normally. I don't know why, but i think some setting in Chrome conflict with Bitwarden extension

**Comment by Tarentules** [comment]
Hi is there a known fix for this or work being made on it? I still encounter this issue daily with the latest Chrome extension:

- Chrome version - 146.0.7680.165 (Official Build) (64-bit)
- Chrome BW client - 2026.2.0
- OS - Windows 11 (OS Build 26200.8039)
