### ISSUE TITLE
Missing textures in desktop client

### ISSUE THREAD

**Issue by FillyBilly** [bitwarden/clients#10138]
### Steps To Reproduce

![Screenshot 2024-07-16 170517](https://github.com/user-attachments/assets/1de95056-6451-4e11-8943-78d867a63384)
This is what my desktop client looks like everytime I open it. It has been like this for the past few months.

This typically is not an issue because every time I open the desktop client there would be an update. After the update finishes the client would return to normal. I don't open the desktop client often so being that it fixed itself after the update would leave me without an issue. However, there hasn't been an update recently so my desktop client will not fix.

### Expected Result

The Client to work and look normally. 

### Actual Result

The client looks broken like missing textures or something.

### Screenshots or Videos

![Screenshot 2024-07-16 170517](https://github.com/user-attachments/assets/9a8eb48e-2f67-4cc7-837d-6926187f3ae0)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @FillyBilly and thank you for your report.

Could you please try updating to a [newer version](https://bitwarden.com/download/) (2024.6 or higher) and see if this resolves it. In addition there's a setting on the desktop client to disable GPU acceleration, which might help. More information can be found here: https://bitwarden.com/help/product-faqs/#q-does-bitwarden-have-any-settings-that-can-be-adjusted-for-graphics-or-performance

Kind regards,
Daniel
