### ISSUE TITLE
Firefox Extension does not "Remember email" when it is enabled 

### ISSUE THREAD

**Issue by NovaSilentium** [bitwarden/clients#10179]
### Steps To Reproduce

1. Go to Firefox extension
2. Enter email address
3. Scroll down and check the box "remember email"
4. Logout
5. Notice you would need to add the email again as it was not remembered

### Expected Result

Open the Bitwarden extension in Firefox.
Enter your email address in the provided field.
Scroll down to locate the option to "remember email" and ensure the checkbox is selected.
Log out of the Bitwarden extension.
Upon logging back in, the email address previously entered and marked to be remembered should still be displayed in the email field. This indicates that the extension correctly retains and recalls the email address, providing a seamless login experience without requiring the email to be re-entered.

### Actual Result

   Open the Bitwarden extension in Firefox.
    Enter your email address in the provided field.
    Scroll down and check the box "remember email" to enable this feature.
    Log out of the Bitwarden extension.
    Upon logging back in, the email address that was previously entered is not remembered or retained. Instead, the email field is empty, requiring the user to manually input the email address again for login.

### Additional Context

Also occurs on Windows

### Operating System

macOS

### Operating System Version

macOS 14 Sonoma

### Web Browser

Firefox

### Browser Version

128.0

### Build Version

Version: 2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
@NovaSilentium this has been addressed with #9750 which is in our `main` branch.  It will be included in our next release.  I am closing this as we have merged the change.
