### ISSUE TITLE
Touch ID integration does not automatically unlock the browser plugin

### ISSUE THREAD

**Issue by carnun** [bitwarden/clients#10225]
### Steps To Reproduce

1. Wait till the Bitwarden App is locked
2. Open the browser plug in
3. Click on Unlock with Biometrics
4. A dialog displays saying you need to unlock the desktop app

### Expected Result

As with previous versions the browser app should unlock on Biometrics even if the Desktop app is locked

### Actual Result

A dialog displays saying you need to unlock the desktop app

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/327fdd8f-ce61-4a40-95a4-ca40608e26f6)

### Operating System

macOS

### Web Browser

Vivaldi

### Browser Version

6.8.3381.48

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by blxckbxrd** [comment]
There's some info and talk about this in #9539.
