### ISSUE TITLE
stop removing tags from your repo

### ISSUE THREAD

**Issue by brjsp** [bitwarden/clients#10239]
A few weeks ago, you tagged commit 5b411894969020e7b0b07b1177687493f1fe2ca0 as https://github.com/bitwarden/clients/releases/tag/desktop-v2024.7.0 . That tag existed long enough for me to pull the code and submit it to openSUSE where i maintain the <a href="https://build.opensuse.org/package/show/devel:languages:nodejs/bitwarden">bitwarden package</a>. This commit is no longer in repository, which makes it harder for users to verify the provenance of the code. I'm also tagging @alex19EP (my Arch Linux counterpart) to alert them to your bad practices.

**Comment by brjsp** [comment]
FWIW the repo history seems to be preserved by github here: https://github.com/bitwarden/clients/actions/workflows/version-auto-bump.yml

**Comment by Krychaz** [comment]
Hey there!

It was necessary to remove this tag because of how the Download Function was initially designed. We are currently working on new methods to enable the organization to follow best practices with tags.
