### ISSUE TITLE
Edge Bitwarden Extension Can't Login

### ISSUE THREAD

**Issue by Rvn0xsy** [bitwarden/clients#10260]
### Steps To Reproduce

I am using the Edge 126.0.2592.113 version of the browser, with the Bitwarden browser extension installed. I tried to log in to my self-hosted server and found that I could not log in normally.

![image](https://github.com/user-attachments/assets/487577ea-9971-4a68-a685-25bf2d407aa5)

My bitwarden Server version is :

```
root@a4f26485a9b3:/# ./vaultwarden --version
vaultwarden 1.31.0
root@a4f26485a9b3:/#
```

### Expected Result

Subsequently, I installed the Chrome browser and also installed the latest Bitwarden browser extension, and found that it works normally!

I would like to inquire whether there are any differences between the Edge browser extension and the Chrome browser extension (the latest version)?

### Actual Result

Their browser extension release dates are the same, which is very puzzling to me.

The Chrome browser extension works properly, but the Edge browser does not.

### Operating System

Linux

### Web Browser

Microsoft Edge

### Browser Version

126.0.2592.113

### Build Version

 126.0.2592.113

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
It is important to note that vaultwarden (the new name for Bitwarden RS) is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 

https://bitwarden.com/help/install-and-deploy-offline/ 

For help with your vaulwarden installation, please check out the vaultwarden repository - https://github.com/dani-garcia/vaultwarden

I hope you find this helpful. Please do not hesitate to let me know if you have any questions.
