### ISSUE TITLE
Getting master password prompt when trying to use passkey from vault entries without master passwrod re-prompt field set.

### ISSUE THREAD

**Issue by skelder** [bitwarden/clients#10262]
### Steps To Reproduce

1. Go to any website with passkey login
2. select passkey login
3. get prompted to enter master password

### Expected Result

Passkey should be used without needing to enter master password

### Actual Result

Even though the master password re-prompt field is not set, it keeps asking for master password, what is weird is that this only happens with using passkeys. editing the entry does not prompt for master password.

Already tried to set-clear the re-prompt value, reinstall the browser extension, re-sync.

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

128.0.2

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hello @skelder 

Thank you for reaching out, This was fixed in the most recent release of the browser extension and you can find more information here; https://bitwarden.com/help/releasenotes/#2024-7-1

Thank you once again.
