### ISSUE TITLE
Memory leaks still exist in Safari extension

### ISSUE THREAD

**Issue by alexyangjie** [bitwarden/clients#10303]
### Steps To Reproduce

1. Open Safari
2. Login to the Bitwarden extension
3. Go to [https://browserbench.org/Speedometer3.0/](https://browserbench.org/Speedometer3.0/)
4. Run a test, note down the score and the browser memory
5. After the test, go back to the url in step 3
6. Repeat 3-5 a few times

### Expected Result

The browser test scores stays relatively the same across different tests

### Actual Result

In M1 Mac mini, Safari scores 23.6 in the first time, 16.5 in the second time, and 15 in the third time. Every time the test runs, the browser's memory increases significantly.

The Firefox browser extension doesn't have this issue at all and stays around 22.7 points in all the tests. If the Bitwarden Safari extension is uninstalled, the Safari also doesn't have the issue and keeps the scores around 23.5 in all tests.

### Additional Context

This issue was discovered long time ago. There has been some fixes to the Safari memory leak in the past, the most recent one being in the 2024.7.1 release, but the issue still seems to occur. 

### Operating System

macOS

### Operating System Version

14.5

### Web Browser

Safari

### Browser Version

17.5

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there!

Thank you for your report, this should be addressed by: https://github.com/bitwarden/clients/pull/9434 in the 2024.7.1 release

This issue will now be closed.

Thanks!

**Comment by alexyangjie** [comment]
No it isn’t. The version I tested is 2024.7.1, which includes the fix you mentioned, but I am reporting a different issue. There is still some memory leak in the Safari extension.
