### ISSUE TITLE
Firefox extension: Exporting vault when using "Login with Device" fails

### ISSUE THREAD

**Issue by Tipoff4317** [bitwarden/clients#10305]
### Steps To Reproduce

1. "Login with Device"
2. Settings -> Vault -> Export vault -> .json, Submit
3. Enter master password

### Expected Result

Dialog box pops up asking to select a file to save to.

### Actual Result

Got an popup error message at the bottom of the sidebar:
Error: Invalid master password

### Additional Context

When logging in with the master password, the export vault works fine.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

128.0esr

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Tipoff4317** [comment]
This has apparently been fixed in 2024.7.1.

Probably related to:

https://github.com/bitwarden/clients/issues/9016

And fixed by:

https://github.com/bitwarden/clients/pull/9523
