### ISSUE TITLE
When opening the account settings menu with no vault timeout action set, a warning will display each time regardless if it was last dismissed

### ISSUE THREAD

**Issue by rthfhgyhy567** [bitwarden/clients#10322]
### Steps To Reproduce

When opening the account settings menu with no vault timeout action set, a warning will display each time regardless if it was last dismissed

### Expected Result

Account settings menu should open without interruptions after the warning was previously dismissed.  I don't know if this is intentional or not but if it is, it is unnecessary to warn users EVERY time about this.

### Actual Result

When opening the account settings menu with no vault timeout action set, a warning will display each time regardless if it was last dismissed.

### Screenshots or Videos

https://imgur.com/a/NvTXRBE

![image](https://github.com/user-attachments/assets/376879e0-4b23-4cb4-94e2-e31d17d51b0b)

### Operating System

Windows

### Operating System Version

Windows 10 Pro

### Web Browser

Firefox

### Browser Version

128.0b9 (64-bit)

### Build Version

2024.6.3

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi there,

Your issue appears to be describing the intended behaviour of the software. If you want this to be changed, it would be a feature request.
As setting it to never, isn't a secure option.

**Comment by rthfhgyhy567** [comment]
Take a closer look at the video.  How can you tell me that a pop up is supposed to display every single time I visit the settings page, and pressing "yes" causes the pop up to just refresh, instead of close.

I know about the security vulnerability, and it is not a big deal to me.  My browser's profile folder is encrypted with EFS and I have a windows password.  Unless someone breaks in my house and points a gun at me and demands that I give them my passwords, there is no reasonable way for my vault to get stolen.  I definitely will be reposting this as a feature request, thank you for wasting my time.
