### ISSUE TITLE
NPM ARM Rocky linux 9

### ISSUE THREAD

**Issue by InSelfControll** [bitwarden/clients#10356]
### Steps To Reproduce

git clone https://github.com/bitwarden/cli.git
cd cli
npm install
npm run build

### Expected Result

Installed successfully and can use it

### Actual Result

# npm audit report

dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available
node_modules/dicer
  busboy  <=0.3.1
  Depends on vulnerable versions of dicer
  node_modules/busboy
    multer  <=2.0.0-rc.3
    Depends on vulnerable versions of busboy
    node_modules/multer
      @koa/multer  *
      Depends on vulnerable versions of multer
      node_modules/@koa/multer

pkg  *
Severity: moderate
Pkg Local Privilege Escalation - https://github.com/advisories/GHSA-22r3-9w55-cj54
No fix available
node_modules/pkg

5 vulnerabilities (1 moderate, 4 high)

Some issues need review, and may require choosing
a different dependency.
[error-report.txt](https://github.com/user-attachments/files/16450694/error-report.txt)

### Operating System

Linux

### Operating System Version

Rocky Linux 9.4 (Blue Onyx)

### Shell

Bash

### Build Version

Can't compile

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by quexten** [comment]
Hi @InSelfControll ,

in your reproduction steps you clone the `bitwarden/cli` repo. That repo
is deprecated and not used anymore. The correct repo is `bitwarden/clients`, and the build is done in the `apps/cli` directory. That being said, the current build scripts to not support arm64. However, with this PR: https://github.com/bitwarden/clients/pull/7338 it might work.
