### ISSUE TITLE
Missing passwords when importing a NordPass CSV

### ISSUE THREAD

**Issue by 1Adri1** [bitwarden/clients#10363]
### Steps To Reproduce

1. Import NordPass CSV
Example file with empty username field (csv):
```csv
name,url,additional_urls,username,password,note,cardholdername,cardnumber,cvc,expirydate,zipcode,folder,full_name,phone_number,email,address1,address2,city,country,state,type,custom_fields
Password of app,https://google.com,,,testtest,,,,,,,,,,,,,,,,password
```

### Expected Result

Password should be imported.

### Actual Result

No import of the passwords with an empty username field.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @1Adri1, thank you for the report.

I've been able to reproduce this.

I just had a brief look at this: There have been new columns (as example: `additonal_urls`) added but they don't shift the csv, so that's not the issue. The issue is the detection of the type in: https://github.com/bitwarden/clients/blob/95e813f2385c618d084f37df4e9bf9147b057155/libs/importer/src/importers/nordpass-csv-importer.ts#L109

As the username is empty it doesn't set the type to login and does not import those fields. Maybe it should fallback/default to LoginType.

**Comment by FlorianLang06** [comment]
Hi,

I would like to try to fix this.

**Comment by FlorianLang06** [comment]
@djsmith85 I am not sure if its the best way to use Login as fallback value. When it is not a login after all a empty record gets imported. My idea was to check if username or password is not null or whitespace. What do you think about this idea?

**Comment by FlorianLang06** [comment]
I would also like to add the additonal_urls in the code. Is it right that I do this in a separate PR? I can I make this PR without a issue or should I create a issue about this topic before?

Sorry for this many questions but I am new in Contribution to open source projects.

**Comment by djsmith85** [comment]
> @djsmith85 I am not sure if its the best way to use Login as fallback value. When it is not a login after all a empty record gets imported. My idea was to check if username or password is not null or whitespace. What do you think about this idea?

@FlorianLang06: Probably best to start with a Login type and then change if needed.

Some other importers start with calling `initLoginCipher()`which would enable you to remove the check for username within `NordPassCsvImport.evaluateType()`. Checking for `record.note` to set it to a Secure Note is not great as a note can be included on all ItemTypes. You could remove their too and then use `convertToNoteIfNeeded()` before pushing the cipher into the result.

**Comment by djsmith85** [comment]
> I would also like to add the additonal_urls in the code. Is it right that I do this in a separate PR? I can I make this PR without a issue or should I create a issue about this topic before?
> 
> Sorry for this many questions but I am new in Contribution to open source projects.

I think you can include the import of `addional_urls` within the same PR, I would just see if you could add it with a separate commit, which makes it easier to review. Adding/extending the unit-tests would be nice.

**Comment by djsmith85** [comment]
> > > @djsmith85 I am not sure if its the best way to use Login as fallback value. When it is not a login after all a empty record gets imported. My idea was to check if username or password is not null or whitespace. What do you think about this idea?
> > 
> > 
> > @FlorianLang06: Probably best to start with a Login type and then change if needed.
> > Some other importers start with calling `initLoginCipher()`which would enable you to remove the check for username within `NordPassCsvImport.evaluateType()`. Checking for `record.note` to set it to a Secure Note is not great as a note can be included on all ItemTypes. You could remove their too and then use `convertToNoteIfNeeded()` before pushing the cipher into the result.
> 
> I found a much better solution. The CSV file has a "type" column

That sounds way better! I should've checked the file again as it seems to have more data/columns than before.

Looking forward to see a PR 😁

**Comment by FlorianLang06** [comment]
[nordpass_2024-08-12 21_17_24.csv](https://github.com/user-attachments/files/16591040/nordpass_2024-08-12.21_17_24.csv)

I created an account to test this. Look into this. If you have other adjustments please let me know

**Comment by FlorianLang06** [comment]
@djsmith85 I also implemented custom_fields. Is it correct that I used processKvp from the base-importer for that? Now I try to adjust the tests
