### ISSUE TITLE
When self-hosted server is down, bitwarden browser extension blank 

### ISSUE THREAD

**Issue by Salvora** [bitwarden/clients#10439]
### Steps To Reproduce

1. Setup a self hosted server
2. Setup the browser extension and connect to your self hosted server
3. Setup the browser extension (Remember password, do not lock) and sync 
4. Shut down the server
5. Wait an hour (approximately, I could not pinpoint the exact timing maybe 2 hours, maybe restarting pc might help, maybe a token has to expire or smth here.)
6. Click the browser extension icon to open up the UI
7. Result: Blank until it times out (approx 78 secs.)

### Expected Result

it should use the local backup of vault while trying to connect the server on the background instead of showing a blank UI.

### Actual Result

Shows a blank page and you have to wait it out for it to fallback to local vault without clicking anything since clicking anything closes the UI and you have to start all over again.

### Screenshots or Videos

Imagine this with blank screen

![image](https://github.com/user-attachments/assets/855109e4-46ff-4b05-8c1d-224a35ce5a00)

### Additional Context

I am not sure what is the timeout and retry settings are for the extension, however, this behavior is recent (maybe 6 months), I am not sure when the change for this got implemented though. Before, I used to be able to access the already synced content even when the server is down.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome, Microsoft Edge, Firefox, Brave

### Browser Version

Firefox 129

### Build Version

Version: 2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dercalli99** [comment]
Hello, 

i´ve got same problem here! I´m using VPN to sync with server.

- after booting it´s possible to login to bitwarden
- without connected VPN blank page appears directly after login. Auto fillup works.
- with VPN connection bitwarden works like a charm.
- after cutting VPN connection round about 30 minutes later also only blank page appears.

Approximately a half year ago everything was fine. 

**Operating System**
Windows

**Operating System Version**
11

**Web Browser**
Chrome

**Browser Version**
Version 127.0.6533.99 (Offizieller Build) (64-Bit)

**Screenshot**
![image_476](https://github.com/user-attachments/assets/e89da63b-090c-4bce-b9f3-e543c8a05102)

**Comment by diablade** [comment]
i have also a probleme like that, on the plugin chrome, linked to my private instance server, but it was offline.
 and the plugin show a lot of errors non stop about couldn't fetch, timeout, again and again , it slows down a lot, but it finally come to display any saved profils after 20seconds, I couldn't login with passkey for exemple, it was too slow.
 it should stop fetching and let plugin working offline
