### ISSUE TITLE
"Show auto-fill menu on form fields" settings resets randomly to "on focus"

### ISSUE THREAD

**Issue by jheuel** [bitwarden/clients#10443]
### Steps To Reproduce

1. Open browser plugin Settings
2. Open "Auto-fill" page
3. Change "Show auto-fill menu on form fields" to only show on click of the button
4. Observe it resetting after browser restart or update

### Expected Result

Setting does not reset

### Actual Result

Setting resets to the default value

### Operating System

macOS

### Operating System Version

14.6.1

### Web Browser

Safari

### Browser Version

Version 17.6 (19618.3.11.11.5)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: [https://bitwarden.com/help/data-storage/#on-your-local-machine](https://bitwarden.com/help/article/data-storage/#on-your-local-machine)

Let me know if that helps.

**Comment by jheuel** [comment]
I followed your instructions and that seems to have done the trick. Thanks!
