### ISSUE TITLE
Biometrics won't work, Thorium MacOS (Chromium Based)

### ISSUE THREAD

**Issue by fluffeuk** [bitwarden/clients#10456]
### Steps To Reproduce

1. Go to Bitwarden Desktop Application for MacOS
2. Check the "Allow Browser Integration" option
3. Open Browser extension (using Thorium Browser)
4. Click on "Unlock with Biometrics" in settings

### Expected Result

Unlocking with biometrics should be enabled.

### Actual Result

Error message "**Browser integration is not set up** Browser integration is not set up in the Bitwarden desktop application. Please set it up in the settings within the desktop application." Despite browser integration being on.

### Screenshots or Videos

<img width="338" alt="image" src="https://github.com/user-attachments/assets/303277e2-f892-4804-b10b-b47d60e63b12">

### Operating System

macOS

### Operating System Version

14.3.1 

### Web Browser

Chrome

### Browser Version

Thorium 124.0.6367.218

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.
