### ISSUE TITLE
Vault timeout settings are not remembered

### ISSUE THREAD

**Issue by warwickmm** [bitwarden/clients#10468]
### Steps To Reproduce

1. Set vault timeout settings to "5 minutes" and "Log out".
2. Wait for some amount of time until you need to log into the extension again.
3. Log into the extension again.
4. The vault timeout settings are reverted to "On browser restart" and "Lock".

### Expected Result

The vault timeout settings should be remembered.

### Actual Result

The vault timeout settings keep reverting to "On browser restart" and "Lock".

### Operating System

Linux

### Operating System Version

6.10.2-arch1-1

### Web Browser

Brave

### Browser Version

Version 1.68.128 Chromium: 127.0.6533.73 (Official Build) (64-bit)

### Build Version

Version: 2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by barbaranelson** [comment]
I am seeing the same issue, using chrome browser extension on a Mac. This is a recent change (probably in the last week or two). I used to set the vault timeout to 4 hours, and the vault timeout action to log out. Now it keeps resetting it to vault timeout on browser restart, and vault timeout action to lock.

**Comment by barbaranelson** [comment]
This is still happening in the Chrome browser extension version 2024.7.1.  I do not see this problem in the BitWarden application on my mac.  The app preserves my app settings (logout after 4 hours) but the Chrome browser extension on the same mac keeps resetting to lock on browser restart.
