### ISSUE TITLE
CWE-316: Cleartext Storage of Sensitive Information in Memory

### ISSUE THREAD

**Issue by strausmann** [bitwarden/clients#10477]
### Steps To Reproduce

Has this security problem at Bitwarden already been fixed? If not, when will it be fixed?

https://cwe.mitre.org/data/definitions/316.html

### Expected Result

See link https://cwe.mitre.org/data/definitions/316.html

### Actual Result

See link https://cwe.mitre.org/data/definitions/316.html

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by strausmann** [comment]
https://www.heise.de/news/Schwere-Luecke-bei-kritischen-Anwendungen-Klartextpasswoerter-im-Prozessspeicher-9830774.html

**Comment by NovaSilentium** [comment]
Hi there, 

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by simonhir** [comment]
For context extracted the information regarding BitWarden from [the source article](https://www.secuvera.de/blog/studie-klartextpassworter-in-passwortspeichern/) for the above mentioned heise article:

(translated from german)
"
Susceptible to CWE-316: Yes
Information read from the memory: MasterkeySecurity Hint (Hint in case you have forgotten your master password. Should only be sent to the user by e-mail).
"

The article also points out that BitWarden has already been contacted directly.

**Comment by aeoneros** [comment]
@NovaSilentium They also Say that Bitwarden was informed about this problem CWE-316
Have you got informations about a new patch coming soon?

**Comment by JohannesK71083** [comment]
I'm wondering why the master password hint is/can be loaded at all because it [should only be sent per mail](https://bitwarden.com/help/forgot-master-password/) by the server if you forget it and you can only change it in the web-app (as far as I know).
So the real security question is why the application can load it at all.

**Comment by player637204** [comment]
"CWE-316: Cleartext Storage of Sensitive Information in Memory": https://cwe.mitre.org/data/definitions/316.html.

I have contacted Bitwarden Support.

The answer:

"Regarding the findings mentioned in this article about the "MasterkeySecurity Hint," we acknowledge the importance of addressing potential security vulnerabilities promptly and transparently. 
**To address the issue directly, we have decided to remove the hint feature from our clients altogether to avoid any associated risks. Additionally, we are enhancing other security measures that come into play when the vault is locked.**

In the meantime, we recommend that users concerned about their master password hint being compromised on a compromised device configure their vault timeout action to log out. This precaution helps mitigate risks associated with unauthorized access. For more details, please refer to our help documentation on vault timeout settings: https://bitwarden.com/help/vault-timeout/#vault-timeout-action"
