### ISSUE TITLE
Bitwarden Firefox add-on does not sort items by last usage

### ISSUE THREAD

**Issue by vscodesyncsettings** [bitwarden/clients#10475]
### Steps To Reproduce

I have multiple google accounts, so I am giving this example, but it happens with all sites
1. Open Firefox
2. go to any google sign in page
3. click on Bitwarden extension on top right

### Expected Result

Bitwarden extension should display a list of my google logins in the order of last usage, i.e., last used item on top

### Actual Result

Items are always displayed in a fixed order. They are not in alphabetical order either. Not sure what order they are but every time I try this, they are in that same order.

### Additional Context

By the way, this issue occurs only on this particular PC. I have no issue on the same setup on another PC.
Following are the troubleshooting steps that I tried.
1. Uninstalled and reinstalled Bitwarden extension
2. Uninstalled and reinstalled Firefox, and then reinstalled Bitwarden extension

### Operating System

Windows

### Operating System Version

Windows 10 Enterprise

### Web Browser

Firefox

### Browser Version

129.0 (64-bit)

### Build Version

Version: 2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @vscodesyncsettings,

Thank you for this report. How do you perform [autofill](https://bitwarden.com/help/auto-fill-browser/) in this particular environment? Via the extension's pop-up, inline autofill, keyboard shortcut, etc.


Thank you in advance,

**Comment by vscodesyncsettings** [comment]
> Hi @vscodesyncsettings,
> 
> Thank you for this report. How do you perform [autofill](https://bitwarden.com/help/auto-fill-browser/) in this particular environment? Via the extension's pop-up, inline autofill, keyboard shortcut, etc.
> 
> Thank you in advance,

Hi @SergeantConfused ,

Thank you for responding. I click on Bitwarden addon icon on top right part of Firefox (on the right side of the address bar where all my addons show up). I don't use autofill or inline fill.

**Comment by vscodesyncsettings** [comment]
> I use the CTRL+SHIFT+L keyboard (firefox linux)
> 
> This seems like a recent regression, perhaps on the last couple of weeks.

Do you face the same issue as well?

**Comment by njkeever** [comment]
I have the same issue. It renders the Ctrl+Shift+L keyboard shortcut useless on site with multiple logins. On Chrome,  you can fill the username you want, then kit the shortcut to fill the password of the last used login. In Firefox this fills the password of whatever login is listed first instead, which doesn't always match the username filled.

**Comment by danialasghar** [comment]
Firefox 130, latest extension. Also having the same issue, Bitwarden does not remember the last used login for a domain and only autofills the topmost login. (i invoke it using the keyboard shortcut)

**Comment by siteleas** [comment]
Same problem here, and quite frankly the list should be sorted in every display of the list of applicable passwords for the current site (not just with the last used at the top but) with all passwords sorted by usage history (popular use) -- rarely used passwords should be listed at the bottom of the list that appears. Also, would be nice to favorite passwords and have them appear at the very top of the list of results for the current site or another tab for favorites that only shows favorites for the current site (and then below a divider a list of other favorites in most recent used sequence).
