### ISSUE TITLE
⚠️ Flatpak Unverified Package ⚠️

### ISSUE THREAD

**Issue by Ironfist69** [bitwarden/clients#10497]
### Steps To Reproduce

1. Go to Flathub
2. Search for Bitwarden
3. Click on it
4. It will show package is unverified (Linux Mint)

### Expected Result

Flatpak package should be verified

### Actual Result

Unverified package

### Screenshots or Videos

![Screenshot from 2024-08-13 11-53-54](https://github.com/user-attachments/assets/726933bb-6849-40fc-aab1-de93b4ab4182)

### Operating System

Linux

### Operating System Version

Linux Mint 22 Cinnamon

### Installation method

Other

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi, 

The flatpak client is maintained by the community, not Bitwarden. We suggest you use the official .AppImage installer from the Bitwarden website as an alternative if the community maintained is failing: https://bitwarden.com/download/

**Comment by Ironfist69** [comment]
@Greenderella

But it says **"by Bitwarden Inc."**

![Screenshot from 2024-08-13 15-45-26](https://github.com/user-attachments/assets/3bf9577c-6200-4183-aad5-6f2bd517f499)

**Comment by djsmith85** [comment]
Linking to https://github.com/bitwarden/clients/issues/6795
