### ISSUE TITLE
Bitwarden takes a long time to start

### ISSUE THREAD

**Issue by RONOT693** [bitwarden/clients#10552]
### Steps To Reproduce

4. Click on '...'

### Expected Result

I use Bitwarden on my new iMac (Sonoma 14.6.1). I have the icon in the dock, click it, and from there it should open immediately.

### Actual Result

I use Bitwarden on my new iMac (Sonoma 14.6.1). I have the icon in the dock, click it, and from there it takes about 40 seconds for the app to start. During that period the computer cannot be used. Once started, Bitwarden functions without problem.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

24.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @RONOT693,

Thank you for reporting this. I tested this on macOS 14.6.1 with Bitwarden 2024.7.1 (.dmg) and the Bitwarden desktop client launched within ~2 seconds. I'd recommend checking if a fresh new installation helps; Please uninstall that Bitwarden desktop client, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the machine, and install it anew and test that once more; Please also consider installing it from the [Mac App Store](https://itunes.apple.com/app/bitwarden/id1352778147).

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
