### ISSUE TITLE
No UI response when unlocking vault, while opening the app in a seperate monitor

### ISSUE THREAD

**Issue by nathanwang16** [bitwarden/clients#10629]
### Steps To Reproduce

1. Use Lunar or other monitor control app. Put your workspaces to the external monitor and shut the macbook lids. 
2. open the Bitwarden app as usual.
3. enter the correct master password
4. Click on 'Unlock'

### Expected Result

The vault should be unlocked, or a error message should display

### Actual Result

UI showed no change

### Additional Context

There is no issue opening vaults when i only use macbook and not the external monitor

### Operating System

macOS

### Operating System Version

14.5

### Installation method

Mac App Store

### Build Version

Version 2024.7.1 (27455)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @nathanwang16 

I attempted to reproduce what you have described and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

Thanks!
