### ISSUE TITLE
[FEATURE REQUEST] No way to filter matching Tab items

### ISSUE THREAD

**Issue by luckman212** [bitwarden/clients#1065]
Bitwarden 1.46.1
Chrome 85.0.4183.102

I have a few sites where I have a lot of saved logins that match the tab (sometimes 20+ matches). Since BW sorts logins by last use instead of by name, it is tedious to hunt for the right login in the list. 

I'd like to be able to filter the list from the tab matches using the search field at the top, but that (counterintuitively) switches you to the "My Vault" tab as soon as you start typing in it. Then, there is no way to action that item and cause BW to autofill - it just opens the editor panel.

![image](https://user-images.githubusercontent.com/1992842/69241009-bf78e980-0b6b-11ea-9750-ca82308f291e.png)

**Comment by PinkDev1** [comment]
I suggest you add "[FEATURE REQUEST]" at the beginning of the title.
Also, this is a good idea, but I think there's an easier work-around for this.

(In the browser extension)If you go to your vault, select an account and scroll down to the URI section, you'll be able to see a little engine on the right that you can click to enable a list of Diferent "detection engines". I suggest you tinker with that until you get the most convenient experience possible.

**Comment by bilogic** [comment]
@PinkDev1 can give an example of what you mean? I need to switch between like 20 different google accounts.. the problem i believe @luckman212 is facing is that he needs to manually scroll around to find the account every time. Having a text input to type and filter only the 1 account he needs to click is much easier. The text input is already there, but after some text is entered, the list's behavior changes; clicking on a filter entry launches that link instead of applying it to the current page

**Comment by luckman212** [comment]
@bilogic is correct - the problem isn't solvable by changing the match algorithm. This is for a case where we have dozens of logins for the same root domain (common ones could be google, microsoft, godaddy etc)

**Comment by luckman212** [comment]
@clayadams5226 Any chance this request will be brought under consideration? E.g. I currently have close to 40 logins for Microsoft 365 stored in BW for accounts that I manage. Scrolling through the non-alphabetized list to find the right one is becoming really tedious. It's almost faster now to switch over to the Vault tab, use the search filter, copy&paste the username, then repeat the process again and copy&paste the password.

**Comment by tgreer-bw** [comment]
@luckman212 - we have this on our backlog and on our community forums here: https://community.bitwarden.com/t/autofill-after-search/2808/39

Thanks!

**Comment by djsmith85** [comment]
Closing this as the discussion can continue and progress can be monitored on the existing [feature request topic](https://community.bitwarden.com/t/autofill-after-search/2808)
