### ISSUE TITLE
Skip unhandled item types while importing ProtonPass

### ISSUE THREAD

**Issue by rsb-23** [bitwarden/clients#10654]
### Steps To Reproduce

1. Go to 'Import from Proton(zip/json)'
2. Upload `proton.json` file with alias items.
3. Click on 'Import Data' button.

### Expected Result

Unhandled item types shouldn't be added as a blank entry to the vault.
Skip `alias` and `identity` items if it is not handled, and show skipped items count at last.

### Actual Result

Getting item entry with just item name and without any username or email address.
This is of no use and also user mistakes it for successful import.

### Additional Context

Fix Suggestions:
1. Add default clause to [this switch case](https://github.com/bitwarden/clients/blob/cfdc52ee84a5144a36bdc7d8deae45f7b353ce62/libs/importer/src/importers/protonpass/protonpass-json-importer.ts#L48)
```ts
default:
   continue
```
2. Also handle `identity` item type.

### Operating System

Windows

### Web Browser

Brave

### Build Version

na

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by rsb-23** [comment]
Has #10471 changes been deployed to web and other clients? 
Currently, some usernames are blank after import.  

I don't have anymore details as of now, let me know if I can help with anything.

Additionally : 
Incase if the team plans to add `identity`, here is the type
```
export type ProtonPassIdentityContent = {
fullName:string,email:string,phoneNumber:string,firstName:string,middleName:string,lastName:string,birthdate:string,gender:string,extraPersonalDetails:string[],
organization:string,streetAddress:string,zipOrPostalCode:string,city:string,stateOrProvince:string,countryOrRegion:string,floor:string,county:string,extraAddressDetails:string[],
socialSecurityNumber:string,passportNumber:string,licenseNumber:string,website:string,xHandle:string,secondPhoneNumber:string,linkedin:string,reddit:string,facebook:string,yahoo:string,instagram:string,extraContactDetails:string[],
company:string,jobTitle:string,personalWebsite:string,workPhoneNumber:string,workEmail:string,extraWorkDetails:string[],
extraSections:string[]
};
```

**Comment by djsmith85** [comment]
Hi @rsb-23, and thank you for your report. 

The changes #10471 you mention have not been released yet. They will be included in the next release.

I've added this ticket to my team's backlog, but I'm also marking it as a `good first issue`, in case anyone would like to take a stab at skipping unmapped/unsupported items and/or mapping aliases and identities.

Kind regards,
Daniel
