### ISSUE TITLE
When logging into my bitwarden account in the browser plugin, it refreshes the system, I cannot log in

### ISSUE THREAD

**Issue by hureyre** [bitwarden/clients#10669]
### Steps To Reproduce

The big problem is this: I installed the add-on in the browser. When I try to log in from the add-on drawer, it refreshes every few seconds. As if the F5 key was pressed. But it's not the tab that is refreshed. Sometimes the desktop is completely refreshed. Sometimes only the browser application is refreshed. Every time it refreshes, the text I copied to ram is deleted (for example, my bitwarden account password that I copied from keepassxc). Also, since it is refreshed, the drawer disappears, and I have to try to log in from the beginning. I can never log in. How did I discover that the problem was caused by the bitwarden add-on? I right-clicked on the add-on and clicked Inspect pop-up. The inspect pop-up screen was open. Then I tried to log in, and it was successful. It did not refresh the browser while the "Inspect pop-up" screen was open. It did not refresh the desktop.

I haven't tried it on other browsers.

### Expected Result

I don't want the Bitwarden extension to refresh the browser and refresh the desktop.
I want the Bitwarden extensions drawer to be fixed on the login screen.

### Actual Result

Bitwarden is refreshing the desktop and browser.

### Additional Context

I am a Nobara 40 OS user based on Fedora 40. The browser is Brave, version 1.68.141 .

I installed the browser plugin from the chrome store. The plugin login panel did not appear on the left side of the screen. It was supposed to make logging in easier, but it didn't. I right clicked and tried to open it on the left of the screen, there was no such option. I checked if there was such an option in the plugin settings, there was no such feature. I couldn't get bitwarden to work on the left side of the screen. The reason I ask for this is that when I paste the username into the plugin on the top right, copy the password from the keepaaxc app and click on brave or the bitwarden plugin in brave, the plugin drawer closes and I have a hard time logging in. Even if I saved the bitwarden account email, copied the password beforehand, then pasted it into the plugin in the browser, I have to click on keepassxc again to see the totp value. I copied the bitwarden account password from the keepassxc desktop app. I clicked on the browser plugin (top right). I tried to log in, entered the account email, clicked next, clicked paste. The reason I want this is because when I paste the username to the plugin on the top right, copy the password from the keepassxc application and click on brave or the bitwarden plugin in brave, the plugin drawer closes, and I have difficulty logging in. Even if I save the bitwarden account email, copy the password beforehand, and then paste it into the plugin in the browser, I have to click keepassxc again to see the totp value, so the bitwarden drawer in the browser closes again, and I have to start over. To prevent this, I need to move the bitwarden plugin login page to the left of the screen or I need to be able to pin the bitwarden plugin drawer. The pinning feature is possible after logging in. But I cannot pin the drawer before logging in. This was not the problem I described when logging in. This was just a feedback.

### Operating System

Linux

### Operating System Version

Nobara 40

### Web Browser

Brave

### Browser Version

1.68.141 

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
