### ISSUE TITLE
The Synology DSM cannot use Bitwarden Browser as a hardware key.

### ISSUE THREAD

**Issue by bzmshang** [bitwarden/clients#10711]
### Steps To Reproduce

Go to the Synology DSM, open Personal Settings, and select "Add Security Hardware Key".

### Expected Result

The Synology DSM cannot use Bitwarden Browser as a hardware key.

### Actual Result

The Synology DSM cannot use Bitwarden Browser as a hardware key.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/2be1eaaf-8f83-4913-a53c-9279426eed74)

### Additional Context

The Synology DSM cannot use Bitwarden Browser as a hardware key.

### Operating System

Windows

### Operating System Version

22631.4037

### Web Browser

Microsoft Edge

### Browser Version

128.0.2739.42

### Build Version

 2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @bzmshang,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,
