### ISSUE TITLE
Search Vault on All Items doesn't include Secure Note content

### ISSUE THREAD

**Issue by robomac** [bitwarden/clients#10712]
### Steps To Reproduce

1. Create a Secure Note, add unique text
2. Create login (password) item, add same unique text in that note
3. Select All Items on left rail
4. Filter with that unique text
5. Note that only the login item appears

### Expected Result

Both items appear. Secure Notes should be searchable when vault is unlocked.
(Note that the _Name_ can be searched. The contents cannot be.)

### Actual Result

Secure Notes do not show.

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.5.0 (24604)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @robomac,

Thank you for reporting this. I tested this on macOS 14.6.1 with Bitwarden 2024.7.1, and searching for one whole word from a [Secure Note](https://bitwarden.com/help/managing-items/#tab-secure-notes-2VtgLfbwjcMq1V04S1pSIO)'s Notes field yielded a result. The same happened when I had also a Login vault item with that same word in its Notes field; Both vault items were listed, in that case. With that in mind, please consider updating to the latest version of Bitwarden, and please make sure that you're searching for [whole words](https://bitwarden.com/help/searching-vault/#indexed-fields).

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
