### ISSUE TITLE
Windows Install for All user installs in C:/Program instead of C:/Program Files/Bitwarden

### ISSUE THREAD

**Issue by GuillaumeHullin** [bitwarden/clients#10724]
### Steps To Reproduce

1. Clean install of Bitwarden 2024.8.0
2. Install for all users

### Expected Result

Bitwarden should install in Program Files/Bitwarden

### Actual Result

Bitwarden installer create a "Program" folder at the root of C: and deploy its files there

### Additional Context

Running the installer manually (not silently) create the same result.
Version 2024.7.1 does not produce this result and create Bitwarden folder in Program Files.
An upgrade from 2024.7.1 to 2024.8.0, do not have issue.

### Operating System

Windows

### Operating System Version

11

### Installation method

Chocolatey

### Build Version

2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by RokeJulianLockhart** [comment]
The created path is literally `%SystemDrive%/Program` verbatim? Not `Programs` instead? And there's no `Bitwarden` subdirectory inside it?

**Comment by GuillaumeHullin** [comment]
@RokeJulianLockhart correct `%SystemDrive%/Program/Bitwarden.exe`. 
I'm guessing the space in the name "Program Files" was mishandled.
I already "solved" my problem by installing 2024.7.1 and then upgrading.

Now, I'm trying to reproduce the problem (by uninstalling)... but I can't seem to reproduce it.

I was planning to reinstall Windows today anyway... so I will try a clean install of Bitwarden and see if I can reproduce.

**Comment by cbw23** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!

**Comment by RokeJulianLockhart** [comment]
> We use GitHub issues as a place to track bugs and other development related issues.

@cbw23, this could very reasonably be construed to be a bug. It's merely not a reproducible one (yet, hopefully).
