### ISSUE TITLE
Safari extension does not autofill with shortcut and there is no autofill prompt until I click on the extension icon

### ISSUE THREAD

**Issue by lorenzo9uerra** [bitwarden/clients#10765]
### Steps To Reproduce

1. Go to a form to autofill
2. Use the shortcut "cmd+shift+L" to autofill or click on the form in order to get an autofill prompt
3. Notice that the fields are not autofilled and the prompt does not appear
4. Now, click on the extension icon and notice that the fields get autofilled as soon as you click on the browser extension and prompts might briefly appear, like if they were stuck and only opening the app gets them unstuck

### Expected Result

I expect the autofill to work with the shortcut, or to get a prompt for autofill when I click on the text field.

### Actual Result

No autofill is possible unless I clock on the browser icon. I have tried multiple times to restart the browser, the mac and everything is updated.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Safari

### Browser Version

17.6

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dfsnow** [comment]
I can confirm this behavior on the exact same OS/browser/build.

**Comment by cagonzalezcs** [comment]
This is a duplicate issue, please see https://github.com/bitwarden/clients/issues/10715#issuecomment-2310093066
