### ISSUE TITLE
Bitwarden makes forms unusable when there's a select with 20k+ options

### ISSUE THREAD

**Issue by pixlmint** [bitwarden/clients#10789]
### Steps To Reproduce

1. Go to any website that has a select with 20k+ options
2. Click on the select (or any other form element)

### Expected Result

The form element gets focused, it's possible to write in it

### Actual Result

It takes a long time for the website to react

### Additional Context

Forms with that many options will make any website slower, but it's not nearly as bad in firefox, and it only occurs when the Bitwarden in Chrome is enabled.

Here is a simple PHP script that shows the behavior described above. Number of options required to crash the form may vary between devices.

```php
<!DOCTYPE html>
<html>
<body>
<input type="text" >
<select>
<?php
for ($i = 0; $i < 20000; $i++) {
	echo "<option value='$i'>$i</option>\n";
}
?>
</select>
</body>
</html>
```

### Operating System

macOS, Linux

### Web Browser

Chrome

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi,

Just to confirm, is the 20k value in relation to available form options or items within Bitwarden vault that can be autofilled?

**Comment by pixlmint** [comment]
> Just to confirm, is the 20k value in relation to available form options or items within Bitwarden vault that can be autofilled?

@Krychaz It's in relation to the <option> Elements inside the <select> HTML field. So no not fields that can be autofilled.

**Comment by Krychaz** [comment]
Thanks. 

I'm having issues imagining a website that has 20k+ options on a single field. We have done work to improve performance for websites that load big chunks of data however the scenario proposed by you seems to be very unrealistic. 

Would you be able to provide a website with such options and its scenarios? 

Otherwise I will close this issue as it is a scenario where a slowdown is expected with such huge amount of items being loaded.

**Comment by pixlmint** [comment]
It's on an internal site for my company. 

Yes I understand that this is not a priority, just that it works fine in firefox, and doesn't work in Chrome seems strange.
