### ISSUE TITLE
Yubikey is no longer seen by Edge with the Bitwarden Edge extension enabled.

### ISSUE THREAD

**Issue by ProgentCT** [bitwarden/clients#10795]
### Steps To Reproduce

1. Go to 'portal.office.com'
2. Click on 'Sign In Options'
3. Select 'Face, Fingerprint, PIN or securtiy key'

### Expected Result

Use an external security key is expected.

### Actual Result

USB security key is listed.
Selecting USB security key prompts me to turn on bluetooth and Edge does not see my Yubikey.

### Screenshots or Videos

This is what I expect.  If I disable the Bitwarden Edge extension this is what the menu looks like and clicking on external security key allows me to login with my yubikey.
![image](https://github.com/user-attachments/assets/1a47c7b2-6cc9-48ee-872d-3f07c62572c6)

With the Bitwarden Edge extension enabled I get the menu below.  Neither of which option allow me to select my Yubikey.
I opened a case with Microsoft on this already but in testing, found that it is the Edge extension that breaks functionality.
![image](https://github.com/user-attachments/assets/fd3da400-fdf5-4cfa-aae3-dc7dfef8ac08)

### Additional Context

I also removed my yubikeys from my Entra ID accounts and attempted to add them back to my profile.  While the Bitwarden extension is enabled this is impossible.  With the Bitwarden extension disabled it works as expected.

### Operating System

Windows

### Operating System Version

19045.4780

### Web Browser

Microsoft Edge

### Browser Version

128.0.2739.42

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ProgentCT** [comment]
This appears to be fixed.
I removed the Edge extension and reinstalled it.  
The existing version is 2024.8.1 and now prompts me for my yubikey.

**Comment by ProgentCT** [comment]
I'll re-open this if it recurs.

**Comment by clickagree** [comment]
Having this issue on Firefox (MacOS)
