### ISSUE TITLE
Safari Extension -- opening tabs

### ISSUE THREAD

**Issue by seghtree** [bitwarden/clients#10826]
### Steps To Reproduce

4. Click on '...'

### Expected Result

No additional tabs open when I use bitwarden extension in Safari.

### Actual Result

With the currently released Mac OS X bitwarden app, when I try to use the bitwarden safari extension ... random tabs are opened when I try to authenticate.  This is naturally quite scary to me.

Sonoma 14.6.1
MacBookPro 2019

I have scanned for malware but nothing came up.  
It seems to happen only when I try to use the Bitwarden safari extension.
I have seen reports this this type of behavior and the replies seem to suggest that it can be extensions some times.

Q_ Are there any other sightings of this behavior in the field?

Please advise.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Safari

### Browser Version

17.6 (19618.3.11.11.5)

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
Can you show a video of this behavior happening?

**Comment by seghtree** [comment]
After clearing full cache in the browser, looks like the issue might have gone away.
Will continue to monitor and will update here if it returns.  Can move to NotABug.
