### ISSUE TITLE
Broken secrets on create a new or save an existing entry at chrome extension

### ISSUE THREAD

**Issue by StratsScorpio** [bitwarden/clients#10864]
### Steps To Reproduce

1. Simply create or save an entry in the chrome extension
2. The (Linux) desktop client can not load the entry

### Expected Result

See the entry at the desktop client

### Actual Result

See nothing at the desktop client

### Screenshots or Videos

![Bildschirmfoto vom 2024-09-03 18-04-51](https://github.com/user-attachments/assets/f1b09743-980f-4138-8bc3-e6fb59a39859)

### Additional Context

If I go now to the Organization Management console and open and save the entry, the entry is now visible at the desktop client.

### Operating System

Linux

### Operating System Version

Mint 21 / Ubuntu 2404

### Web Browser

Vivaldi

### Browser Version

6.9.3447.37

### Build Version

Browser-Extension: 2024.8.1 / Desktop-App: 1.32.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by StratsScorpio** [comment]
Hi,
I've created today to reproduce it:

- First I've created an entry in the bitwarden app.
- We can also see it in the Manager web interface.
- We can see it in the browser-Extension
- Add then an entry with the browser extension
- We can see it in the Manager web interface
- **We can not see it in the bitwarden app** --- Error!
- We edit it in the Manager web interface
- We can see it in the bitwarden app

![1](https://github.com/user-attachments/assets/74556ec8-8f41-4fc3-b2c2-ba93d52bacf5)
![2](https://github.com/user-attachments/assets/e6758277-c1eb-4aa8-9551-ed2f03d8c699)
![3](https://github.com/user-attachments/assets/22bbb20a-3148-4e4f-85c3-77f9be126ff3)
![4](https://github.com/user-attachments/assets/87d2cef3-0fbe-4af4-b7b2-eb03e5f33b2c)
![5](https://github.com/user-attachments/assets/419315e6-641c-4326-9649-bffae90ce9a6)
![6](https://github.com/user-attachments/assets/fef2f49c-d1c0-4abf-9ee7-1dec4c54abe1)
![7](https://github.com/user-attachments/assets/a341f6bf-5690-437b-b591-b57dc86d5802)
![8](https://github.com/user-attachments/assets/801b7bb0-fb7b-473b-8343-37ce45e9ffb9)
![9](https://github.com/user-attachments/assets/7119dd8d-5e51-4b6f-b5bb-9010b7302dca)
![a](https://github.com/user-attachments/assets/9fdd4a5d-794a-4271-bff7-df83f6d321bd)
![b](https://github.com/user-attachments/assets/8d28f443-10f2-43e5-bd2b-d2116dd20afd)

**Comment by StratsScorpio** [comment]
Ok, after testing a few - it seems not a problem with the chrome extension - it's a problem with Linux client. Windows clients 2024.8.1 can read this. But my Linux client update takes me to site, which delivers 2022.6.12 version. This version is also not working. It's not a chrome extension problem, it's linux client problem.

**Comment by StratsScorpio** [comment]
Yeah: 
2022: search for new releases: https://github.com/bitwarden/desktop/releases
2024: search for new releases: https://github.com/bitwarden/clients/releases
