### ISSUE TITLE
Autofill multi-line street address mishandled

### ISSUE THREAD

**Issue by mheins57** [bitwarden/clients#10863]
### Steps To Reproduce

1. In your vault, create a test identity with more than one line for the street address.  In my case, I used the following address:
123 Main St
(top floor)
Draper, UT, 84020
US
3. In browser, navigate to a page with a name and address form which supports a second line of street address.  Fill in the address info from the test identity and observe the results.

### Expected Result

The first line of street address on the form should receive the first line of street address in the test identity, e.g. "123 Main St"
The second line of street address on the form should receive the second line in the identity, e.g. "(top floor)"

### Actual Result

Both street address lines on the form receive the same concatenation of the two address lines in the identity, e.g.:

123 Main St (top floor)
123 Main St (top floor)

which is incorrect.

### Screenshots or Videos

![Bitwarden-bug1](https://github.com/user-attachments/assets/f56f9d20-44ce-4729-be27-0c5d72c37e6e)

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1 (23G93)

### Web Browser

Chrome

### Browser Version

128.0.6613.114 (Official Build) (arm64)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
