### ISSUE TITLE
Chrome extension says biometrics not enabled in desktop application when it is.

### ISSUE THREAD

**Issue by daxliniere** [bitwarden/clients#10889]
### Steps To Reproduce

Install desktop and browser extension.

### Expected Result

Browser integration enabled in desktop app, but Chrome extension says it is disabled.

### Actual Result

![image](https://github.com/user-attachments/assets/91f094d6-e358-4cf9-bb9e-7c8de4941409)

### Operating System

Windows

### Operating System Version

Win10x64 Pro N

### Web Browser

Chrome

### Browser Version

128.0.6613.114 (Official Build) (64-bit)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AdeSills** [comment]
I am having this same problem with the chrome extension since this morning, it was fine yesterday. Also the extension locking every time the browser closes when I have set it not to because no one else ever uses my laptop

**Comment by AdeSills** [comment]
I have just solved the problem by uninstalling and reinstalling the browser extension. No idea what was wrong.
