### ISSUE TITLE
Logged out of Chrome plugin on MacOS even though I've been active the whole time

### ISSUE THREAD

**Issue by srasku** [bitwarden/clients#10938]
### Steps To Reproduce

1. Set timeout to 5 minutes
2. Pop out plugin to it's own window
3. Work for 5 minutes or more

### Expected Result

I should remain logged in.  According to [this comment](https://github.com/bitwarden/clients/issues/8465#issuecomment-2021645994) the plugin should never log me out if the window is popped out.  In any case, if I'm active over the timeout period it shouldn't log me out at all regardless of whether the window is popped out or not.

### Actual Result

I am logged out.

### Additional Context

Chrome Plugin on MacOS on M1 MacBook.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1 (23G93)

### Web Browser

Chrome

### Browser Version

128.0.6613.120 (Official Build) (arm64)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @srasku,

Thank you for your report. I was able to reproduce this and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by coroiu** [comment]
Likely related to https://github.com/bitwarden/clients/pull/11344 - double checking if this is fixed now

**Comment by coroiu** [comment]
Confirmed that this was fixed by #11344, closing issue!
