### ISSUE TITLE
Unable to Import When Selected Non-Primary Vault

### ISSUE THREAD

**Issue by sarvesh4396** [bitwarden/clients#10937]
### Steps To Reproduce

When attempting to import credentials into a non-primary vault using the web import tool, the import fails without a clear error message. The issue occurs specifically when a vault other than the primary one is selected as the target for the import.

1. Open the Bitwarden web vault and navigate to the import data tool.
2. Select a vault (mandatory) other than the primary vault (e.g., an organization or shared vault).
3. Upload a CSV file for import.
4. Attempt to complete the import process.

### Expected Result

The import should successfully add the credentials to the selected non-primary vault without issues.

### Actual Result

The import fails with this message
![image](https://github.com/user-attachments/assets/7f3c7377-10d2-4362-b423-7b778b853e81)

### Additional Context

- The issue does not occur when importing into the primary vault.
- No specific error messages are provided, making troubleshooting difficult.
- CSV file format was validated and confirmed to be correct.

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

Version 128.0.6613.120 (Official Build) (64-bit)

### Build Version

Could not find it at the bottom, but the mobile version is the latest 2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @sarvesh4396,

The error states that the file contains items that are not assigned to a collection. This is a requirement for non-admin members of an organization.

More information can be found on Bitwarden's help site: https://bitwarden.com/help/import-data/#file-contains-unassigned-items

Closing this now, as this is expected behavior.

Kind regards,
Daniel
