### ISSUE TITLE
Bitwarden can't match my Password entry for Custom domains

### ISSUE THREAD

**Issue by QbikEdge** [bitwarden/clients#10942]
### Steps To Reproduce

I am on windows an added custom domain for an Local-IP 
1. Create a local custom domain for any Local-IP i did that in hosts file in `C:\Windows\System32\drivers\etc`
   - example: 192.168.1.5 portainer

2. <details> <summary>create a authentication entry for that custom domain we created: </summary> 
    
    ![image](https://github.com/user-attachments/assets/d3ed55d5-59ec-4ff0-8e3e-ff6d25927744)
  </details>

3. try to get the entry to show up 
4. <details> <summary>it does not show up: </summary> 

    ![image](https://github.com/user-attachments/assets/f3fafc16-7011-4564-9493-895d6e7772b6)
  </details>

### Expected Result

It should match my entry with the custom domain, but it shows that there is no entry for this website.

### Actual Result

It does not match my entry for the custom domain:

![image](https://github.com/user-attachments/assets/a570a3cc-b2a9-423e-9d72-df402acfae10)

### Operating System

Windows

### Operating System Version

win10 22h2

### Web Browser

Brave

### Build Version

Version 1.69.162 Chromium: 128.0.6613.120 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Please try switching match detection for that item to host as seen below. 

<img width="385" alt="SCR-20240909-lfiz" src="https://github.com/user-attachments/assets/00d65087-a07d-4d03-b0f9-3fc06237a779">
