### ISSUE TITLE
Receiving error "Unable to autofill selected item..." on Firefox

### ISSUE THREAD

**Issue by WrichikBasu** [bitwarden/clients#10950]
### Steps To Reproduce

1. Go to any website's login page where you have a password saved, ensuring the URI matches.
2. Click on the extension icon; the extension shows that a login is available for that website.
3. Click on that login, and enter the master password again if required.

### Expected Result

The username/email and password should autofill on the respective fields on the webpage.

### Actual Result

1. Error shown: `Unable to autofill the selected item on this page...`
2. Happens irrespective of whether the login has master password confirmation turned on.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/92f3603c-f60d-434a-b403-5c87f43e565b)

![image](https://github.com/user-attachments/assets/361eb554-22c1-43d9-bb25-187d2158eda1)

### Additional Context

Issue spotted in Firefox only. On Chrome, the same version seems to work fine. Tried in a private window too on Firefox to rule out any other plugin issues, and could reproduce it.

### Operating System

Linux

### Operating System Version

22.04.4

### Web Browser

Firefox

### Browser Version

130.0 (64-bit)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Duplicate https://github.com/bitwarden/clients/issues/10815
