### ISSUE TITLE
When "Show autofill menu on form fields" is "Off" the autofill hotkey and context menu don't work 

### ISSUE THREAD

**Issue by lukbukkit** [bitwarden/clients#10972]
### Steps To Reproduce

1. Go to Settings -> Autofill and toggle "Show autofill menu on form fields" to "Off"
2. Reload the website
3. Use the hotkey (shift + cmd + L) to autofill OR use the content menu Bitwarden -> Autofill login and click on the entry

### Expected Result

Bitwarden auto-fills the login credentials almost instantly.

### Actual Result

The login credentials are not auto-filled (even after a certain delay). They are only auto-filled after a click on the Bitwarden extension icon.

### Screenshots or Videos

https://youtu.be/ZizWXAgnax8

### Additional Context

The problem does not appear if "Show autofill menu on form fields" is set to "When field is selected (on focus) or by clicking on the menu entry in the Bitwarden extension to autofill.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Safari

### Browser Version

17.6 (19618.3.11.11.5)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Thank you for bringing this to my attention. We’ve received reports about this behavior and it’s being investigated by the Engineering team. It appears to be an upstream issue introduced by Apple in version 17.4.1 of Safari. They say they have a fix in 17.6.1 (in beta, coming soon) and 18 (September 16th). More information about this can be found here> https://github.com/bitwarden/clients/issues/10715#issuecomment-2310093066 

I hope this clarifies everything up for you. Please do not hesitate to let me know if you have any further questions.
