### ISSUE TITLE
CLI not reporting any events except logging in

### ISSUE THREAD

**Issue by jonjohnston** [bitwarden/clients#11033]
### Steps To Reproduce

1. log into bitwarden via cli
2. using cli, view the password to an item
3. log into Admin console and go to event logs

### Expected Result

Event should show "Logged in"
Event should show "Viewed item dsfdaadsdasf"

### Actual Result

Event shows "Logged in"

Nothing else shows

### Operating System

Windows, macOS, Linux

### Shell

Bash, Zsh

### Build Version

1.22.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@jonjohnston Thank you for your report. 

Just one thing I'm curious about. Is the version number you mention correct? The latest CLI version is [v2024.8.2](https://github.com/bitwarden/clients/releases/tag/cli-v2024.8.2).

Downloads can be found at: https://bitwarden.com/download/

**Comment by djsmith85** [comment]
The version you mention is the [last version](https://github.com/bitwarden/cli/releases/tag/v1.22.1) released on the previous repository before moving to a mono-repository under bitwarden/clients

**Comment by jonjohnston** [comment]
@djsmith85 yes the issue I was on the latest version from the old repo. Once upgrading, the issue is gone. Thanks
