### ISSUE TITLE
Autofill no longer works on Chrome

### ISSUE THREAD

**Issue by cyberfox1** [bitwarden/clients#11050]
### Steps To Reproduce

1. Go to any logon page
2. Click on bitwaden extension
3. Scroll down to matching logon profile
4. Click on logon profile

### Expected Result

Autfill userpass password

### Actual Result

This error

![image](https://github.com/user-attachments/assets/4a274046-e087-4ce3-8c18-368bf8d0e498)

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/5b4b6f9a-385a-46b9-8492-11256dda9766)

### Additional Context

Stopped working a few days ago

### Operating System

Windows

### Operating System Version

Win10 X64

### Web Browser

Chrome

### Browser Version

128.0.6613.138 (Official Build) (64-bit)

### Build Version

Version: 2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @cyberfox1,

Thank you for reporting this. I tested this on Windows 11 Pro with Chrome 128.0 and Bitwarden 2024.9.0, and I was able to perform autofill at [Vimeo](https://vimeo.com/) via Inline autofill, the extension's pop-up, and the [keyboard shortcut](https://bitwarden.com/help/auto-fill-browser/#keyboard-shortcuts). I recommend that we proceed with a fresh new installation; Please uninstall the Bitwarden browser extension, clear any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the machine, install the extension anew, and test that once more.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by JABirchall** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/10814 https://github.com/bitwarden/clients/issues/10815

@SergeantConfused this is a issue effecting every user. there has been 12+ reports of this issue and 2 open issues with 50+ comments each about the issue.
