### ISSUE TITLE
Firefox Extension import from LastPass fails with encrypted URLs

### ISSUE THREAD

**Issue by patzm** [bitwarden/clients#11051]
### Steps To Reproduce

1. Have a LastPass account with encrypted URLs. Note that that's something pretty recent.
2. Follow the instructions from https://bitwarden.com/help/import-from-lastpass/#tab-direct-import-7dsxR2Yah8mdGJAmQdYZea
  Note that I am _not_ using the `csv` import! I use the API / extension-based handshake import.
3. I have both the LastPass and Bitwarden browser extension for Firefox.
4. Follow the instructions for the import. Authentication etc. all worked and all passwords were imported. However, each entry in Bitwarden now as a long encrypted URI instead of the clear text version.

### Expected Result

I guess decrypt (or trigger decryption) of the Lastpass URIs (URLs).

### Actual Result

They were all encrypted and look like this.
![image](https://github.com/user-attachments/assets/c6fbfbdd-bd46-4349-b83e-b422eee5c953)

### Additional Context

I also noticed that the flag "require master password re-prompt" wasn't imported properly. Should I file a separate issue for that?

### Operating System

macOS, iOS

### Operating System Version

Sonoma 14.6.1 (23G93)

### Web Browser

Firefox

### Browser Version

130.0 (64-bit)

### Build Version

Version: 2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by webash** [comment]
i've also just experienced this in the Chrome extension. I also was only recently prompted by LastPass to encrypt URLs. Let me know if there's any information I can gather or tests I can run,

**Comment by patzm** [comment]
yes, I also ran into the problem of _not_ being able to select all. I went ahead and downloaded the [BitWarden CLI](https://bitwarden.com/help/cli/).
1. Follow [authentication instructions](https://bitwarden.com/help/cli/#log-in)
2. run
  ```bash
  echo "$(./bw list folders)" | jq -r '.[].id' | while read -r id; do
    ./bw delete folder "$id"
  done
  ```

you can add any filter on top of `$id` before issuing the delete.
