### ISSUE TITLE
Firefox Addon TOTP fills every input box/field individually (example PayPal)

### ISSUE THREAD

**Issue by zmberber** [bitwarden/clients#11076]
### Steps To Reproduce

Try to log into a website that requires TOTP and where each digit has a separate input box.  Use the Bitwarden firefox addon to try to fill in the correct digits, either by keyboard shortcut, or by just clicking on the correct account in the addon dropdown.

### Expected Result

Each digit is input correctly, the same way as if I had copied the code and then just done a paste.

### Actual Result

Every digit (i.e. every textbox) has only the first digit of the correct TOTP code (e.g. 111111 instead of 123456).  Sometimes it is also weird and not all numbers are the same, but whatever.  It seems like Bitwarden fills out every single textbox individually with the TOTP digits.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8a7b64f8-3dfe-4b5b-8089-278682494040)
![image](https://github.com/user-attachments/assets/6d5631c0-e2ce-4aa6-8ee6-5ff58bdfd0a9)

### Additional Context

If it were to just fill out the first one, then it would work, because then the way the webpage works is that after pasting, it will automatically fill in the other boxes with the subsequent numbers.  One can actually see this for a split second when Bitwarden fills it in, just before Bitwarden fills out every subsequent box as well.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by FlorianLang06** [comment]
I would like to work on this issue

**Comment by FlorianLang06** [comment]
This issue can be closed because the fix is merged.
