### ISSUE TITLE
mac failed.

### ISSUE THREAD

**Issue by mihalyr** [bitwarden/clients#11072]
### Steps To Reproduce

* configure server
* login
* call `bw list items`

### Expected Result

```
➜  ~ bw list items
? Master password: [hidden]
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
mac failed.
[{"object":"item","id":...
```

### Actual Result

list of items without errors?

### Additional Context

Why does `bw` CLI return a bunch of `mac failed.` lines when I try to list my vault items? Does this mean it fails to retrieve some of the items? Which ones?

### Operating System

Linux

### Operating System Version

Fedora 40

### Shell

Zsh

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in an outdated CLI client - I'd recommend updating to the latest version to try and remedy this.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by mihalyr** [comment]
> I think your error could have its origin in an outdated CLI client - I'd recommend updating to the latest version to try and remedy this.

You are right, I had to update, now I got a more detailed error, but all the same...

```
➜  ~ bw list items
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
MAC comparison failed. Key or payload has changed.
[{"passwordHistory":null,"revisionDate":
```

Why close this if you were unable to repro on your side without asking for more details? Not very helpful support and I am paying for your product....

**Comment by mihalyr** [comment]
I've created a new issue because customer support was too eager to close this one without much interest in helping customers https://github.com/bitwarden/clients/issues/11074
