### ISSUE TITLE
Issue with www.filae.com Page Loading Incompletely when Bitwarden Firefox is activated

### ISSUE THREAD

**Issue by NovaSilentium** [bitwarden/clients#11098]
### Steps To Reproduce

1. Open your browser and go to www.filae.com.
2. Note that the Bitwarden extension is locked and not opened.
3. Log in to  account on www.filae.com.
4. Observe the page load.
5. When you deactivate the Bitwarden extension there is no infinite loading

### Expected Result

The page should load completely and function as expected without any elements spinning indefinitely.

### Actual Result

The page loads partially, and some items on the page spin forever, preventing further interaction.

### Screenshots or Videos

[screen-recorder-fri-sep-13-2024-12-18-41.webm](https://github.com/user-attachments/assets/1510f2c3-d68a-4041-8ef1-f029f0ab36c2)

### Additional Context

When you deactivate the extension, there is no spinning circle

### Operating System

Windows, macOS

### Operating System Version

MacOS Sonoma

### Web Browser

Microsoft Edge, Firefox

### Browser Version

130.0 

### Build Version

 2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@NovaSilentium 

Thank you for this bug report. This seems very similar to the issue reported here - https://github.com/bitwarden/clients/issues/10798#issuecomment-2359375973

Can you test if disabling passkeys resolves the problem on your side? You can do this by going to `Settings > Notifications > Ask to save and use passkeys` and clicking off the checkbox.

If that's the case, we have a fix coming very soon that should resolve this problem.

**Comment by NovaSilentium** [comment]
Hi @cagonzalezcs Indeed disabling passkeys has solved this behavior.
