### ISSUE TITLE
Heavy CPU usage on DOM visibility changes

### ISSUE THREAD

**Issue by qsantos** [bitwarden/clients#11105]
### Steps To Reproduce

1. Go to https://news.ycombinator.com/item?id=41558554#41562094
2. Click on the `[-]` / `[253 more]` link repeatedly in quick succession
3. Watch the CPU usage of the `firefox` process spike to 50%, or listen to the fans spinning up

### Expected Result

<1% CPU usage

### Actual Result

~50% CPU usage

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/c1f1c3dd-8e94-4eb7-9e4b-2dd6a10df75a)

### Additional Context

This is definitely a very minor and likely niche issue, but I report it in case it is simple to fix, or if it could be related to more significant issues on other sites for regular users.

I am the author of a tiny browser extension to navigate Hacker News more efficiently ([ViHN](https://github.com/qsantos/ViHN/)). This makes me notice even slight performance issues when folding comments threads. However, the issue is not coming from ViHN, since:

1. With Bitwarden disabled, I see no CPU spike, even when toggle threads using ViHN or with by clicking on the link
2. With ViHN disabled (and Bitwarden enabled), I see a CPU spike by clicking on the link repeatedly

Anyway, I am not expecting a fix for this anytime soon, or at all, since it is such a minor thing. I only ever had a few minor issues with your extension, so keep up the good work!

### Operating System

Linux

### Operating System Version

Debian 12

### Web Browser

Firefox

### Browser Version

130.0.1

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@qsantos 

Thank you for this bug report. This is a duplicate report and we have some improvements for this problem present within main that will be released in the near future. For more details please review this comment - https://github.com/bitwarden/clients/issues/11077#issuecomment-2353414875

Closing this thread for now.

**Comment by qsantos** [comment]
I had found #11077, thanks for deduplicating!
