### ISSUE TITLE
Extremely Poor Performance on Wordpress "Appearance/Menus"

### ISSUE THREAD

**Issue by theofficialgman** [bitwarden/clients#11131]
### Steps To Reproduce

1. Edit wordpress site
2. Click on Appearance/Menus
3. Observe intense browser slowdown (no page response)

It does not matter if there are no login matches for the site, the slowdown still occurs.

### Expected Result

No slowown, ESPECIALLY if I do not have any login matches for the site. I expect that the bitwarden process does not run in such cases.

### Actual Result

5-10 second slowdown on page load and whenever moving a menu item. This makes the site nearly unusable.
![image](https://github.com/user-attachments/assets/af24631b-e667-4e93-b5d1-a80098285007)

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox

### Browser Version

Latest stable releases

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@theofficialgman 

Thank you for this bug report. This is a duplicate report and we have some improvements for this problem present within `main` that will be released in the near future. For more details please review this comment - https://github.com/bitwarden/clients/issues/11077#issuecomment-2353414875

Closing this thread for now.
