### ISSUE TITLE
"Show Autofill Menu on Form Fields" option setting ignored in Microsoft Edge Client Extension v2024.9.1

### ISSUE THREAD

**Issue by wdouglascampbell** [bitwarden/clients#11179]
### Steps To Reproduce

1. First, ensure that "Show Autofill Menu on Form Fields" option is off.
   a. Click BitWarden extension icon and select Settings.
   b. Click Autofill
   c. Change dropdown box for "Show Autofill Menu on Form Fields" of **Off**.

2. Go to a login page for a site that you have saved credentials.
3. Click in the username or password box.

### Expected Result

Since "Show Autofill Menu on Form Fields" is Off.  There should be no change.

### Actual Result

The BitWarden shield icon is displayed and its dropdown list of available credentials to choose from is shown.  Since this is set to "Off", this should not be occurring.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Microsoft Edge

### Browser Version

Version 129.0.2792.52 (Official build) (64-bit)

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by wdouglascampbell** [comment]
This also occurs with the latest Chrome extension as well.  It does not occur though with v2024.9.0.

**Comment by cagonzalezcs** [comment]
@wdouglascampbell Are you seeing any console errors within the extension's background or within the popup? Specifically, I'm wondering if you have similar errors to the ones reported by this user - https://github.com/bitwarden/clients/issues/10814#issuecomment-2359409694

**Comment by wdouglascampbell** [comment]
No errors in the console for me.

**Comment by cagonzalezcs** [comment]
@wdouglascampbell Thanks for confirming that. 

Your reported issue seems similar to the one reported here - https://github.com/bitwarden/clients/issues/11173

I'm going to close this thread to centralize discussion on the topic.

One other thing, if you're comfortable with doing so, would you please try side loading one of the extension builds from this page for your browser?

https://github.com/bitwarden/clients/actions/runs/10945259339?pr=11156

I'm interested in finding out if this build allows you to disable the inline menu without issues.
