### ISSUE TITLE
Inline autofill menu does not disable regardless of setting

### ISSUE THREAD

**Issue by Gauss23** [bitwarden/clients#11173]
### Steps To Reproduce

1. start Chrome or Opera
2. add the extension
3. log in to Bitwarden
4. choose to disable auto-fill
5. Restart the browser
6. all input fields will still have the Bitwarden logo and credentials drop-down

### Expected Result

With auto-fill disabled, I expect to not see any auto-fill features on websites. This worked with all versions, before the version today received

### Actual Result

All input fields still show auto-fill features.

### Operating System

macOS

### Operating System Version

15.0

### Web Browser

Chrome, Opera

### Browser Version

latest

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Gauss23** [comment]
Seems like reinstalling everything (browsers) from scratch solved it.

**Comment by cagonzalezcs** [comment]
@Gauss23 Are you seeing any console errors within the extension's background or within the popup? Specifically, I'm wondering if you have similar errors to the ones reported by this user - https://github.com/bitwarden/clients/issues/10814#issuecomment-2359409694

**Comment by cagonzalezcs** [comment]
@Gauss23 Hmm understood. 

If you're comfortable with doing so, could you please try to side load this build artifact of the extension to see if the issue persists? https://github.com/bitwarden/clients/actions/runs/10945259339?pr=11156

I have a feeling that the issue you're experiencing is similar to those in the thread, even if no visible errors are presenting themselves.

**Comment by cagonzalezcs** [comment]
Alright, so I installed a fresh version of the `v2024.9.1` extension in Edge and found a similar problem on first login. The inline menu would not appear at all for, regardless of what setting I set. I had to refresh my extension a couple of times for it to finally function as expected, allowing me to disable/enable the extension as expected.

Strange, we'll look into it... for now, try turning the extension off/on if the issue does appear...

**Comment by gokou340** [comment]
> @Gauss23 Hmm understood.
> 
> If you're comfortable with doing so, could you please try to side load this build artifact of the extension to see if the issue persists? https://github.com/bitwarden/clients/actions/runs/10945259339?pr=11156
> 
> I have a feeling that the issue you're experiencing is similar to those in the thread, even if no visible errors are presenting themselves.

I sideloaded the build artifact but still had the same issue.

I am using a self hosted instance of Bitwarden if that matters.

**Comment by wdouglascampbell** [comment]
I am experiencing the exact same thing with Chrome and Edge on Windows and the sideloaded build artifact still had the same issue.  Before I updated from 2024.09.0 to 2024.09.1 I did not have the issue.  In fact, Firefox does not have the issue since it appears 2024.09.1 is not yet available for it.

**Comment by dvoijen** [comment]
Same here with Brave

**Comment by alaahariri** [comment]
I am having the same issue.

**Comment by JPC-IT** [comment]
Same issue. **Only on self-hosted**
I have a Bitwarden hosted account I am using on different Edge browser profiles on the same machine and these seem fine. Any machine I test the plugin against the self-hosted server has the above problem. Fresh installs don't matter, either.

Edge Browser Version 129.0.2792.52
Server updated to 2024.9.1
Extension updated to 2024.9.1

**Comment by waschbaer2004** [comment]
Same Here with Opera (Chrome Extension) and since today the Firefox extension.

**Comment by castigo86** [comment]
Sorry, joining in to confirm that is also true for Firefox 130.0.1.

**Comment by cagonzalezcs** [comment]
Thank you for the details everyone, we've been looking into the issue this week trying to find a definitive reason. I wanted to ask a separate question, though it could point to a reason for why this issue is appearing with the setting. 

For anyone having issues with this setting, are you able to update any other settings within the extension which also show the same problem?

We've caught this issue a couple of times in attempting replicate the behavior, though we've found that a fresh install of the extension resolves the problem. That alone has been a bit of an issue though, as it doesn't seem to replicate after that first trigger.

**Comment by castigo86** [comment]
Hi @cagonzalezcs, on FIrefox I can positively alter any other settings form the settings autofill tab (like showing identities) without errors.

**Comment by dvoijen** [comment]
@cagonzalezcs in Brave other settings like check default URI detection works ok.

**Comment by alaahariri** [comment]
@cagonzalezcs I'd like to share my experience regarding this issue:

I recently installed Google Chrome for the first time on my Windows machine (previously, I was using only Microsoft Edge). After installing the Bitwarden extension, I noticed the following:

**Issue with "Off" Option in Autofill -> Show the autofill menu on Form Fields:** When selecting the "Off" option in the settings (as shown in the screenshot below), it does not work as expected. The other two options function correctly. When "Off" is selected, the system behaves as if the option "When field is selected (On Focus)). Thus, doesn't respect the Off option.

![image](https://github.com/user-attachments/assets/5ee2b8c0-44c0-4494-bd33-101187ae466e)


### Client Details:

**Microsoft Edge**: Version 129.0.2792.52 (Official build) (64-bit)
**Bitwarden Edge Extension**: Version 2024.9.1
**Accounts**: Bitwarden client is running with two accounts (one from Bitwarden.com and one self-hosted).
**Autofill Setting**: Autofill is turned off in the Bitwarden extension settings.

### Scenarios Tested:

- **Activate Bitwarden.com Account:** Form fields on any website do not display any Bitwarden overlays (icons or dropdowns), which aligns with the chosen settings.

- **Activate Self-Hosted Account and Refresh the Webpage:** Form fields on any site display the icon and overlay on the fields. The extension does not respect the "Off" setting in this case.

- **Switch Back to Bitwarden.com Account and Refresh the Page:** Web form fields do not show overlays or icons, functioning as expected.

- **Switch Again to the Self-Hosted Account and Refresh the Page:** The extension displays overlays/icons on form fields regardless of the extension settings.


It appears that when using the self-hosted account, the extension does not respect the "Off" setting for Autofill icon/menu on form fields.

Thank you for looking into this issue.

**Comment by dvoijen** [comment]
Indeed forgot to mention here also self hosted.

**Comment by castigo86** [comment]
Indeed, self-hosted for me too.

**Comment by clowncracker** [comment]
@cagonzalezcs if you had to guess, when do you think `v2024.9.2` will be released?  Debating if it's worth the hassle to downgrade if it's just going to be a week out.

**Comment by RudeDude** [comment]
I'm having this same problem in FireFox (ver 130.0.1 (64-bit)) on Windows with Extension version 2024.9.1 (self hosted with ver 2024.9.1)

**Comment by cagonzalezcs** [comment]
@clowncracker The next browser extension release should be submitted to the various browser storefronts towards the end of the week of October 14th.

**Comment by cagonzalezcs** [comment]
@clowncracker

Need to provide a correction to this, it appears that the team is working on releasing a mid-cycle version of the browser extension. The fix for this issue should be appearing this week.

**Comment by reinob** [comment]
My Chrome updated to 2024.10.0. Everything is good now :)
Still waiting for Firefox to also update..

**Comment by dvoijen** [comment]
In brave updated to 2024.10.0 everything fine again.

**Comment by clowncracker** [comment]
When is 2024.10.0 going to be released in Firefox?

**Comment by cagonzalezcs** [comment]
It was submitted last week. As with every release, we're pending approval from the Mozilla team.

**Comment by saschafoerster** [comment]
How about Safari? I am still on version 2024.09, I guess this takes the longest time, right?

**Comment by EvilBMP** [comment]
@cagonzalezcs Still no approval from the Mozilla team? Chrom(ium) based browsers got the update last week already, but Firefox users are still waiting. This bug is really annoying. Any updates on this one?

**Comment by reinob** [comment]
My firefox extension was updated today to 2024.10.0! :)
