### ISSUE TITLE
Bitwarden Firefox extension never locks vault  

### ISSUE THREAD

**Issue by joeriddles** [bitwarden/clients#11185]
### Steps To Reproduce

1. Install the Firefox Bitwarden extension and log in
2. Set the Vault Timeout to immediately or 1-minute
3. Notice that is **never locks**

### Expected Result

The vault is locked when the vault timeout is reached.

### Actual Result

The vault is not locking when it should. The vault timeout setting is being ignored.

### Additional Context

<img width="373" alt="image" src="https://github.com/user-attachments/assets/ff893c5b-9482-4a49-b4f1-970fd3057f35">

<img width="726" alt="image" src="https://github.com/user-attachments/assets/197f03fe-2105-423b-bc92-f747ffdbe85e">

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Firefox

### Browser Version

130.0

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @joeriddles,

Thank you for reporting this. I tested this on macOS 15 with Firefox 131.0 and Bitwarden browser extension 2024.9.1, and the browser extension locked as expected after 1 minute, after I set the Vault Timeout to 1 minute and clicked out of the extension. I'd recommend updating Firefox and the Bitwarden browser extension; If that does not assist, please consider uninstalling the extension, removing any of its [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), rebooting the machine, and installing it anew.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
