### ISSUE TITLE
flathub bug

### ISSUE THREAD

**Issue by s-b-repo** [bitwarden/clients#11193]
### Steps To Reproduce

launch flatpak in teminal

### Expected Result

running

### Actual Result

should migrate: false - up
/app/Bitwarden/bitwarden: line 11:    13 Trace/breakpoint trap   (core dumped) $APP_PATH/bitwarden-app "$@"
[2 preload-host-spawn-strategy] Warning: waitpid override ignores groups

### Operating System

Linux

### Operating System Version

arch linux

### Installation method

Other

### Build Version

latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there!

Thank you for your report - the flatpak is a community maintained package, so it is not an issue we are able to resolve. 

This issue will now be closed.

Thanks!
