### ISSUE TITLE
cloning from organisation to personal vault - reproducible failure, reproducible workaround

### ISSUE THREAD

**Issue by richardwonka** [bitwarden/clients#11279]
### Steps To Reproduce

1. open admin console of organsiation vault
2. select clone from items ... menu
3. select personal vault as owner at bottom of cloned entry
4. click [save]
 -> FAILURE: Popup with Error message "The client has not provided an organization id!"

WORKAROUND (continue from last step)
7. select _different_ organisation _without collections_ as owner
8. click [save] -> (expected) error message about requiring a collection
9. (re-) select personal vault as owner
10. click [save]
-> clone is successfully saved in personal vault. 

### Expected Result

saving clone to personal vault _should_ succeed at first try

### Actual Result

clone is only saved to personal vault _after_ first failing to save to organisation vault without collections

### Additional Context

reproduced multiple times in firefox tab. 
bitwarden server running on current stable debian on raspberry pi 4b as homeassistant vaultwarden addon container.

First thought: This _might_ be a race condition, due to slow-ish response from server. (client -> vpn -> home network -> raspi 4b)

### Operating System

Windows, Linux

### Operating System Version

windows 11

### Web Browser

Firefox

### Browser Version

123.0.1

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for the report but this appears to be hosted with Vaultwarden which is a separate application from Bitwarden that we do not provide support for.

You can find the contact information for Vaultwarden here: https://github.com/dani-garcia/vaultwarden#get-in-touch
