### ISSUE TITLE
Bitwarden Safari Plugin don't stop open tabs

### ISSUE THREAD

**Issue by ra-albrecht** [bitwarden/clients#11287]
### Steps To Reproduce

Nothing to do: Just install the bitwarden macos client from app store and activate the Safari Plugin. 

Even if logged in or not, the plugin starts opening tabs (not sure how often, seems to be every 1 or 2 hour) After a while safari starts looking like in the screenshot appended.

this can rapidly count up, after closing this tabs they start to appear again. 
 Nothing to do: Just install the bitwarden Macos client from the marketplace and activate the Safari Plugin.

### Expected Result

Bitwarden should not display the "Getting started" page over and over again in Safari.

### Actual Result

The Safari extension doesn't stop displaying the "Getting started" page in new tabs, even if a tab with this is or was opened before.

### Screenshots or Videos

![Screenshot 2024-09-27 at 12 30 29](https://github.com/user-attachments/assets/b8e2d62a-065d-42ce-b2ce-81e1d71577ec)

### Operating System

macOS

### Operating System Version

14.6, 15.0

### Web Browser

Safari

### Browser Version

18.0 (19619.1.26.111.10, 19619) and earlier

### Build Version

Version: 2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by trmartin4** [comment]
@ra-albrecht can you confirm that this has been fixed?  We believe that this was addressed with version `2024.9.1` of the Safari extension.

**Comment by ra-albrecht** [comment]
I'll check and let you know

**Comment by ra-albrecht** [comment]
Okay, it looks good for now - no new tabs are opened anymore. So if you want you can close the ticket - not sure about the comment of @vojeroen .
Thanks for fixing.

**Comment by vojeroen** [comment]
I can open a new ticket if the specific problem in this ticket is solved, if that is more appropriate. It looked similar to this so I didn't open a new ticket yet.

**Comment by trmartin4** [comment]
@vojeroen I do think it would be best to open that as a separate ticket.  It sounds like a different problem from the one that we've resolved here.

**Comment by aamoh22** [comment]
We have same issue in Safari Version 18.0.1 (20619.1.26.31.7), Bitwarden plugin 2024.9.1. Could you take a look at this one too and guide us on how to resolve it? Let us know if you need any additional information. Thanks!

**Comment by petarhristov94** [comment]
I'm experiencing an issue where Bitwarden opens multiple tabs to the "_Getting Started_" page (`https://bitwarden.com/browser-start/`) after unlocking the vault. The timing between unlocking and the tabs opening varies - sometimes immediately, other times after a few minutes.

Recently, I had two Safari windows open on different profiles, and suddenly 3 tabs opened in one window and another 3 tabs in the second window, forcing me to close 6 tabs in total. This behavior seems random and disruptive.

I’ve tried reproducing the issue, and it consistently happens the first time I open the Bitwarden desktop app (**Version 2024.11.0 (33157)**) on **macOS Sequoia 15.1.1 (24B91)**, though _I experienced the same problem on the previous macOS version as well_.

Interestingly, I also use the Bitwarden desktop client on a Windows system, and I have never encountered this issue there. In fact, I’ve never seen the "_Getting Started_" page open on my Windows system at all.

I’d appreciate guidance on how to disable this behavior entirely or any steps to resolve this issue. It seems like a bug specific to macOS or the Safari extension.

**Comment by petarhristov94** [comment]
Happens to me too and to be honest it's quite annoying. I'm commenting in the other open ticket too.
