### ISSUE TITLE
Linux flatpak desktop client terminates abnormally when switching accounts

### ISSUE THREAD

**Issue by m8ram** [bitwarden/clients#11335]
### Steps To Reproduce

1. OpenBitwarden
2. Log in to one account
3. Open the account drop down
4. Select second account to unlock

### Expected Result

password screen to unlock the account

### Actual Result

bitwarden crashes but does not generate coredump

### Additional Context

This has worked fine until today. I did not install updates or make any changes to either account.
Switching still works on the android client.
This morning when unlocking my work account I had to reauthenticate (including the OTP) because the "token" was no longer valid (not sure about the wording).
This is something I have seen occassionally so I was not worried about it. Not sure if it is relevant.

### Operating System

Linux

### Operating System Version

Fedora 40

### Installation method

Other

### Build Version

2024.9.0 Shell 32.0.1, Renderer 128.0.6613.36, Node 20.16.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

The flatpak is maintained by the community, not Bitwarden. You can use the [official .AppImage installer](https://bitwarden.com/download) from the Bitwarden website as an alternative while updates are pending for the flatpak application.

This issue will now be closed.
