### ISSUE TITLE
"Start to tray icon" steals focus

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [bitwarden/clients#11341]
### Steps To Reproduce

1, Enable "start to tray icon" and "Start automatically on login".
2. Logoff then logon.
Quickly, open any application and start typing.
4. Suddenly whatever you type is not displayed. This cocurs when Bitwarden starts in the background, stealing the input focus.

### Expected Result

Whatever I type is displayed.

### Actual Result

Suddenly what I type is not displayed.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.9.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hello there,

Can you try updating to 2024.10.1 and confirm if this is still occurring on your machine?

Thanks!

**Comment by sammbw** [comment]
I haven't heard back from you, and this issue doesn't appear to be widespread at this time.

If you could contact us using the form below, we'll follow up and treat it as a troubleshooting issue instead!

Contact Bitwarden: https://bitwarden.com/contact/

Many thanks!
