### ISSUE TITLE
Passkeys do NOT work in lockdown mode

### ISSUE THREAD

**Issue by oppressor1761** [bitwarden/clients#11355]
### Steps To Reproduce

1. log in Bitwarden extension
2. turn on lockdown mode
3. go to https://webauthn.io for test
4. register a passkey

### Expected Result

Bitwarden pops up and ask to create a passkey

### Actual Result

macOS system UI pops up to ask for either iPhone or a hardware security key

### Screenshots or Videos

![截屏2024-10-02 14 11 16](https://github.com/user-attachments/assets/d544241a-9307-4aa5-83a6-e73e691bb778)

### Additional Context

_Ask to save and use passkeys_ is turned on

### Operating System

macOS

### Operating System Version

15.0

### Web Browser

Safari

### Browser Version

18.0

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @oppressor1761
Thank you very much for letting us know about the difficulties you are experiencing.
Turning on Lockdown Mode hardens device defenses and strictly limits certain functionalities while it place some restrictions on web browsing in Apple's Safari.
With this enabled, you should still be able to authenticate with your passkey, What i noticed is that you dont have an account associated with the website 
![image](https://github.com/user-attachments/assets/5f148a85-0f86-4138-aea1-a9b792bc211a)

To continue to use the Bitwarden extension for autofill and passkey purposes, you might need to disable the lockdown mode.
This issue will now be closed.
