### ISSUE TITLE
Bitwarden extension stuck to login through Duo 2FA !

### ISSUE THREAD

**Issue by Doohie** [bitwarden/clients#11377]
### Steps To Reproduce

Go to your bitwarden extension and login
A pop up will appear from the extension to ask popout extension, click on it
3. Click on '...'
The extension comes loose and asks for launch DUO, click on it
4. Go to '...'
The extension will now open a new tab in your browser that will automatically send a verification to your smartphone through DUO,
and here it gets stuck instead of verifying.

### Expected Result

After logging into bitwarden through the extension,
a popup appears to launch duo two-steps
which you then have to verify on your smartphone to gain access to your vault.

### Actual Result

After logging into bitwarden through the extension,
a popup appears to launch my duo two-steps.
However after clicking on launch Duo, bitwarden keeps loading without going through to Duo to verify my login.
The extension redirects you and keep hangs on …vault.bitwarden.com/duo-redirect-connector…

(Extension version 2024.9.1)

### Screenshots or Videos

![Bit1](https://github.com/user-attachments/assets/3737d6c0-00b6-44fe-9ab5-6ff9bd20d0a7)
![Bit2](https://github.com/user-attachments/assets/6e6af253-8a49-429e-9edf-4e2d6baa2ec0)

### Additional Context

Affects any browser...

### Operating System

Windows

### Web Browser

Microsoft Edge, Firefox

### Browser Version

Edge 129.0.2792.65 (Official build) (64-bit)

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Doohie** [comment]
> Hi there,
> 
> Thank you for your report!
> 
> I was able to reproduce this issue, and I have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

Not sure if it helps, but someone on the bitwarden forum see two errors in the dev console. One where the browser is refusing to apply inline style because of a violated Content Security Policy. The other being an error in duo-redirect.ts stating “Invalid redirect URL”.

**Comment by Doohie** [comment]
Just to let you know that everything is working perfectly again.
Browsers Used - Firefox and Edge.

**Comment by trmartin4** [comment]
Thank you for letting us know!  This was fixed with [#11363](https://github.com/bitwarden/clients/pull/11363), so I will close the ticket.
