### ISSUE TITLE
Rate limit exceeded in browser login

### ISSUE THREAD

**Issue by FahimFBA** [bitwarden/clients#11381]
### Steps To Reproduce

1. Go to the official website of Bitwarden
2. Click on Login
3. Give your ID and Password
4. Click on Login button
5. Issue appears as a toaster in the top right side

### Expected Result

User successfully logged in to the website in their account

### Actual Result

It gives an error

### Screenshots or Videos

![{2F0E462C-DD1D-4154-829C-7063F2F503CE}](https://github.com/user-attachments/assets/daa75592-c582-4294-b1d1-002757c06cf0)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

We have received reports of intermittent server access when trying to use the web app, and we’re currently looking into it. In the meantime, users should be able to log in through any other clients as expected.

Thank you in advance for your patience and understanding.

**Comment by FahimFBA** [comment]
The issue has been resolved as I can login to the account via the web browser.

Therefore, I am closing the issue now. Thank you so much for resolving the issue within this much short amount of time. 👏
