### ISSUE TITLE
When in "Security Note", creating new record doesn't choose type "security note" by default.

### ISSUE THREAD

**Issue by holms** [bitwarden/clients#11423]
### Steps To Reproduce

1. Go to 'Security note"
2. Click on "+" button on the bottom

### Expected Result

Type should be "Security note"

### Actual Result

instead type is "Login"

### Screenshots or Videos

![Screenshot 2024-10-05 at 01 28 15](https://github.com/user-attachments/assets/6b13c2e6-b096-4260-9aad-e75b3f63b3a3)

### Additional Context

I go to security note, I add the item and it's pretty much expected to have "Security note" type by default, I've created an item and I couldn't find it after repeating operation i've noticed that type is wrong. That's not very intuitive behavior. 

### Operating System

macOS

### Operating System Version

Sonoma

### Installation method

Homebrew

### Build Version

2024.9.0 (30042)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment]
Hi @holms 

Thanks for the report.

This is a duplicate https://github.com/bitwarden/clients/issues/10994

**Comment by holms** [comment]
Closing it then
