### ISSUE TITLE
Biometric Unlock no longer working on Brave Browser (Chrome) extension after updating to MacOS Sequoia 15.0

### ISSUE THREAD

**Issue by fd40551** [bitwarden/clients#11424]
### Steps To Reproduce

1.  Open Desktop App, unlock with PW and keep open (hidden to Menu Bar)
2. Unlock with Biometric option on Desktop App working fine.
3. Extension works as expected on Safari Browser.
4. When using Brave Browser, the "Unlock with biometrics" button turns blue and appears to be active (Screenshot 1), but does not open biometric dialog screen as before (see screenshot 2).  

![Screenshot 2024-10-04 at 5 08 07 PM](https://github.com/user-attachments/assets/ba81cb75-d59e-4535-8259-cd1fbfae68fd)

![Screenshot 2024-10-04 at 5 12 09 PM](https://github.com/user-attachments/assets/31f1086a-eda5-4384-90ca-ab4ffdd107d0)

### Expected Result

Unlocking Bitwarden with biometrics very useful and convenient, specially since use long and cryptic PW to lock Vault.  Real pain to have to renter PW each time need to use Bitwarden. 

### Actual Result

Biometric dialog screen no longer displays after selecting "Unlock with biometrics" option as before.

### Additional Context

Please address this "must-have" issue.  Thanks!

### Operating System

macOS

### Operating System Version

Sequoia 15.0

### Web Browser

Brave

### Browser Version

Version 1.70.123 Chromium: 129.0.6668.89 (Official Build) (arm64)

### Build Version

Chromium: 129.0.6668.89 (Official Build) (M1 Mackbook pro)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @fd40551,

Thank you for this report. What version of the Bitwarden desktop client do you have installed via the Mac App Store? If possible, please update it to version 2024.9.0, reboot the computer, and let me know if that helps.

Thank you,

**Comment by 1tacocat1** [comment]
@SergeantConfused - this resolved the issue for me (was seeing the same on edge).  One item of note - I had to force quit bitwarden on the mac to get the upgrade to go through.  Just noting that here in case others see similar and aren't sure why the client didn't just update itself.

**Comment by Sophon** [comment]
Updating works. There was some issue that App Store couldn't update it and you have to manually end the Bitwarden task. After doing so, update works and after the update, the biometrics work.

**Comment by fd40551** [comment]
Did as you suggested and it's working again!
Thank you for the great support!Frank




    On Saturday, October 5, 2024 at 08:52:13 AM PDT, LeNDuyA ***@***.***> wrote:  
 
 


Updating works. There was some issue that App Store couldn't update it and you have to manually end the Bitwarden task. After doing so, update works and after the update, the biometrics work.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for following up on this. I will now proceed and close this GitHub report.

If you encounter anything else, or if you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) with us.

Thank you again,
