### ISSUE TITLE
Cannot disable the blue shield in input fields

### ISSUE THREAD

**Issue by patrakov** [bitwarden/clients#11433]
### Steps To Reproduce

Use case: I want the Bitwarden browser extension only to allow me to autofill logins that the team shared with me. I want it to have zero effect on sites for which there are no saved logins, and I do not save any logins in BitWarden. In other words, it is a read-only source of credentials for a few specific websites.

1. Go to settings. Set "Show autofill menu" to "off".
2. Go to any website with a login form for which you have no saved credentials.
3. Click on the username field.

I have also tried disabling the context menu options.

### Expected Result

I should not see anything related to Bitwarden except in the address bar. I want to be able to interact with Bitwarden only through the button that it adds to the address bar, just like it was possible in previous versions of the extension.

### Actual Result

I see a blue shield in the input field. I shouldn't.

### Screenshots or Videos

Preferences (and I also tried disabling the context menu):
![image](https://github.com/user-attachments/assets/8e018348-ff13-4bfd-a545-6cfef3a5d26e)

Unwanted blue shield on a site not in Bitwarden:
![image](https://github.com/user-attachments/assets/dce0964e-ab37-4705-b805-245416eda9e8)

In the second screenshot, the username/password pair comes from the built-in password manager, and I don't want that to be copied to Bitwarden.

### Additional Context

I also want to be able to disable this panel which pops up if I click on any username field:

![image](https://github.com/user-attachments/assets/9f7f939a-bf82-46d1-b711-8a1c34a0d5f8)

If necessary, I will click the button in the address bar and select the autofill from there.

Note that the server is actually VaultWarden, but the screenshot above is from a user using the official server.

### Operating System

Linux

### Operating System Version

Arch Linux (rolling)

### Web Browser

Firefox

### Browser Version

130.0.1 (64-bit)

### Build Version

Version: 2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Hi there,

It is important to note that vaultwarden is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 

https://bitwarden.com/help/install-and-deploy-offline/ 

If you wish, you can follow this issue on GitHub at the link below.

GitHub: https://github.com/bitwarden/clients/issues/10815 

While I am unable to provide an ETA for a fix, I would expect to see this introduced in an upcoming version release to the Bitwarden extension. You may also find a workaround for your specific browser within the GitHub issues comments above.

**Comment by patrakov** [comment]
Hello,

I don't see how #10815 is related. It is about the extension not autofilling when it should. This bug is about a missing preference to disable all forms of UI (such as a blue shield in all edit fields) outside of the address bar.

**Comment by patrakov** [comment]
The latest browser extension works as desired.
