### ISSUE TITLE
Unlock with biometrics stopped working

### ISSUE THREAD

**Issue by Mscebba** [bitwarden/clients#11434]
### Steps To Reproduce

1. Go to chrome extensions settings > Account security and check
3. Click on "Unlock with biometrics"
<img width="375" alt="Screenshot 2024-10-06 at 15 34 11" src="https://github.com/user-attachments/assets/7257b001-db00-44e5-9358-2c39c2bdcb29">

### Expected Result

It should ask for biometrics next time the vault is locked

### Actual Result

Biometrics pop up doesn't show and only allows entering master password every time the vault is locked for chrome extension

### Screenshots or Videos

<img width="375" alt="Screenshot 2024-10-06 at 15 34 11" src="https://github.com/user-attachments/assets/6647fe3f-5b73-455f-8319-e0d038a70965">

https://github.com/user-attachments/assets/6e696b3f-9b59-4839-b65e-5fa0b14942b9

### Additional Context

It started about 4 days ago in both of my macbooks Pro, one 2024 M3 and the other is a 2020 M1

<img width="355" alt="Screenshot 2024-10-06 at 15 30 12" src="https://github.com/user-attachments/assets/e3a42287-67a3-49a5-bec2-22ee5eb4b9b6">

<img width="702" alt="Screenshot 2024-10-06 at 15 30 30" src="https://github.com/user-attachments/assets/904790b1-3fe4-4fa9-991d-e98676758e3d">

<img width="266" alt="Screenshot 2024-10-06 at 15 30 56" src="https://github.com/user-attachments/assets/42cec951-9998-49d9-a811-56ddfe57978c">

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1 (23G93)

### Web Browser

Chrome

### Browser Version

 129.0.6668.90 (Official Build) (arm64)

### Build Version

2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by nqlp** [comment]
Same issue here with my Macbook Pro M1. 

macOS: Sonoma 14.5

**Comment by jamesbezuk** [comment]
Same issue, similar setup to both posters:

Macbook Pro M1 2020
macOS: Sonoma 14.6.1
Browsers: Chrome 129.0.6668.90 (Official Build) (arm64) and Vivaldi 6.9.3447.51 (Stable channel) (arm64)

**Comment by mikicvi** [comment]
Can repro on:
Macbook Pro 2023, M2 Pro 
macOS: Sequoia 15.1 Beta (24B5055e)
Browser: Version 129.0.6668.90 (Official Build) (arm64)

-> Works on Safari: Version 18.1 (20619.2.5.11.2)

**Comment by nqlp** [comment]
I have updated the app to the latest version through the App Store and it works!

**Comment by felipemlemos** [comment]
which version did you update to, @nqlp ?
I tried to update, but it is still failing for me.

Plugin version: 2024.10.0

Macbook Air M2 2022
macos: Sonoma 14.6 (23G80)
Browser: Chrome 129.0.6668.90 (Official Build) (arm64)

**Comment by Mscebba** [comment]
> > which version did you update to, @nqlp ? I did update it, but it is still failing for me.
> > Plugin version: 2024.10.0
> > Macbook Air M2 2022 macos: Sonoma 14.6 (23G80) Browser: Chrome 129.0.6668.90 (Official Build) (arm64)
> 
> Version 2024.9.0 Shell 32.0.1 Renderer 128.0.6613.36 Node 20.16.0 Architecture arm64

Thanks! Updating desktop this version worked for me!

![Screenshot 2024-10-07 at 12 12 17](https://github.com/user-attachments/assets/1769b887-d953-494a-a0c3-29e1c5f0476f)

**Comment by Mscebba** [comment]
Updating desktop version to 2024.9.0 fixes chrome extension problem
