### ISSUE TITLE
Generator Page Not Displaying When Creating New Login

### ISSUE THREAD

**Issue by dpearson2699** [bitwarden/clients#11454]
### Steps To Reproduce

1. Create a new login from the Chromium web extension.
2. Click on the generate button for the password 
<img width="283" alt="image" src="https://github.com/user-attachments/assets/e0f30e6c-eecd-45c7-af2b-ce9838adfef7">

3. Be presented with a blank screen
![image](https://github.com/user-attachments/assets/786a7be8-ae48-4489-af8d-866906bc3bbe)

### Expected Result

The generator page should pop up allowing you to create a random password.

### Actual Result

The blank page shows up instead

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Brave

### Build Version

2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarikaBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of your browser settings.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

**Comment by SirTobyB** [comment]
Hi, i've got exactly the same problem. In the past, this was working but i've noticed the problem a few months ago. Can we get a hint, what misconfiguration in the browser settings can cause this?

### Screenshots or Videos

![grafik](https://github.com/user-attachments/assets/36abbf31-2717-445c-b770-791e1be91310)

![grafik](https://github.com/user-attachments/assets/71f2d444-74a0-4060-91cf-ad51ca7b223b)

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

131.0

### Build Version

2024.9.2

**Comment by SirTobyB** [comment]
**Ok, uninstalling the addon, restarting Firefox and reinstalling the addon fixed the problem for me.**
Just in case anyone is experiencing the same problem.
