### ISSUE TITLE
Autofill Username Not Working On login5.fisglobal.com

### ISSUE THREAD

**Issue by LZeugirdor** [bitwarden/clients#11521]
### Steps To Reproduce

1. Go to 'https://www.ebtedge.com/gov/portal/PortalHome.do'
2. Click on 'Cardholder Login'
3. Attempt to autofill

### Expected Result

Username should be autofilled.

### Actual Result

Username is not autofilled, however password is.

### Screenshots or Videos

https://github.com/user-attachments/assets/ae6a2200-a7e4-4c97-b862-dfa99b8d805a

### Additional Context

I've tried using custom fields such as
loginName, User ID, idp-first-time-login-loginname
None of these work

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Browser Version

1.70.126 Chromium: 129.0.6668.100 (Official Build) (64-bit)

### Build Version

Version: 2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by LZeugirdor** [comment]
I should add default chrome autofill works on another computer in this house.

**Comment by SergeantConfused** [comment]
Hello @LZeugirdor,

We appreciate you letting us know of this. Due to the nature of autofill, we track such reports internally using this [form](https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform). Could you please report this via that form? Please remember that you can access that form also via the ([New issue](https://github.com/bitwarden/clients/issues/new/choose)) button on GitHub.

I thank you in advance for your understanding; I will proceed and close this report now.

Thank you again,

**Comment by LZeugirdor** [comment]
I've submitted the form a while back and haven't seen it work yet.

**Comment by LZeugirdor** [comment]
Still not working even with custom fields as previously stated. 

> Hello [@LZeugirdor](https://github.com/LZeugirdor),
> 
> We appreciate you letting us know of this. Due to the nature of autofill, we track such reports internally using this [form](https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform). Could you please report this via that form? Please remember that you can access that form also via the ([New issue](https://github.com/bitwarden/clients/issues/new/choose)) button on GitHub.
> 
> I thank you in advance for your understanding; I will proceed and close this report now.
> 
> Thank you again,

**Comment by LZeugirdor** [comment]
I also want to state I'm on firefox and it's the same issue, so it's not browser specific.
