### ISSUE TITLE
Keepass CSV import doesn't include TOTP

### ISSUE THREAD

**Issue by jnns** [bitwarden/clients#11522]
### Steps To Reproduce

Export a CSV file from KeePass. Open it to verify that TOTP are included.
Go to bitwarden.com and import the file using the appropriate selection from the drop down menu. The import finishes without problems.

### Expected Result

TOTP are included in the vault entries.

### Actual Result

TOTP are not included in the vault entries.

### Operating System

Linux

### Operating System Version

Fedora

### Web Browser

Firefox

### Build Version

bitwarden.com

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ZilongXue** [comment]
Hi, I'm interested in taking on this issue as my first contribution to the Bitwarden project. I believe it would be a great learning opportunity for me, and I'd be happy to help address the problem.

However, I'm still relatively new to the codebase and would appreciate some guidance. Could you please provide a general outline of how to approach this problem, or point me to any relevant sections of the codebase where I should start looking? Any help or tips would be greatly appreciated.

**Comment by djsmith85** [comment]
Hi @ZilongXue,

Thank you for offering your help with this. 

Please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/), these will help you with getting your environment set up and offer further information in regards to contributing. Importers are available on all clients, so it doesn't matter which one you set-up for development.

The `keepassx-csv-importer` is located [here](https://github.com/bitwarden/clients/blob/main/libs/importer/src/importers/keepassx-csv-importer.ts). Unfortunately, there are no unit-tests for this specific importer yet, but all other unit-test can be found [here](https://github.com/bitwarden/clients/tree/main/libs/importer/spec). We'd appreciate if you or anyone else tackling this, could add tests for this importer.

Kind regards,
Daniel

**Comment by ZilongXue** [comment]
Hi @djsmith85 ,

I’ve submitted a PR that fixes the TOTP import issue in the KeePassX CSV importer and added the unit tests. Could you please take a look when you have time and let me know if any changes are needed?

Thanks,
Zilong
