### ISSUE TITLE
Bitwarden Desktop forced log out and cannot log back in (works on website and browser extension)

### ISSUE THREAD

**Issue by bucky-pds** [bitwarden/clients#11602]
### Steps To Reproduce

1. Got logged out of bitwarden enterprise and could not log in again. 
2. Logging in to the browser extension and logging into the web version does work 
3. Logging in with a personal account does work

### Expected Result

That a password manager is reliable and that I can log in and use it.

### Actual Result

Cannot log in. completely locked out of password access. 

### Screenshots or Videos

![Screenshot 2024-10-17 at 11 07 24 AM](https://github.com/user-attachments/assets/549cc9ee-87e9-4a91-bb2b-025461b71633)

### Additional Context

Provide a local only login for a cached version of the vault. This is critical. Also this is the 2nd time in 3 months I've completely lost access to bitwarden password - unacceptable. 

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

Version 2024.9.0 Shell 32.0.1 Renderer 128.0.6613.36 Node 20.16.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by natefabian18** [comment]
I also had this happen just a few moments ago. After a few minutes it seemed to return to normal after a reboot?
# Operating System
Linux Mint 21.3
# Installation method
deb and appImage both had the same issue

**Comment by waifod** [comment]
I experienced the same issue a few minutes ago. Rebooting fixed it.

# Operating system
macOS

## Operating system version
Sonoma 14.7

# Installation method
Via the Mac App Store

# Build version
2024.8.2

**Comment by jtodddd** [comment]
Hi there,

Thanks for reaching out!

Bitwarden has mitigated a temporary disruption to network traffic when logging into the Desktop client. Rules have been adjusted in our security settings to prevent false positives.

Everything should be back in working order now. Please reach out to us using our “Contact support” form located on our Help Center (https://bitwarden.com/help/) if this is still occurring or if you are experiencing any other issues you feel may be related.
