### ISSUE TITLE
[WebSite] CreationDate and RevisionDate of imported data is reset

### ISSUE THREAD

**Issue by wordpure** [bitwarden/clients#11666]
### Steps To Reproduce

1. Export Bitwarden Password Vault to Bitwarden (json) file
2. Go to 'https://vault.bitwarden.com/#/tools/import'
3. Select  'Bitwarden (json)' for the imported file format
4. Import Password Vault File
5. Click on 'Import Data'

### Expected Result

The creationDate and revisionDate of the items should be the same as in the import file.

### Actual Result

The creationDate and revisionDate of the item are reset to the time when the data was imported.

### Screenshots or Videos

![图片](https://github.com/user-attachments/assets/b29b9596-1689-484e-8bba-d1cb053bbec7)

### Operating System

Windows

### Operating System Version

Windows 11 22H2 22621.4317

### Web Browser

Firefox

### Browser Version

131

### Build Version

Sorry, I don't see the version number at the bottom of the vault.bitwarden.com.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@wordpure As mentioned above this is the currently expected behaviour, as items are newly created on import.
The respective feature request on the forums, is: **https://community.bitwarden.com/t/when-importing-vault-items-set-their-created-and-or-updated-dates-based-on-the-imported-data/48542/3**
