### ISSUE TITLE
Desktop Client 2024.10.1 Cannot Log In Using Master Password w/Duo or Windows Hello Biometrics

### ISSUE THREAD

**Issue by ctracy-tsts** [bitwarden/clients#11695]
### Steps To Reproduce

1) Open Desktop Client
2) Attempt to login using Windows Hello or Master Passphrase
3) Fail
4) Repeat

### Expected Result

Successful login to vault using Desktop client

### Actual Result

With Windows Hello, endless loop of authentication popups each saying "Something went wrong"
With Passphrase, spinner icon with eventual "username or password incorrect" message after 20-30 seconds

### Screenshots or Videos

Cannot get any because Desktop client "hides" when attempting to screenshot

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Fjunky** [comment]
I'm having the same problem right now.

**Comment by ctracy-tsts** [comment]
> I'm having the same problem right now.

Seems the latest update has really borked things. I wonder if we can we roll back to an older release?

**Comment by Fjunky** [comment]
> > I'm having the same problem right now.
> 
> Seems the latest update has really borked things. I wonder if we can we roll back to an older release?

Hopefully. Otherwise they should be fixing it soon.

**Comment by andreluizreis** [comment]
I am experiencing the same bug. This is the first time I am using the service and I could not use the desktop app. I was not sure if this was an issue with me or the service.

**Comment by Mictianos** [comment]
Same here, cant login in windows app (wrong passworf/login) but at the same time i can login through web and browser extension.

**Comment by juglanshub** [comment]
I am experiencing the same issue with the desktop app [appimage v2024.10.1] on my two Linux Mint PCs.  
Logging into Bitwarden  via web vault works fine.

**Comment by CM-MBC** [comment]
![image](https://github.com/user-attachments/assets/56405130-60ad-4068-89d0-f4aa3fa4ed95)

I am experiencing the same issue with trying to log in to the windows desktop app with my master password.

**Comment by BBGhub** [comment]
Hi All, 
This should now be resolved

**Comment by ctracy-tsts** [comment]
Confirmed, is working now, thank you! But what was the issue?

**Comment by Euge908** [comment]
Hello. I'm experiencing the same issue with a fresh install of Linux Mint. Logging in via web is fine though. Version installed is 2024.10.1.
