### ISSUE TITLE
Cannot connect BitWarden and DuckDuckGo on macOS

### ISSUE THREAD

**Issue by ivanbarlog** [bitwarden/clients#11692]
### Steps To Reproduce

1. Download and install DuckDuckGo from https://bitwarden.com/download/
 
<img width="568" alt="image" src="https://github.com/user-attachments/assets/81b6acf2-5b62-4d46-a718-755348d4ed53">

2. Install BitWarden from macOS AppStore

<img width="287" alt="image" src="https://github.com/user-attachments/assets/96da2425-39b0-40ba-80e2-9dd8893bc753">

3. Set up BitWarden for DuckDuckGo browser following this steps - https://bitwarden.com/blog/the-first-external-password-manager-built-into-duckduckgo-for-mac/
4. See the following error - it seems like BitWarden wants to open some window with confirmation but it closes automatically and hence the setup is not complete - when I click connect it does not work because it still missing handshake confirmation.

### Expected Result

The integration should work.

### Actual Result

The integration dos not work - see the attached video.

### Screenshots or Videos

https://github.com/user-attachments/assets/0c2be9b0-011b-40ed-b184-45fc0f8248f3

### Operating System

macOS

### Operating System Version

15.0.1 (24A348)

### Installation method

Mac App Store

### Build Version

2024.10.0 (31484)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by syedmhashim** [comment]
(+1) I’m also having the same error

**Comment by cbbit** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by wmkirby1** [comment]
+1 same error

**Comment by zerr0s** [comment]
same here. I’m looking for a new browser to use globally on all my devices and I need some extensions.
Bitwarden is one of them.

https://github.com/user-attachments/assets/23e3544e-c63d-4eb5-b296-e1108c5aa3f4

```
Mac OS: Sequoia 15.0.1
```
```
DDG version: last one (Version 1.110.0 (284))
```
```
Bitwarden:
Version 2024.10.0
Shell 32.1.1
Renderer 128.0.6613.137
Node 20.17.0
Architecture arm64
```

**Comment by 41pie** [comment]
+1, same issue after upgrades,
```
Mac OS: Sequoia 15.0.1
DuckDuckGo: 1.111.0
Bitwarden: 2024.10.0 (31484) connecting to bitwarden.eu
```

**Comment by w1hm1** [comment]
Same issue here. Has someone come up with any workable workaround?

**Comment by siklodi-mariusz** [comment]
+1, having the same issue recently.

```
macOS: Sequoia 15.0.1
DuckDuckGo: 1.111.0 (289)
Bitwarden: 2024.10.0 (31484)
```

**Comment by waddlek** [comment]
Also having this problem!  Would love to stick with Duckduckgo but need Bitwarden too, and it’s not working at all at the moment, just keeps saying I need to unlock Bitwarden, but it’s already unlocked :(

**Comment by graymoment** [comment]
Same issue. When DuckDuckGo browser is open, this happens nonstop. 

https://github.com/user-attachments/assets/a032a606-897a-47c5-9d75-0fed5a9aa82a

**Comment by dawaldow** [comment]
Following to watch progress … same for me … back to Safari for now.

**Comment by graymoment** [comment]
I haven't heard back from Bitwarden yet. If you submit a ticket and hear back, please reply here.

**Comment by RyGuy994** [comment]
+1

**Comment by redeyes85** [comment]
+1

**Comment by kennedyjosh** [comment]
Same issue here. Not able to find any workarounds currently

**Comment by graymoment** [comment]
This setting to _Allow DuckDuckGo Browser Integration_ in _Bitwarden > Settings > App Settings (All Acounts)_ is the causes of the issue. It appears no handshake is happening, or it is being blocked or stopped somehow. 
<img width="494" alt="Screenshot 2024-11-02 at 8 12 22 AM" src="https://github.com/user-attachments/assets/805dae93-c4c2-4179-86ac-476c3c7ef7ec">

**Comment by alazabe** [comment]
Is there any ETA when this will be fixed ?!

**Comment by hevisko** [comment]
https://github.com/bitwarden/clients/issues/11833 -> seems to be the duplicate I commented in before seeing this one

**Comment by TonyPaco** [comment]
After last night's DDG update...

<img width="1136" alt="Screenshot 2024-11-05 at 8 41 23 AM" src="https://github.com/user-attachments/assets/30cd42a0-e0a8-48cf-9c4a-afc0bace6502">

**Comment by waddlek** [comment]
Is there a way to force this to come up? I've done the update of Duckduckgo, but this doesn't dialogue box doesn't appear for me.

**Comment by TonyPaco** [comment]
@waddlek 
That screen was from a fresh install of both.

On my usual daily driver, if I click to use the DDG built-in password manager and then click back to use Bitwarden, I'll get some sort of dialog.

Actually, when I first launched on my usual machine this morning, I had the download button inline with an already-selected Bitwarden:
![Screenshot 2024-11-05 at 12 04 59 PM](https://github.com/user-attachments/assets/9e85e4bb-2bf3-4f07-be9c-3e4725a1a047)

**Comment by psteichen** [comment]
+1 for this same issue

The downgrade seems to work, but one has to watch out because Bitwarden wants to update to a newer version "all the time”. Working with an “old” versin, espcially for sensitive things like passwords, is, of course, not ideal and bit annoying as well.

Looking forward to see a fast resolution of this soon.

**Comment by danieleremchuk** [comment]
+1 same issue

Downgrading to v2024.9.0 works for now, but I am getting constant notifications via macOS to update to the latest version of Bitwarden. Also would prefer to be on the latest and greatest when it comes to security and password management 😅

**Comment by wmkirby1** [comment]
Awfully long time for this bug to go unresolved, when it is fully breaking usage, and this is a paid product... just sayin' Bitwarden team. Is there even an ETA yet? Anyone able to comment on that? @cbbit ?

**Comment by dani-garcia** [comment]
Hey everyone!

Apologies, I didn't realize there was an issue thread without an official response here.

The connection problem with DuckDuckGo was solved in these PRs: #11804 #11878 which were merged a few weeks ago. The 2024.11.0 release from last Thursday contains those fixes, and should fix the connection problems you are all experiencing.

There is still one issue with the DuckDuckGo connection, where if a website has more than 15 or so entries in the Bitwarden vault, they won't be sent correctly to DDG. This is fixed with this yet to be merged PR https://github.com/bitwarden/clients/pull/11987, and will be part of the next release.

**Comment by redeyes85** [comment]
Confirmed that the 2024.11.0 works fine with DDG 1.114.0 (308). Able to connect both DDG and Bitwarden now.

**Comment by cas41pie** [comment]
Seems like there is a regression on this issue again. Same symptoms DDG: 1.141.0 (443) BW: 2025.5.0 (42712)

**Comment by waddlek** [comment]
Yes, also having the same issue, Bitwarden is open, but keeps trying to open again (looks like it's trying to open another instance).

**Comment by edeandrea** [comment]
Same issue here today

DuckDuckGo version 1.141.0 (443)
Bitwarden version 2025.5.0 (42712)
MacOS 15.5

**Comment by waddlek** [comment]
Updated to Bitwarden version 25.5.1, still a problem

**Comment by edeandrea** [comment]
Same here

**Comment by edeandrea** [comment]
I created a new issue (#15104) to track the fact its broken.
