### ISSUE TITLE
Bitwarden Ubuntu app unable to login 

### ISSUE THREAD

**Issue by chris122380** [bitwarden/clients#11701]
### Steps To Reproduce

Unable to login to Bitwarden SNAP, flatpak, or Appimage

### Expected Result

Expect to be able to login with my email and password

### Actual Result

Acts like it's taking a long time to login and then either times out or says incorrect password (it is the correct user name and password). 

### Screenshots or Videos
![Screenshot From 2024-10-24 17-51-43](https://github.com/user-attachments/assets/eede99ef-0a8d-4aa8-8706-4261a5777226)
![Screenshot From 2024-10-24 17-52-37](https://github.com/user-attachments/assets/54569203-4bdf-49e1-ba2d-5c762bcbbedc)

### Operating System

Linux

### Operating System Version

Ubuntu 24.10

### Installation method

Other

### Build Version

Version 2024.10.0 Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chris122380** [comment]
I can login on Android, browser extension, and vault.bitwarden. Just receive the issue on the Linux desktop app builds.

**Comment by sammbw** [comment]
Hello @chris122380,

Thanks for reporting this today - this was a temporary issue and should be resolved now. If that's not the case, please reach out to us using the link below.

Contact Bitwarden: https://bitwarden.com/contact/

Thanks and have a great day!
