### ISSUE TITLE
Can't update desktop Bitwarden- version 2024.10.1

### ISSUE THREAD

**Issue by mburen1956** [bitwarden/clients#11712]
### Steps To Reproduce

4. Click on '...'
The desktop opens a window to update to version 2024.10.1. When updating, a new window opens with the following:"Failed to uninstall old application files. Please try running the installer again.:2"

### Expected Result

I expect Bitwarden to update to the current version - 2024.10.1

### Actual Result

Bitwarden desktop does not update.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @mburen1956,

Thank you for reporting this. I suspect that this could be related to certain security software that's locking Bitwarden files or the installer; You can check if temporarily deactivating such services assists. If that does not resolve this, please consider uninstalling Bitwarden manually and then performing a fresh new installation of the latest version; To be clear, I did not encounter this in my own personal experience or in testing on Windows 11 Pro.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track potential bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by mburen1956** [comment]
I uninstalled Bitwarden and re-installed, and that solved the problem.
Thank You,
mburen1956

**Comment by gitthangbaby** [comment]
this error "Failed to uninstall old application files, Please try running the installer again: 2" interrupts my update process every single time, it's the only user-attended installer out of hundreds (producing a dialog and stopping everything). Why we don't terminate Bitwarden silently? "uninstalling" as a solution, that's some low expectation approach. Luckily we can track #9425.
