### ISSUE TITLE
CORS error during login on Edge

### ISSUE THREAD

**Issue by tcaesvk** [bitwarden/clients#11743]
### Steps To Reproduce

1. Open extension
2. Enter email address
3. Click Continue
4. Enter master password
5. Click "Log in with master password"

### Expected Result

2FA request or successful vault menu.

### Actual Result

Console output in inspector:

> Access to fetch at 'https://api.bitwarden.com/devices/knowndevice' from origin 'chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
api.bitwarden.com/devices/knowndevice:1 
> Failed to load resource: net::ERR_FAILED
> index.html#/login?email=**REDACTED**:1  Access to fetch at 'https://identity.bitwarden.com/accounts/prelogin' from origin 'chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://vault.bitwarden.com' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
identity.bitwarden.com/accounts/prelogin:1 
> Failed to load resource: net::ERR_FAILED

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

130.0.2849.56

### Build Version

2024.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration in your current setup.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by tcaesvk** [comment]
@daniellbw reproduction method has revised:

- Before attempting to log in, change site access permissions for extensions from to [`on specific sites`](https://support.microsoft.com/microsoft-edge/7d1c889d-e267-4be0-15d4-3ed5d0c82ef5#:~:text=.-,On%20%5Bcurrent%20site%5D,-%3A)

This problem was fixed when I [added](https://support.microsoft.com/microsoft-edge/7d1c889d-e267-4be0-15d4-3ed5d0c82ef5#ID0EDD:~:text=%3A-,Add,-%3A) the following sites:

- `https://api.bitwarden.com/*`
- `https://identity.bitwarden.com/*`

In my opinion, this is still a bug because browser extensions are deployed with **misconfiguration**, as such mandatory site accesses are not guaranteed.

- The extension MUST display the diagnostic message correctly [**when permission is requested but not granted**](https://github.com/bitwarden/clients/blob/87cb45c5202599a6daf5c6dc75d7a5cf3863f454/libs/common/src/platform/services/default-environment.service.ts#L361-L403). It should explain what user action is required, not give some misinterpretable internal error.
- The extension MAY also declare [ALL mandatory regional API endpoints](https://github.com/bitwarden/clients/blob/c70a5aa02457e515c6a94854da71e1200ea1b6e2/libs/common/src/platform/services/default-environment.service.spec.ts#L75-L102) formatted as [match patterns](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) as
  ```json
  [
    "https://vault.bitwarden.com/*",
    "https://identity.bitwarden.com/*",
    "https://api.bitwarden.com/*",
    "https://icons.bitwarden.net/*",
    "https://notifications.bitwarden.com/*",
    "https://events.bitwarden.com/*",
    "https://scim.bitwarden.com/v2/*",
    "https://send.bitwarden.com/",
    "https://vault.bitwarden.eu/*",
    "https://identity.bitwarden.eu/*",
    "https://api.bitwarden.eu/*",
    "https://icons.bitwarden.eu/*",
    "https://notifications.bitwarden.eu/*",
    "https://events.bitwarden.eu/*",
    "https://scim.bitwarden.eu/v2/*"
  ]
  ```
  **explicitly** in the [optional_permission](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_permissions#host_permissions) field of [manifest.json](https://github.com/bitwarden/clients/blob/37523ca66b6f4394c58d0a7f48e7cd3b3b547f94/apps/browser/src/manifest.json#L67) and the [optional_host_permissions](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/manifest.json/optional_host_permissions) field of [manifest.v3.json](https://github.com/bitwarden/clients/blob/c88c5bf1ef2a983f0a8c5589c2d5d83fec85b67d/apps/browser/src/manifest.v3.json#L69).
