### ISSUE TITLE
iOS app doesn't display Chinese when language is set to "中文（中国）"

### ISSUE THREAD

**Issue by zhiweizh0ng** [bitwarden/clients#11857]
### Steps To Reproduce

1. Go to 'iOS app'
2. Click on 'settings'
3. Click on 'language'
4. Choose '中文（中国）'

### Expected Result

The interface displays Chinese

### Actual Result

The interface still displays English

### Operating System

iOS

### Operating System Version

18.1

### Web Browser

Chrome

### Build Version

2024.9.2(1106)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/ios/issues/747

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
