### ISSUE TITLE
Zoho importer does not import TOTP seeds

### ISSUE THREAD

**Issue by djsmith85** [bitwarden/clients#11872]
### Steps To Reproduce

When attempting to import TOTP codes from a CSV file exported from Zoho Vault into Bitwarden, the TOTP codes do not appear to be imported correctly.

Steps to Reproduce:
1. Export your vault from Zoho Vault and save it as a CSV file.
2. Log in to the Bitwarden Password Manager/Admin Console.
3. Go to the import section and select Zoho Vault as the source.
4. Upload the CSV file.

### Expected Result

The TOTP codes should be imported and appear correctly in the Bitwarden vault.

### Actual Result

The TOTP codes are not imported or do not appear in the Bitwarden vault after the import process.

### Additional Context

Example file:
```
"Password Name","Description","Password URL","SecretData","Notes","CustomData","Tags","Classification","Favorite","login_totp","Folder Name"
XYZ Test,,https://abc.xyz.de:5001/#/login,"SecretType:Web Account
User Name:email@domain.de
Password:PcY_IQEXIjKGj8YW
",,"",,E,0,otpauth://totp?secret=PI2XO5TW0DF0SHTYOVZXOOBVHFEWM6JU&algorithm=SHA1&period=30&digits=6,someValue,
```

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2024.10

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kshashikumar** [comment]
Hi @djsmith85 ,

Hope this message finds you well, Thank you for giving a wonderful opportunity. Can you assign above issue to me , Just fixed above issue and raised a PR  #11912 , Can you please take a look into it at your convenience and let me know if that is helpful or any further changes needed.

Thank you for your time and consideration.

Regards,
Shashi Kumar Kasturi
