### ISSUE TITLE
Can't accept enterprise sponsorship with existing account

### ISSUE THREAD

**Issue by lus** [bitwarden/clients#11931]
### Steps To Reproduce

1. Receive sponsorship offer to an email of an existing BW account
2. Click on "Create account" (why this terminology? Was the possibility of accepting offers for existing accounts removed?)
3. The `register` query parameter will be set to `true` and you will be prompted to create a new account with the same email your existing account is attached to.
4. Wenn removing the query parameter manually, I am prompted to log in, but my correct credentials are rejected in this case.

### Expected Result

I expect to be able to create a new family organization under my existing account.

### Actual Result

I am prompted to create an account and/or am unable to login otherwise.

### Operating System

Android

### Web Browser

Brave

### Build Version

2024.10.5

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @lus,

Thank you for this report. Could you please contact us via a [support ticket](https://bitwarden.com/help/) so we'd review the Enterprise organization and the existing organization that you're trying to sponsor? Please be sure to include this GitHub report's link in the body of your message.

I will close this GitHub report for now; I'll open it back up in case there indeed is an unexpected behaviour.

Thank you in advance,
