### ISSUE TITLE
Desktop v2024.11.1 - 404 error when installing

### ISSUE THREAD

**Issue by BradleyB-2020** [bitwarden/clients#12003]
### Steps To Reproduce

1. install bitwarden Desktop v2024.11.1
2. run the installer
3. select install for all users and click install
4. confirm install
5. get alert message saying: "Unable to downlaod aplication package from https://artifacts.bitwarden.com/desktop/bitwarden-2024.11.1-x64.nsis.7z (status: File Not Found (404)) Please check your internet connection and retry."

### Expected Result

should've installed normally

### Actual Result

doesn't install - remains stuck on the alert pop-up asking to check internet connection and to retry.

Internet is working fine, and previous version works fine (installed previous version: v2024.11.0 and didn't get this error message).

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

v2024.11.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gilromano** [comment]
I'm seeing the same problem, while previous version (Desktop v2024.11.0) installed just fine a few days ago.
![Untitled](https://github.com/user-attachments/assets/668c07e4-306f-48ec-8b75-aafcdd0a4dd4)

**Comment by djsmith85** [comment]
@BradleyB-2020, @gilromano Thank you for reporting this. Your issue was raised internally and should be resolved now.

Closing this now, but if you are still experiencing issues, please comment here.
