### ISSUE TITLE
Check for Updates not seeing latest available version

### ISSUE THREAD

**Issue by srlennon** [bitwarden/clients#12025]
### Steps To Reproduce

1. Go to 'Help'
2. Click on 'Check for Updates'
3. Wait for result 'No updates are currently available. You are using the latest version'
4. Click on 'Help'
5. Click on About Bitwarden and note the version number

### Expected Result

Expected result of checking for updates should show the latest available version that is available for download from the website.

### Actual Result

Over the last few updates the desktop client fails to see newly published versions available for download when checking for available updates. My current client is displaying version 2024.10.2 and says I am using the latest version even though 2024.11.1 is available for download from your website.

Third Party software update utilities such as UniGetUI correctly show updates as being available via WinGet.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/0d20a81f-ab5e-41a8-9d5a-50c4ada17f5b)
![image](https://github.com/user-attachments/assets/b84084a9-6cb0-4cb7-87ad-4990b1a24247)
![image](https://github.com/user-attachments/assets/242f22de-b7de-4817-9ead-fa2670fa4cfb)
![image](https://github.com/user-attachments/assets/a0c65e9d-ceea-4086-9860-3a65f3cdfba0)

### Operating System

Windows

### Operating System Version

11 24H2

### Installation method

Other

### Build Version

2024.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @srlennon,

Thank you for this report. We release newer versions in a [gradual manner](https://bitwarden.com/help/releasenotes/#release-announcements), and that is why you may see that there's a newer version available on our website and on GitHub whilst it's not being made available through the update function. If you'd like to expedite this, please feel free to download the new version and to update your desktop client by running the latest installer.

I hope you find this clear and helpful; If you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/) with us and please include a link to this GitHub report if you do.

Thank you again,
