### ISSUE TITLE
Bitwarden shield icon blocks the verification code characters

### ISSUE THREAD

**Issue by weijianwen** [bitwarden/clients#12024]
### Steps To Reproduce

1. Try to fill the verification code  in Safari.

### Expected Result

The verification code should be displayed without being blocked.

### Actual Result

Bitwarden shield icon blocks the last verification code character, preventing the users to read the full verification code.

### Screenshots or Videos

The expected result.
<img width="300" alt="截屏2024-11-17 11 12 33" src="https://github.com/user-attachments/assets/71d149f5-2f34-41db-8266-c1994ad7c239">

The actual result.
<img width="288" alt="截屏2024-11-17 11 12 39" src="https://github.com/user-attachments/assets/60591893-e471-4257-a3df-5ca626c995ce">

### Operating System

macOS

### Web Browser

Safari

### Build Version

2024.10.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@weijianwen 

If you press `ESC`, the button should remove itself and remain removed until the form field is refocused. Placement of the button on a form field has it's quirks... but it's not easy to take into account all edge cases.
