### ISSUE TITLE
Beta: Unable to Generate Aliases With Addy.io

### ISSUE THREAD

**Issue by windmueller** [bitwarden/clients#12057]
### Steps To Reproduce

1. Go to 'Generator'
2. Select "Username"
3. Choose 'Addy.io' and fill domain and API key
4. Generate a new alias

### Expected Result

A new alias should be generated.

### Actual Result

An error message appears about an invalid API token.

### Additional Context

The same token works perfectly fine with the stable browser extension.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Brave

### Browser Version

1.73.89

### Build Version

2024.11.999

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!
