### ISSUE TITLE
Password generator lowercase Ascii sets are swapped

### ISSUE THREAD

**Issue by FreeWall** [bitwarden/clients#12098]
### Steps To Reproduce

1. Go to Generator
2. Select "Avoid ambiguous characters" option

### Expected Result

When `Avoid ambiguous characters` option is selected, generated password **does not** contain `l`.
When `Avoid ambiguous characters` option is **not** selected, generated password contains `l`.

### Actual Result

When `Avoid ambiguous characters` option is selected, generated password contains `l`.
When `Avoid ambiguous characters` option is **not** selected, generated password **does not** contain `l`.

### Additional Context

https://github.com/bitwarden/clients/pull/10032
https://github.com/bitwarden/clients/blame/e6c68b7138a7db42fe93434e96f99eac5fba7652/libs/tools/generator/core/src/engine/data.ts#L14-L27

### Operating System

Linux

### Web Browser

Chrome

### Build Version

2024.11.0

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!
