### ISSUE TITLE
Autofill does not work on textarea elements

### ISSUE THREAD

**Issue by TheJoelGray** [bitwarden/clients#1214]
My QNap NAS admin software in a recent update changed their login form's username field to use a `<textarea>` rather than an `<input>` element. Bitwarden no longer auto-fills the username field. I have performed a couple of tests to verify my hypothesis.

1. On my QNap NAS admin login I used Dev Tools to change the HTML from textarea to input and then clicked on the entry in the browser extension again. This caused the username to fill out properly.

2. I went to another site that I have saved in BW and verified that autofill is working. I used dev tools to change the username field from an input to a textarea and cleared the contents. Clicking on the browser extension entry no longer filled out the username.

**Comment by kspearrin** [comment]
Using a textarea for a username input seems quite odd. Can you target it with a custom field?

**Comment by thepaleone** [comment]
Agreed that it's odd, I don't know why the changed it. I'm not sure what you mean by targeting it with a custom field. Can you point me to the right docs on what that provides and how to do it?

**Comment by kspearrin** [comment]
https://help.bitwarden.com/article/custom-fields/

**Comment by thepaleone** [comment]
Huh, I didn't know about that feature, that is very cool! Unfortunately I tried to come up with a solution based on that with no luck. The textarea has the id and placeholder both set to "Username" and none of the other attributes listed in the article are used.

**Comment by lyrixderaven** [comment]
Came to this issue just now, same problem (same QNAP Admin software, it seems). Can confirm behavior, and also tried custom field, incl. regex matching. Textarea fields seem to be exempt from the search patterns.

**Comment by PaulMeadSiliconBullet** [comment]
I can confirm that this is an issue for me too.

**Comment by abrewner** [comment]
Same issue here. It was also my first thought that a custom field would solve the problem (as it does on other sites too), but no luck on the QNAP login page.

**Comment by TheJoelGray** [comment]
As a temporary stop-gap I simply found the login page on my QNAP system and edited it, changing the element to a <input type="text"> tag. It seems to work just fine that way; however when I perform firmware upgrades I have to go do it again. Fortunately it's a quick fix.

**Comment by bassarf** [comment]
+1
maybe this suggestion would be elegant: https://community.bitwarden.com/t/bitwarden-doesnt-scan-the-textarea-field/12586

**Comment by upscalebaby** [comment]
Interesting, I found this page via Google after looking for solutions as to why textArea doesn't respect autocomplete.

I'm not sure if this applies to this thread/issue, but it sounds like it.

From a clean html-document I create a from with a submit button and a textarea with autocomplete="on". It never works. If I switch the textarea for an input element it works fine...

Tried on FF and Chrome to no avail. The docs says it's supported and should work (given that the requirements listed, which I've ensured are met): https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

**Comment by zhaoyibo** [comment]
@TheJoelGray I found a simple greasemonkey script that converts the username field into an 'input' which allows autofill to work. 
You just need to modify the "@match" field to your qnap address. Here is the link to the script: https://greasyfork.org/en/scripts/419313-fix-qnap-qts-username-autofill/code

**Comment by egooner** [comment]
I found this issue also with QNAP. It does not work with Custom Fields.
I created a dummy Web Page and tested it 
`
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Simple Auto Type Test Page</title>
  </head>
  <body>
    <label for="simpleinput">Simple Input</label>
    <input id="simpleinput" autocomplete="off" placeholder="User Input"/><br />
    <label for="simpletextarea">Simple TextArea</label>
    <textarea id="simpletextarea" autocomplete="off" placeholder="User TextArea"></textarea><br />
    <label for="simplepassword">Simple Password</label>
    <input id="simplepassword" type="password" autocomplete="off" placeholder="User Password" /><br />
    <label for="simpledata">Simple Data</label>
    <input id="simpledata" autocomplete="off" placeholder="Data Value" /><br />
  </body>
</html>
`
The Simple Input and Simple Password fields got filled in my the standard fieldsm the Simple Text Area did not get filled by the Custom Field and the Simple Data got filled in by another Custom Field. I also toggled autocomplete from off to on and it made no difference.

Not sure if this issue is specific to QNAP - but it is rather frustrating!

**Comment by levihb** [comment]
Yeah this is still an issue. It's frustrating because it makes it unusable on QNAP.

**Comment by SVNKoch** [comment]
having this problemm too on another page.

**Comment by fabiengagne** [comment]
I have reported the issue to QNAP through a support ticket, asking to change the textarea class to an input class. They said they will send the request to their development team, but somehow I doubt they will actually do anything.

**Comment by televisi** [comment]
For those of you looking for a workaround, this [reddit poster](https://www.reddit.com/r/Bitwarden/comments/idrri0/comment/ghchukd/?utm_source=reddit&utm_medium=web2x&context=3) provided one - that you might find it useful using greaseMonkey extension: [here](https://greasyfork.org/en/scripts/419313-fix-qnap-qts-username-autofill/code)

**Comment by fabiengagne** [comment]
Someone made a pull request that should fix this issue. [4155](https://github.com/bitwarden/clients/pull/4155)

**Comment by olluz** [comment]
I wonder why such a small change takes several years to fix. Even worse: Now with an already available PR...Nobody cares to review it ???

**Comment by vinada** [comment]
Sad and problem still here with QTS 5.0.1.2376.
