### ISSUE TITLE
Firefox Passphrase Generator Stuck

### ISSUE THREAD

**Issue by justinmahendra** [bitwarden/clients#12169]
### Steps To Reproduce

On generator page firefox. If password is set to passphrase the number of words is stuck at 6. Manually setting it does not work. Neither does using the arrows.

### Expected Result

Able to decrease said number

### Actual Result

Stuck at 6

### Screenshots or Videos

https://github.com/user-attachments/assets/7cf70de1-8d24-42a6-901f-a18710a86aa7

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.11.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NeuWasFlaggedAgain** [comment]
I'd feel better if it was a config option, but just having the minimum 6 words made it seem stuck/broken to me. Should this change be brought back, a small warning above about this limitation would've be nice too!
