### ISSUE TITLE
Titlebar without window control buttons in Wayland

### ISSUE THREAD

**Issue by diogopessoa** [bitwarden/clients#12197]
### Steps To Reproduce

1. Install and open Bitwarden Flatpak
2. Bitwarden opens without window control buttons

![Captura de tela de 2024-12-01 09 40 50](https://github.com/user-attachments/assets/58116737-cab1-4435-96a9-942e5a9d98fa)

### Expected Result

The titlebar should have window control buttons

### Actual Result

On elementary OS this bug only occurs in Wayland session. In the X11 session the titlebar works normally.
I verified that in fedora 41 with gnome this bug does not exist in either Wayland or X11.

### Operating System

Linux

### Operating System Version

elementary OS 8

### Installation method

Other

### Build Version

version 2024.11.2 

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by diogopessoa** [comment]
It's probably connected to Pantheon Desktop.

**Comment by diogopessoa** [comment]
I don't know what happened that now the window control buttons appeared. 
Anyway, thanks for your attention!
