### ISSUE TITLE
MacOS Desktop App With DuckDuckGo integration JavaScript Error Popup

### ISSUE THREAD

**Issue by giovai** [bitwarden/clients#12283]
### Steps To Reproduce

1. Enable DuckDuckGo integration, following steps in https://bitwarden.com/help/duckduckgo-macos-browser-integration/
2. Unlock Bitwarden Vault
3. Navigate to any website in DuckDuckGo
4. JavaScript Popup presented

The error does not always show. Seems related to blocking the cookies banner or maybe other tracking features.

### Expected Result

No Error Occured

### Actual Result

Intermittent JavaScript Error PopUp

### Screenshots or Videos

![Screenshot 2024-12-07 at 14 23 05](https://github.com/user-attachments/assets/2eda2bcc-7d32-46ec-a0d7-f6c872c0b2d8)
<img width="178" alt="Screenshot 2024-12-07 at 15 01 04" src="https://github.com/user-attachments/assets/5fda3375-579b-4459-b079-b97675b19322">

### Additional Context

Attached Sreenshot of the error and the Bitwarden client app settings.

System Info:
Bitwarden Version: 2024.11.2 (33636)
DuckDuckGo Version: 1.115.0 (314)
MacBook Pro: 14-inch, 2021, Apple M1 Pro
macOS Version: 15.1.1 (24B91)

Also raised issue in this DuckDuckGo repository: https://github.com/duckduckgo/macos-browser/issues/3647

### Operating System

macOS

### Operating System Version

15.1.1 (24B91)

### Installation method

Mac App Store

### Build Version

2024.11.2 (33636)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

This seems related to https://github.com/bitwarden/clients/issues/11818

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by giovai** [comment]
Hi @NovaSilentium,

I don’t think these are related. #11818 mentions issues with enabling the integration at all. In my case, I am able to authenticate and use the auto-fill feature in DuckDuckGo with Bitwarden.

**Comment by SergeantConfused** [comment]
Hello @giovai,

Thank you for following up on this. Could you please review this [GitHub report](https://github.com/bitwarden/clients/issues/12190) and let me know if it seems similar to yours?


Thank you in advance,

**Comment by giovai** [comment]
Hi @SergeantConfused, yes I think it’s similar, although it has fewer details, so I can’t be sure.
