### ISSUE TITLE
Can not choose bitwarden.eu

### ISSUE THREAD

**Issue by jandeuss** [bitwarden/clients#12315]
### Steps To Reproduce

1. Start the bitwarden Desktop App
2. Click on server bitwarden.eu

### Expected Result

bitwarden.eu Server location is selected

### Actual Result

bitwarden.com is the selected server location

### Screenshots or Videos

https://github.com/user-attachments/assets/05cdb3ca-2abe-4bfb-9096-b07a7747b536

### Operating System

Windows

### Operating System Version

23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.11.2 Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

Let me know if that helps.

**Comment by jandeuss** [comment]
Hello @Krychaz 

thank you for your answer. The problem is solved and the application works fine now.

**Comment by jandeuss** [comment]
Problem solved
