### ISSUE TITLE
Web app: Generator page: the buttons aren't round

### ISSUE THREAD

**Issue by Tipoff4317** [bitwarden/clients#12344]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/tools/generator
2. The Regenerate and Copy Password buttons aren't round like the rest.

### Expected Result

Round buttons

### Actual Result

Square buttons

### Additional Context

* Minor visual aberration on the new style web.

### Feedbacks
I would like to give a compliment that it looks nicer, starting right from the login page.  Feels more like an app, rather the old-style web app (that feels like a client-server HTML-style app ).  Not sure if it is faster than the old web app or not, but it feels like it (or maybe the app look fools me to think so).

From a quick look, it's a wonderful improvement.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

128.5.1ESR

### Build Version

2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Tipoff4317,

Thank you for the praise on the new UI.

The generator page has also been re-written but didn't make the cut for 2024.12-release. It's currently behind a separate feature flag. The new look will be available on the browser extension with 2024.12 and will likely follow on web and desktop with the 2025.1 release.

As this is already addressed/scheduled I'll go ahead and close this issue.

Kind regards,
Daniel
