### ISSUE TITLE
Unable to Delete WebAuthn Key Registered for Two-Step Login

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#12351]
### Steps To Reproduce

1. Go to "Two-Step Login" configuration page in Web Vault.
2. Click <kbd>Manage</kbd> for the two-step login provider category "Passkey".
3. Register a Yubikey, and click <kbd>Save</kbd>.
4. Click <kbd>Manage</kbd> for the two-step login provider category "Passkey".

### Expected Result

Expect to see an option in the UI for deleting the individual passkey that was just registered.

### Actual Result

There is no UI option to delete individual passkeys, only an option to "Deactivate **all** keys".

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/853a6d3e-0c1a-46ba-a1df-2fa66b5544ae)

### Additional Context

In case it makes a difference for reproducing this bug, this was observed while logged in to the Web Vault using _passkey_ login (in fact, the same passkey that was registered in the two-step login setup described in the above tests).

### Operating System

Windows

### Operating System Version

23H2 (OS Build 22631.4460)

### Web Browser

Chrome

### Build Version

2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Option to delete individual keys should appear once you add more than one key, as seen here:

<img width="724" alt="SCR-20241211-ogxo" src="https://github.com/user-attachments/assets/5850aacd-9dcf-42bf-a2e4-6d431221f32e" />
