### ISSUE TITLE
No prompt for passkeys in latest Google Chrome

### ISSUE THREAD

**Issue by bvinnerd** [bitwarden/clients#12366]
### Steps To Reproduce

1. Go to a website where you have a passkey stored in BW for that site
2. Attempt to sign in using a stored passkey

### Expected Result

Bitwarden window should open asking to confirm which passkey to use

### Actual Result

Chrome's own passkey mechanism is used

### Screenshots or Videos

<img width="463" alt="Screenshot 2024-12-12 at 21 26 33" src="https://github.com/user-attachments/assets/ecb8d1ce-a0fd-46bc-b633-f9e2f7172a11" />

### Additional Context

Problem is on BW client 2024.11.2 (current) and 2024.11.9991 (beta)

In both current Chrome and Chrome Canary:
- Version 131.0.6778.140 (Official Build) (arm64), and
- Version 133.0.6891.0 (Official Build) canary (arm64)

BW works fine in Safari

### Operating System

macOS

### Operating System Version

Sequoia 15.2

### Web Browser

Chrome

### Browser Version

131.0.6778.140 (Official Build) (arm64)

### Build Version

2024.11.2 and 2024.11.9991

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @bvinnerd

Could you please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/). This will enable our support team to review your case. You may include a link to this issue in the message content for reference.

Thanks!
