### ISSUE TITLE
Error when setting up passkey on LinkedIn

### ISSUE THREAD

**Issue by ocrete** [bitwarden/clients#12380]
### Steps To Reproduce

1. Go to linkedin.com
2.  Go to "settings and privacy"
3.  Select "sign in and security"
4. Select "Passkeys"
5. Click on "Create a passkey"
6. Enter password
7. Select the linkedin login in the Bitwarden window that popup up, and select save
 

### Expected Result

The passkey is created succesfully and save

### Actual Result

The passkey is saved in bitwarden, but LinkedIn gives an error:

> Sorry, something went wrong. Please try again. 

### Operating System

Linux

### Operating System Version

Fedora 41

### Web Browser

Firefox

### Browser Version

132.0.1 (64-bit)

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/7545

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by mxxcon** [comment]
@cbbit I believe the problem in this issue is different from #7545.
Here Bitwarden does recognize LinkedIn's request to create a passkey and saves it properly, but for whatever reason LinkedIn says there's an error.
