### ISSUE TITLE
Copying a value to clipboard yields an empty tooltip

### ISSUE THREAD

**Issue by lflaurflorin** [bitwarden/clients#12413]
### Steps To Reproduce

1. Open Bitwarden Desktop client version 2024.12.0
2. Select a category that has a user/password
3. Copy the password (click the Copy icon)
4. The tooltip will show as empty with no text

### Expected Result

The tooltip should have contained a text explaining the action ("Value has been copied to clipboard" for example)

### Actual Result

The tooltip is empty

### Screenshots or Videos

![err](https://github.com/user-attachments/assets/885bc9a7-7873-4a4a-861f-1aece88fc566)

### Operating System

Windows

### Operating System Version

Microsoft Windows 11 [Version 10.0.26100.2605]

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.12.0 SDK 'main (edee180)' Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lflaurflorin** [comment]
Hi there. 
I tried to change the theme of the app to Light, and now the tooltips show properly. 

They still don't show under the Nord theme that I was previously using. 

I can use the Light theme from now now. 

Thank you for checking !

**Comment by emichael** [comment]
@Greenderella This should be re-opened. There's a bug with the Nord theme on the Chrome extension. The popups aren't empty, the text is just too light to read.
