### ISSUE TITLE
No option for ssh keys in 2024.12.0

### ISSUE THREAD

**Issue by heathcliff26** [bitwarden/clients#12411]
### Steps To Reproduce

1. Update to latest Desktop version 2024.12.0
2. Create New Entry

### Expected Result

I can create a new entry of the type ssh key and use it for my ssh agent

### Actual Result

Only the old types are available

### Additional Context

In the release notes of 2024.12.0 ssh key support is written as the new feature for the release, but i can't find it in the client.

### Operating System

Windows, Linux

### Operating System Version

win11, F41

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version 2024.12.0 SDK 'main (edee180)' Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Erd89** [comment]
same thing on newly updated iOS and macOS clients :(

**Comment by heathcliff26** [comment]
Yes, browsing through the git history, i think it might be hidden behind a feature flag?
See: https://github.com/bitwarden/clients/commit/9b58e111c7538fe4bb0b5cfd834ea91676025948
But when looking through the docs, it seems feature Flags are server side only? So if i get that right Bitwarden would need to enable it on their servers so we can see it in the client?

**Comment by SergeantConfused** [comment]
Hello @heathcliff26,

Thank you for this report. Whilst we do mention that in the [GitHub repository](https://github.com/bitwarden/clients/releases/tag/desktop-v2024.12.0), it's currently behind a feature-flag; we'll roll out that function in the near future. Please feel free to subscribe to the Bitwarden [Release Announcements](https://bitwarden.com/help/releasenotes/#release-announcements), if you'd like to stay in the loop.

I will now close this GitHub report; if you have any questions of concerns, please feel free to [get in touch](https://bitwarden.com/help/) with us and please include the URL of this GitHub report if you do.

Thank you again,
