### ISSUE TITLE
Bring back separate password and username icons.

### ISSUE THREAD

**Issue by Hatchtek** [bitwarden/clients#12419]
### Steps To Reproduce

open Bitwarden Icons missing from vault

### Expected Result

Separate icons for Username and Password.  

### Actual Result

It's in a copy subsection. More clicks required.

### Additional Context

Can we put the icons for separate Username and Copy? 

!. it was less clicking
2. It was good visually to see if there was a Username or Password for the item.

I understand yall want it to look better but adding more steps and taking features away in not in the right direction

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Microsoft Edge

### Build Version

Version: 2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by DavidSpackman** [comment]
+1

**Comment by micahblut** [comment]
Thank you for providing the feedback. Since this is an intentional change, I am going to close the bug report, but you are welcome to create a topic in the discussions section so others can weigh in.
