### ISSUE TITLE
Some issues with SSH-Key management

### ISSUE THREAD

**Issue by WRW001** [bitwarden/clients#12412]
### Steps To Reproduce

1. Update to the latest desktop client.(2024.12.0)
2. Create or import a new SSH-Key entry(RSA\ECDSA\ED25519\ED448).

### Expected Result

The keys(RSA\ECDSA\ED25519\ED448) can be created or imported.

### Actual Result

1. Only OpenSSH generated 70-linewidth(70 characters pre line) ED25519 or RSA key can be imported.
2. Only RSA and ED25519 keys are supported, the ECDSA(any curves) and the ED448 are not yet supported, even if they have been formatted to 70-linewidth.
3. The format of the keys is too strict to 70-linewidth. The most common is 64-linewidth, so there is a serious compatibility issue with the current implementation. In other words, most 3rd party generated keys can not be imported.

### Additional Context

https://github.com/dani-garcia/vaultwarden/discussions/5158

### Operating System

Windows

### Operating System Version

Windows 11 23H2 and 24H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.12.0 SDK 'main (edee180)' Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @WRW001,

Thank you for this report.
1. The SSH vault item-type is currently unavailable generally; it's behind a feature-flag at this time.
2. The SSH vault item-type is designed to store RSA and ED25519. If you'd like to include support for ECDSA, for example, that'd be considered an improvement suggestion/feature request, and in that case it'd be best to submit it via the [Bitwarden Community](https://community.bitwarden.com/c/feature-requests/5).
3. With regard to the line width matter, we've been looking into that internally.

At this stage, I'll proceed and close this GitHub report; if you have any questions or concerns, please feel free to [get in touch with us](https://bitwarden.com/help/) and please include a link to this GitHub report if you do create a support ticket.

Thank you again,
