### ISSUE TITLE
BUG: Bitwarden still force disabling Chrome's address and card autofill "Bitwarden Password Manager is controlling this setting"

### ISSUE THREAD

**Issue by godzfire** [bitwarden/clients#12435]
### Steps To Reproduce

**BUG: Bitwarden still force disabling Chrome's address and card autofill**
(as originally posted here: https://sh.reddit.com/r/Bitwarden/comments/1he97b9/bug_bitwarden_still_force_disabling_chromes/)

Essentially the same problem encountered from the below thread, where installing Bitwarden and setting it as default password manager disables and forces control over Chrome's address and card autofill with this message "Bitwarden Password Manager is controlling this setting":
https://www.reddit.com/r/Bitwarden/comments/1ck8jo5/bitwarden_disables_chromes_autofill_for_addresses/

I did the same thing that was suggested and uninstalled/reinstalled. It seemed to fix it at first after selecting the option to make Bitwarden the password manager and the Chrome address/card autofill were still separate. However just to make sure I went back in the settings to double check. Sure enough the checkbox was again blank. Clicked it again, and boom, it took over the other autofills.

The problem still exists. Because Bitwarden struggles properly filling in address/card fields vs Chrome's built in one, I use those instead. I came from LastPass which allowed this. Bitwarden shouldn't be brute forcing itself.

### Expected Result

We're allowed to use Chrome's address and credit card autofill if we want separately of Bitwarden's.

### Actual Result

Bitwarden takes them over and just has the message 'Bitwarden Password Manager is controlling this setting'

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/787a0f2c-e8e2-4024-92a0-641e8d73027d)

### Operating System

macOS

### Operating System Version

OS Monterey 12.7.6 (21H1320)

### Web Browser

Chrome

### Browser Version

131.0.6778.140 (Official Build) (x86_64)

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by godzfire** [comment]
This is definitely not proper intended behavior of the software as confirmed by BT tech support I reached out to who told me to open an issue here (email thread proof below). LastPass does not do this and allows you to choose if you want to use Chrome's built in solutions or LP's.

Kindly requesting this be reopened.

--------------------
On 12/16/24 7:19 PM, Bitwarden wrote:
Thanks for reporting this today - this issue has been previously reported

While I’m unable to provide an ETA for a fix, I would expect to see one introduced in a future update to the Bitwarden extension.
 
Kind Regards, Ben
--------------------
On Thu, Dec 19 at 6:07 PM , GodzFire wrote:
Since this issue affects me daily, I'd appreciate if I could be kept apprised of the status of this support ticket issue until it's been resolved. Is there a github entry or bugtracker link I can reference?
--------------------
On 12/20/24 1:05 AM, Bitwarden wrote:
Hi GodzFire,
This GitHub issue exists with this reported behavior: https://github.com/bitwarden/clients/issues/12435

If this is a duplicate, it will be merged with another entry after a member of our team is able to review it. Otherwise, the GitHub issue will be the best place to track any updates related to this.
​
Regards, Ryan

**Comment by davidwf1** [comment]
This should not have been closed.... it is STILL an issue, Brave saying it's a BW problem, BW saying its a chrome problem....it needs sorting somewhere
Unbeknown to me this is a known issue, found after I created a new thread here      https://community.brave.app/t/brave-card-manager/645786/7
