### ISSUE TITLE
Biometrics unlock breaks the extension and browser's internet connection on 2024.12.0 in Floorp (Firefox)

### ISSUE THREAD

**Issue by Lernos** [bitwarden/clients#12430]
### Steps To Reproduce

Windows 10 x64, Floorp browser Version 11.21.0 (64-bit) | Firefox: 128.5.0
I installed the [latest release](https://github.com/bitwarden/clients/releases/tag/browser-v2024.12.0) manually by dragging dist-firefox-2024.12.0.zip into the extensions page.

On the surface, it appears to be working fine, the new UI is there, the vault can be unlocked with a PIN or master password, the logins and passwords autofill correctly etc. However, when I try to unlock it with biometrics using Windows Hello + USB fingerprint reader + Desktop Bitwarden (version 2024.12.0), something weird happens.

### Expected Result

I expected for the vault to unlock and for everything to work as intended.

### Actual Result

The vault unlocks as it's supposed to, even showing you the number of available entries for the current site if applicable. However, the extension itself doesn't "open". If you click on the extension's icon, a grey "skeleton" rectangular window appears, indicating that the vault is loading. The vault, however, never loads (I didn't bother waiting longer than 3 minutes). What's worse, if you click away from the extension's icon, trying to click on the extension again won't even bring out the "skeleton" form. In fact, none of the extensions work anymore, clicking on any of them does nothing. The entire browser seems to lose connection to the internet, or is at the very least unable to load any online content. No sites will load.

### Screenshots or Videos

https://github.com/user-attachments/assets/ddab6cde-6d39-43cb-af24-74eef6f897ac

Don't mind the fingerprint scanner saying it can't recognize my finger at first, I readjust it, and the vault "unlocks" a moment later, as indicated by its extension icon switching from "locked" to "1 entry detected for this site".

### Additional Context

I suppose I should point out that the biometrics unlock works perfectly on my Desktop app on the newest version, and worked just fine on the Firefox browser extension on the previous build version (2024.11.2).

### Operating System

Windows 10

### Operating System Version

22H2 OS Build 19045.5247

### Web Browser

Firefox

### Browser Version

128.5.0

### Build Version

2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
@Lernos thank you for the report.

We have been able to reproduce this internally and are working on a fix.

**Comment by trmartin4** [comment]
@Lernos this has been addressed in version `2024.12.3` of the browser extension.  We'll be closing this issue, but if you continue to encounter any issues please feel free to re-open or open another issue.
