### ISSUE TITLE
The buttons for copying login, password and OTP code have disappeared

### ISSUE THREAD

**Issue by illia-weisser** [bitwarden/clients#12442]
### Steps To Reproduce

1. Go to any website
2. Click on bitwarden plugin icon 

### Expected Result

See buttons for copying login, password and OTP code

### Actual Result

There is no button to copy login, password and OTP code

### Additional Context

Who is this mega-brain who came up with this design? First you broke the extension and now you have to wait three seconds for the extension panel to open. Now you have removed the buttons for copying the most important data.

Now I have to click on the account, watch this slow animation with the data appearing. And only then I can copy the login, password or OTP code. WTF, guys?

Bring back quick access to important buttons

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

Version 131.0.6778.140 (Official Build) (x86_64)

### Build Version

Version: 2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by illia-weisser** [comment]
What feature requests? You broke something that had been working for years with your new design.

**Comment by djsmith85** [comment]
@illia-weisser This was removed with 2024.12. Based on feedback there's a new option within the settings that was implemented with https://github.com/bitwarden/clients/pull/12428.

Those changes are available with 2024.12.2

**Comment by illia-weisser** [comment]
Nice, thanks!
