### ISSUE TITLE
New extension Tab 'button' missing, small Fill button

### ISSUE THREAD

**Issue by yRob69** [bitwarden/clients#12456]
### Steps To Reproduce

New version just appeared 2024.12.2 Chrome/Brave browser
TAB is missing which would show current page login/s. Now current login shows on top of All Items
Fill button is too small.

### Expected Result

The function of the the 'old' extension was much much better.

### Actual Result

TAB is missing which would show current page login/s. Now current login shows on top of All Items
Fill button is too small.

### Operating System

Windows

### Operating System Version

11 Pro

### Web Browser

Chrome, Brave

### Browser Version

Latest on both

### Build Version

2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ps-tunnelsoft** [comment]
How did the layout change get through testing? I want my "tab" button back. Showing only the tresor with ausfill entries from current website on top is not a solution. This is simply bad. Give the option to activate the old layout. 

![image](https://github.com/user-attachments/assets/a3e89ba9-d66d-4ce6-a090-0799417d0f8c)

How would I access those button as shortcuts in the new version? 

![image](https://github.com/user-attachments/assets/948e9e77-b266-4049-8fb0-5cfe297e136d)

Just give the old layout back. The new stuff is just stupid and reduces functionality.

**Comment by luetm** [comment]
While I understand that creating a new UI always ticks off users, I really struggle to understand why "Fill" is a secondary action now. 99% of the time I open the extension i want to _fill_, maybe 1% of the times I want to _show or edit_ the entry.

At the moment, editing the thing is clearly primary, while "Fill" is secondary. What was the reasoning behind this? Could we flip t hat round, and have a "Details" or "show" button?
