### ISSUE TITLE
View modal no longer shows full URI/URL

### ISSUE THREAD

**Issue by Schweinepriester** [bitwarden/clients#12465]
### Steps To Reproduce

1. Have an entry with a URI which contains not just a domain, but a protocol and a path, for example `https://www.paypal.com/signin`
2. View the entry
3. URI is truncated, both at the start and end, basically to (sub)domain only, e.g. `https://www.paypal.com/signin` becomes `www.paypal.com`

### Expected Result

URI is not truncated

### Actual Result

URI is truncated, both at the start and end, basically to (sub)domain only, e.g. `https://www.paypal.com/signin` becomes `www.paypal.com`

### Screenshots or Videos

Actual entry:

![image](https://github.com/user-attachments/assets/c06f63c1-1012-4a59-a75e-2ecd245841f1)

View result:

![image](https://github.com/user-attachments/assets/b8287114-f2d8-48f1-bbf1-3ab588c4f620)

### Additional Context

OS & Browser versions most likely do not matter for this bug report.

I believe this changed with the recent redesign and I would suspect is a conscious design decision from your side.

Now you might think for the given PayPal example it does not really matter, which might be fair, but consider having multiple different entries under the same domain - how to distinguish then without going into edit mode and having to manually copy instead of being able to the the new tab button?

Here's a real example from my vault:

![image](https://github.com/user-attachments/assets/d2925c5c-9c4d-44d2-8630-76f86a3eafde)

Edit reveals:

![image](https://github.com/user-attachments/assets/9b00d514-c2ec-4324-ad6d-d90d1e92e21e)

If you will not change it generally to always show the full URI/URL, I'd really like to strongly ask for an option in the settings, e.g. "Always show full URI", default off if it needs to be.

---

Leaving the concrete topic and going meta:
I would even challenge the decision to hide parts of the URL in the first place - much like Safari and somewhat recent Chrome (following much drama) defaulting to only showing the domain in the address bar is not beneficial to the web imho.
"Normal users don't understand the complexity of URLs" - maybe, but then hiding is not the way, educate instead!
Esp. for something so relevant to security.

Coming back to Bitwarden, esp. for a password safe which is likely to be used by more tech-savvy people anyway, I really think the "complexity" of URIs should not be hidden for security and ease of use sake, or at the very least have the option to be brought back.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

131.0.6778.140

### Build Version

2024.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Schweinepriester** [comment]
Huh, it seems I'd partially need to eat my words.

But I really would have sworn that I previously was able to distinguish in the view mode between the different `mein.gebuhrenfrei.com` and just click the new tab button to go were I wanted…

Are you by any chance more easily able to spin up the state from a few months ago, say three? Was it really the same truncation there…? 🤔

**Comment by jtodddd** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). Which as mentioned above, it looks like this request does exist already. So, you can vote for it and contribute to any discussions about it. 

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
