### ISSUE TITLE
Cannot renew premium subscription in web vault on Firefox

### ISSUE THREAD

**Issue by fijibestwater** [bitwarden/clients#12567]
### Steps To Reproduce

1. Open https://vault.bitwarden.com/#/settings/subscription/premium
2. Click account credit for payment method
3. Select Country
4. Type zip code
5. Click submit button

### Expected Result

Payment is accepted and premium features are unlocked

### Actual Result

throws:

An error has occurred.

null has no properties 

### Operating System

Windows

### Operating System Version

10 

### Web Browser

Firefox

### Build Version

2024.11.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarikaBW** [comment]
Hi there!

This is a known issue which our team is aware of, more information can be found here: https://bitwarden.com/help/billing-faqs/#q-an-error-occurs-when-i-try-to-go-premium-on-firefox-how-do-i-fix-this

This issue will now be closed.

Thanks!

**Comment by fijibestwater** [comment]
I have tried firefox in private browsing mode, Zen browser, and LibreWolf and i have gotten the same error with each one. i even removed all extensions from each browser and still got the same error.
