### ISSUE TITLE
New Chrome extension "fill" button is hard to hit

### ISSUE THREAD

**Issue by bafulton** [bitwarden/clients#12565]
### Steps To Reproduce

Before the UI update, clicking on a set of saved credentials would autofill them into the login form on the page. Now you have to click the "fill" button, which is a small, hard-to-hit button.

### Expected Result

Preserve old UI functionality.

### Actual Result

Now you have to hit a "fill" button which is much smaller and harder to hit.

### Screenshots or Videos

<img width="380" alt="Screenshot 2024-12-23 at 19 32 00" src="https://github.com/user-attachments/assets/a16ed8c3-0879-4f21-ba02-eb57d149e3e8" />

### Operating System

macOS

### Web Browser

Brave

### Build Version

2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarikaBW** [comment]
Hi,

Thank you for contacting Bitwarden support and for sharing your feedback on the new browser extension user interface.

The team enlisted a large group of current Bitwarden users and companies that use Bitwarden as part of the alpha and beta tests for the new design refresh. Their feedback was incorporated, along with the feedback of internal Bitwarden team members, throughout the process.

The product team is continuing to gather feedback from the community and planning future improvements. Bitwarden maintains a regular release schedule and the team will continue working to improve Bitwarden for all users.

Please share additional feedback in this thread on the Bitwarden community forum: https://community.bitwarden.com/t/usability-issues-ux-in-redesigned-ui-2024-12-0/76836 

I'll now close this ticket

Kind regards

**Comment by wesinator** [comment]
that is sort of astonishing if a statistically significant portion of companies gave feedback leading directly to this change.
This is also an issue with the updated Bitwarden extension in the Firefox browser, and there are several issue reports here and mentions in the forums.
I do think the previous UI was easier to use, and changes to usability and workflow should be considered and evaluated more than cosmetic or stylistic changes.

[NO_TRAIN]::
