### ISSUE TITLE
Improper handling of translation token "viewItemHeader"

### ISSUE THREAD

**Issue by poschi3** [bitwarden/clients#12564]
### Steps To Reproduce

1. Set language to German
2. Go to vault item (e.g. credentials)
3. Look to heading

### Expected Result

"Zugangsdaten ansehen"

### Actual Result

"zugangsdaten ansehen"

### Screenshots or Videos

![grafik](https://github.com/user-attachments/assets/513e3b72-2c67-4562-a08d-7e08d55fea4e)

### Additional Context

Problem is that translation string in englisch is `View $TYPE$` and so code does a `toLowerCase`on `$TYPE$`. But in German grammar it must be the other way around: `$TYPE$ ansehen` and the the `toLowerCase` leads to a grammar error.

https://github.com/bitwarden/clients/blob/395258d63ed39305a6fa7f21becbc842210a8db5/apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts#L146-L162

There is already a [discussion on Crowdin](https://crowdin.com/editor/bitwarden-browser/26/en-de?view=comfortable#44364) but it can't be fixed in translation strings only

Problem also exits for Cards and all other item types

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Web Browser

Firefox

### Browser Version

133.0.3

### Build Version

2024.12.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Thanks for the report @poschi3 

I was also following the forum thread and opened a PR to address this.

This will likely be included and fixed in the next release.

Greetings from Germany!
