### ISSUE TITLE
Usability decreased extremly with last update

### ISSUE THREAD

**Issue by pokecheater** [bitwarden/clients#12575]
### Steps To Reproduce

Hey Bitwarden Team,

This might sound like I am joking, but I am really serious about the following issue.
Since a recent update, I have to click twice to copy my password. As an IT Administrator, it is part of my daily routine to frequently copy passwords from Bitwarden. Each additional click drives me crazy >:-D.

You can ee what I mean here:
<img width="234" alt="image" src="https://github.com/user-attachments/assets/4a5c8534-71a3-449a-993c-df756cc6cde7" />

Before I was able to copy the password with just one click, now a wild context menu appears and I have to beat it first.
Would be lovely If you can bring back the old one click password function back.
(But really: Why this context menu? Who cares about the user name?)

Greetings and have a nice christmas.

### Expected Result

Copy password directly

### Actual Result

A wild context menu appears

### Operating System

iOS

### Web Browser

Brave

### Build Version

1.73.97

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by boneitis** [comment]
+1 this is a massive slowdown in workflow. In today's age of short-lived sessions and already constantly having to re-login to many of my day-to-day accounts _several_ times even within the same day, this is painful. Respectfully, I ask development to revert this design, please.

**Comment by pamperer562580892423** [comment]
@pokecheater @boneitis You can get back the separate copy buttons by checking this: --> Settings --> Appearance --> "Show quick copy actions on Vault"

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one. Please share additional feedback in this thread: [https://community.bitwarden.com/t/usability-issues-ux-in-redesigned-ui-2024-12-0/76836/472](https://community.bitwarden.com/t/usability-issues-ux-in-redesigned-ui-2024-12-0/76836/472?u=abanay)

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
