### ISSUE TITLE
[Firefox] Minimum width is now much, much larger - even in compact mode

### ISSUE THREAD

**Issue by DHowett** [bitwarden/clients#12572]
### Steps To Reproduce

1. Update to the latest version of the extension.
2. Have a narrow screen with a narrow browser sidebar.

### Expected Result

It all fits, or shrinks.

### Actual Result

![Image](https://github.com/user-attachments/assets/afe4c044-d12b-4d86-b11b-c415447c82f8)

The width options are "Default", "Wide" and "Extra Wide". This is Default.

Compact only makes the text smaller, it does not reduce the horizontal width required to display the sidebar.

I only have a 13" 3:2 laptop display; my horizontal space is unfortunately more precious than Bitwarden's need of it.

### Operating System

Windows, Linux

### Web Browser

Firefox

### Build Version

I can't get to Settings, because it's cut off. (2024.12.3)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one. Please share additional feedback in this thread: [https://community.bitwarden.com/t/usability-issues-ux-in-redesigned-ui-2024-12-0/76836/472](https://community.bitwarden.com/t/usability-issues-ux-in-redesigned-ui-2024-12-0/76836/472?u=abanay)

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
