### ISSUE TITLE
New Look does not allow quick copy of User/Password/TOTP - Option to revert to old interface required

### ISSUE THREAD

**Issue by Routhinator** [bitwarden/clients#12571]
### Steps To Reproduce

This new look just broke everything I loved about using Bitwarden in Firefox by taking away everything that made it better than 1password and the competition from the quick list of accounts. I should not have to click into every item, or open a submenu just to get to a TOTP code or the password, especially when not everything is a web app or has a link. Over 50% of the entries in my vault are NEVER used with The Autofill or Launch buttons.  I use the User or Password or TOTP quick buttons almost exclusively.

To reproduce this, open the new extension and be faced with what looks like some designers dream and users largest annoyance. Now all the useful items are buried in a menu.

### Expected Result

I expect to be able to access useful quick buttons on the items in my vault and to be able to hide the Launch items. 

### Actual Result

I now have to click a dropdown menu to access the quick buttons I used most frequently.

### Screenshots or Videos

![Screenshot_20241224_060810](https://github.com/user-attachments/assets/85fed09d-b0fe-48ba-bc40-f81f94a16a91)

### Additional Context

UI Updates should consider every workflow and the plethora of us who do more than use webpages every day.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Routhinator** [comment]
Ok I have finally found how to get these options back. This Bug should be to have the app ask the user _before_ moving all the useful items out of the interface.

**Comment by magicsunday** [comment]
The ratings for the Firefox extension are all going down the drain because of the "UI" adjustments. These are really awful. I have no idea why you always have to optimize things to pieces instead of asking the community what is important to them.

**Comment by ellsclytn** [comment]
In case anyone is wondering how to restore these buttons:

1. Open the BitWarden Extension
2. Settings
3. Appearance
4. "Show quick copy actions on Vault"
