### ISSUE TITLE
password chars not color-coded

### ISSUE THREAD

**Issue by isaiahfrantz** [bitwarden/clients#12592]
### Steps To Reproduce

create a new login
set password to 0oO0 (zero, lowercase o, uppercase o, zero)

### Expected Result

color-coded characters in password field (makes transcribing them much easier!!)
- zeros/numbers should be blue
- letters should be white
- special chars should be red

### Actual Result

all chars are white in browser plugin on vivaldi and firefox on linux and MS edge on windows and macos
(NOTE: the password chars are properly color coded in the android app)

### Screenshots or Videos

firefox-view-existing-login_no-color-in-password
![firefox-view-existing-login_no-color-in-password](https://github.com/user-attachments/assets/bb4d686b-0003-4943-8d59-abce0aa8ec18)
vivaldi-view-existing-login_no-color-in-password
![vivaldi-view-existing-login_no-color-in-password](https://github.com/user-attachments/assets/7a956ea0-fcd4-4282-8410-0c6eacec9f40)
vivaldi-create-new-login_no-color-in-password
![vivaldi-create-new-login_no-color-in-password](https://github.com/user-attachments/assets/d02dfeea-d5d9-4ac6-92c3-40ddf7e96292)

### Operating System

Windows, Linux

### Web Browser

Microsoft Edge, Firefox, Vivaldi

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @isaiahfrantz, thank you for the report.

This has been implemented with #12354.

The changes will be included in the next release (`2025.1`).

Closing this now.

Kind regards,
Daniel
