### ISSUE TITLE
Bitwarden prompt to Never save password doesn’t work

### ISSUE THREAD

**Issue by joshorenberg** [bitwarden/clients#12606]
### Steps To Reproduce

Simple enter a user and password to log into a website in Chrome and then click never save password. The next time you go the extension will ask again.

### Expected Result

The Chrome extension should remember to not save the username/password combo.

### Actual Result

The Chrome extension doesn't remember.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

latest

### Build Version

Version: 2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @joshorenberg,

Just to make sure that you and I are on the same page:
1. Did you encounter the second autosave prompt in a second Login attempt shortly after the first Login attempt within the same browser tab?
2. Do you see that URL in the extension's [Excluded Domains](https://bitwarden.com/help/exclude-domains/) at this stage?
3. If you now open a new tab and navigate to that webpage and log in whilst the URL is still set within the Excluded Domains function, are you now presented with an autosave prompt?

Thank you in advance,

**Comment by joshorenberg** [comment]
@SergeantConfused Hi the issue has disappeared... I will repost here if it returns.
Thanks
Josh

**Comment by SergeantConfused** [comment]
Hi @joshorenberg,

Thank you for keeping me in the loop; I'm happy to hear it's working as expected now. At this stage, I will proceed and close this GitHub report; if you have any questions or concerns, please feel free to [get in touch](https://bitwarden.com/help/), and please include a link to this GitHub report if you do.

Thank you again,

**Comment by joshorenberg** [comment]
It's back... been happening for a week or so now.
