### ISSUE TITLE
Item Data Fields Are No Longer Draggable From Browser Extension

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#12616]
### Steps To Reproduce

1. Open "View Login" view (or any other item view).
2. Hover mouse over field label for Username, Password, or any other field (except for custom linked fields).
3. Click and drag to any valid drop target for HTML5 draggable items.

### Expected Result

On hovering the mouse in **Step 2** of the above instructions, the mouse cursor should change to a "Move" icon (four arrows arranged in a compass shape: &#10021;).

Upon release of the dragged item, the _value_ of the dragged field should be transferred into the drop target.

### Actual Result

Nothing happens.  Item fields are no longer draggable.

### Additional Context

For versions 2022.10.0-2024.11.2, all fields in the browser extension (except custom linked fields) were draggable, thanks to [PR 3321](https://github.com/bitwarden/clients/pull/3321) by @patrickhlauke (and prior to 2022.10.0, at least the Username, Password and TOTP fields were draggable).  The functionality was lost starting in version 2024.12.0, and has still not been restored (as of version 2024.12.4).

Draggable fields are essential for secure transfer of credentials (avoiding potential information leaks from the highly vulnerable system clipboard) for scenarios in which Bitwarden's autofill functionality cannot be used (e.g., autofill failures, or transferring of sensitive information to input fields outside the browser).

Therefore, fixing this bug is a high-priority security issue.

### Operating System

Windows

### Operating System Version

Windows 11 (23H2)

### Web Browser

Microsoft Edge

### Build Version

Version: 2024.12.4;  SDK: 'main (edee180)'

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @bwbug and thank you for the report.

This was also noticed internally and is addressed with https://github.com/bitwarden/clients/pull/12067. The changes will be included in the next release (`2025.1`).

Closing this now.
