### ISSUE TITLE
Launching an item doesn't auto-fill that item

### ISSUE THREAD

**Issue by TargetCrafter** [bitwarden/clients#1958]
## Describe the Bug

Clicking launch on an item doesn't auto-fill that item.

## Steps To Reproduce

Click on the "Launch" button next to a login and let it fill automatically or auto-fill using a keyboard shortcut.
You can also see that the item you just launched is not on top of the list.

## Expected Result

The launched item should be the one that is auto-filled.

## Actual Result

The last filled item is auto-filled.

## Environment

- Operating system: Windows 10, Windows 11
- Browser: Edge 91.0.864.67, Edge Canary
- Build Version 1.51.1

## Additional Context

I can't find it, but i believe i reported this before. It was fixed back then, but it's back now.

**Comment by eliykat** [comment]
The launch button only navigates to the URL. It does not not auto-fill credentials unless [auto-fill on page load](https://bitwarden.com/help/article/auto-fill-browser/#on-page-load) is turned on. Please ensure that you have auto-fill on page load turned on and then try again.

**Comment by TargetCrafter** [comment]
I have that setting disabled, but I use a keyboard shortcut to "Auto-fill the last used login for the current website".
With [auto-fill on page load](https://bitwarden.com/help/article/auto-fill-browser/#on-page-load) enabled, the problem is the same.
Like I said, it fills the wrong item. Not the one you "launched", but the one you last used.

**Comment by eliykat** [comment]
Ah sorry, I misread your report. I understand, it's the issue I solved in #1576. I'll have a look at it, sounds like it's a regression.

**Comment by TargetCrafter** [comment]
You're right, that was the issue I couldn't find. I posted in that too, and it's indeed the same problem.
In the old issue it's noted to be a regression too, it seems to keep coming back..

**Comment by TargetCrafter** [comment]
Is there an update on this issue?

**Comment by eliykat** [comment]
Not yet @TargetCrafter. It's triaged and I've identified the breaking changes, but I haven't come up with a fix yet. Thanks for your patience - I'll make sure to link this issue in the PR so that you can see the fix when it comes in.

**Comment by TargetCrafter** [comment]
Is there an update on this Issue? It seems to work when I use the plugin for the first time, but any time after it just fills the last used item.

**Comment by mackaaij** [comment]
Still/again an issue in Google Chrome's Bitwarden 2024.10.0. If you search your vault for a website that has multiple login items in Bitwarden and specifically choose one to launch, Bitwarden has a preference for the one to prefill (maybe alphabetically). Expected behavior is to fill the item for which the launch icon was selected.

Seems to be a regression every now and then, see #869, #1391, #1428, #1576, #1958
