### ISSUE TITLE
Sarfari Extension is missing after Bitwarden 1.29.0 macOS update

### ISSUE THREAD

**Issue by ChrisBegley** [bitwarden/clients#2150]
### Steps To Reproduce

I'm running macOS 12.0.1 and just updated Bitwarden to version 1.29.0 in the Mac App store. 

Now the extension in Safari is gone from my toolbar. I went into Safari's Preferences > Extensions and it's not in the list there. 

I restarted my Mac, uninstalled and reinstalled Bitwarden from the Mac App Store, but it's still not there. 

### Expected Result

The Bitwarden Safari extension would be available

### Actual Result

The Bitwarden Safari extension is missing 

### Operating System

macOS

### Operating System Version

12.0.1

### Web Browser

Safari

### Browser Version

15.1

### Build Version

1.29.0

**Comment by cscharf** [comment]
Hi @zmilonas , we perform retrospective release reviews both within our DevOps team and the engineering team as a whole (which are open to the rest of the organization for input/thoughts), so we'll definitely visit this particular issue as well. Unfortunately up to very recently (and it's only in Beta), Apple has not offered any kind of MAS "Test Flight" like it does for iOS apps, and therefore when there are changes to packaging and our build pipelines, there's no way to test its final delivery through MAS and how it will behave deployed in the wild, and Apple also removed the ability to use signed extensions within a DMG installation (it has to be MAS), so they shut the door in multiple ways on rooting out these types of issues during normal testing cycles. Once TestFlight for MAS/macOS has been released, we'll be in much better shape to mitigate these types of problems going forward.

**Comment by zmilonas** [comment]
Thank you @cscharf for this insightful answer and taking the time. Wish you all the best learnings from the retrospective.
