### ISSUE TITLE
Safari extension missing. Version 1.29.0 1790

### ISSUE THREAD

**Issue by michael1900** [bitwarden/clients#2152]
### Steps To Reproduce

-----

### Expected Result

-----

### Actual Result

After last Bitwarden update the bitwarden safari extension is missing. Already tried every thing seen googling, like Onyx, rebuild database launch services, uninstall, etc.. but nothing of these fix the problem.

### Operating System

macOS

### Operating System Version

10.15.7

### Web Browser

Safari

### Browser Version

15.1

### Build Version

1.29.0 1790

**Comment by shubhpatel** [comment]
Same here.
M1 Macbook Pro
Mac OS 12.0.1
Bitwarden 1.29.0

**Comment by whitesiroi** [comment]
Same here.
M1 Macbook Pro
Mac OS 12.1
Bitwarden 1.30.0
