### ISSUE TITLE
Bitwarden does not respect chrome.storage.managed

### ISSUE THREAD

**Issue by p3lim** [bitwarden/clients#2160]
### Steps To Reproduce

Create a [policy for Firefox](https://extensionworkshop.com/documentation/enterprise/adding-policy-support-to-your-extension/):
```json
{
	"policies": {
		"3rdparty": {
			"Extensions": {
				"{446900e4-71c2-419f-a6a7-df9c091e268b}": {
					"environmentUrls": {
						"base": "bitwarden.internal.corp"
					}
				}
			}
		}
	}
}
```

### Expected Result

The extension should respect settings stored in [chrome.storage.managed](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/managed) (created by the policy) over `chrome.storage.local` if they are set there, supporting enterprise policies.

### Actual Result

Extension only reads `chrome.storage.local`.

### Additional Context

Policies allows corporations/teams to pre-configure the browser (and extensions) for mass-rollouts of computers. If the Bitwarden browser extension supporting this it would make it easier to adopt Bitwarden for all users in the corporation/team.

### Web Browser

Firefox (although this might be a thing for Chrome too, haven't checked).

### Build Version

1.54

**Comment by jesseliu612** [comment]
@djsmith85
Perhaps there's more to be discussed before implementing this feature?
For example, whether the extension should allow user override the managed policy or not?

**Comment by p3lim** [comment]
I still want to see this feature supported, please do not close it.

@jesseliu612 If the browser is managed by an enterprise policy then no, the user should not be able to override it. That is the whole point of having a policy, and is how Firefox itself treats options that have been locked by a policy.
