### ISSUE TITLE
Double scrollbar with default zoom greater than 100%

### ISSUE THREAD

**Issue by ob-tk** [bitwarden/clients#2190]
### Steps To Reproduce

1. Go to Chrome browser settings. 
2. Set up default zoom 110%. 
3. Open the extension window.

### Expected Result

 A second scrollbar appears in the extension (the body is taller than the window).

### Actual Result

Html body should fit in the window.

### Screenshots or Videos

![e1f018e6b48c9f](https://user-images.githubusercontent.com/17561825/142726195-4eecd085-19f5-43fa-8c33-fd9e380dc198.png)

![5be8309deac5a5](https://user-images.githubusercontent.com/17561825/142726200-c86e5cfc-09d2-472e-8141-9ae1d13268fb.png)

### Operating System

Linux

### Operating System Version

Ubuntu 18.04

### Web Browser

Chrome

### Browser Version

95.0.4638.69

### Build Version

1.54.0

**Comment by Hinton** [comment]
@ob-tk do you know if other extensions have similar visual issues in their popups?

**Comment by ob-tk** [comment]
I have never noticed such isses

**Comment by Hinton** [comment]
I've managed to replicate the issue on Windows by setting the page zoom to 110%. It seems that since we set the height to 600px, the page zoom expands it beyond the maximum allowed height in Chrome.

Not completely certain how to solve this efficiently, but some trick with overflow hidden maybe.

**Comment by Hinton** [comment]
Related:

https://github.com/bitwarden/browser/issues/1008
https://github.com/bitwarden/browser/pull/1627
https://github.com/bitwarden/browser/pull/1714

**Comment by c0ldplasma** [comment]
Can someone repoen this? I'm still encountering this on Brave and Chrome on Mac.

**Comment by Hinton** [comment]
@c0ldplasma can you provide your environment details? What OS, versions etc, is zoom level configured?

**Comment by c0ldplasma** [comment]
OS: MacOS Monterey 12.5 
Browser: Brave 1.42 and Chrome 104
Browser zoom level: 110%

**Comment by ttdatt** [comment]
it only happens on Chromium browsers, firefox works well with default zoom 110%

**Comment by jrivard** [comment]
Bump, still having this issue in 2024.

**Comment by ramprasathasokan** [comment]
Hi @kspearrin, 

This issue is a nightmare while working in monitors where we are forced to increase the default zoom of chromium browsers. It wasn't like this a year back if memory serves right. 

We don't know whether this is technically feasible to be addressed. 

However, I love Bitwarden so much that evangelize it to everyone I meet. 

Please take a look and update. ✌️

**Comment by ob-tk** [comment]
![image](https://github.com/user-attachments/assets/b1205dd4-3b2c-42c8-adc6-8dc0250deede)
