### ISSUE TITLE
"This extension may have been corrupted" - happening multiple times/week on two separate machines and two separate browsers

### ISSUE THREAD

**Issue by TriggerDingus** [bitwarden/clients#2216]
### Steps To Reproduce

Here are the versions, though keep in-mind I update frequently and this issue has been occurring a few months.

Bitwarden extension 1.54.0
Pop OS: 21.04
Brave: Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)
Firefox: 94.0.1

I posted this issue in Reddit but never received a response, though I saw at least one older post describing the same issue and nobody had responded to that one either. I'm convinced this issue isn't just me since I experience the issue:

On two separate Linux machines (Pop OS)
On two separate browsers on each of the machines (Chromium and Firefox)

At least once a week, I find my Bitwarden extension disappears from my browser extensions bar in each of the browsers on each of the machines. Upon investigation in the Manage Extensions page, I find the entry for Bitwarden says: "This extension may have been corrupted". In addition to the usual links for Details and Remove, there's a Repair link.

This issue began occurring a few months back and hasn't gotten any better or any worse. I don't know that I'm doing anything to trigger the behavior - I'm just using the browsers as usual.

### Expected Result

Bitwarden extension never to corrupt during normal browser usage.

### Actual Result

See "Steps to reproduce"

### Screenshots or Videos

![144352898-f9b0e50f-a161-449d-969b-8a10644aea35](https://user-images.githubusercontent.com/75340371/145307455-eb0e5f7a-35bd-4539-9f67-c369dfb26215.jpg)

### Operating System

Linux

### Operating System Version

Pop! 21.04

### Web Browser

Firefox, Brave

### Browser Version

Brave Version 1.15.76 Chromium: 86.0.4240.111 (Official Build) (64-bit)

### Build Version

Latest extensiion for each browser

**Comment by TriggerDingus** [comment]
This issue is still happening for me but doesn't look like others are complaining, so closing the ticket.

**Comment by sohang3112** [comment]
@TriggerDingus I am having the same issue on Fedora LXDE (new install). Did you find any solution for this?

**Comment by TriggerDingus** [comment]
> @TriggerDingus I am having the same issue on Fedora LXDE (new install). Did you find any solution for this?

After posting in a few different places (including here on github), I didn't received a response from any of the developers or contributors so I closed the ticket.  The problem persisted for a month or two and eventually it just stopped happening (knock on wood) so I don't know if the issue was quietly resolved or what was going on.

**Comment by TriggerDingus** [comment]
Reopening. Its still happening and has been ever since soon after I closed it. 
Everything I wrote in this issue a couple years ago is still accurate, except all versions of everything is updated. It doesn't happen multiple times/week but it does happen multiple times a month. It's become rather comical at this point that this is still an issue and I just chuckle when I open the browser and Bitwarden is gone again, then I fix the Bitwarden extension like I've done 100 times before.

**Comment by yakau** [comment]
According to this: https://stackoverflow.com/questions/60701105/chrome-extension-gives-following-error-this-extension-may-have-been-corrupted - the corruption alerts occur when the extension is altered unexpectedly (ie. not by Chrome).

I'd suggest grabbing your Bitwarden extension ID and monitoring every directory that includes that ID for any changes. Monitor for any files added, removed, or altered.

Wait for the error to re-occur, and then check your folder monitor to see what changed.

**Comment by TriggerDingus** [comment]
Interesting suggestion.

**Comment by TriggerDingus** [comment]
Apparently Bitwarden doesn't believe this is an issue.

**Comment by quexten** [comment]
> Since it is happening to you regularly, I do not think this is your problem, but I still wanted to write this.
> 
> There are scripts where the script tries to access Bitwarden plugin and get or change the data from there. You click a link or website, and the website directly tries to access the password manager or plugin (Bitwarden in this case), and retrieve data from there (or just change the existing data). I can only be vague as since I do not know what these scripts do, and I can only guess. Unfortunately, these scripts can run while showing you the website on the front, or while during 'loading' process. One way to test what is being changed is having access to a malicious link or website where the script is run and copying the extension folder before and after corruption, and comparing the files. (test with dummy browsers with dummy bitwarden accounts where a few fake vault items has been created, in a safe environment - on a dummy system or where the browser is on an isolated virtual machine -).
> 
> I can send you some malicious links below, I do not know if they are still active or not. I did not test these links myself.
> 
> **------------------- DO NOT GO TO THESE SITES!!! --------------------- -------------------- THESE LINKS ARE PROVIDED FOR DEVELOPERS TO TEST ONLY IN CONTROLLED ENVIRONMENTS ------**
> 
> bn-bz.com wfhskc.com cems-yzhb.com dgqybz888.com jswj68.com cic-ccicfj.com wl-xg.com dx-wfg.com hljjxdd.com kb9888.com bgs-fm.com sdjgsx.com hwcyjc.com akukukuh.com
> 
> Hopefully, one of the developers or penetration testers will be able to identify how these scripts work, and if they can gain access to any information in the vault.

@Fern99 How did you come across these links, and how does "accessing the extension" manifest/how did you notice this? Due to browser sandboxing, there are only a very limited set of points where this is technically possible.

**Comment by shnabz** [comment]
I just ran a diff check on the corrupted directory against a repaired directory, the only difference was that the `computed_hashes.json` file is missing from the corrupted directory. Suspicious indeed.
