### ISSUE TITLE
SSO fails when Vault Timeout Action is set to Log Out

### ISSUE THREAD

**Issue by rdaunce** [bitwarden/clients#2221]
### Steps To Reproduce

Caution - following these steps may leave your extension in an unusable state if you only use SSO authentication.

1. Login to the browser extension using the 'Enterprise Single Sign-On' button.
2. Follow the normal process to complete SSO for that account.
3. Unlock the vault
4. Change the browser extension setting 'Vault Timeout Action' to 'Log Out'
5. Allow the vault to timeout OR logout manually.
6. Attempt to login again using the 'Enterprise Single Sign-On' button.

### Expected Result

I expect the extension to follow the normal process to complete SSO and the extension icon to update to a blue icon with a red lock overlay indicating that the vault is locked.  I expect that clicking on the extension icon will prompt me for the vault Master Password the same way it did in Step 3.

### Actual Result

After following the process to complete SSO, the standard page appears that says 'You may now close this tab and continue in the extension.'  The extension icon does not update and remains a grey color indicating that it is not logged in.  Clicking on the extension only displays the login options ('Log In', 'Enterprise Single Sign-On', and 'Create Account'), not the expected prompt for the vault Master Password.

The SSO login process can be performed repeatedly and it will never successfully reach the prompt to unlock the vault.

There are two ways I am aware to resolve the problem:

1. Login using a non-SSO account and change the extension setting 'Vault Timeout Action' to 'Lock'.  Log Out of that account and you will now be able to authenticate using SSO.
2. Uninstall the extension and reinstall it.  This will revert all extension settings that have been modified back to their default value.  You will now be able to authenticate using SSO.

### Additional Context

The account I used to test this had 2 factor authentication setup with a Yubikey.  It is not clear to me if this is a factor or not.  I'm not willing to disable that on my account to see if it makes a difference.

### Operating System

Windows

### Operating System Version

10 Pro 21H2 (19044.1348)

### Web Browser

Chrome, Firefox

### Browser Version

96.0.4664.93, 95.0

### Build Version

1.55.0

**Comment by Hinton** [comment]
Hi @rdaunce,

Thanks for reporting this. we've managed to replicate this issue. And it's been added to our backlog.

In the meanwhile the current work-arounds are to either login without sso, or set vault timeout to lock.

**Comment by rdaunce** [comment]
This issue described hasn't been resolved and I'd still like to see it fixed.  There isn't much that I would expect to see on the GitHub Issue until the underlying problem is resolved, though.  Based on the comment by @Hinton on 12/15 it is reproducible and added to the backlog.  Would an issue like this normally be kept open on GitHub until resolution or would you typically close it and track it through the backlog?

**Comment by rituraj00** [comment]
@Hinton, I would like to take a stab at this issue, is it still there or resolved?

**Comment by rdaunce** [comment]
@rituraj00 @Hinton I just tested and confirmed that the issue still occurs.  I tested it using the Chrome extension version 2023.2.0.

**Comment by rdaunce** [comment]
I also was not able to resolve the issue by logging in with a non-SSO account and changing the setting.  When I logged in with the non-SSO account, the 'Vault Timeout Action' setting was already set to 'Lock'.  I had to remove the extension and reinstall it to successfully login using SSO again.

**Comment by Greenderella** [comment]
Solved by https://github.com/bitwarden/clients/pull/5286

Thanks for reporting!
