### ISSUE TITLE
Opening of new tab to enter credentials to unlock vault fails to bring focus when in incognito

### ISSUE THREAD

**Issue by ianspryn** [bitwarden/clients#2243]
### Steps To Reproduce

1. Go to `chrome://extensions/shortcuts` and ensure "Auto-fill the last used login for the current website" has a keyboard shortcut set.
2. Open a regular chrome window.
2. Open an incognito window and navigate to any webpage that has a username/password field.
3. Press the keyboard shortcut.

### Expected Result

A new tab opens and is brought to focus to allow you to unlock your vault.

### Actual Result

A new tab opens but it is NOT brought to focus.

### Screenshots or Videos

https://user-images.githubusercontent.com/4182500/147000059-f2ae11ff-e11d-4d76-965f-8d862a0f5cf5.mp4

### Additional Context

This issue is most annoying in full-screen because you have no indication that a new tab was opened.

### Operating System

macOS

### Operating System Version

10.15.7

### Web Browser

Chrome

### Browser Version

96.0.4664.110 (Official Build) (x86_64)

### Build Version

1.55.0

**Comment by ianspryn** [comment]
This is still an ongoing issue.

**Comment by mtoygar** [comment]
Another alternative might be opening popup instead of creating a new tab. It should be possible on incognito view.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/22214691/201931863-1f0c5e5d-e2dc-47ab-8e48-854cb63d6bde.png">

**Comment by ok-nick** [comment]
I agree with @mtoygar, it would be much more preferable to open a popup rather than a new tab (or window). There's a thread on the forum about this [here](https://community.bitwarden.com/t/ask-for-pin-without-opening-a-new-tab/36946).
