### ISSUE TITLE
Extension causing STATUS_ACCESS_VIOLATION in Edge Canary (99.0.1126.0)

### ISSUE THREAD

**Issue by turnma** [bitwarden/clients#2262]
### Steps To Reproduce

1. Ensure extension is installed and logged on..
2. Go to https://www.bbc.co.uk/news/technology-59907864 
2. Page loads successfully
3. Wait a couple of seconds
4. Observe that Edge error page replaces the loaded page - "This page is having a problem" with error STATUS_ACCESS_VIOLATION.

This error is not 100% reproducible, but it's frequent enough to make it problematic to have the extension running.

### Expected Result

Page should stay loaded and not create errors.

### Actual Result

Loaded page is replaced with Edge error page, as above.

### Screenshots or Videos

![edgeerror](https://user-images.githubusercontent.com/33033814/148566073-eb590ce8-8c76-47ce-8d45-85e5db670ded.png)
![edgecrash](https://user-images.githubusercontent.com/33033814/148566350-73868d24-c0c4-4306-a63d-fbc4018e651c.png)

### Additional Context

This problem is only apparent in Edge Canary (v99) and so might be an Edge issue that will be fixed before it reaches the stable branch.  But raising it here to give notice of a potential problem.

### Operating System

Windows

### Operating System Version

20H2

### Web Browser

Microsoft Edge

### Browser Version

99.0.1126.0

### Build Version

 1.55.0

**Comment by turnma** [comment]
{
  "Local ID": "b5afaa53-7ffa-44ea-a1df-c58629ac922c",
  "Upload ID": "b5afaa53-7ffa-44ea-a1df-c58629ac922c",
  "Bucket ID": "b501df5b1bc93f48b56672ed8c2b29e5",
  "Cab ID": "f530666c-6a78-4252-888c-402fd6a7dcec",
  "Capture Time": "Friday, 7 January 2022 at 15:28:13",
  "Upload Time": "Friday, 7 January 2022 at 15:28:14",
  "State": "uploaded",
  "Application Name P1": "msedge.exe",
  "Application Version P2": "99.0.1126.0",
  "Module Name P3": "msedge.dll",
  "Module Version P4": "99.0.1126.0",
  "Module Offset P5": "39426802",
  "Process Type P6": "renderer",
  "Sub Code P7": "0xc0000005",
  "Stack Hash P8": "0"
}

**Comment by djsmith85** [comment]
@turnma Is this still an issue?

**Comment by turnma** [comment]
No, seems to have stabilised, thanks.
