### ISSUE TITLE
OTP not working

### ISSUE THREAD

**Issue by Sakujakira** [bitwarden/clients#2362]
### Steps To Reproduce

Since today i cant use any OTP within my Browser.

Option 1: 
> Open some Website you have configured a OTP in the past
> CTRL-Shift-L works but OTP is not copied

Option 2:
> Open some Website you have configured OTP in the past
> Click the bitwarden Add-On icon, OTP is greyed out.

### Expected Result

My OTP should be moved into the clipboard after i succesfully used ctrl-shift-L
I should be able to click the Clock-Icon and copy my OTP to the Clipboard after clicking on it.

### Actual Result

OTP Icon is greyed out and not useable atm in the browser. 

### Screenshots or Videos

![Screenshot 2022-02-11 172619](https://user-images.githubusercontent.com/3703103/153629810-966ec6e3-e598-4934-99d6-011219fe2187.png)

### Additional Context

The OTP stays configured, i can clearly see my secrets in bitwarden. I have tested this with atleast these Domains:
- selfhosted Service
- Google
- all-inkl.com
- Discord

Within the Desktop App it still works.
Desktop App:
> Version 1.30.0
> Shell 14.2.0
> Renderer 93.0.4577.82
> Node 14.17.0
> Architecture x64

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Browser Version

V1.35.101 Chrome 98.0.4758.87

### Build Version

1.56.0

**Comment by mderazon** [comment]
Dup https://github.com/bitwarden/browser/issues/2348

**Comment by nartz** [comment]
Not sure if this is related, but the chrome extension does get OTP codes after reinstalling 1.56, however, they are out of sync (they seem lagged) and thus don't work
