### ISSUE TITLE
Problem with dropped letters/keypresses when Searching vault from Browser extension (debounce)

### ISSUE THREAD

**Issue by luckman212** [bitwarden/clients#2371]
### Environment

- Bitwarden 2022.6.x
- macOS 12.4
- Chrome 103

### Repro

1. click on bw icon in Chrome toolbar to open vault
2. start typing a search word— **_type fast_**
3. notice that midway through your typing, the field drops letters or garbles part of the word by overwriting the first few letters (this happens precisely when the preview/results area refreshes)

This might be a little hard to reproduce, but if you have a large enough vault (1000+ items) it shouldn't be too difficult. 

I think this is a debounce issue. The search function seems to run in a tight loop. It should run synchronously, and not drop keypresses so if typing quickly the search term is entered correctly.

### Expected Result

Search term e.g. "google" is entered completely

### Actual Result

Search sometimes gets entered as "goole" or "gogl" etc. due to dropped letters during refresh of results.

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Chrome

### Browser Version

103.0.5060.114

### Build Version

2022.6.3

**Comment by ginat** [comment]
Thanks for submitting a ticket! I am having a hard time reproducing the level of fastness needed for this. Can you use Quicktime to attach a screen recording?

**Comment by instag1b** [comment]
@ginat in a Vault with ~1400 items (from collections), I need to at least type at a speed of ~60WPM or 300CPM to reliably reproduce this issue. Sometimes, even slower typing speeds can cause this problem. 

### Environment

- Fedora 35
- Firefox 97.0.1
- Bitwarden plugin 1.56.6

**Comment by luckman212** [comment]
I'm having a hard time capturing it in a screen recording @ginat 

It occurs during the initial vault load after a "cold start" of the browser. Once the cache is warmed up, it's much harder to reproduce. When you first start typing in the search box, the extension seems to wait for you to pause typing (around ~250ms) and then will trigger the vault to load. It's during this loading that keypresses are eaten (you see the spinning arrows while it's loading/decrypting).

I think this would be solved by simply performing that "expensive" load/decrypt operation when the extension does its initial load instead of upon first use of the search field.

**Comment by karlgrz** [comment]
Just adding my anecdotal experience with this issue, it's frustrating to say the least but not show stopping. 

Ubuntu 20.04 on a modern desktop, seeing this occasionally on both Google Chrome and Firefox, current versions below:

- Google Chrome Version 99.0.4844.51 (Official Build) (64-bit), Bitwarden Version: 1.56.6
- Firefox 98.0 (64-bit), Bitwarden Version: 1.56.6

**Comment by anastrophe** [comment]
As noted by karlgrz above, this issue still persists in v 1.56.6 of the extension. Is there a timeline for when this issue will be resolved? This is pretty much the first material problem I've ever experienced w Bitwarden, all previous issues I've had over the years have been 'gripes' about UI decisions and whatnot. This one is an actual bug that causes genuine frustration...

**Comment by ahsodex** [comment]
Still an issue with version 1.57.0 on Firefox 99

**Comment by flaxton** [comment]
Still a problem with 1.58.0 on Google Chrome Version 100.0.4896.127 (Official Build) (arm64) on M1 MacBook Pro.

I often have to backtrack and fill in one or more missing characters in the search, that were dropped/ignored as I typed.

**Comment by instag1b** [comment]
So I finally managed to capture a good example of this bug in a screen recording. It seems like it doesn't really depend on how fast you type, but rather how many keypresses fall into the window where the extension does something in the background as mentioned by @luckman212. For me, this doesn't only happen after a cold start, but for every first search when opening Bitwarden as shown in the attached video. When I close this view, the problem will occur the next time I open Bitwarden and do a search.

https://user-images.githubusercontent.com/48023919/165590563-a5dda758-31f2-4570-961f-a453d65f7a7d.mp4

### Environment
- Fedora 35
- Firefox 99.0.1
- Bitwarden plugin 1.58.0

**Comment by anastrophe** [comment]
Is there any way to go back to a previous version of the bitwarden extension? This bug is a daily - hourly - every five minutes annoyance for me, just constantly having to remember to stop typing after i enter the first three letters, so that it can dutifully blank the entire field then restore the field - so that I don't type over that moment of blanking, and wind up entering 'gub' instead of 'github'.

**Comment by luckman212** [comment]
Hi @ginat can we please get a status on this 5+ month old bugreport? It was an annoyance at first but has turned into a real daily PITA where I have a new muscle memory now when I go to use Bitwarden... click icon, type 1 letter, wait 2 seconds for BW to "think", and then type the rest of my search string. This is not how it should be.

**Comment by anastrophe** [comment]
I don't really see any evidence that @ginat is either active or actually associated with bitwarden; I could be wrong. The only other contributor here appears to be @djsmith85, but other than closing other reports of this as duplicates, he doesn't appear to be interested in this bug either; again, I could be wrong.

Whats further frustrating is that _before_ February 2022, this bug _did not_ exist, so therefore it was _introduced_ into the code on or about then. In my excruciatingly limited experience with coding, it shouldn't be much more than reviewing a diff to find what went wrong. However, I'll throw in my standard disclaimer again: I could be wrong.

**Comment by flaxton** [comment]
It's still happening. I start typing, then it drops letters, then I backtrack to correct the dropped letters.

**Comment by dbosompem** [comment]
Hi @luckman212 @anastrophe , apologies for the inconvenience caused as well as the delay. This issue will be reproduced and will be given the attention it needs. We will definitely get back to you on this.

**Comment by anastrophe** [comment]
Thank you very kindly @dbosompem !

**Comment by ahsodex** [comment]
I looked through the git log for "search", didn't find much but this jumped out to me. I'm not familiar with the code base/logic to say if it's related, and there's a lot of different branches so not sure if/when it was introduced, but the commit date is January 20.

> commit 025a4a5e3878bcc3f5126074f154e3d51aa9c091
> Author: Addison Beck <abeck@bitwarden.com>
> Date:   Thu Jan 20 16:25:04 2022 -0500
> 
> [bug] Index search service when setting decrypted ciphers (#620)
> 
> With the move to a central StateService we erroniously cut out search indexing from the process of setting decrypted ciphers to memory.
> This commit calls the method responsible for setting decrypted ciphers and indexing when decrypting, instead of setting decrypted ciphers directly.

**Comment by luckman212** [comment]
@dbosompem Does it help or matter at all to note that this bug does **_not_** affect the "desktop" (Electron) app `v2022.6.2`? Only the browser extension.

**Comment by dbosompem** [comment]
Sure, this additional info helps. Thanks @luckman212

**Comment by inhji** [comment]
I would like to add that this problem occurs on my system with these specs:

Bitwarden Firefox 2022.8.0
Windows 10
Firefox 103.0.2

**Comment by kileywm** [comment]
Here are some concrete steps to reproduce:

1. Begin with browser extension in the closed state.
2. Open the browser extension.
3. At a reduced speed, type out a long-ish search string. I used "testing" as my test case.
4. When the first result set is rendered below the search box (while I'm still typing), the search string's value is reset momentarily to an empty string, and then restores to the state it was when the result set began rendering.
5. Notice the missing letter(s) from the search text. For me the final value is "testng", indicating that my "i" keypress was lost.

Note that subsequent search are not affected while the browser extension is open. Only the first search after the browser extension is opened.

I took a quick peek at the code and suspect that, somewhere, the value of `searchText` is being mutated incorrectly. Maybe when it's normalized prior to filtering. Maybe elsewhere.

**Comment by rdaugherty** [comment]
Hello everyone! I have been able to reproduce this consistently enough, and I can definitely understand the frustration it's causing. I'm going to turn our internal bug ticket over to the development team to find a fix so we can get this resolved.

Based on what I'm seeing, it looks like the issue occurs when the user is on the "Current Tab" view (the folder icon that says "Tab") and attempts to perform a search. Search logic doesn't kick in until the second character. Once that second character is entered the extension auto-switches to the "My Vault" view (the lock icon that says "Vault") and begins to load the vault contents. In doing so, the search component seems to reload, alongside the rest of the "My Vault" view, causing the first part of the search to disappear for a few moments and then re-appear once the "My Vault" view has finally loaded. It's during this loading event, triggered by switching from "Current Tab" to "Vault Tab", where any characters typed in the search component can possibly get lost.

TL;DR If you're on the "Current Tab" view, and attempt to perform a search, especially in a large vault, you can run into this issue. 

The current workaround is to ensure that you are on the "My Vault" view when performing a search, as I have not been able to reproduce this issue when starting from there. That's not ideal, but hopefully this helps until a fix can be made.

**Comment by karlgrz** [comment]
@rdaugherty confirmed that workaround...works around the issue :-P Thanks for that suggestion and I look forward to a fix! :+1:

**Comment by luckman212** [comment]
Yes, hopefully _some_ of that $100MM in funding they just landed is going towards developers. The pace of bugfixes in Bitwarden is frustratingly slow.

**Comment by flaxton** [comment]
Not sure if you all mentioned it, but this happens to me in the browser extensions, but only on Chrome and Firefox.

On Safari it doesn't "stutter" like this and drop letters as I type.

I don't recall seeing it in the Bitwarden app itself.

**Comment by anastrophe** [comment]
Holy shit, $100 million?? Obviously it takes a few days for the ink to dry and the money to fill up the bank account, but - sure would like to know what plans there are for increasing dev staff. It's been seven months now since this bug was *introduced* into the code, and while I appreciate the statements back in July that this matter will be addressed, it does not seem that material bugs are a priority. The question is...what are the priorities? This is no longer the early days of an open source project funded by 'buy me a coffee' - this bug affects any customer using firefox or chrome. That's a LOT of affected customers.

Sorry for the harsh tone, but seven months to fix the damage of a one-liner diff....just no.

**Comment by dbosompem** [comment]
Hi all, we apologize for the delay in reviewing this and the inconveniences caused as a result. Issue has been prioritized and we are currently working on this issue , and would be resolved very soon. Thank you for your patience.

**Comment by drguildo** [comment]
I now seem to getting the same issue, or at least a similar one, when entering my master password.

**Comment by luckman212** [comment]
@drguildo Never seen that, but it's slightly terrifying. Imagine changing your master password and it randomly dropping the same keypress twice, poof you're locked out. 😐

**Comment by anastrophe** [comment]
> Hi all, we apologize for the delay in reviewing this and the inconveniences caused as a result. Issue has been prioritized and we are currently working on this issue , and would be resolved very soon. Thank you for your patience.

Assignees: No one assigned
Projects: None yet
Milestone: No milestone
Development: No branches or pull requests

I have a doubt.

**Comment by MGibson1** [comment]
@anastrophe, We don't use Github to track work. We've discussed how our decision to use outside ticketing software (Jira for now) will hurt transparency when we chose to use it. We have good reasons we wanted to use Jira (familiarity, broader feature set, discrete for security vulnerability issues), and those overruled for the time being.

We're always looking for ways to work better and more transparently where we can. Our solution for now is to tag issues we're working on in PRs we push up and open, as @dgoodman-bw did.

We also promise to not lie to you

**Comment by anastrophe** [comment]
Thanks. As I said, I had a doubt; I didn't accuse anyone of lying. Here's the problem as I see it:

1. A bitwarden user comes here to submit a bug report or feature request. They do so. A conversation arises. The 'assignees', 'projects' etc. box never updates. Without having previous knowledge that BW doesn't use github for tracking, what is one to assume from the information presented?
2. dbosempem posted that 'we are currently working on the issue' nine days ago. Three days ago I noted that the box showed zero progress - again, in a state of ignorance of the current backend machinations at work here, shared by I would assume virtually all end users of BW when they come here after experiencing an issue.
3. One day ago, dgoodman-bw linked the pull request to my comment of three days ago, about the (unintentional, to be clear) lack of transparency nine days ago. 

While obviously everyone there is hard at work, and you don't need peripheral issues taking up time ----- this "broken" flow of information has done just that. Needless effort in explaining to an average rube like me that what I see here unintuitively doesn't reflect what's happening elsewhere.

Along those lines of more work...perhaps investigate integration, at least of status, between Jira and github? A quick search brought this up  - https://exalate.com/blog/jira-github-integration/ - one of an assortment of products out there that appear to be designed to mitigate just this meta-problem. 

Or in the meantime, 'pin' an open issue called "All issues are tracked internally on JIRA, progress updates are not reflected here on github". 

Or - modify the bug reporting form, and have it clearly state (even in all-caps, for the slow among us like myself) that workflow status updates will not occur here. It certainly looks to me like that's customizable.

And with that, I'll shut-the-F-up, let you get back to work, and I thank you for an outstanding product that I use several dozens of times every single day.

**Comment by dbosompem** [comment]
Hi @anastrophe , thank you for the suggestion. We are always looking for ways to be transparent as we uphold that strongly as a value, and so we will better refine this process. Sorry for any misunderstanding or break in information. Thank you for your continuous use of Bitwarden. Your opinions are highly welcome, anyday!

**Comment by anastrophe** [comment]
I apologize for my somewhat harsh/less civil tone; a frustration like this - small but near constant - brings about the kind of aggravation that pushes me to be an arsehole sometimes. I appreciate your measured response in the face of that. :)

**Comment by MGibson1** [comment]
Sorry, didn't mean to put words in your mouth.

ooh I like the pinned issue and template ideas. I'll get some stuff set up for those in the morning.

We have a few integrations for Jira and github we're using, but (speaking for myself, not necessarily for Bitwarden), I'm a little hesitant on them. They always feel like square peg/round hole solutions that will bite you when you're least expecting them.

**Comment by anastrophe** [comment]
Agreed, cross-platform ju-ju is often...unsettling.

**Comment by anastrophe** [comment]
Noticed today it's fixed. Thank you so very much for that!

**Comment by drguildo** [comment]
Has this fix been published? I'm using version 2022.10.0 of the Firefox extension and still see the same behaviour.

**Comment by rdaugherty** [comment]
Hi all! Just to clarify things a bit here. This fix is NOT in the most recent 2022.10.0 release, as the ticket was completed near the end of this release cycle. However, based on our tracking in Jira, this ticket has been tested and is ready to go for our next release which should be in about 4-5 weeks given our normal release cadence.

**Comment by anastrophe** [comment]
Well, this is troubling. With the 2022.10.1 release, I'm now experiencing the issue in.......Opera. Which previously was unaffected by the issue.

Never had the issue previously with Opera.

Sigh.

**Comment by drguildo** [comment]
It's 3 months later, I'm on version 2022.12.1, and this bug is still present.

**Comment by ahsodex** [comment]
@mgombar This issue is marked closed. I doubt anyone from Bitwarden is monitoring it. It might be better to open a new one and mention this issue (and the other two above) in it.

I too am also still experiencing the issue, though not as frequent. It only happens to me now if I wait too long between keystrokes, like if I momentarily forget the next letter / get distracted. Whereas before the "fix", it happened if I didn't wait long enough.

As an aside, I recently tried out 1Password for a few months, used it as my main pw store, and it's not nearly as nice as Bitwarden, even with this frustrating issue going so long without an actual fix.

**Comment by drguildo** [comment]
It's over two years later and this is still an issue. It's still possible to lose characters if you type them at the "correct" moment. Why is this closed?

**Comment by bclaymiles** [comment]
> It's over two years later and this is still an issue. It's still possible to lose characters if you type them at the "correct" moment. Why is this closed?

The problem was fixed for a long time, but it has recently resurfaced, say in the last month or so. It's easily reproducable, and perhaps the fact that a fix was put in place previously, that can be found and reproduced relatively easily - I dunno, just speculating. But it is an infuriating bug when it happens.

**Comment by drguildo** [comment]
I don't think it was ever properly fixed; just look at the posts on this issue. The "fix" sounds like it was a hacky workaround that never worked properly. It still did that thing where it clears the text field while you're typing, it's just they tried to make it so that you don't lose text when it does it. A real fix would be not clearing the text field in the first place.

**Comment by bclaymiles** [comment]
So, since this bug report is closed, does that mean the coders aren't even aware of these reports that the bug has resumed? I recall a comment at one point  stating that the devs don't use github, using an internal process instead - and that bugs reported here have to (practically) be 'sneakernetted' to the real bug repo...

**Comment by danielleflinn** [comment]
Thank your for raising this issue. Bitwarden is working on an [updated extension design](https://bitwarden.com/blog/bringing-intuitive-workflows-and-visual-updates-to-the-bitwarden-browser/) and this behavior has not been able reproduced in the new design. Once the update is released, if you still are seeing this behavior, please open a new Github issue.
