### ISSUE TITLE
Still tells me  desktop app needs  to be started

### ISSUE THREAD

**Issue by YouveGotMeowxy** [bitwarden/clients#2402]
### Steps To Reproduce

Installed the latest everything as of today; and using the github version of BW, not the Windows Store version.

I have the  bw desktop app running in the tray, and even if I bring it out fo the tray, and then try to use the Hello feature of the extension (on MS Edge) it shows  me this:

![image](https://user-images.githubusercontent.com/39491297/155032924-9f7918ec-24a0-4247-aa7c-628abd383567.png)

### Expected Result

use my thumbprint to unlock the extension

### Actual Result

says  I need the desktop app running (it is).

### Operating System

Windows

### Operating System Version

11 ToGo

### Web Browser

Microsoft Edge

### Build Version

1.55.0

**Comment by red0fireus** [comment]
Same problem here. 
I even tried it on Windows Sandbox which is an absolute clean version of windows 11 and it doesn't work. Doesn't seem like its our problem....

**Comment by Hinton** [comment]
Hi,

Can you follow the steps from https://github.com/bitwarden/browser/issues/2258#issuecomment-1019933401 but check if `Computer\HKEY_CURRENT_USER\Software\Google\Chrome\NativeMessagingHosts\com.8bit.bitwarden` exists instead.
