### ISSUE TITLE
Safari Extension only shows blank screen with spinning wheel...

### ISSUE THREAD

**Issue by ctschach** [bitwarden/clients#2404]
### Steps To Reproduce

Safari Version 15.3 (17612.4.9.1.8)
on MacOS Monteray 12.2.1

1. Open Safari
2. Click on Browser Extension Symbol

### Expected Result

The extension doesn't show any content. **It's a Safari issue**. The Desktop clients work fine as well as the Chrome and Firefox extension.

### Actual Result

No interaction is possible. Even if you wait 5+ minutes

### Screenshots or Videos

![Bildschirmfoto 2022-02-22 um 14 55 46](https://user-images.githubusercontent.com/8994357/155147729-230ea29c-37c4-4edc-8f47-17635fea5baf.png)

### Additional Context

I already completely deleted Bitwarden using AppCleaner (which also removes content from ~/Library), quit Safari, rebooted the machine, and reinstalled Bitwarden from the App Store.

The problem remains. Also disabling and enabling the extension in Safari Settings doesn't help.

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Safari

### Browser Version

Version 15.3 (17612.4.9.1.8)

### Build Version

Bitwarden Desktop - Version 1.31.3 (2320) - Bitwarden Safari Extension 1.56.5

**Comment by ctschach** [comment]
I also try disabling all other extensions and restarting Safari - this didn't help...

**Comment by chuck614** [comment]
I have the exact same issue on every Mac I have tried it on.  Two different Intel Macs and an M1 based.  Same versions as above.

**Comment by addisonbeck** [comment]
Thanks for reporting this folks, definitely a strange and blocking issue.

Doing some digging I noticed that my persistent Safari extension data is stored here in my file system:
`~/Library/Containers/com.apple.Safari/Data/Library/Safari/WebExtensions/com.bitwarden.desktop.safari (LTZ2PFU5D6)`
I checked, and it looks like AppCleaner isn't removing this folder. Could you try manually deleting this folder and seeing where that gets you?

**Comment by chuck614** [comment]
> Thanks for reporting this folks, definitely a strange and blocking issue.
> 
> Doing some digging I noticed that my persistent Safari extension data is stored here in my file system: `~/Library/Containers/com.apple.Safari/Data/Library/Safari/WebExtensions/com.bitwarden.desktop.safari (LTZ2PFU5D6)` I checked, and it looks like AppCleaner isn't removing this folder. Could you try manually deleting this folder and seeing where that gets you?

This worked for me!  I have only tried it on the one Mac in front of me at the moment.  I also noticed that all my other attempts to reinstall I never received the automatic new tab webpage that talks about Bitwarden and the plugin the first time you activate it.  This time I did.

**Comment by ctschach** [comment]
Worked for me too....so the problem is solved.

However, it might be interesting why this happened. Unfortunately I just deleted the folder. Might have been interesting to further investigate the issue.

**Comment by addisonbeck** [comment]
I can shed a bit of light on what happened, though not much because this seemed to be an edge case and we haven't been able to recreate it on the team.

In February we had a release that contained a really large restructure of the storage layer of the Bitwarden clients. _Everything_ that is stored in the browser of all the clients was moved, and the only way to do that is to migrate that data on initial load of the application after an update. This is a rather fragile and cumbersome process.

Something went wrong with that migration here, corrupting that data and leaving the extension in a broken state it couldn't recover from. It's possible other browsers are effected to, and that they just haven't been reported on because Safari doesn't fully clear extension data on application delete.

**Comment by hlarsen** [comment]
I was also seeing this using the Firefox extension on Linux; removing and re-installing the extension fixed it.

**Comment by jmarkcoy** [comment]
I am experiencing the exact same thing. Bitwarden works completely fine even on another profile on this Mac but doesn't nothing but spin my current profile. I have gone through all the above (multiple times) and still nothing seems to fix it.

Also, went and looked for the path mentioned above, but it didn't exist. Open to ideas as I love Bitwarden.

How would one clear all the extension cache in Safari? That seems to be the problem to me. Whenever I reinstall, the Bitwarden extension doesn't go through the same permission requests etc. that it usually does on the first install.

**Comment by Ectalite** [comment]
Fixed in 1.32.1. 
Thanks !

**Comment by djsmith85** [comment]
Based on the report from @Ectalite this has been resolved with 1.32.1, the other commenters were able to get it to work via the work-around provided by @addisonbeck.

@jmarkcoy: Have you been able to get this working and can this issue be closed?

**Comment by chuckecheeseli** [comment]
I have this issue with Safari and Bitwarden versions listed below. I think this occurred when I updated Bitwarden to current version of 2024.3. Steps I've followed:

- uninstall Bitwarded using AppCleaner
- remove the entire directory of "/Users/[username]/Library/Containers/com.apple.Safari/Data/Library/Safari/WebExtensions"
- reinstall Bitwarden from App Store
- launch Safari
- Safari asked if I wanted to give it permissions to access current/all website, which I granted
- BItwarden extension still only displays spinning circle like OP showed


Safari Version 16.1 (18614.2.9.1.12)

Bitwarden
Version 2024.3.0
Shell 28.2.4
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64
