### ISSUE TITLE
Hotkeys and context menu does not reset the vault timeout timer

### ISSUE THREAD

**Issue by andreapx** [bitwarden/clients#2420]
### Steps To Reproduce

Set the _Vault Timeout_ to 1 hour.
Use the vault to autocomplete credentials on some websites.
After less than 1 hour after the last time I've used the vault to autocomplete credential on a website, the vault gets locked.

### Expected Result

The vault should be locked after the value set in _Vault Timeout_ has passed after the last time the vault has been used

### Actual Result

The vault gets locked before the value set in _Vault Timeout_. It seems to be random.

### Operating System

Windows

### Operating System Version

10 (20H2)

### Web Browser

Firefox

### Browser Version

97.0.1

### Build Version

1.56.6

**Comment by Filaipus** [comment]
I'm experiencing this too on Edge.

**Comment by MasterOfStar** [comment]
same bug on edge.
But only my timeout set different

**Comment by hml-github** [comment]
same bug on Firefox.
I found it would get locked everytime when the browser start, and ignored the value set in Vault Timeout.

**Comment by eliykat** [comment]
How are you autofilling? e.g. from the popup, context menu, or hotkeys? It's possible that our hotkeys don't reset the timeout.

@hml-github you're describing a different issue. Unless you have your Vault Timeout set to "Never", it will always lock when you restart your browser. This is because the extension closes when your browser closes, so it's not practicable to keep the timer running and we lock it for security.

**Comment by hml-github** [comment]
@eliykat Now I get it. Thank you.

**Comment by MasterOfStar** [comment]
> Timeout set to "Never

I set Vault Timeout Never and it's lock on restart browser.

**Comment by andreapx** [comment]
> How are you autofilling? e.g. from the popup, context menu, or hotkeys? It's possible that our hotkeys don't reset the timeout timer.

@eliykat I use hotkeys.

**Comment by itsfeng** [comment]
same here.  
vault timeout `never` is not respected on firefox.
it does however work with vivaldi browser.

**Comment by andreapx** [comment]
> How are you autofilling? e.g. from the popup, context menu, or hotkeys? It's possible that our hotkeys don't reset the timeout timer.

I've done some tests and I confirm that this problem is present only if I use hotkeys, every time I use the plugin icon, the timer gets reset

**Comment by Hinton** [comment]
@eliykat I believe we only reset the timer in the popup.

**Comment by andreapx** [comment]
> @eliykat I believe we only reset the timer in the popup.

@eliykat @Hinton are you planning to reset the timer even when using shortcut/context menu?

**Comment by eliykat** [comment]
Yes I think we should, the current behaviour seems like an oversight to me. This will be triaged for a fix, or PRs are welcome if anyone wants to fix it sooner.

**Comment by andreapx** [comment]
Please don't forget about this!
Unfortunately I can't code at all, so I'm not helpful...

**Comment by andreapx** [comment]
@eliykat please don't forget about this, pleeeeease!

**Comment by schang1146** [comment]
Looking in the console.log, I'm seeing it fire the error `Did not auto-fill.` when using the keyboard shortcut even if it did do the thing.

Ubuntu 22.04.2 LTS
Firefox 112.0.1 (64-bit)
Bitwarden Extension Version: 2023.3.1
