### ISSUE TITLE
Bitwarden Microsoft Edge extension does not offer to store login details, password

### ISSUE THREAD

**Issue by gustavoagp** [bitwarden/clients#2424]
### Steps To Reproduce

Bitwarden Microsoft Edge extension does not offer to store new password on registration and/or update.
Password management is disabled for MS Edge

### Expected Result

Should get Bitwarden to offer to store login credentials when registering on a website, or password update and extension is enabled and logged in

### Actual Result

No offer whatsoever

### Additional Context

This is MS Edge running on Windows 11 Pro

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.31.3, Extension version: 1.55.0

**Comment by Hinton** [comment]
Hi @gustavoagp, can you check the extension options (`settings -> options`) and verify that "Disable Add Login" and "Disable Change password" options are not enabled?

![image](https://user-images.githubusercontent.com/137855/156257887-acef00d5-69c0-4420-8c5b-120f01a9b201.png)

**Comment by djsmith85** [comment]
Hi @gustavoagp, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
