### ISSUE TITLE
Contextual menu does not detect website properly

### ISSUE THREAD

**Issue by jwestlake** [bitwarden/clients#2455]
### Steps To Reproduce

1. Go to website ABC.com (any site where the plugin could be used).
2. Right click on the field to be filled with the Bitwarden plugin, select "Auto-fill".
3. Rather than see the correct website credentials presented in the "Auto-fill" list, it presents a different website.  This same website is presented in "Auto-fill" throughout all other websites where I right-click and try to use the contextual menu.

![BitwardenBug](https://user-images.githubusercontent.com/55899/158621993-4542e333-009a-42e0-a7d0-b19e990a0ded.jpg)

### Expected Result

I expect to be presented with the correct website when right-clicking on a fillable field and selecting "Auto-fill".

### Actual Result

Presently, a different website is presented in Auto-fill rather than the correct website.

### Screenshots or Videos

![BitwardenBug](https://user-images.githubusercontent.com/55899/158622250-c49f6543-5278-4e9c-a35a-c76a6be7078c.jpg)

### Additional Context

I either have to quit my browser or deactivate/reactivate the plugin for it to start detecting again.  Eventually, the problem will return... I have not yet found what triggers the issue to begin with.

### Operating System

macOS

### Operating System Version

12.3, 12.2.x

### Installation method

Mac App Store

### Build Version

Version 1.31.3 (2320)

**Comment by dzirtusss** [comment]
@jwestlake after starting extension in a bit different way like explained here, seems to go away for me:

> Thank you for bringing this to my attention. I was able to reproduce this on macOS 12.3, Safari 15.4, and Bitwarden extension 1.56.6, and we're looking into this internally. Please note that this appears to occur only when the extension is unlocked through an autofill attempt (CMD+SHIFT+L); If you unlock the Safari extension the moment you open Safari, either by clicking on it or by pressing CMD+SHIFT+Y, the extension would then operate as expected and match and autofill vault items consistently.

https://github.com/bitwarden/bitwarden/issues/2456#issuecomment-1073976192

**Comment by djsmith85** [comment]
@jwestlake With the changes I mentioned (#2447) having been released, has updating the browser extension fixed the issue?

**Comment by jwestlake** [comment]
I'm still seeing the issue now after a few days of trying it out.

This morning, I launched Safari (version 15.5 (17613.2.7.1.8)) and came to
a login field. I used the contextual menu to bring up Bitwarden (version
2022.5.1 (3283)) > Unlock My Vault. I unlocked using Touch ID on my laptop.
The first page presented the correct item in the contextual menu >
Autofill. When I brought up a new page/site, I used the contextual menu
again and was only presented the option for the first site where I unlocked
Bitwarden.  I then logged out of Bitwarden, logged back in, reloaded the
page I was on, and although my Bitwarden is unlocked in the toolbar of
Safari, the contextual menu shows "Unlock My Vault" on the website. If I
choose "Unlock My Vault", it populates the correct information for the site.

So, unfortunately, the issue still remains.  I'll be happy to help out
however I can. Let me know if you need anything else from me.

Jason

**Comment by jwestlake** [comment]
BTW, all future sites now show "Unlock My Vault" when using the CM.  (Just launched Github and "Unlock My Vault" was the only option for credentials. I locked vault, unlocked again (bypassed Touch ID this time), and now the CM only shows the credentials for the page I was on when I unlocked (in this case, Github). 🤔😕

**Comment by jwestlake** [comment]
Hi all,

I haven’t noticed it happening lately, so that’s a good sign. I’ll double
check when I get home to make sure I’m running the latest version (do you
have an exact version/build it was released in?).

Thanks for this, it was extremely annoying! :-)

Jason

**Comment by djsmith85** [comment]
@jwestlake Closing this now, as this seems resolved.
