### ISSUE TITLE
Ignore accented characters in vault searches

### ISSUE THREAD

**Issue by plourenco** [bitwarden/clients#2479]
### Steps To Reproduce

1. Create a credential with accented characters "olá"
2. Search for "ola"
3. No results are shown

### Expected Result

A credential containing "olá". As accented characters should have an equivalent.

### Actual Result

No results are shown.

### Additional Context

It would be an useful enhancement to have matches for accented equivalents, either by ignoring them on (I assume) `searchCiphers` or stripping those characters out, e.g.: 

```javascript
str.normalize("NFD").replace(/[\u0300-\u036f]/g, "")
```

### Operating System

macOS

### Web Browser

Firefox

### Build Version

1.57.0

**Comment by djsmith85** [comment]
Hi @plourenco and thank you for your report.

I think this already got addressed with a previous release. Would you mind updating to the newest version and confirm this is fixed.

Kind regards,
Daniel

**Comment by plourenco** [comment]
Yes, confirmed. Thanks!
