### ISSUE TITLE
"Enable browser integration" should be grayed out when using Linux

### ISSUE THREAD

**Issue by bramirezMAP** [bitwarden/clients#2556]
### Steps To Reproduce

1. On the desktop app, go to **File > Settings > App Settings (All Accounts)** and ensure that **Enable browser integration** is enabled.
2. Open the extension and go to **Settings > Security**.
3. Try to check **Unlock with biometrics**.

### Expected Result

One of the two:
- Browser integration works successfully
- I should not have been allowed to enable browser integration in step 1 because it is not supported on the platform; the option should be grayed out.

### Actual Result

An error appears that says "Browser integration is not enabled" is displayed even though browser integration was marked as enabled in desktop, because biometrics is not supported and thus the desktop app does not actually enable integration.

### Additional Context

Web extension info:
- Build: 1.58.0
- Browser: Firefox 99.0.1

See bitwarden/desktop#1132 - @eliykat had suggested creating a new issue to track disabling this item in the UI but seems that it was never created.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04 LTS

### Installation method

Snap

### Build Version

1.33.0

**Comment by LosD** [comment]
This is not complete. An error message is not the same. Especially when it looks like this:
![image](https://github.com/bitwarden/clients/assets/1282832/78604363-b4ef-4a2e-96e1-ceab2d5fcfd5)

**Comment by djsmith85** [comment]
@LosD The error message being displayed like that, is unrelated to this issue. 
It's more likely related to https://github.com/bitwarden/clients/issues/2628

Kind regards,
Daniel
