### ISSUE TITLE
Windows Installer is not asking for location

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#2557]
### Steps To Reproduce

1. Uninstall the current desktop app
2. Install Desktop app on Windows

### Expected Result

Installer is asking for installation location

### Actual Result

Installer doesn't ask and proceed to install to the default location

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by Hinton** [comment]
We no longer support installing to custom locations.

If you really want to, it might be possible using `/D` argument to the NSIS installer, but it's not something we support and the upgrade behavior is unknown.
