### ISSUE TITLE
Entries that have the same text prefix, but numerical suffix, do not appear in correct order

### ISSUE THREAD

**Issue by AJerm** [bitwarden/clients#2558]
### Steps To Reproduce

Have multiple entries that start with the same name, but then are numbered, as per the screenshot. 

When I type in the search term 'Hik', the results do not order correctly by the text first, then by number, as per the screenshot.

![image](https://user-images.githubusercontent.com/1643439/166462129-69a8542f-592a-4f40-8eab-1bde161dd9c9.png)

### Expected Result

It should be ordered

Hik Cam 1 - .....
Hik Cam 2 - .....
Hik Cam 3 - .....
Hik Cam 4 - .....
Hik Cam 5 - .....
Hik Cam 6 - .....
...

### Actual Result

![image](https://user-images.githubusercontent.com/1643439/166462202-5f52e1d2-8773-4fba-88ad-e89de2d51849.png)

### Operating System

Windows

### Operating System Version

Win 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by CarleyDiaz-Bitwarden** [comment]
Hello @AJerm I am researching into this bug you are experiencing but am unable to replicate it, can you please confirm you are typing in "Hik" as your search term? For me, everything appears to order properly (closer matches at the top) and alphabetically until I enter "-" in my search, then it gets a little unorganized.

**Comment by AJerm** [comment]
Hi there,

I'm not on my computer at the moment, but that is correct.

I frequently edit these entries with updated info such as custom fields with IP addresses, so you may need to edit one or two of them out of order and save them? 

Or perhaps rename some of them? 
If they were added all correctly from scratch they might be okay, perhaps it's after renaming?

**Comment by CarleyDiaz-Bitwarden** [comment]
Thank you for the additional information! I am curious, do you notice this
happening only with items with "-" in the name? What I'm going to do next
is compare the code inside the IOS app and inside the chrome extension as
well.

**Comment by CarleyDiaz-Bitwarden** [comment]
@AJerm thank you again for the extra information! In your original post you shared a screenshot of the unordered results from the Desktop app, can you please send me that same screenshot but including the entire text?

**Comment by AJerm** [comment]
Hi Carley, I just tried emailing you a more detailed screenshot to your github email address as I don't want to post that info publicly. If it doesn't come through, maybe give me your bitwarden email and I can send you a screenshot there.

**Comment by CarleyDiaz-Bitwarden** [comment]
@AJerm can you please send it to cdiaz@bitwarden.com thank you!

**Comment by Krychaz** [comment]
Hello there, 

I was unable to replicate this behaviour. From my testing, everything is working as expected when running the latest version. If you still experience this issue, please contact our support team - https://bitwarden.com/contact/
<img width="374" alt="SCR-20240104-mpji" src="https://github.com/bitwarden/clients/assets/36608718/631abe86-afb2-47c1-a673-184cea359855">

**Comment by AJerm** [comment]
Hi @Krychaz 

I've just tested the Chrome extention and still seems to be doing it for me. 

The first 8 are fine, but then the format changes and the Hik Cam x format is totally jumbled

![image](https://github.com/bitwarden/clients/assets/1643439/88a5fc60-f937-4fbc-98ec-1fb7b7ddb41e)
