### ISSUE TITLE
Search does not get cleared when switching between accounts

### ISSUE THREAD

**Issue by dmlemos** [bitwarden/clients#2562]
### Steps To Reproduce

1. Create two accounts
2. Login to the accounts
3. Search for anything in account 1
4. Switch to account 2

### Expected Result

Search bar cleared

### Actual Result

Search bar contains the previous search term

### Additional Context

I doubt anyone has duplicate records, hence the search bar persisting between accounts should not happen.

### Operating System

macOS

### Operating System Version

11.6.5

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by evelez7** [comment]
I've tried looking into this and it seems that this only happens in production versions of the application. I've built from source in Windows, macOS, and linux and I cannot replicate this in those situations, but they do occur in the production app. Seems difficult to triage.

**Comment by dmlemos** [comment]
Wouldn't that imply the production code for the client is not reproducible? 😮

**Comment by Hinton** [comment]
Resolved in https://github.com/bitwarden/clients/pull/2685, will be available in the next major release.

**Comment by dmlemos** [comment]
@Hinton This is not fixed in v2022.5.1
