### ISSUE TITLE
A11y: not possible for keyboard users to reach the control to edit folder in left-hand column

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/clients#2567]
### Steps To Reproduce

1. Navigate using the keyboard `Tab`/`Shift+Tab`
2. Navigate through the interface until your reach any defined folders
3. Set focus on a folder

### Expected Result

Once focus is on a folder, the "Edit" pencil icon is shown. I'd expect to be able to now `Tab` forward once more to set focus not on the folder itself, but on its edit button (to then hit `Enter` or `Space` to toggle the edit modal).

### Actual Result

There is no current way (it seems) for a keyboard user to either reach the "Edit" control, or to trigger edit in some other way. Further, when running a screen reader, the folder control itself is misleadingly announced as `[Folder name] Edit Folder` (e.g. "#id24 Edit Folder") even though editing is not possible.

### Screenshots or Videos

![screenshot showing part of the folder column, with one folder focused with the keyboard and the pencil icon showing](https://user-images.githubusercontent.com/895831/159761132-c96caa64-6743-4a64-9819-5ef3fc992731.png)

![screenshot showing the same folder control highlighted, with NVDA's speech viewer running and showing that it is announced as "#id24 Edit Folder"](https://user-images.githubusercontent.com/895831/159761561-4d813b4b-c941-4f34-9112-e0c4f7682f92.png)

### Additional Context

The cause of this is likely that the "Edit" pencil icon is inside the control for the folder, and is not currently keyboard focusable.

As you can't validly have focusable controls inside each other, I'd recommend splitting this into two parts: one control to toggle the folder, and one adjacent separate control to edit it. ideally, give that second control an accessible name (i.e. `aria-label`) that tie it back / include the name of the folder, for clarity.

for instance, something along these lines (also  foreshadowing that these should really be `<button>` elements, per https://github.com/bitwarden/desktop/issues/1435)

```
<button type="button" ...>#id24</button> <button type="button" ... aria-label="Edit Folder #id24">Edit Folder</button>
```

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.32.1 Shell 16.0.7 Renderer 96.0.4664.110 Node 16.9.1 Architecture x64

**Comment by djsmith85** [comment]
@patrickhlauke Thank you for bringing this up. Can this be closed as the work that @addisonbeck mentioned has been released, or is this still an issue?

**Comment by patrickhlauke** [comment]
@addisonbeck just coming back to this comment

> collapsable folders and collections isn't paywalled, though it's probably not very intuitive to do. Simply creating a folder with a name like {parentName}/{childName} will nest the folder.

I tried, but all I get is a folder that then has the name "beep/boop" or similar. Am I missing something?

**Comment by patrickhlauke** [comment]
@djsmith85 

> @patrickhlauke Thank you for bringing this up. Can this be closed as the work that @addisonbeck mentioned has been released, or is this still an issue?

confirming that with the edit/pencil icon button for the folder can now be focused/activated correctly using the keyboard.

I see that the control is announced just as "Edit folder", without further context (e.g. "Edit folder: #id24"), but I might file that as a separate suggestion.

Closing this issue as resolved.
