### ISSUE TITLE
Update continuously offered at Windows start despite being at latest version 

### ISSUE THREAD

**Issue by ComotoJC** [bitwarden/clients#2571]
### Steps To Reproduce

Steps to reproduce?  Uh. i guess...
1. Start with 1.31 version
2. Restart windows and wait to be prompted for update
3. Respond yes to update installation and restart BW
4. Restart windows and wait to be prompted yet again to install update 
5. Manually check version to see it has not worked
6. Manually install latest version 1.32
7. Start BW and manually check for update and see that "no update available"
8. Restart windows and wait to be prompted yet again to install update despite being on latest version 

### Expected Result

This format for BR is kind of ridiculous for this type of thing which could be explained better in just one box but OK... 

1. Ensure that windows-start update prompt actually installs update if one is available. 
and 
2. Don't prompt for an update if program is already at latest version

### Actual Result

On windows startup for some time now, BW **always** offered to install an update and requests a restart.  
Not only was the windows-start update not working, but now, seems that the version check is returning erroneous status.   

At first it turned out the update process - despite responding properly to all prompts for admin access etc. - was not actually installing the latest update (to 1.32 when I checked) manually downloaded and installed update.  Extremely high number of times I authorized install of the update but it did not install. 

Then after doing manual 1.32 install, on Windows reboot BW still requests to install and restart every time despite being on latest version.  Manually checking for updates returns - as it should - 'no update available'. Yet on next Windows restart i will get prompted again to install an update and restart BW.   

### Additional Context

Version 1.32.0
Shell 16.0.7
Renderer 96.0.4664.110
Node 16.9.1
Architecture x64

### Operating System

Windows

### Operating System Version

10 Pro x64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

See text of bug report

**Comment by Dwuuds** [comment]
Been happening for months now

**Comment by Hinton** [comment]
@Dwuuds Is the MS store prompting you to upgrade? The built in update process is supposed to be disabled on the store builds.

**Comment by ts1985** [comment]
> Wanted to give a quick update on this. As previously mentioned we identified some issues with the updating process which should be resolved for the next release.
> 
> In the meanwhile the recommended workaround is to:
> 
> 1. Uninstall the desktop application.
> 2. Restart the computer
> 3. Re-install the latest version from the website.
> 
> Should Bitwarden auto start after restarting the computer you most likely have multiple versions of Bitwarden installed, and need to uninstall all of them.
> 
> The default installation locations are:
> 
> * `C:\Program Files\Bitwarden`
> * `%LocalAppData%\Programs\Bitwarden`
> 
> And they should contain an Uninstaller which you can run.

This doesn't really help. Here the solution:
- Follow the steps from Hinton
- Before the restart, delete also: %LocalAppData%\bitwarden-updater
- Then restart and follow the other steps.

That should work.

**Comment by BobbyWibowo** [comment]
For whatever reason, desktop client's auto-update for version 2022.5.0 simply uninstalled my existing Bitwarden installation, and did NOT continue to upgrade, lmao

**Comment by kkrza8** [comment]
I experienced the exact issue as Bobby above.

**Comment by Rykimaruh** [comment]
> > Wanted to give a quick update on this. As previously mentioned we identified some issues with the updating process which should be resolved for the next release.
> > In the meanwhile the recommended workaround is to:
> > 
> > 1. Uninstall the desktop application.
> > 2. Restart the computer
> > 3. Re-install the latest version from the website.
> > 
> > Should Bitwarden auto start after restarting the computer you most likely have multiple versions of Bitwarden installed, and need to uninstall all of them.
> > The default installation locations are:
> > 
> > * `C:\Program Files\Bitwarden`
> > * `%LocalAppData%\Programs\Bitwarden`
> > 
> > And they should contain an Uninstaller which you can run.
> 
> This doesn't really help. Here the solution:
> 
> * Follow the steps from Hinton
> * Before the restart, delete also: %LocalAppData%\bitwarden-updater
> * Then restart and follow the other steps.
> 
> That should work.

None of these work for me. I noticed that the uninstall doesn't really do anything, normally it would clean up the folder from any remnants, but nothing happens after I restart, I get the BitWarden popup with the updater after doing the entire process and restarting.

Will await for further instructions

**Comment by Hinton** [comment]
For those that are still encountering this issue please perform the following steps:

1. Uninstall Bitwarden
3. Verify there is no Bitwarden instance installed in either
	- `C:\Program Files\Bitwarden`
	- `%LocalAppData%\Programs\Bitwarden`
4. If any of the above paths exists please run the `Uninstall Bitwarden.exe` from that directory.
5. Restart your computer (important!)
6. Install the latest version of Bitwarden.

If the issue still persists after following these steps please let me know.
Please include the last couple of lines from `app.log` in `%LocalAppData%\bitwarden`. Everything after the last `Checking for update`, including any log for the update process.

**Comment by djsmith85** [comment]
Closing this issue as it appears the originally posted problem has been resolved. 

For users still experiencing this behaviour please have a look at the comments from @Hinton / @ts1985
