### ISSUE TITLE
Tray icon left and right click does the same

### ISSUE THREAD

**Issue by MartinX3** [bitwarden/clients#2584]
### Steps To Reproduce

1. Right click on the tray icon
2. Left click on the tray icon

### Expected Result

Left click opens bitwarden
Right click opens context menu

### Actual Result

Left click opens bitwarden
Right click opens context menu

### Screenshots or Videos

Left click opens context menu
Right click opens context menu

### Operating System

Linux

### Operating System Version

Arch Linux

### Installation method

Other

### Build Version

1.31.3

**Comment by monkeyhybrid** [comment]
I'm fairly new to Bitwarden so wasn't sure what the norm was supposed to be, regarding system tray icon behaviour. However, my expectations for system tray icons are generally left click opens the app and right click opens a context menu. It would be nice if Bitwarden was to do the same, in my opinion.

**Comment by poeck** [comment]
I'm on Linux (Ubuntu 22.04) and for me all apps open context menu on left click, so I think this is a standard.
Although I would also prefer the app to open on LMB, I am really used to the context menu.

**Comment by monkeyhybrid** [comment]
@poeck That's interesting. Are you using Gnome by any chance? I'm using KDE and I've just tested all my normal system tray stuff, plus some apps that leave an icon there (e.g. VLC, Nextcloud) and they are all left-click show/hide, right-click context menu other than the one exception I came across - Bitwarden. I've not used a non-KDE desktop for a while to compare, but if nothing else it suggests there's not much of a standard.

Maybe the behaviour could be user selectable in the settings?

**Comment by d-air1** [comment]
Gnome doesn't even have a system tray, so if @poeck is on Gnome. It would likely be an extension that is making that decision. I would also like for the left click to show/hide bitwarden and the right click to show the context menu. That extra click to open bitwarden actually makes me dread using the system tray icon altogether.

**Comment by t3chguy** [comment]
Electron has fixed this upstream in v22.x https://github.com/electron/electron/issues/36283

**Comment by d-air1** [comment]
Just wanted to say this issue has been resolved for me in arch with electron version 24.

**Comment by djsmith85** [comment]
@d-air1 Thank you for the update.

We bumped to Electron to v24 with https://github.com/bitwarden/clients/pull/5205 which got included with `2023.5`

Closing this now.

**Comment by monkeyhybrid** [comment]
Awesome! Just tried it with BitWarden 2023.5.1 on KDE and it also now works the way I'd expect (left-click opens app, right-click opens context menu).

Thank you to all of those involved.
