### ISSUE TITLE
Browser integration, Bitwarden update, and Multiple users

### ISSUE THREAD

**Issue by natsbar** [bitwarden/clients#2586]
### Steps To Reproduce

1. Windows 11 (and probably 10) with multiple users
2. Update Bitwarden when notified of a new version
3. Change to a user other than the one that updated Bitwarden
4. Open a browser and try to log into Bitwarden extension with biometrics
5. Error message to start the Bitwarden application
6. Only solution is to install Bitwarden for every user separately

### Expected Result

One install or update of Bitwarden should not break browser integration for all other users.

### Actual Result

Browser integration is only possible for the user that updates or install the application. After an install or update of the application all users should be able to use browser integration.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.31.3

**Comment by popy2k14** [comment]
Exact same issue here. would be nice to see a fix soon.
thx
