### ISSUE TITLE
Umlaut character in dot-hidden master password not accepted anymore on macOS

### ISSUE THREAD

**Issue by aeroperf** [bitwarden/clients#2602]
### Steps To Reproduce

1. On macOS Bitwarden app, ensure visibility toggle is set to hidden
2. Type `Option-u` followed by the lowercase `a`; observe a single dot
3. Set visibility toggle to not hidden, observe letter `a` instead of the expected `ä`

### Expected Result

With master password hidden, I would expect use of `Option-u` followed by `a` to provide `ä` when the password is made visible, but `a` is shown instead.

### Actual Result

Letter `a` is shown instead of the expected `ä`

### Additional Context

This appears to be a regression starting with version 1.29.0 as previously this worked fine. The current workaround is to unhide the password, type in that one umlaut character when password is visible and then hide the password again for the rest of typing it.

### Operating System

macOS

### Operating System Version

Big Sur 11.6.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.29.1 (1802)

**Comment by djsmith85** [comment]
Closing this in favor of https://github.com/bitwarden/clients/issues/2472 as they are duplicates and the other has some more recent comments/examples.
