### ISSUE TITLE
Buttons for new "send" feature should not be part of scroll bar

### ISSUE THREAD

**Issue by mwoelke** [bitwarden/clients#2612]
## Describe the Bug

When having a lot of collections in the vault, you have to scroll down all the way to reach the new "send" feature.

I doubt that this is the intended behaviour, therefore I consider this a bug instead of a feature request.

## Steps To Reproduce

Add many collections or folders to a vault.

## Expected Result

The two buttons "vault" and "send" should always be visible instead of being at the bottom of the scroll bar.

## Actual Result

See screenshot

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/37511215/111137784-8003b700-857f-11eb-9323-c91fe41ca290.png)

## Environment

- Operating system: Windows 10
- Build Version: 1.25.0

**Comment by djsmith85** [comment]
Per my comment [here](https://github.com/bitwarden/desktop/issues/1513#issuecomment-1113991145) this was addressed with https://github.com/bitwarden/desktop/pull/1487 and will be included in the next release. 

If this is still an issue after installing the upcoming release, feel free to report back and we'll re-open.

**Comment by webdev69420** [comment]
I saw this has finally been added but it seems that the 1px border/separation line on top of those 2 buttons is gone, which looks weird. Could you please add it back? It should look the same as the 1px line above the "+" button next to it.

Here's a [screenshot of the issue](https://cln.sh/vRcZRW), if my post is unclear to you.

**Comment by webdev69420** [comment]
Any updates on the 1px border?
