### ISSUE TITLE
The strange tagged version 1.31.2 could mislead version checkers

### ISSUE THREAD

**Issue by proletarius101** [bitwarden/clients#2613]
## Describe the Bug

There is a tag `1.31.2` [in this repo](https://github.com/bitwarden/desktop/releases/tag/1.31.2) which is not incremental and doesn't belong to any branch. A non-incremental tag/release could simply mislead version checkers like https://release-monitoring.org/project/179174/.

## Steps To Reproduce

1. Go to https://release-monitoring.org/project/179174/

## Expected Result

The latest version should be 1.25.0. 

## Actual Result

The latest version shown in the lower left is 1.31.2 rather than 1.25.0 because 1.31.2 is higher than 1.25.0. But 1.31.2 was tagged in 2018.

## Environment

- Operating system: [e.g. Windows 10, Mac OS Catalina]
- Build Version (go to "Settings" → "About"): [e.g. 1.16.10]

## Additional Context

So 1.31.2 should be untagged.

**Comment by Hinton** [comment]
The v1.32.2 tag was in the old [desktop ](https://github.com/bitwarden/desktop) repository which is now archived. And we can't make changes to it due to it's archived state.

Since we've both changed the versioning and moved the repository, I consider this issue resolved, and will close it.
