### ISSUE TITLE
Scaling factor not remembered on reboot.

### ISSUE THREAD

**Issue by ChooChooAl** [bitwarden/clients#2614]
I can use the ctrl + to expand the font for the aged weary eyes, maybe 2-3 clicks.  Let's call it level 4, level 1 being the default smaller font.   When I reboot and log in, the vault is back to the default small font (level 1).   If I hit the ctrl + one time, the font jumps real large, level 5.   <br>
Seems to appear that bitwarden knows I want the font scaled larger (level 4) but doesn't display it that way initially.  When I scale it up one level after the restart, it <i>does</i> seem to remember the scale factor since it jumps to the next level above what I wanted.  (level 5) <br>
So I wind up having to hit ctrl + and then ctrl - to joggle it's memory to get it back to my font size.

## Expected Result
It should remember and reset to my desired font scale.
## Actual Result
It doesn't

## Environment
Linux Mint 20.1 Cinnamon 64bit.  <br> 
Version 1.24.6
Shell 6.1.7
Renderer 76.0.3809.146
Node 12.4.0
Architecture x64

I don't think screenshots would add anything to the issue.

**Comment by djsmith85** [comment]
This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2623.

I'm closing this now.
