### ISSUE TITLE
Zoom level not remembered on Ubuntu & Windows consistently

### ISSUE THREAD

**Issue by rohit** [bitwarden/clients#2623]
## Describe the Bug
The Bitwarden desktop application on Ubuntu does not remember zoom settings. My laptop display has a high resolution and so I need to be able to zoom for the UI to be legible. Setting the zoom level manually at the moment every time I start the app.

## Steps To Reproduce
1. Start Bitwarden desktop application
2. Login/Unlock account.
3. Set zoom level using menu bar or keyboard shortcut.
4. Close application.
5. Relaunch application.

## Expected Result
My previously set zoom level should be restored.

## Actual Result
The zoom level is reset to default making everything small again.

## Environment

- Operating system: Ubuntu 20.04
- Version: Version 1.20.1
- Shell: 6.1.7
- Renderer: 76.0.3809.146
- Node: 12.4.0
- Architecture: x64

## Additional Context
There appears to be some memory retention of the zoom level because when I try to zoom again it goes one level higher then what I've set. So I'm guessing the zoom level is remembered but not applied at startup?

This might not be a priority as it's not the responsibility of the application to deal with HiDPI screens(?), but since there is the option to set zoom levels, being able to remember it would be a big help. I'd be happy to help with the code if it isn't very complicated to fix.

**Comment by mcint** [comment]
I'm having this issue on macOS as well. Zoom levels are not remembered across application restarts. As of latest upgrade `Version 2022.6.1 (3610)`.

**Comment by dbosompem** [comment]
@skyler-shuman have you been able to make progress with this? If not, I can unassign , and be open to any PR. @anthonygedeon you could also let me know if still interested to work on this, and it would be assigned to you.

**Comment by skylerahuman** [comment]
My apologies for not communicating better. I had some issues that limited my ability to work on the project.

My initial idea for a solution was to extend the `WindowState` to include the `webPreferences -> zoomState`. However, there is not currently a use of `webPreferences` in `updateWindowState` and I'm unsure if it would be a good idea to add one.

An alternative solution, similar to what occurred in [standardnotes](https://github.com/standardnotes/desktop/pull/355) would be to introduce a zoomManager dedicated to handling zoom. However, this doesn't seem like the best solution given BrowserWindow already has a webPreferences object which stores the zoomState and can restore it when being instantiated. 

I am also confused why `updateWindowState` takes the argument `configKey` but the only `configKey` ever passed is `mainWindowSizeKey`. It appears to imply there are multiple possible `WindowStates` however, the TODO in the WindowState class implies there should only be a singular client-specific global state. 

Finally, why is `windowStates`'s type declaration not for values of the class `WindowState`?

**Comment by jebby7** [comment]
This has been happening to me on Win 11 for some time. No updates in the past 6 months have fixed it. I'm currently on 
Version 2025.3.0
SDK 'main (50f5a17)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64
I'm elderly and can't see it without zooming in a lot. The Android app has a similar problem since before Xmas, as in it's too small to read it at all. I prefer Bitwarden to others I have tried, but its no use if I can't see it. Can It be fixed, as its quite annoying. TIA

**Comment by trmartin4** [comment]
@jebby7 thank you for reaching out.  We investigated this issue internally and were not able to reproduce.  Could you possibly retry with the current desktop version and let us know if you still are able to reproduce it?

If so, could you let us know if there are any particular actions you're taking after you set the zoom level?  A screen recording would be helpful if that is possible.

If you have a problem with the Android app, I would recommend filing a corresponding issue on the https://github.com/bitwarden/android repo.

Thank you.

**Comment by jebby7** [comment]
I have an account on github, but I'm not PC /  IT trained (I am a retired
medic), so I don't know how to upload a screen recording there. I have
filmed with my phone, and was going to attach here. They are too big for
the email client (apparently). The Windows app is fine while I'm using the
PC. However, when I reboot (I do, daily) the zoom resets to default which
is too wee for my old eyes. I normally have it zoomed +3x
