### ISSUE TITLE
Generate duplicates bitwarden notifications tray icons by repeating clicking on notification tray shortcut option on the deepin desktop environnement.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [bitwarden/clients#2626]
![deepin-screen-recorder_Select area_20200321140011](https://user-images.githubusercontent.com/13170204/77226935-55556d00-6b7c-11ea-8551-7c872e9da217.gif)
On the deepin desktop environment, repeating clicking the notification tray shortcut setting create an infinite amount of bitwarden notification trays icons. However, those notifications trays icons doesn’t seem to work despite the number of created notifications trays icons.
This happens : 
— If the dock is hidden between each generation of a new icon (Showed in the GIF preview)
— If the dock is kept visible.
— If the dock has been expanded or not (With or without the other cases combined)
— If the dock is moved in another part of the screen (With or without the other cases combined)

Cleaning up the created mess is as easy, as closing the bitwarden app process.

I’m currently experimenting it on a ¨habitually unsupported build using this AUR package [bitwarden-bin](https://aur.archlinux.org/packages/bitwarden-bin) based on that GitHub.deb release executables.
So, not the AppImage, or snap package that would be suggested for Arch Linux distributions.
I wasn’t able to test this issue on a Debian based Operating system with the deepin desktop environment, to see if this could be a behavior being caused by the Desktop environment, or the operating system base.
Might be related to this even though, it seems to occur on a Windows operating system : bitwarden/clients#2631

```bash
                   -`                    pm@VIX 
                  .o+`                   ------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 5.5.10-arch1-1 
               `+oooooo:                 Uptime: 51 mins 
               -+oooooo+:                Packages: 1474 (pacman), 5 (flatpak) 
             `/:-:++oooo+:               Shell: bash 5.0.16 
            `/++++/+++++++:              Resolution: 3440x1440 
           `/++++++++++++++:             DE: Deepin 
          `/+++ooooooooooooo/`           WM: Mutter(DeepinGala) 
         ./ooosssso++osssssso+`          Icons: Papirus-Dark [GTK2/3] 
        .oossssso-````/ossssss+`         Terminal: deepin-terminal 
       -osssssso.      :ssssssso.        Terminal Font: SF Mono Powerline 11 
      :osssssss/        osssso+++.       CPU: AMD Ryzen 5 3600X (12) @ 3.800GHz 
     /ossssssss/        +ssssooo/-       GPU: NVIDIA GeForce GTX 1060 6GB 
   `/ossssso+/:-        -:/+osssso+-     Memory: 5015MiB / 32044MiB 
  `+sso+:-`                 `.-/+oso:
 `++:.                           `-/+/                           
 .`                                 `/                           

```

**Comment by djsmith85** [comment]
@PoorPocketsMcNewHold Is https://github.com/bitwarden/clients/issues/2630 possibly a duplicate of your report?

**Comment by PoorPocketsMcNewHold** [comment]
Seems like it. I don't use the deepin desktop environnement but the behavior doesn't seems to be distro-specific if it's actually creating new processes instead of not clearing the previous instances. I'll close it for potentially be a duplicate. Deepin users, feel free to re-open it if you don't think the same.
