### ISSUE TITLE
MacOS desktop client does not respect OS-level cursor/caret blink rate settings

### ISSUE THREAD

**Issue by dmattera** [bitwarden/clients#2627]
MacOS: 10.15.2
BitWarden: 1.16.6

OS-level settings are set via `NSTextInsertionPointBlinkPeriodOn` and `NSTextInsertionPointBlinkPeriodOff` and the caret in most (if not all) other apps honors this setting. However, Bitwarden does not.

**Comment by Hinton** [comment]
Hi @dmattera, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
