### ISSUE TITLE
Password fields 'redable' by textexpanders - SOLVED

### ISSUE THREAD

**Issue by marketingspectrumNL** [bitwarden/clients#2648]
### Steps To Reproduce

1. Using Beeftext and TextExpander + Bitwarden via Chrome browser extension. (might work with others as well)
2. Add a new item
3. In the password field add the combo (like ;name if that is what you have)
4. It will now be filled in, even if the password field is set to hide input.

5. Log out - try the same with the master password. It actually works there as well....

I would conclude this means the textexpander (*or keylogger) can read my password. 

### Expected Result

I would expect this to be a secure input field. Unreadable for loggers / text snippet tools.

### Actual Result

Since it catches my keystrokes to add the snippet, it can read my password as well.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

101.0.4951.54

### Build Version

1.58.0

**Comment by sectokia** [comment]
I’m not sure this is even possible, nor even a boarded issue. 

You are running what are effectively keyloggers who monitor key strokes and add keystrokes as if they were the keyboard.

Bitwarden can’t do anything about this. You should disable key loggers when using bitwarden.

**Comment by marketingspectrumNL** [comment]
> I’m not sure this is even possible, nor even a bitwarden issue. 
> 
> 
> 
> You are running what are effectively keyloggers who monitor key strokes and add keystrokes as if they were the keyboard.
> 
> 
> 
> Bitwarden can’t do anything about this. You should disable key loggers when using bitwarden.
> 
> 
> 
> 

Reading about secure input fields it states textexpander can't read them. Yet on bitwarden it can. 

Does that mean / are you saying bitwarden is not using secure input fields?


https://textexpander.com/secure-input

**Comment by marketingspectrumNL** [comment]
So, after further analysis all is good. 
The textexpander app doesn't work when the password is 'invisible'. As soon as you make it visible it is no longer a secure input field - and therefor it works.

**Comment by djsmith85** [comment]
Closing this, as marked as solved.
