### ISSUE TITLE
Clipboard history Windows

### ISSUE THREAD

**Issue by chiwou** [bitwarden/clients#2672]
still not solved, the clipboard history is a feature used in our organization, and we can't rollout Bitwarden until this issue is fixed.

Sure we could disable the clipboard history via GPO but we can't remove a well like feature for another app, people will be displeased with the new application (in this case Bitwarden)

_Originally posted by @chiwou in https://github.com/bitwarden/clients/issues/939#issuecomment-1122689926_

**Comment by Hinton** [comment]
Duplicate of either https://github.com/bitwarden/clients/issues/1047 https://github.com/bitwarden/clients/issues/2621
