### ISSUE TITLE
Any Popup Browser Window Doesn't Have Access to the GUI w/o Keyboard Shortcut

### ISSUE THREAD

**Issue by jfftck** [bitwarden/clients#2690]
### Steps To Reproduce

1. Go to a website with a pay with PayPal button
2. Click on the PayPal button
3. Notice that the window that opens has a reduced window chrome

### Expected Result

There would be an icon to fill in the password

### Actual Result

There is no way to click on the Bitwarden icon due to the reduced chrome

### Operating System

Windows, macOS, Linux

### Web Browser

Firefox

### Build Version

1.58.0

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. When Firefox presents the smaller browser window (for example, when using certain PayPal login flows), browser extensions are not visible. However, you may still autofill login credential that are saved in your Bitwarden Vault by using keyboard shortcuts (as you've noted), or by right-clicking in the page and choosing _Bitwarden > Autofill_. 

If I have misunderstood the issue, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

This issue will now be closed. 

Thanks!
