### ISSUE TITLE
Can't search for `ssh`

### ISSUE THREAD

**Issue by thetillhoff** [bitwarden/clients#2691]
### Steps To Reproduce

1. Have any login named something with `ssh` or `SSH` in its name
2. Try to search for it

### Expected Result

The entry should be shown (worked before last update)

### Actual Result

No search result update is shown

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by CarleyDiaz-Bitwarden** [comment]
I was unable to recreate this on my desktop environment.

**Comment by CarleyDiaz-Bitwarden** [comment]
Hello @thetillhoff I am attempting to recreate this bug, but require more information from you, can you please share your email so I can communicate with you through there?

**Comment by CarleyDiaz-Bitwarden** [comment]
@thetillhoff can you confirm that you are still experiencing this issue? I have tried to recreate in Desktop and Browser, with SSH ssh 'SSH' 'ssh' in the name and they all were pulled back properly.

**Comment by thetillhoff** [comment]
Strange... since my last restart I'm unable to reproduce the issue. I'll go ahead and close the issue.
Thanks for getting back on this!!!
