### ISSUE TITLE
"localhost is not a valid domain" error

### ISSUE THREAD

**Issue by kotsius** [bitwarden/clients#2692]
### Steps To Reproduce

1. Settings → Excluded Domains → add "http://localhost" → Save
2. Settings → Excluded Domains → add "https://www.google.com" → Save

### Expected Result

No errors.

### Actual Result

No error after the first step, "localhost is not a valid domain" error after the second step.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 20H2

### Web Browser

Vivaldi

### Browser Version

5.2.2623.46 (Stable channel) (64-bit)

### Build Version

1.58.0

**Comment by aj-bw** [comment]
Hi @kotsius,

Thanks for bringing this to our attention! After doing some testing, it seems you can successfully add "http://localhost" without issue. However, if that URI is already in your Excluded Domains settings and you go to add a new URI it removes the "http://" and determines it is a non-compliant entry.  A workaround in the meantime is when you are in the menu adding additional URIs, manually re-enter "http://" to the beginning of the localhost item(s) and it will let you save it.
