### ISSUE TITLE
Mac client (1.33.0) menu "File a bug report" still redirects to old repo

### ISSUE THREAD

**Issue by mackonsti** [bitwarden/clients#2717]
### Steps To Reproduce

0. Download latest client from MacAppStore
1. Go to menu HELP
2. Click on "File a bug report"
3. Browser is opened
4. Takes user to https://github.com/bitwarden/desktop/issues instead of the **older** repo.

### Expected Result

Just a simple change of URL reference, should take the user to the new Issues page:
https://github.com/bitwarden/clients/issues

### Actual Result

Takes user to the older (read-only) Issues page:
https://github.com/bitwarden/desktop/issues

### Operating System

macOS

### Operating System Version

Catalina 10.15.7

### Installation method

Mac App Store

### Build Version

1.33.0 (2645)

**Comment by djsmith85** [comment]
@mackonsti Thank you for your report. This issue has been addressed with https://github.com/bitwarden/clients/pull/2655 and will be fixed with the next release.

**Comment by mackonsti** [comment]
Sorry for the duplicate @djsmith85 !

**Comment by djsmith85** [comment]
@mackonsti No worries 👍
