### ISSUE TITLE
bw {list, get} outputs "mac required." before expected result

### ISSUE THREAD

**Issue by a7g4** [bitwarden/clients#2724]
## Describe the Bug

bw cli prints `mac required.` to stderr before printing the expected result to stdout

```
~$ bw list items --search test.com
mac required.
mac required.
mac required.
mac required.
[{"object":"item","id":"699bd239-0601-4711-b32b-ae9801347cb8","organizationId":null,"folderId":null,"type":1,"reprompt":0,"name":"Test","notes":null,"favorite":false,"login":{"uris":[{"match":null,"uri":"test.com"}],"username":"test_un","password":"test_pw","totp":null,"passwordRevisionDate":null},"collectionIds":[],"revisionDate":"2022-05-17T18:43:10.040Z","deletedDate":null}]
~$ bw get password test.com
mac required.
mac required.
mac required.
mac required.
test_pw
~$ bw get item 699bd239-0601-4711-b32b-ae9801347cb8
{"object":"item","id":"699bd239-0601-4711-b32b-ae9801347cb8","organizationId":null,"folderId":null,"type":1,"reprompt":0,"name":"Test","notes":null,"favorite":false,"login":{"uris":[{"match":null,"uri":"test.com"}],"username":"test_un","password":"test_pw","totp":null,"passwordRevisionDate":null},"collectionIds":[],"revisionDate":"2022-05-17T18:43:10.040Z","deletedDate":null}
```

## Steps To Reproduce

Based on https://github.com/bitwarden/cli/issues/246 it is probably to do with the state of my vault which I'm not sure how to reproduce, but any `bw get` or `bw list` command will do this.

## Expected Result

```
~$ bw get password test.com
test_pw
```

## Actual Result

```
~$ bw get password test.com
mac required.
mac required.
mac required.
mac required.
test_pw
```

## Screenshots or Videos

![2022-05-17_13-03](https://user-images.githubusercontent.com/38473816/169102662-bbf8a23b-df86-4ac7-868b-b288f323a79c.png)

## Environment

- Operating system: Ubuntu 22.04 and Ubuntu 20.04 using bw installed as a snap
- Shell: bash
- Build Version (run `bw --version`): 1.22.1

**Comment by aj-bw** [comment]
Hi @a7g4,

Thanks for reaching out! So far I am having trouble recreating the issue, thanks for linking the previous issue there was helpful context there.

Do you have your session key stored?
Try the following commands and see if it resolves the mac required issue you're experiencing:

`bw unlock --raw`
this will print out your session key

`export BW_SESSION="your-session-key"`
