### ISSUE TITLE
`bw unlock --check` reports vault as locked although it is not

### ISSUE THREAD

**Issue by kbialek** [bitwarden/clients#2729]
## Describe the Bug

`bw unlock --check` reports incorrect vault status

## Steps To Reproduce

1. Unlock the vault
2. Set `BW_SESSION` environment variable
3. Run `bw unlock --check`

## Expected Result
Vault status is `unlocked`

## Actual Result
Vault is `locked`

## Screenshots or Videos

```
[2022-02-13 11:12:37]:~ 
>>> bw --version
1.21.0

[2022-02-13 11:12:42]:~ 
>>> bw unlock
? Master password: [hidden]
Your vault is now unlocked!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="******"
> $env:BW_SESSION="******"

You can also pass the session key to any command with the `--session` option. ex:
$ bw list items --session ******

[2022-02-13 11:12:50]:~ 
>>> export BW_SESSION="******"

[2022-02-13 11:13:02]:~ 
>>> bw unlock --check
Vault is locked.

[2022-02-13 11:13:12]:~ 
>>> bw sync
Syncing complete.

[2022-02-13 11:13:16]:~ 
>>> bw unlock --check --session ******
Vault is locked.

[2022-02-13 11:13:49]:~ 
>>> bw sync --session ******
Syncing complete.
```

## Environment

- Operating system: pop-os 21.10
- Shell: bash
- Build Version (run `bw --version`): 1.21.0

## Additional Context

bw cli installed with npm

**Comment by creatorKoo** [comment]
It seems to have been resolved in version 2022.09. 
Any maintainer check and close this issue, please?

**Comment by mattcen** [comment]
@creatorKoo The issue does not appear to be fixed:

Note that the first time I run `bw list items` it asks for my mast password (because the vault is locked), but the second time it does not ask for my password because the vault is unlocked, despite `bw unlock --check` still reporting it as locked:

```sh
mattcen@inga:tmp$ bw -v
2022.9.0
mattcen@inga:tmp$ bw list items >/dev/null </dev/null; echo
? Master password: [input is hidden]
mattcen@inga:tmp$ bw unlock --check
Vault is locked.
mattcen@inga:tmp$ export BW_SESSION=$(bw unlock --raw)
? Master password: [hidden]
mattcen@inga:tmp$ bw list items >/dev/null </dev/null; echo

mattcen@inga:tmp$ bw unlock --check
Vault is locked.
```

**Comment by creatorKoo** [comment]
In my case, I have different result..
That's weird

`
bitwarden-iterm-helper % bw -v
2022.9.0
bitwarden-iterm-helper % bw list items >/dev/null </dev/null; echo
? Master password: [input is hidden]
bitwarden-iterm-helper % bw unlock --check
Vault is locked.
bitwarden-iterm-helper % export BW_SESSION=$(bw unlock --raw)
? Master password: [hidden]
bitwarden-iterm-helper % bw list items >/dev/null </dev/null; echo

bitwarden-iterm-helper % bw unlock --check
Vault is unlocked!
`

**Comment by mattcen** [comment]
How very odd.

**Comment by creatorKoo** [comment]
Anyway Thanks for your test. I'll wait for another result.

**Comment by sgallagher** [comment]
I can confirm @mattcen 's experience.
I just did the following:
```
$ bw update
A new version is available: v1.22.1
- New --hostname option for the bw serve command to securely bind your API web server to a host
- Bug fixes

You can download this update at https://github.com/bitwarden/cli/releases/download/v1.22.1/bw-linux-1.22.1.zip

If you installed this CLI through NPM you should update using `npm install -g @bitwarden/cli`

$ sudo npm install -g @bitwarden/cli
changed 212 packages, and audited 213 packages in 9s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ bw --version
2022.9.0

$ bw unlock --check
Vault is locked.

$ export BW_SESSION=$(bw unlock --raw)
? Master password: [hidden]

$ bw unlock --check
Vault is locked.

**Comment by sgallagher** [comment]
A couple questions:

1. Is it possible that the NPM wasn't updated?
2. Why does `bw update` report that `1.22.1` is available, but `bw --version` shows `2022.9.0`?

**Comment by djsmith85** [comment]
> A couple questions:
> 
> 1. Is it possible that the NPM wasn't updated?
> 2. Why does `bw update` report that `1.22.1` is available, but `bw --version` shows `2022.9.0`?

There's a known issue with the cli's update command, still looking at the old repository(bitwarden/cli vs bitwarden/clients), which is being tracked with https://github.com/bitwarden/clients/issues/3062

**Comment by kbialek** [comment]
It does not work for me neither. The fix is ready and waiting in this PR https://github.com/bitwarden/clients/pull/3070 Just saying :slightly_smiling_face:

**Comment by mattcen** [comment]
For what it's worth, this now seems to be working for me on version 2022.11.0, so it's possible this is now fixed (or it's a sporadic bug and is magically working for me now for some other reason)?

**Comment by adestis-mb** [comment]
The problem also exists in version 2023.4.0

**Comment by Hooch180** [comment]
problem exist in 2023.9.1

**Comment by milkpirate** [comment]
Same problem here, 2023.9.1 (snap).

**Comment by jrpedrianes** [comment]
In 2023.10.0 version, it happens too.

**Comment by kpiris** [comment]
I just noticed this on 2023.10.0.

Although bw status or bw unlock --check report that the vault is locked, it is not (having set the correct BW_SESSION environtment variable):

`kiko@penguin:~$ bw unlock --check
Vault is locked.
kiko@penguin:~$ bw status | jq '.status'
"locked"
kiko@penguin:~$ bw unlock --check
Vault is locked.
kiko@penguin:~$ bw get item testnote | jq '.notes'
"this is a test note stored in my vault."`

The vault can be queried, but the wrong status reported by bw breaks scripting.

**Comment by hamelg** [comment]
still happens with  2023.12.0 :(

**Comment by milkpirate** [comment]
still happens with 2023.12.1 :(

**Comment by kevinschweikert** [comment]
I've worked around it with `bw logout` and `bw login`. That seems to reset something so the status is correctly displayed again

**Comment by milkpirate** [comment]
@kevinschweikert could you describe you workflow a little more?

**Comment by kevinschweikert** [comment]
@milkpirate I had the same issues that `bw status` showed incorrectly "locked" although my `BW_SESSION` variable was set and all other commands were working. I needed to work with an Ansible lookup plugin which depends on the output of `bw status`. Logging out of the vault with `bw logout` and the immediately logging in with `bw login` fixed the issue (probably just temporarily)

**Comment by sellmerfud** [comment]
I can confirm the behavior reported by @kevinschweikert 
Using 2023.10.0

After I run
```
bw login
BW_SESSION="$(bw unlock --raw)"
```

Both `bw status` and `bw unlock --check` will correctly report that the vault is unlocked.

But if I subsquently run
```
bw lock
BW_SESSION="$(bw unlock --raw)"
```

Then both `bw status` and `bw unlock --check` now incorrectly report that the vault is locked.

Logging out and then logging in will fix the behavior until the vault is locked again.

**Comment by milkpirate** [comment]
still happens with 2024.1.0 :(

Would even open a PR if I would know how to fix it...

**Comment by sellmerfud** [comment]
I just installed 2024.1.0 and it now works correctly for me.
I installed the prebuilt binary for MacOS.

Be sure you set and export BW_SESSION after unlocking the vault.

**Comment by milkpirate** [comment]
Nope, still not working:

```bash
$ export BW_SESSION="$(bw unlock --raw)"
? Master password: [hidden]
$ bw unlock --check 
Vault is locked.
```
(snap, ubuntu)

**Comment by muffl0n** [comment]
Can confirm, works on macOS Sonoma
```
> % export BW_SESSION="$(bw unlock --raw)"
? Master password: [hidden]

-> % bw unlock --check
Vault is unlocked!

-> % bw --version
2024.2.0
```

**Comment by KucharczykL** [comment]
Tested on Linux with https://github.com/bitwarden/clients/releases/tag/cli-v2024.2.0 and I can also confirm it works.

**Comment by kbialek** [comment]
Yes, version 2024.2.0 works as expected.

**Comment by milkpirate** [comment]
Ok, the prebuild binary works as @Kucharczyk. pointed out. For the snap build the problem still persists. Now I realize it might be a Snap problem, since Snap often has permission problems (accessing the hosts file system). This might be the reason for this. Anyway, will use the prebuilt (github) binary.

**Comment by kbialek** [comment]
> For the snap build the problem still persists

Could be. I'm installing bw over npm.

**Comment by hal1961** [comment]
I'm getting the same error message "Master password: [input is hidden]", sometimes followed by one more message "mac failed"bw, with bw version 2024.7.2, extracted from the zip downloaded from github and saved in /usr/local/sbin/.

The script to reproduce the error is:
#! /bin/bash

# $BW_PASSWORD is set apart

# example: ITEM_NAME="keepass keys";
# example: ATTACHMENT_NAME="/home/hal1961/logins/keys.kdbx";
ITEM_NAME=$1;
ATTACHMENT_NAME=$2;
ITEM_NAME="keepass pandora";
ATTACHMENT_NAME="/home/hal1961/logins/pandora.kdbx";

bw login --apikey;

# Check if login was successful
if [ $? -eq 0 ]; then
	# Unlock Bitwarden vault and get session key in one step
	echo "Getting SESSION_KEY";
	SESSION_KEY=$(bw unlock $BW_PASSWORD --raw);
	
	# Check if session key retrieval was successful
	if [ -n "$SESSION_KEY" ]; then
		echo "Syncing vault";
		bw sync --session $SESSION_KEY;
		
		# Check if sync was successful
		if [ $? -eq 0 ]; then
			
			# Retrieve the ITEM_ID
			echo Looking for item id of "$ITEM_NAME";
			ITEM_ID=;
			ITEM_ID=$(bw --session $SESSION_KEY list items --search "$ITEM_NAME" \
			  | jq --arg ITEM_NAME "$ITEM_NAME" -r '.[] | select(.name == $ITEM_NAME)' \
			  | jq ".id" \
			  | tr -d '"');
			  
			if [ -z "$ITEM_ID" ]; then
				echo "Variable ITEM_ID is empty";
				bw logout;
				exit -1;
			else
				# Upload the attachment
				echo "Uploading $ATTACHMENT_NAME";
				bw create attachment --session "$SESSION_KEY" --file "$ATTACHMENT_NAME" --itemid "$ITEM_ID";
				# echo "Return value: $?";
				if [ -n "$?" ]; then
					echo "Upload successful";
					bw logout;
					exit 0;
				else
					echo "Upload failed";
					bw logout;
					exit -1;
				fi;
			fi;
		  else
			echo "Sync failed!";
			bw logout;
			exit -1;
		  fi;
	else
		echo "Failure getting SESSION_KEY";
		bw logout;
		exit -1;
	fi; # SESSION_KEY"
else
	echo "Login failed!";
	exit -1;
fi; #login

Randomly I get the error either getting the item ID or uploading the attachment.
Is this a bug of bw or have I to fix anything in my test script?

**Comment by dafrauen** [comment]
Hi, I'm on version 2024.7.2 and just ran into this problem.

Nothing worked, I ended up deleting data.json :

```
rm ~/.config/Bitwarden\ CLI/data.json
bw login
```
"Could not find data file, "~/.config/Bitwarden CLI/data.json"; creating it instead."

Then it worked fine, until the next lock I guess.

**Comment by hal1961** [comment]
Sound interesting! On my side, few days ago I tried again my script, renowing the session key for each upload and everything went fine

**Comment by lukens** [comment]
Though this is closed as complete, it seems the vault still reports as locked when using:

```
bw unlock --check --session ******
```

With a valid session.

I'm trying to use this as a workaround for the issue that sessions keep breaking, however, as this can't even test a valid session, it's not of much use.

**Comment by AlecBlance** [comment]
> Hi, I'm on version 2024.7.2 and just ran into this problem.
> 
> Nothing worked, I ended up deleting data.json :
> 
> ```
> rm ~/.config/Bitwarden\ CLI/data.json
> 
> bw login --sso
> 
> export BW_SESSION=$(bw unlock --raw)
> ```
> 
> "Could not find data file, "~/.config/Bitwarden CLI/data.json"; creating it instead."
> 
> Then it worked fine, until the next lock I guess.

This is my workaround as well. I'm still experiencing this in `2025.10.0` (npm)
