### ISSUE TITLE
Human friendly output for all subcommands with a machine friendly option

### ISSUE THREAD

**Issue by mhalano** [bitwarden/clients#2743]
Some subcommands have a friendly output, like "bw get", but others are just machine friendly, like "bw list". The idea is create a readable output for all subcommands with an option, like --json, to generate a machine friendly output. I think humans and machines will be happy.

**Comment by xundeenergie** [comment]
pass use "tree" command from linux-shell to show the tree where passwords are stored in... only the "name".
