### ISSUE TITLE
"Pop out to a new window" - keeps getting wider with each "Pop out"

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#2747]
### Steps To Reproduce

1. Left click plugin
2. Click on 'Pop out to a new window' top left of dialog
3. Repeat step 2 on child dialog
4. Observe dialog box got wider
5. Repeat step 2 on the subsequent child dialog
6. Observe dialog box got wider
7. Repeat ad infinitum - Observe new child dialog box again got wider...

Clicking on the 'Pop out to a new window' of the previous child will yield the same size window again, ie. larger than the one you came from, but no larger than it's sibling.

### Expected Result

Same size dialog as parent...

### Actual Result

Subsequent child dialog box is progressively wider than it's parent...

### Operating System

Linux

### Operating System Version

```
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal
```

### Web Browser

Firefox

### Browser Version

100.0.2 (64-bit)

### Build Version

1.58.0

**Comment by djsmith85** [comment]
@DavidPesticcio Thank you for the report. This is indeed a weird behaviour. I haven't checked if I can reproduce it, but it should be solved with https://github.com/bitwarden/clients/pull/2705. The popout button should not be present on an already popped out window.
