### ISSUE TITLE
Biometrics unlock from browser plugin can disable desktop biometrics when using multiple accounts

### ISSUE THREAD

**Issue by bobvandevijver** [bitwarden/clients#2752]
### Steps To Reproduce

1. Use multiple accounts (I have three accounts over three different instances), all with biometrics unlock. For the browser plugin I use different profiles to be able to use multiple accounts easily.
2. Ensure all accounts are locked in the desktop client
3. Try to unlock an account with biometrics from the browser plugin, and make sure it is not the one being displayed on the lock screen of the desktop application
4. Use you biometrics
5. See no error message, but the browser plugin is not unlocked
6. Switch the desktop client to the account you tried
7. See that the biometrics unlock option has disappeared

### Expected Result

I expect that it does not matter which account is selected in the client when all are locked, but it does. 

### Actual Result

The unlock fails and removed the biometrics option from the account you tried to unlock.

### Additional Context

This only happens when all used accounts in the desktop client are locked. When one account has been unlocked (it doesn't matter which one), everything works great. Also, when the account you're trying to unlock is visible on the lock screen of the desktop app, it works fine for that particular account.

When the biometrics option has disappeared from the account, it comes back after unlocking with the normal password.

### Operating System

Windows

### Operating System Version

11, 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0 (desktop) / 1.58.0 (edge plugin)

**Comment by pro4tlzz** [comment]
I have the same issue.

MacOS 12.4 (21F79)
Desktop: Version 2022.5.1
Extension: Version: 2022.5.0

Also using 3 accounts.

You can temp fix the issue by going into the desktop app and disabling the biometric and enabling it again.

It will work for the account you are currently active on and nothing else

**Comment by pro4tlzz** [comment]
Still a problem with the latest macos client 

dekstop app:
Version 2022.5.1
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture arm64

extension:
Version: 2022.6.1

**Comment by pro4tlzz** [comment]
This is a very annoying problem, is no one else facing it?

**Comment by bobvandevijver** [comment]
Well, I created the issue, so I'm facing it ;) But I try to switch the desktop client to the correct account before unlocking as workaround, which helps a lot already.

**Comment by dbosompem** [comment]
Hi @bobvandevijver and @pro4tlzz , apologies for the inconveniences. The team will take time to reproduce this, and look through this whiles we keep you in the loop. For the meantime, @pro4tlzz  please try @bobvandevijver's temporal workaround, as the team take a look at this.

**Comment by benjiwolff** [comment]
This issue still exists. The workaround works but if I would rather type my master password than going through this process every time I switch accounts.

**Comment by bobvandevijver** [comment]
It seems to be resolved with 2024.4.1 (maybe has something to do with #8046?), but I will keep this open for a couple of days to verify.

**Comment by bobvandevijver** [comment]
This seems to be fully resolved :+1:
