### ISSUE TITLE
Firefox browser extension drops keystrokes in the search bar

### ISSUE THREAD

**Issue by Gooberpatrol66** [bitwarden/clients#2756]
### Steps To Reproduce

1. open extension
2. type the name of a vault item moderately fast in the search bar

### Expected Result

the search bar captures all keystrokes

### Actual Result

it drops keystrokes as search results are loaded

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

nightly

### Build Version

100.0

**Comment by djsmith85** [comment]
@Gooberpatrol66 Thank you for your report. This issue is being tracked under https://github.com/bitwarden/clients/issues/2371. Closing this as duplicate.
