### ISSUE TITLE
Notification counter text contrast in macOS dark mode

### ISSUE THREAD

**Issue by wdninja** [bitwarden/clients#2760]
### Steps To Reproduce

- Logged into extension
- Navigate to site where you have existing logins to show counter on extension icon
- Enable macOS Dark Mode appearance theme

### Expected Result

Counter has contrasting white text while macOS is in Light Mode, the same white contrasting text is expected in Dark Mode as well. 

### Actual Result

In macOS Dark Mode, the text switches to a dark color and has very low contrast to the background color of the notification counter.

### Screenshots or Videos

<img width="39" alt="Screen Shot 2022-05-31 at 9 07 15 AM" src="https://user-images.githubusercontent.com/11201605/171180524-bda07869-8ad3-41ed-a4e8-690b070ce9bc.png">

<img width="42" alt="Screen Shot 2022-05-31 at 8 53 59 AM" src="https://user-images.githubusercontent.com/11201605/171178746-e1936e63-39e7-48dc-ab79-6cd8e26159aa.png">

### Operating System

macOS

### Operating System Version

12.3.1

### Web Browser

Chrome

### Browser Version

102.0.5005.61

### Build Version

1.58.0

**Comment by djsmith85** [comment]
Hi @wdninja and thank you for the report.

As mentioned [here](https://github.com/bitwarden/clients/issues/2758#issuecomment-1141854240) this is an upstream issue with Chrome.

Closing this now.
