### ISSUE TITLE
`bw get password` does not find item by second URL

### ISSUE THREAD

**Issue by webmozart** [bitwarden/clients#2762]
### Steps To Reproduce

1. Add a password entry with two URLs `myscheme://foo` and `myscheme://bar`
2. Run `bw get password myscheme://foo --raw` and the password is found
3. Run `bw get password myscheme://bar --raw` and the password is **not** found

### Expected Result

The password should be found when running `bw get password myscheme://bar --raw`.

### Actual Result

The password is not found. The result is:

```
Not found.
```

### Operating System

macOS

### Operating System Version

12.4

### Shell

Zsh

### Build Version

1.22.1

**Comment by dbosompem** [comment]
Hello @webmozart , thank you for opening this issue. We will prioritise this accordingly and get it fixed in due time whiles we keep you in the loop. This is well appreciated, many thanks!
