### ISSUE TITLE
Chrome extension causes text spacing issues in Microsoft Teams web app

### ISSUE THREAD

**Issue by Evan-Walter** [bitwarden/clients#2770]
### Steps To Reproduce

1. Be sure you are logged out of the Microsoft account in other browser profiles.
2. Log in to Microsoft Teams in a browser profile which has the Bitwarden extension installed.
3. Log out of Microsoft.
4. Quit the browser.
5. Log in to Microsoft Teams again in the browser profile which has the Bitwarden extension installed. The issue should appear.
6. If the issue does not appear (i.e., if text in Microsoft Teams still appears normal), repeat steps 3 and 4. And then log in to Microsoft Teams in browser profile which does not have the Bitwarden extension installed.

### Expected Result

Microsoft Teams should look normal.

### Actual Result

The text in Microsoft Teams has weird spacing. 

### Screenshots or Videos

<img width="1512" alt="screenshot1" src="https://user-images.githubusercontent.com/57516308/171487662-dcc5e5c7-f1df-4664-ad7f-a02be9c1210a.png">

<img width="1088" alt="screenshot2" src="https://user-images.githubusercontent.com/57516308/171487677-4f08f7e5-5c81-4442-8152-9469b7327910.png">

### Additional Context

I've been using Microsoft Teams, the Bitwarden Chrome extension, and other Chrome extensions all together for more than 4 months since the time of this report submission. About two weeks ago, I noticed weird spacing in Microsoft Teams. I uninstalled and reinstalled each Chrome extension one-by-one while logging in and logging out of Microsoft in my browser. The issue appeared after I reinstalled the Bitwarden extension. My workaround is to only log in to Microsoft in a browser profile which does not have the Bitwarden extension installed. I use the Bitwarden extension in all my other browser profiles.

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Brave

### Browser Version

Version 1.39.111

### Build Version

Chromium: 102.0.5005.61 (Official Build) (arm64)

**Comment by ifernandezdiaz** [comment]
Hi, @Evan-Walter! I tried to reproduce this issue with no luck. 
Could you please tell me which extension version you are using?  

Thanks in advance!

**Comment by Evan-Walter** [comment]
> Hi, @Evan-Walter! I tried to reproduce this issue with no luck. Could you please tell me which extension version you are using?
> 
> Thanks in advance!

Hi @ifernandezdiaz, thank you for your reply. I took steps to repeat this issue several times at one point in time. However, this issue no longer appears. I later noticed that this issue appeared in other scenarios, and I believe my assertion may have been incorrect. I will close this issue.
