### ISSUE TITLE
When importing data or purging the vault, the Web Vault returns to the 'My Vault' view, which is not reflecting the recent changes.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#2780]
### Steps To Reproduce

1. Log into your Bitwarden account via the Web Vault (https://vault.bitwarden.com/#/).
2. Import a Bitwarden .json file into your vault.
3. You'd be automatically directed to the 'My Vault' view after you click on 'Import Data'.
4. Check what you see in the 'My Vault' view.

### Expected Result

To see the newly imported data.

### Actual Result

The 'My Vault' displays the same data as before, as if nothing was imported.

### Screenshots or Videos

N/A.

### Additional Context

Refreshing the My Vault view by pressing F5 and unlocking or going to the Settings menu and back helps, and this also occurs when using the 'Purge Vault' function.

### Operating System

Windows

### Operating System Version

11 Pro 21H2.

### Web Browser

Microsoft Edge

### Browser Version

101.0.1210.47.

### Build Version

2.28.1.

**Comment by djsmith85** [comment]
Closing this, as it was addressed with https://github.com/bitwarden/clients/pull/4380 which was included in `2023.2`
