### ISSUE TITLE
When downloading PDF from Send, it opens up a new tab with the pdf open at a small height 

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#2782]
### Steps To Reproduce

1. Create a File Send and attach a PDF
2. Open the Send URL in Chrome
3. Download the file

### Expected Result

File downloaded or open up properly

### Actual Result

 it opens up a new tab with the pdf open at a small height 

### Screenshots or Videos

![2022-05-03 15_37_21-Window](https://user-images.githubusercontent.com/75601583/166611933-c95bcfb3-98df-4c4d-a9c3-00f57057750f.png)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2.28.1

**Comment by djsmith85** [comment]
Closing this as it was addressed with https://github.com/bitwarden/clients/pull/2908 and the fix will be included in the next release (2022.8).
