### ISSUE TITLE
Missing `lang` attribute on body element

### ISSUE THREAD

**Issue by Hinton** [bitwarden/clients#2783]
### Steps To Reproduce

Visit vault.bitwarden.com

### Expected Result

The HTML element should have the correct `lang` attribute set. i.e. `lang="en"`.

### Actual Result

No lang element is set.

### Additional Context

Related to https://github.com/bitwarden/web/pull/1398

Implementation notes:

We should expand the `I18nService` to expose a `lang$` observable which a decorator can subscribe to in order to assign the correct lang to the page. We will need to ensure the language in the decorator matches the ISO 639-1 standard.

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2.28.0

**Comment by djsmith85** [comment]
Closing this now, as work was completed with: https://github.com/bitwarden/clients/pull/2837
