### ISSUE TITLE
Favicons doesn't load for certain website

### ISSUE THREAD

**Issue by K-techie** [bitwarden/clients#2786]
### Steps To Reproduce

1. Enter the URI as https://login.linode.com/login in a login item 

### Expected Result

Favicon for linode.com should appear

### Actual Result

No favicon appears 

### Additional Context

The URI seems valid to me as , it was able to fetch favicon on keepassxc

### Operating System

Android, Windows

### Operating System Version

Problem on all devices including web vault

### Web Browser

Chrome, Brave

### Browser Version

Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (64-bit)

### Build Version

Windows 10 home v21H1 OS build 19043.1526

**Comment by shane-melton** [comment]
Hi @K-techie, it appears linode.com is using a strict Cloudflare configuration that prevents/forbids Bitwarden's cloud Icon service from retrieving Linode's favicon. Unfortunately, this is out of Bitwarden's control and can't be fixed on the server where Icons are currently handled.

For additional confirmation, you can also see that DuckDuckGo has a similar icon service at https://icons.duckduckgo.com and it also cannot retrieve/display Linode's favicon.

[https://icons.duckduckgo.com/ip3/login.linode.com.ico](https://icons.duckduckgo.com/ip3/linode.com.ico) ❌ 
[https://icons.duckduckgo.com/ip3/linode.com.ico](https://icons.duckduckgo.com/ip3/linode.com.ico) ❌ 

Some working examples:
[https://icons.duckduckgo.com/ip3/vault.bitwarden.com.ico](https://icons.duckduckgo.com/ip3/vault.bitwarden.com.ico) ✅
[https://icons.duckduckgo.com/ip3/github.com.ico](https://icons.duckduckgo.com/ip3/github.com.ico) ✅
