### ISSUE TITLE
"manager" role can't move entry to collection within organization.

### ISSUE THREAD

**Issue by IgnazNepumuk** [bitwarden/clients#2796]
### Steps To Reproduce

1. create an organization, add a collection and within add an entry "1st entry"
2. invite a second user to this organization, give it "manager role" and "This user can access and modify all items."
3. login with invited user
4. on right side click on the organization  (to filter entries for this organization)
5. click on the gear next to entry "1st entry" and within on "collection"
6. a popup appears which says "Collections There are no collections to list. "

### Expected Result

at 6. there should be a list of all collections within the organization

### Actual Result

no collection is shown.

the same works if  no organization is clicked before hand. So if the user is at his "vault", the entry can be moved to another collection.

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

96.0.3

### Build Version

2.25.1

**Comment by Greenderella** [comment]
Hello,

The manager role referenced in this issue no longer exists. Closing this issue as it's no longer relevant.

We use GitHub issues as a place to track bugs and other development related issues. For support requests, please contact us using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

Thanks!
