### ISSUE TITLE
Verify Email Box does not update after verify

### ISSUE THREAD

**Issue by Dentrax** [bitwarden/clients#2800]
### Steps To Reproduce

1. Register
2. Open bitwarden homepage
3. Verify your email
4. See the "Verify Email" warning box

### Expected Result

Warning box should not show.

### Actual Result

Warning box is shown.

### Screenshots or Videos

![Screen Shot 2022-01-14 at 22 02 43](https://user-images.githubusercontent.com/16493751/149633580-ef2d8304-2f22-48d6-9649-ad7509b152e6.png)

### Additional Context

Refreshing the page does not fix the glitch. I had to clear local storage of the website.

### Operating System

macOS

### Operating System Version

12.1

### Web Browser

Firefox

### Browser Version

96.0.1

### Build Version

2.25.1

**Comment by schang1146** [comment]
Gonna try implementing the improvement mentioned by @Hinton where if a user tries to send another verification code after already verified, it'll update the verification status and hide the banner.

**Comment by Hinton** [comment]
Showing a notification toast while also hiding the banner perhaps?

**Comment by schang1146** [comment]
Got a PR made for the issue.
