### ISSUE TITLE
The "Import Data", "Premium Membership", "Subscription" and "Edit User" pages contain strings that cannot be translated

### ISSUE THREAD

**Issue by olavinto** [bitwarden/clients#2806]
## Describe the Bug

It seems that the "Choose File" button text and its "No file chosen" description can't be translated at Crowdin (at least I could not find them there). Both Finnish and English screenshots are attached.

These are located under "Tools" > "Import Data" > "2. Select the import file".

The membership and subscription status message is also not translatable it seems. 

Located under "Settings" > "Premium Membership" and Organization "Settings" > "Subscription".

One addition to this list: "Organization Settings > Manage > People" page "Edit User" screen. The headers for custom permissions do not seem to be available for translation at Crowdin.

## Screenshots

**Tools > Import Data:**
![bitwarden_import_en](https://user-images.githubusercontent.com/23163218/124379142-ebec6580-dcbd-11eb-8ea8-bdbb6028cd16.png)
![bitwarden_import_fi](https://user-images.githubusercontent.com/23163218/124379143-ec84fc00-dcbd-11eb-9bab-f7d7c413395a.png)

**Settings > Premium Membership:**
![english](https://user-images.githubusercontent.com/23163218/128597023-636c87ba-b79d-4380-9450-f1d0b3c2925a.png)
![finnish](https://user-images.githubusercontent.com/23163218/128597025-536dea7b-9919-40d3-b528-81ee6155a0d6.png)

**Organization Settings > Subscription:**
![english_org](https://user-images.githubusercontent.com/23163218/128597030-3a06be29-45fb-4906-953c-dd8c2a0a9cdd.png)

**Organization Settings > Manage > People > Edit User:**
![en](https://user-images.githubusercontent.com/23163218/141368495-07583311-154d-466c-92fb-20bd294528a0.png)
![fi](https://user-images.githubusercontent.com/23163218/141368410-d9a668ac-b6e7-4ab0-8368-3d64867db787.png)

## Environment

- Build Version: [2.21.1]

**Comment by adamkaplan0** [comment]
Hello, newbie here and very interested in tackling this issue if allowed!

**Comment by schang1146** [comment]
Is anyone actively working on this? Planning on working on it if not.

**Comment by olavinto** [comment]
> Is anyone actively working on this? Planning on working on it if not.
> 
> Edit: I'm seeing the issue still there for the above-mentioned locations.

Not me, I'm just the reporter. My coding experience is limited to HTML and CSS and even that was mostly years ago. Hopefully someone can fix these!

**Comment by schang1146** [comment]
Cool, I hope it's good with others. I am making progress on this, and I'll keep the thread updated :)

**Comment by schang1146** [comment]
A bit blocked on using Crowdin/getting translations and the "Status" options.

## Crowdin stuff:

I'm not too familiar with Crowdin and the workflow to get translations in for it. I've updated the English messages.json (src/locales/en) and the Finnish messages.json (src/locales/fi) to test with.

I did find the [Bitwarden - Web](https://crowdin.com/project/bitwarden-web) project in Crowdin. Do we just update the messages.json for English and the others get auto-updated when translations are submitted?

## Status stuff:

Also, looks like the way translations are handled, we'd need an entry for all the different options Status can have:
- active
- canceled
- unpaid
- incomplete_expired
- trialing

Would we want to make an entry for each of those in the messages.json file?

I'm worried if a new status is ever created (or if I missed any) and it's not populated on the messages.json file, it'll just show up blank.

## Progress:

Tools > Import Data (English)
![image](https://user-images.githubusercontent.com/20074034/189549147-c4961bf5-fdce-44c5-aad9-0659688fdff7.png)
![image](https://user-images.githubusercontent.com/20074034/189549165-f6d25135-0989-4e9c-a8e0-42c54a20717b.png)

Tools > Import Data (Finnish)
![image](https://user-images.githubusercontent.com/20074034/189549268-46265679-e7c7-4645-8544-24db4e29c18e.png)
![image](https://user-images.githubusercontent.com/20074034/189549284-d353d0ec-0298-461d-9c3b-2a0350cca483.png)

Organization Settings > Manage > People > Edit User (English)
![image](https://user-images.githubusercontent.com/20074034/189549247-17824d01-6cc8-4790-af98-98ab6c0bdc20.png)

Organization Settings > Manage > People > Edit User (Finnish)
![image](https://user-images.githubusercontent.com/20074034/189549329-5f1d5f7a-f483-468d-b6d2-7e22d8bcc219.png)
