### ISSUE TITLE
Gravatar image reloads on change detection

### ISSUE THREAD

**Issue by JensSpanier** [bitwarden/clients#2807]
## Describe the Bug

When gravatar icon are enabled, the avatar gets reloaded every time something changes on the site (like typing in an input field)

## Steps To Reproduce

1. Activate gravatar
2. Reload vault so it gets applied
3. Open browser development tools (network)
4. Type something in any input field

## Expected Result

Gravatar image gets loaded once

## Actual Result

Gravatar image gets loaded everytime something changes on the site

## Screenshots or Videos

![image](https://user-images.githubusercontent.com/42373861/120383294-0204b000-c325-11eb-8345-ecc7b22beff8.png)

## Environment

- Operating system: Windows 10
- Browser: Chrome 91.0.4472.77
- Build Version (Bottom of the page): 2.20.3

**Comment by Hinton** [comment]
We no longer support gravatars, so I consider this issue resolved.
