### ISSUE TITLE
Email verfication invalid state

### ISSUE THREAD

**Issue by jblachly** [bitwarden/clients#2810]
## Describe the Bug

A break in the email verification flow leads to invalid application state.

## Steps To Reproduce

1. Register for new account
2. Login
3. Click "send verification email"
4. Open verification email, click link
5. (Web browser opens to vault login screen [even if logged in in another tab]; Green "email verified" status banner appears)
6. Do not log in; instead, close the tab (because of course you are logged in in an adjacent tab
7. Optionally refresh the adjacent, logged in tab, but this step probably does seem to affect state
8. Unverified email box still appears -- click "send verification email"
9. A red warning banner pops up indicating that the email verification has already been sent

The only way out of this invalid state, as far as I can tell, is to go back to the original email and re click the link, and successfully login.

## Expected Result

Email verification flows should always offer the option to re-send the email

## Actual Result

Clicking the "send verification email" warns the user that email was already sent (too bad)

## Screenshots or Videos

Didn't think to capture

## Environment

Firefox 84.0.1

**Comment by schang1146** [comment]
Just read through this thread, looks like PR #3552 might help out with this.

**Comment by djsmith85** [comment]
Closed as completed with #3552
