### ISSUE TITLE
No way to export org items with folders

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#2813]
I can export my personal vault, which will include the folders that I have put my personal vault items in.

I can export my organization, which will _not_ include the folders that I have put the organization items in, even though they're right there in the UI.

As far as I can tell there is no way to generate an export of items in my organization that include the folders I've personally assigned to them.

This is bad.

**Comment by djsmith85** [comment]
Possibly related feature request on the Bitwarden Community Forums: https://community.bitwarden.com/t/consolidated-export-vault/40164
