### ISSUE TITLE
'No Folder' shows all items

### ISSUE THREAD

**Issue by nichu42** [bitwarden/clients#2821]
### Steps To Reproduce

1. Click on 'No Folder' folder

### Expected Result

Showing items that have no folder associated.

### Actual Result

Showing all items, no matter if they are in a folder or not.

### Operating System

Windows

### Operating System Version

Windows 11 Version 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.0

**Comment by johegl** [comment]
Same here. Windows 10 Pro 21H2.

**Comment by Menschenkindlein** [comment]
Same on macOS 12.4 Monterey.

**Comment by KDaro** [comment]
> Same here. Windows 10 Pro 21H2.
I confirm.

**Comment by e2zippo** [comment]
Same here, works in extension and web vault, but the desktop app is borked.

**Comment by nichu42** [comment]
Update: Problem still exists with Version 2022.5.1

**Comment by e2zippo** [comment]
> Update: Problem still exists with Version 2022.5.1

Can confirm, not fixed in 2022.5.1

**Comment by HariTheCoder341** [comment]
Same Here,

Versione 2022.5.1
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

**Comment by zorg73** [comment]
Same in :
Version 2022.5.1
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

**Comment by DarkArc** [comment]
Same here using the Flathub Flatpak on Linux (2202.5.1).
