### ISSUE TITLE
passwordGenerationOptions being saved to sessionStorage, not localStorage, causes settings to be lost

### ISSUE THREAD

**Issue by joobus** [bitwarden/clients#2828]
Currently each time I log into the web interface, I have to go to tools to change the default `passwordGenerationOptions`.  This is because `passwordGenerationOptions` is only being saved in sessionStorage, which gets cleared by the browser when the tab is closed.

I manually copied the `passwordGenerationOptions` from sessionStorage, and pasted them in localStorage, and after logging in with a new tab, the options were restored correctly.

Save `passwordGenerationOptions` to localStorage so that the settings persist across logins.

**Comment by evelez7** [comment]
Maybe this has changed but my password generation options persist across logins. It is only saved though if you generate a password from the password generator in tools or if you generate a password in a new Item and save it. Do you mean for it to persist if you change any of the generation options?

**Comment by djsmith85** [comment]
Closing this now as this should have been addressed with https://github.com/bitwarden/clients/pull/3074 and released with 2022.6.2.

Please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
