### ISSUE TITLE
Bitwarden does not start on boot in Windows 10

### ISSUE THREAD

**Issue by dziban303** [bitwarden/clients#2835]
### Steps To Reproduce

Looking in the Task Manager->Startup tab, Bitwarden is listed as having the name "program" and the command line is set to `"C:\Program" files\Bitwarden\Bitwarden.exe`, with the misplaced quotes.

### Expected Result

Bitwarden should start on Windows boot.

### Actual Result

Nothing. It doesn't start.

### Screenshots or Videos

![](https://i.imgur.com/uO51lDB.png)

### Additional Context

The problem is in the registry at `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run`:

![image](https://user-images.githubusercontent.com/7931765/172071926-496c61f2-f6e6-491c-ac5d-38f74f45aa11.png)

Generally speaking, such a string should be enclosed in quotes:
 
![image](https://user-images.githubusercontent.com/7931765/172071967-b3d246c2-c6e4-4d6b-8af9-47bf2b48b325.png)

Except the binary is not located there at all, but at `C:\Users\<user>\AppData\Local\Programs\Bitwarden\Bitwarden.exe`, which is where it should point:

![image](https://user-images.githubusercontent.com/7931765/172072276-9bc62126-32ad-4856-9b8e-37a3157bd139.png)

This also fixes the appearance in Task Manager's Startup tab:
![image](https://user-images.githubusercontent.com/7931765/172072317-4f240690-4fd1-43d2-9ae7-03b47411d7a1.png)

### Operating System

Windows

### Operating System Version

Win10 21H2 19044.1741 x64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.0

**Comment by frombrosis** [comment]
I have this exact same issue and the above fix solved the problem. Could Bitwarden please fix this bug in a future release so Bitwarden starts when logging into Windows 10.
