### ISSUE TITLE
Problem with setting "boot to system tray icon"!

### ISSUE THREAD

**Issue by Studenthero** [bitwarden/clients#2871]
### Steps To Reproduce

Windows 10 desktop client, the program does not respond after checking "boot to system tray icon" in the settings, and the interface cannot be displayed by right-clicking the tray icon.

### Expected Result

fix bug。

### Actual Result

As long as "boot to system tray icon" is selected, it won't work properly...

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

V2022.5.1

**Comment by creyhani** [comment]
fixed in recent patch.
