### ISSUE TITLE
Organizational vault items disappear from the Collection filter when they are edited, and return only when the client is synced.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#2876]
### Steps To Reproduce

1. Set up an organization with 2 members; 1 Owner-type with 'This use can access and modify all items' and 1 Manager-type with 'This user can access only the selected Collections' and create a vault item in a collection they both can access.
2. Log into the Manager-type account via the desktop client, click on the organizational vault and then on the collection in the collection filter on the left, and confirm that you're able to see that vault item.
3. Log into the Owner-type account via the Web Vault and edit the vault item; For testing, I added a number to the end of the password and saved.
4. Return to the desktop client.

### Expected Result

To see the vault item in its collection via the collection filter, as before.

### Actual Result

The collection appears empty.

### Screenshots or Videos

I've posted a video internally.

### Additional Context

Even through the collection appears empty, the vault item is still present in the 'All Items' filter, and manually syncing the client also addresses this.

### Operating System

Windows

### Operating System Version

11 Pro 21H2.

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1.

**Comment by djsmith85** [comment]
This got fixed with https://github.com/bitwarden/server/pull/2057 and will be included in the upcoming release.

Closing this now.
