### ISSUE TITLE
Changes made in Firefox private windows slow to update

### ISSUE THREAD

**Issue by umbralOptimatum** [bitwarden/clients#2881]
### Steps To Reproduce

1. Add a new login or edit an existing login in a Firefox private window.
2. Check vault from a normal window.

### Expected Result

The new login or edits should be visible in the vault in the normal window.

### Actual Result

The new login or edits are not visible in the vault when opened normal windows until Firefox is restarted. They are immediately visible in the private window.

### Additional Context

The Firefox client works fine in the opposite direction; add a new login from a normal window and it's visible from private windows without issue.

### Operating System

macOS

### Operating System Version

10.14.6

### Web Browser

Firefox

### Browser Version

101.0.1

### Build Version

1.58.0

**Comment by creyhani** [comment]
Fixed deployed last update
