### ISSUE TITLE
API Keys not stored for email generation

### ISSUE THREAD

**Issue by Explosion-Scratch** [bitwarden/clients#2894]
### Steps To Reproduce

1. Go to generator
2. Select email
3. Select using an external forwarding email provider
4. Paste in an API key
5. Click regenerate
6. Close/reload bitwarden (extension or web vault)
7. API key gone

### Expected Result

The API key stays filled in so that it works better. This is especially necessary with services where you can only view the API key once.

### Actual Result

The API key is cleared

### Additional Context

I selected windows as the operating system but I'm actually using ChromeOS but there's no option

### Operating System

Windows

### Operating System Version

100

### Web Browser

Chrome

### Browser Version

100

### Build Version

2022.5.0

**Comment by vphan916** [comment]
Hi @Explosion-Scratch. Hope all is well!  Are you pasting the API key on one client (for example, you paste the API key on the browser ext) then signing in on another client (such as the web vault) and you don't see API keys filled on there?
