### ISSUE TITLE
Search keyword is now being cleared after viewing an item

### ISSUE THREAD

**Issue by isleshocky77** [bitwarden/clients#2905]
### Steps To Reproduce

1. Go to browser vault
2. Type search term "airline X"
3. Click on first entry for for "airline X - Person A"
4. View some detail
5. Click "Close"

### Expected Result

Search term should still be filled in until I hit clear so that I can look at "airline X - Person B"

### Actual Result

Search term is cleared, I now must re-type "airline X", then click "airline X - Person B"

### Additional Context

Up until a week or two ago, this bug never existed. It was extremely easy to type a search result and go from one item to the next.
I believe this may have been introduced in #2685 

### Operating System

Linux

### Web Browser

Chrome

### Browser Version

101.0.4951.64

### Build Version

2022.5.0

**Comment by page-down** [comment]
I was able to reproduce this issue in `2022.6.2`.
Thankfully it was fixed in `2022.8.0`, but not sure which PR.

@isleshocky77
I think you can close this issue now.

**Comment by dbosompem** [comment]
@isleshocky77  closing this issue now, feel free to reopen if you encounter same issue.
