### ISSUE TITLE
"No Folder" tab shows entire vault instead of just items without folder designation

### ISSUE THREAD

**Issue by saka1221** [bitwarden/clients#2917]
### Steps To Reproduce

Bug only occurs on desktop app.  Works fine on mobile app and website.

1. Click on "No Folder" tab under folders.
2. Mobile app and website only show items without folder designation, but desktop app shows all items

### Expected Result

Only items without folder designation are displayed.

### Actual Result

"No Folder" tab has the exact same functionality as the "All Items" tab

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by djsmith85** [comment]
Hi @saka1221 and thank you for your report. This has already been reported with https://github.com/bitwarden/clients/issues/2821 and a fix will be included in the next release.

Closing this as duplicate
