### ISSUE TITLE
bitwarden.com has no CSP

### ISSUE THREAD

**Issue by johngraybosch** [bitwarden/clients#2927]
### Steps To Reproduce

The bitwarden.com site does not have a content security policy set. This could allow for cross site scripting attack vectors. The main risk would be that the Login button could be rewritten to redirect to a phishing site.

Here is the report from Mozilla Observatory for the main site:

[https://observatory.mozilla.org/analyze/bitwarden.com](https://observatory.mozilla.org/analyze/bitwarden.com)

### Expected Result

The vault.bitwarden.com site has the expected level of security:

[https://observatory.mozilla.org/analyze/vault.bitwarden.com](https://observatory.mozilla.org/analyze/vault.bitwarden.com)

As does the main 1password.com site:

[https://observatory.mozilla.org/analyze/1password.com](https://observatory.mozilla.org/analyze/1password.com)

### Actual Result

Here is the report from Mozilla Observatory for the main site:

[https://observatory.mozilla.org/analyze/bitwarden.com](https://observatory.mozilla.org/analyze/bitwarden.com)

### Screenshots or Videos

I'm also worried about the 15 different trackers that are included on the main website. Without a CSP, they could in theory also become weak spots and attack vectors. Bitwarden's security is then only as good as Reddit's or Quora's.
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1764921/174342416-f4fbcbb6-eafa-444a-84ba-1b4d914645fe.png">
<img width="814" alt="image" src="https://user-images.githubusercontent.com/1764921/174342442-87917de2-0ffc-465f-bdaf-91c9574741aa.png">

### Operating System

macOS

### Operating System Version

Montery 12.4

### Web Browser

Safari

### Browser Version

15.5

### Build Version

Main Website

**Comment by dbosompem** [comment]
Hi @johngraybosch, thanks for creating this issue, that was a good discovery! We value security so much so we wouldn't take this discovery for granted. This issue would be looked into immediately, hopefully we can get things sorted soon. Very appreciated!

**Comment by atjbramley** [comment]
@johngraybosch, 

Thanks once more for your original report.  

Since this, the web team has implemented a CSP, as well as an ongoing monitoring plan.  The CSP in effect is already greatly improved from your original report, and please rest assured that the team will continue to iterate on this as necessary!

This issue will now be closed.
