### ISSUE TITLE
Application window momentarily displays on OS startup / login when 'Start To Tray Icon' is enabled

### ISSUE THREAD

**Issue by monkeyhybrid** [bitwarden/clients#2929]
### Steps To Reproduce

1. Enable 'Start To Tray Icon' in Bitwarden settings, on Linux. 
2. Exit Bitwarden desktop client.
3. Start Bitwarden desktop client.
4. Observe application window is momentarily displayed before being minimised to system tray icon.

### Expected Result

With 'Start To Tray Icon' enabled, the application window should not be displayed at all when being first opened.

### Actual Result

The application window is momentarily displayed (or at least the window decorations are) before being minimised to system tray icon, albeit only for a very short time (less than a second).

Worth noting, this happens for me on Linux (Kubuntu 21.10) but does not seem to happen on macOS.

### Operating System

Linux

### Operating System Version

Kubuntu 21.10

### Build Version

Version 2022.5.1 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by dbosompem** [comment]
Hi @monkeyhybrid , thanks for creating this issue. The team will take a look, so we can hopefully get things sorted and working for you. Very appreciated!

**Comment by Greenderella** [comment]
Since this issue has been open for quite some time without recent activity, I'm curious if anyone is still experiencing this problem. If the issue persists, please share any updated details. Thanks, everyone, for your contributions and feedback!
