### ISSUE TITLE
"No folder" option show all items

### ISSUE THREAD

**Issue by samuelcg49** [bitwarden/clients#2930]
### Steps To Reproduce

1. Go to 'No Folder' inside FOLDERS
2. Click on it

### Expected Result

If you click on the "No Folder" option you should see the items with no folder assigned.

### Actual Result

If you click on the "No Folder" option you see all items you have, and the option "all items" you can see it over the "favorites" option.

### Operating System

macOS

### Operating System Version

12.4

### Installation method

Mac App Store

### Build Version

Version 2022.5.1 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture arm64

**Comment by djsmith85** [comment]
Hi @samuelcg49, thank you for your report. This has already been reported with https://github.com/bitwarden/clients/issues/2821 and a fix will be included in the next release.

Closing this as duplicate
