### ISSUE TITLE
"No folder" folder shows all items

### ISSUE THREAD

**Issue by YBStolker** [bitwarden/clients#2941]
### Steps To Reproduce

1. Create a folder "test_folder"
2. Create an item "test_item"
3. Add the item to the folder you just created

### Expected Result

I expect "test_item" to be hidden when I select "No folder" and to be shown when I select "test_folder".

### Actual Result

"test_item" is shown in both "No folder" and "test_folder" 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/23400223/174767432-2da24362-2d38-4fda-ad7d-b063a01cc212.png)
![image](https://user-images.githubusercontent.com/23400223/174768112-ae4b3380-ec76-4c30-b7c8-049873766608.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by djsmith85** [comment]
Hi @YBStolker , thank you for your report. This has already been reported with https://github.com/bitwarden/clients/issues/2821 and a fix will be included in the next release.

Closing this as duplicate
