### ISSUE TITLE
Bitwarden Desktop (Windows) "No Folder" filter lists all entries

### ISSUE THREAD

**Issue by AlasdairMS** [bitwarden/clients#2972]
### Steps To Reproduce

Select "No Folder" in left hand navigation pane under Folders

### Expected Result

Only entries with no folder assigned should be listed.

### Actual Result

All entries are listed.

### Operating System

Windows

### Operating System Version

Windows 11 pro 21H2

### Web Browser

Chrome

### Browser Version

N/A - Issue in Desktop App

### Build Version

Version 2022.5.1

**Comment by djsmith85** [comment]
Hi @AlasdairMS, thank you for your report. This has already been reported with https://github.com/bitwarden/clients/issues/2821 and a fix will be included in the next release.

Closing this as duplicate
