### ISSUE TITLE
Locale 'de' inconsistencies

### ISSUE THREAD

**Issue by AuspeXeu** [bitwarden/clients#2977]
### Steps To Reproduce

Compare these three lines.

https://github.com/bitwarden/clients/blob/master/apps/browser/src/_locales/de/messages.json#L1256
https://github.com/bitwarden/clients/blob/master/apps/desktop/src/locales/de/messages.json#L1217
https://github.com/bitwarden/clients/blob/master/apps/web/src/locales/de/messages.json#L198

### Expected Result

The translation to be consistent across all three clients.

### Actual Result

The translation is inconsitent.

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2.28.1

**Comment by djsmith85** [comment]
Hi @AuspeXeu thank you for your report.

We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌 
Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/) for further information.

Here are the links to the specific translation across our clients:

https://crowdin.com/translate/bitwarden-browser/26/en-de#2140
https://crowdin.com/translate/bitwarden-web/58/en-de#2278
https://crowdin.com/translate/bitwarden-desktop/53/en-de#2170

New translations can be added or existing one can be up-/down-voted

Greetings from Germany

Closing this now.

**Comment by AuspeXeu** [comment]
No clue how this is supposed to work to be frank.

![image](https://user-images.githubusercontent.com/2115696/176605423-51bd3daf-8970-454f-8053-7d5a5a3fe1b6.png)

**Comment by djsmith85** [comment]
@AuspeXeu No worries, I've up/downvoted the translations and they all now reflect to show `Host`. 

If you find any other issues in regards to translations, I'd ask you to please create an account at Crowdin and familiarize yourself with the platform. You can raise issue there directly, add translations or up-/down-vote existing ones. For example here's an [overview](https://support.crowdin.com/online-editor/) on how the editor works.
