### ISSUE TITLE
Folder list item click and hover areas are inconsistent

### ISSUE THREAD

**Issue by Diesmo** [bitwarden/clients#2978]
### Steps To Reproduce

1. Open Bitwarden Desktop Client (Windows) and login
2. Create an folder named "ABC" or anything short named
3. Hover over the folders list items white space in the side menu
4. Click to select that folder

### Expected Result

Folder gets selected after the click, as indicated by the hovering color highlight

### Actual Result

Folder does not get selected as the click listener seems to be only present on the shorter text name of the folder list item, meanwhile the hover listener is on the whole item.

### Screenshots or Videos

![Bitwarden_2022-06-25_17-11-03](https://user-images.githubusercontent.com/17813062/175779671-cef48181-1d12-4a00-b9cb-67772bd2dde5.gif)

Notice in the clip I click multiple times, but it only get registered when my cursor enters the text area and the cursor changes to `pointer` mode

### Additional Context

Either shrink the hover listener to the text size or expand the click listener to the whole item size. But the current state feels inconsistent and unintuitive.
I personally would choose to expand the click listener to the whole item size, as this is the most common approach to side bar list menus.

### Operating System

Windows

### Installation method

Microsoft Store

### Build Version

2022.5.1

**Comment by federicom09** [comment]
Hello @Diesmo,

This issue was fixed. You can find the PR below.
Thanks for reporting this!

https://github.com/bitwarden/clients/pull/3233
