### ISSUE TITLE
Firefox keeps "forgetting" connection with desktop app for authentication with biometrics

### ISSUE THREAD

**Issue by ericswpark** [bitwarden/clients#2981]
### Steps To Reproduce

1. Open extension in Firefox. The extension will ask you to "re-link" with the desktop app, and display a fingerprint phrase so you can approve the connection within the desktop app.
2. Quit the desktop app.
3. Quit and re-open Firefox.
4. Open extension.

### Expected Result

The extension should remember the connection with the desktop app. Additionally, if it is having trouble communicating with the desktop app, it should prompt the user to open the desktop app.

### Actual Result

The extension forgets the connection and prompts the user to connect the extension to the desktop app again, showing a fingerprint phrase to approve in the desktop app. The fingerprint is different from the one shown in step 1 in steps to reproduce, and continues to change as the steps are repeated.

### Operating System

macOS

### Operating System Version

macOS Monterey 12.4 (21F79)

### Web Browser

Firefox

### Browser Version

101.0.1

### Build Version

2022.5.0

**Comment by ericswpark** [comment]
Found the problem: I had biometric authentication enabled on both Safari and Firefox (I switched from Safari to Firefox some time ago). Disabling biometric authentication on Safari seems to have fixed the issue. I'll keep this open because in my opinion Bitwarden should allow for multiple extensions to connect to the desktop app for biometric authentication.

**Comment by dbosompem** [comment]
Hi @ericswpark , thank you for raising this issue and delving deeper to find the problem. The team will make time to take a look at this. Very appreciated!

**Comment by Hinton** [comment]
This sounds like the expected behaviour when the "Require verification for browser integration" is enabled.

> Enable an additional layer of security by requiring fingerprint phrase validation when establishing a link between your desktop and browser. When enabled, this requires user intervention and verification each time a connection is established.

This connection needs to be re-established should either the desktop application or the browser be restarted.

**Comment by ericswpark** [comment]
@Hinton  when I had the toggle enabled I didn't get this behavior with Safari. Maybe Firefox establishes a new connection each time the browser is restarted? I'm not sure what changed the behavior, but I now have the toggle off and have the extension disabled on Safari and I no longer get the fingerprint verification prompt.

In any case I'll close this issue now as it does not seem to be one anymore. Thanks!

**Comment by ericswpark** [comment]
@Hinton ah I see, that makes sense as to why Bitwarden required multiple verifications with Firefox. Thank you for the explanation!

**Comment by psa** [comment]
This started being a problem for me after the 2022.10.01 update. Constantly loses connection to the desktop application. I'm not using Safari, so that isn't a fix for me.

There's a number of people noticing this, as per https://www.reddit.com/r/Bitwarden/comments/xjl7lu/desktop_communication_interrupted/
