### ISSUE TITLE
"No folder" lists all items on desktop version

### ISSUE THREAD

**Issue by Nyxtorm** [bitwarden/clients#2997]
### Steps To Reproduce

1. Create a new element in a folder
2. Go to "No folder" on the left

### Expected Result

Only items outside a folder should be displayed

### Actual Result

All items are displayed

### Screenshots or Videos

- Screenshot 01 : https://i.imgur.com/6Cj49EQ.png

### Operating System

Windows

### Operating System Version

Windows 11 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by djsmith85** [comment]
@Nyxtorm Thank you for your report. This has already been reported with https://github.com/bitwarden/clients/issues/2821 and a fix will be included in the next release (scheduled for this week).

Closing this as duplicate
