### ISSUE TITLE
Bitwarden auto-fill is available in firefox window if extension is unlocked in another window

### ISSUE THREAD

**Issue by AdneSvendsrud** [bitwarden/clients#2998]
### Steps To Reproduce

1. Open a private window with bitwarden
2. log into the bitwarden browser extension
3. Open a private window with bitwarden
4. Try to use the context menu to auto-fill using bitwarden in the new window

### Expected Result

The standard popup of "unlock vault" since the vault is locked in that window

### Actual Result

Autofill is available through the context menu

### Screenshots or Videos

The private window's vault is locked
![image](https://user-images.githubusercontent.com/79193704/176402470-aba1029a-8ee8-4a9f-8379-d947d8c82943.png)

Autofill is still enabled, since the browser extension in a normal window is enabled
![image](https://user-images.githubusercontent.com/79193704/176402452-4a717473-2807-438a-ab3f-9c98695fdb00.png)

### Additional Context

The problem seems to be an issue between windows as the context menu is changed when one instance of the bitwarden browser extension is unlocked.
The issue does transfer from a normal browsing windows to the private browsing windows, but not the other way

Tested in firefox:
Tested between private windows (autofill available in the private window with a locked vault)
from normal window to private window (autofill available in the private window with a locked vault)
from private window to normal window (autofill not available in the normal window, even though the vault is unlocked in the private window)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

102.0

### Build Version

2022.5.0

**Comment by Hinton** [comment]
This is the expected behavior. The private window and the regular window are the same browser and share context. However the browser popup in the private window cannot communicate with the background page and therefore needs to be unlocked each time.
