### ISSUE TITLE
Organization filter causes items to shift as toolbar popup slowly loads

### ISSUE THREAD

**Issue by setyb** [bitwarden/clients#3001]
### Steps To Reproduce

1. Open the web browser.
2. Click on the Bitwarden toolbar icon.
3. Notice that as the Bitwarden panel slowly loads, the items displayed will shift down once the organization filter is finally displayed (this can lead to the user clicking the wrong item).

### Expected Result

Items in Bitwarden panel to remain in a static position as the the panel loads.

### Actual Result

The items display will shift down once the organization filter is finally displayed.  This can lead to the user clicking the wrong item.

### Additional Context

This is a regression after the new organization filter was introduced in #2463.

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

102

### Build Version

2022.5.0

**Comment by aj-bw** [comment]
hi @setyb,

Thanks for reaching out. So far I have been unable to reproduce this bug on the current production browser extension in Firefox ( version 2022.08.0 ). It seems to load the vault filter first on login then the following vault items.

Would you mind updating when you have a moment and test again and let me know the results here? If the issue persists please also include the distro of Linux you are using so we can do more 1 to 1 testing.
