### ISSUE TITLE
Moving issue #351

### ISSUE THREAD

**Issue by setyb** [bitwarden/clients#3002]
### Steps To Reproduce

Confirmed issue https://github.com/bitwarden/web/issues/351 was possibly abandoned during Bitwarden's reorganization.  Can you move it to the appropriate area and reopen?

### Expected Result

See https://github.com/bitwarden/web/issues/351

### Actual Result

See https://github.com/bitwarden/web/issues/351

### Operating System

Linux

### Web Browser

Firefox

### Build Version

See https://github.com/bitwarden/web/issues/351

**Comment by djsmith85** [comment]
@setyb Thank you for mentioning this. Before we move the issue over, can you confirm that the behaviour described in https://github.com/bitwarden/web/issues/351 is still occurring, as the last reports/examples are quite old.
