### ISSUE TITLE
Unable to add any item in the vault

### ISSUE THREAD

**Issue by royshubhadeep** [bitwarden/clients#3008]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Add New Login'
3. Enter all details
4. Click on 'Save'

### Expected Result

New item should be saved in the vault

### Actual Result

Getting the following error-
An error has occurred.
An unhandled server error has occurred.

### Screenshots or Videos

<img width="731" alt="2022-06-29_16-27-41" src="https://user-images.githubusercontent.com/12464969/176539476-500d07f4-ed89-4a54-b306-21decf8a2b5a.png">

### Additional Context

Getting the same error while using the Chrome Extension. However the iPhone app is working fine.

### Operating System

macOS

### Operating System Version

macOS Monterey v12.4

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.5.1 (3283)

**Comment by dbosompem** [comment]
Hello @royshubhadeep , thank you for raising this issue, and apologies for facing this issue. Could you confirm if you're still having such encounter?
