### ISSUE TITLE
Desktop app doesn't give itself focus or window ordering properly

### ISSUE THREAD

**Issue by steakknife** [bitwarden/clients#3009]
### Steps To Reproduce

Turn on hide to status bar, and minimize when copying.

### Expected Result

Focus when requested

### Actual Result

Focus / window order is relinquished below other apps. Requires switching focus to it manually.

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

2022.5.1

**Comment by ataruselli** [comment]
Hello @steakknife , thank you for taking the time to report this.
We tried to reproduce this issue but we couldn’t. 
Could you please check if this issue is still happening to you in the last version (2022.8)? If so, could you please provide us the steps to reproduce the issue?

**Comment by steakknife** [comment]
It might take some time as I'm mid-relocating. I'll take a look when I can.

**Comment by aj-bw** [comment]
Hi @steakknife,

Just wanted to reach out that after additional research, I discovered this issue had been reported previously. I have linked this GitHub issue to our internal report and raised it for further prioritization / consideration.

**Comment by fabriziobagala** [comment]
Hi @steakknife,

I am also experiencing the same problem as you. The bug is also present in version 2023.5.0 of the app downloaded from the App Store.

**Comment by atjbramley** [comment]
Hi @steakknife, 

Thank you for your report, it seems like it has been duplicated by this one: https://github.com/bitwarden/clients/issues/5252 

As 5252 includes more discussion, the team will refer to that issue moving forwards.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
