### ISSUE TITLE
'No Folder' section shows all items, including those in folders

### ISSUE THREAD

**Issue by thechnet** [bitwarden/clients#3010]
### Steps To Reproduce

1. Add an entry to a folder.
2. Check the 'No Folder' section: the entry is still listed.

### Expected Result

After an entry was added to a folder, it should no longer be listed under the 'No Folder' section. This behavior works as expected in the browser extension.

### Actual Result

Entries that have been added to a folder are listed both in the actual folder and in 'No Folder'.

### Operating System

Windows

### Operating System Version

11

### Installation method

Microsoft Store

### Build Version

2022.5.1

**Comment by djsmith85** [comment]
@thechnet Thank you for your report. This has already been reported with #2821 and a fix will be included in the next release (scheduled for this week).

Closing this as duplicate
