### ISSUE TITLE
Bitwarden Windows desktop client does not auto-prompt Windows Hello after lock, only when 1st starting

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#3012]
### Steps To Reproduce

1. When you are in Windows (I have tested it with Windows 11 and 10), make sure you have the option 'Unlock with Windows Hello' selected and Windows Hello configured on your Windows PC.
2. Exit Bitwarden Windows client:
![image](https://user-images.githubusercontent.com/98819304/176653807-b266b16a-2fc4-4821-860d-3e3736d8f375.png)
right click on Bitwarden system tray icon | Exit
3. Start Bitwarden for Windows. You are being automatically prompted by Windows Hello to unlock your vault.
4. Now, lock your vault: 
![image](https://user-images.githubusercontent.com/98819304/176653807-b266b16a-2fc4-4821-860d-3e3736d8f375.png)
right click on Bitwarden system tray icon | Lock
6. Open Windows start menu, then double click on Bitwarden for Windows icon. Bitwarden for Windows open itself and does not auto-prompt Windows Hello (like your other apps do). You are forced to do that manually by clicking on the button "Unlock with Windows Hello":
![image](https://user-images.githubusercontent.com/98819304/176654871-78cae5c9-7694-4ac8-aad1-3a374b456bd7.png)
We should have to click on that button to get Windows Hello when the vault is locked, we should get auto-prompt Windows Hello (like on your Chrome extension for example and your Android app)

### Expected Result

The expected result is to be automatically prompted by Windows Hello each time Bitwarden Windows client is locked:
![image](https://user-images.githubusercontent.com/98819304/176652890-89677c2d-3c96-4fc9-9621-f9426026943c.png)

### Actual Result

Currently this is not what happens
![image](https://user-images.githubusercontent.com/98819304/176653038-978097b9-133f-4b91-b6e0-65c1655a98c0.png)

### Additional Context

This bug has been fully discussed in the Bitwarden Community thread: https://community.bitwarden.com/t/windows-hello-auto-prompt-in-bitwarden-for-windows/42293

Here is the technical solution: The Windows Hello trigger has been added into the Bitwarden for Windows start event, instead of putting it into the Bitwarden unlock event. If I exit Bitwarden completely, I get the auto Windows Hello prompt. Users should also get it for unlocking their vault (like your Android app and Chrome extension are doing).

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by VM9797** [comment]
I am facing the exact same issue. Is there any additional information I can provide about this? 
My build version is 2022.6.2

**Comment by dwbit** [comment]
Thanks for the information everyone, the team has confirmed that this currently working as expected (ei not broken) and that changing this behavior can be discussed and voted on in this [feature request](https://community.bitwarden.com/t/windows-hello-auto-prompt-in-bitwarden-for-windows/42293/35).

**Comment by oeloo** [comment]
> Thanks for the information everyone, the team has confirmed that this is currently working as expected (ei not broken) and that changing this behavior can be discussed and voted on in this [feature request](https://community.bitwarden.com/t/windows-hello-auto-prompt-in-bitwarden-for-windows/42293/35).

A lot of information is missing here ! what is the argument to claim it is expected ?
And why would the Bitwarden desktop app would be inconsistent on this point with Bitwarden for Chrome ? For information Bitwarden for Chrome auto-prompt Biometrics.


Furthermore the renaming in " Biometrics auto-prompt on Window Focus (after locking vault)" is fully incorrect with the conversation below. Is it not on Windows focus, but on relaunching the app.
It clearly shows your decision was badly taken
