### ISSUE TITLE
Snap fails to start -- `~/snap/bitwarden/69/.last_revision` permission denied

### ISSUE THREAD

**Issue by macbrayne** [bitwarden/clients#3032]
### Steps To Reproduce

Start Bitwarden via console or desktop file

### Expected Result

Bitwarden opens up

### Actual Result

Bitwarden doesn't start

### Additional Context

This probably happened due to an update however I can't check as only versions `68` and `69` are locally available which were both installed after the problem first appeared.

I can still open it via https://github.com/bitwarden/desktop/issues/250

`dmesg | grep denied` shows stuff like

```log
[   1121.781035] audit: type=1400 audit(1657023582.367:192): apparmor="DENIED" operation="open" profile="snap.bitwarden.bitwarden" name="/home/macbrayne/snap/bitwarden/69/.last_revision" pid=6036 comm="desktop-init.sh" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000
```
The permissions of the affected `.last_revison` are the same as the one as for `~/snap/bitwarden/68/.last_revision`
```bash
ls -l /home/macbrayne/snap/bitwarden/69/.last_revision 
-rw-rw-r-- 1 macbrayne macbrayne 30 Jun 28 15:35 /home/macbrayne/snap/bitwarden/69/.last_revision
```

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.4 LTS

### Installation method

Snap

### Build Version

bitwarden Version 2022.6.0 Rev 69

**Comment by djsmith85** [comment]
@macbrayne Thank you for your report. Is this possibly a duplicate of https://github.com/bitwarden/clients/issues/2629? If so, please close this issue.

**Comment by macbrayne** [comment]
I'd say it probably isn't as neither deleting user config files does anything nor am I symlinking any directories. For whatever reason it fails on the `.last_revision` file containing a nothing but a version number.
