### ISSUE TITLE
Username generation API Access Token not saved in browser extension

### ISSUE THREAD

**Issue by adambanr** [bitwarden/clients#3055]
### Steps To Reproduce

Using latest version of Microsoft Edge
1. Click on Bitwarden extension
2. Click on 'generator' and select Username Option
3. For username type select Forwarded Email Alias
4. Select AnonAddy
5. Paste API Access Token (AnonAddy) 
6. Generate email address and select copy
7. Go back in to generate a second email alias using same options on same browser and API key is not saved.

### Expected Result

Expecting to only have to paste the API token into the Edge web extension one time and have it saved there for future email alias generation needs.  Having to go generate a new API Token each time negates the time savings for the integration.

### Actual Result

API key is not saved and you have to go back to Anonaddy to generate a new key when generating a new email alias.  I see that the API Token is saved in the Bitwarden web vault but not appearing in the extension.

### Operating System

Windows

### Operating System Version

Windows 11 21H2 OS Build 22000.778

### Web Browser

Microsoft Edge

### Browser Version

Version 103.0.1264.44 (Official build) (64-bit)

### Build Version

Version 103.0.1264.44 (Official build) (64-bit)

**Comment by dbosompem** [comment]
Hi @adambanr , thanks for raising this issue. We will reproduce this issue and look into it as we keep you in the loop. Very appreciated.

**Comment by aj-bw** [comment]
Hi @adambanr, Thanks for reaching out.

I have been triaging this and so far have been unable to reproduce the issue. Please consider updating or uninstalling / reinstalling your browser extension and trying again.

We use GitHub issues as a place to track bugs and other development related issues. Your issue appears it would be better handled by our dedicated Customer Success team. Please feel free to contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.
