### ISSUE TITLE
Slow loading time after login.

### ISSUE THREAD

**Issue by jjosorioc** [bitwarden/clients#3093]
### Steps To Reproduce

1. Click on the app icon
2. Enter the vault's PIN / Password
3. After logging in, it takes about 10 seconds for the app to load the items.

### Expected Result

Immediately display the items after logging in. 

### Actual Result

It takes about 10 seconds for the app to load the items.

### Operating System

Linux

### Operating System Version

Linux Mint 20.3 x86_64

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.5.1 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by dbosompem** [comment]
Hi @jjosorioc. Thank you for opening this issue. The team will reproduce this and we'd revert soon

**Comment by dbosompem** [comment]
Hi @jjosorioc can you confirm if you still face this issue currently?

**Comment by jjosorioc** [comment]
Yes, I still face this issue.
Version 2022.5.1
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

**Comment by bnagawiecki** [comment]
Hey @jjosorioc, 

Thanks for submitting this issue!

I tried to replicate this on the latest version of the app with a similar setup but was unable to. Even with a larger vault (~4k items), it did take slightly longer to load but still loaded my vault well under 10 seconds after unlocking. Is there any more information you can provide that might help us replicate this?

**Comment by jjosorioc** [comment]
Hi! Like I mentioned in [this issue](https://github.com/bitwarden/clients/issues/3236#issuecomment-1235043729), it may be because it's a Flathub/Flatpak app.

**Comment by vphan916** [comment]
Hi @jjosorioc.  Hope all is well. Can you download the app without Flathub/Flatpak and let us know if this problem persists?
