### ISSUE TITLE
Vulnerability: Chrome extension saves vault in persistent local storage after logging out and exiting Chrome

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#3124]
### Steps To Reproduce

1. Log into vault using Chrome extension
2. Log out of vault on Chrome extension
3. Exit Chrome
4. Navigate to %LocalAppData%\Google\Chrome\User Data\Default\Local Extension Settings\nngceckbapebfimnlniiiahkandclblb
5. Open the most recent *.log file using Notepad
6. Optionally, use Edit/Find to search for terms such as "keyHash", "email", "login", "password", etc.

### Expected Result

If the user has logged out, the vault should be expunged from persistent storage.  [Bitwarden documentation](https://bitwarden.com/help/vault-timeout/#vault-timeout-action) makes the claim: **"Logging out of your vault completely removes all vault data from your device."**

Thus, the *.log file (which contains vault data for the Chrome extension) should be deleted, or contain only a skeleton template structure with non-existent entries for "email", "keyHash", "login", "password", etc., or (at worst) empty values for all fields that hold secret/sensitive information.

### Actual Result

The stored *.log file contains one or more copies of the encrypted vault, which persists even after logging out of the vault, exiting Chrome, and rebooting the computer,  By scanning through the file, or by using search terms such as those suggested above, the full contents of the vault are revealed, including the email account in plaintext, the hashed version of the Master Key, as well as encrypted cipher strings containing all secrets.  In effect, there appears to be no practical security difference between the locked state and the logged out state.

### Additional Context

The vault data can be easily be exfiltrated by anybody who has physical access to the computer for a short time, whether the computer is on or off.  Using copied values of the fields "email", "kdfIterations", and "keyHash", the master password can be brute-forced if it is sufficiently weak, which would then allow a bad actor to access the web vault.  Whether such a threat model is widely applicable or not, users have the expectation that encrypted vault data is removed from persistent storage upon logout; this expectation is not met for the Chrome extension.  I have not tested other browser extensions.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome

### Browser Version

Version 103.0.5060.114

### Build Version

2022.6.1

**Comment by dbosompem** [comment]
Hi @bwbug ,thank you for raising this issue. The team will reproduce the issue which afterwards we'd investigate and look for potential solutions. Very appreciated!

**Comment by dbosompem** [comment]
Hi @bwbug , thank you for checking in on this issue. I will do a quick follow up and get back to you on this; looks like we gave the other vulnerability a very high priority, but I will check in with the team and let you know if we have been able to reproduce this. Appreciate your proactiveness!

**Comment by dbosompem** [comment]
Hi @bwbug, the team has been able to reproduce this now. Apologies for the long wait. It would be passed over to the dev team to take a look, but kindly note that we are working on the other vulnerability now. This will be visited when we get a good hold on that, first.
With regards to the new observation, I believe it is not so related to this one, so we can create a new issue, the team will reproduce that as well.

**Comment by joaobeltrao** [comment]
Could we get an update here please? @dbosompem

**Comment by migueldemoura** [comment]
Well, this just saved me after messing up and losing my 2FA. 😅
