### ISSUE TITLE
Chocolatey Upgrades broken

### ISSUE THREAD

**Issue by nykBM** [bitwarden/clients#3134]
### Steps To Reproduce

The Chocolatey packages for Bitwarden V2022.6.1 and V2022.6.2 are failing because they point to the old repository and naming convention.  The new versions for Bitwarden are then not being released to the community to have their machines updated.

### Expected Result

chocolateyinstall.ps1 (https://github.com/bitwarden/clients/tree/master/apps/desktop/stores/chocolatey/tools) should point to the new repository (https://github.com/bitwarden/clients/releases/download/desktop-v2022.6.1/Bitwarden-Installer-2022.6.1.exe).  The chocolatey upgrade from Bitwarden V2022.6.0 to V2022.6.1 should be successful.

### Actual Result

From what I can tell the new automatically generated chocolatey packages (V2022.6.1 and V2022.6.2) are failing because the chocolateyinstall.ps1 file here (https://github.com/bitwarden/clients/tree/master/apps/desktop/stores/chocolatey/tools) is still pointing to the old repository (https://github.com/bitwarden/desktop/releases/download/v2022.6.1/Bitwarden-Installer-2022.6.1.exe).  It gives a 404 error because it cannot find the file at the url and the install is not successful.

### Additional Context

I assume that a change in github for the chocolateyinstall.ps1 file will trigger a new chocolatey package to be generated and submited for Bitwarden V2022.6.2 that will be eventually approved for the community to use.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Chocolatey

### Build Version

Bitwarden Client V2022.6.0

**Comment by joseph-flinn** [comment]
The Desktop release has been backported to the deprecated repo. This problem has been fixed.

[Desktop v2022.6.1](https://github.com/bitwarden/desktop/releases/tag/v2022.6.1)
[Desktop v2022.6.2](https://github.com/bitwarden/desktop/releases/tag/v2022.6.2)
