### ISSUE TITLE
Breakpoint exception

### ISSUE THREAD

**Issue by goose-ws** [bitwarden/clients#3138]
### Steps To Reproduce

Attempt to shut down the computer

### Expected Result

The application closes, and Windows shuts down

### Actual Result

When attempting to shut down Windows (via Start > Power > Shutdown), occasionally the Bitwarden desktop application will throw a breakpoint exception. The resulting popup prevents Windows from shutting down. There does not seem to be a pattern to this, I can't pin down any specific thing that does or does not cause the breakpoint exception to occur.

### Screenshots or Videos

Here is a screenshot of the breakpoint exception pop up, which prevents Windows from shutting down.

![image](https://user-images.githubusercontent.com/874014/179972947-3723e81c-7458-4beb-b3a8-60ecd4a809bd.png)

### Operating System

Windows

### Operating System Version

Edition: Windows 11 Pro | Version: 21H2 | Installed on: ‎7/‎1/‎2022 | OS build: 22000.795 | Experience: Windows Feature Experience Pack 1000.22000.795.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version: 2022.6.2 | Shell: 16.2.7 | Renderer: 96.0.4664.174 | Node: 16.9.1 | Architecture: x64

**Comment by Akkowicz** [comment]
I have the same issue, installed from MS Store.

**Comment by ataruselli** [comment]
Hello @goose-ws , thank you for taking the time for reporting this.
We tried to reproduce the issue with the last version (2022.8) and we couldn't.
Could you please try updating to the last version and check again?

**Comment by Akkowicz** [comment]
For me the issue does not appear anymore on 2022.8.

**Comment by xc-manoj** [comment]
Hi, may I reopen?
I do still experience this on 2023.4.0, the same thing with the pattern and I'm currently at Windows 11 22621.1635. I installed it through an official installer from Bitwarden's website.

**Comment by UhtredTheBold** [comment]
I don't know if this will help anybody but I had this problem and eventually I figured out that it was fast startup causing the problem. As soon as I disabled it the problem went away.

**Comment by flumiie** [comment]
I managed to get the screenshot of it, almost a week ago. Only shows up at that one time, so I guess it's an improvement?
![breakpoint](https://github.com/bitwarden/clients/assets/8995187/e4994502-0083-469c-b079-4d8126d63084)

It's on Windows 11 build 22621.1702,
![image](https://github.com/bitwarden/clients/assets/8995187/42f6c533-5d4a-4324-b9ba-c18956de6ab9)
> I don't know if this will help anybody but I had this problem and eventually I figured out that it was fast startup causing this. As soon as I disabled it the problem went away.

I disabled hibernate entirely by using `powercfg /hibernate off`. So I guess it's not that.

**Comment by ijimin** [comment]
I just got this on trying to reboot.  
![image](https://github.com/bitwarden/clients/assets/137301931/23e7f144-333b-4151-9e49-435b021d7663)

**Comment by goose-ws** [comment]
Yeah, nearly two years and many version updates later and I'm still experiencing this issue randomly. I can't reopen this, but perhaps a maintainer can?

**Comment by Kasazn** [comment]
If I don't close Bitwarden when shutting down my PC, error as described by OP appears. I'm on latest Windows 11 Pro.

**Comment by sh-hi** [comment]
Its September 2024 and the error still pops up randomly during shutdown. To reproduce the error it might have something to do with Windows Hello enabled (Fingerprint, PIN)?
