### ISSUE TITLE
So many logs created by Bitwarden on Windows event manager when using Bitwarden windows client.

### ISSUE THREAD

**Issue by thelastfantasy** [bitwarden/clients#3159]
### Steps To Reproduce

None

### Expected Result

None

### Actual Result

None

### Additional Context

Also reported on the official cummunity
https://community.bitwarden.com/t/bitwarden-desktop-client-for-windows-creates-too-many-logs-on-event-manager/42980

Here are the logs
https://onedrive.live.com/redir?resid=CDD08088BCB5A0C%21121564&authkey=%21ABjPYTy2XAYKKeA&e=ZoDHZJ

### Operating System

Windows

### Operating System Version

Windows10 Pro 19044.1826

### Installation method

Direct Download (from bitwarden.com)

### Build Version

版本 2022.6.2 Shell 16.2.7 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by ataruselli** [comment]
Hello @thelastfantasy , thank you for taking the time for reporting this issue.
We tried to reproduce the issue but we couldn't because we need more information to be able to reproduce the issue, could you please provide us steps for reproducing it?

**Comment by vphan916** [comment]
We need more information before we can help you with your problem. As we haven’t heard from you recently, this issue will be closed.

If this happens again or continues to be a problem, please respond to this issue with the information we’ve requested and anything else relevant.
