### ISSUE TITLE
Bitwarden causing Safari to freeze the browser 

### ISSUE THREAD

**Issue by iksdeecz** [bitwarden/clients#3167]
### Steps To Reproduce

1. Go to 'www.seznam.cz' using latest Safari browser (macOS 12.5 intel)
2. Wait for the page to load.

### Expected Result

Freeze of browser/ browser tab. Slowness of website.

### Actual Result

When the page loads it should freeze the browser page and for approximately 5-10 seconds you are unable to click on and url link.

### Additional Context

It happens only in Safari with only  Bitwarden plug-in enabled. When the plug-in is disabled there are no longer any freezes and slowness. Also in Firefox and Chrome there are no issues described above.

### Operating System

macOS

### Operating System Version

12.5

### Web Browser

Safari

### Build Version

latest v2022.6.1

**Comment by ataruselli** [comment]
hello @iksdeecz, thank you for taking the time for reporting this.
We tried to reproduce this issue and we couldn't.
Could you please try again with the last version (2022.8) and check if the issue is still present?
