### ISSUE TITLE
Login suggestions are terrible for domains without SSO.

### ISSUE THREAD

**Issue by Leopere** [bitwarden/clients#3184]
### Steps To Reproduce

1. Navigate to subdomain.example.com and log in using bitwarden browser extension having picked manually through list for record for subdomain.example.com
2. Navigate to othersubdomain.example.com and log in usinb bitwarden browser extension having scrolled manually through list for record for othersubdomain.example.com.
3. Wonder why Bitwarden can't suggest the most likely credential based on URL strings.

### Expected Result

Be able to detect and suggest as a top result rather than just random, seemingly unsorted list of potential matches for logging in.

### Actual Result

The credentials list seems to change without explanation of potential options for login credentials within the same site.  For example, on Slack, you're forced to need a separate account for every possible Slack server you're forced to use.

### Operating System

Windows, macOS, Android, iOS

### Web Browser

Chrome, Safari, Firefox, Brave

### Build Version

Version: 2022.6.1

**Comment by djsmith85** [comment]
Hi @Leopere thank you for your report. 

Please have a look at the following [help page](https://bitwarden.com/help/uri-match-detection/), which details the uri-match-detection. Maybe also have a look at our {community forums](https://community.bitwarden.com/c/support/6).  

In your case the match-detection likelt needs to be set to `Host` on those items.

Kind regards,
Daniel
