### ISSUE TITLE
Documentation for contributors lacks instructions for Chromatic

### ISSUE THREAD

**Issue by UppaJung** [bitwarden/clients#3185]
### Steps To Reproduce

1. Fork [the clients master](https://github.com/bitwarden/clients) without whatever magic makes Chromatic work internally at Bitwarden
2. Check in any change, no matter how big or small.

### Expected Result

A successful build if no breaking changes occur

### Actual Result

Chromatic breaks CI because it can't get credentials.

### Additional Context

The addition of chromatic to the CI experience seems to break for third-party developers.  The contribution guidelines may need to be updated to that those of us forking the repository to build PRs don't encounter failures on every checkin.

### Operating System

macOS

### Operating System Version

12.4

### Installation method

Other

### Build Version

commit 6572bac

**Comment by Hinton** [comment]
Hi @UppaJung,

I don't believe GH actions runs on forked repositories by default. Many of our workflows requires secrets which we cannot share for various reasons, Chromatic being one of those.

It should be possible to disable a single workflow from being triggered through the GitHub UI which would be my recommended solution. I also suspect you will run into issues with other workflows since they aren't designed to work properly on forked repositories.

**Comment by UppaJung** [comment]
@hinton, I believe this is actually NOT the default, as my fork runs these actions automatically.  One option to ensure other contributors don't run into this is to add to the contributor instructions what they need to turn actions off.  You could direct them to [Github's instructions for disabling a single workflow](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow) or just use this for all workflows:

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/8259431/182467754-20fd1b53-1a46-442c-be94-aed09c0d0ed5.png">

However, there are actions you likely want to run in the fork, like the lint action, so that outside contributors generate PRs that are easier for you to integrate.  So, I'd suggest adding the following to the .yml files of those actions that require credentials and thus can't be run in forks:

```yml
if: github.repository == ‘bitwarden/clients’
```

In fact, this very case is the motivation using the if statement in the context of a job when GitHub wrote their documentation.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif

I can write a PR if you'd like, but I'd only be able to test that it works in the case of the fork and not that it still works for you.

**Comment by Hinton** [comment]
I created a new fork and they seem to be disabled there.

![image](https://user-images.githubusercontent.com/137855/182556837-df2d833e-8b07-43ac-a329-daee753ed15b.png)

With that said, I believe we are happy to accept a PR that adds the if condition on all workflows.
