### ISSUE TITLE
When search Chinese terms, the search result won't appear unless add an extra space

### ISSUE THREAD

**Issue by crowbardispensingcore** [bitwarden/clients#3211]
### Steps To Reproduce

1. Open the plugin or website version of Bitwarden
2. Type search terms in Chinese

### Expected Result

Results appear immediately

### Actual Result

Results do not appear until adding an extra space in the end

### Additional Context

- The problem only happens in my first search after the plugin opens/website loads. If any search result has been shown for once, the problem disappears. The problem appears again if I close & reopen the plugin or reload the web version.
- If I copy & paste the search term instead of typing it in, the result shows immediately.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Latest

### Build Version

2022.6.2

**Comment by djsmith85** [comment]
Hi @crowbardispensingcore and thank you for your report. This has been reported before ( https://github.com/bitwarden/clients/issues/2702, https://github.com/bitwarden/clients/issues/3025 )and has been addressed with https://github.com/bitwarden/clients/pull/3014. The fix will be included in the next release.

Closing this now.
