### ISSUE TITLE
Bitwarden minimizes before master password is asked

### ISSUE THREAD

**Issue by YetAnotherSimon** [bitwarden/clients#3235]
### Steps To Reproduce

1. Go to settings and activate 'Minimize when copying to clipboard'
2. Add an entry with 'Master password re-prompt' enabled
3. Click on the icon to copy the password
4. Open the minimized desktop client

### Expected Result

Should have asked to confirm the master password after step 3 before minimizing

### Actual Result

Still waiting for master password confirmation after step 4

### Screenshots or Videos

![BitwardenMasterPasswordConfirmation](https://user-images.githubusercontent.com/22818389/182707526-a1017fdb-c500-43e3-9d3c-e07c877cdee3.gif)

### Operating System

Linux

### Operating System Version

Arch Linux (Gnome)

### Installation method

Other

### Build Version

2022.6.2

**Comment by TroyBW** [comment]
Hi there!

This issue should now be resolved in version 2023.8.x with this PR: https://github.com/bitwarden/clients/pull/5635

This issue will now be closed. Thanks!
