### ISSUE TITLE
The menu bar color is white while having the dark theme.

### ISSUE THREAD

**Issue by jjosorioc** [bitwarden/clients#3236]
### Steps To Reproduce

1. Open the Bitwarden app.

### Expected Result

The menu bar's color should follow the apps current theme.

### Actual Result

The menu bar's color is white regardless of the current theme. This occurs while using the dark theme or the "Nord" theme.

### Screenshots or Videos

Dark Theme:
![image](https://user-images.githubusercontent.com/77997542/182717384-ec7d3442-4d8d-4188-9639-48715e4d938e.png)

Nord Theme:
![image](https://user-images.githubusercontent.com/77997542/182717235-fed4c1f4-2491-428e-a1d8-57a2cf6f0802.png)

### Operating System

Linux

### Operating System Version

Linux Mint 20.3 x86_64

### Installation method

Other

### Build Version

Version 2022.6.2 Shell 16.2.7 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by bnagawiecki** [comment]
Hi @jjosorioc,

Thanks for submitting this issue!

Can you please confirm that your system theme is set to dark mode?

Based on my testing on Ubuntu, this occurs when your system theme is not set to dark mode, and you have manually changed the Bitwarden app to a dark or Nord theme. However, if the system theme is set to dark mode, then that bar changes to a dark theme. You can achieve the opposite result if your system is set to dark mode, but the app is in Light theme.

I'm seeing similar behavior on other applications.

**Comment by jjosorioc** [comment]
Yes, my system is set to dark mode. I believe this has something to do with the fact that I installed Bitwarden via Flathub/Flatpak.

**Comment by Hinton** [comment]
Flatpack applications are sandboxed https://forum.manjaro.org/t/flatpak-electron-menu-dark-mode/118297 which prevents the application from detecting the system theme. There is currently no electron API to change the menu color outside of this.

**Comment by victorodg** [comment]
You just have to install the "Flatseal" app, and in "All Applications", allow access to user files. Then in the "Environment" section, just pass "GTK_THEME=<themename>"
Flatseal is an app that is able to guarantee some accesses to Flatpak apps

**Comment by 4r1-60ld** [comment]
> You just have to install the "Flatseal" app, and in "All Applications", allow access to user files. Then in the "Environment" section, just pass "GTK_THEME=" Flatseal is an app that is able to guarantee some accesses to Flatpak apps

I cant get this solution to to work. When you say "just pass GTK_THEME=" ... what does that mean, exactly?

Thank you for any help.
