### ISSUE TITLE
Alt-Tab'ing interrupts copy to clipboard

### ISSUE THREAD

**Issue by oscarhermoso** [bitwarden/clients#3238]
### Steps To Reproduce

1. In the desktop client for Bitwarden, open any "Item"
2. Click on "Copy Username" or similar
3. Immediately `Alt`+`Tab` before the grey "Username copied" notification shows

### Expected Result

Expect clipboard to be populated with copied username

### Actual Result

Clipboard is unchanged

### Additional Context

Happens to me all the time, where I'll click to copy, and then immediately alt-tab, pasting the wrong value into a password field. I have recently been locked out of a service because of incorrect password attempts. Would be really nice to get it fixed.

This issue could be resolved by either making the copy resolve "faster" or allowing the Bitwarden client to populate the clipboard after navigating to a different window.

----

I'm not familiar with the codebase, but I assume the problematic line is this window check? Could be totally wrong though.

https://github.com/bitwarden/clients/blob/bc639688e84c1a997019194312e9c4a8a826479d/libs/angular/src/directives/select-copy.directive.ts

```javascript
    if (window == null) {
      return;
    }
```

### Operating System

Windows

### Operating System Version

Windows 10 Enterprise - Build 19044.1826

### Installation method

Chocolatey

### Build Version

Version 2022.6.2 Shell 16.2.7 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by aj-bw** [comment]
Hi @oscarhermoso! Thanks for reaching out.

So far I am unable to reproduce the issue, I tried the regular installation from bitwarden.com/download as well as Chocolatey. Consistently I was able to interact with any of the copy to clipboard buttons and immediately alt+tab to another window such as a browser or text editor and paste in the appropriate data.

I did notice you were on version 20222.6.2, I was testing on 2022.8.1 which is current production. Could you attempt to either update your app, or uninstall and reinstall the latest version, test again and report back here with the results?

**Comment by oscarhermoso** [comment]
Heyhey, my Bitwarden is now running the latest version, and the issue is resolved! Previously was able to reproduce 100% of the time. Thanks @aj-bw!

**Comment by aj-bw** [comment]
@oscarhermoso great news! Just to be double sure, I ran version 2022.6.2 and tested, then I could reproduce the bug. Glad it was resolved in the latest update for you.
