### ISSUE TITLE
Bitwarden mac client / browser extensions do not recognize dead keys on a PT-PT keyboard

### ISSUE THREAD

**Issue by abtsousa** [bitwarden/clients#3257]
### Steps To Reproduce

1. Use a PT-PT keyboard configuration on macOS.
2. Lock vault or log out of Bitwarden and get to the login form on either the macOS desktop client or any browser extension
3. Try inputting a password with accented characters (such as áèîõ)

### Expected Result

Password input is recognized correctly

### Actual Result

The accent dead keys give an error sound when pressed and non-accented keys are written instead (so áèîõ becomes aeio). Clicking the "show password" eye button allows you to enter the password correctly, but is an additional security risk.

### Operating System

macOS

### Operating System Version

Big Sur

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

2022.5.1 (3283)

**Comment by djsmith85** [comment]
Hi @abtsousa and thank you for your report. Closing this as a duplicate of #2472.
