### ISSUE TITLE
Extension auto-fills Wordpress page title field

### ISSUE THREAD

**Issue by shadowsofthesun** [bitwarden/clients#3271]
### Steps To Reproduce

1. Log in to a Wordpress site as an editor
2. Editor must be Classic (not Gutenberg), which is accomplished via the "Classic Editor" plugin
3. Go to edit a page
4. Allow the session to timeout (or immediately) click auto-fill
5. The Title field is replaced with your WP username

### Expected Result

Your username is inserted only into the username field of the session timeout popup.

### Actual Result

Your username is inserted into the Title field, as well as the username field of the session timeout popup. This can cause users to accidentally change the post title.

### Screenshots or Videos

![Screenshot 2022-08-09 225123](https://user-images.githubusercontent.com/110952942/183799776-bfbbb785-e875-4aee-895f-63c00b778d17.jpg)

### Additional Context

Field is marked as autocomplete="off". Full HTML is as follows.
```
<div id="titlewrap">
    <label class="screen-reader-text" id="title-prompt-text" for="title">Add title</label>
    <input type="text" name="post_title" size="30" value="[your page title]" id="title" spellcheck="true" autocomplete="off">
</div>
```

Wordpress 6.0.1.
Seems to happen in the Classic editor, rather than Gutenberg.
Also reported in Mar 2020, here: https://github.com/bitwarden/clients/issues/1190

### Operating System

Windows

### Operating System Version

10.0.19043 Build 19043

### Web Browser

Firefox

### Browser Version

103.0.1

### Build Version

2022.8.0

**Comment by creyhani** [comment]
Hello! I was able to reproduce this bug and am putting it into our queue for fixing -- great catch and thanks for reporting!

**Comment by djsmith85** [comment]
@shadowsofthesun With some very recent large changes to how autofill works, is this still an issue?

**Comment by shadowsofthesun** [comment]
> @shadowsofthesun With some very recent large changes to how autofill works, is this still an issue?

Sorry, been busy...
Yes, still happening in the browsers I tested: Firefox 124 and Brave 1.63.174 (Chromium 122.0.6261.128) with BW 2024.2.1
![image](https://github.com/bitwarden/clients/assets/110952942/6c20c9b7-d8f7-43e6-9ab3-7eff6a83108e)
