### ISSUE TITLE
Panel Filter / Collections cuts collection labels making them not readable

### ISSUE THREAD

**Issue by fabiobeoni** [bitwarden/clients#3293]
### Steps To Reproduce

1. Create a Collection with about 20 characters (uppercase)
2. Go back to Vault / Filter Panel / Collections

### Expected Result

Read the full label name

### Actual Result

Collection label shows dots.... (see screenshot)

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16882089/184308033-78b95826-6c59-4794-9a86-e8413e9cc7e6.png)

### Additional Context

It happens on web, desktop clients.

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Firefox, Brave

### Build Version

2022.8.1

**Comment by djsmith85** [comment]
@fabiobeoni Thank you again for your report.

Closing this now, as Desktop got addressed with #5131 and web with the rewrite of the vault-filters.

Kind regards,
Daniel
