### ISSUE TITLE
[Chrome extension] Clear search button has poor visibility

### ISSUE THREAD

**Issue by bhajneet** [bitwarden/clients#3299]
### Steps To Reproduce

<img width="373" alt="image" src="https://user-images.githubusercontent.com/14130567/184500707-56601170-f376-43b6-bb02-7d253b49a913.png">

### Expected Result

An easier to see "x" for clearing search

### Actual Result

A different shaded x blue on blue

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2022.8.0

**Comment by djsmith85** [comment]
Confirming this behaviour for the browser extension. For the the desktop-client this got resolved with https://github.com/bitwarden/clients/pull/2639

**Comment by scottmondo** [comment]
Hi :) Is this still available to be picked up?

**Comment by djsmith85** [comment]
@scottmondo As long as no PR is attached that would close this, it's up for grabs.

**Comment by scottmondo** [comment]
@djsmith85 Thank you :) I've added a pr https://github.com/bitwarden/clients/pull/3876
