### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by cloudcome** [bitwarden/clients#3309]
### Steps To Reproduce

点击登录

### Expected Result

登录成功

### Actual Result

![image](https://user-images.githubusercontent.com/3362033/184572217-8e226199-da15-48b3-bfe7-cf7312a9ab5e.png)

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2022.8.1

**Comment by dbosompem** [comment]
Hi @cloudcome, could you please try again and confirm if issue still persist? Should be fine now

**Comment by cloudcome** [comment]
上周已经成功登录了，可能是网络问题
