### ISSUE TITLE
Safari Extension: Clicking "Premium Membership" hangs the extension

### ISSUE THREAD

**Issue by cunneen** [bitwarden/clients#3314]
### Steps To Reproduce

In the safari extension toolbar icon

1. Go to 'Settings'
2. Click on 'Premium Membership'

The extension hangs, only fixable by a browser restart.

Version: 2022.5.0

### Expected Result

Premium membership information should display

### Actual Result

The extension hangs

### Screenshots or Videos

https://user-images.githubusercontent.com/1751645/184784269-4f95e7e2-8480-4959-9c26-ab333239bcef.mov

### Operating System

macOS

### Operating System Version

12.2.1

### Web Browser

Safari

### Browser Version

15.3 (17612.4.9.1.8)

### Build Version

2022.5.0

**Comment by djsmith85** [comment]
Hi @cunneen and thank you for your report.

This has previously been reported and is being tracked with https://github.com/bitwarden/clients/issues/2267.

Closing this as duplicate.
