### ISSUE TITLE
When the name of an entry is too long, the Icon indicating it is shared is not shown

### ISSUE THREAD

**Issue by gabrielfin** [bitwarden/clients#3322]
### Steps To Reproduce

1. Create an entry with a long name and add it to any collection
2. Go to where that entry is listed (for example, search for it or access the collection)

### Expected Result

The name of the entry should be truncated with a "...", and there should also be a visible icon (a little square) to the right of the name indicating that that item is shared. 

### Actual Result

The name is truncated with "..." but no icon is shown

### Screenshots or Videos

All of these entries are in a collection. Notice that the first and fourth ones don't have the "shared" icon because their names are too long.

![2022-08-16_19-54](https://user-images.githubusercontent.com/787075/184999523-30255d39-6651-456a-9f76-fcc83f01d91e.png)

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2022.08.0

**Comment by rdaugherty** [comment]
Hi @gabrielfin. Thank you for bringing this to our attention! We have confirmed the behavior and will send this issue to our development team for a fix.

**Comment by federicom09** [comment]
Hello @gabrielfin, how are you?

This issue is already fixed, you can find the PR below:
https://github.com/bitwarden/clients/pull/3500

Thanks again for reporting this!
