### ISSUE TITLE
add password/object expiration feature

### ISSUE THREAD

**Issue by AndrewtheCanon** [bitwarden/clients#3343]
### Steps To Reproduce

just check the various fields in bitwarden.

### Expected Result

It would be very helpful to have a password or other object expiration field in the different clients. Some of the other clients do have this feature.

### Actual Result

Password expiration doesnt happen.

### Operating System

Windows

### Web Browser

Microsoft Edge

### Build Version

11

**Comment by dwbit** [comment]
Hey @AndrewtheCanon closing this one for now as there is an open feature request for voting and discussion here: https://community.bitwarden.com/t/password-expiration-date/162

If you're referring to something else, let me know!
