### ISSUE TITLE
Search does not cover the Description

### ISSUE THREAD

**Issue by DeflateAwning** [bitwarden/clients#3348]
### Steps To Reproduce

1. Create a password entry with a title, username, password, etc. Make the description something like "hello word, it's me, margret". Make sure the title, UN, PW doesn't include "margret". 
2. Save entry.
3. Search for "margret" with the main search.
4. See no results.

### Expected Result

In the Step 3 search, I would expect to see a search result for the entry created in Step 1.

### Actual Result

Per Step 4, no search results are shown.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Vivaldi

### Browser Version

All versions in 2022

### Build Version

2022.8.0

**Comment by aj-bw** [comment]
Hi @DeflateAwning, thanks for reaching out.

I was unable to reproduce this bug on Vivaldi across multiple operating systems. I created a vault item with the parameters you described, with the Notes field including `margret` and was able to type `margret` into the search field and return the test login item created.

Our browser extension does support full-text search, which includes the Notes field of login items. More can be here: https://bitwarden.com/help/searching-vault/#full-text-search

If you need further assistance, please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content.

**Comment by DeflateAwning** [comment]
You're correct. I didn't actually test my repro case, but based it on what I thought I was experiencing. I've updated my repro below. 

## Steps To Reproduce
1. Create a password entry with a title, username, password, etc. Make the ~~description~~ *Notes section* something like "hello word, it's me, margret". Make sure the title, UN, PW doesn't include "margret".
2 Save entry.
3. Search for "argret" with the main search (without the letter 'm')
4. See no results.
