### ISSUE TITLE
Password History by View menu is empty

### ISSUE THREAD

**Issue by millecentdix** [bitwarden/clients#3351]
### Steps To Reproduce

Hi,

1. Select an item
2. Password history indicate 2 passwords
3. Go to View Menu
4. Click on Password History

### Expected Result

Display password history

### Actual Result

Password History is empty

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/31278829/185789970-75ec3ff7-fa93-4858-9972-3953f828fc1d.png)

![image](https://user-images.githubusercontent.com/31278829/185789987-184f7628-3abc-4f4f-ad0c-1d0232d73bab.png)

Click on number 2 of password history :
![image](https://user-images.githubusercontent.com/31278829/185790083-9a4d62c5-dfbb-48dd-9a37-3ea25311161f.png)

### Operating System

macOS

### Operating System Version

10.13.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.8.1 (4085)

**Comment by bnagawiecki** [comment]
Hey @millecentdix,

Thanks for submitting this issue!

I was able to replicate it on my end. I'll raise this internally for prioritization.

**Comment by latetedemelon** [comment]
I've found this issue on the windows client, chrome plugin, and IOS app.  It seems to be prevalent across all platforms.

**Comment by millecentdix** [comment]
Hi,
A little UP to say that the bug is still present in Version 2023.3.1 (7892).

**Comment by emiliocacayoren** [comment]
Was this ever fixed? I still see the issue on Version 2024.7.1

**Comment by djsmith85** [comment]
The reason for this, is that these are 2 separate histories.

- Opening via the desktop's view menu is a general generator history. This only contains passwords generated by the generator also accessed via the view menu.
- The other history is item-specific, which contains the previous passwords of the currently viewed item.

Closing this, as it is behaving as expected.

Kind regards,
Daniel
