### ISSUE TITLE
The Exposed Passwords Report in the Vault Health Reports inside the Web Vault is stuck showing a spinning loading circle.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#3364]
### Steps To Reproduce

1. Log into your Bitwarden account via the Web Vault (https://vault.bitwarden.com/#/).
2. Access the Vault Health Reports.
3. Open and run the Exposed Passwords Report.

### Expected Result

To display results.

### Actual Result

The (Check Exposed Passwords) button shows a spinning circle indicating that it is loading, but no results are displayed.

### Screenshots or Videos

Internal.

### Additional Context

N/A.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 21H2.

### Web Browser

Firefox

### Browser Version

103.0.2.

### Build Version

2022.8.1.

**Comment by bnagawiecki** [comment]
Hey @SergeantConfused,

Thanks for submitting this!

I believe this was a momentary issue and has since been resolved. Can you check to see if this is still occurring for you?

**Comment by bitdryvr** [comment]
It is now about a year later and I am having this hang now. ChromeOS 116.

What was the nature of the temporary issue back then?
