### ISSUE TITLE
No way to clear currently displayed entry

### ISSUE THREAD

**Issue by MichaelKing1832** [bitwarden/clients#3367]
### Steps To Reproduce

After viewing an entry, there is no way to clear the display of the current entry other than exiting the app or displaying a new entry instead.

This is a critical design/usability issue - after viewing an entry, there should be some way for the user to control clearing the current entry to prevent inadvertent (unauthorized) viewing.

I strongly suggest:

1. There be a menu entry to clear the current displayed entry
2. Clearing the search bar (clicking on the "X") -or- deleting its contents (i.e. the current search term is the empty string) shall clear the current displayed entry.

I am surprised that this hasn't been noticed before. I only noticed it because I minimized BW after use and then several minutes later when I re-opened it to access another site, the old info was still being displayed.

At least the "visibility" flag was reset and card numbers and passwords were masked. The entry is cleared when the vault is locked or when you exit the app.

However, the notes were still clearly visible and accessible, long after several actions should have cleared the display and removed access to the entry. Many people store backup one-time passwords and security question information in the Notes area which is always displayed for all entries.

Not cool.

### Expected Result

After minimizing the app, the currently displayed entry should be cleared. If you need the entry again, the search term should still remain in the search bar to easily be selected and pulled up again.

**After clearing the search bar (the "X" or deleting the search string), the currently displayed entry should be cleared.**

After performing any search, the currently displayed entry should be cleared, whether there are any search results or not.

There should be a user-accessible mechanism to initiate a manual clearing of the currently displayed entry to remove sensitive information from my screen - not by BW forcing me to disclose some other entry's information in its place!

### Actual Result

The displayed entry can only be replaced by another entry. 
It cannot be cleared to a blank display, such as upon initial launch of the app or by locking the vault.

### Screenshots or Videos

Starting view (empty entry display)
![BW-1-blank-entry-2022-08-23](https://user-images.githubusercontent.com/50266989/186270844-e68f5c3f-2ead-474b-8dcb-fd7071a24bc5.png)
Viewing entry
![BW-2-viewed-entry-2022-08-23](https://user-images.githubusercontent.com/50266989/186270889-d8aee30b-7d65-4716-a22a-5d9141124d17.png)
Clearing search
![BW-3-cleared-search-entry-2022-08-23](https://user-images.githubusercontent.com/50266989/186270917-106d4ac4-7c6a-4b1d-abc4-57db6e8e9bed.png)
Searching for no matches
![BW-4-nomatch-search-entry-2022-08-23](https://user-images.githubusercontent.com/50266989/186270976-52205326-ee70-4a37-a1e3-95678d5aa3ea.png)
Searching with different terms and matches
![BW-5-diffmatch-search-entry-2022-08-23](https://user-images.githubusercontent.com/50266989/186271039-196a519e-0ddf-410f-9005-d92fea7f25ba.png)

### Operating System

Windows

### Operating System Version

Win10x64 21H2 (Build 19044.1889)

### Installation method

Microsoft Store

### Build Version

App Version 2022.08.01, Shell 19.0.8, Renderer 102.0.5005.148, Node 16.14.2, Arch x64.

**Comment by Maltavius** [comment]
Came here to report this bug today also. There needs to be a "Close this entry" Button besides the Edit and Trash buttons

**Comment by MichaelKing1832** [comment]
Came here to check 2 years later, and it seems nobody at Bitwarden has an understanding of operational security, despite the perpetual slathering of "least privilege" buzzwords in presentations.

Leaving sensitive information displayed for all to see (shoulder surfing is still a thing) is definitely not "leaning into" "least privilege" principles, or demonstrating mastery of operational security practices.

Does anyone at Bitwarden read these? Or is it just a popularity contest with clickbait to get votes, have millions of followers on social media, or "knowing somebody" to get a simple defect fixed?

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by Maltavius** [comment]
This is a UX Bug not a Feature Request.
