### ISSUE TITLE
Browser/Desktop/Web: Accessibility - focus lost/reset when generating new "Username" 

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/clients#3400]
### Steps To Reproduce

1. Go to the Generator
2. Select "Username" for the type of thing to generate
3. Use keyboard (`Tab` / `Shift+Tab`) to set focus to the generate/regenerate control
4. Activate the control

### Expected Result

Once the new username has been generated, focus should remain on the generate/regenerate control.

### Actual Result

Focus seems to be lost - it does not remain on the actual control. It doesn't reset to the start of the page/document/view, but this may just be down to browser heuristics trying to salvage the situation.

### Screenshots or Videos

Video in Chrome with the browser popup, showing keystrokes. Note how for generating "Password"s, this works perfectly - focus remains on the control, and we can just keep pressing `Enter`. Changing to "Username", however, after each generated username, focus is lost and we need to tab to the next or previous control and back to set focus on it again.

https://user-images.githubusercontent.com/895831/187052975-f45e21ef-e3df-437c-aad7-42d917b3fd81.mp4

This also happens in the desktop application, and on the web vault as well.

https://user-images.githubusercontent.com/895831/187052993-195af5ea-3fe3-4d48-8698-a66285d39d43.mp4

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2022.8.0 (browser) / 2022.8.1 (desktop and web)

**Comment by bnagawiecki** [comment]
Hey @patrickhlauke, 

Just to add some more info from what I saw:

Browser (2022.8.0): When testing on Chrome (104.0) and Firefox (Windows and Mac) myself, both password and username generators behave the same--once I generate using the keyboard, it loses focus of the generate button.

Web: On Chrome, I am getting the behavior you describe. But when I perform the same tests on Firefox, everything behaves fine.

Desktop: Behavior is as you described.

Not sure what explains the discrepancies in the Chrome extension, but wanted to note it.

**Comment by patrickhlauke** [comment]
@bnagawiecki thanks for your check on this.

> Browser (2022.8.0): When testing on Chrome (104.0) and Firefox (Windows and Mac) myself, both password and username generators behave the same--once I generate using the keyboard, it loses focus of the generate button.

I should have been a bit more specific here: I was testing what nominally is 2022.8.0, but using the latest `master` branch (where some of the more general focus loss issues have already been addressed by removing `appClickBlur`). the distributed public 2022.8.0 still has that issue even for the password generator.

> Web: On Chrome, I am getting the behavior you describe. But when I perform the same tests on Firefox, everything behaves fine.

I believe this is a heuristic behavior of Firefox - even though the control is temporarily set to disabled and then enabled again, Firefox manages to "latch on" back to that control. Chrome, on the other hand, loses its grip on it as soon as it's set to disabled for a microsecond.

In any case, my PR here https://github.com/bitwarden/clients/pull/3405 should fix it for all browsers https://github.com/bitwarden/clients/pull/3405
