### ISSUE TITLE
Safari auto-fill menu doesn't update site after first unlock

### ISSUE THREAD

**Issue by desbo** [bitwarden/clients#3403]
### Steps To Reproduce

1. Open a new Safari window with Bitwarden signed out
2. Browse to the login page of a site  with an entry in the Bitwarden vault
3. Right click on the username field > Bitwarden > Auto-fill > Unlock your vault
4. Unlock vault, auto-fill and login 
5. Browse to a different site and use the auto-fill right click menu

The entry for the site from step 2, not the current one, will be in the prompt, and this remains while browsing to other sites.

### Expected Result

The entry for the currently viewed site will be shown in the auto-fill menu. 

### Actual Result

When the vault is first unlocked through the auto-fill menu, the menu will always show whatever site was being viewed at this point for the rest of the session. 

### Operating System

macOS

### Operating System Version

12.4

### Web Browser

Safari

### Browser Version

15.5 (17613.2.7.1.8)

### Build Version

2022.8.0

**Comment by bnagawiecki** [comment]
Hey @desbo,

Thanks for submitting this issue!

I have attempted to replicate this behavior on my end but am not able to. Is there any additional information you can provide that might help us replicate?

**Comment by desbo** [comment]
Hi @bnagawiecki, thanks for the reply. I'd be happy to submit a screen recording showing this bug, but as this would involve slightly personal data (e.g. showing my vault entries), would it be possible to submit this privately?

**Comment by Larry-Sussman** [comment]
Hi @desbo, is this still occurring on the latest Safari extension [Browser v2022.10.1](https://github.com/bitwarden/clients/releases/tag/browser-v2022.10.1)? I was also unable to reproduce this on the latest Safari extension. 

If so, this may be better handled by our dedicated Customer Success team.
Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content. If it's consistently reproducible across sites, you may try creating a screen recording with two sites that you don't use, with fake test credentials for privacy. 

I hope this helps!

**Comment by desbo** [comment]
Hi @Larry-Sussman, thanks for the reply. Confirming this issue has been resolved in 2022.10.1. Thanks!
