### ISSUE TITLE
Desktop app does not start hangs on loading bar

### ISSUE THREAD

**Issue by Jamarilo** [bitwarden/clients#3411]
### Steps To Reproduce

Launch Bitwarde desktop app, the loading bar appears but does not go away.

### Expected Result

See the login page

### Actual Result

loading bar does not disappear

### Screenshots or Videos

![Bildschirmfoto 2022-08-29 um 13 46 23](https://user-images.githubusercontent.com/12269709/187194120-105ea390-b885-4e8d-be95-20d176a2b1ce.png)

### Additional Context

i have turned on the developer mode and i see the following error messages which can also be seen in the screenshot.

### Operating System

macOS

### Operating System Version

12.5.1

### Installation method

Mac App Store

### Build Version

2022.8.1

**Comment by vphan916** [comment]
Hey @Jamarilo, hope all is well.  Can you install our latest version and let us know if this problem persist?  Thank you!

**Comment by Jamarilo** [comment]
> Hey @Jamarilo, hope all is well. Can you install our latest version and let us know if this problem persist? Thank you!
Hi @vphan916  thank you all is well. The issue is gone after i did a clean install on my mac, i will close this issue.
