### ISSUE TITLE
Auto-fill: not working for https://app.slack.com/workspace-signin

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#3412]
### Steps To Reproduce

1. Go to 'https://app.slack.com/workspace-signin'
2. Right-click inside text-box
3. Select 'Bitwarden' --> 'Copy Custom Field Name' to copy the name of the custom field to Auto-fill
4. Click on 'Bitwarden' icon on the extension toolbar
5. Click '+' (top right)
6. Scroll down to 'CUSTOM FIELDS'
7. Click 'New custom field' (ensure type 'Text' is selected)
8. Into the 'Name' box, paste the copied custom field name
9. Into the 'Value' box, type the desired text to be inserted into the above named custom field
10. Click 'Save'

Now try using 'Ctrl-Shift + L' to activate Auto-fill - does it work?

It either doesn't work at all, or sporadically works with no discernible pattern leading up to it working.

### Expected Result

When visiting a website with a custom field, using keyboard shortcut 'Ctrl-Shift + L' should Auto-fill the custom field from the associated login profile from Bitwarden

### Actual Result

Nothing, or sporadically it works under uncertain conditions.

### Screenshots or Videos

N/A

### Additional Context

When it does work, multiple (cloned logins from a working login) variants are not rotated through upon each successive use of 'Ctrl-Shift + L' keyboard shortcut.

<details><summary>Inspector details</summary>
<p>

```
<input data-qa="signin_domain_input" spellcheck="false" min="0" max="0" aria-describedby="domain_hint" aria-invalid="true" aria-labelledby="domain_label domain_error" aria-required="false" aria-label="" autocomplete="off" class="c-input_text c-input_text--large c-input_text--with_error c-input_text--with_inline_alert c-input_text--with_error full_width margin_bottom_0" id="domain" name="domain" placeholder="your-workspace" type="text" value="" data-com.bitwarden.browser.user-edited="yes" width="0">
```

</p>
</details>

---

**UPDATE:**
Further testing seems to reveal some consistency after an apparent trigger-point, which seems to be set after doing one of the below actions;
* Use/Edit/Save/Add a login for the current URL and then use 'Ctrl-Shift + L' - it works for that specific login
* Subsequent Use/Edit/Save/Add a login for current URL seems to enable the use 'Ctrl-Shift + L' - it works for that additional login, but confusingly not any login that may already exist.

It seems as though Use/Edit/Save/Add of a login "activates" it for consideration when using 'Ctrl-Shift + L'

Interestingly there is NO looping back to the first login, there seems to be a hard STOP once the last login is reached - although upon reloading the page, you can loop through the "activated" entries ONCE more.

---

### Operating System

Linux

### Operating System Version

Linux 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022

### Web Browser

Chrome (Chromium), Firefox

### Build Version

Chromium: 104.0.5112.101 (Official Build) for Linux Mint (64-bit)
Firefox: Mozilla Firefox for Linux Mint mint-001 - 1.0 Firefox:104.0 (64-bit)

**Comment by Larry-Sussman** [comment]
Hi @DavidPesticcio, I'm not able to reproduce this on my end, are you still running into this issue?

I have a question about what you're seeing on Step 3: 
> Select 'Bitwarden' --> 'Copy Custom Field Name' to copy the name of the custom field to Auto-fill

On Chrome and Firefox, the custom field name is `domain`, is this what you're seeing too?

From testing on Safari, when I right-click the "your-workspace.slack.com" field and copy the custom field name, this is what's saved to the clipboard:
`Unable to identify a valid form element. Try inspecting the HTML instead.`

I wonder if this is a result of the browser not identifying the field correctly. In my experience, I've been able to cycle through multiple logins using that custom field without issue.

**Comment by DavidPesticcio** [comment]
Hi @Larry-Sussman - appologies for missing your reply...

> I have a question about what you're seeing on Step 3:
> 
> > Select 'Bitwarden' --> 'Copy Custom Field Name' to copy the name of the custom field to Auto-fill
> 
> On Chrome and Firefox, the custom field name is `domain`, is this what you're seeing too?

Yes I see `domain`

> From testing on Safari, when I right-click the "your-workspace.slack.com" field and copy the custom field name, this is what's saved to the clipboard: `Unable to identify a valid form element. Try inspecting the HTML instead.`

I don't use Safari, but I suspect that may be another issue not necessarily related to Bitwarden..

> I wonder if this is a result of the browser not identifying the field correctly. In my experience, I've been able to cycle through multiple logins using that custom field without issue.

I can cycle through logins on other websites just fine, although the starting point in the cycle seems to be random/weighted, but not on the page mentioned above until I have used the `Auto-fill` from the Bitwarden extension first, then it (and future other credentials) appears to be added to the list. :confused:

**Comment by DavidPesticcio** [comment]
Hi @Larry-Sussman, could you please re-open this issue and see my reply above. Thanks.

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.  If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
