### ISSUE TITLE
Check For Updates link directs to outdated page

### ISSUE THREAD

**Issue by secondl1ght** [bitwarden/clients#3423]
### Steps To Reproduce

1. Open desktop app
2. Click Help in top nav
3. Click Check For Updates

### Expected Result

This link directs to the latest stable release.

### Actual Result

This link directs to an outdated repo: https://github.com/bitwarden/desktop/releases

### Operating System

Linux

### Installation method

Other

### Build Version

2022.8.1

**Comment by proton-byte** [comment]
Should already be fixed by this (merged) pull request: https://github.com/bitwarden/clients/pull/3352 :thumbsup:

**Comment by djsmith85** [comment]
@secondl1ght Thank you for the report but as mentioned by @proton-byte this has already been fixed. Thanks again for the fix @proton-byte.

Closing this now.
