### ISSUE TITLE
Clicking on premium membership makes the extension crash on safari

### ISSUE THREAD

**Issue by lachrist** [bitwarden/clients#3426]
### Steps To Reproduce

cf screen shot

### Expected Result

not crashing?

### Actual Result

crashing (reproducible)

### Screenshots or Videos

<img width="1392" alt="Screenshot 2022-09-01 at 14 30 36" src="https://user-images.githubusercontent.com/5468597/187914150-3e48fcf4-5443-447b-bed1-5276f42b0c9a.png">

<img width="1392" alt="Screenshot 2022-09-01 at 14 33 01" src="https://user-images.githubusercontent.com/5468597/187914549-5221658b-8b77-4291-8755-dba45c0cb6a4.png">

### Operating System

macOS

### Operating System Version

10.15.7

### Web Browser

Safari

### Browser Version

15613.2.7.1.9

### Build Version

2022.8.0

**Comment by bnagawiecki** [comment]
Hey @lachrist,

Thanks so much for reporting this.

This has previously been reported and is being tracked with #2267.

Closing this one as a duplicate.
