### ISSUE TITLE
2 reddit accounts, EXACT same URI, and 2 different icons !

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#3437]
### Steps To Reproduce

1. Create entry a 1st login entry for Reddit like this:
![image](https://user-images.githubusercontent.com/98819304/188153482-eabc00a0-9c2f-4929-9e06-20660cea9b9f.png)
With the setting:
![image](https://user-images.githubusercontent.com/98819304/188154118-934649b7-45d0-40f7-8717-47d6b14d7823.png)

2. Create a 2nd login entry for Reddit like this:
![image](https://user-images.githubusercontent.com/98819304/188153718-7fa4e2cf-4f17-42ea-869d-23e673e83cef.png)
With the setting: 
![image](https://user-images.githubusercontent.com/98819304/188154087-5f29cd78-7788-4a8e-b769-2cfe5d63dc62.png)

3. Search for Reddit in the search box:
![image](https://user-images.githubusercontent.com/98819304/188153957-3c185fe8-1511-4c6f-929a-7b33fd222e12.png)

### Expected Result

They both should have the same icon.

### Actual Result

They have both different icons !

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.8.1

**Comment by mphelp** [comment]
@oeloo Wasn't able to reproduce on desktop. Is this the browser extension?

**Comment by oeloo** [comment]
The problem is in BOTH the browser and BW destop app .
This problem is even there on BW Android app.

Maybe it is because you have created them one after the other. On my side I have created the 2 Reddit entry with a one month interval. Any way there is still an issues how this favicon is handle inside BW.
