### ISSUE TITLE
Context Menu Displays Wrong Login Information

### ISSUE THREAD

**Issue by 7AvbOEZM9xEvXdN** [bitwarden/clients#3443]
### Steps To Reproduce

1. Open a browser window, login to Bitwarden extension (if you aren't already), and navigate to the login page of a website for which credentials are stored in Bitwarden. Do not login to the website or do anything except navigate to the login page.
2. Open a second browser window and navigate to a second website for which you have saved credentials in Bitwarden. You do not need to login.
3. Go back to the first browser window and right click on the field to be filled on first website, select Bitwarden, and Auto-fill. 

### Expected Result

Auto-fill should show the login information for the first website. 

### Actual Result

Auto-fill shows the login information for the second website.

### Additional Context

I've noticed the problem for a number of months now and just haven't gotten around to reporting it until now. I suspect the problem is present in Chrome as well since Edge and Chrome are both based on Chromium.

This bug is especially apparent when using PWAs because the context menu will always show the wrong login information unless I refresh the PWA app before logging in. For example, I have certain websites installed as PWAs, which I open in separate windows. Logging in with the context menu is annoying because of this bug.

### Operating System

Windows

### Operating System Version

11 21H2 (OS build 22000.918)

### Web Browser

Microsoft Edge

### Browser Version

105.0.1343.23 (Official build) beta (64-bit)

### Build Version

2022.8.0

**Comment by federicom09** [comment]
Hello @7AvbOEZM9xEvXdN, how are you?

Thank you for reporting this! 
We were able to reproduce the issue and we created a ticket in our internal bug-tracking system.

Hopefully this is going to be fixed soon.

Thanks!

**Comment by andyshultz** [comment]
Any updates on this? I noticed the same behavior today on Chrome. Interestingly, the context menu is wrong but the toolbar menu is correct. Refreshing the page corrects the context menu.

**Comment by mhenstell** [comment]
Still having this issue. I've got lots of tabs open and BW seems to guess which credentials I want in the context menu incorrectly maybe 20% of the time. I'm very often seeing autofill suggestions for websites other than the one in the active tab.
