### ISSUE TITLE
Selfhosted anonaddy not working

### ISSUE THREAD

**Issue by praptoumache** [bitwarden/clients#3458]
### Steps To Reproduce

1. Go to 'Generator'
2. Click on 'username'
3. Scroll down to 'Options'
4. Click on 'Forwarded Email Alias'
5. Select Anonaddy
6. fill with custom domain name and add api token.
7. try to generate username

### Expected Result

selfhosted anonaddy should be usable

### Actual Result

Error occured

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/57391596/188856748-be68b3fc-4ff6-41e1-8ff1-cc58b8222268.png)

### Additional Context

I'd like to connect my selfhosted anonaddy but found that it is not implemented yet.
https://github.com/anonaddy/anonaddy/issues/313

i'd love to see a feature like that!

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox, Brave

### Build Version

2022.8.0

**Comment by ddanielyan** [comment]
@praptoumache  - Hi, Can you try checking that your Domain name is set to anonaddy.me, you are using the correct API Key, and that you have available alias on AnonAddy? If you're using a free AnonAddy account the max that you can have is 5

**Comment by praptoumache** [comment]
> 

Its a selfhosted instance of anonaddy. so there is no anonaddy.me to use

**Comment by dwbit** [comment]
Thanks for the feedback @praptoumache! Closing this one out as we have an [open feature request here](https://community.bitwarden.com/t/custom-api-url-for-self-hosted-email-alias-services/42185) for voting and discussion on the community forums.
