### ISSUE TITLE
Login denied on Chrome Browser extension, but not via MacOS App

### ISSUE THREAD

**Issue by timfea926** [bitwarden/clients#3480]
### Steps To Reproduce

Login denied on the Chrome 105.0.5195.102 using MacOS 12.5.1. Was working as of yesterday, 9/8/22. Was able to login just fine using the exact same credentials through your MacOS app version 2022.8.1 (4085). 

### Expected Result

Expected result was to be able to login after entering my login credentials via browser extension. 

### Actual Result

![Screen Shot 2022-09-09 at 10 01 02 AM](https://user-images.githubusercontent.com/50429353/189405060-27cd91a0-f84d-418d-a6cd-a2a87d34686d.png)

### Screenshots or Videos
![Screen Shot 2022-09-09 at 10 01 02 AM](https://user-images.githubusercontent.com/50429353/189405120-1422175b-64ba-4a34-bdab-552da0c60391.png)

### Operating System

macOS

### Operating System Version

12.5.1

### Web Browser

Chrome

### Browser Version

105.0.5195.102

### Build Version

 (Official Build) (arm64)

**Comment by djsmith85** [comment]
Hi @timfea926, 

we had some issues with Intermittent Access in the past 2 hours. The status of our services can always be monitored at https://status.bitwarden.com/

All should be up and working and I'm sorry for any inconveniences this might have caused.

I'm closing this now, but please feel free to comment/re-open if it is still not working for you.

Kind regards,
Daniel
