### ISSUE TITLE
NixOS: Selecting a folder for a new login entry to be in results in the window being closed while the list of folders persist

### ISSUE THREAD

**Issue by itslychee** [bitwarden/clients#3489]
### Steps To Reproduce

1. Use https://github.com/itslychee/dotfiles nixos config
2. Create a new login and click on the selection list that displays the list of folders
3. The window that had the login entries is gone, but the list of folders is still there

### Expected Result

I expected the parent window/node/whatever to persist in order to create a new login entry to my vault.

### Actual Result

The parent window closes but I am stuck with the selection list of folder names

### Screenshots or Videos

Demo:
https://user-images.githubusercontent.com/82718618/189556171-bc2c2961-76aa-4f65-946a-1724397cc89c.mp4

### Operating System

Linux

### Operating System Version

NixOS

### Web Browser

Firefox

### Browser Version

Mozilla Firefox 104.0.2

### Build Version

2022.8.0

**Comment by Hinton** [comment]
Hi @itslychee,

That functionality is a standard select element, which means this seems to be a browser defect and not something that can be solved on our end.

This can either be a defect in Firefox, or some patches that the linux distribution applies. From your dotfiles it seems you are using wayland which has historically had a lot of bugs. Have you tried using the wayland specific builds described on https://nixos.wiki/wiki/Firefox?

**Comment by itslychee** [comment]
yes I have tried using those, but they resulted in the same bug. Thanks for your input!
