### ISSUE TITLE
Missed translation for month in Card menu wizard

### ISSUE THREAD

**Issue by FadeMind** [bitwarden/clients#3491]
### Steps To Reproduce

1. Add new entry to vault.
2. Select Card form.
3. Click month,
4. In Polish language September (Wrzesień in Polish) is not translated. 

### Expected Result

All months are properly translated to Polish language.

### Actual Result

Missing September (Wrzesień in Polish)

### Screenshots or Videos

![20220912-1662987966](https://user-images.githubusercontent.com/9846948/189663145-85fcd764-43bb-457b-9b7c-8f49c69a38ee.png)

### Operating System

Windows

### Operating System Version

11 22622.590

### Web Browser

Firefox

### Browser Version

105.0b9

### Build Version

2022.8.0

**Comment by djsmith85** [comment]
Hi @FadeMind

We use a translation tool called Crowdin to help manage our localization efforts across many different languages. Our translations can only be updated using Crowdin.

If you are interested in helping translate a Bitwarden client into another language (or make a translation correction), please register an account at Crowdin and join our project here: https://crowdin.com/project/bitwarden-browser

If the language that you are interested in translating is not already listed, create a new account on Crowdin, join the project, and contact the project managers.

You can read Crowdin's getting started guide for translators here: https://support.crowdin.com/crowdin-intro/

If the translations on Crowdin do not match the translations on Github, please let us know and we will investigate.
