### ISSUE TITLE
Windows client: auto-update should not create dialog box

### ISSUE THREAD

**Issue by bhughes339** [bitwarden/clients#3497]
### Steps To Reproduce

1. Wait for Bitwarden to auto-update

### Expected Result

A Windows notification, etc

### Actual Result

A dialog box appears and steals focus from the user

### Additional Context

Unexpected dialog box creation is an atrocious design that is very non-user friendly. Please consider using the Windows notification system or another method of silent updating.

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.9.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by kvanska** [comment]
This is very annoying. When opening bitwarden and starting to write login credentials, a popup appears and steals the focus. If you're typing too fast and press Enter, update process starts.

**Comment by Hinton** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/2608
