### ISSUE TITLE
Desktop App cannot display TOTP codes

### ISSUE THREAD

**Issue by azulskyknight** [bitwarden/clients#3499]
### Steps To Reproduce

Upgrade to Desktop v2022.9.0

Login to vault
Own a Family 2019 subscription
Select a password with TOTP in the family organization
Get told to buy premium

### Expected Result

I expect to see my TOTP codes as I have for years.

### Actual Result

I'm told to buy premium.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/45128329/189761594-5904eefb-3323-4a5e-9659-157441998075.png)
![image](https://user-images.githubusercontent.com/45128329/189761760-c4513a9d-5ea7-4dcc-8677-82595259c9f5.png)

### Additional Context

Downgrading to 2022.8.1 solves the problem.
This issue also seems to impact the website vault.bitwarden.com as it's no longer creating codes either.
I assume the .9 release of my browser plugins will do the same thing when the time comes, but those are all still on .8.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.0

**Comment by nimajalali** [comment]
Also seeing this on Mac 12.3 Bitwarden Version 2022.9.0 with a Teams Organization subscription.

**Comment by Larry-Sussman** [comment]
Thanks for the report, @azulskyknight and @nimajalali! We have addressed this in #3509 and I've confirmed that the latest release of [Desktop v2022.9.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2022.9.1) resolves this issue for 2019 Organization Owners and Users. Please let me know if you run into any issues on the latest update. 😄

**Comment by nimajalali** [comment]
@Larry-Sussman Confirmed on my end as well. v2022.9.1 fixes the issue. Thanks!
