### ISSUE TITLE
Uncaught SyntxError: Unexpected token .

### ISSUE THREAD

**Issue by axk4545** [bitwarden/clients#3501]
### Steps To Reproduce

1. Go to  vault.bitwarden.com 

### Expected Result

The web vault login screen appears.

### Actual Result

The Bitwarden logo appears but the login form never loads.

### Screenshots or Videos

![Screenshot 2022-09-12 at 6 53 50 PM](https://user-images.githubusercontent.com/3486252/189773575-bb2ad8a7-7205-4f2d-bc06-be9675b15f6a.png)

### Additional Context

I have also had a similar issue with elements of the page not loading on

### Operating System

Linux

### Operating System Version

ChromeOS 76.0.3809.136

### Web Browser

Chrome

### Browser Version

76.0.3809.136

### Build Version

The page won't load enough to obtain this information.

**Comment by dbosompem** [comment]
@axk4545 can you confirm if this issue still persist at your end?

**Comment by axk4545** [comment]
I am still seeing this issue.

**Comment by axk4545** [comment]
Unfortunately I am unable to do that. Is there anything else I can do to
verify that it is caused by the old version of Chrome? I remember seeing
the same issue on another Chromebook that I think had a newer OS but I
don't remember what version it was.

**Comment by axk4545** [comment]
I just realized I didn't answer your first two questions. I am able to
access the web vault from other devices although I had issues earlier in
the week with some of the CSS not rendering on various browsers and
devices. The last time I remember being able to access the web vault
properly on that Chrome OS device was around September 5th although it
could have been a few days after that as well.

**Comment by vphan916** [comment]
Hi @axk4545!  Can you do a hard refresh on the page (ctrl + shift + r) and see if that helps?

**Comment by axk4545** [comment]
@vphan916 no luck.

**Comment by grit96** [comment]
I am seeing the same error on an older Chromebook (Chrome 76 - can no longer be updated).

**Comment by grit96** [comment]
It turns out optional chaining is not supported in Chrome 76 so websites using it without transpiling no longer work on these old devices that can't be updated :-(

**Comment by tom24** [comment]
I have the same issue and am also constrained by using an older chromebook that can no longer be updated.  The chrome os version is 75.0.3770.144.

**Comment by Krychaz** [comment]
Hello there,

If you still experience this issue could you please update your Firefox version as mention here https://github.com/bitwarden/clients/issues/3829#issuecomment-1285146415

**Comment by axk4545** [comment]
Hello all,
I am moving away from Gmail. My new email address is ***@***.***
Please update any records, address books or contact lists as necessary to
reflect this.

Thank you.
Sincerely,

Aidan Kahrs
