### ISSUE TITLE
Microsoft Store Bitwarden client won't open after I enabled Hyper-V on Windows 11 22H2 / 22621

### ISSUE THREAD

**Issue by o-l-a-v** [bitwarden/clients#3503]
### Steps To Reproduce

Don't know if this reproduces the problem, but here is what I did.

* Installed Windows 11 22H2 / 22621.598.
* Installed Bitwarden from Microsoft Store, used it for weeks without problems.
* Enabled Hyper-V from "Turn Windows features on or off", rebooted.
* Created a VM with default switch.
* Now Bitwarden won't open when I start it.

In Event Viewer -> Windows Logs -> Application I get following two events.

<details><summary>Error event</summary>

```
Faulting application name: Bitwarden.exe, version: 2022.9.0.0, time stamp: 0x62c5b9aa
Faulting module name: desktop_native.win32-ia32-msvc.node, version: 0.0.0.0, time stamp: 0x62de8071
Exception code: 0xc0000005
Fault offset: 0x0001f4b9
Faulting process id: 0x0x7F3C
Faulting application start time: 0x0x1D8C7522AF318C7
Faulting application path: C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\Bitwarden.exe
Faulting module path: \\?\C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\resources\app.asar.unpacked\node_modules\@bitwarden\desktop-native\desktop_native.win32-ia32-msvc.node
Report Id: 7fcaa3cc-2544-4523-ba61-8461a063c7be
Faulting package full name: 8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
Faulting package-relative application ID: bitwardendesktop
```

</details>

<details><summary>Information event</summary>

```
Fault bucket 2116013822800497304, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: 8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
P2: praid:bitwardendesktop
P3: 2022.9.0.0
P4: 62c5b9aa
P5: desktop_native.win32-ia32-msvc.node
P6: 0.0.0.0
P7: 62de8071
P8: c0000005
P9: 0001f4b9
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.85fd6b39-1e0e-42c2-9b67-b871bec6b824.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5fba630d-0177-4f63-83a0-04d349744957.tmp.WERInternalMetadata.xml
WPR_initiated_DiagTrackMiniLogger_OneTrace_User_Logger_20220910_1_EC_0_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.871e000d-e16c-471b-a736-f17807c66680.tmp.etl
WPR_initiated_DiagTrackMiniLogger_WPR System Collector_inject.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.bf84b7ae-1a55-4df9-a900-83fd7168c0cb.tmp.etl
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.40cee474-f33b-44dc-8b94-f0741c438e29.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ce1c0a2c-810d-4de9-82f1-137bce8d976b.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.030cd043-806c-4010-b4b4-5b4507951d6b.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_8bitSolutionsLLC_6c4426e09ee348b2e871890271556ecf168f34_51e80f5f_cf9e4d61-e62d-4995-86f9-7dcd1accdd94

Analysis symbol: 
Rechecking for solution: 0
Report Id: 7fcaa3cc-2544-4523-ba61-8461a063c7be
Report Status: 268435456
Hashed bucket: 9bf40892f7e8c13aad5d975c57d70a98
Cab Guid: 0
```

</details>

### Expected Result

Bitwarden desktop client should run.

### Actual Result

Bitwarden desktop client never opens.

### Additional Context

Hardware info (that might be relevant):

* Dell Precision 5570
* Intel i7-12800H
* TPM and BitLocker: All good.
* OS: Windows 11 Enterprise, 22H2 / 22621.598.
* MDM: Azure AD joined and Intune controlled (not hybrid, cloud only)

What I've tried:

* Microsoft settings -> Apps -> Bitwarden: Reset
* Uninstall Bitwarden using Geek Uninstaller, reinstall with Microsoft Store.
* CMD as admin ```sfc /scannow``` found no errors.
* Rebooted PC again, tried BitWarden first thing, did not open.

Observations

* Portable version of v2022.8.1 and v2022.9.0 opens no problem.
* Installer version installed in user context (only thing I tried) works.

### Operating System

Windows

### Operating System Version

Windows 11 22H2 / 22621

### Installation method

Microsoft Store

### Build Version

2022.9.0.0

**Comment by peterbandi** [comment]
I have the exact same issue with the same error report (except some IDs in it). My Windows specifications are:
Edition: Windows 11 Pro
Version: 21H2
OS build: 22000.918
Experience: Windows Feature Experience Pack 1000.22000.918.0

Strangely enough it did work yesterday and I did not change anything in Windows. The only change is that the **KB2267602 (Version 1.375.287.0)** Definition Update has been installed.

**Comment by o-l-a-v** [comment]
Probably had nothing to do with Hyper-V, just that v2022.9.0 got pushed by Microsoft Store.
