### ISSUE TITLE
Windows Hello prompt hidden when Bitwarden is on minimized/tray mode

### ISSUE THREAD

**Issue by Hazmi35** [bitwarden/clients#3504]
### Steps To Reproduce

1. Enable browser integration in *Bitwarden Desktop*
2. Enable "Unlock with Biometrics" in Browser Extension
3. Lock the Browser extension vault
4. Put *Bitwarden Desktop* into minimized/tray mode
5. Unlock Browser extension vault with Biometrics

### Expected Result

Windows Hello prompt visible, even if *Bitwarden Desktop* is minimized or in tray mode

### Actual Result

Windows Hello prompt is hidden on version [Desktop v2022.9.0](https://github.com/bitwarden/clients/releases/tag/desktop-v2022.9.0), it will be available if you focus the *Bitwarden Desktop* application again (Unminimize or reopen it from tray)

### Additional Context

This does not happen with the previous release [Desktop v2022.8.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2022.8.1), only on [Desktop v2022.9.0](https://github.com/bitwarden/clients/releases/tag/desktop-v2022.9.0)

Currently using Windows 11, not sure if this also happens with Windows 10.

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.0

**Comment by papageno** [comment]
Same OS. Same version. Same issue here. Just about to post this issue. Thank you!

**Comment by AreiousX** [comment]
Same issue, can confirm it affects Windows 10 as well.

**Comment by pavelcheto** [comment]
Same OS. Same version. Same issue here. Rolled back to 2022.5, works fine.

**Comment by ClassicGOD** [comment]
Same issue here, rolling back to 2022.8.1 fixes the issue. 
The prompt appears in the background, under other windows. If only browser is opened initiating biometric unlock and minimizing the browser exposes the Windows Hello prompt. Authenticating with that prompt unlocks plugin as expected so the only issue seems to be window not popping up on top and getting focus.

**Comment by Onyx1640** [comment]
Same issue; Windows 10 and 11.

**Comment by dracula385** [comment]
I have the same issue. 

The desktop app is running in the tray. I am using Chrome and when I try to unlock the vault, my biometrics is not recognized. Windows hello dialogue pops up but until I click on the Windows hello prompt my biometrics are not recognized. 
It's like the focus does not switch on to the Windows hello dialogue. Once I click on Windows hello prompt then it can recognize my fingerprint. It is happening since 2022.09 on all of my 5 computers window windows 11

**Comment by DimitriosPi** [comment]
Anybody knows were we could find the previous version installer?

**Comment by davebowers01** [comment]
Same OS, same version, same issue.

**Comment by KenADev** [comment]
I experience the same issue, but additionally, the biometrics prompt does not detect my fingerprint anymore.

**Comment by floh96** [comment]
If you experience the same issue, please do not post on the thread, but give the issue a thumbs up so you are not pinging everyone on the thread.

**Comment by jeffi7** [comment]
This is still occurring.

Windows 10 21H2 build 19044.2130
Desktop app: 2022.10.0
Chrome extension: 2022.10.1

**Comment by pavelcheto** [comment]
How can this be not fixed still? It has been almost a year.

**Comment by JamesDBartlett3** [comment]
Still happening...

_**Operating System**_
OS Name: Microsoft Windows 11 Pro
OS Version: 10.0.26100 N/A Build 26100
OS Manufacturer: Microsoft Corporation
OS Configuration: Standalone Workstation
OS Build Type: Multiprocessor Free

_**Bitwarden Desktop**_
Version 2025.2.1
SDK 'main (6008e90)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64

_**Bitwarden Firefox Extension**_
Version: 2025.2.0
SDK: 'main (28c7e29)'
Server version: 2025.3.3

@Hinton, can we re-open this issue, please?

**Comment by masprodv1** [comment]
Issue is still occurring.

**Operating System**
Edition: Windows 11 Home
Version: 24H2
OS build: 26100.4202
Experience: Windows Feature Experience Pack 1000.26100.107.0


**Bitwarden Desktop**
Bitwarden Version: 2025.5.0
SDK 'main (c6835e5)'
Shell 34.0.0
Renderer: 132.0.6834.83
Node 20.18.1
Architecture x64

**Bitwarden Chrome Extension**
Version: 2025.5.1
SDK: 'main (c6835e5)'
Server version: 2025.5.2

@Hinton Is there any chance this issue could be reopened. I'm not the only one this is happening to.

**Comment by DimitriosPi** [comment]
Same here:

Edition	Windows 11 Pro
Version	24H2
Installed on	‎20/‎12/‎2024
OS build	26100.4061
Experience	Windows Feature Experience Pack 1000.26100.84.0

Version 2025.5.0
SDK 'main (c6835e5)'
Shell 34.0.0
Renderer 132.0.6834.83
Node 20.18.1
Architecture x64

Version: 2025.5.1

SDK: 'main (c6835e5)'

Server version: 2025.5.2


@Hinton  it happens only with chrome extension, desktop works as it should

**Comment by Hinton** [comment]
There is already an open issue about this https://github.com/bitwarden/clients/issues/5287
