### ISSUE TITLE
Desktop client 2022 9.0 does not start on W10

### ISSUE THREAD

**Issue by Klauwkikker** [bitwarden/clients#3507]
### Steps To Reproduce

Update version to 2022 9.0
Click on Bitwarden icon
Nothing happens
Nothing to see in taskbar

### Expected Result

Bitwarden to start 

### Actual Result

After installation of the newest version Bitwarden does not start. Portable version 2022 9.0 does als not start.

### Operating System

Windows

### Operating System Version

10 pro 32 bit 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022 9.0

**Comment by Klauwkikker** [comment]
Just updated the Windows app from the Windows Store to 2022 9.0 does not start either.

**Comment by keskinoglu** [comment]
Same here. Looks like Bitwarden desktop app on windows 10 64 bit updated today 9/13/22 to version 2022.9.0.0. Won't start, nothing happens. Tried uninstalling and reinstalling. No dice.

**Comment by Klauwkikker** [comment]
> Same here. Looks like Bitwarden desktop app on windows 10 64 bit updated today 9/13/22 to version 2022.9.0.0. Won't start, nothing happens. Tried uninstalling and reinstalling. No dice.
 problem is known by Bitwarden. Hope they find a solution.

**Comment by bckp** [comment]
Same here, it is only desktop app, extension for browsers is working without issue
Název chybující aplikace: Bitwarden.exe, verze: 2022.9.0.0, časové razítko: 0x62c5b9aa
Název chybujícího modulu: desktop_native.win32-ia32-msvc.node, verze: 0.0.0.0, časové razítko: 0x62de8071
Kód výjimky: 0xc0000005
Posun chyby: 0x0001f4b9
ID chybujícího procesu: 0x4e10
Čas spuštění chybující aplikace: 0x01d8c79c47c16261
Cesta k chybující aplikaci: C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\Bitwarden.exe
Cesta k chybujícímu modulu: \?\C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\resources\app.asar.unpacked\node_modules@bitwarden\desktop-native\desktop_native.win32-ia32-msvc.node
ID zprávy: b38fb3f8-1caa-4e1f-b576-24485c55009a
Úplný název chybujícího balíčku: 8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
ID aplikace související s chybujícím balíčkem: bitwardendesktop

**Comment by dbosompem** [comment]
Hi all, apologies for the inconveniences and thanks for updating with more details. The team is currently investigating and we will have it fixed soon, hopefully.

**Comment by dwbit** [comment]
Adding info for @mymags

Steps To Reproduce

    Go to '...'
    Click on '....'
    Scroll down to '....'
    Click on '...'
    Clicked on icon in taskbar. A momentary pause, the "waiting" circle appeared briefly, then no response.
    Clicked on Start, scrolled down to BitWarden, clicked - same result.
    I repeated each action multiple times with the same response, but the app did not open (expected).
    I checked my Android phone and the app appeared normal. This was NOT updated (ver 2022.8.0).
    Opened Firefox browser, searched for BitWarden support. That led to the community forums where I found and participated in the discussion.

Expected Result

I expected BitWarden to open and display my data.
Actual Result

Clicked on icon in taskbar. A momentary pause, the "waiting" circle appeared briefly, then no response.
Screenshots or Videos

No response
Additional Context

Apparently a new problem as I was using the app and storing passwords about 14 hours earlier.
Other posts indicated it is a global problem, but restricted to Windows users.
Operating System

Windows
Operating System Version

Windows 10 Home Version x64 10.0.19043 Build 19043
Installation method

Direct Download (from bitwarden.com)
Build Version

App doesn't open - Other comments lead to 2022.9.0. However, the version on my Android phone is 2022.8.0 downloaded from Google Play Store.

**Comment by DarrenTweedale** [comment]
Not just windows 10, but also windows 11 Pro (version 21H2)

**Comment by msimecek** [comment]
Adding more signal to this thread: 2022.9.0 works fine on my Windows 11 Enterprise, 22H2.

Version 2022.9.0
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture x64

**Comment by ThaMc** [comment]
Version 2022.9.0 not working for me on Windows 11 Enterprise x 64 22H2 (10.0.22000 Build 22000)

**Comment by JCVanderbilt** [comment]
Since the update, this is the error I get when launching Bitwarden:

Faulting application name: Bitwarden.exe, version: 2022.9.0.0, time stamp: 0x62c5b9aa
Faulting module name: desktop_native.win32-ia32-msvc.node, version: 0.0.0.0, time stamp: 0x62de8071
Exception code: 0xc0000005
Fault offset: 0x0001f4b9
Faulting process id: 0x5a70
Faulting application start time: 0x01d8c843f8e7d4d5
Faulting application path: C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\Bitwarden.exe
Faulting module path: \\?\C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\resources\app.asar.unpacked\node_modules\@bitwarden\desktop-native\desktop_native.win32-ia32-msvc.node
Report Id: 06e9122d-74c4-4828-83de-ffca4a4dd598
Faulting package full name: 8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
Faulting package-relative application ID: bitwardendesktop

**Comment by michael-givealittle** [comment]
The same thing is happening for me, Windows 10 Version 20H2 (OS Build 19042.1889).

**Comment by sirdragonlord** [comment]
why hasn't this been pulled, just updated as got notification to update and bang, no longer runs - if this was known yesterday then surely it should have been pulled

**Comment by o-l-a-v** [comment]
Portable and regular installer versions works (until a new Microsoft Store version is pushed).

**Comment by Wicardorith** [comment]
I noticed this yesterday after installing the latest version from microsoft store. I thought it was a problem on my end until I saw this issue. To add more info:
OS: Windows 10 Pro x64 21H2 19044.2006
Bitwarden app version: 2022.9.0.0

**Comment by sirdragonlord** [comment]
check to see if java requires an update, if it does then update it, then rerun the installer for bitwarden

I had to update java and rerun the installer and it is now working in windows 21H2

**Comment by rdyhalt** [comment]
Same for me.
Windows 11 Enterprise x64 v10.0.2200 Build 22000.


`Faulting application name: Bitwarden.exe, version: 2022.9.0.0, time stamp: 0x62c5b9aa
Faulting module name: desktop_native.win32-ia32-msvc.node, version: 0.0.0.0, time stamp: 0x62de8071
Exception code: 0xc0000005
Fault offset: 0x0001f4b9
Faulting process id: 0x707c
Faulting application start time: 0x01d8c8f25980f508
Faulting application path: C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\Bitwarden.exe
Faulting module path: \\?\C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\resources\app.asar.unpacked\node_modules\@bitwarden\desktop-native\desktop_native.win32-ia32-msvc.node
Report Id: 47325c14-5562-4bc1-b6dc-88a879a9ec9f
Faulting package full name: 8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
Faulting package-relative application ID: bitwardendesktop`

**Comment by Letter3900** [comment]
I am also having issues launching the app after downloading it from Windows App Store. Please fix the problem ASAP.

**Comment by jarmomak** [comment]
Same issue here. Reinstallation did not solve the issue.  Serious bug here!

**Comment by jarmomak** [comment]
Running win 11

**Comment by jarmomak** [comment]
![bitwarden bug](https://user-images.githubusercontent.com/32121447/190430379-0545e00c-9d37-4203-a1da-e3f1a1861391.png)

Windbg shows the call stack where fatal exception occurs.

**Comment by oldium** [comment]
That is a null pointer exception. But with no more info.

**Comment by MyMags** [comment]
New info (I am not a "Power User").
1.  When I re-, re-, re-downloaded the updated program this morning from Bitwarden, I selected the option to open after download.  It opened, complete with my data.
2.  When I closed and tried to reopen from shortcut, it failed to open again, as described above.
3.  I looked in Program Files, but Bitwarden is not listed.  Why?
4.  I checked into updating java, but Java does not seem to be on my computer either.  Am I missing something critical?

**Comment by Klauwkikker** [comment]
Bitwarden is aware of the problem and is working at an fix. You can use the webvault until the problem is solved.

**Comment by randall99c** [comment]
For those like me who didn't know it existed, the web version is at https://vault.bitwarden.com/

**Comment by Klauwkikker** [comment]
> For those like me who didn't know it existed, the web version is at https://vault.bitwarden.com/

Thanks for the addition!

**Comment by Klauwkikker** [comment]
New version Bitwarden 2022 9.1 is ready.
Download it on the site of Bitwarden.

**Comment by rdyhalt** [comment]
Just updated from MS Store, all is working for me 👍

**Comment by Letter3900** [comment]
Yes, I have updated the app. It's working for me now.

**Comment by MyMags** [comment]
Thank you for resolving this issue and for enlightening us of the web version way to access BitWarden.
