### ISSUE TITLE
BW Version 2022.9.0 does not start on Windows 10

### ISSUE THREAD

**Issue by MyMags** [bitwarden/clients#3513]
### Steps To Reproduce

4. Click on '...'
Clicked on icon in taskbar. A momentary pause, the "waiting" circle appeared briefly, then no response.
Clicked on Start, scrolled down to BitWarden, clicked - same result.  
I repeated each action multiple times with the same response, but the app did not open (expected).
I checked my Android phone and the app appeared normal.  This was NOT updated (ver 2022.8.0).
Opened Firefox browser, searched for BitWarden support.  That  led to the community forums where I found and participated in the discussion.

### Expected Result

I expected BitWarden to open and display my data.

### Actual Result

Clicked on icon in taskbar. A momentary pause, the "waiting" circle appeared briefly, then no response.

### Additional Context

Apparently a new problem as I was using the app and storing passwords about 14 hours earlier.
Other posts indicated it is a global problem, but restricted to Windows users.

### Operating System

Windows

### Operating System Version

Windows 10 Home Version x64 10.0.19043 Build 19043

### Installation method

Direct Download (from bitwarden.com)

### Build Version

App doesn't open - Other comments lead to 2022.9.0.  However, the version on my Android phone is 2022.8.0 downloaded from Google Play Store.

**Comment by dwbit** [comment]
Moved response to https://github.com/bitwarden/clients/issues/3507
