### ISSUE TITLE
Microsoft Store version of Bitwarden won't open, even after a fresh install

### ISSUE THREAD

**Issue by jovonkos** [bitwarden/clients#3522]
### Steps To Reproduce

1. Run Bitwarden.

### Expected Result

Bitwarden opens

### Actual Result

A _Bitwarden has stopped working_ window

Screenshots are provided below

### Screenshots or Videos

![Screenshot 2022-09-14 135028](https://user-images.githubusercontent.com/74419615/190081734-c835b6dc-c72e-4aec-b526-1a119e62fe6d.png)
This window appears every time I tried to open Bitwarden, even from a fresh install.

![image](https://user-images.githubusercontent.com/74419615/190082067-c2d4a919-f310-4933-a141-d8c351bfc433.png)

### Additional Context

Bug persists even after reinstalling Bitwarden, so I'm now using the web to access my vault. It worked perfectly before, but today it's simply inaccesible.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Microsoft Store

### Build Version

2022.9.0.0

**Comment by Akkowicz** [comment]
Same for me

```
Source
Bitwarden

Summary
Stopped working

Date
‎14/‎09/‎2022 09:11

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\WindowsApps\8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy\app\Bitwarden.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	8bitSolutionsLLC.bitwardendesktop_2022.9.0.0_x86__h4e712dmw3xyy
Application Name:	praid:bitwardendesktop
Application Version:	2022.9.0.0
Application Timestamp:	62c5b9aa
Fault Module Name:	desktop_native.win32-ia32-msvc.node
Fault Module Version:	0.0.0.0
Fault Module Timestamp:	62de8071
Exception Code:	c0000005
Exception Offset:	0001f4b9
OS Version:	10.0.22000.2.0.0.256.48
Locale ID:	2057
Additional Information 1:	38ec
Additional Information 2:	38ec0a44a56ae3174f809e5929106ff9
Additional Information 3:	78b3
Additional Information 4:	78b3bea2c7d95cdb4ad1ef758fe62eb6

Extra information about the problem
Bucket ID:	9bf40892f7e8c13aad5d975c57d70a98 (2116013822800497304)

```

**Comment by djsmith85** [comment]
Hi @jovonkos and @Akkowicz, thank you for your reports. 

This is a known issue and is being tracked at #3507.

Closing this as duplicate.
