### ISSUE TITLE
Chrome asking to reset pre-configured settings when custom server url set in registry

### ISSUE THREAD

**Issue by davideverall** [bitwarden/clients#3523]
### Steps To Reproduce

1. Configure base registry setting as documented in [configure client centrally](https://bitwarden.com/help/configure-clients/#chrome-and-chromium)
2. Open bitwarden extension in chrome and go to settings
3. User is presented with a message: "SETTINGS HAVE BEEN EDITED - click here to reset to pre-configured settings"
4. After clicking to reset settings, the custom url from the registry setting appears in "server url"

![bitwarden-settings](https://user-images.githubusercontent.com/74308196/190131184-31c8b48e-0ee2-4579-bb1e-4b7a0dfa43bc.png)

### Expected Result

After applying the registry setting, the server url should be auto populated in the Chrome extension bitwarden settings

### Actual Result

User needs to first click reset before the ser url is populated

### Operating System

Windows

### Operating System Version

10 21h2

### Web Browser

Chrome

### Browser Version

105.0.5195.102

### Build Version

2022.9.0

**Comment by Hinton** [comment]
Hi @davideverall,

This is the current intended behavior. The settings are applied on install of the browser extension, in order avoid conflicting with any users existing settings. You can verify this behavior by reinstalling the extension.

Please reach out to our customer success team if you have any further issues with this functionality https://bitwarden.com/contact/ and they should be able to assist you.
