### ISSUE TITLE
Dialog window characters are only rectangles on ubuntu

### ISSUE THREAD

**Issue by mceikens** [bitwarden/clients#3525]
### Steps To Reproduce

In my case i got the dialog with the rectangles on vault export.

![grafik](https://user-images.githubusercontent.com/82055774/190153940-08c1b4c0-e1d5-4425-86f6-492de974fb97.png)

But i got this bug on different actions.

Like try to delete a entry or others.
![grafik](https://user-images.githubusercontent.com/82055774/190154281-a1ae41d1-f442-4028-bb86-d04eae88e21e.png)

Or About BItwarden are the same 
![grafik](https://user-images.githubusercontent.com/82055774/190156188-a99bfe78-3dfe-406c-9114-94430232b6a1.png)

### Expected Result

I want to read the message in the dialog clearly without to suppose under which rectangle is my information what i need

### Actual Result

Current result is that i can't read the dialogs on delete processes or About Bitwarden or equal.
You can see that in the images in chapter "Steps to Reproduce"

### Additional Context

I have tried different languages. 
I tried 

- English
- English (British)
- Default
- German

In all languages the result of dialogs are equal (see on pictures)

Also i using the dark theme.

In my case i can't see the build version from bitwarden over "About Bitwarden".
I'm used the command "snap info bitwarden"

### Operating System

Linux

### Operating System Version

Ubuntu 22.04, Ubuntu 20.04

### Installation method

Snap

### Build Version

installed:          2022.9.0

**Comment by djsmith85** [comment]
Hi @mceikens and thank you for your report.

This is a known issue which we are tracking with https://github.com/bitwarden/clients/issues/2628.

Closing this now, as duplicate.
