### ISSUE TITLE
Windows 10 Chrome - no longer able to enable sign in with biometrics

### ISSUE THREAD

**Issue by mwittmann** [bitwarden/clients#3528]
### Steps To Reproduce

Yesterday, my Windows 10 PC installed some updates. After that, the Bitwarden desktop client stopped working with Windows Hello. After disabling Bitwarden biometrics, reenabling it, rebooting, etc., it started working again.

However, the Bitwarden Chrome extension "Unlock with biometrics" no longer works. I wanted to try disabling and reenabling the setting, but after disabling it, I am unable to reenable it. I get the message:
![image](https://user-images.githubusercontent.com/5827956/190197446-87d298b2-271c-4882-b36e-9097ade27294.png)

1. Sign into the Bitwarden Chrome extension with master password.
2. Click on "Settings" (gear) icon.
3. Click on "Unlock with biometrics".
4. After a second, the error message above appears.

### Expected Result

It should be possible to enable "Unlock with biometrics." (And after that, the biometrics feature should work again!)

### Actual Result

Error message (see screenshot) appears.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5827956/190198179-f989bcf2-6551-4f86-a732-20d35472137c.png)

### Operating System

Windows

### Operating System Version

Edition	Windows 10 Pro Version	21H1 Installed on	‎6/‎5/‎2020 OS build	19043.2006 Serial number	PF0V78DT Experience	Windows Feature Experience Pack 120.2212.4180.0

### Web Browser

Chrome

### Browser Version

Version 105.0.5195.102 (Official Build) (64-bit)

### Build Version

2022.8.0

**Comment by msiqx9** [comment]
Now fixed in 2022.9.1 released yesterday.

**Comment by mwittmann** [comment]
I've confirmed this is now working again with the Windows 10 and Chrome versions indicated.
