### ISSUE TITLE
Search typing interuptions

### ISSUE THREAD

**Issue by samo-sato** [bitwarden/clients#3535]
### Steps To Reproduce

Hello,
1. Go to browser.
2. Click on Bitwarden icon in the browser.
3. Start typing some longer string that will match some of the saved items in vault so it returns result(s). Type not too slowly and not too quickly, it seems there are thresholds.
4. If issue not reproduced then close extension window (click outside of it) and open extension again and start typing again.

### Expected Result

Searching for the string user has actually typed.

### Actual Result

In short: App searches for the string user has not typed.
In long: At some of the typed character the typing is interrupted as results are constantly generated and refreshed while typing and after you finished typing you realized that instead of for example "github" the app is looking for "gihub" (typing was interrupted while typing letter "t").

### Additional Context

- This is happening for many months and it is annoying.
- Brave browser extension does the same.
- Bitwarden desktop app is without issue.
- If necessary I can try to reproduce it at Windows 10 on Firefox too.

### Operating System

Linux

### Operating System Version

Mint 20

### Web Browser

Firefox

### Browser Version

104.0.2

### Build Version

2022.8.0

**Comment by djsmith85** [comment]
Hi @samo-sato and thank you for your report.

This is a known issue which we are currently tracking with https://github.com/bitwarden/clients/issues/2371.

Closing this as duplicate.
