### ISSUE TITLE
Since BW Windows 2022.9.0 update, Windows Hello prompt to log in BW Chrome extension is showing in the background

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#3536]
### Steps To Reproduce

First requirements:
Have a Windows PC with BW desktop for Windows installed and Chrome browser with BW extension
Configure them to use Windows Hello to login

1. go to any website with Chrome
2.  open BW extension and login with Windows Hello

### Expected Result

The Windows Hello prompt should come up automatically in front of every applications :
![image](https://user-images.githubusercontent.com/98819304/190391746-1d9d5ace-bb76-4465-a45d-609a182cddaa.png)

### Actual Result

The Windows Hello prompt is not visible and you BW is not responding and it is endlessly showing:
![image](https://user-images.githubusercontent.com/98819304/190392341-1d07f61b-f9f8-4de6-99f8-2429b176d97f.png)

After searching what has happened, you realize the Windows Hello prompt was opened in the background by BW : it is hidden behind other Windows and you have to use Alt+Tab to find it. Only then you can use Windows Hello.

### Screenshots or Videos

Here is the BW desktop for Windows version causing this issue :
![image](https://user-images.githubusercontent.com/98819304/190391595-aaf16a76-6faa-4bf0-ae72-d768ed0d320e.png)

There was no issue in the August version of BW for Windows.

### Additional Context

BW desktop for Windows was installed from the .exe on your website (not Windows Store).

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.0

**Comment by djsmith85** [comment]
Hi @oeloo and thank you for your report.

This is already being tracked with https://github.com/bitwarden/clients/issues/3504.

Closing this as duplicate.
