### ISSUE TITLE
popup window - wrong domain name detected

### ISSUE THREAD

**Issue by zcz3** [bitwarden/clients#3542]
### Steps To Reproduce

1. Buy something from a website that allows paypal (e.g. ebay)
2. Paypal creates a pop-up window prompting login, the domain name for this can be seen in the address bar as paypal.com
3. In the popup window, right click and go to Bitwarden -> Auto fill in the context menu
4. The auto-fill list shows your login for ebay.com (the parent window), not paypal.com (the popup you right-clicked on)
5. Furthermore, if you switch to another tab in the parent browser window (literally anything, e.g bbc.co.uk), then bring the paypal popup window to the foreground, right click on it, the Bitwarden context menu now shows my login to BBC even though the domain name is clearly paypal.com!

This is on Firefox with the Bitwarden extension.

I'm fairly sure this used to work as expected so is a regression.

### Expected Result

See above

### Actual Result

See above

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Build Version

2022.8.0

**Comment by JorisDebonnet** [comment]
I also have this problem. It happens on any website that offers PayPal, if the PayPal login opens up a popup. 

I am also on Firefox, on Windows 11.

**Comment by Krychaz** [comment]
Hello, 

I tried to replicate this but I was unable to. I was able to autofill Paypal information on a popup window without issues. Please make sure you are using the correct URI https://www.paypal.com/
