### ISSUE TITLE
Cannot find module '@bitwarden/desktop-native-linux-x64-musl' since  2022.9.0

### ISSUE THREAD

**Issue by tomamplius** [bitwarden/clients#3544]
### Steps To Reproduce

npm ci
cd /apps/desktop
PATH=$PATH:/tmp/${APP}/node_modules/.bin/
npm run clean:dist
npm run build
electron-builder --linux dir --x64 -p never

### Expected Result

application start without issue until 2022.8.1 and not work since 2022.9.0

### Actual Result

```
./bitwarden 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '@bitwarden/desktop-native-linux-x64-musl'
Require stack:
- /mnt/debmaker/bitwarden-desktop/tmp/bitwarden-desktop/apps/desktop/dist/linux-unpacked/resources/app.asar/node_modules/@bitwarden/desktop-native/index.js
- /mnt/debmaker/bitwarden-desktop/tmp/bitwarden-desktop/apps/desktop/dist/linux-unpacked/resources/app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/mnt/debmaker/bitwarden-desktop/tmp/bitwarden-desktop/apps/desktop/dist/linux-unpacked/resources/app.asar/node_modules/@bitwarden/desktop-native/index.js:160:29)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```

### Additional Context

application start without issue until 2022.8.1 and not work since 2022.9.0

### Operating System

Linux

### Operating System Version

Linux debian 11

### Installation method

Other

### Build Version

2022.9.0 and  2022.9.1

**Comment by djsmith85** [comment]
Hi @tomamplius,

from the error message and build-steps you provided, I guess the native desktop module (apps/desktop/desktop_native) has not been built or needs to be re-built.

Please have a look at our setup instructions for the desktop client [here](https://contributing.bitwarden.com/clients/desktop/) and see if that resolves it.

**Comment by tomamplius** [comment]
Thanks about your reply.
I have miss understand between path apps/desktop and apps/desktop/desktop_native
It instruction create now desktop_native.linux-**x64-gnu**.node

And i have the bellow error now (same as before) with musl
```
[Main] Debugger listening on ws://127.0.0.1:5858/00fee294-3a20-4064-af15-5792d674275a
[Main] For help, see: https://nodejs.org/en/docs/inspector
[Rend] 
[Rend] > @bitwarden/desktop@2022.9.1 build:renderer:watch
[Rend] > cross-env NODE_ENV=development webpack --config webpack.renderer.js --watch
[Rend] 
[Main] App threw an error during load
[Main] Error: Cannot find module '@bitwarden/desktop-native-linux-x64-musl'
[Main] Require stack:
[Main] - /tmp/bitwarden-desktop/apps/desktop/desktop_native/index.js
[Main] - /tmp/bitwarden-desktop/apps/desktop/build/main.js
[Main] - /tmp/bitwarden-desktop/node_modules/electron/dist/resources/default_app.asar/main.js
[Main] - 
[Main]     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[Main]     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
[Main]     at Module._load (node:internal/modules/cjs/loader:785:27)
[Main]     at c._load (node:electron/js2c/asar_bundle:5:13343)
[Main]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[Main]     at require (node:internal/modules/cjs/helpers:102:18)
[Main]     at Object.<anonymous> (/tmp/bitwarden-desktop/apps/desktop/desktop_native/index.js:160:29)
[Main]     at Module._compile (node:internal/modules/cjs/loader:1118:14)
[Main]     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
[Main]     at Module.load (node:internal/modules/cjs/loader:988:32)
[Main] A JavaScript error occurred in the main process
[Main] Uncaught Exception:
[Main] Error: Cannot find module '@bitwarden/desktop-native-linux-x64-musl'
[Main] Require stack:
[Main] - /tmp/bitwarden-desktop/apps/desktop/desktop_native/index.js
[Main] - /tmp/bitwarden-desktop/apps/desktop/build/main.js
[Main] - /tmp/bitwarden-desktop/node_modules/electron/dist/resources/default_app.asar/main.js
[Main] - 
[Main]     at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
[Main]     at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
[Main]     at Module._load (node:internal/modules/cjs/loader:785:27)
[Main]     at c._load (node:electron/js2c/asar_bundle:5:13343)
[Main]     at Module.require (node:internal/modules/cjs/loader:1012:19)
[Main]     at require (node:internal/modules/cjs/helpers:102:18)
[Main]     at Object.<anonymous> (/tmp/bitwarden-desktop/apps/desktop/desktop_native/index.js:160:29)
[Main]     at Module._compile (node:internal/modules/cjs/loader:1118:14)
[Main]     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
[Main]     at Module.load (node:internal/modules/cjs/loader:988:32)
[Main] Authorization required, but no authorization protocol specified
[Main] [1760028:0916/080259.698226:ERROR:ozone_platform_x11.cc(248)] Missing X server or $DISPLAY
[Main] [1760028:0916/080259.698270:ERROR:env.cc(226)] The platform failed to initialize.  Exiting.
[Main] /tmp/bitwarden-desktop/node_modules/electron/dist/electron exited with signal SIGSEGV
[Main] electron --inspect=5858 ./build --no-sandbox --watch exited with code 1
--> Sending SIGTERM to other processes..
[Rend] npm run build:renderer:watch exited with code SIGTERM

```

**Comment by Hinton** [comment]
Please try running `npm run build -- --target x86_64-unknown-linux-musl` your linux setup might be trying to use the gnu buildtools instead of musl.

**Comment by tomamplius** [comment]
Thanks for your help, 
i compile bitwarden desktop on chroot DEBIAN linux create with debootstrap.


To run your command in need to execute `rustup target add x86_64-unknown-linux-musl`
and next issue is 
```
warning: pkg-config has not been configured to support cross-compilation.

error: failed to run custom build command for `gobject-sys v0.15.5`
```

I think debian use gnu libc by default?
I need to change configuration to compile with musl and install all with this libc?
Bitwarden desktop work only with this lib now?

**Comment by Hinton** [comment]
We have rewritten the native portions of the Bitwarden Desktop application in rust in order to have more control of the feature set. So yes, the native module is a requirement in order to run the application. You can either build it yourself or fetch it from one of the artifacts we make available.

The script we use to build it on linux is https://github.com/bitwarden/clients/blob/master/.github/workflows/build-desktop.yml#L188-L197.

**Comment by tomamplius** [comment]
I understand my issue now. 
i will find how make cross-compilation with musl libc on debian.

Best regards and thanks you very much

**Comment by tomamplius** [comment]
Work very well now

```
	APP=bitwarden-desktop
	source ~/.cargo/env
	export PKG_CONFIG_ALL_STATIC=1
	export PKG_CONFIG_ALLOW_CROSS=1
	rustup target add x86_64-unknown-linux-musl
	cd /tmp/${APP}
	npm ci
	cd /tmp/${APP}/apps/desktop/desktop_native/
	npm run build -- --target x86_64-unknown-linux-musl
	cd /tmp/${APP}/apps/desktop
	PATH=$PATH:/tmp/${APP}/node_modules/.bin/
	npm run clean:dist
	npm run build
	electron-builder --linux dir --x64 -p never
```

**Comment by patrickhlauke** [comment]
@Hinton as i just spent some time recreating my build environment, and hit on the same problem (using WSL2 on windows), is it maybe possible to add the information above (about doing `rustup target add x86_64-unknown-linux-musl` and then specifically `npm run build -- --target x86_64-unknown-linux-musl`) somewhere on the documentation https://contributing.bitwarden.com/getting-started/clients/desktop/#build-native-module ?

**Comment by Hinton** [comment]
@patrickhlauke the contributing docs are open source and that page can be found at https://github.com/bitwarden/contributing-docs/blob/master/docs/getting-started/clients/desktop/index.mdx. I'll see if we can add a note to mention cross compile, it's not typically something that's needed.

I would also discourage the use of WSL for the desktop application since we rely on native components on both Windows and Linux for it to functional properly. The created dev experience diverges fairly far from how the production build would behave.

**Comment by M1cha** [comment]
> I would also discourage the use of WSL for the desktop application since we rely on native components on both Windows and Linux for it to functional properly. The WSL dev experience diverges fairly far from how the production build would behave.

I have the exact same problem on arch linux and @patrickhlauke s instructions work for me.

**Comment by Hinton** [comment]
I've opened a PR with cross compiling instructions, https://github.com/bitwarden/contributing-docs/pull/55. @patrickhlauke would appreciate any comments, I removed `APP=` since I don't believe it's required but let me know if I'm wrong.
