### ISSUE TITLE
Firefox browser extention does not automatically or manually lock anymore

### ISSUE THREAD

**Issue by timharek** [bitwarden/clients#3570]
### Steps To Reproduce

1. Restart Firefox
2. Unlock Bitwarden
3. Use the browser a bit
4. Try to lock Bitwarden

### Expected Result

Expected the extention to lock and require password/PIN.

### Actual Result

Does not do anything.

### Additional Context

When I try to to it manually in the Settings in the extension it also does nothing.

### Operating System

macOS

### Operating System Version

12.5.1

### Web Browser

Firefox

### Browser Version

104.0.2

### Build Version

2022.8.0

**Comment by timharek** [comment]
> @timharek the browser version you listed is a link to a book on goodreads. I think you pasted the wrong information

Thanks for letting me know, for some reason I can't copy my browser version from the settings 😅

**Comment by djsmith85** [comment]
Hi @timharek and @mrlinuxfish, thank you for your reports.

Is it possible a popped out window of the extension was open or Bitwarden was open in the Firefox sidebar? If one of those were the case then this has previously been reported with https://github.com/bitwarden/clients/issues/854

If not, then it's possibly a duplicate of https://github.com/bitwarden/clients/issues/3274

Please close this issue, if its a duplicate to one of the mentioned issues.

**Comment by timharek** [comment]
Thanks for the reply!

> Is it possible a popped out window of the extension was open or Bitwarden was open in the Firefox sidebar?

No, I regularly quit my browser and this happens every time now. It may be a duplicate of #3274, but I don't know for sure.

**Comment by mrlinuxfish** [comment]
@djsmith85 I have closed my browser a few times and I definitely don't have bitwarden open in the sidebar or a floating window

**Comment by Camusensei** [comment]
I never had a locking issue and I can't reproduce.
![image](https://user-images.githubusercontent.com/3405342/193776150-f6c65bd6-715d-401a-91f7-ee01664725ab.png)
![image](https://user-images.githubusercontent.com/3405342/193776223-6d4ffe6e-4965-42cb-b85c-85e43752beb7.png)

**Comment by OliverPearmain** [comment]
My vault is also permantly unlocked despite having a vault timeout of "1 minute", and vault timeout action of "Lock". Even pressing on the "Lock Now" does nothing. Wonderful security.

OS: macOS Monterey 12.4
Browser: Firefox 104.0.2
Extension: 2022.9.1

**Comment by Camusensei** [comment]
It works for me on (I will edit my message later to add the version of the browser on windows):
Firefox 105.0 + Ubuntu 20.04.5 LTS
Firefox + Windows 10
Edge + Windows 10

Be careful, being arrogant like this may make people not want to help anymore.
Have you tried re-installing the extension?
What about logout as a timeout action, does it work?

**Comment by OliverPearmain** [comment]
Restarting the browser entirely has solved the issue for me. However if its possible to put the extension in this state it seems like a siginificany security vulnerability (hence my sarcastic comment, I apologise for this it was inappropriate).

**Comment by Camusensei** [comment]
@nortti0 good job finding this. Same behaviour on windows.
With this, I guess someone will be able to figure out where the problem is coming from.
But beware: being in the middle of creating a new login is probably ONLY ONE of the triggers which can lead to this tricky situation.

**Comment by calvinrw** [comment]
I can confirm @nrotti0's steps work on macOS - well done! Specifically, this is how I do it:

1. Ensure the Bitwarden extension is logged into a vault, but is locked
1. Browse to a page with a URL that doesn't have a vault entry associated with it, e.g., Firefox's new tab page
1. Click the toolbar button to open the Bitwarden popup
1. Enter the master password to unlock the vault
1. Click the "Add a Login" button
1. Command-Tab away from Firefox to a different application that's running, causing the popup to close
1. Command-Tab back to Firefox
1. Click the toolbar button again to re-open the Bitwarden popup
1. In the popup, click Settings -> Lock Now and observe that the vault does not lock

Echoing @Camusensei's point, I don't recall the circumstances that caused me to stumble upon this issue originally, so I can't say for sure if this is the only way to induce it.

As of now, I'm using:
- Firefox 107.0.1 
- Bitwarden extension 2022.10.1
- macOS 10.15.7

**Comment by Greenderella** [comment]
Hello,

We can no longer reproduce this issue. Please try a clean installation by removing any leftover data (https://help.bitwarden.com/article/where-is-data-stored-computer/).

Additionally, you might want to refresh your Firefox profile (instructions here: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings).

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
