### ISSUE TITLE
Error thrown on app startup leaves app with infinite spinner

### ISSUE THREAD

**Issue by tabsnotspaces9** [bitwarden/clients#3584]
### Steps To Reproduce

1. Open App on Mac

### Expected Result

Vault login will show

### Actual Result

Infinite spinner blocking all functionality

### Screenshots or Videos

<img width="865" alt="Screen Shot 2022-09-21 at 3 57 46 PM" src="https://user-images.githubusercontent.com/6473983/191609329-a11540ac-d32e-40a1-8827-63b3dec645a4.png">

### Operating System

macOS

### Operating System Version

12.5.1

### Installation method

Mac App Store

### Build Version

2022.9.1 (4562)

**Comment by alexpearce92** [comment]
A full uninstall and reinstall resolved the bug
