### ISSUE TITLE
Export organization vault gives error 404 resource not found

### ISSUE THREAD

**Issue by TimoVerbrugghe** [bitwarden/clients#3595]
### Steps To Reproduce

1. Using the bw cli (in my case installed using npm), signed into my selfhosted bitwarden server

`bw config server <serverurl>
bw login --apikey
bw sync
bw unlock`

2. List my organizations in order to get organization IDs

`bw list organizations --session <BW_SESSION_KEY>`

3. Try to export one of my organizations' vault as a non-encrypted json 

`bw export --format json --organizationid <orgid> --session <BW_SESSION_KEY> --output .`

### Expected Result

A json formatted file with the items in my organization vault

### Actual Result

Getting the following error code:

{"response":{"error":{"code":404,"reason":"Not Found","description":"The requested resource could not be found."}},"captchaRequired":false,"statusCode":404}

### Screenshots or Videos

<img width="770" alt="Screenshot 2022-09-22 at 19 43 59" src="https://user-images.githubusercontent.com/7707120/191815840-9d59e1d8-75bc-454a-878f-a6f65176b685.png">

### Additional Context

I've triple checked that the org id is correct. Additionally, other commands such as 

`bw get organization <orgid>`
`bw list org-collections --organizationid <orgid>`

do work with the same org id that I'm using on the export command.

Exporting using other formats (csv or encrypted json) come with the same result.

Exporting the organization vault using the web client works as expected.

### Operating System

Linux

### Operating System Version

Using alpine linux in a docker container

### Shell

Bash

### Build Version

2022.9.0

**Comment by dh024** [comment]
For anyone reading this thread in the future, this is a server-side issue. Note above that the user is running vaultwarden server, not a Bitwarden product.
