### ISSUE TITLE
Master password field no longer auto focus when Bitwarden extension is clicked

### ISSUE THREAD

**Issue by bilogic** [bitwarden/clients#3605]
### Steps To Reproduce

1. Go to 'Chrome'
2. Click on 'Bitwarden' extension
3. Master password is not auto focused, an extra click is required to focus it

### Expected Result

1. Go to 'Chrome'
2. Click on 'Bitwarden' extension
3. Master password should auto focus

### Actual Result

1. Go to 'Chrome'
2. Click on 'Bitwarden' extension
3. Master password is not auto focused, an extra click is required to focus it

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome

### Browser Version

Chrome is up to date Version 105.0.5195.127 (Official Build) (64-bit)

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @bilogic, thank you for the report. This is a known issue and is being tracked with https://github.com/bitwarden/clients/issues/3562.

Closing this as duplicate.
