### ISSUE TITLE
The new organization export is case sensitive in regards to the server response with ciphers and collections

### ISSUE THREAD

**Issue by BlackDex** [bitwarden/clients#3606]
### Steps To Reproduce

Not really able to reproduce this with the Bitwarden server, but it is with the Vaultwarden server.

Steps to take are simple.
- Export an organization vault to json.

Doesn't matter if this is via web-vault or cli for example.

### Expected Result

A full export in JSON format with all the ciphers and collections.

### Actual Result

Empty JSON, no ciphers or collections.

### Additional Context

I'm one of the main developers of Vaultwarden, and it looks like the JSON response format on how to export the vault has changed to be case-sensitive.

Previously it didn't matter if the JSON key's were like `FolderId` or `folderId`, both were excepted.
If i check the code for the old way to export i see a `ListResponse` function which handles this. (https://github.com/bitwarden/clients/blob/f72ef2dce5cee26a4df80d3c6d23ccddb4b2fe4a/libs/common/src/services/api.service.ts#L572-L580)

With the new function that `ListResponse` is gone, and it now is case sensitive in the parsing. (https://github.com/bitwarden/clients/blob/5f74b9a6947ec71c8022e0d170f3db18f317fcce/libs/common/src/services/export.service.ts#L239-L242)

I wonder if this is intentional or, maybe was an oversight, since all other API's do handle both formats as far as I can tell.

Thanks in advance!

### Operating System

Linux

### Web Browser

Chrome, Firefox

### Build Version

2022.9.0+

**Comment by Hinton** [comment]
Hi @BlackDex,

I took a look at the response model and it indeed seems we are not parsing the nested json properly. This can have unintended site effects other than the camelCase, snake_case observed here.

On another note, the servers previously returned either PascalCase or camelCase, however we removed PascalCase support on the servers a while back. While we currently have no plans to intentionally remove it from the server I won't guarantee it will always exist. So it might be worth considering migrating to camelCase completely for vaultwarden.

**Comment by BlackDex** [comment]
@Hinton Thanks for the reply.
Looks like we have some work to do.
But, better to have everything the same and one format.

**Comment by Hinton** [comment]
@BlackDex before I forget it, the API for export will change again once that PR is merged. We're removing the unecessary nesting, since it doesn't match how our other APIs are implemented.

**Comment by BlackDex** [comment]
@Hinton, that would be #3641 i guess.
Sounds like a simple change.

Is there some way to differentiate between the versions?
Because now clients 2022.9.x will break on newer server version of i look at both PR's, but I could be wrong.

**Comment by Hinton** [comment]
The organization export is just for the web vault, which is version tied to the server so we lucked out in this case. There is a version header that should be sent along for each request you could check.

**Comment by BlackDex** [comment]
@Hinton, are you sure??
If i run: `bw export --format json --organizationid <org-id>` with v2022.9.0 it calls the exact same endpoint.
With v2022.8.x it still calls the two separate endpoints.

**Comment by Hinton** [comment]
That's a good point, I had forgotten the CLI.

**Comment by BlackDex** [comment]
@Hinton i think this ticket can be closed right?
Or do you need this still for some checking?

**Comment by Hinton** [comment]
It will close once the PR gets merged.
