### ISSUE TITLE
KeePass2 Import Fails on CLI 2022.9.1

### ISSUE THREAD

**Issue by atjbramley** [bitwarden/clients#3658]
### Steps To Reproduce

1. Attempt to import a valid Keepass2 XML file using:
 ` bw import keepass2xml (path to file)`

### Expected Result

The Keepass XML contents should be imported into the Vault

### Actual Result

An error stating 'Missing `KeePassFile > Root > Group` node

### Screenshots or Videos

https://user-images.githubusercontent.com/71517198/193228855-5d3ccd5f-f0ee-4ed5-8ead-6ad5aa847bbb.mov

### Additional Context

Appears to be a regression - the same file is imported correctly using bw CLI version 1.22.1

### Operating System

Windows, macOS

### Operating System Version

macOS 12.6 / Windows 11 in QEMU VM

### Shell

Zsh, PowerShell

### Build Version

2022.9.0

**Comment by Boscop** [comment]
I'm getting the same error, it's preventing me from importing my data!
I checked the xml file and it **has** the `KeePassFile > Root > Group` node, so it's not missing!

I would appreciate if this can get fixed soon :)
@atjbramley Is there any known workaround? I just installed the CLI from npm (`npm install -g @bitwarden/cli`), where can I get a version that works?
