### ISSUE TITLE
Master password field not active when opening extension

### ISSUE THREAD

**Issue by mull0r** [bitwarden/clients#3668]
### Steps To Reproduce

1. Open browser
2. Click on Extension to open
3. Typing master password to unlock vault
4. Password not showing up in password text field
5. Cursor doesn't show active in extension
6. Click on field for master password (or TAB 2 times)
7. Then it works.

### Expected Result

When you click the extension to unlock your vault and start typing, the master password (text) input field should be active right away. This was always the case, but not anymore.

### Actual Result

The input field for master password isn't active. Takes extra effort (typing once, clicking, typing again)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.1

### Web Browser

Firefox

### Browser Version

105.0.1 (64-bits)

### Build Version

2022.9.1

**Comment by raccettura** [comment]
Noticing this as well.  It's not actually that it doesn't focus on the password field, it's that there's now a 1s delay which is cumbersome.

**Comment by mull0r** [comment]
Correction, it is indeed working with a delay. Only my delay last for about 4-5 seconds.

**Comment by BadCo-NZ** [comment]
Can confirm this is happening on a linux desktop with FireFox and a Windows desktop with Chrome.

**Comment by bohanyang** [comment]
Can confirm this. It's delayed for about 2-3 seconds.

**Comment by djsmith85** [comment]
Hi @mull0r, @raccettura, @BadCo-NZ and @bohanyang  thank you for the reports.

This is a known issue and is being tracked with https://github.com/bitwarden/clients/issues/3562.

Closing this as duplicate.
