### ISSUE TITLE
Locked vault doesn’t autofocus master password field

### ISSUE THREAD

**Issue by sylbru** [bitwarden/clients#3685]
### Steps To Reproduce

1. Have your vault be locked
2. Click the Bitwarden icon
3. If you try to type your password directly, it does nothing, because the master password field isn’t focused.

### Expected Result

The master password field used to be automatically focused.

### Actual Result

The master password field is not focused.

### Operating System

Linux

### Web Browser

Chrome, Firefox

### Browser Version

Firefox 105, Chromium 106

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @sylbru thank you for your report.

This is a known issue and being tracked with #3562.

Closing this as duplicate now.
