### ISSUE TITLE
F-Secure Key Importer broken

### ISSUE THREAD

**Issue by Phasip** [bitwarden/clients#3692]
### Steps To Reproduce

Export fsk from F-Secure ID Protect (Rename of F-Secure Key)
Import into bitwarden

### Expected Result

All entries within the exported fsk file should be imported. Entries with an unknown "style" parameter would be partially imported or warned about in the cli output.

### Actual Result

Only entries with "style":"globe", "style":"website" or "style":"creditcard" are imported.
Most of my entries were "style":""

### Additional Context

The issue also happens on the web.
A simple workaround was to search and replace `"style":""` with `"style":"globe"` in the FSK to make all my entries style: globe.

https://github.com/bitwarden/clients/blob/da5e4a57d026e0d09356ad3405e08fb140462fd7/libs/common/src/importers/fsecureFskImporter.ts

### Operating System

Linux

### Shell

Bash

### Build Version

2022.9.0

**Comment by djsmith85** [comment]
@Phasip Thank you for your report.

This issue has previously been reported with https://github.com/bitwarden/clients/issues/2801.

Closing this now as duplicate.
