### ISSUE TITLE
Windows 10 Edge ignores lock settings and locks itself right after extension is closed. 

### ISSUE THREAD

**Issue by Krychaz** [bitwarden/clients#3693]
### Steps To Reproduce

1. Go to Edge on Windows 10 
2. Click on Bitwarden Extension
3. Set to vault timeout to on system lock
4. Close browser 
5. Open browser and extension again 
6. Vault requires entering of master password again. 

### Expected Result

1. Go to Edge on Windows 10 
2. Click on Bitwarden Extension
3. Set to vault timeout to on system lock
4. Close browser 
5. Open browser and extension again 
6. Vault does not require authentication 

### Actual Result

Vault requires authentication even though under this scenario system was not restarted. 

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H2 Build 19044.2075

### Web Browser

Microsoft Edge

### Browser Version

106.0.1370.34

### Build Version

2022.9.1

**Comment by creyhani** [comment]
Hello! I was able to reproduce this and we will be working on fixing it! I'll get you an update as soon as we have it taken care of! Thanks for using Bitwarden!

**Comment by cyb3rko** [comment]
Seeing same behaviour on:

Windows 11 Pro 22H2 Build 22621.674
Google Chrome 106.0.5249.119
Bitwarden 2022.10.0

**Comment by Hinton** [comment]
Hi @Krychaz,

This is the current expected behavior. Browsers don't have a safe way to persist sensitive information across sessions. This unfortunately means the extension will lock itself should the browser be closed, or if the extension is reloaded by the browser. You can read a bit more on our help page, https://bitwarden.com/help/vault-timeout/#web-and-browser-extension-timeouts.

**Comment by cyb3rko** [comment]
@Hinton Then maybe the we should remove the option "Never" for the timeout as it seems impossible.
And has Bitwarden removed that feature in an update as it used to work a few months ago.

**Comment by Hinton** [comment]
Never is a valid timeout option and should work. The option "On System Lock" however does not persist it to disk and therefore loses context if the browser closes the extensions main process.

**Comment by Krychaz** [comment]
I can confirm that 'never' option works correctly.

**Comment by cyb3rko** [comment]
Oh okay, for me 'Never' does not work.
Interesting.
