### ISSUE TITLE
Firefox master password focus delay

### ISSUE THREAD

**Issue by andreapx** [bitwarden/clients#3700]
### Steps To Reproduce

1. With the vault locked, click on the BitWarden icon
2. The BitWarden windows opens immediately
3. The focus on the field to insert the master password is set after about 4 seconds and not immediately as it was before the last update (of Firefox for sure, I don't know if the BitWarden extension got updated recently or not)
4. Click on '...'

### Expected Result

As soon as I click on the BitWarden icons I should be able to write the master password straight away as it was previously.

### Actual Result

The focus on the field to insert the master password is set after about 4 seconds and not immediately as it was before the last update (of Firefox for sure, I don't know if the BitWarden extension got updated recently or not)

### Screenshots or Videos

https://user-images.githubusercontent.com/13846728/194263144-df38c5d0-cc36-4873-9bc8-22796a49bf36.mp4

### Operating System

Windows

### Operating System Version

20H2

### Web Browser

Firefox

### Browser Version

105.0.1

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @andreapx thank you for your report.

This is a known issue and is being tracked at https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.

**Comment by andreapx** [comment]
Oh, wonderful! I've searched before creating the bug report but...evidently not enough...sorry!
