### ISSUE TITLE
Master password input focus delayed on opening unlock

### ISSUE THREAD

**Issue by naxxfish** [bitwarden/clients#3718]
### Steps To Reproduce

1. Log into Bitwarden Browser Extension in Chrome
2. Lock the vault by going to Settings->Lock Now
3. Click on the Bitwarden Browser Extension to open it.
4. Start typing your Master password immediately
5. Notice that the input box for the Master password only got focussed after a delay, so only a portion of your Master Password has been input

### Expected Result

I expect the Master password input box to be instantly focussed as soon as the extension opens, so I can quickly type my master password and unlock my vault.

### Actual Result

The input box does get focus, but after a short delay (maybe 1-1.5 seconds). As a result, only part of my master password is entered, and so unlocking the vault fails the first time (unless you manually focus the input box by clicking on it). 

### Screenshots or Videos

https://youtu.be/-3_W3Q4762Q

### Additional Context

This seems to have started happening recently, so expect it may be a regression. 

### Operating System

Windows

### Operating System Version

Windows 11 Pro 10.0.22000 Build 22000

### Web Browser

Chrome

### Browser Version

Version 106.0.5249.103 (Official Build) (64-bit)

### Build Version

2022.9.1

**Comment by melvyn-apryl** [comment]
Also applies to pin. I miss 1-3 keystrokes before it gets focused.

MacOS/Firefox.

**Comment by djsmith85** [comment]
Hi @naxxfish and @melvyn-apryl thank you for your reports.

This is a known issue and is being tracked at https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.
