### ISSUE TITLE
Firefox Extension does not focus PIN input field

### ISSUE THREAD

**Issue by D3SOX** [bitwarden/clients#3719]
### Steps To Reproduce

1. Set a PIN
2. Lock the vault
3. Click the extension icon

### Expected Result

The PIN input field should be focussed, just like before

### Actual Result

PIN input field is not focussed instantly, you need to manually click with the mouse or wait a few seconds

### Additional Context

I'm not sure if the culprit is within the extension or a Firefox update

### Operating System

Linux

### Operating System Version

Arch Linux rolling

### Web Browser

Firefox

### Browser Version

105.0.2

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @D3SOX thank you for your report.

This is a known issue and is being tracked at https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.

**Comment by D3SOX** [comment]
Thanks, I haven't found that issue searching for `focus` and `PIN`
