### ISSUE TITLE
Delayed focus on unlock screen focus

### ISSUE THREAD

**Issue by woutervanwijk** [bitwarden/clients#3723]
### Steps To Reproduce

Click on the web-extension button in the browser. 
The unlock screen is showed
I type my pin/password
Nothing happens, because the textbox doesn't have the focus

### Expected Result

Focussed textbox, ready for input

### Actual Result

Texbox that receives the input after one or two seconds

### Additional Context

It used to work ok
Solution: Focus it earlier (maybe try twice even)

### Operating System

macOS

### Operating System Version

12.6

### Web Browser

Safari, Firefox, Brave

### Browser Version

latest

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @woutervanwijk thank you for your report.

This is a known issue and is being tracked at https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.
