### ISSUE TITLE
User must wait for master password field to be automatically given focus

### ISSUE THREAD

**Issue by jivanpal** [bitwarden/clients#3731]
### Steps To Reproduce

1. Open Google Chrome.
2. Click the Bitwarden browser extension button whilst the vault is locked. The extension window opens and you are prompted for your master password.
3. Immediately start typing your password after the window appears. If the password is typed sufficiently quickly, notice that nothing was actually entered into the password field. If it was typed less quickly, notice that only a portion of the end of the password was actually entered into the password field.
4. Be sad/frustrated.

### Expected Result

The password field should be automatically given focus immediately after/as the extension windows appears. This was the previous behaviour.

### Actual Result

The password field is only given focus about 3–5 seconds after the window appears. If the user waits this amount of time or manually clicks the password field before it is automatically given focus, then all typing is correctly entered into the field.

### Additional Context

Thank you for the excellent product!

### Operating System

macOS

### Operating System Version

Catalina 10.15.7 (19H2026)

### Web Browser

Chrome

### Browser Version

106.0.5249.103 (Official Build) (x86_64)

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @jivanpal thank you for your report.

This is a known issue and is being tracked at https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.
