### ISSUE TITLE
Delay to focus on PIN input field

### ISSUE THREAD

**Issue by victorp13** [bitwarden/clients#3763]
### Steps To Reproduce

1. Make sure the vault is locked with a PIN
2. Click in the Bitwarden extension icon
3. Start inputting the PIN number

### Expected Result

Immediate focus on the PIN input field, so I can smoothly input the PIN number.

### Actual Result

There is a 2-3 second delay on focus on the input field from opening the dialog. This used to be almost zero delay, so something must have changed recently (last few weeks or so).

### Screenshots or Videos

Here's a small GIF recording of when the input carrot appears (takes 2-3 seconds):
![bitwarden_delay](https://user-images.githubusercontent.com/1854749/195331457-eb558b09-6747-409e-9cfc-82241c7e6eaa.gif)

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

Version 106.0.5249.103 (Official Build) (64-bit)

### Build Version

2022.9.1

**Comment by djsmith85** [comment]
Hi @victorp13  thank you for your report.

This is a known issue and is being tracked at #3562. As you can see from the linked issue, a fix has been issued and will be available with the next release 2022.10.

Closing this as duplicate.

**Comment by victorp13** [comment]
Thanks @djsmith85! Hadn't seen that Issue, thanks for pointing it out and closing this as a duplicate 👍🏼
