### ISSUE TITLE
Auto-Fill not working until page has been refreshed

### ISSUE THREAD

**Issue by erbesner** [bitwarden/clients#3770]
### Steps To Reproduce

1. Revisit a tab where the user session has timed out, after some amount of time has passed
2. Use auto-fill keyboard shortcut, or manually select vault item to auto-fill
3. auto fill fails
> keyboard shortcut while vault is locked will also fail to automatically open extension to log in

### Expected Result

using auto-fill, manual or keyboard shortcut, should work all the time

### Actual Result

auto-fill works intermittently after a user session expires and browser tab is not opened after some amount of time

### Operating System

macOS

### Operating System Version

12.6

### Web Browser

Chrome

### Browser Version

106.0.5249.103

### Build Version

2022.9.1

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment]
This issue has been resolved with the introduction of https://github.com/bitwarden/clients/pull/6826 

If any further issues arise, please let us know. Closing this thread for now.
