### ISSUE TITLE
Biometrics on launch not working

### ISSUE THREAD

**Issue by ywwry66** [bitwarden/clients#3774]
### Steps To Reproduce

1. Open `Bitwarden` desktop app

### Expected Result

Touch ID prompt will show up

### Actual Result

I have to click on `Unlock with Touch ID` to bring up the Touch ID prompt

### Operating System

macOS

### Operating System Version

12.6

### Installation method

Mac App Store

### Build Version

2022.10.0

**Comment by federicom09** [comment]
Hello @ywwry66, how are you?

Thank you for reporting this!
This is a know issue and hopefully we are going to have this fixed soon!

**Comment by ywwry66** [comment]
Thanks for your prompt reply. Feel free to close this if there is a different thread tracking the same issue.

**Comment by patrickhlauke** [comment]
same for Windows Hello

**Comment by WinterLemur** [comment]
I still have the issue with Touch ID on version 2023.1.1.

**Operating System**
macOS

**Operating System Version**
13.1

**Installation method**
Mac App Store

**Build Version**
2023.1.1

When I fully quit the desktop application -> Touch ID works the first time
When I "close to menu bar" or "minimize to menu bar" -> Touch ID won't show the prompt

_[tried multiple times to just close or minimize but it will not work until fully quit]_

**Comment by AshenPaladin** [comment]
The issue is still very much present on macOS 13.3.1 and app version 2023.4.0 (8382). Having to click on the Unlock with Touch ID button isn't an experience breaking bug, but it's still a hiccup that shouldn't be there - if the prompt would just appear from the start, using biometrics to unlock the vault would be a lot better.

**Comment by dangelion** [comment]
Still present on macOS Ventura 13.5.2 (22G91).
Please fix it, it's so annoying

**Comment by fsafq41** [comment]
I also have the same issue and it has been ongoing for the past several months and versions.
Current version with the same issue: 2023.9.3 (12828)

**Comment by zexpe** [comment]
I had this problem with 2022.10.0 (issue #3839), and it was latterly fixed, but for me it's returned with 2023.10.0! How odd!

**Comment by alex-ioma** [comment]
Confirmed. The bug is present in latest release - Version 2023.10.0 (13355)

**Comment by ywwry66** [comment]
See the latest open issue #6134 and pull request #6400.
