### ISSUE TITLE
Clicking on browser extension doesn't focus on password field

### ISSUE THREAD

**Issue by Bazzu85** [bitwarden/clients#3787]
### Steps To Reproduce

1. Lock the app
2. Click on extension to login
3. to enter the password you have to manually click on field

### Expected Result

When opening in previous versions I could insert the pass/pin directly

### Actual Result

With current version we have to manually click on pass/pin to digit it

### Operating System

Windows

### Operating System Version

10 pro

### Web Browser

Chrome

### Browser Version

Version 106.0.5249.119 (Official Build) (64-bit)

### Build Version

2022.9.1

**Comment by Morpheus0x** [comment]
I think that was fixed with 2022.10.0

**Comment by djsmith85** [comment]
Hi @Bazzu85 thank you for your report.

This is a known issue and was being tracked with https://github.com/bitwarden/clients/issues/3562. As you can see from the linked issue, a fix has been issued and is available with 2022.10.

Closing this as duplicate.

**Comment by Bazzu85** [comment]
> Hi @Bazzu85 thank you for your report.
> 
> This is a known issue and was being tracked with #3562. As you can see from the linked issue, a fix has been issued and is available with 2022.10.
> 
> Closing this as duplicate.

Thx. IDK why the extension didn't update by is self. forcing the update installed the 2022.10.0!
