### ISSUE TITLE
Too early abbreviation for item name

### ISSUE THREAD

**Issue by Morpheus0x** [bitwarden/clients#3788]
### Steps To Reproduce

1. Log in to browser extension
2. Look at the name of any item (login, card, identity or secure note) in tab or vault view
3. The item name is shortened if it is longer than 17 characters

### Expected Result

Use all the available space to display as much of the item name as possible

### Actual Result

The item name is shortened if it is longer than 17 characters

### Screenshots or Videos

![bitwarden_issue](https://user-images.githubusercontent.com/22265595/195798847-0264ae3a-ff6a-4d54-a614-5a21c7c0b400.png)

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox

### Build Version

2022.10.0

**Comment by tessus** [comment]
I have also noticed something similar with the web version 2022.10.0:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/223439/196056753-e3459875-54f7-4af8-bd9a-3ad2949d5faa.png">

All Sen...
Te..
Fi..

It does not happen with Safari or Chrome. Only with Firefox.

I don't want to hijack this topic, but rather point out that this seems to be a problem specific to Firefox.

**Comment by djsmith85** [comment]
@tessus The issue with Send filters not showing up properly was reported and addressed with https://github.com/bitwarden/clients/issues/3789. 

Once https://github.com/bitwarden/clients/pull/3792 is good to go, we are looking into releasing a fix for both issues.

**Comment by tessus** [comment]
@djsmith85 thanks a bunch. I marked my comment as outdated. sorry for the noise.
