### ISSUE TITLE
"Ask for Windows Hello on launch" function doesn't work anymore after last update

### ISSUE THREAD

**Issue by powern3rd** [bitwarden/clients#3799]
### Steps To Reproduce

To reproduce:

1. Be sure that under Settings > Security, Both "Unlock with Windows Hello" & "Ask for Windows Hello on launch" are selected.
2. Close the app
3. Open the app

### Expected Result

Expected result: Windows Hello launches automatically when launching the Desktop app.

Since the last update, while opening the Bitwarden desktop app on Windows (11), Windows Hello is not popping up automatically anymore. To log in with Windows Hello, you now first have to click on the "Unlock with Windows Hello" button before Windows Hello is showing up. 

So, the option under Settings > Security > Unlock with Windows Hello > Ask for Windows Hello on launch is not working anymore. 

I tried to deselect both options and restarted the app, selected both options again and started the app again without the expected results. Have this issue on my 3 Windows 11 PCs.

### Actual Result

To log in with Windows Hello, you now first have to click on the "Unlock with Windows Hello" button before Windows Hello is showing up.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/25515495/195995387-ceed4c02-a198-4ff3-ad8d-fbfcdfc307b9.png)
![image](https://user-images.githubusercontent.com/25515495/195995414-d64d8edd-aacd-4b59-a7a6-fd38bdeb3373.png)
![image](https://user-images.githubusercontent.com/25515495/195995575-04c78f55-d1fc-4b06-8f17-4784271b509b.png)

### Operating System

Windows

### Operating System Version

22H2 (OS Build 22621.674)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.0

**Comment by djsmith85** [comment]
Hi @powern3rd and thank you for your detailed report.

Closing this as a duplicate of https://github.com/bitwarden/clients/issues/3774
