### ISSUE TITLE
Auto-fill does not work for EdgeMax OS form in Safari

### ISSUE THREAD

**Issue by bverkron** [bitwarden/clients#3801]
### Steps To Reproduce

1. Go to web interface for EdgeMax OS (for example on an EdgeRouter X) in Safari on macOS.
 macOS 11.7 (20G817)

2. Attempt to autofill credentials

### Expected Result

Credentials get auto-fill either automatically when the page loads (I have that enabled and it works on other sites) or at least when I click the Auto-fill button in the extension, which also works on other sites. Both work with Chrome.

### Actual Result

Gives error 
![image](https://user-images.githubusercontent.com/19174503/196005004-43234c84-61b0-4e66-8ee3-627ffdcbd6f1.png)

### Screenshots or Videos

<img width="333" alt="image" src="https://user-images.githubusercontent.com/19174503/196005250-891476d5-caaa-440e-bece-a35cf054571d.png">

### Additional Context

Form in Chrome

```html
<form id="LoginForm" method="post" class="ui-form" data-bitwarden-watching="1">
              <input id="Username" name="username" class="text-input" type="text" placeholder="Username" autocapitalize="off" autocorrection="off">
              <input id="Password" name="password" class="text-input" type="password" placeholder="Password">

              <input id="LoginButton" class="submit-input ui-button ui-widget ui-state-default ui-corner-all" type="submit" value="Login" role="button" aria-disabled="false">
            </form>
```

Form in Safari
```html
<form id="LoginForm" method="post" class="ui-form">
              <input id="Username" name="username" class="text-input" type="text" placeholder="Username" autocapitalize="off" autocorrection="off">
              <input id="Password" name="password" class="text-input" type="password" placeholder="Password">

              <input id="LoginButton" class="submit-input ui-button ui-widget ui-state-default ui-corner-all" type="submit" value="Login" role="button" aria-disabled="false">
            </form>
```

HTML looks the same when copied from  browser dev tools but Safari visually shows some "shadow content" section. Not sure if they are interfering or if they're just rendered in developer view.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/19174503/196005341-40d0200f-32f0-4282-a414-11f1ab9c1932.png">

### Operating System

macOS

### Operating System Version

11.7 (20G817)

### Web Browser

Safari

### Browser Version

Version 16.0 (16614.1.25.9.10, 16614)

### Build Version

Version: 2022.8.0

**Comment by bverkron** [comment]
Ok, this is very strange. This hasn't been working for weeks. I've had several browser restarts and even full computer restarts and it would never work in Safari. After switching to chrome using auto-fill while debugging and writing up this issue it now works in Safari. I did literally nothing else in between it not working and it now working. Just switch to Chrome, auto-fill worked, switched back to Safari and now auto-fill works there too.

I suppose we could close this but I'm curious if anyone else can replicate the issue I was having. Maybe an intermittent bug?

**Comment by bverkron** [comment]
Looks like it might have been a refresh issue. The issue came back again and after I refresh the page after trying to fill a couple times the auto-fill worked but it won't work on initial page load for some reason

**Comment by TroyBW** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

The issue here will be closed.

Thanks!
