### ISSUE TITLE
Report fake-website: vault.bitwarde.com

### ISSUE THREAD

**Issue by josias-r** [bitwarden/clients#3810]
Not really a bug report, sorry for the inconvenience, but I didn't really want to go through an unnecessary contact form or process.

Just wanted to report that the website at https://vault.bitwarde.com/ is using your domain name just with a missing "e".

I think they use it to generate ad revenue, nothing more serious, but still I wanted to report it :D

**Comment by djsmith85** [comment]
Hi @josias-r, thank you for raising this. I have passed this onto the team.

We use GitHub issues as a place to track bugs and other development related issues, and as the information has been passed on, I'll close this now.
