### ISSUE TITLE
Update password form does not check if the new password is set as password hint

### ISSUE THREAD

**Issue by stefan0xC** [bitwarden/clients#3821]
### Steps To Reproduce

1. Go to Account settings
2. Click on Security
3. Fill out your current password in all the fields (also as password hint).
4. Click on 'Change Master Password'
5. Request a password hint

### Expected Result

I expect the form to recognize and prevent setting my password as the password hint (as it does while signing up).

### Actual Result

I get an email with my current password as password hint.

### Additional Context

Noticed this when checking the implementation of Vaultwarden but it's possible in vault.bitwarden.com as well.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Firefox

### Browser Version

105.0.3

### Build Version

Version 2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bwjohnson207** [comment]
I also just noticed this issue after helping a user set up their account and stopping them from using their password as the hint.  I wasn't sure if BitWarden would deny the password change so I recreated it with a test account and it does allow the password hint to be the same as the password.

**Comment by tessus** [comment]
TBH, moving the password hint from `Account` to `Security > Master Passpword` was a design error. This also means that one cannot update or remove their password hint unless they set a new password.

You can choose the same password as the one, but still. It is a heck of a workaround to update/remove your password hint. Yes, usually it is not necessary to update it, but what if you have a type in there? Or, if you choose to remove it altogether? The issue with this workaround is that you are still kicked out of active sessions.

Maybe there should be a separate button next to the hint field (`Change hint`).

**Comment by Tipoff4317** [comment]
Also, if you fill in the form with the **browser extension**, the extension will fill all the password fields, **plus the password hint field, with the current password.**  If the user hits submit without really changing the password, voila, the password hint, presumably **_stored as clear text or in an accessible form_** (not encrypted with user's key), is out there.  **I bet this already happens**: either the user stores the current password as password hint, or stores the previous password (which, assuredly, the current version of the password may be a derivative of).   

If BW ever has user vault breach, or has rogue employees with access, those users are going to have total vault breaches.  So much for zero-knowledge architecture if it's likely to store passwords in the clear for certain sub-population.

**Comment by stefan0xC** [comment]
Seems to have been fixed by #4635
