### ISSUE TITLE
The organizational Export function in the Web Vault always exports an Account Backup encrypted .json.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#3827]
### Steps To Reproduce

1. Log into your Bitwarden account via the Web Vault (https://vault.bitwarden.com/#/).
2. Navigate to your organizational vault and attempt to export it out to a Password Protected encrypted .json file.

### Expected Result

To export a password-protected file which can be imported into other Bitwarden vaults/accounts.

### Actual Result

The output is a .json file which is encrypted with the vault's encryption key (Account Backup) and cannot be imported into other vaults/accounts.

### Screenshots or Videos

N/A.

### Additional Context

The organizational Import function supports password-protected .json files. The CLI's Export function is able to export a password protected .json file from an organizational vault.

### Operating System

Windows

### Operating System Version

22H2.

### Web Browser

Firefox

### Browser Version

105.0.3.

### Build Version

2022.10.0.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@SergeantConfused: I have just tried to reproduce this and was unable to. Exporting a password-protected file from one org, creating a new account and org, then importing the password-protected file, worked fine. 

Closing this now.
