### ISSUE TITLE
GitHub: New issue choose > Feature Request link is dead (OffTopic)

### ISSUE THREAD

**Issue by HRIT-Florian** [bitwarden/clients#3832]
### Steps To Reproduce

1. Click to github > new issue
2. On the Issue chose page, the feature reqeust link is dead
https://community.bitwarden.com/c/feature-requests/
**Connection to the server hosting the URL fails.**

@Admins, feel free to take out the wrong label, unfortunately there was no other choice. Many thanks 🤘

**Comment by djsmith85** [comment]
Hi @HRIT-Florian, 

Thank you for reporting this. 

The community forums are currently experiencing some issues. 

I have passed the information on to the team and it will hopefully be available again, shortly.
