### ISSUE TITLE
Import from Nordpass CSV does not start when clicking import button

### ISSUE THREAD

**Issue by loovanloon** [bitwarden/clients#3847]
### Steps To Reproduce

1. Export your vault from Nordpass (version 4.32.8.31079) as a CSV-file to your local drive
2. Open Vaultwarden in your browser
3. Go to the import section of Vaultwarden
4. Select the Nordpass profile
5. Select the Nordpass-export CSV (see step 1)
6. Click on 'import button'

### Expected Result

The import function starts and the Nordpass export CSV file gets imported.

### Actual Result

The import does not start. 
The Nordpass-export CSV file is not imported
The only visible feedback is the button-down-up-effect from the import button when you click it.

### Additional Context

When I imported the nordpass-export-csv-file with a **non-nordpass profile** an import-action took place, but resulted in the creation of folders in Bitwarden. I can’t remember which profile I took (one of the major players I guess)

### Operating System

Windows

### Operating System Version

Windows 11 Pro - 22H2 - build 22621.675

### Web Browser

Chrome, Microsoft Edge, Firefox

### Browser Version

Microsoft Edge Versie 106.0.1370.47 (Officiële build) (64-bits), Chrome is up-to-date Versie 106.0.5249.119 (Officiële build) (64-bits), Firefox 105.0.3 (64-bits), Firefox Developper 107.0b2 (64-bit)

### Build Version

Bitwarden Inc. (Powered by Vaultwarden) Versie 2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by loovanloon** [comment]
Tested this also with official Bitwarden account. Same results.  

[https://community.bitwarden.com/t/import-from-nordpass-csv-does-not-start-when-clicking-import-button/45450/8?u=loovanloon](url)

**Comment by djsmith85** [comment]
Hi @loovanloon,

Could you please try and export from the Nordpass web vault (4.32.10) and see if the import works with that file. I suspect the file might be corrupted or the format may differ on your older desktop version.

I have just tested an import with a freshly exported `nordpass.csv` from their web-vault and the import worked fine.

Just in case, [here](https://bitwarden.com/help/import-data/) is a link to our help-site documenting the import process.

In case the import does not work, could you please also check the browser console for any errors and report back.

**Comment by loovanloon** [comment]
Hi Daniel,

 

Thank you for your help. In the console I found out that the problem is on my server configuration (Error: WebSocket failed to connect.) I’ll have to fix that.

 

Van: Daniel James Smith ***@***.***> 
Verzonden: zaterdag 22 oktober 2022 10:56
Aan: bitwarden/clients ***@***.***>
CC: loovanloon ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [bitwarden/clients] Import from Nordpass CSV does not start when clicking import button (Issue #3847)

 

Hi @loovanloon <https://github.com/loovanloon> ,

Could you please try and export from the Nordpass web vault (4.32.10) and see if the import works with that file. I suspect the file might be corrupted or the format may differ on your older desktop version.

I have just tested an import with a freshly exported nordpass.csv from their web-vault and the import worked fine.

Just in case, here <https://bitwarden.com/help/import-data/>  is a link to our help-site documenting the import process.

In case the import does not work, could you please also check the browser console for any errors and report back.

**Comment by loovanloon** [comment]
In the console I found out that the problem is on my server configuration (Error: WebSocket failed to connect.) I’ll have to fix that.

**Comment by djsmith85** [comment]
@loovanloon: Thank you for reporting back. If you are able to resolve your server issue and you are still not able to import, feel free to comment here and we'll re-open. Please provide further details if possible.

Closing this now.
