### ISSUE TITLE
NPM install of CLI very slow under WSL, standalone binary works fine

### ISSUE THREAD

**Issue by ruan-dt** [bitwarden/clients#3848]
### Steps To Reproduce

CLI installed using `npm install -g @bitwarden/cli`

Run a `bw` command like `--version` or `login` or `unlock`.

### Expected Result

Commands should execute promptly. For example, with the standalone binary from from https://vault.bitwarden.com/download/?app=cli&platform=linux I can run `time ./bw list items` and see that it takes under a second.

```
real    0m0.844s
user    0m0.836s
sys     0m0.116s
```

### Actual Result

 `time bw list items` returns

```
real    0m53.655s
user    0m4.441s
sys     0m4.337s
```

Even `bw --version` can take over 40 seconds, and that presumably isn't doing any IO or cryptography!

### Additional Context

Both standalone and NPM-installed `bw` are version 2022.10.0.

Everything seems to work just fine in both cases.. I can log in with username/password or API key, unlock the vault, view its contents... it is just unbearably slow if I'm using the NPM-installed version

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.1 LTS, running on WSL2 under Windows 10

### Shell

Bash

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @ruan-dt,

This is likely an upstream issue with wsl/node.

Possibly more information can be found here: https://github.com/microsoft/WSL/issues/7254

If you have more information that this is specific to the Bitwarden CLI, please comment and we'll re-open.

Closing this now.
