### ISSUE TITLE
Disrupting reminder at startup

### ISSUE THREAD

**Issue by DirkTaggesell** [bitwarden/clients#3853]
### Steps To Reproduce

When I start Bitwarden and want to quickly unlock it by typing in my passphrase, there's always the update reminder popping up interrupting the typing which is very annoying. 

And neither do I want to wait everytime I start the software just for the reminder to having finally popped up so I can type in my passphrase. 

I understand that it is important to install updates, but this reminder is interrupting quick usage and doesn't have to be this way.

Equally annoying: first the software sends me to github for filing a bug, when I then chose "Feature request" (because it can be argues that what I'm reporting is not really a bug) I get send to the bitwarden site where I can NOT use my bitwarden account but are forced to create a new one. 

### Expected Result

Reminder that is not interrupting typing in my passphrase.

### Actual Result

When I start Bitwarden and want to quickly unlock it by typing in my passphrase, there's always the update reminder popping up interrupting the typing which is very annoying. 

### Additional Context

Suggestion: chose a less intrusive way to remind of updates than a modal pop-up.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@DirkTaggesell: Thank you for your report. 

This issue is already being tracked with https://github.com/bitwarden/clients/issues/2608

Closing this as duplicate
