### ISSUE TITLE
Card Number is displayed as correct block when hidden, but not when visible

### ISSUE THREAD

**Issue by SwissOS** [bitwarden/clients#3859]
### Steps To Reproduce

1. Go to 'Card'
2. Click on 'a credit card'
3. Check that number is  '•••• •••• •••• •••• •••' (and note the extra 3 dots at the end of the 4 by 4 block)
4. Click on 'Toggle Visibility'
5. Card number is not shown as entered originally (4 blocks of 4 digits), but as '1234 123 4 12 34 1 234'

### Expected Result

Card number should be displayed as:
1234 1234 1234 1234

### Actual Result

Card number is not shown as entered originally (4 blocks of 4 digits), but as '1234 123 4 12 34 1 234'

### Additional Context

MacOS desktop app Version 2022.10.0 (4964)

### Operating System

macOS

### Operating System Version

MacOS 12.6 (Monterey)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.0 (4964)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@SwissOS Thank you for your report.

Could you please check if any spaces or non-printable characters are included in the card-number.

We currently use a [directive](https://github.com/bitwarden/clients/blob/master/libs/angular/src/pipes/credit-card-number.pipe.ts) to visually separate the card-number based on some known and supported brands. So if your card-number has the wrong amount of digits or is of a currently unsupported brand the spacing would be off.

Please check and report back

**Comment by SwissOS** [comment]
Oh, I see now! I did indeed enter the card number with spaces when I created it.
I edited it to append all the numbers together and it displays correctly in the 4x4 blocks now. Thank you and sorry for the erroneous bug report!
