### ISSUE TITLE
macOS client doesn't respond correctly to OS Hide command

### ISSUE THREAD

**Issue by ozlanus** [bitwarden/clients#3878]
### Steps To Reproduce

1. Open macOS client app
2. Open another macOS app
3. Give focus to macOS client app
4. Bitwarden menu > Hide Bitwarden

### Expected Result

Bitwarden app (all windows) should be completely hidden, and app remains running in the background - standard macOS windowing behaviour

### Actual Result

- Bitwarden app loses focus, but its windows remain visible (incorrect behaviour)
- There also appears to be an issue with Bitwarden windows not respecting normal macOS window behaviours and causing focus issues. In the attached video you can see that after the initial attempt to Hide Bitwarden, the Microsoft Edge window is brought to the front - since it's the only remaining visible app. However the Edge > Hide Microsoft Edge menu item is disabled, which is indicates that the system doesn't see that Edge now has focus. It's only once you click again into the Edge window that menu item appears enabled again, as expected.
- Also note "Hide Others" command (when activated form another app that has focus) does not work on Bitwarden window when it's in the background, either

### Screenshots or Videos

https://user-images.githubusercontent.com/55814374/197369978-f643a239-1178-4f62-97e0-1cec2e3a689d.mp4

### Operating System

macOS

### Operating System Version

13.0 (22A380) - also occurred on macOS 12.x

### Installation method

Mac App Store

### Build Version

2022.10.1 (5129)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Larry-Sussman** [comment]
Hi @ozlanus, thanks for the report!

I'm unable to reproduce this issue on macOS 12.1 and the latest desktop app, both the "Hide Bitwarden" and "Hide Others" (from another app) options are correctly hiding the desktop app window. 

I'm not sure what's going on here, but some further troubleshooting would likely be better handled by our dedicated Customer Success team. Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content. Thank you!

**Comment by ozlanus** [comment]
Narrowed it down in past couple of days: issues described occur only when the menu bar item / option is active. Some combination of minimise to/hide to/display menu bar item interferes with normal macOS hide function.

**Comment by Krychaz** [comment]
Unable to reproduce on Ventura, even after the more specific instructions. Client hides as expected.

**Comment by pbx-finetune** [comment]
I'm seeing this behavior on Sequoia 15.5 (24F74).

For me, the problem happens regardless of whether the menu bar icon is active or not.

When the menu bar icon is active, clicking it _does_ toggle visibility of the BW window.

**Cmd-H** and **File > Hide** both fail to hide the window — they cycle to the next app, backgrounding the BW window but not hiding it.

Bitwarden version 2025.2.1 (38769)
