### ISSUE TITLE
Misleading text while unlocking the extension

### ISSUE THREAD

**Issue by knhash** [bitwarden/clients#3890]
### Steps To Reproduce

1. Set a PIN to unlock the vault, lock the vault
2. Click on the extension icon to unlock it
3. The message reads `"...Verify your master password..."`

### Expected Result

The message should instead read `"...Verify your PIN..."` when a PIN is set.

### Actual Result

The message reads `"...Verify your master password..."`

### Screenshots or Videos

![Screenshot_20221025_140125](https://user-images.githubusercontent.com/8710439/197725548-b3eb50af-7486-4cb0-9c46-5d498826d8b6.png)

### Operating System

Windows

### Operating System Version

22H2

### Web Browser

Firefox

### Browser Version

106.0.1

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lrbn86** [comment]
I think this might be a localization issue and Bitwarden uses [Crowdin](https://crowdin.com/project/bitwarden-browser) for their localization effort.

I looked into the [lock.component.html](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/popup/accounts/lock.component.html#L58) file for vault lock. From there, I noticed an inconsistency in the messages.json for "yourVaultIsLocked" in [en](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/_locales/en/messages.json#L344), [en_GB](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/_locales/en_GB/messages.json#L344), and [en_IN](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/_locales/en_IN/messages.json#L344).

I also looked into other languages such as in [de](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/_locales/de/messages.json#L344) and found that it may also translate to "verify master password". In [es](https://github.com/bitwarden/clients/blob/41d6b6bd2168ae65cdb6e3ae28e4e16b633fe09b/apps/browser/src/_locales/es/messages.json#L344), it seems to translate to "verify identity to continue". So in some languages, there is a mix between "verify identity to continue" or "verify master password to continue".

**Comment by djsmith85** [comment]
@knhash Thank you for the report. This will be fixed in the next release.

@lrbn86 Good catch on the translation issue! The source(en) did get changed to `Your vault is locked. Verify your identity to continue` but the translations for en_GB and en_IN were still showing the old translation. I have updated `en_GB`, `en_IN` and `de` but there are probably still translations in other languages that are based on the old value. The remaining will likely be reported/fixed within Crowdin
