### ISSUE TITLE
Can only update when prompted. Check for updates doesn't work. Always interrupts workflow.

### ISSUE THREAD

**Issue by michael-mcdonald-at-prophet** [bitwarden/clients#3899]
### Steps To Reproduce

1. open app
2. check for updates because you've been interrupted enough times now you just want to get it over with
3. no updates I guess because nothing happens
4. enter password
5. GET INTERRUPTED AND PROMPTED
6. IF you say no
7. check for updates later so you don't get interrupted again
8. "no updates"

### Expected Result

Let me update manually. I don't like the constant interruptions every time I open the app because when I am opening the app and entering my password it is because I WANT TO USE IT RIGHT THEN.

### Actual Result

If I try to check for updates before entering password, there are none.
If I say NO when I'm prompted (because I need to USE the app not restart it yet again), no updates either
I can only update after you interrupt me to prompt me, which is always AFTER I have entered a password.
You don't need me to enter my very long secure password in order to tell me there are updates and I should restart and enter that password again.
So annoying.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.10.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @michael-mcdonald-at-prophet, Thank you for your report.

This issue is currently being tracked with https://github.com/bitwarden/clients/issues/2608.

I'm closing this issue now, as duplicate.
