### ISSUE TITLE
Client does not overwrite existing file when downloading attachements

### ISSUE THREAD

**Issue by coroiu** [bitwarden/clients#3921]
### Steps To Reproduce

1. Create a file on your computer
2. Open Bitwarden desktop client
3. Download attachement
4. Choose file you created in step 1
5. Choose "overwrite" when asked

### Expected Result

File is overwritten with the new downloaded results

### Actual Result

Two alternatives:

1. Client informs user that it does not support overwriting
or
2. File contents are changed and contain the newly downloaded results 

### Operating System

macOS

### Operating System Version

12.4

### Installation method

Mac App Store

### Build Version

Version 2022.10.1 (5129)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

I am unable to replicate this issue. In my testing the file gets overwritten correctly. If you still see this behaviour please contact our support team - https://bitwarden.com/contact/
