### ISSUE TITLE
bw get folder fails when unlocked, succeeds when locked

### ISSUE THREAD

**Issue by aptly-io** [bitwarden/clients#3930]
### Steps To Reproduce

Using bitwarden-cli on MacOS 12.6.1
`bw --version` gives 2022.10.0 (it is installed and updated with brew)
Log in with api key (user_id, secret_id and master password).
exported the `$BW_SESSION` after logging in with api key.
Using `bw --raw get folder <existing-id>` fails.
Then locking the db with `bw lock`and invoking the same `get folder` succeeds after first entering the master password.

What might be the difference between `get folder` while having the DB unlocked through the BW_SESSION and the exact same command with on a locked bw but supplying the master password?

Is there some cache that one can clean inbetween bw updates?

### Expected Result

`get folder` on an existing id should succeed no matter how the db is unlocked I would think?

### Actual Result

Getting a `Not found.`instead

### Operating System

macOS

### Operating System Version

12.6.1

### Shell

Bash

### Build Version

2022.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by aptly-io** [comment]
@djsmith85 How can I check this? How can I easily install bw cli on MacOS?

PS brew seems to still use the old version.

Thank you!

**Comment by djsmith85** [comment]
@aptly-io The changes made in the linked PR are part of 2022.12, which has not been released yet. The build artifacts can be found [here](https://github.com/bitwarden/clients/actions/runs/3488009991)

I recommend using those build artifacts **only for testing** purposes! This is a pre-release and you might experience other issues.

**Comment by aptly-io** [comment]
@djsmith85 I noticed several other products already released for 2022.12 (web, desktop, browser, ...). Any idea if/when there will be a release for CLI?

Thank you!

**Comment by djsmith85** [comment]
@aptly-io: Unfortunately, the CLI won't be part of the 2022.12 releases. The next scheduled release is 2023.1 (~mid-January) which will include the linked changes.

**Comment by tamsky** [comment]
Thanks for fixing this!

I can confirm the bug is fixed when using the [above-linked test build](https://github.com/bitwarden/clients/actions/runs/3488009991) `bw` binary within (`bw-macos-2022.10.0.zip`).
