### ISSUE TITLE
BW CLI REST API open to all users on host (or worse) once unlocked

### ISSUE THREAD

**Issue by ggiesen** [bitwarden/clients#3932]
### Steps To Reproduce

1. Start bw with serve option: `bw serve`
2. Unlock the vault: 
```
$ curl --request POST \
  --url http://127.0.0.1:8087/unlock \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --data '{
	"password": "CorrectHorseBatteryStaple"
  }'
```
3. Get a list of all items:
```
$ curl --request GET \
  --url http://127.0.0.1:8087/list/object/items \
  --header 'Accept: application/json'
```
Once the vault is unlocked, the BW REST API doesn't require any sort of session key (as the CLI does), cookie, or anything else, so any user on the machine (or anywhere if `--hostname` is set to a non-localhost address) can access the entire vault. This is a terrible implementation for any type of multiuser machine.

Is there some reason such a basic security measure was overlooked, especially since you already had it implemented in the CLI commands?

### Expected Result

Expected to have to pass the session key returned by `/login` in the `raw` field as an HTTP header to continue be able to access items in the vault:

```
$ curl --request GET \
  --url http://127.0.0.1:8087/list/object/items \
  --header 'Accept: application/json' \
  --header 'Authorization': 'Bearer <session_token>'
```

### Actual Result

No additional authentication is required. Once vault is unlocked, it's accessible to all users on host

### Operating System

Windows, macOS, Linux

### Shell

Bash

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ggiesen** [comment]
For what it's worth, I've found a workaround that at least decreases the surface area of this weakness. `iptables` can be configured to block connections based on user ID.  So if the `bw serve` instance is running on localhost on port 8087 (the default), you can limit access to this port by using the following:

_Plain iptables_:
```
iptables -I OUTPUT 1 -o lo -p tcp --dport 8087 --match owner --uid-owner 0 -j ACCEPT
iptables -I OUTPUT 2 -o lo -p tcp --dport 8087 -j REJECT
ip6tables -I OUTPUT 1 -o lo -p tcp --dport 8087 --match owner --uid-owner 0 -j ACCEPT
ip6tables -I OUTPUT 2 -o lo -p tcp --dport 8087 -j REJECT
```

_firewalld_:
```
firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -o lo -p tcp --dport 8087 -m owner --uid-owner 0 -j ACCEPT
firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 1 -o lo -p tcp --dport 8087 -j REJECT
firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 0 -o lo -p tcp --dport 8087 -m owner --uid-owner 0 -j ACCEPT
firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 1 -o lo -p tcp --dport 8087 -j REJECT
```

**Comment by wollew** [comment]
I just found out about `bw serve`, why does this issue not even have a single reaction to it? I would expect at least having a big fat warning in the documentation about this.

**Comment by maximiliangarmatsch** [comment]
Any update on this??

**Comment by micahblut** [comment]
Thanks for raising this issue. The vault management API is not intended to be used outside of a tightly controlled environment. This is why it serves over http and not https. We require authentication starting up the server, but this is for use by appropriately scoped machine accounts. We recommend using the CLI for remote or multi-user machines.
