### ISSUE TITLE
If "Minimize after copying" and "Ask master password again" is activated, the program minimizes even it didn't copied

### ISSUE THREAD

**Issue by christian179717** [bitwarden/clients#3943]
### Steps To Reproduce

1. Activate "Minimize after copying" in the settings section in the settings.
2. Use a login with "ask master password again".
3. Click the "Copy Password" button.

### Expected Result

The program shows the field for the master password before minimizing.

### Actual Result

It minimizes so you have to maximize it before you can enter the master password.

### Operating System

Linux

### Operating System Version

Mint 21 Cinnamon

### Installation method

Snap

### Build Version

Version 2022.10.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @christian179717 and thank you for your report.

This issue is already being tracked with https://github.com/bitwarden/clients/issues/3235

Closing this as duplicate.
