### ISSUE TITLE
"Remember email" checkbox label isn't clickable

### ISSUE THREAD

**Issue by fromaline** [bitwarden/clients#3945]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/login
2. Click on the "Remember email" label

### Expected Result

Checkbox changes its state when clicking on the "Remember email" label.

### Actual Result

Checkbox does not change its state when clicking on the "Remember email" label. Only checkbox itself works.

### Screenshots or Videos

From Chrome on macOS:

https://user-images.githubusercontent.com/55146773/199336536-b39423d0-ae37-418a-bf30-a71f2da94474.mov

### Additional Context

1. Bug is most likely reproducible on any operating system in any browser.

2. Checkbox's label should be clickable according to [accessibility guidelines](https://www.a11ymatters.com/pattern/checkbox/#associating-the-label-with-the-input).

3. I'd be happy to help fix this bug.

### Operating System

macOS, Linux

### Operating System Version

macOS 12.4, Ubuntu 20.04

### Web Browser

Chrome, Safari, Firefox, Brave

### Browser Version

Chrome 106.0.5249.119, Safari 15.5 (17613.2.7.1.8), Firefox 106.0 (64-bit), Brave v1.45.113

### Build Version

2022.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@fromaline Thank you for your report and offering your help to fix this.

As a starting guide please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/). These will get you started with setting up your development environment.

Please reference this issue when you create a pull request.

**Comment by fromaline** [comment]
Get it, thanks.

**Comment by ssrihari4102** [comment]
@fromaline I was wondering if you are still working on this? If not I might be able to give it a try.

**Comment by fromaline** [comment]
@ssrihari4102, go, give it a try! I'm busy at work, so nothing had been done :)

**Comment by CeedRenon** [comment]
Did they fix it? I would love to work on this one!

**Comment by M27afk** [comment]
Hey! Can I get to work on this?

**Comment by fromaline** [comment]
Is it question for me?

**Comment by M27afk** [comment]
Yes, would you assign this issues to me?

**Comment by fromaline** [comment]
It's not my repo, I just created the issue. You may work on this, if you want to!

**Comment by djsmith85** [comment]
Hi @ssrihari4102 and @M27afk, thank you for your interest in helping to fix this.

As mentioned before https://github.com/bitwarden/clients/issues/3945#issuecomment-1301012973:  
The [Contribution guidelines](https://contributing.bitwarden.com/) are a great starting point. Those include instruction on how to setup your development environment and also includes more information about the [Component Library and usage of Tailwind](https://contributing.bitwarden.com/code-style/tailwind/) in the web-vault.

We really appreciate and welcome all contributions. 
Once you have developed and tested your solution locally, please feel free to create a pull request and mention this issue.
