### ISSUE TITLE
F-secure Key Import only takes credit cards

### ISSUE THREAD

**Issue by clandtma** [bitwarden/clients#3966]
### Steps To Reproduce

Importing F-secure Key exported file .fsk
Import successful, says data added to vault
When refreshing vault only credit cards visible, no web services
[ExportedPasswords.zip](https://github.com/bitwarden/clients/files/9933183/ExportedPasswords.zip)

### Expected Result

See "Credit Card" in the list, but would be expecting also "Adobe" as web service when using attached demo .fsk-file.

### Actual Result

See only "Credit Card".

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/117401001/199839396-fac6d8b0-4d32-4cf8-ab9e-f7e068c64981.png)

### Additional Context

Exported .fsk-file from KEY 3.11.2022

### Operating System

Windows

### Web Browser

Chrome

### Build Version

Version 2022.10.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @clandtma thank you for your report and also for providing an example file.

I have had a look at the file and can confirm it's the same issue as https://github.com/bitwarden/clients/issues/2801.

As you can see on there, a [Pull Request](https://github.com/bitwarden/clients/pull/3877) is already attached, which will address that issue.

I'm going to close this as duplicate.

**Comment by clandtma** [comment]
Thank you @djsmith85 and sorry for missing #2801 before submitting. When is #2801 / #3877 expected to be published?

**Comment by djsmith85** [comment]
No worries @clandtma. PR #3877 is ready for code review. Earliest point to include this, will be the 2022.12 release (~mid December).

**Comment by clandtma** [comment]
Thanks @djsmith85. Is there some relatively easy work-around in the meantime to get an .fsk-file imported?

**Comment by djsmith85** [comment]
@clandtma 
The .fsk-file can be edited with any text-editor. It's essentialy just a json-file with a vendor-specific file-extension (.fsk).

1. Open the *.fsk-file with a text-editor
2. Ensure it does not change the Encoding (UTF-8)
3. Identify an item you'd like to add as a login and set the style-property to `"website"`. In your example file it would be replacing `"style":"initials"` with `"style":"website"`
4. dentify an item you'd like to add as a credit-card and set the style-property gto `"creditcard"`
5. Save the file 
6. Import via the web-vault into Bitwarden.

Kind regards,
Daniel

**Comment by clandtma** [comment]
Thank you @djsmith85 works like a charm
