### ISSUE TITLE
Extension on Brave opens half of the height

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#3970]
### Steps To Reproduce

1. Install Bitwarden extension on Brave
2. Log in to your account
3. Click the icon to open the pop-up

### Expected Result

The pop-up opens at the normal full height

### Actual Result

the pop-up opens at half of the normal height with a vertical slider. Occasionally, it will open at full height.

### Screenshots or Videos

<img width="416" alt="Screen Shot 2022-11-04 at 9 29 11 AM" src="https://user-images.githubusercontent.com/75601583/199865891-49c081b0-d006-4205-83bf-0972cdf6ab75.png">

### Operating System

macOS

### Operating System Version

12

### Web Browser

Brave

### Browser Version

1.45.116. Chromium 107.0.53

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Workaround:

1) Open brave://flags

2) Search for 'fingerprinting'

3) Find 'Block screen fingerprinting' and set it to 'Disabled'

4) Restart Brave browser

**Comment by djsmith85** [comment]
Same issue as with Firefox, reported with https://github.com/bitwarden/clients/issues/1451

**Comment by rob4226** [comment]
It kinda sucks to have to disable a privacy feature to make this work. Is there a way we can fix this? If not, maybe add an option to allow manually setting the height of the popup in the extension settings?  I'd be willing to work on it.

**Comment by djsmith85** [comment]
Linking to upstream issue https://github.com/brave/brave-browser/issues/26715

**Comment by acro5piano** [comment]
@Greenderella Thank you, it works!

**Comment by syntaxseed** [comment]
I'd think of this as an enhancement - I'd like to resize the popup manually and have it save the size for next time. The narrow width bothers me as well as this height bug and I'd like the extension to take better advantage of my screen size.

**Comment by djsmith85** [comment]
Closing this now, as the upstream issue has received a fix and will be available as of Brave `1.45.131`
 
@syntaxseed, (@exostin, @acro5piano, @silencebow): Thank you for your input on this.  Could you please comment and upvote on the existing [feature request](https://community.bitwarden.com/t/allow-to-extend-width-of-popup-widget-and-customize-default-width/29167/1) on our Community forums
