### ISSUE TITLE
BW CLI REST API retrieving templates produces an HTTP 404 Not Found

### ISSUE THREAD

**Issue by ggiesen** [bitwarden/clients#3982]
### Steps To Reproduce

1. Start bw with serve option: `bw serve`
2. Retrieve the template: 
```
$ curl --request GET \
>   --url http://127.0.0.1:8087/template/item \
>   --header 'Accept: application/json' \
>   --header 'Content-Type: application/json'
Not Found
```

It doesn't matter if the vault is unlocked or not.

Retrieving templates works on the command line (although curiously requires entering the master password):

```
bw get template item
? Master password: [hidden]
{"organizationId":null,"collectionIds":null,"folderId":null,"type":1,"name":"Item name","notes":"Some notes about this item.","favorite":false,"fields":[],"login":null,"secureNote":null,"card":null,"identity":null,"reprompt":0}
```

### Expected Result

```
$ curl --request GET \
>   --url http://127.0.0.1:8087/template/item \
>   --header 'Accept: application/json' \
>   --header 'Content-Type: application/json'
{"organizationId":null,"collectionIds":null,"folderId":null,"type":1,"name":"Item name","notes":"Some notes about this item.","favorite":false,"fields":[],"login":null,"secureNote":null,"card":null,"identity":null,"reprompt":0}
```

### Actual Result

```
$ curl --request GET \
>   --url http://127.0.0.1:8087/template/item \
>   --header 'Accept: application/json' \
>   --header 'Content-Type: application/json'
Not Found
```

### Additional Context

nodejs-18.12.0 from nodesource repo. Used npm to install.

### Operating System

Linux

### Operating System Version

AlmaLinux release 8.6 (Sky Tiger)

### Shell

Bash

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ggiesen** [comment]
This seems to be an issue with the npm version of `bw`. If I install the pre-built binary, it works fine (both CLI and REST API)

**Comment by ggiesen** [comment]
Tested with NPM and single-binary install. Same issue with both

**Comment by ggiesen** [comment]
With the caveat that I'm not a JavaScript developer, looking at https://github.com/bitwarden/clients/blob/master/apps/cli/src/commands/serve.command.ts I don't see a router implemented for `/template`

**Comment by ggiesen** [comment]
So this looks like it's a documentation issue. [This page](https://bitwarden.com/help/vault-management-api/) says the endpoint should be `/template/{type}`, when in fact it's `/object/template/{type}`:

```
$ curl --request GET --header 'Accept: application/json' --header 'Content-Type: application/json' --url http://127.0.0.1:8087/object/template/item
{"success":true,"data":{"object":"template","template":{"organizationId":null,"collectionIds":null,"folderId":null,"type":1,"name":"Item name","notes":"Some notes about this item.","favorite":false,"fields":[],"login":null,"secureNote":null,"card":null,"identity":null,"reprompt":0}}}
```

**Comment by dbosompem** [comment]
Hi @ggiesen , thanks for pointing this out. We have made the required changes in our documentation. This issue will now be closed.
