### ISSUE TITLE
Desktop app does not launch links in default browser

### ISSUE THREAD

**Issue by gordol1** [bitwarden/clients#3983]
### Steps To Reproduce

1. Open Bitwarden on the desktop
2. Click the link to "launch" the site for the saved item

I have Firefox as my desktop default browser. Doing the above prompted to select Edge, Internet Explorer(!) or search the MS Store for something. No option to select another program, and no honoring my PC's default app setting.

### Expected Result

Open the site link in the system default browser.

### Actual Result

Not even giving me the option of using my system default browser.

### Additional Context

Current version of Bitwarden, just downloaded and installed today from the official site, in Windows 10.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vrosu** [comment]
@gordol1 ,
(not part of the staff, just tested out of curiosity)

In my Windows 11 22H2 I have the Firefox set as default browser, and for a login it starts Firefox by default.
Is this happening the same with the last version of BW?

With Bitwarden Version 2022.12.0
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture x64

**Comment by gordol1** [comment]
I don't know. I had given up, removed BitWarden and Firefox. Then just set it up again last week after Edge pissed me off about something, and I'm skipping the desktop app this time, at least for now.

**Comment by djsmith85** [comment]
@gordol1 Thank you for your report. 

I have also not been able to reproduce this. The Bitwarden client calls the system shell with the url and the OS decides which browser or program to open. Depending on the settings that have been set as default.

As you have explained that you are currently not using Bitwarden, I'm not going to ask for further reproduction steps.

Closing this now.

**Comment by gordol1** [comment]
I am using Bitarden, just as the browser plugin and the web, not the full desktop client.
