### ISSUE TITLE
Random disconnect with Safari

### ISSUE THREAD

**Issue by ghost** [bitwarden/clients#3998]
### Steps To Reproduce

1. Have vault timeout on browser restart
2. Vault timeout action on lock
3. Unlock with biometrics
4. Browse the web for a while
5. Put your laptop to sleep (close the lid)
6. Reopen it

### Expected Result

I must be able to unlock the Bitwarden extension by using my fingerprint.

### Actual Result

Sometimes (this time 3x in a row) I'm being logged out my Bitwarden account. I must then type my master password before been allowed to access the vault content.

### Additional Context

The issue appears to happen randomly so far. I haven't been able to discern some pattern in this annoying behaviour.

### Operating System

macOS

### Operating System Version

v12, v13.0

### Web Browser

Safari

### Browser Version

v15, v16.1

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mthld** [comment]
For the sake of completeness, here is a list of this same issue been reported multiple times on the community forum:
- [Safari extension logging itself out](https://community.bitwarden.com/t/safari-extension-logging-itself-out/13099)
- [Constantly being logged out - Safari](https://community.bitwarden.com/t/constantly-being-logged-out-safari/44123)
- [Safari plugin frequently logs out](https://community.bitwarden.com/t/safari-plugin-frequently-logs-out/32951)
- [Suddenly logged out of some Bitwarden apps at once (but not all…)](https://community.bitwarden.com/t/suddenly-logged-out-of-some-bitwarden-apps-at-once-but-not-all/31086)

Thanks in advance for your help.

**Comment by Krychaz** [comment]
Hello there, 

I was unable to replicate this issue. If you still experience this behaviour please contact our support team https://bitwarden.com/contact/
