### ISSUE TITLE
Firefox Extension - Vault Locks on Browser Close despite vault timeout action

### ISSUE THREAD

**Issue by marshyyyy** [bitwarden/clients#4005]
### Steps To Reproduce

1. Log into BitWarden
2. Set Vault Timeout to anything (e.g. Never, Custom, etc.)
3. Close Browser
4. Reopen Browser

### Expected Result

Bitwarden is unlocked

### Actual Result

Bitwarden is locked

### Additional Context

Have not tested other browsers

### Operating System

Linux

### Operating System Version

PopOS!, Ubuntu

### Web Browser

Firefox

### Browser Version

106.0.3

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by marshyyyy** [comment]
Found a similar bug:
https://github.com/bitwarden/clients/issues/2482

I do not experience an immediate lock.

**Comment by Hinton** [comment]
Can you verify it locks even with the `never` option?

The other scenarios are intentional and covered in the docs, https://bitwarden.com/help/vault-timeout/#web-and-browser-extension-timeouts.
