### ISSUE TITLE
Browser ext loses "Unlock with PIN" setting

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bitwarden/clients#4021]
### Steps To Reproduce

No steps. It is just happens for no apparent reasons.

### Expected Result

The extension sometimes ask me to enter master pass instead of my pin.

### Actual Result

Should ask me to enter the pin.

### Additional Context

I always check "Unlock with PIN" and uncheck "Lock with master pass on browser restart", so the extension should always prompt me for the PIN. But sometimes it's just loses my settings: "Unlock with PIN" unchecked, and i have to do it all over again. And again. Repeated once every ~2-3 weeks.
I have this bug for a few months on different OS and browsers. The last time was yesterday in Brave.

### Operating System

Windows, macOS, Linux

### Operating System Version

Mac 11, 12; Windows 10; Ubuntu 20.04

### Web Browser

Firefox, Brave

### Browser Version

Different versions

### Build Version

2022.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it could be that this issue has been already fixed or that it was only a temporary issue. If you notice this behaviour again, please contact our support - https://bitwarden.com/contact/

Thanks!

**Comment by Greenderella** [comment]
More information about this can be found here: https://bitwarden.com/help/security-faqs/#q-how-long-does-bitwarden-cache-session-information
