### ISSUE TITLE
MAC OS High CPU

### ISSUE THREAD

**Issue by alexandrekeller** [bitwarden/clients#4030]
### Steps To Reproduce

Activate any browser bitwarden extension.

### Expected Result

Not to use 100% CPU.

### Actual Result

Since I started using BitWarden my MacBook Pro began to, aleatory, use nearly 100% CPU.

I realized it only happens when any bitwarden browser extension is active, I did tested on Safari, Brave and Firefox.

Any ideas?

### Screenshots or Videos

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/1012367/201071581-929403a6-8be0-4797-8c95-d02d0200a6ee.png">

### Operating System

macOS

### Operating System Version

macOS Monterey 12.6.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

© Bitwarden Inc. 2015-2022  Version: 2022.10.0  Server Version: 2022.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@alexandrekeller Thank you for reporting back, I'm going to close this now.
