### ISSUE TITLE
BW client does not return Masked Email "name" to Fastmail

### ISSUE THREAD

**Issue by alienpup** [bitwarden/clients#4033]
### Steps To Reproduce

1. obtain Fastmail API for BW client
2. add or edit BW "item"
3. create or replace "Username": 
Options: "Forwarded Email Address
Service: Fastmail
4. click "Regenerate Username" icon
5. Confirm receipt of Fastmail Masked Email address
6. Log into Fastmail account .
7. Go to "Settings" | "Masked Email"
8. Locate the maske email address generated above
9. Observe that "Description" field is empty 

### Expected Result

Fastmail should receive the item "name" from BW client. Name should appear with the generated Masked Email address.

### Actual Result

BW does not send, and Fastmail does not receive the BW item "name". The "Description" field for the generated Masked Email address remains empty.

### Screenshots or Videos

![bw-fastmail-masked-email](https://user-images.githubusercontent.com/116597927/201179337-e5e58604-476f-4127-80a8-68c4d390135e.png)

### Additional Context

Problem confirmed on current BW Linux, iOS, iPadOS and MacOS clients.

### Operating System

macOS, Linux

### Operating System Version

Linux thinkpad 5.13.13-1-MANJARO #1 SMP PREEMPT Thu Aug 26 20:34:21 UTC 2021 x86_64 GNU/Linux, MacOS Big Sur 11.7.1

### Installation method

Other

### Build Version

Version 2022.10.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by alienpup** [comment]
BW client for MacOS and iPadOS obtained from Apple App Store. BW Linux client obtained from Manjaro repository.

**Comment by cubemike99** [comment]
Still present in the BW Firefox 2023.10.1 extension.

Here's the exact problem, found by viewing and editing the POST request sent to the Masked Email API:
The BW extension is setting the `url:` metadata field of the Masked Email API request to the Name of the BW Login Item being created; this in incorrect per the API description at https://www.fastmail.com/for-developers/masked-email/

> If your product supports deep links, the url property should be a deep link to the credential or other record related to this masked email address in your product. If deep links are not supported, leave this null. Do not set this to the domain of the site the user is using the masked email for, see above and use forDomain for this.

I believe literally the only change necessary is to set the `forDomain:` metadata field to the Name of the Login Item, instead of the `url:` metadata field.
