### ISSUE TITLE
bw delete folder 'id' results in not found when using session env variable

### ISSUE THREAD

**Issue by BuggeXX** [bitwarden/clients#4040]
### Steps To Reproduce

$env:BW_CLIENTID = 'client.id'
$env:BW_CLIENTSECRET = 'secret'
$env:BW_PASSWORD = 'password'

Log in to Bitwarden CLI
& $BW_Exe login --apikey --raw

Unlock vault and set session token
$env:BW_SESSION = (& $BW_Exe unlock --passwordenv BW_PASSWORD --raw)

Attemt to delete a folder
& $BW_Exe delete folder 'folder.id'

### Expected Result

Folder got deletet

### Actual Result

CLI fails with
Not found.

### Additional Context

This error only occures when attempting to use bw delete folder with a valid session token in $env:BW_SESSION.
If the vault is locked or the token invalid, bw delete folder will prompt for the master password and the folder get
deleted without issues.

This issues only occurs with delete folder but not with delete item which works fine also with $env:BW_SESSION set.

### Operating System

Windows, Linux

### Operating System Version

Windows11, Debian12

### Shell

Bash, PowerShell

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by worryboy** [comment]
same here

**Comment by djsmith85** [comment]
Hi @chipzzz, 
The CLI version [2023.1](https://github.com/bitwarden/clients/releases/tag/cli-v2023.1.0) got released beginning of January. If you are still experiencing this with 2023.1, please create a new issue, detailing the symptoms and link to this issue.
