### ISSUE TITLE
No items displaying

### ISSUE THREAD

**Issue by pedrito1414** [bitwarden/clients#4048]
### Steps To Reproduce

I don't know I am afraid. I have two accounts, both of which I access through the same desktop client (Bitwarden Version 2022.10.1) run on linux mint and installed through the software manager. I have had this issue twice but only with one of the accounts!

### Expected Result

When I log in, I expect to see all of my items displayed as normal.

### Actual Result

Instead I see this... 

![image](https://user-images.githubusercontent.com/8447248/201473459-0e6276dd-6369-4bcc-a52b-38e30e362311.png)

If I click on one of the blank items, I just see this, for example:

![image](https://user-images.githubusercontent.com/8447248/201473487-be23ab6b-95a1-4721-98d6-5023bf6f1bf4.png)

### Operating System

Linux

### Operating System Version

Linux Mint 20.2 Cinnamon / 5.0.7

### Installation method

Other

### Build Version

Bitwarden Version 2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NAICOLAS** [comment]
I experience the same bug on Windows 11:
Version	10.0.22000 Build 22000
Hardware Abstraction Layer	Version = "10.0.22000.1219"

Bitwarden:
Version 2022.10.1
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture x64

**Comment by RafLaf** [comment]
I have the same issue on the snap linux client. I usualy use bitwarden's website on chrome or firefox to avoid the problem! Sometimes restarting the computer fixes it. 
Version 2022.10.1
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture x64

**Comment by Hanbokman** [comment]
In case people are having this problem still, I managed to fix it by syncing my vault manually. 

Went into the app -> Options -> Sync -> Sync vault now.

Even though it said it had been syncing recently, this manual sync fixed it for me. 

Good luck

**Comment by RafLaf** [comment]
Thanks !

**Comment by TroyBW** [comment]
Hi there!

We attempted to reproduce your issue and were unable to do so. It seems that you had downloaded the Bitwarden desktop app through the Mint Software Manager, which is not an official release channel. We recommend that users download the Bitwarden desktop app using one of the methods listed on the Bitwarden downloads page: https://bitwarden.com/download/

The issue here will be closed.

Thanks!
