### ISSUE TITLE
Stacktrace when trying to export Vault without the correct access rights

### ISSUE THREAD

**Issue by birdie1** [bitwarden/clients#4054]
### Steps To Reproduce

1. Give a user access without export right (For example user or manager type) for a vault
2. Use cli to login into this account
3. Use cli to export the vault

### Expected Result

An error message, that the user does not have the access rights for exporting this vault.

### Actual Result

```
/snapshot/clients/apps/cli/build/bw.js:32334
                error.message != null
                      ^

TypeError: Cannot read properties of null (reading 'message')
    at Function.error (/snapshot/clients/apps/cli/build/bw.js:32334:23)
    at ExportCommand.<anonymous> (/snapshot/clients/apps/cli/build/bw.js:38107:33)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/clients/apps/cli/build/bw.js:38073:65)
```

### Operating System

Linux

### Operating System Version

Archlinux / Debian 11

### Shell

Zsh

### Build Version

2022.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

This issue has now been fixed. A user without export rights now exports blank vault.
