### ISSUE TITLE
UWP App error: cannot decrypt when using multiple Accounts with biometric unlock

### ISSUE THREAD

**Issue by base2itc** [bitwarden/clients#4077]
### Steps To Reproduce

1. Add multiple accounts (i have 1 enterprise and 1 personal)
2. Activate WindowsHello unlock (i use fingerprint) for both
3. Lock the App
4. unlock 1st Account (always ok)
5. unlock 2nd Account (random error cannot decrypt)

### Expected Result

All entries should be visible/readable

### Actual Result

1. All folders are listed correctly with names
2. All entries in folders are listet as "[error: connot decryt][error: cannot decrypt]"
3. when you select any entry, the entry infos are shown correctly in the details (name, username, password, and averything else)
4. only in the overview every entry is listed with the error.

### Screenshots or Videos

![bw err 1](https://user-images.githubusercontent.com/111295537/202389311-616dbc63-6c85-44b8-9681-99891393ea9a.png)
![bw err 2](https://user-images.githubusercontent.com/111295537/202389318-e61b664a-0064-4265-a3f5-cec5699b9e60.png)
![bw err 3](https://user-images.githubusercontent.com/111295537/202389319-c9ea7050-bf61-44b8-9ceb-c285b7d18746.png)

### Additional Context

to resolve this error, close and restart the app.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.819

### Installation method

Microsoft Store

### Build Version

version 2022.10.1, shell 19.0.8, renderer 102.0.5005.148, node 16.14.2, arch x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@base2itc Thank you for report.

This seems to be very similar, if not the same cause as in https://github.com/bitwarden/clients/issues/3057. This has to do with the account switching and not necessarily with the usage of biometrics to unlock/switch

Closing this as duplicate. Feel free to comment if you think otherwise and we can re-open.
