### ISSUE TITLE
How to show bitwarden in login popup?

### ISSUE THREAD

**Issue by alexisfrjp** [bitwarden/clients#4090]
### Steps To Reproduce

1. https://tgvinoui.sncf/prehome?utm_source=site_SNCF&utm_medium=Env_SNCF&utm_campagne=Accedez_a_votre_Espace
2. Click on "Valider"
3. A login popup appears without the bitwarden extension icon showing up

### Expected Result

To see the bitwarden extension icon so that we can auto-fill the email and password.

### Actual Result

![image](https://user-images.githubusercontent.com/6713988/202897376-0d67da9d-b7e2-47c9-8878-6e3796220da8.png)

### Operating System

Linux

### Operating System Version

RHEL 8.7

### Web Browser

Firefox

### Browser Version

102.4.0esr (64-bit)

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tangowithfoxtrot** [comment]
Hi, @alexisfrjp.

I don't believe there is a way to display the extension icon in pop-up dialogs, as it appears to be something controlled by Firefox.

For pop-up windows like that, I'd recommend using our [autofill keyboard shortcut](https://bitwarden.com/help/auto-fill-browser/#using-keyboard-shortcuts) to autofill pages like that. You should be able to use any of the other autofill methods mentioned on that page, if you prefer.

Closing this issue.
