### ISSUE TITLE
Google browser plug-in consumes a lot of memory

### ISSUE THREAD

**Issue by coverthesea** [bitwarden/clients#4109]
### Steps To Reproduce

Normal use

### Expected Result

Normal memory usage

### Actual Result

memory used 1.5gb 

### Screenshots or Videos

<img width="997" alt="image" src="https://user-images.githubusercontent.com/48321555/203458005-3c37c6d0-f26b-4cf4-bb51-43d596fc9d7b.png">

### Operating System

macOS

### Operating System Version

12.5 (21G72)

### Web Browser

Chrome

### Browser Version

107.0.5304.110

### Build Version

2022.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @coverthesea and thank you for your report.

This issue has previously been reported and is being tracked with https://github.com/bitwarden/clients/issues/2249.

Closing this, as duplicate.
