### ISSUE TITLE
Popup window sometimes very small

### ISSUE THREAD

**Issue by dhilgarth** [bitwarden/clients#4114]
### Steps To Reproduce

1. Hit Ctrl+Shift+Y to show the browser popup or click the Bitwarden icon with the mouse
2. Sometimes - unclear when or why - the popup window is smaller than usual, about half the normal size
In fact, clicking multiple times it will sometimes be good and sometimes bad from the height

I'm not sure if there is causality, but I think I'm seeing this since I activated "Unlock with biometrics". However, when I deactivate that setting, I can still reproduce the issue.

### Expected Result

Popup is always the same height

### Actual Result

Popup sometimes has incorrect height

### Screenshots or Videos

Buggy height:
![image](https://user-images.githubusercontent.com/1180105/203797849-727b7a2f-9045-47cd-97eb-433809523fde.png)

Correct height:
![image](https://user-images.githubusercontent.com/1180105/203798063-c8f6b645-2709-465f-bf0d-a1c9f9bc70ef.png)

https://user-images.githubusercontent.com/1180105/203798947-40ef599a-384f-4720-9640-df6541c01d1b.mp4

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @dhilgarth and thank you for the detailed report.

This issue was tracked with https://github.com/bitwarden/clients/issues/3970 and is actually an upstream issue with Brave and their  protection against browser fingerprinting. The fix is available in Brave `1.45.131`

Closing this now, as duplicate.
