### ISSUE TITLE
"Pop out to a new window" - Additional popout window created instead of switching focus to existing popout

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#4121]
### Steps To Reproduce

1. Left click plugin
2. Click on 'Pop out to a new window' top left of dialog
3. Focus to main window and repeat steps 1-2

### Expected Result

Unless I'm missing something...

"Pop out to a new window" should focus existing popout.

### Actual Result

Additional popout created for each invocation of "Pop out to a new window"

### Operating System

Linux

### Operating System Version

Linux redacted 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Web Browser

Chrome

### Browser Version

Version 106.0.5249.119 (Official Build) for Linux Mint (64-bit)

### Build Version

Version: 2022.10.1 / Server version: 2022.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @DavidPesticcio and thank you for your report.

Clicking on "Pop out to a **new** window" has the intended behaviour and opens a **new** window, This was implemented so that users could have several popups open to compare/copy/edit vault data.
