### ISSUE TITLE
Data / Session loss in browser extensions

### ISSUE THREAD

**Issue by mindrunner** [bitwarden/clients#4125]
I would like to follow up on the usability issue where we lose the current state of the session as well as already made inputs when the popup window closes. It has already been discussed in several tickets:

https://github.com/bitwarden/clients/issues/2139
https://github.com/bitwarden/clients/issues/2291
https://github.com/bitwarden/clients/issues/2465
https://github.com/bitwarden/clients/issues/3013

For me personally, this is a huge dealbreaker and it is more than annoying in everyday use cases. I always thought this is a limitation by browser plugins, which is also the close reason in above mentioned tickets. However, I had a look at alternative password managers recently and figured out, that this indeed seems to be a bitwarden specific problem. 

For example, dashlane does not have this issue. It preserves my session even if I lose focus and need to re-open the popup.

I checked both Chrome and Firexox with the same result.

Can we please get this behaviour  into bitwarden as well?

### Operating System

Linux

### Web Browser

Chrome, Firefox

**Comment by djsmith85** [comment]
Hi @mindrunner and thank you for your report.

The issues mentioned above are all duplicates of https://github.com/bitwarden/clients/issues/1798, please see https://github.com/bitwarden/browser/issues/1798#issuecomment-831574003 closing that issue.

Currently there is still no way to keep the browser popup open. This might improve with the work being done to support for Manifest V3 which includes Chrome introducing new APIs at a browser level.

Closing this now.

**Comment by mindrunner** [comment]
It's a duplicate, yes. However it is

1) an ongoing issue
2) other extensions did actually solve it

So why do those tickets get closed if it seems solvable and would really improve user experience? 

To clarify:

I am NOT asking to keep the popup open. I am asking to preserve the state (e.g. see the same content after re-opening it).

Most of the other password managers I tried recently show this behavior, but bitwarden does not. Why?

Please re-open. Let's talk about it and get this into bitwarden. It is super super annoying with the current behavior :(

**Comment by djsmith85** [comment]
Hi @mindrunner,

I hear you, with this still being an UX issue for you and other users. Your ticket got closed for the same reason #1798 got closed. 

Keeping the popup open is _currently_ not possible. This and your other point about preserving data are being discussed with the linked [feature request](https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470) that was provided with the linked comment on #1798. 

I'd ask you to please engage there, adding your views and findings to the discussion with our product team and other community members. 

Kind regards,
Daniel

**Comment by mindrunner** [comment]
Hello Daniel,

it seems we have a big misunderstanding here! I am NOT asking to keep the popup open!!

Please read my previous messages: 

> I am NOT asking to keep the popup open. I am asking to preserve the state (e.g. see the same content after re-opening it).

> However, I had a look at alternative password managers recently and figured out, that this indeed seems to be a bitwarden specific problem.


---> This is a problem in Bitwarden. Most other Password managers / estensions DO NOT have this issue!!

**Comment by djsmith85** [comment]
Hey @mindrunner,

Preserving the state between opening and closing of popup is part of the discussion at https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470

As always, there are several ways to approach or solve a problem, some of them are being discussed on the feature request.

Please take some time and read through the comments and see what our awesome community members have to say about this. Then please vote and add to the discussion. 

If you think the linked feature request does not describe your problem accurately, please feel free to open a new thread in the feature request category of our Community Forums.

Kind regards,
Daniel

**Comment by mindrunner** [comment]
I know that thread and I am following it since 2(!!) years now. I probably won't for another 2. Luckily I have the choice which password manager I put my money into! :)

Thank you

**Comment by djsmith85** [comment]
@mindrunner Thank you for your feedback
