### ISSUE TITLE
Search field swallows key strokes

### ISSUE THREAD

**Issue by Aloso** [bitwarden/clients#4128]
### Steps To Reproduce

1. Open the browser extension popup
2. Type quickly in the search field

Note that I could only reliably reproduce the bug _directly after opening the popup_.

### Expected Result

The search field contains all typed letters

### Actual Result

While typing, the popup refreshes several times to show the search results. But after each refresh, the most recent key press may be lost.

For example, if you type "The quick brown" and the popup refreshes while typing the "e", and again when typing the "w", then the search field contains the text "Th quick bron"

This is reproducible ~50% of the time when typing very quickly, directly after opening the popup.

### Operating System

Windows, Linux

### Operating System Version

Windows 10, Manjaro Linux 21.3.7

### Web Browser

Firefox

### Browser Version

104, 107

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Aloso and thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/2371. With https://github.com/bitwarden/clients/pull/3680 it has also received a fix, but this fix has not been released yet. It will be part of the upcoming browser release.

Closing this as duplicate.

**Comment by Aloso** [comment]
Thanks for the explanation, I appreciate it!
