### ISSUE TITLE
accented characters stripped of accents when typed passwords are hidden, when creating an item

### ISSUE THREAD

**Issue by chadm-sq** [bitwarden/clients#4143]
### Steps To Reproduce

1. Open the browser plugin window, click "+" to add a new item.
2. Click in the password field
3. Type an accented character. On OSX, this could be `Option-e e` to make `é`. Notice the password input show a mid-dot. On linux (not tested yet), `Compose e '`. Windows, no idea.
4. Click the eyeball to reveal the password.

### Expected Result

`é`

### Actual Result

`e`

### Additional Context

If the password is revealed, it does indeed accept its input characters.

option-u e *reveal* option-e a would make `eá`, not correct `ëá` or the other expected purely ASCII `ea`

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @chadm-sq and thank you for your report.

This has previously been reported and is being tracked with https://github.com/bitwarden/clients/issues/2472.

Please add any additonal information you have on that issue.

Closing this now, as duplicate
