### ISSUE TITLE
Bitwarden does not properly unwind in Chrome under Wayland

### ISSUE THREAD

**Issue by matlacki** [bitwarden/clients#4175]
### Steps To Reproduce

Ubuntu 22.10 with Wayland
multi-monitor setup
open Bitwarden extension while google chrome is on the third screen

Please let me know what debug info should I post in this case

### Expected Result

Normal window of bitwarden should open

### Actual Result

On Ubuntu 22.10 in Google Chrome under Wayland , pressing blue icon of BitWarden should open a popup with main GUI of the application. It does so when Google Chrome  is on the primary or second screen. If Google Chrome window is on third screen, the popup has around 20 pixels width making it useless. If Google chrome is moved to a primary screen the Chrome Bitwarden Extension opens a proper window. This workaround does not require restarting the browser. Moving window back to the third screen immediarely re-triggers the issue.

### Screenshots or Videos

![Screenshot from 2022-12-02 10-27-46](https://user-images.githubusercontent.com/92470884/205261192-e6d8aa54-6583-4aa1-a560-1d3ded0e2aa6.png)

### Operating System

Linux

### Operating System Version

Ubuntu 22.10

### Web Browser

Chrome

### Browser Version

Version 107.0.5304.121 (Official Build) (64-bit)

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by calebccff** [comment]
Confirming this it happens to me but with all chrome extensions, i don't think it's exclusive to bitwarden. I've been able to reproduce it on an ARM64 laptop and a ThinkPad T430 with chrome and chromium. Running through xwayland is a potential "workaround".

**Comment by vlnk** [comment]
I opened an issue on the Chromium tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=1409441. I hope, it will help!

**Comment by gammons** [comment]
I can confirm this is an issue as well.  I use Swaywm.  Interestingly, the issue only occurs on my external monitor.  The Bitwarden extension works normally on my laptop screen.

**Comment by lukejcollins** [comment]
I'm also experiencing this issue. Very frustrating!

**Comment by gammons** [comment]
wondering if this issue should be renamed.  I had to do a lot of digging / searching to find it, and I bet it's a common issue.

**Comment by gammons** [comment]
Alright, I found something - I noticed the position of my laptop screen is set to 3840 to offset when it's being used when the laptop screen and the external monitor are on together.

When I set the position of my external monitor to 0, chrome extension windows behave normally.
