### ISSUE TITLE
Exception Breakpoint in Version 2022.11.0

### ISSUE THREAD

**Issue by owittek** [bitwarden/clients#4188]
### Steps To Reproduce

1. Have Bitwarden open
2. Shutdown

### Expected Result

The PC shuts down successfully

### Actual Result

An exception Breakpoint error pops up.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/57495944/205749317-201a9e19-9da3-4dac-9d8d-268a2c76ae51.png)

### Operating System

Windows

### Operating System Version

11 Version 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.11.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vrosu** [comment]
@owittek 
I'm not part of the Bitwarden staff, but this seemed to be an easy thing to test.
In my Windows 11 Pro 22H2 build 22621.963  and Bitwarden Version 2022.12.0, Shell 19.0.8, Renderer 102.0.5005.148, Node 6.14.2, Architecture x64 I did the same steps and when shutting down BW it did not popup any exception. Note I was unlocked via Hello in Bitwarden.

**Comment by owittek** [comment]
> @owittek I'm not part of the Bitwarden staff, but this seemed to be an easy thing to test. In my Windows 11 Pro 22H2 build 22621.963 and Bitwarden Version 2022.12.0, Shell 19.0.8, Renderer 102.0.5005.148, Node 6.14.2, Architecture x64 I did the same steps and when shutting down BW it did not popup any exception. Note I was unlocked via Hello in Bitwarden.

Hi vrosu, I'm currently not home so I can't test it on my Windows Machine but the error popped up when I've shutdown my computer without closing BW first (not sure if it's clear enough in the issue). Could as well have been fixed in 2022.12.0 but it's always odd to have a breakpoint exception in a release build.

**Comment by vrosu** [comment]
No rush. It was clear in the issue description.
I also have from time to time apps that behave like this (as exception, not rule, thanks God) but at least with my BW version this did not manifest. Now if you want to dig into release quality....let's just say that I am also keeping an eye on this topic. I'd be very curious to see how it compares to enterprise world (cough).

**Comment by owittek** [comment]
![Bitwarden](https://user-images.githubusercontent.com/57495944/211797180-b1e66bb9-9a7e-4c08-89ea-2ce9a87c5ce3.png)

Another day, another Breakpoint Exception :D

I'm on Version 2022.11.0 and left my PC locked for about an hour while leaving Bitwarden unlocked on my PC and I returned to the exception that I've screenshotted.

**Comment by LukaHummel** [comment]
Had this error also occur on two Windows 11 devices. I use multiple accounts (Business and private) maybe that has something to do with it. Can confirm it on Windows 11 Pro Version 22H2 OS build 22621.1105.
Version 2023.1.1
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

**Comment by owittek** [comment]
> Had this error also occur on two Windows 11 devices. I use multiple accounts (Business and private) maybe that has something to do with it. Can confirm it on Windows 11 Pro Version 22H2 OS build 22621.1105.
> 
> Version 2023.1.1
> 
> Shell 21.3.1
> 
> Renderer 106.0.5249.181
> 
> Node 16.16.0
> 
> Architecture x64
> 

I use a single account on my Windows machine so I don't think it's related to the issue.

**Comment by LukaHummel** [comment]
I meant two Bitwarden accounts. Not two Windows accounts.On Jan 30, 2023 06:55, Oli ***@***.***> wrote:

Had this error also occur on two Windows 11 devices. I use multiple accounts (Business and private) maybe that has something to do with it. Can confirm it on Windows 11 Pro Version 22H2 OS build 22621.1105.
Version 2023.1.1
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

I use a single account on my Windows machine so I don't think it's related to the issue.

**Comment by atjbramley** [comment]
Hi @owittek ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a conflict with other software on your machine.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by owittek** [comment]
Hi @atjbramley,
how about this one then?

![Untitled](https://github.com/bitwarden/clients/assets/57495944/49f363e2-004a-423b-aa18-b5fa9962a3fc)

Windows 11 Version 22H2 (OS Build) 22621.2134
Version 2023.7.1
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

**Comment by atjbramley** [comment]
Hi @owittek, 

We use GitHub issues as a place to track bugs and other development related issues.  We do not provide tech support via GitHub.

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

We look forward to receiving your email.
