### ISSUE TITLE
Character loss when typing into search box

### ISSUE THREAD

**Issue by counterpoint** [bitwarden/clients#4191]
### Steps To Reproduce

Click on the browser icon. By default the cursor is in the search field. Type a word at normal typing speed (in my case about 50 words per minute). For example, “PayPal”.

### Expected Result

Passwords for PayPal accounts are shown.

### Actual Result

The software is attempting matches as each character is typed, but in the process, characters are lost. So after typing “PayPal” the box may show “Payal”. No match is found. 

### Additional Context

I don’t want to type slowly, waiting for search to operate on each character, that is an unnatural thing to do. In around a second, I can type enough to be confident of finding what iam looking for. Except that if a character is lost, the search fails completely even though what I typed was correct.

### Operating System

Linux

### Operating System Version

Recent

### Web Browser

Firefox

### Browser Version

Current

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luckman212** [comment]
This has been an issue for many months—close to a year now. I reported the original issue #2371. Since then others have also reported similar issues. See below



It's annoying because they keep closing it as "fixed" when clearly it's not.

**Comment by djsmith85** [comment]
Hi @counterpoint and thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/2371. With https://github.com/bitwarden/clients/pull/3680 it has also received a fix, the changes made there just got released with `2022.12`

@luckman212: Issues get closed when a PR gets merged. This does not mean, those changes are available straight away. There's also a [comment](https://github.com/bitwarden/clients/issues/2371#issuecomment-1282773485) on the actual PR.

Please test out the changes with 2022.12 and report back if the issue has been resolved/behavior has improved.

Kind regards,
Daniel
