### ISSUE TITLE
browser plugin limits scan of form elements to 50 items // there is no metrics reporter yet

### ISSUE THREAD

**Issue by chadm-sq** [bitwarden/clients#4229]
### Steps To Reproduce

Not exactly a bug. I noticed a suspicious number in the code, and I think it needs a comment or investigation.

In apps/browser/src/content/autofill.js , getFormElement receives an integer limiting the number of elements it inspects. A good safety measure.

I see it called with literal _50_ . It's a weird number. Isn't commented. It looks arbitrary, and that might mean it isn't chosen well.

I wonder if we can have metrics that report how deeply we find the form elements, out in the wild.  If a histogram of metrics looks like the tail leads up to 50, it could mean 50 is too low.

A generic metrics system would be helpful for a dozen other things that we're blind to right now.

### Expected Result

This bug template is too rigid.

### Actual Result

This bug template is too rigid.

### Operating System

macOS, Linux

### Web Browser

Chrome, Firefox

### Build Version

This bug template is too rigid.

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Hi @chadm-sq.  The reason for the introduction of this limit was to guard against any potential performance degradation from too many inputs being evaluated.  We performed some testing and found that while we could raise the limit to another arbitrary value without compromising performance, we didn't feel that there warranted any adjustment at this point (and the requisite regression testing) in light of other priorities.  We don't foresee common use cases where this limit would affect the success of the autofill process.
