### ISSUE TITLE
Revert UI change in Browser Extension v2022.12.0

### ISSUE THREAD

**Issue by profucius** [bitwarden/clients#4256]
### Steps To Reproduce

Open the browser extension.

### Expected Result

In Browser v2022.12.0 a change was made to the UI which increases the amount of space that each vault item consumes, but does not increase the size of the popup window. Design-wise this being forced on everyone is unacceptable.

The number of vault entries available in a single screen prior was 11. Now it is 7. It is approximately 1 item reduced for every 4 in the old design. That is an unnecessary loss for those of us power users who prefer to see _more_ on the screen at once, rather than less.

Is there a method to revert the UI to the previous longstanding design (v2022.10 and prior)? A toggle in the settings would be amicable.

### Actual Result

Less visibility within the already small popup window.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/18254607/208141202-3c0f9351-3db7-46a3-a744-b7d657e35af1.png) ![image](https://user-images.githubusercontent.com/18254607/208141116-f4d73608-8493-4ae4-a844-ba21d149c514.png)

![image](https://user-images.githubusercontent.com/18254607/208142078-179b6a82-2df2-42a8-a430-bbbf62f3593b.png) ![image](https://user-images.githubusercontent.com/18254607/208141923-f757464c-1134-41de-94be-8fa6b81e6706.png)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2022.12

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @profucius, thank you for your report and feedback.

To keep track of feedback about the just released browser extension, there is a [thread on our community forums](https://community.bitwarden.com/t/browser-extension-22-12-0-change-in-ui/46974/1).

Please add your feedback to the discussion on that thread. 

Kind regards,
Daniel
