### ISSUE TITLE
login is broken with Firefox extension v 2022.12.0

### ISSUE THREAD

**Issue by ghost** [bitwarden/clients#4257]
### Steps To Reproduce

1. Install on a new Firefox profile Bitwarden v 2022.12.0
2. set up your Bitwarden URL
3. Login with email and password

### Expected Result

Login succeed, eventually asking 2FA

### Actual Result

an error ha occurred. Username or password is incorrect. Try again

### Additional Context

No issue with version 2022.10.1

No issue if Bitwarden updates from 2022.10.1 to 2022.12.0, **unless the user logs out**

### Operating System

Linux

### Operating System Version

debian 11

### Web Browser

Firefox

### Build Version

102.6esr

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @luca-e075e, thank you for your report.

You mention setting the Bitwarden-Url which indicates you are self-hosting. Could you please provide more information about your Bitwarden server installation?

Depending on your installed version -> 
![image](https://user-images.githubusercontent.com/2670567/208155819-4be0ad0a-c786-4255-a190-8338bf5327ce.png)

More information on this can be found on our [help-site](https://bitwarden.com/help/)

**Comment by djsmith85** [comment]
Looking through our [server-releases page](https://github.com/bitwarden/server/releases?page=2)we never released a 2.19.0 which indicates, that you are not using an official version of Bitwarden (possibly bitwarden_rs or now known as [vaultwarden](https://github.com/dani-garcia/vaultwarden)) 

Kind regards,
Daniel
