### ISSUE TITLE
Extension icon decorations not showing in secondary browser windows

### ISSUE THREAD

**Issue by mackncheesiest** [bitwarden/clients#4258]
### Steps To Reproduce

Steps to reproduce:
1. Open Firefox
2. If your vault is not locked, lock it
3. Note that the icon decoration shows the padlock symbol to indicate your vault is locked 
4. Open a second Firefox window (i.e. Ctrl-N)
5. Note that the icon no longer shows the padlock symbol in this secondary window

Equivalently
1. Unlock Bitwarden and navigate to a saved site, noting that the icon decoration showing "number of available logins" is visible in this primary window
2. Open a second Firefox window (i.e. Ctrl-N)
3. Navigate to a saved site, and the icon decoration is not visible.

### Expected Result

The extension icon decorations (padlock for locked vault, number of logins for a given site) should be equally visible across all browser windows

### Actual Result

The icon decorations are only visible on the "primary"/"first launched" browser window

### Additional Context

This only started happening with the recent 2022.12.0 UI changes, so my initial thought was that these decorations had been removed for some reason. No one in the Reddit [feedback thread](https://www.reddit.com/r/Bitwarden/comments/znjrdk/2022120_browser_extension_ui_changes_feedback/) seemed to be discussing this, though, so I assumed it must be on my end. Noticed that, in my primary window, the decorations were working as expected. Tried various browser restarts, but the problem still seems to persist.

### Operating System

Linux

### Operating System Version

Fedora 37

### Web Browser

Firefox

### Browser Version

Developer Edition 109.0b3

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mackncheesiest** [comment]
Seeing the same issue on Windows 10

**Comment by thericle** [comment]
I'm having the same issue on Chrome 108.0.5359.125 with Bitwarden 2022.12.0.

**Comment by dylmcd13** [comment]
Encountering the same. Windows 10, Firefox 108.0.1, Bitwarden 2022.12.0

**Comment by awalkonthebeach** [comment]
No padlock or badge counter on Firefox.  Also, the icon stays always blue even when logged out (it should be gray)

**Comment by Racle** [comment]
Oh, this is why I don't see the counter on my second Firefox instance.

pop_os 22.04, Firefox 109.0b4, BW 2022.12.0

**Comment by awalkonthebeach** [comment]
I"ll reiterate something I mentioned on the other thread which I believe is referring to the same issue.  The icon works fine on the first (primary) Firefox window, but it's broken on all secondary windows.

**Comment by mackncheesiest** [comment]
Going to guess that it's maybe that this call
https://github.com/bitwarden/clients/blob/32ec5bdba1089514119113529bab0eee60925d8c/apps/browser/src/background/main.background.ts#L607-L609
isn't passing in a window id
https://github.com/bitwarden/clients/blob/32ec5bdba1089514119113529bab0eee60925d8c/apps/browser/src/listeners/update-badge.ts#L75-L103

**Comment by StereogramStudios** [comment]
Same issue on Firefox. Badge counter missing :(

**Comment by djsmith85** [comment]
Thank you all for your feedback on this one.

Closing this in favor of https://github.com/bitwarden/clients/issues/4260 as it's describing the same issue.

Rest assured we have seen your feedback and are looking into it.
