### ISSUE TITLE
Badge counter has gone

### ISSUE THREAD

**Issue by Limboso** [bitwarden/clients#4260]
### Steps To Reproduce

1. Go to any site with login credentials saved in bitwarden vault.

### Expected Result

The badge counter should appear on the extension icon indicating how many logins I have for the current web page.

### Actual Result

After the 2022.12.0 update the badge counter has vanished. It only appears the extension icon without any badge counter.

### Additional Context

I tested in several websites using the chrome standard mode (not incognito) and the badge counter didn't show up in any of them.

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

108.0.5359.125 (64-bit)

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by christianhubmann** [comment]
I also have this issue in Firefox 107.0.1 on Windows 10 and Ubuntu 22.04
Version: 2022.12.0
Server version self-hosted: 2022.10.0

**Comment by mackncheesiest** [comment]
Just curious, are y'all seeing the issue across all browser windows? Or just on "secondary" browser windows like in #4258 ?

**Comment by awalkonthebeach** [comment]
> Just curious, are y'all seeing the issue across all browser windows? Or just on "secondary" browser windows like in #4258 ?

I didn't notice this before because I've configured FIrefox to restore the previous session and I always have multiple windows open.  You're right - one of the windows shows the badge counter and padlock, and I think that was the first window that opened which you call "primary" I think.

**Comment by Limboso** [comment]
> Just curious, are y'all seeing the issue across all browser windows? Or just on "secondary" browser windows like in #4258 ?

Like @awalkonthebeach I also didn't notice before because of my use of multiple windows. But you're right. I just tested carefully now and the badge counter does show **only** on the 1st opened window. You open any new windows and there's no more badge counter.

**Comment by livinlicious** [comment]
> > Just curious, are y'all seeing the issue across all browser windows? Or just on "secondary" browser windows like in #4258 ?
> 
> Like @awalkonthebeach I also didn't notice before because of my use of multiple windows. But you're right. I just tested carefully now and the badge counter does show **only** on the 1st opened window. You open any new windows and there's no more badge counter.

can confirm, only first window.

**Comment by sentix001** [comment]
can confirm same as above

**Comment by hymccord** [comment]
Confirming as well. Only "primary" browser window shows correct badge text.

**Comment by SamJade** [comment]
Confirming that the first or primary browser window shows badge counters for me, but no other FF windows will. FF v108 on Windows 10 21H2.

**Comment by deaduncledave** [comment]
> Confirming that the first or primary browser window shows badge counters for me, but no other FF windows will. FF v108 on Windows 10 21H2.

Confirming this for Firefox 102.6.0esr (64-bit) in Windows 10 Enterprise, Build 19044. Badge counter appears on primary FF window for all tabs, does not appear on secondary windows.

**Comment by kinghat** [comment]
just adding my info:
- fedora 37 kde spin
- ![image](https://user-images.githubusercontent.com/16073360/208756359-e87b3924-30ec-4025-b727-1de006965c10.png)

i dont get badge count or badge for locked/unlocked state. 0 badges to be had.

**Comment by worldsdream** [comment]
Confirmed.

**Comment by bakx** [comment]
Confirming this in Edge too. Looks like it's for all browsers.

**Comment by DimitriDR** [comment]
> Confirming this in Edge too. Looks like it's for all browsers.

Oddly, It doesn't happen on Chrome (version 108.0.5359.125) and only in Firefox on my Windows PC.

**Comment by Limboso** [comment]
> > Confirming this in Edge too. Looks like it's for all browsers.
> 
> Oddly, It doesn't happen on Chrome (version 108.0.5359.125) and only in Firefox on my Windows PC.

It does happen on chrome too. I'm using that same version and the bug is here. You **must** open more than a single window and you'll see that all the windows **but the first** have no badge counter.

**Comment by DimitriDR** [comment]
@Limboso Indeed, you're right! 😨

**Comment by cdman** [comment]
I can also confirm that this is an issue for both Firefox on MacOS and Firefox on Windows. On both platforms the browser as well as the browser extension is up to date (specifically on MacOS the bitwarden extension version is 2022.12.1, with "Last updated" at 21 December 2022)

**Comment by mareklab** [comment]
It does not work again, at least on Mac. Firefox, Safari, Edge - broken everywhere.
