### ISSUE TITLE
Cannot connect to my self-hosted bitwarden environment with the firefox extension

### ISSUE THREAD

**Issue by jeudine** [bitwarden/clients#4262]
### Steps To Reproduce

1. Set the server URL
2. enter your email address
3. enter your password
4. try to connect

### Expected Result

Connection

### Actual Result

Following error message:

**An error has occurred**

**Username or password incorrect. Try again**

### Operating System

Linux

### Operating System Version

Debian 12

### Web Browser

Firefox

### Browser Version

firefox 102.5esr

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Please ensure the self-hosted server is running 1.46.0 or newer, https://bitwarden.com/help/november-deprecation-notice/

**Comment by jeudine** [comment]
Thanks @Hinton, it's working now
