### ISSUE TITLE
Can't log in on Firefox

### ISSUE THREAD

**Issue by benshep** [bitwarden/clients#4265]
### Steps To Reproduce

1. Click browser extension button
2. Username is auto-populated (I've been using it for a while)
3. Click 'next'
4. Enter password

### Expected Result

Logged in

### Actual Result

Not logged in. Message that says "Error: 'i' is undefined"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/5038790/208502763-b49aae2c-47e0-4bd7-bed8-2025b5dca6f4.png)

### Additional Context

This works on my other devices which all run Firefox, and also worked on this one until recently.

### Operating System

Windows

### Operating System Version

Windows 11 21H2 build 22000.1219

### Web Browser

Firefox

### Browser Version

108.0.1 64-bit

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @benshep and thank you for your report. 

This seems to be already reported and tracked with https://github.com/bitwarden/clients/issues/4076. 

I'll close this now.
