### ISSUE TITLE
heavy cpu usage when not performing any specific action

### ISSUE THREAD

**Issue by step7** [bitwarden/clients#4266]
### Steps To Reproduce

1: open bitwarden
2: login
3: use app a bit, then minimize it
4: restore app to foreground and do a search
5: app freezes and OS asks to kill it or wait

### Expected Result

app become responsive again

### Actual Result

app waits and freezes

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.1 LTS

### Installation method

Snap

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

We were not able to reproduce this issue. Could you please show the output of the Bitwarden process if the issue is still there for you.

`ps -p <pid> -o %cpu,%mem,cmd`
