### ISSUE TITLE
Warning about non-https-site when url points to localhost

### ISSUE THREAD

**Issue by contextfw** [bitwarden/clients#4271]
### Steps To Reproduce

1. Go to web-site that is served by localhost with http-connection
2. Open Bitwarden-extension in order to automatically fill credentials.

### Expected Result

Extension should fill credentials automatically without warnings

### Actual Result

Extension displays a warning that site is not secured by https. However this warning is pointless on sites served by localhost. It is rare that users who have local services running (i.e. software developers) to use self-signed certificates when hosting content
in localhost.

### Additional Context

In my case the work environment is such that there is a "single sign-on"-methodology where same credentials are used for multiple services whether they are remote or local. So single bitwarden-entry have multiple urls where some of them are https and for localhost http.

### Operating System

Linux

### Web Browser

Chrome

### Browser Version

108.0.5359.124

### Build Version

 2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

While we understand this workflow is not ideal. The warning is not considered a bug as it is there to protect the end users. Adding the ability to enable or disable this warning would need to go as a feature request - https://community.bitwarden.com/c/feature-requests/
