### ISSUE TITLE
Form “Add item” is broken for collections

### ISSUE THREAD

**Issue by itkfm** [bitwarden/clients#4276]
### Steps To Reproduce

1. Navigate to a collection in your vault
2. Click the top right “+” to add a new item → dialog is broken
3. Try going back with “cancel” → end up stuck on a loading screen
4. Vault view is broken until you hit the “Vault” button in the bottom bar

### Expected Result

- I get the normal “add item” form with inputs as expected
- There’s no infinite loading screen

### Actual Result

- “Add item” form: empty thing, only “Cancel” + “Save” buttons show up, nothing else
- Clicking “cancel” brings me back to the (working) vault view

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53079668/208655667-3e57e8c0-ad69-46b3-a3c0-03b24570922a.png)
![image](https://user-images.githubusercontent.com/53079668/208656115-aa27c002-5e5f-47ef-b5f8-395fd3f95ecf.png)

### Additional Context

Happens for both: the in-browser pop-up as well as a detached window.
Issue does not occur when clicking the “add item” + button from the vault’s root view.

### Operating System

Linux

### Operating System Version

Debian 11 “Bullseye”

### Web Browser

Firefox

### Browser Version

108.0.1

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by itkfm** [comment]
After adding an item to a collection (by opening the “add item” form via the vault root view) viewing collections is broken as well for the current Bitwarden “window”, i.e. there’s only the endless loading circle

**Comment by rokenbuzz** [comment]
Chrome extension, Windows
Version: 2023.1.0

When opening a collection and clicking the +, the add window is empty for me (and a coworker), aside from Cancel and Save.
Cancel brings me back.

As a workaround I can successfully create the login/note at the high level outside of the collection and then move it into my organization and collection.
