### ISSUE TITLE
Dashlane CSV card import ignores month

### ISSUE THREAD

**Issue by eleaner** [bitwarden/clients#4282]
### Steps To Reproduce

1. Go to "Tools/Import"
2. Select "Dashlane (csv)"
4. Select the file attached 
[test.csv](https://github.com/bitwarden/clients/files/10271788/test.csv)
5. Click on "Import data"

### Expected Result

The expiry month is loaded from file (March)
<img width="137" alt="image" src="https://user-images.githubusercontent.com/5169203/208749047-cffa211f-408d-48c9-a69b-dcca88e4a211.png">

### Actual Result

The expiry month is ignored.
<img width="773" alt="image" src="https://user-images.githubusercontent.com/5169203/208749593-082ef7be-e31c-4ef7-8fd2-4d5939e62a6c.png">

### Operating System

macOS

### Web Browser

Brave

### Build Version

Version 2022.12.0 (vault.bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @eleaner and thank you for your report with a test-file. I was able to reproduce the behaviour and have created the linked pull-request which addresses the issue.
