### ISSUE TITLE
TypeError: encValue.split is not a function

### ISSUE THREAD

**Issue by markusressel** [bitwarden/clients#4285]
### Steps To Reproduce

1. bw get password "something"
2. see error

### Expected Result

A printout of the requested password

### Actual Result

```
/usr/lib/node_modules/@bitwarden/cli/build/bw.js:14303
            const headerPieces = encValue.split(".");
                                          ^

TypeError: encValue.split is not a function
    at CryptoService.<anonymous> (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:14303:43)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@bitwarden/cli/build/bw.js:13816:71
    at new Promise (<anonymous>)
    at crypto_service_awaiter (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:13812:12)
    at CryptoService.rsaDecrypt (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:14302:16)
    at EncryptedOrganizationKey.<anonymous> (/usr/lib/node_modules/@bitwarden/cli/build/bw.js:13768:50)
    at Generator.next (<anonymous>)
    at /usr/lib/node_modules/@bitwarden/cli/build/bw.js:13745:71
    at new Promise (<anonymous>)
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/14024504/208776992-df995424-0baa-4486-8cc4-c2c23f89139f.png)

### Operating System

Linux

### Operating System Version

6.0.11-arch1-1

### Shell

Bash

### Build Version

2022.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @markusressel, 
​
You seem to have run into a bug that we have when using the CLI + SSL 3.0.2: https://github.com/nodejs/node/discussions/43184
​
There is a temporary fix suggested that consist of changing the openssl_init configuration in your /etc/ssl/openssl.cnf file to read as below:
​
```
[openssl_init]
​#providers = provider_sect
```

Or adding 

[`alias bw='OPENSSL_CONF=/dev/null bw' `](https://github.com/bitwarden/clients/issues/2726#issuecomment-1292698746)

to your .bash_aliases file

However, please be aware that these changes could impact other system services.

If you prefer to wait for an official release on our end, a fix has been submitted, which is currently undergoing testing: https://github.com/bitwarden/clients/pull/4165

I hope you find this helpful. Please do not hesitate to let me know if you have any questions.
