### ISSUE TITLE
Browser integration and biometric authentication on Linux

### ISSUE THREAD

**Issue by mochaaP** [bitwarden/clients#4289]
### Steps To Reproduce

1. Go to 'Settings'
2. Try enabling 'Allow browser integration'

### Expected Result

- Should install native messaging host
- Optionally ask for biometric authentication

### Actual Result

- Prompts "Unfortunately browser integration is currently not supported in the linux version."

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/21154023/208901693-acf4f46c-f4ce-4d60-a739-0a7fd384acda.png)

### Additional Context

I see that biometric authentication is not implemented on the [native side](https://github.com/bitwarden/clients/tree/master/apps/desktop/desktop_native/src/biometric) nor the [electron side](https://github.com/bitwarden/clients/tree/master/apps/desktop/src/main/biometric).

The standard biometric authentication interface on Linux is fprintd: <https://fprint.freedesktop.org>, it provides a D-Bus interface so it could be easily called from Electron without involving too much on the native side.

### Operating System

Linux

### Operating System Version

Fedora Linux 37 (Workstation Edition)

### Installation method

Other

### Build Version

Flatpak

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @mochaaP and thank you for your report. 

Here is a link to the [existing feature request](https://community.bitwarden.com/t/linux-fingerprint-and-or-biometric-support/16715/36) to add biometrics on Linux and [this](https://community.bitwarden.com/t/support-for-libsecrets-dbus-api/4006) for supporting D-Bus.  

We'd appreciate if you shared your feedback and insights on the forum threads.

Kind regards,
Daniel

**Comment by mochaaP** [comment]
Is it okay to reference this issue if I implement this and create a PR?

**Comment by djsmith85** [comment]
@mochaaP If you'd be willing to take a stab at this, that would be awesome and really appreciated. ❤️ Please reference this issue, if you open a PR.

Would you mind detailing your plans in a topic in our [Github contributions](https://community.bitwarden.com/c/github-contributions/7) category? I know we devs love to tinker first and then document, but this ensures a discussion about your approach with product/engineering before you put in all the work. 

Kinds regards,
Daniel

**Comment by Zujaj** [comment]
I’m using Bitwarden on Ubuntu 24.04.3 LTS (Kernel 6.14.0-33-generic, x86-64) with Microsoft Edge 141.0.3537.85.

After installing the Bitwarden desktop app from Snap, I received the message:

“Browser integration not supported — unfortunately browser integration is currently not supported in the Linux version.”

This means I can’t use biometric unlock in the browser, which makes everyday use much harder. It works fine on Windows and macOS, so it’s disappointing that Linux users are missing out on this core feature.

Please consider adding browser ↔ desktop integration support for Linux — many of us rely on Edge or Chromium-based browsers for work, and this would make Bitwarden far more seamless to use.

Thank you for your great work maintaining Bitwarden, and I hope this feature can be prioritized soon.
