### ISSUE TITLE
Browser no longer matches top level domains (2022.12.1)

### ISSUE THREAD

**Issue by prestonvanloon** [bitwarden/clients#4315]
### Steps To Reproduce

1. Install 2022.12.1
2. Access a host using a top level domain only. Like `my-lan-server:8005`
3. See that saved logins with `my-lan-server` do not show up.

### Expected Result

Logins with the URL of `my-lan-server` would match in the extension.

### Actual Result

No joy.

### Additional Context

I confirmed this works in the previous version `browser-v2022.10.1`

### Operating System

Linux

### Web Browser

Chrome

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by prestonvanloon** [comment]
I suspect it might be something with this PR https://github.com/bitwarden/clients/pull/3168

**Comment by prestonvanloon** [comment]
I have done a bisect to identify that #3168 changes the behavior in an unexpected way.

For example, a URL like `http://some-tld:8000` is not matching any logins with that URL after 8c59eef257bcef9d9866ed7c009784d6b586c77a. Last commit where this worked was the parent of that commit, 94e9744d0603f46fd3244d935a0e4fe9baf10e30. 

cc: OP @djsmith85

**Comment by prestonvanloon** [comment]
For more context as why this was a feature and not a bug: I am using [tailscale's MagicDNS](https://tailscale.com/kb/1081/magicdns/) and I have many services I connect to by simply typing in their machine name and not a fully valid domain.

**Comment by castigo86** [comment]
Looks like we caught the same bug, and it's spreading #4247

**Comment by Shuttleu** [comment]
Current solution is to either remove your current extension, install [V2022.10.1](https://github.com/bitwarden/clients/releases/tag/browser-v2022.10.1) and prevent it from updating.
Or build commit 94e9744d0603f46fd3244d935a0e4fe9baf10e30 and install that one (I don't believe manually installed extensions update automatically, or at least mine hasn't)

**Comment by prestonvanloon** [comment]
Thanks @castigo86 and @Shuttleu. I'll close this issue as a duplicate of https://github.com/bitwarden/clients/issues/4247
