### ISSUE TITLE
Unable to log in on Macos Desktop client

### ISSUE THREAD

**Issue by MisterJacen** [bitwarden/clients#4319]
### Steps To Reproduce

Just open the app and try to connect with correct email address and password.

### Expected Result

Successful login

### Actual Result

Login fail

### Screenshots or Videos

<img width="947" alt="Capture d’écran 2022-12-26 à 17 19 18" src="https://user-images.githubusercontent.com/37700366/209567091-b14d77e7-4526-4dc8-88d8-cf9b48344ce9.png">

### Additional Context

I use self-hosted instance.
I tried many times to directly log in from webapp and it's successful.
I made sure address I put in settings is right.
I tried to uninstall/reinstall app.

### Operating System

macOS

### Operating System Version

13.0.1

### Installation method

Mac App Store

### Build Version

Version 2022.11.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @MisterJacen, thank you for your report.

You mention you are self-hosting. Could you please provide more information about your Bitwarden server installation?

Depending on your installed version ->

![image](https://user-images.githubusercontent.com/2670567/209568350-a64e2995-eff6-48c2-ba79-d99cfc6eabdf.png)

More information on this can be found on our [help-site](https://bitwarden.com/help/)

**Comment by MisterJacen** [comment]
> Hi @MisterJacen, thank you for your report.
> 
> You mention you are self-hosting. Could you please provide more information about your Bitwarden server installation?
> 
> Depending on your installed version ->
> 
> ![image](https://user-images.githubusercontent.com/2670567/209568350-a64e2995-eff6-48c2-ba79-d99cfc6eabdf.png)
> 
> More information on this can be found on our [help-site](https://bitwarden.com/help/)

Thank you, didn't notice that information and tought my server was more recent.

It works after an update of my server !

Sorry for the waste of time.

**Comment by agustinvinao** [comment]
Client:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/61054/217618835-7fb54946-46a9-4abc-96d6-ee84bbdc89fb.png">

I can login into web and it shows:
![image](https://user-images.githubusercontent.com/61054/217621022-bc1069f9-44ae-4534-9d82-50952badc652.png)

Im using a raspberrypi cluster with K3s but I can't use the OSX app, using the same credentials it shows:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/61054/217621308-aec5488e-2b59-4b7f-b03f-459d2926e139.png">

**Comment by dwbit** [comment]
Thanks for the info @agustinvinao please keep in mind this space is for official Bitwarden support, please follow up in appropriate third party spaces for assistance.

**Comment by agustinvinao** [comment]
@dwbit this is not the place for the osx desktop version? Im using this formula to install it https://formulae.brew.sh/cask/bitwarden and it has this as the url https://bitwarden.com/
