### ISSUE TITLE
Google Chrome: bitwarden extension requires a password before the set time 

### ISSUE THREAD

**Issue by bacchilega** [bitwarden/clients#4326]
### Steps To Reproduce

1. Go to 'Settings'
2. Click on 'Security Section'
3. Click on to 'Timeout Vault' section
4. Put 72 hours
5. Wait some hour
6. Password needed

### Expected Result

Put the password afeter the custom time (example of 72 hours)

### Actual Result

The extension ask password after a couple of hours

### Operating System

Windows

### Operating System Version

Win 10

### Web Browser

Chrome

### Browser Version

last

### Build Version

Version: 2022.12.1  Server Version : 2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @bacchilega 

At the moment, all the Vault Timeout settings that I've tested on Windows 11 and Chrome Version 108.0.5359.125 work as expected (https://bitwarden.com/help/article/vault-timeout/). 

Take into account that Bitwarden decrypts your passwords when you log in. So when you close your browser (click on the X button) the session gets terminated, and you will need to log back in regardless of your settings. If you want to avoid introducing your master password again, you can configure a PIN, just make sure to uncheck the option of "Lock with master password on browser restart":
![image](https://user-images.githubusercontent.com/5418577/209979314-817cc08b-29c5-4f90-8974-6013e80acb5e.png)

I hope you find this helpful. Please do not hesitate to let me know if you have any questions.
