### ISSUE TITLE
https://www.eftps.gov/eftps/login/loginInitial Need Help

### ISSUE THREAD

**Issue by jahvari** [bitwarden/clients#4331]
### Steps To Reproduce

1. Go to https://www.eftps.gov/eftps/login/loginInitial
2. Try saving a login to use and attempt to autofill 

This website needs an EIN, which is broken into two text fields, then it needs a 4 digit pin, and then a password.

Example of EIN being used for a business and this is how it should be when logging in. This is randomly typed numbers so no private information is used. 
![Screenshot 2022-12-28 at 08-18-32 Welcome To EFTPS - Login](https://user-images.githubusercontent.com/75337667/209825857-35d5bc22-34d3-4886-901f-4001f16e7670.png)

### Expected Result

I need Bitwarden to pick up the text fields and autofill the information correctly.

### Actual Result

It does not put the autofill text in the right location

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

102.6.0 ESR

### Build Version

Version 2022.12.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @jahvari and thank you for your report

As this is not a standard login form (just username & password), you can use custom fields to fill these values.

More information can be found at https://bitwarden.com/help/auto-fill-custom-fields/

Closing this now.

**Comment by jahvari** [comment]
@djsmith85 I have attempted to do custom field and have been unable to auto-fill this information. I could use some help to see if it is possible or not.

**Comment by djsmith85** [comment]
Hi @jahvari,

As described in the linked article, the field names can be copied via the context menu or by inspecting the page's source.

Here's the configuration I saved to fill in the required information:
- Empty username and password as none are present
- URL
![image](https://user-images.githubusercontent.com/2670567/215461490-1159c552-985b-4e7b-8775-31398b280530.png)

Custom field names:
EIN1, EIN2
or
SSN1, SSN2, SSN3
PIN or password
![image](https://user-images.githubusercontent.com/2670567/215461652-e015c077-39d8-4c2e-8fb2-b42085315b6c.png)

I hope this helps, if this still doesn't work or for any further questions, please get in touch with [support](https://bitwarden.com/contact/).
