### ISSUE TITLE
Strict matching on the FQDN in the website field to avoid all subdomains being offered.

### ISSUE THREAD

**Issue by mcx808** [bitwarden/clients#4343]
### Steps To Reproduce

1. Go to 'host.subdomain.domain.tld'
2. Click on the Bitwarden plugin icon
3. Credentials for ALL hosts & subdomains within that domain will be offered. In a corporate network this is highly undesirable, especially where many systems are replicated among many subdomains (i.e. lost of host entries, for firewall / webserver / sqlserver with the same name) where they are distinguished by their folder name in the vault view, when trying to select a suggested entry they are indistinguishable unless the item details are viewed.

### Expected Result

For me it's unacceptable to show all 'fuzzy' matches on the FQDN without any distinction. 
If it's not possible to disable this, then a UI distinction should be made with the actual match as the first result (and indicated as a match) and the other fuzzy matches perhaps listed as suggestions.

### Actual Result

All hosts in all subdomains which match the top domain will be displayed in an indistinguishable order.

### Operating System

Windows, macOS

### Web Browser

Safari, Microsoft Edge, Firefox

### Build Version

Version: 2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @mcx808 and thank you for your report.

This seems like the match detection is set to use `domain`, which will match all entries with `domain.tld`.

You might need to choose a different match detection option for your case.

More information about URI match detection options can be found [here](https://bitwarden.com/help/uri-match-detection/#match-detection-options).

Closing this now, but if you feel this is not solved, please comment and provide more details, and I'll happily re-open.

**Comment by mcx808** [comment]
@djsmith85, perfect thank you! Host matching is exactly what I need.

I had searched the KB for 'subdomain matching' and 'subdomain match' but got 0 results. With your provided link it is clear, thanks.
