### ISSUE TITLE
autofill does not work for https://schwab.com

### ISSUE THREAD

**Issue by sabujp** [bitwarden/clients#4357]
### Steps To Reproduce

Google Chrome 109.0.5414.46 (Official Build) beta (64-bit)
Version: 2022.12.1
Server version: 2022.12.0

1. Go to https://schwab.com
2. extension detects the site and shows '1' underneath the extension icon in the chrome toolbar

added uri's for the vault item :
 
https://www.schwab.com
https://schwab.com
https://client.schwab.com

all with default match detection. 

4. click in the Login ID or Password fields and try right click -> autofill -> schwab.com  
5. nothing happens

Also tried regex '.*?schwab.com', site still detected but autofill still doesn't work.

Here's the username/login form item:

```
<input _ngcontent-qbg-c61="" id="loginIdInput" type="text" aria-placeholder="Login ID" aria-label="Login ID" class="ng-pristine ng-valid ng-touched" placeholder="Login ID">
```

Here's the password form item:

```
<input _ngcontent-qbg-c61="" id="passwordInput" autocomplete="off" type="password" aria-label="Password" placeholder="Password" aria-placeholder="Password" class="ng-pristine ng-valid ng-touched">
```

### Expected Result

should autofill

### Actual Result

does not autofill

### Operating System

Linux

### Operating System Version

debian

### Web Browser

Chrome

### Browser Version

109.0.5414.46 (Official Build) beta (64-bit)

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sabujp** [comment]
it appears this is the code that tries to find username and password fields? 

https://github.com/bitwarden/clients/blob/200dd0a1fb3d79391060a405adf3ce86c05e9436/apps/browser/src/services/autofill.service.ts#L1080

If so I can send a PR

**Comment by Greenderella** [comment]
Hi @sabujp 

You should be able to create two new custom fields with the ID you posted in order to be able to autofill this page: https://bitwarden.com/help/custom-fields/#creating-custom-fields

If you still encounter any problem with this page, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

Have a nice day.

**Comment by sabujp** [comment]
So the autofill seems to just work in firefox without adding any custom fields. In chrome I'm not even able to copy the custom field name for some reason, but I added "loginIdInput" as a text field with my user name and passwordInput as a hidden field with my password but, refreshed the page several times but it's still not working in chrome.

**Comment by Greenderella** [comment]
Hi  @sabujp please contact us using our form: https://bitwarden.com/contact/ 

That way, our support team can troubleshoot this issue. Thanks!
