### ISSUE TITLE
Inactive two-step login Report Error

### ISSUE THREAD

**Issue by nowasteaccount** [bitwarden/clients#4362]
### Steps To Reproduce

1. Login to Web vault
2. Go to Reports --> Inactive two-step login [ https://vault.bitwarden.com/#/reports/inactive-two-factor-report ]

### Expected Result

It should show all websites without TOTP enabled in Bitwarden

### Actual Result

Whether TOTP enabled or not in Bitwarden, it shows

GOOD NEWS
No websites were found in your vault with a missing two-step login configuration.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/121700012/210119867-6790aeff-a8fb-4683-adea-444fa9d4dd63.png)

Error screenshot below

![image](https://user-images.githubusercontent.com/121700012/210119902-52293b37-07cc-4894-8290-fa38b4eb88c1.png)

### Additional Context

Looks like web vault is unable to access to fetch at 'https://2fa.directory/api/v3/totp.json' from origin 'https://vault.bitwarden.com' 

It has been blocked by CORS policy. Request to please check server side API allowing this CORS.

### Operating System

Windows

### Web Browser

Chrome, Brave

### Build Version

Version 2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @nowasteaccount and thank you for your report.

This has already been reported and fixes (https://github.com/bitwarden/server/pull/2523 and https://github.com/bitwarden/clients/pull/4318) are currently being tested by QA.

Once these have been approved and merged, they will be included in the next release.
