### ISSUE TITLE
Chrome's WebAuthn dialog is clipped within the extension popup 

### ISSUE THREAD

**Issue by ngparker** [bitwarden/clients#4365]
### Steps To Reproduce

1. First, on Chrome, use several mobile devices to authenticate to sites while logged into Chrome and syncing. This will add several options to the Chrome WebAuthn chooser dialog. You can also use Stable + Canary Chrome on Android to ensure you've got several "phones" listed. 
2. Ensure your BitWarden account has some WebAuthn methods configured
3. Log into the Chrome Extension (I did on ChromeOS) with master password, then it asks for WebAuthn auth.

### Expected Result

I expected the Chrome popup to show all the auth method options without being clipped by the bottom and right edge of BitWarden's extension popup.  

### Actual Result

The "manage devices " button is partially obscured because the extension popup is too short, and there's no scroll bar.  Then on the next authentication screen it obscures even more, but I failed to get a screenshot.

I'm not sure if the best solution here is for the dialog to be bigger to provide sufficient space, or if somehow the Chrome authentication dialog should pop out of the extension dialog (a Chromium feature req). The latter could be problematic since it would be less clear what app/site/extension it was attached to. Adding a scrollbar seems like the minimum requirement to make it usable.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/8672111/210156896-db100ca1-7e0c-4d3f-80b3-b38a452764f0.png)

### Operating System

Linux

### Operating System Version

ChromeOS 107.0.5304.110 (Official Build) (64-bit) 

### Web Browser

Chrome

### Browser Version

107.0.5304.110 (Official Build) (64-bit) 

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi,

We changed the WebAuthn behavior in #4695 to resolve another issue. This means WebAuthn prompts are now handled in a regular browser window and this overlap should no longer appear. Closing this as resolved.
