### ISSUE TITLE
Light menubar with Dark theme on Linux desktop 

### ISSUE THREAD

**Issue by amadeusp** [bitwarden/clients#4368]
### Steps To Reproduce

1. Go to Settings
2. Click on the drop-down next to "Theme"
3. Select "Dark"
4. Enable dark mode with your host OS

### Expected Result

A completely dark Bitwarden UI.

### Actual Result

A dark UI with a light menubar.

### Screenshots or Videos

![Screenshot from 2023-01-01 18-17-48](https://user-images.githubusercontent.com/2808562/210246010-14f4f88e-11f7-4b9d-8fef-cf47eedb96c2.png)

### Operating System

Linux

### Operating System Version

Manjaro Linux x86_64

### Installation method

Other

### Build Version

Flatpak (2022.12.0)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @amadeusp and thank you for your report.

This is a know issue and is being tracked with https://github.com/bitwarden/clients/issues/2616.

Closing this as duplicate.
