### ISSUE TITLE
Can't unlock Bitwarden with Apple Watch on Safari, when macbook lid is closed

### ISSUE THREAD

**Issue by akierzkowski** [bitwarden/clients#4376]
### Steps To Reproduce

1. On Macbook (tested on Macbook Air 2021, mac os Ventura 13.0 and 13.1) with closed lid, with an Apple Watch paired and enabled to unlock the Macbook.
2. Open Safari Browser with: 
-> Bitwarden extention installed
-> User have logged in before
-> Biometrics is turned on

3. Click on Bitwarden icon to open panel.
4. Bitwarden displays message about the biometrics is turned off: 
![image](https://user-images.githubusercontent.com/49369719/210557918-f8e3c9d9-74ab-42a3-9719-bbb80ceee985.png)

### Expected Result

Bitwarden uses AppleWatch to unlock (works fine for Chrome).

### Actual Result

 Bitwarden displays message about the biometrics is turned off: 
![image](https://user-images.githubusercontent.com/49369719/210557918-f8e3c9d9-74ab-42a3-9719-bbb80ceee985.png)

### Operating System

macOS

### Operating System Version

13.0, 13.1

### Web Browser

Safari

### Browser Version

16.2

### Build Version

18614.3.7.1.5

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @akierzkowski and thank you for your report.

This is a known issue and is being tracked with https://github.com/bitwarden/clients/issues/2470.

Closing this as duplicate.
