### ISSUE TITLE
edge extension webauthn issue

### ISSUE THREAD

**Issue by fawaf** [bitwarden/clients#4384]
### Steps To Reproduce

1. update iterations for the pbkdf2 to 200000 in web vault
2. try to login on edge browser extension (username + password successful)
3. get to webauthn step

### Expected Result

successful login with webauthn/yubikey

### Actual Result

fails with "NotAllowedError: WebAuthn is not supported on sites with TLS certificate errors" error

### Additional Context

also asked in community https://community.bitwarden.com/t/edge-extension-webauthn-issue/48034

happy to provide more info if needed

### Operating System

Windows

### Web Browser

Microsoft Edge

### Build Version

2022.12.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Are you using a self-hosted instance? And do you get any certificate errors if you visit the web vault?

**Comment by fawaf** [comment]
> Are you using a self-hosted instance? And do you get any certificate errors if you visit the web vault?

I am not, no. no cert issues using bitwarden cloud.

**Comment by jordang** [comment]
I'm seeing the same issue as of the other day.  I'm running Chrome beta (110.0.5481.41, chromeos lacros), extension is up to date (2023.1.0) .

**Comment by Braddux** [comment]
Just started running into this today on ChromeOS (Version 110.0.5481.32 (Official Build) beta (64-bit)) and version 2023.1.0 of the extension.
