### ISSUE TITLE
TypeError when changing password on joining organisation

### ISSUE THREAD

**Issue by ByteBitten** [bitwarden/clients#4388]
### Steps To Reproduce

1. Have an account that's not in your organisation
2. Set password to a lower length (ex. 12)
3. Set organisation password requirement higher (ex 16)
4. Invite account
5. Join organisation
6. Get prompt to change password to comply
7. Nothing responds

Here I get this error:

> error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'score')
> TypeError: Cannot read properties of undefined (reading 'score')
>     at ep.<anonymous> (change-password.component.ts:140:24)
>     at Generator.next (<anonymous>)
>     at main.e5299c4e5a3fe32e759b.js:54:826781
>     at new t (zone.js:1351:25)
>     at iu (main.e5299c4e5a3fe32e759b.js:54:826526)
>     at ep.strongPassword (main.e5299c4e5a3fe32e759b.js:54:828235)
>     at ep.<anonymous> (change-password.component.ts:61:22)
>     at Generator.next (<anonymous>)
>     at main.e5299c4e5a3fe32e759b.js:54:826781
>     at new t (zone.js:1351:25)
>     at P (zone.js:1262:35)
>     at zone.js:1169:21
>     at zone.js:1185:37
>     at a (main.e5299c4e5a3fe32e759b.js:54:826648)
>     at t.invoke (zone.js:409:30)
>     at Object.onInvoke (ng_zone.ts:418:29)
>     at t.invoke (zone.js:408:56)
>     at e.run (zone.js:169:47)
>     at zone.js:1326:38
>     at t.invokeTask (zone.js:443:35)
> handleError @ error_handler.ts:45

Tested with Vivaldi, Firefox and Chrome (also in Privacy mode)

Changing password to required length before accepting an organisation invite does work.

### Expected Result

When clicking "change masterpassword" I expect to be enrolled into the organisation.

### Actual Result

No response. TypeError in Javascript.

### Additional Context

If I remember correctly, this was also on the self-hosted version.

### Operating System

Windows, Linux

### Web Browser

Chrome, Firefox, Vivaldi

### Build Version

Version 2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Thank you for the input!  I am closing this issue as it will be resolved in the next release with #4218.
