### ISSUE TITLE
Error unlocking vault from Chromium extension

### ISSUE THREAD

**Issue by Ryan6578** [bitwarden/clients#4403]
### Steps To Reproduce

1. Lock vault from the browser extension.
2. Enter in master password.
3. Press enter or "unlock".

### Expected Result

Vault unlocks.

### Actual Result

Nothing happens. Console output is the following:

```
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Key data must be a BufferSource for non-JWK formats
TypeError: Key data must be a BufferSource for non-JWK formats
    at Do.<anonymous> (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:375415)
    at Generator.next (<anonymous>)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:375050
    at new Promise (<anonymous>)
    at Ao (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:374795)
    at Do.pbkdf2 (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:375224)
    at vl.<anonymous> (chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:505111)
    at Generator.next (<anonymous>)
    at chrome-extension://nngceckbapebfimnlniiiahkandclblb/background.js:1:497789
    at new Promise (<anonymous>)
    at P (zone.js:1262:35)
    at zone.js:1169:21
    at zone.js:1185:37
    at a (main.js:1:51960)
    at t.invoke (zone.js:409:30)
    at Object.onInvoke (ng_zone.ts:418:29)
    at t.invoke (zone.js:408:56)
    at e.run (zone.js:169:47)
    at zone.js:1326:38
    at t.invokeTask (zone.js:443:35)
```

### Operating System

Windows

### Operating System Version

19045.2364

### Web Browser

Brave

### Browser Version

1.46.144

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Ryan6578** [comment]
Additional info:

Apparently, the "Unlock with PIN" setting was checked, but it prompted me for my master password instead. So, putting in my master password (even though that's what the plugin requested) resulted in that error. When I unchecked the setting, it works now. Re-checking and setting a PIN now prompts me for my PIN.

I'm not sure how that setting was checked and still was prompting me for a master password, but that's what the issue seemed to be. I'll leave this open regardless in case anyone wants to investigate further.

**Comment by mcmikemn** [comment]
> Additional info:
> 
> Apparently, the "Unlock with PIN" setting was checked, but it prompted me for my master password instead. So, putting in my master password (even though that's what the plugin requested) resulted in that error. When I unchecked the setting, it works now. Re-checking and setting a PIN now prompts me for my PIN.
> 
> I'm not sure how that setting was checked and still was prompting me for a master password, but that's what the issue seemed to be. I'll leave this open regardless in case anyone wants to investigate further.

I don't have a PIN set up, so if the problem you describe is happening for me, I can't log in at all and thus can't change the "Unlock with PIN" setting as a workaround. I mention this in case a dev reads your post and thinks this bug doesn't need resolution.

**Comment by atjbramley** [comment]
Hi @Ryan6578 ,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a corruption of your Brave installation, and recommend reinstalling this and your Bitwarden clients to clear the issue.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
