### ISSUE TITLE
Click in the login interface automaticaly send the input field

### ISSUE THREAD

**Issue by luciolebrillante** [bitwarden/clients#4404]
### Steps To Reproduce

1. Go to the login interface
2. Click somewhere
3. Email address is selected with an error message

### Expected Result

Nothing is selected and, create an account is available with two clicks instead of one.

### Actual Result

It is required to click twice to create an account to open the window.

### Screenshots or Videos

[Screencast from 2023-01-06 16-59-28.webm](https://user-images.githubusercontent.com/50231120/211049572-7f929e4c-a9c9-4f1e-a8c2-7d67c27671fb.webm)

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

108.0.1 (64 bits)

### Build Version

 © 2023 Bitwarden Inc. Version 2022.12.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
This issue was addressed in the February release (`2023.2`).  Please let us know if you still experience the problem.
