### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by AaronFriel** [bitwarden/clients#4408]
### Steps To Reproduce

1. Click on BitWarden extension icon while in logged out state
2. Enter email address and click "Continue"
3. Enter password and click "Log in with master password"

### Expected Result

Logged in

### Actual Result

Error message toast at the bottom of window: `An error has occurred \n can't access property "keys", i is undefined`.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/788800/211070702-335a6945-f787-45dc-8c03-f0257d9e09b3.png)

### Operating System

Windows

### Operating System Version

Windows 11 22621.963

### Web Browser

Firefox

### Browser Version

109.0b9

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @AaronFriel and thank you for your report.

This issue has previously been reported with https://github.com/bitwarden/clients/issues/4076.

Closing this as duplicate.
