### ISSUE TITLE
yubikeys 2FA with webauthn are not configured properly by bitwarden client upon enrollment

### ISSUE THREAD

**Issue by rdslw** [bitwarden/clients#4409]
### Steps To Reproduce

1. use FIDO2 compliant yubikey (not older U2F/FIDO1)
2. set pin on FIDO2 (e.g. 'ykman fido access change-pin`)
3. enroll such key as 2FA to bitwarden, using browser
4. new credentials are created (because of improper configuration*) with only user-presence required, while not user-verification required.
5. any future usage of such 2fa token, will only required touch, while not pin.

*) here I mean, that bitwarden js code upon key enrollment may  require (CTAP2 usage) specific parameters of generated credentials, like touch required, pin required etc. and currently is doing it improperly.

__

### Expected Result

Actually two scenarios are possible/correct:

1. minimal: checking if PIN is set on FIDO2 key. If so, properly mark new credential upon key enrollment as 'user-verification-required', if not, only 'user-presence'
2. full: allow user, during key enrollment, to define two options according to his needs:
touch-required/not
pin-required/not 
and create credential on key according to user selection.

### Actual Result

Currently all credentials on keys are generated with the same configuration: touch required, pin not required.

### Additional Context

a. You can read more here: https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/User_Presence_vs_User_Verification.html 

b. Although I report it under 'web bitwarden' it shall apply to most/all clients supporting fido.

c. PIN is only FIDO2 construct, in older, U2F (2014), there is no pin for credentials protection

d. current firefox has intermitent support of fido2/ctap2, while chrome/chromium supports it fully. beware of browser used during tests.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

newest

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rdslw** [comment]
It states it in "use cases" loose section, and AFAIR this is not FIDO2 recommendation. The very same article says differently:
"the user experience depends on whether or not a PIN is set or a fingerprint is enrolled on the user’s security key."

Here my point is, that if the user previously set the pin for FIDO app on key, it shall be respected, and userVerification being used. This is not happening today, even if user set pin on his key, bitwarden clients access key with FIDO1 protocol, not FIDO2.

For example, google, using chrome, adding pin enabled key to google account as a 2FA, ASKS for a pin. 2FA for google account has much lower attack surface than password manager (probably holding passwords to multiple accounts like google one).

There is also another important consideration here: PIN never reaches any bitwarden server, nor client side executed code of bitwarden clients. This gives additional strength/protection, in this attack vector area (malicious code). Also PIN can't be successfully bruteforced (contrary to shared secret), as it is quarded by the key, not by the bitwarden code nor browser/OS code. 

hence in my understanding this is strong case that requiring PIN is quite logical and recommended for keys used with bitwarden. in two scenarios:


1.    minimal: checking if PIN is set on FIDO2 key. If so, properly mark new credential upon key enrollment as 'user-verification-required', if not, only 'user-presence'
2.   full: allow user, during key enrollment, to define two options according to his needs:
    touch-required/not
    pin-required/not
    and create credential on key according to user selection.

**Comment by atjbramley** [comment]
Hi @rdslw ,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
