### ISSUE TITLE
Firefox on Android : impossible to install

### ISSUE THREAD

**Issue by JohannCR** [bitwarden/clients#4417]
### Steps To Reproduce

1. Simply try to install Firefox extension on Android 

### Expected Result

Should install

### Actual Result

Error message : install failed

### Operating System

Android

### Operating System Version

Android 11 on Fairphone 4

### Web Browser

Firefox

### Browser Version

108.2.0 (Build #2015925643)

### Build Version

cannot install...

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xanoni** [comment]
Curious, is the extension better than just setting up the Bitwarden app as your autofill provider in Android [1]? Think I saw the extension at some point but didn't want to add another potential point of failure to my stack. The native Android functionality seems to be working fine.

[1] See here: https://bitwarden.com/help/auto-fill-android/

**Comment by JohannCR** [comment]
Nope, I'm just using a self hosted vault and long story short I have not yet succeeded in configuring it properly so I cannot save entries in the app... But I can in the web version (on PC) so would like to try in Firefox mobile extension.

**Comment by rokejulianlockhart** [comment]
Works for me, same device and software. Have you tried installing via Firefox Nightly / addons.mozilla.com's (initially hidden) Collections feature?

**Comment by JohannCR** [comment]
Weird that it works for you... I don't understand are you suggesting that I use firefox nightly ? Tried and it failed just the same.
Using addons from addons.mozilla.com/fr/android

**Comment by nortti0** [comment]
Mozilla prevents developers from developing addons for non-Nightly on Android outside of a few hand-picked ones. As far as I can tell Bitwarden is not part of that hand-picked set, meaning you must use Firefox Nightly on Android if you want to install it.

**Comment by rokejulianlockhart** [comment]
@JohannCR, we might all have misinterpreted your problem – a good lesson indeed to provide specific information in bug-reports:

What do you mean by “cannot install”? Is the button disabled? If so, that is expected. If you login to addons.mozilla.org, add the extension to a collection, and add that collection to Firefox Nightly via the hidden menu, you shall be able to install the extension.

However, Bitwarden should be part of the allowed MV2 extensions. Try installing from the in-built Add-ons menu of Firefox 1st.

**Comment by JohannCR** [comment]
The button is not disabled, but when I click on it, it shows the permission popup (access tabs, store data, read clipboard, etc.) with another button. When I click on it a message shows install failed.
Exact same thing happens on firefox nightly.

**Comment by shrugal** [comment]
I have the same problem. When I try to install it from the add-ons page in the settings I get the permissions dialog, but when I confirm it I just get a toast message saying install failed.

FF version 114.1.1
