### ISSUE TITLE
Problem logging in to Schwab on IOS using Chrome

### ISSUE THREAD

**Issue by sv3ted** [bitwarden/clients#4427]
### Steps To Reproduce

1. Go to 'https://client.schwab.com'
2. Click on 'Login ID'
3. Click on (key) Passwords (IOS)
4. Select proper login account from bitwarden
5. Proper credentials are entered
6. Hit Done (IOS) to remove keyboard
7. Hit Log In
8. Login ID is removed and Schwab displays "Invalid login ID or password"

### Expected Result

Login is successful

### Actual Result

Schwab says "Invalid login ID or password"

### Operating System

iOS

### Operating System Version

16.2

### Web Browser

Chrome

### Browser Version

Chrome. Don't know version. Latest?

### Build Version

Don't know.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @sv3ted and thank you for your report.

This has previously been reported with https://github.com/bitwarden/clients/issues/4427.

Closing this as duplicate.

**Comment by sv3ted** [comment]
Daniel,

The issue I reported does not seem to me to be a duplicate. The claimed 
duplicate is an Autofill issue. In my case the Autofill is correct but 
when I hit Login the UserID field is deleted and the login fails.

Just trying to help.

Ted Myers

**Comment by Greenderella** [comment]
Hi  @sv3ted please contact us using our form: https://bitwarden.com/contact/ 

That way, our support team can troubleshoot this issue. Thanks!
