### ISSUE TITLE
Browser client tries to record OTP entry as new password

### ISSUE THREAD

**Issue by kcactc** [bitwarden/clients#4447]
### Steps To Reproduce

1. Open any portal that includes OTP in the login process.
2. Fill credentials from browser client
3. Successfully enter OTP code
4. Get prompted by browser client to save updated password.

### Expected Result

The expected behavior is for Bitwarden browser extension client to recognize OTP codes and not prompt for a password update.
Occurs in firefox, chrome, and safari. On mac and on PC.

### Actual Result

1. Open any portal that includes OTP in the login process.
2. Fill credentials from browser client
3. Successfully enter OTP code
4. Get prompted by browser client to save updated password.

### Operating System

Windows

### Operating System Version

Win10

### Web Browser

Firefox

### Browser Version

108.0.1 (64-bit)

### Build Version

Version: 2022.12.1  Server version: 2023.1.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I'm unable to reproduce this issue with any of the pages where I normally use TOTP codes as my 2FA. Could you please share with us some of those pages where Bitwarden is offering to save your TOTP code? Also, are they generated by Bitwarden or by a third party application?

Thanks!
