### ISSUE TITLE
chrome extension does not ask for password for note even though 'Master password re-prompt' is checked

### ISSUE THREAD

**Issue by sanderkerel** [bitwarden/clients#4448]
### Steps To Reproduce

1. Create a secure note with 'Master password re-prompt' checked.
2. In the chrome extension open the note.

### Expected Result

Before I can see anything I expect a master password reprompt, as described in the documentation.

### Actual Result

The contents of the note are plainly visible.

### Additional Context

This is not the behaviour described in the help-page: https://bitwarden.com/help/managing-items/#protect-individual-items

> For any item, you can activate the Master password re-prompt option from the Add/Edit screen to require verification of your master password to *access* or auto-fill sensitive vault items
(emphasis on *access* is mine)

In the Bitwarden Web Vault it does work as expected.

So, in chrome the password reprompt checkbox protects me from unauthorized _editing_, but not unauthorized _viewing_. That is not very useful to me.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

108.0.5359.125

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dennisbabkin** [comment]
> Hi @sanderkerel, this is the expected behavior, at the moment the master password re-prompt only triggers for passwords or hidden custom fields.
> 
> If this is important to you, please consider joining our community and voting for it on our feature request page: https://community.bitwarden.com/t/require-re-prompt-for-entire-item-view-edit-etc/31737
> 
> I hope you find this helpful. Please do not hesitate to let me know if you have any questions.

That's quite a lousy "expected behavior" for a "password manager".

**Comment by dwbit** [comment]
Hey @dennisbabkin thanks for providing additional detail. The current behavior is the how the initial functionality was requested by the community and the team is working on several different enhancements to this feature, such as including biometric options and protecting the whole vault item, stay tuned for updates!

**Comment by maximus321** [comment]
Is there a feature request for this?

I find the behavior misleading, in the web app, the prompt master password works for viewing.
In the web extension (chrome), it does not work for viewing, but works for editing.

It would be nice to have a toggle for both feature
- prompt master password for viewing
- prompt master password for editing

OR
- prompt master password (that works for both view and edit, like the web app does)

I don't want to leave my personnal computer open and someone comes and copy paste all my info. 
Thanks!
