### ISSUE TITLE
Bitwarden Linux AppImage no longer auto updates since last few releases

### ISSUE THREAD

**Issue by pizzadude** [bitwarden/clients#4464]
### Steps To Reproduce

Use an older release of Bitwarden AppImage (for example: version 2022.12.0)
Check for updates
Notice it says there are no updates available, even though there are
See this in the terminal:
Update for version 2022.12.0 is not available (latest version: 2023.1.0, downgrade is disallowed).

### Expected Result

For it to auto update

### Actual Result

It doesn't auto update

### Additional Context

Since version 2022.12.0 of the Bitwarden Desktop release, The Linux AppImage is not auto updating to new releases anymore. This started happening last few releases.

### Operating System

Linux

### Operating System Version

Fedora 37

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dwbit** [comment]
Hey @pizzadude the release is staggered and it takes time for releases to become available for upgrading. Closing this one for now as expected behavior, feel free to add additional comments.
