### ISSUE TITLE
Empty folders are shown in all vaults (privat and organization vault view)

### ISSUE THREAD

**Issue by Diesmo** [bitwarden/clients#4471]
### Steps To Reproduce

Prerequirements:
Have an Bitwarden account with access to a Organization.

1. Go to the Webvault or Windows Desktop App and login (tested only those too in 2023.1.0)
2. Click on "My Vault" in the left sidebar to see only your privat Vault view.
3. Create an empty folder via the plus(+) icon in the sidebar, name it any unique name (e.g Test123456).
4. Now switch to the Organization vault view via the sidebar.
5. The created test folder should be visible in the organization vault view.
6. If you do step 3 with a nested folder (creating a empty folder inside a folder that has items) you will see the whole path in the organization vault view. E.g. "FolderWithItems/Test123456"
7. Delete the empty folder while being in the Organization vault view. This will delete the folder in your private vault as well (because it's a display bug)
8. This also works in the other direction (creating empty folder in Organization vault view and switching to private vault view).

### Expected Result

Not being able to see empty folders that are not an actual synced part of the Organization because other Organization members do not see my empty folder in their client, but instead they see their own empty folders inside the Organization vault view.

### Actual Result

Empty folders are somehow treated as being part of whatever vault you are currently viewing. Regardless in which vault they belong. Visual bug only as they are **not synced**.

### Additional Context

Very annoying, especially when creating an Organization for the first time, like I did 30min ago, and then wondering why it "moved" my privat folder structure into the shared vault of the organization.

### Operating System

Windows

### Web Browser

Vivaldi

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dwbit** [comment]
Hey @Diesmo folders are only used to organize your personal view and are never seen by other organization members. They can include items from any vault you have access to, including shared organization items. 

In a future iteration of Bitwarden, folders will be replaced with vault item labels. As this is currently expected behavior, closing the issue.

**Comment by Diesmo** [comment]
Okay, sounds very strange to me that this is indented behavior, because it screams UI bug to me, but okay.

But to make sure that my problem was understood correctly, please confirm to me that those two screenshots are indeed the intended UI behavior if one switches between "My Vault" and "Organization Vault/Items" view. My Organization is btw empty, no items are shared to it currently, freshly created Orga.

![vivaldi_2023-01-15_14-31-46](https://user-images.githubusercontent.com/17813062/212543838-db580f77-00c0-493c-aab6-2333c714d55c.png)
![vivaldi_2023-01-15_14-28-01](https://user-images.githubusercontent.com/17813062/212543847-fe800bd2-6ce0-445d-bde9-92d80f39d216.png)

Blurred folders are the folders with items assigned to them.

If this is somehow indeed intent, it can be closed for good, even tho I absolutely don't understand why the empty folders of the other vault structure show up and only the empty ones.

**Comment by dwbit** [comment]
Thanks for your patience, reviewing this one with the team.

**Comment by Diesmo** [comment]
Seems like #4455 and #3163 are the same issue as this one and therefore all duplicates of each other.

But you guys always close those tickets and explain that this is expected behavior.

So what is it now? 

Should one see empty/newly created folders, be it manually created or via Importer, across all 'view filter' or not? 

That's the core question that needs to get answered, because if the answer is yes, then it's expected behavior, although absolutely not understandable from a UX point of view. 
And if the answer is no, then all three tickets are, in my eyes and if I understood the others correctly, valid bug reports that should not be closed.

**Comment by GeertTech** [comment]
Thanks for pursuing this, @Diesmo. I really hope it's a bug, otherwise (as you said) it is a truly baffling UX decision.

**Comment by laspinacristian** [comment]
I'm having the same problem and tought it was a bug.
This way of maniging folders has no sense whatsoever
