### ISSUE TITLE
Problems building desktop app from source on Windows 11

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/clients#4475]
### Steps To Reproduce

I've recently upgraded to Windows 11, and now find that I can't seem to run/build the desktop app from source here for development purposes.

I've tried starting again from scratch in ubuntu/wsl2, running the general steps first https://contributing.bitwarden.com/getting-started/clients/ and then the linux-specific steps https://contributing.bitwarden.com/getting-started/clients/desktop/ (with addition of the cross-compilation setup from https://github.com/bitwarden/clients/issues/3544#issuecomment-1382903971 since at first it was giving me errors about missing module '@bitwarden/desktop-native-linux-x64-musl').

However, when trying to then `npm run electron`, a linux GUI window does open, and has the app's menus, but the main part of the app itself refuses to load - in devtools, it's showing me an error "Not allowed to load local resource".

I then tried to instead go via PowerShell ... again, made sure all the general requirements were met (including re-running `npm ci`) https://contributing.bitwarden.com/getting-started/clients/ and then the windows-specific steps https://contributing.bitwarden.com/getting-started/clients/desktop/ (and rebuilding desktop_native again)

However, when trying `npm run electron` this time, it all goes through up to the "webpack ... compiled" part, but no window appears, and no error messages are shown.

Is there anything I might be missing? /cc @hinton @djsmith85 

### Expected Result

Before my Windows upgrade, I used to be able to `npm run electron` from the terminal/WSL2 in VS Code, and it would fire up the windows version of the compiled app - but admittedly, can't remember if I had to do anything special at the time to get it running. Any idea/hint would be appreciated, as this is now preventing me from testing/submitting PRs

### Actual Result

Currently unable to fire up desktop app from source

### Screenshots or Videos

![screenshot of VS code's terminal and the linux GUI window](https://user-images.githubusercontent.com/895831/212502592-3a55b333-b375-4c4c-9999-bab50f796111.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Other

### Build Version

Latest from master

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by patrickhlauke** [comment]
i have no idea what actually fixed it (perhaps doing an `npm run clean:dist` and `npm run build` before `npm run electron`?), but I somehow managed to get the linux version under WSL to actually fire up. closing this for now and chalking this up to just some weird setup issue...

**Comment by Hinton** [comment]
@patrickhlauke I can't really endorse running the electron app in WSL. It's not a configuration we support and since the desktop application integrates with native services both on Windows and Linux I would expect undefined behavior.

**Comment by patrickhlauke** [comment]
I'll see if i can get the PowerShell flow to work...but while trying to get it to work, it kept hanging.

Not sure why/how, but with my currently fixed setup, even though i start electron from WSL, it now fires up the windows-native desktop app / integrates with Windows Hello, so I'm in some sort of demi-monde it seems. It all works just like the regular native windows desktop app... *shrug*
