### ISSUE TITLE
Sends tab not rendering fully Firefox private tab

### ISSUE THREAD

**Issue by wnelson03** [bitwarden/clients#4483]
### Steps To Reproduce

1. Go to Bitwarden on FireFox private tab
2. Click on Bitwarden and then the sends tab
3. Look at send names and most likely not all of them will be rendered

### Expected Result

All the send names render when I click the sends tab the first time.

### Actual Result

I have to click on the sends tab multiple times to get a majority of the send names to render, and still not all of them render.

### Screenshots or Videos

https://www.youtube.com/watch?v=6_dFwwgqshU

### Additional Context

At this time I'm only seeing this issue with Firefox private tab, though I'm not positive it isn't an issue in the normal non-private mode as well.
I have 32GB of ram and Firefox was only using around 1600MB of that. After recording the video listed above, I closed all pages but this GitHub tab, so I only had 1 Github.com page open in non-private mode and one Firefox new tab page open in private mode, and the issue still occurred. So it doesn't seem to be a memory limitation. 

### Operating System

Windows

### Operating System Version

Version 21H2 19044.2486

### Web Browser

Firefox

### Browser Version

108.0.2

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! We are able to reproduce this issue, if you wish to add any other information/screenshot or so, please do it here and our engineering team will review it.

Thanks!

**Comment by wnelson03** [comment]
@atjbramley are there any updates on this?

**Comment by dbosompem** [comment]
Hi @wnelson03 , no updates yet. We will make time and take a look, and update accordingly. Thanks for your patience!

**Comment by Greenderella** [comment]
We wanted to let everybody know that this issue has been addressed. With the 2024.6.0 update, the Firefox extension now operates with full functionality in private windows.

![sendFirefox](https://github.com/user-attachments/assets/0044abe5-d96d-4790-99d3-a3c090e82aea)

For more details on this update, you can refer to the [release notes](https://bitwarden.com/help/releasenotes/#2024-6-0).

I will proceed to close it.
Thanks!
