### ISSUE TITLE
This cli feedback should go to /dev/stderr instead of /dev/stdout 

### ISSUE THREAD

**Issue by dewijones92** [bitwarden/clients#4486]
### Steps To Reproduce

Thanks for this amazing tool, I just have some feedback that will make the cli a bit better. thanks :)

1. Run this `bw get attachment --output /dev/stdout --itemid $ID 2>/dev/null`

### Expected Result

***SOLELY THE CONTENT OF THE FILE ATTACHMENT**

### Actual Result

Saved /dev/stdout
***THE CONTENT OF THE FILE ATTACHMENT**

### Additional Context

I am trying to inject a secret in to my docker container by piping the output of `bw get attachment --output /dev/stdout --itemid $ID 2>/dev/null` into a docker container. 
I don't want it to save to a real file on disk - for security reasons - hence the `--output /dev/stdout `
The issue is:   
The results of the above command gives me logging: "Saved /dev/stdout". And this is also piped to my docker container - which I don't want.   
I suggest we change the command output so that logging message goes to /dev/stderr instead.   

I believe the diff is something like this, but I am having trouble building the repo so I can't test it:  
```
pi@raspberrypi:~/code/clients/apps/cli $ git diff src/utils.ts
diff --git a/apps/cli/src/utils.ts b/apps/cli/src/utils.ts
index e41c1c789..f4bd11785 100644
--- a/apps/cli/src/utils.ts
+++ b/apps/cli/src/utils.ts
@@ -142,7 +142,7 @@ export class CliUtils {
     }

     const filePath = await this.saveFile(data, output, defaultFileName);
-    const res = new MessageResponse("Saved " + filePath, null);
+    writeLn(error: "Saved " + filePath);
     res.raw = filePath;
     return Response.success(res);
   }
```

Thanks :)

### Operating System

Linux

### Shell

Bash

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dewijones92** [comment]
or is there an easier way to output attachment contents to /dev/stdout that I am not aware of? lol

**Comment by joshtrichards** [comment]
I was going to suggest a quick workaround (appending a `| grep -v "Saved /dev/stdout"` to your command-line), but I rechecked and appending `--quiet` to the BW CLI command-line should accomplish what you're looking for:


`
bw get attachment $FILENAME --output /dev/stdout --itemid $ITEM_ID --quiet
`

It's documented, but stashed away at the end of the docs a bit under "Global Options":

  https://bitwarden.com/help/cli/#global-options

**Comment by Greenderella** [comment]
Hi @dewijones92 

I've tested @joshtrichards suggestion, and it seems like that exactly what you are looking for. I will check with the documentation team to see if we can add this example here: https://bitwarden.com/help/cli/#global-options

This issue will now be closed. If you encounter any problems running the commands or anything similar, please write us back using our contact form, that way someone on our dedicated support team can help you: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Thanks!
