### ISSUE TITLE
The connection from the firefox extension to the windows app never connects even after a reinstall.

### ISSUE THREAD

**Issue by GarnetSunset** [bitwarden/clients#4501]
### Steps To Reproduce

1. Go to 'unlock with biometrics'
2. Click on it
3. See the "awaiting confirmation from desktop", nothing from the desktop app

### Expected Result

The popup comes through from bitwarden desktop.

### Actual Result

Unlocking with hello works on the desktop app, but it doesn't connect and prompt for unlock. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13430434/213079081-f5a67d4c-146b-40e0-8a65-559957be69ca.png)

### Additional Context

Worked up until like... 2 days ago?

Are there any logs I can attach? I can't find any for the browser app, and the desktop logs seem to be devoid of hello attempts.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Firefox

### Browser Version

109.0

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
The issue stems from the HKEY_CURRENT_USER\Software\[your_browser]\NativeMessagingHosts\com.8bit.bitwarden registry key not being created.  You can try the below steps, with which some users have reported success:

**In Bitwarden Desktop**

​Disable Login With Windows Hello

Disable Browser integration.

**Restart your machine**

**In Bitwarden Desktop**

Enable Browser Integration

Enable Windows Hello / Biometrics

**In the Browser Extension:**

Enable Biometrics

**Comment by GarnetSunset** [comment]
It's working now! That did indeed fix it!
