### ISSUE TITLE
Bottom of password list is truncated after updating password

### ISSUE THREAD

**Issue by btemplep** [bitwarden/clients#4508]
### Steps To Reproduce

1. Go to Vault tab, and scroll until all entries load (I have about 250).
2. In the chrome browser extension, update a password near the bottom
3. When the vault is reloaded it will truncate the passwords list.

### Expected Result

All passwords will load again in the browser when a password is updated form the chrome browser extension.

### Actual Result

The vault reloads and the password list is truncated after updating from the chrome browser extension.

### Operating System

Linux

### Operating System Version

Pop!_OS 22.04

### Web Browser

Chrome

### Browser Version

Version 108.0.5359.98 (Official Build) (64-bit)

### Build Version

Version 2023.1.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

I was not able to replicate this. Would it be possible to provide a short video of this issue?
