### ISSUE TITLE
After upgrading to 2023.1.1 Bitwarden's window stays on top even when passive

### ISSUE THREAD

**Issue by Th1990** [bitwarden/clients#4512]
### Steps To Reproduce

1. Open Bitwarden desktop app
2. Move any other window to place where Bitwarden's window is

### Expected Result

When Bitwarden's window is passive it should not conceal active window.

### Actual Result

Bitwarden's window stays on top always concealing all other windows in the same position.

### Screenshots or Videos

Here Firefox is active window but Bitwarden still stays on top of it concealing the view.
![kuva](https://user-images.githubusercontent.com/16610255/213416855-4c44d6bf-6a9c-4d9e-9eea-78732e5573c3.png)

### Additional Context

This beaviour appeared after Bitwarden to auto upgraded to new version:
```
Version 2023.1.1
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64
```
There was no issue on previous version I had.

Desktop environment:
```
Gnome Version 3.32.2
```
Bitwarden is running as AppImage.
Minimizing Bitwarden's window still works.

### Operating System

Linux

### Operating System Version

Red Hat Enterprise Linux 8.7 (Ootpa)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi, 
I recreated your environment and unable to reproduce this.  I'd recommend looking at any tools that you have that may be modifying your window manager's settings.

If your issue persists, please contact us via our support team at https://bitwarden.com/contact/
