### ISSUE TITLE
FF extension shows empty vault after the master password change

### ISSUE THREAD

**Issue by dennisbabkin** [bitwarden/clients#4522]
### Steps To Reproduce

Change the master password using the web page (not the extension.) Then click on the extension icon. You should see master password prompt. When you enter the new master password the vault will be empty.

 Bitwarden

© Bitwarden Inc. 2015-2023

Version: 2023.1.0

Server version: 2023.1.0 

### Expected Result

I would expect to see my vault contents 😁

### Actual Result

The vault is empty

### Additional Context

To resolve this I had to remove the FF extension for Bitwarden and then re-install it. After that the vault started showing up items.

### Operating System

Windows

### Operating System Version

Win 10 x64

### Web Browser

Firefox

### Build Version

see above

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi, 
Please sign out and back in again to refresh the contents of the vault.

If this doesn't resolve the issue then please get in touch with our CS team at https://bitwarden.com/contact/

**Comment by dennisbabkin** [comment]
@atjbramley that did not help. I am reporting an issue to whoever cares to read it from the Bitwarden dev team.

**Comment by dennisbabkin** [comment]
Wow, how the f is it closed? This is a good sign to stay away from this password manager. Thank you.

**Comment by atjbramley** [comment]
Hi Dennis, 

I attempted to reproduce your issue and was unable to do so.  As such, your issue is better handled by our Support team.

If, after further investigation, we discover that this is an issue affecting numerous Bitwarden users we will happily assign engineers to investigate further.

Please do get in touch with our CS team so that we can have a look at what might be causing this particular issue on your machine.

**Comment by dwbit** [comment]
Hey @dennisbabkin thanks for providing the additional information and completely understand your sentiment. We don't have any action to take on this one until the support team can follow up on additional detail and troubleshooting. After that point, a bug report can be generated and followed up on if needed, thanks for your understanding.
