### ISSUE TITLE
"Master password re-prompt" option doesn't ask for master password to view secure notes

### ISSUE THREAD

**Issue by dennisbabkin** [bitwarden/clients#4523]
### Steps To Reproduce

FF extension - enable "Master password re-prompt" option for a secure note. Save it. And then try to open it. The master password is not re-prompted for viewing that note.

### Expected Result

Master password prompt to view the secure note

### Actual Result

Read above

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2023.1.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@dennisbabkin Thank you for your report. 

As this has previously been reported with https://github.com/bitwarden/clients/issues/4448 I'm am closing this now as duplicate.
