### ISSUE TITLE
"Important:" Seems to be untranslateable in the account registeration form

### ISSUE THREAD

**Issue by olavinto** [bitwarden/clients#4538]
### Steps To Reproduce

I just noticed that on the account registration form (of the web application), there is an untranslated word "Important:" and it does not seem to be available for translation at Crowdin either.

There is also some styling difference going on with (optional = valinnainen) vs. (required = pakollinen). It seems that the (required) phrases are handled as separate strings while the (optional) one is a part of the field title.

Check the attached screenshot (which has been taken from the Finnish form).

### Expected Result

Should be available for translation at Crowdin.

### Actual Result

Is not available for translation at Crowdin. :-)

### Screenshots or Videos

![regform](https://user-images.githubusercontent.com/23163218/214059547-5005d15f-fcad-406c-93ab-6f6148f539c7.png)

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Here's the line in question: https://github.com/bitwarden/clients/blob/c62f3a9607024f5ef4e8939bfb8ea8d85e46978b/apps/web/src/app/accounts/register-form/register-form.component.html#L48
