### ISSUE TITLE
Autofilling with multiple tabs 

### ISSUE THREAD

**Issue by brrry2022** [bitwarden/clients#4559]
### Steps To Reproduce

1. Using Firefox Bitwarden Sidebar . Open https://www.paypal.com/home 
2. Sign in to Bitwarden Sidebar. (Bitwarden sidebar will show all matching logins for that page)
3. Click Sign-in in paypal to open the sign-in page. 
4. Click the matching login in from Bitwarden sidebar. " Unable to auto-fill the selected item on this page."  Pop up
5. Click Bitwarden Refresh button then auto-fill will work. (don't click the login button in paypal webpage)
6. Create another tab in firefox and open https://www.paypal.com/signin
7. Click the matching login in from Bitwarden sidebar. Bitwarden will auto-fill  the previous page not the active on. I have to refresh the sidebar again.

### Expected Result

Bitwarden should  auto-fill the active page. 

### Actual Result

When signing in to a webpage and not knowing you have existing tab with the same page. 

### Screenshots or Videos

https://youtu.be/YShKvz8hyYw
https://youtu.be/HoR6XrfDHAM
https://youtu.be/QR5kawg5vu4

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

109.0 (64-bit)

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

If you have performed a clean installation of the browser extension already by removing any leftover data (https://bitwarden.com/help/data-storage/#on-your-local-machine), I suggest you try to refresh your Firefox's profile following their instructions: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by brrry2022** [comment]
I followed your suggestion with same result.

**Comment by Krychaz** [comment]
Unfortunately I was able to reproduce this behaviour. We will be on a lookout for similar reports however for now we will close this issue.
