### ISSUE TITLE
sync fails, exception object doesn't contain .toString()

### ISSUE THREAD

**Issue by maxxer** [bitwarden/clients#4587]
### Steps To Reproduce

Run `bw sync`

### Expected Result

Sync completes

### Actual Result

```
❯ bw sync
/usr/local/Cellar/bitwarden-cli/2023.1.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:33990
                return Response.error("Syncing failed: " + e.toString());
                                                             ^

TypeError: Cannot read properties of null (reading 'toString')
    at SyncCommand.<anonymous> (/usr/local/Cellar/bitwarden-cli/2023.1.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:33990:62)
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/Cellar/bitwarden-cli/2023.1.0/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:33965:65)

Node.js v19.5.0
```

### Additional Context

Sync fails from Firefox as well, showing a red flash message.

### Operating System

macOS

### Operating System Version

12.6.2

### Shell

Zsh

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maxxer** [comment]
After retrying a couple of times I got logged out. Logging in again worked fine, no error thrown

**Comment by Adedamola-Aina** [comment]
i will proceed to close this request as this issue seem fixed.
