### ISSUE TITLE
Cannot connect to my self-hosted bitwarden environment with the firefox extension

### ISSUE THREAD

**Issue by pnizet** [bitwarden/clients#4595]
### Steps To Reproduce

1. Set the server URL
2. enter your email address
3. enter your password
4. try to connect

Ubuntu just updated to 20.04 LTS
Firefox in 109.0
extension in 2023.1.0
self host BW in Version 2.20.4 

### Expected Result

Connection
My credentials are good, I managed to connect on the web page of my self-host

### Actual Result

Username or password incorrect. Try again

### Operating System

Linux

### Operating System Version

ubuntu 20.04 LTS

### Web Browser

Firefox

### Browser Version

109

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by grzenio-l** [comment]
I have exactly the same problem (Windows 10, Firefox 109.0, extension 2023.1.0, self-hosted Vaultwarden). The issue only started about 2 hours ago. Rolling back the Bitwarden extension for Firefox to version 2022.10.1 helps, each subsequent version has this issue.

**Comment by dwbit** [comment]
Hey @pnizet please update your server, see https://bitwarden.com/help/november-deprecation-notice/ for more information.

**Comment by pnizet** [comment]
My self host is in version 2.20.4 which is not concerned by 'November Deprecation Notice'

**Comment by djsmith85** [comment]
@grzenio-l: Please have a look [here](https://github.com/dani-garcia/vaultwarden/issues/3082), as you are using Vaultwarden.

@pnizet None, of [our server-releases](https://github.com/bitwarden/server/releases) have that version number, so you are likely using an unofficial version. Please check with your maintainer and update your server.

**Comment by pnizet** [comment]
@djsmith85 thanks.
An update of Vaultwarden fixs this.
