### ISSUE TITLE
2FA page in Chrome extension is broken when opened full-tab

### ISSUE THREAD

**Issue by ruuda** [bitwarden/clients#4608]
### Steps To Reproduce

1. Open chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#/home
2. Enter email address ruud@chorus.one, check remember, click login.
3. Enter master password and press enter.

Alternatively to step 3, I can also enter the master password and click “enterprise SSO” (our organization has this enabled). After going through the SSO flow, I end up at the same page described below.

### Expected Result

I am able to sign in, possibly after confirming 2FA.

### Actual Result

I see this page:

![bitwarden-after-login](https://user-images.githubusercontent.com/506953/215754920-0f3ffdfd-7616-4cbc-aeb7-166841873693.png)

The blue rectangle appears to be a button without text in it. Clicking it does nothing. Pressing my Yubikey does nothing. My Yubikey is inserted.

### Additional Context

I was signed in to the extension, but it didn’t sync. If I recall correctly, the error message was “unable to fetch”. I uninstalled the extension and reinstalled it, because this previously fixed an “unable to fetch” problem, but now I am unable to sign in at all.

Note, I only get the page with the Yubikey picture if I open the extension in its own window. If I open the extension on a page, previously I did not get to the Yubikey page at all, but now that I try again, it did create a browser prompt for the Yubikey and it did sign me in. It also does show text in the blue rectangle in that case (“sign in with Webauthn” if I recall correctly) :thinking: 

### Operating System

Linux

### Operating System Version

6.1.4

### Web Browser

Chrome

### Browser Version

Chromium 109.0.5414.74 (Official Build) Arch Linux (64-bit)

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @ruuda,

I've tested this on Ubuntu 22.10 using Chrome 109.0 and Chromium 109.0, and the FIDO2 WebAuthn prompt is operating as expected when the extension is open in its own tab (chrome-extension://nngceckbapebfimnlniiiahkandclblb/popup/index.html#/home). Based on the description and the prior error messages you've encountered, it seems like a network-related matter caused that.

We use GitHub to track bugs and other development related issues. If this behaviour persists, please feel free to get in touch with us via this form (https://bitwarden.com/contact/) so we'll troubleshoot this, and please include a link to this GitHub thread in your message.

Alternatively, you can get help from the Bitwarden community in the forums here (https://community.bitwarden.com/c/support/). 

I thank you in advance for your understanding; This issue will now be closed.

**Comment by ruuda** [comment]
This issue is happening again to me, sync was broken again and then [login was broken again with the "failed to fetch" error](https://github.com/bitwarden/clients/issues/1977#issuecomment-1211069100). After signing out, I am now again on the 2FA page without buttons. I think it may be related to https://github.com/bitwarden/clients/issues/1612#issuecomment-1116438789 — I have configured the extension to only be allowed after click.

**Comment by ruuda** [comment]
In the non-full-tab extension, I now get the following error:

> NotAllowedError: WebAuthn is not supported on sites that have TLS certificate errors.
