### ISSUE TITLE
Password generator preview value is not wrapping

### ISSUE THREAD

**Issue by codeaid** [bitwarden/clients#4614]
### Steps To Reproduce

1. Click on the **"Add item"** button.
2. Click on the **"Generate password"** button.
3. Expand password generation options.
4. Change desired password length to more than 33 characters.
5. Observe password preview string overflowing outside its container instead of wrapping (like it used to when I first installed the application a couple months ago).

### Expected Result

![image](https://user-images.githubusercontent.com/637799/215869527-9ab3a761-2a28-43c8-88cb-f022c1be3fa3.png)

### Actual Result

![image](https://user-images.githubusercontent.com/637799/215869302-dc72eeb4-ddee-4d72-a4f6-d7dd8ee60b27.png)

### Additional Context

This can be fixed by adding the following CSS rule to the `.generated-block .generated-wrapper` selector in `misc.scss`:
```css
word-break: break-all;
```

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@codeaid Thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/4469

Closing this as duplicate.
