### ISSUE TITLE
Blank Box in Safari When Adding Password

### ISSUE THREAD

**Issue by adamesq** [bitwarden/clients#4621]
### Steps To Reproduce

Cause BitWarden to prompt to remember password.

### Expected Result

Box in BW's title bar for remembering a password should be clickable

### Actual Result

Box in BW's title bar for remembering a password is not clickable

### Screenshots or Videos

![Screen Shot 2023-02-01 at 12 26 18 PM](https://user-images.githubusercontent.com/34196956/216172337-f33133db-0eb1-41f8-8f0c-6ce74d19575c.jpg)

### Operating System

macOS

### Operating System Version

11.7.3

### Installation method

Mac App Store

### Build Version

2023.1.1 (6572)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi there,

Thank you for your report! We are able to reproduce this issue, if you wish to add any information/screenshot/recording or so, please do it here and our engineering team will review it.

Thanks!

**Comment by dmedi011** [comment]
Any update?

**Comment by adamesq** [comment]
Yes! Apple’s update yesterday finally fixed this issue! I figured the BW team was involved in that discussion. Thank you for asking…and reminding me to upgrade BW, actually. I’ll be getting other family moved over from Last Pass.Sent from my iPhoneOn Feb 16, 2023, at 2:48 PM, dmedi011 ***@***.***> wrote:﻿
Any update?

**Comment by adamesq** [comment]
I apologize. My last reply was regarding the fix for missing icons which was fixed. I didn't realize that the email I received was related to the issue above in _this_ thread. The problem here still exists. I couldn't even click "Save." The bar is still not clickable in 2023.2.0 (7249) under Safari 16.3.1.

**Comment by djsmith85** [comment]
A resolution for this has been merged into main and will be present in the upcoming release of the extension.

https://github.com/bitwarden/clients/pull/7729

Closing this Github issue for now, if the issue persists past the release of extension v2024.3.0, then we can re-address any potentially missed issues.
