### ISSUE TITLE
(After lock/unlock?) Zoom setting resets without intervention

### ISSUE THREAD

**Issue by mcint** [bitwarden/clients#4643]
### Steps To Reproduce

1. Open a Bitwarden vault, change zoom to non-default: e.g. zoom out (Cmd--) 3 times. ~2. Lock/Unlock~
3. Enter a new search term
4. Select a result, and tab into the entry, e.g. to the copy button
5. Change the zoom setting again, say Cmd-- again.
    - Notice that the zoom gets bigger, even though you asked for further zooming out.
    - The default changed out from under the user

### Expected Result

Application interface continues to zoom out.

### Actual Result

Application interface, seems to apply zoom settings to the default value, instead of the current value.

### Additional Context

Bitwarden / About:
Version 2023.1.1
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

### Operating System

macOS

### Operating System Version

12.6.3

### Installation method

Homebrew

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

We only support width setting at the moment. This will be a feature request. We invite you to post it on our forums feature request - https://community.bitwarden.com/c/feature-requests/5/none

**Comment by mcint** [comment]
Best I can tell, if this was merged on Dec 15, 2022, but I have version 2023.1.1, then this is still an issue.

**Comment by mcint** [comment]
#2623 first tracked this.
