### ISSUE TITLE
Brave browser 1.48.158 with Bw extension 2023.1.0 - -webauth = “not allowed error: webauthn is not supported on site with TLS certificate errors”

### ISSUE THREAD

**Issue by cyanide699** [bitwarden/clients#4691]
### Steps To Reproduce

since brave updated today 1.48.158
using the bitwarnden extension to sign in to bitwarden using fido/webauthn (yubikey bio) gives the error
“not allowed error: webauthn is not supported on site with TLS certificate errors”

Edge & the previous Brave and works OK 1.47.186

other webauth sites (google/twitter/proton/nextcloud etc are not affected, it appears to be only bitwarden extension & this latest version of brave

### Expected Result

no error, asks for key touch

### Actual Result

error
“not allowed error: webauthn is not supported on site with TLS certificate errors”

### Operating System

Windows

### Operating System Version

11

### Web Browser

Brave

### Browser Version

1.48.158

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kpiris** [comment]
This error also happened to me this morning with the google chrome extension (with google chrome version 110).

And [it seems I'm not the only one](https://community.bitwarden.com/t/edge-extension-webauthn-issue/48034/9).

**Comment by crypt0rr** [comment]
Same here.

> Brave Version 1.48.158 Chromium: 110.0.5481.77 (Official Build) (arm64)

**Comment by timowevel1** [comment]
Why closed? Still doesnt work for me

**Comment by bitstobreath** [comment]
> Why closed? Still doesnt work for me

It is most likely not pushed to the upstream production builds yet.

**Comment by mmfire118** [comment]
I have this issue as well in Brave v1.48.158 with extension version 2023.1.0

**Comment by crypt0rr** [comment]
Quick fix is to downgrade to [Brave v1.47.186](https://github.com/brave/brave-browser/releases/tag/v1.47.186)

**Comment by cyanide699** [comment]
> Quick fix is to downgrade to [Brave v1.47.186](https://github.com/brave/brave-browser/releases/tag/v1.47.186) for now until update pushed to public.

Using an older version of a browser with its possible security risks is a daft idea...
For now keep your browser current & just enable and use totp for the extension until bw deem this important enough to release a fix

**Comment by bitstobreath** [comment]
Yeah I have what I need working... so I am just gonna leave it as is, secure browser and all.

**Comment by laaghalerveennl** [comment]
Exactly the same problem here on Chrome. Guess we have to wait it out then ?

**Comment by cyanide699** [comment]
> Exactly the same problem here on Chrome. Guess we have to wait it out then ?

no you dont ....you have options

- use older version (maybe security risks)
- start chrome with the flag –disable-features=DisableWebAuthnWithBrokenCerts
- or wait it out

**Comment by cyanide699** [comment]
bw extension updated today 2023.2.0 and this now works again

albeit with a lot more steps and opening extra tabs 

- open extension
- enter password
- click on authenticate
- a new tab opens
- click on authenticate again
- press your key when prompted
- close the tab

the old method was far more graceful & quick
> open extension
> enter password
> press key when prompted


its actually quicker now and less steps to just enter a toto code than use a yubikey with the extension
