### ISSUE TITLE
Bitwarden doesn't ask for saving credential

### ISSUE THREAD

**Issue by gui0506** [bitwarden/clients#4731]
### Steps To Reproduce

1. Go to https://pay.toronto.ca/auth
2. Fill credentials
3. Click on Log in

![截屏2023-02-12 19 33 38](https://user-images.githubusercontent.com/3136254/218364555-88798813-aef8-4cf0-bf0d-7c87b454cd6b.png)

### Expected Result

Chrome shows up a prompt to ask whether you want to save the credential 

### Actual Result

No prompt showing

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

109.0.5414.119 (x86_64)

### Build Version

2023.1.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @gui0506,

Thank you for reporting this. I've report that website for you via the dedicated form; You are more than welcome to submit further examples via the (Report failure of prompt to save credentials in browser) form here (https://github.com/bitwarden/clients/issues/new/choose) when it's related to the browser extension. By the way, more information about this can be found in this thread (https://github.com/bitwarden/clients/issues/1620).

I will close this thread now, and I thank you in advance for your understanding.

**Comment by gui0506** [comment]
Hi @SergeantConfused , is there a way that I can track the progress of my submitted issue?
