### ISSUE TITLE
Notes marked as "master password re-prompt" do not re-prompt in Firefox extension

### ISSUE THREAD

**Issue by fin444** [bitwarden/clients#4741]
### Steps To Reproduce

1. Have a note in your vault marked for password re-prompt
2. Attempt to open or copy the note in the extension

### Expected Result

Extension should re-prompt before showing/copying the note

### Actual Result

Extension allows access to the note without re-prompt

### Additional Context

I am using VaultWarden backend with the official BitWarden browser extension. I checked with VaultWarden and they said that it is not their fault, so I am moving the report here.

https://github.com/dani-garcia/vaultwarden/issues/3243

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

109.0.1-1

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment]
Hi fin444,

For extra context, this is currently how the feature is intended to work, however there are improvements being worked on for a future release that will place the entire Vault Item behind the Master Password re-prompt.

Cheers,
Jack
