### ISSUE TITLE
KDF iterations Help page- Error 404

### ISSUE THREAD

**Issue by nowasteaccount** [bitwarden/clients#4759]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/settings/security/security-keys
2. Click on Help Icon on KDF iterations
3. Redirects to non existent page.

![image](https://user-images.githubusercontent.com/121700012/218929249-8accbbe8-c079-4a58-a7a8-d1e72e9a9349.png)

### Expected Result

Help link https://bitwarden.com/help/kdf-algorithms should be created / updated.

### Actual Result

Non existent - Error 404 - https://bitwarden.com/help/kdf-algorithms

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/121700012/218929430-25fe71ba-e2b6-419c-83e1-2a53528d48b9.png)

### Operating System

Windows

### Web Browser

Chrome, Firefox, Brave

### Build Version

Version 2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

The team is aware of this, and reports that you've managed to catch the release at a stage where the supporting documentation hasn't yet been uploaded.  There is a plan to do so, and this will go live very soon.

Thanks once again!
