### ISSUE TITLE
Improve highlight contrast in search bar

### ISSUE THREAD

**Issue by lduperval** [bitwarden/clients#4769]
### Steps To Reproduce

1. Go to search
2. Enter anything
3. Highlight the search term 

### Expected Result

I should see what has been highlighted

### Actual Result

The text is highlighted but it doesn't appear like it. See the screenshot.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/73903942/219057598-3ab6e697-e7d5-4d30-aea5-e846a7a84699.png)

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @Iduperval, 

Could you let me know which Bitwarden client you're seeing this in?  Is this report regarding the desktop application?

**Comment by atjbramley** [comment]
Hi again @lduperval,

Thank you for your report! 

I was able to reproduce this issue in the Windows 10 Desktop App, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by patrickhlauke** [comment]
for the light theme, this applies to desktop and browser extension. I might have some time this weekend to propose a fix (also for the contrast of the non-selected solarised theme in the browser, which is horribly low)

### browser extension

Light
![light-theme-browser](https://user-images.githubusercontent.com/895831/219338553-522df4d4-c5ca-491d-a360-100f8f6550eb.png)

Dark
![dark-theme-browser](https://user-images.githubusercontent.com/895831/219338598-2d30beef-08a3-4366-b5fa-ab84ef538016.png)

Nord
![nord-theme-browser](https://user-images.githubusercontent.com/895831/219338638-5b499207-eb8a-4ba5-af49-694c380c49f1.png)

Solarised dark
![solarised-dark-theme-browser](https://user-images.githubusercontent.com/895831/219338664-6db5268c-bdc0-49ac-ab89-cba1d615d778.png)

### Desktop

Light
![light-theme-desktop](https://user-images.githubusercontent.com/895831/219338836-a8d3a9a1-6b52-464a-92fa-319ab2392472.png)

Dark
![dark-theme-desktop](https://user-images.githubusercontent.com/895831/219338883-f55de7b7-34ef-4e95-b22b-48c0c8153cd7.png)

Nord
![nord-theme-desktop](https://user-images.githubusercontent.com/895831/219338912-eeb654b5-1a84-4944-b4e1-c248a4b4f4f1.png)

**Comment by patrickhlauke** [comment]
also, mea culpa, as this is likely the result of https://github.com/bitwarden/clients/pull/3675

**Comment by lduperval** [comment]
Excellent, thanks for the feedback. I just noticed the email responses.

**Comment by patrickhlauke** [comment]
Proposed fix (and additional change to the dreadfully low solarized dark style) here https://github.com/bitwarden/clients/pull/4788
