### ISSUE TITLE
2FA codes are wrong on Chrome/Chromium Browser extension

### ISSUE THREAD

**Issue by ChillHorse** [bitwarden/clients#4796]
### Steps To Reproduce

1. look up account that has 2FA set up on browser extension
2. compare that code with one the mobile app shows 
3. try to use code of extension which will most likely fail
4. try code of mobile app, this one should give you access to your application

### Expected Result

The browser extension should provide a valid TOTP Code

### Actual Result

Extension is out of sync and has an invalid TOTP code. 

### Screenshots or Videos

I would provide a comparison screenshot with time stamp if the android application would paint the screenshot completly blank (Android 13)

### Additional Context

The entries that I used (Discord and Twitter) were quite old they they aren't too new that it could've been the cause of the extension providing a wrong code. 
I did sync the pcs time with windows time servers and tried again, it did not resolve the issue

### Operating System

Windows

### Operating System Version

Windows 10 22H2 (Build 19045.2364)

### Web Browser

Vivaldi

### Browser Version

5.7.2921.53 (Stable channel) (64-Bit) 

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@ChillHorse Please check the time and timezone on your Windows-machine

**Comment by ChillHorse** [comment]
as already mentioned in the issue I did synch it with windows time servers and tried again.
I had to logout of the extension to fix this issue
