### ISSUE TITLE
Cannot enable "Unlock with Windows Hello" when using Remote Desktop

### ISSUE THREAD

**Issue by jetwiwo** [bitwarden/clients#4811]
### Steps To Reproduce

1. Enable Windows Hello in Windows (e.g. set up a pin, register a key, record a face) on the client machine
2. Connect to the host machine using remote desktop, ensuring that Local Resources => "More..." => "Web Authn ("Windows Hello or Security Keys")" is checked when setting up Remote Desktop.
3. Install Bitwarden and login.
4. File => Settings
5. Look for "Unlock with Windows Hello" under the "Unlock with PIN" option. It's not there :(

### Expected Result

"Unlock with Windows Hello" option should be present.

### Actual Result

"Unlock with Windows Hello" option is not present.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/92765854/220314129-75026b95-0cde-4f20-8914-b761de25955f.png)
Screenshot of how to enable Windows Hello sharing on Remote Desktop

### Additional Context

Both the client and host machines are Windows 10 with the most recent updates installed. 

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @jetwiwo,

Unfortunately I'm unsure if Remote Desktop supports non Business Windows Hello. The WebAuthn option is not the same as Windows Hello for the desktop application.

I would be curious to know if enabling Windows Hello with PIN on the host machine might work? Something else to rule out would be to start Bitwarden after connecting with remote desktop in case it was already running. I believe we currently evaluate the criteria on launch.

**Comment by jetwiwo** [comment]
Hi there,

I can confirm that I've tried enabling Windows Hello with PIN on the host machine. This worked while I was logged into the machine physically (i.e. using the keyboard I temporarily attached to the workstation), but stopped working once I'd connected via Remote Desktop. It does appear correct that the option is detected on startup because the option *appeared* enabled when I used the existing BitWarden process on remote desktop but disappeared when I closed and re-opened it.

Remote desktop definitely supports non-business Windows Hello in some form or another because I'm able to use the Windows Hello PIN on my client machine as a 2FA option for the BitWarden web vault on the host machine. I've also been able to unlock the Dashlane browser extension using Windows Hello credentials from the host machine. I'm guessing this works because those tools use WebAuthn and the desktop application does something different.

I suppose this is no longer a bug report, but a feature request. Here's what I'd like to achieve:

1. I'd like to use a security key (or any other Windows Hello compatible credential) from my client machine to unlock the Edge extension on the host machine.
2. If possible, I'd like to do this without installing the desktop app as I will only be using it in the browser.

**Comment by Adedamola-Aina** [comment]
Hi there,
We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
