### ISSUE TITLE
Personal vault folders only viewable in "All Vaults" view as Owner of a Family plan

### ISSUE THREAD

**Issue by sawft99** [bitwarden/clients#4818]
### Steps To Reproduce

1. In my instance, I am the owner of a family plan/organization
2. Go to your web vault (I'm on Windows 11 in Vivaldi)
3. Select "All vaults" view and note all folders are visible whether from your organization or personal vault
4. Switch to your personal vault and you will see no folders
5. Switch to Organizations vault and see folders that are part of the organization
6. Note your personal folders are only viewable in the "All Vaults" view

### Expected Result

See folders displayed properly based on corresponding view

### Actual Result

No folders displayed in personal web vault

### Screenshots or Videos

![1](https://user-images.githubusercontent.com/81699231/220501894-93130197-6fcd-419e-97c1-fbcbf52a6989.png)
![2](https://user-images.githubusercontent.com/81699231/220501898-e00e1574-ed1d-4b44-9562-a0d4b5fffd07.png)
![3](https://user-images.githubusercontent.com/81699231/220501899-0198cc4c-9b1f-4c6f-b197-7028d97ca8ed.png)

### Operating System

Windows

### Operating System Version

11 - 10.0.22621.1265

### Web Browser

Vivaldi

### Browser Version

5.7.2921.53 (Stable channel) (64-bit)

### Build Version

2023.2.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
HI @sawft99,

Thank you for this report. This appears to be the same as (https://github.com/bitwarden/clients/issues/4805); If you have any information or screenshots you'd like to add, please feel free to do so in the other thread (https://github.com/bitwarden/clients/issues/4805).

I will close this thread now.

Thank you.
