### ISSUE TITLE
Bitwarden does not offer to fill credentials for non-HTTPS sites, or sites using an invalid/self-signed certificate

### ISSUE THREAD

**Issue by Ziginox** [bitwarden/clients#4831]
### Steps To Reproduce

1. Add a credential to Bitwarden from a website which is not HTTPS, or which is HTTPS but uses a self-signed certificate. Router configuration pages are a good example
2. Attempt to log into the site
3. Bitwarden does not autofill with the keyboard shortcut, nor does it offer any items in the list of Logins, despite the URL matching

### Expected Result

Saved logins should be offered for websites using https with self-signed certificate and http, at the very least with a toggle in each vault item to allow this per-item.

### Actual Result

Saved logins are not offered for http/self-signed https websites, and must be manually searched for in the vault

### Additional Context

This is happening for me with the Chrome and Firefox extensions, as well as the autofill service on Android 13 (also in Chrome.)
If I manually search for the login I need, open it, scroll down, and click Autofill, it will properly autofill credentials for the site.
If I hit "Auto-fill and save", it will fill and add a duplicate URL to the list. After doing this, the behavior above does not change.
On Android, when tapping the Bitwarden prompt, the search result states "Items for --" and "There are no items in your vault for --.", leading me to believe that Bitwarden is somehow not receiving the URL properly.

I can see that v2022.12.0 of the Browser extension does have "Fix for auto-filling credentials into pages served over http://" in its release notes, but it is unclear if this was supposed to resolve an issue preventing auto-fill from working, or introduced this 'feature' for security purposes. I am not certain when this started, but it does seem to be around this timeframe.

### Operating System

Windows, macOS, Android

### Operating System Version

Windows 10 21H2, Android 10 and 13

### Web Browser

Chrome, Firefox

### Browser Version

Chrome 110.0.5481.96, Firefox 110.0

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment]
Hi Ziginox,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the URIs in the Vault Item itself.  You can find full information on this here: https://bitwarden.com/help/uri-match-detection/

There's also an active feature request to change how autofill works in similar circumstances that might be related: https://community.bitwarden.com/t/add-the-ability-to-disable-unsecured-http-page-warning/47033

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Ziginox** [comment]
I have reached out to support via the contact URL provided. I forgot to mention in my original post that this is happening across 10+ vault items, though. I've made sure the URIs make sense. For instance:
http://router/cgi-bin/luci/ is the site, the URI is http://router/ with "Default match detection", this is how Bitwarden automatically added it.
Another is http://librenms/login, and the vault item has a URI of http://librenms
HOWEVER, I may have found the issue.
If I instead go to "http://librenms.lan/" and add that as a URI (either manually or automatically), it works. "lan" is, of course, the local domain of my home network.
If the URI is an IP address, and you go to the resource by IP instead of hostname, Bitwarden offers the logins as expected.
It seems that Bitwarden does not seem to match properly if a URI with only an SLD is provided. The match requires a TLD.
I can do further testing with my work's domain tomorrow, but from memory it seems like those with a TLD autofilled properly while those with only a hostname/SLD did not.

The above does not apply to the Android app, which still thinks the website is "--", but that maybe an Android limitation.

**Comment by trinity-geology-unstable** [comment]
I am also facing this same issue on Android.

I have Bitwarden installed on my phone running Android 13 (GrapheneOS) and I am not offered suggestions for auto-filling on http:// sites in Firefox (Fennec). The app says "There are no items in your vault for --." 

The issue occurs under these conditions:

- The site is on my LAN and starts with http:// (no certificate)
- The URI is in the format http://[hostname].localdomain/. 
- If the URI is an IP address then auto-fill can work as expected
- The URI is correctly entered into Bitwarden
- The password for the same site is found and correctly filled on desktop using the Firefox Add-on.

If I search for the entry on Android and ask it to autofill then it works. If I ask it to autofill and save then it creates a duplicate URI.

**Comment by Ziginox** [comment]
So, after poking around at work, I can confirm that Bitwarden will **only** match a URI if a TLD is provided. A hostname or SLD only will no longer match.

**Comment by sNiXx** [comment]
I just wanted to add to the discussion that the following worked for me: change how a match is detected (click on the gear icon of the URI to toggle the option) to "Host" or "Starts with". The "Default match detection" does no longer seem to work in the previously mentioned scenarios.
