### ISSUE TITLE
Extension does not recognize sites that do not have a TLD

### ISSUE THREAD

**Issue by mehrexe** [bitwarden/clients#4836]
### Steps To Reproduce

1. Have DNS resolve a site without a TLD (i.e. http://example), and have credentials saved for that site. Visit that site in the browser.
        i. There are various means of DNS overriding including setting rules in the upstream DNS server or host file entries.
2. Attempt to fill in the saved credentials, you should see that the list is empty. You may even save credentials after signing in, or find the credentials in the extension's vault access and hit "Autofill and Save" to save the domain for that login. It will autofill the login boxes, and if the domain that has no TLD is in the login's URIs list, it will not duplicate it. 

### Expected Result

A URI, whether it has a TLD or not, should have its logins shown in the extension's logins list when that site is visited and credentials exist for it in the vault. 

### Actual Result

When visiting any site with a saved credential, the extension's icon (when it is in an authenticated state) will indicate the number of logins for that site. Logins can have numerous URIs for the extension to recognize those credentials that also apply to different sites.

No matter how you slice it: whether the URI is added manually or through the "autofill and save" button-- the extension does not offer logins for sites with no TLD. There is no issue with saving the URI to the login. 

### Screenshots or Videos

![chrome_SXAytL2Y2A](https://user-images.githubusercontent.com/49566023/220890703-e36ab4aa-c1cf-4dff-9a23-fe7d2ed37922.png)

![chrome_sMHxHJ6elH](https://user-images.githubusercontent.com/49566023/220891034-0da64741-aa04-4985-9af8-8d8e775986fd.png)

![chrome_SqhuATQA5N](https://user-images.githubusercontent.com/49566023/220891068-6d098482-1eeb-4947-8937-48ce4fe73bc2.png)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

110.0.5481.104

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Could you please change your domain match settings in **settings -> autofill** from **base domain** to either **exact**, **host** or **regular expression**. This will now be recognised by the extension.

**Comment by mehrexe** [comment]
> Hello there,
> 
> Could you please change your domain match settings in **settings -> autofill** from **base domain** to either **exact**, **host** or **regular expression**. This will now be recognised by the extension.

That was it. Thank you so much.

**Comment by mehrexe** [comment]
> Hello there,
> 
> Could you please change your domain match settings in **settings -> autofill** from **base domain** to either **exact**, **host** or **regular expression**. This will now be recognised by the extension.

This was it, thank you so much.
