### ISSUE TITLE
Text overflow when too long password in the password generator

### ISSUE THREAD

**Issue by tomexx** [bitwarden/clients#4847]
### Steps To Reproduce

1. Go to CTRL + G
2. Click on Options
3. Set length to 70 characters or so
4. Set password type to Password

### Expected Result

Generated password is NOT overflown from modal window

### Actual Result

Generated password is overflown from modal window

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/2822756/221044760-35166caf-29e4-4ef2-8e36-73ba5f25883f.png)

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment]
Hi @tomexx and thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/4469 and has been fixed with #4480. The changes will be rolled out with the next release.

Closing this now.
