### ISSUE TITLE
MacOS client: Login Unavailable - can't login without turning off 2FA

### ISSUE THREAD

**Issue by neorrk** [bitwarden/clients#4856]
### Steps To Reproduce

I am trying to login to the MacOS client (tried both from App Store and Github), but after entering my email and password, it won't let me log in. Same thing when if approve login requests from the mobile app.

I use FIDO 2 keys as 2FA.

### Expected Result

It should let me login with my Yubikeys or with mobile app approval without having to disable them first.

### Actual Result

_Login unavailable_

_This account has two-step login set up,
however, none of the configured two-step
providers are supported by this device._

_Please add additional providers that are
better supported across devices (such as an
authenticator app)._

If I click _Use another two-step login method_ then it only has this option: 
_Recovery code_

_Lost access to all of your two-factor providers? Use your recovery code to turn
off all two-factor providers on your account._

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/58256328/221186250-49d5562c-7fc4-44c6-a3dc-c15da8a19f85.png)
![image](https://user-images.githubusercontent.com/58256328/221186297-f0e37b41-9950-442b-a1d0-af06a1b18ba2.png)

### Additional Context

I have Lockdown Mode enabled on MacOS. I was able to log in before switching to Argon2, not sure if that matters.

### Operating System

macOS

### Operating System Version

13.2.1

### Installation method

Mac App Store

### Build Version

Version 2023.2.0 (7249)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @neorrk,

Unfortunately we don't yet support WebAuthn as a 2FA method in the Desktop application on MacOS since it's not supported in Electron. We're tracking the issue but until it's available we are not able to provide support for this method.
