### ISSUE TITLE
Firefox extension asks to save password for already existing passwords

### ISSUE THREAD

**Issue by CubeRanch** [bitwarden/clients#4867]
### Steps To Reproduce

1. In the Firefox browser extension, log in or unlock your vault.
2. Go to Settings->Options->Ask to add login and enable by checking the checkbox.
3. Go to a website that has a corresponding login in your vault.
4. Open the extension and fill the login fields via Auto-fill.
5. Log in.

### Expected Result

Expect to be logged in and don't expect to be asked "Should Bitwarden remember this password for you?"
The login exists in my vault and this feature is described as "Ask to add an item if one isn't found in your vault".

### Actual Result

A bar across the top of the browser window pops up asking "Should Bitwarden remember this password for you? Never Save X".

### Additional Context

Problem began after updating to version 2023.2.1

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

110.0

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by CubeRanch** [comment]
Closing this issue. Removing and reinstalling the extension seems to have fixed this issue, as well as the missing badge counter. 
The extension had been updated to the latest version (2023.2.1) from within the Firefox Extensions page. Obviously, something went wrong.

**Comment by SergeantConfused** [comment]
Hi @CubeRanch,

Thank you for following up and updating this report; If you encounter this behaviour again, please feel free to get in touch (https://bitwarden.com/contact/) so we'd assist you with it.


All the best,
