### ISSUE TITLE
No line warp for password generation

### ISSUE THREAD

**Issue by hisel-sabermetrics** [bitwarden/clients#4870]
### Steps To Reproduce

1. Click on 'Add item'
2. Click on 'Generate password'
3. Click on 'OPTIONS' under 'Username'
4. Move the slider next to 'Length' to the right

### Expected Result

The generated password would warp to new line when there is not enough space

### Actual Result

The generated password extend outside the popup

### Screenshots or Videos

![Screenshot](https://user-images.githubusercontent.com/96913686/221381794-a9ead121-bd96-4da4-ba4b-4ae579954cae.png)

### Operating System

macOS

### Operating System Version

13.2.1 (22D68)

### Installation method

Mac App Store

### Build Version

2023.2.0 (7249)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @hisel-sabermetrics and thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/4469 and has been fixed with https://github.com/bitwarden/clients/pull/4480. The changes will be rolled out with the next release.

Closing this now.
