### ISSUE TITLE
copy send link incomplet after /

### ISSUE THREAD

**Issue by tomamplius** [bitwarden/clients#4888]
### Steps To Reproduce

open plugin 
go to send
copy link
Value is : https://p.lgy.fr/#/send/lBBb2j9MRzyXiME-fVESAg/

From other client ( desktop, web) value is : https://p.lgy.fr/#/send/lBBb2j9MRzyXiME-fVESAg/7X-X3eISAlZ3Yet_TZkMDQ

![image](https://user-images.githubusercontent.com/6951820/221853318-1628198d-3bfb-4def-a649-7ccea904bc6b.png)

### Expected Result

firefox plugin give same result as others clients ( desktop, web)

Value need to be https://p.lgy.fr/#/send/lBBb2j9MRzyXiME-fVESAg/7X-X3eISAlZ3Yet_TZkMDQ

### Actual Result

Value is : https://p.lgy.fr/#/send/lBBb2j9MRzyXiME-fVESAg/

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Web Browser

Firefox

### Browser Version

110.0

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @tomamplius ,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by wnelson03** [comment]
@atjbramley @djsmith85 any updates? still a problem on Firefox.

**Comment by huantrinh1802** [comment]
It seems there is a regression in Firefox, Safari and Chrome's extension for this issue. 
This is the https://send.bitwarden.com/#Jkpq3ksqDkqsNK_VABP1Ew/ in the clipboard after I copied.
The link generated by desktop is working. https://send.bitwarden.com/#Jkpq3ksqDkqsNK_VABP1Ew/4BBK5_3q25MuPWkq_Mrj8w

**Comment by kevinrode** [comment]
It looks like if you create a new Bitwarden Send via extension and mark "Copy this Send's link to clipboard upon save." during creation the link which is copied to the clipboard are working. The link is only broken if you using the copy icon button in the Send overview.
