### ISSUE TITLE
Safari Browser Extemsion show Error when trying to login to account

### ISSUE THREAD

**Issue by PaddyPad** [bitwarden/clients#4906]
### Steps To Reproduce

After the last Bitwarden Update, the Safari Browser Extension logged out of the account. When I try to log back in it shows an error not being able to log in. Loggin in with the Mac Desktop App, iOS App, and Android App is no problem.
![Bildschirm­foto 2023-03-02 um 10 43 25](https://user-images.githubusercontent.com/46504832/222391773-9953fb2e-476a-4eec-bdb0-29cb504fa204.jpg)

### Expected Result

Expected to login to account

### Actual Result

Browser Extension is not usable, since I can't access my vault.

### Operating System

macOS

### Operating System Version

MacOS Ventura 13.2

### Web Browser

Safari

### Browser Version

Version 16.3 (18614.4.6.1.5)

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ralfboernemeier** [comment]
I have the same problem as describe by @PaddyPad with the Mac OS App. See also https://github.com/bitwarden/clients/issues/4895

**Comment by PaddyPad** [comment]
Thank you, I’ll close this thread then, so it can be solved in the other thread.

**Comment by Adedamola-Aina** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

Could you reinstall the extension or try from another browser.

And If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/
