### ISSUE TITLE
Bitwarden Extension Conflict with Google Maps on Firefox Ubuntu 22

### ISSUE THREAD

**Issue by VinayakaHk** [bitwarden/clients#4907]
### Steps To Reproduce

Steps to reproduce:

* Install Bitwarden extension in Firefox Ubuntu 22
* Log in to Bitwarden and lock the extension
* Go to Google Maps and search for a place
* Click on directions and enter another place
* Try to type the destination address

Additional Information:
The bug occurs only when the Bitwarden extension is installed in Firefox Ubuntu 22 and is locked. When the Bitwarden extension is unlocked or disabled, the issue does not occur, and the user can enter the destination address without any problem.

Possible Cause:
It is possible that the Bitwarden extension is conflicting with Google Maps and preventing the user from entering the destination address. This could be due to some coding issues or a compatibility problem between the two extensions.

### Expected Result

The user should be able to enter the destination address in Google Maps and get directions.

### Actual Result

Upon trying to type the destination address in Google Maps, the text field becomes unresponsive, and Google Maps stop working. The user is unable to enter the destination address, and the application becomes unusable.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/32355181/222403953-fe0d89b4-0074-401f-b3df-e1c7ea3b1aca.png)
I can't type the destination address when Bitwarden is locked. But when it's unlocked, I can. 

### Operating System

Linux

### Operating System Version

Ubuntu 22

### Web Browser

Firefox

### Browser Version

110.0 (64 bit)

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

Could you perform a clean install of your browser and extension. 

And If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/
