### ISSUE TITLE
i18n layout redress

### ISSUE THREAD

**Issue by atx49559** [bitwarden/clients#4920]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Right layout, maybe let the width more larger.

### Actual Result

location zh-tw

![2023-03-03 14-22-30 的螢幕擷圖](https://user-images.githubusercontent.com/47237586/222648793-c1aee608-6136-49a9-aecb-6db1d2fe6320.png)

### Operating System

Windows

### Web Browser

Brave

### Build Version

2023.2.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by patrickhlauke** [comment]
Filed a fix #4932

**Comment by atx49559** [comment]
Thank you!
