### ISSUE TITLE
Regenerating a password multiple times makes the extension crash

### ISSUE THREAD

**Issue by FaviFake** [bitwarden/clients#4939]
### Steps To Reproduce

1. Open the browser extension
2. Go to the "Generator" section
3. Click the ![image](https://user-images.githubusercontent.com/86537048/223060637-ad39afc8-652c-429b-aaf9-0213e4076aaa.png) Regenerate icon multiple times
4. The extension crashes

### Expected Result

the extension shouldn't crash

### Actual Result

the extension crashes

### Screenshots or Videos

https://user-images.githubusercontent.com/86537048/223061217-1e2842e3-9d6f-4112-aeed-a04f251016cf.mp4

![image](https://user-images.githubusercontent.com/86537048/223061084-7665d75b-17f5-4d58-8bc4-cdba279bd314.png)

https://user-images.githubusercontent.com/86537048/223061223-b96c17d7-4396-44c6-8572-afd15f503a30.mp4

![image](https://user-images.githubusercontent.com/86537048/223061084-7665d75b-17f5-4d58-8bc4-cdba279bd314.png)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Version 113.0.5632.0

### Build Version

Version 2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @FaviFake, thank you for your report.

I was not able to reproduce this behavior. Could you please check if there are any errors occuring on the console (Developer Tools -> F12). If there are, please add that information here. This might help in narrowing down potential causes.

Kind regards,
Daniel

**Comment by SergeantConfused** [comment]
Hi @FaviFake,

Thank you for your report. I am unable to reproduce this on Chrome (110.0.5481.178); If you are able to reproduce this in the stable release of the browser, you're more than welcome to get in touch with us (https://bitwarden.com/contact/) and we'll troubleshoot this together; Please include a link to this GitHub report in your message.

We use GitHub issues as a place to track bugs and other development related issues; This report will now be closed.

Thank you all,

**Comment by FaviFake** [comment]
The problem seems to have been fixed by Chrome! I can't even reproduce it in Canary now :)
