### ISSUE TITLE
Cannot enable Unlock With biometrics feature with Firefox

### ISSUE THREAD

**Issue by peterbandi** [bitwarden/clients#4940]
### Steps To Reproduce

1. Go to: Bitwarden Desktop
2. Click on: File > Settings
3. Click on: APP SETTINGS > Allow browser integration
4. Click on: APP SETTINGS > Require verification for browser integration
5. Go to: Firefox
6. Click on: Bitwarden extension icon
7. Click on: Settings
8. Click on: Unlock with biometrics

### Expected Result

1. The Firefox browser extension should ask for  checking the fingerprint phrase.
2. The Bitwarden desktop application should ask for accepting the fingerprint phrase.
3. The _Unlock with biometrics_ should be enabled in the Firefox browser extension.

### Actual Result

I get the error message: _Browser integration is not set up_

### Screenshots or Videos

![screenshot](https://user-images.githubusercontent.com/16120716/223077169-85b70e7e-d31f-4c9e-b614-353c044e592e.jpg)

![permissions](https://user-images.githubusercontent.com/16120716/223080234-055bbd2d-4238-40ea-89b5-d611b27d94bb.jpg)

### Additional Context

Bitwarden desktop: 2023.2.0 (x64)

The exact same steps successfully enable the _Unlock with biometrics_ feature in the Edge browser on the same system.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2 22621.1265

### Web Browser

Firefox

### Browser Version

110.0.1 (64-bit) Microsoft Store version

### Build Version

2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @peterbandi,

Thank you for your report. I tested biometrics (Windows Hello) in Firefox (110.1) with Bitwarden extension (2023.2.1) and Bitwarden desktop (2023.2.0), and it's working as expected. I would recommend that you test this without (Require verification for browser integration) to see if that makes a difference; If not, please deactivate (Allow browser integration) hit (Close), reboot, open Bitwarden desktop and activate (Allow browser integration) anew and test this once more. If that does not help, please create a support ticket (https://bitwarden.com/contact/) and include a link to this GitHub report, and we'll assist you in troubleshooting this further.

Alternatively, you can seek assistance from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

We use GitHub issues as a place to track bugs and other development related issues; This report will be closed now.


Thank you.
