### ISSUE TITLE
Browser Addon Autofill, Items with "Re-prompt Master Password" fail silently

### ISSUE THREAD

**Issue by crespire** [bitwarden/clients#4942]
### Steps To Reproduce

1. Go to a site with credentials that require master password re-prompt
2. Attempt to autofill with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>L</kbd>

### Expected Result

Browser add-on should show a prompt to enter master password, or otherwise indicate to the user that additional action is required for autofill completion.

### Actual Result

Nothing happens at all.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 22H2

### Web Browser

Chrome, Firefox

### Browser Version

Chrome v110.0.5481.187 - Firefox v110.0.1

### Build Version

Extension v 2023.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by wuwendell** [comment]
Reproducible with Firefox on Windows 11 build 22H2, extension version 2023.2.1. Firefox version 111.0.1

**Comment by crespire** [comment]
Seems like it might be worthwhile to consider enabling this unless autofill is enabled. I understand  the point about autofill and opening a new tab right away being a jarring experience.

**Comment by djsmith85** [comment]
Closing this, as a fix was provided with https://github.com/bitwarden/clients/pull/5621 and released with 2023.8.2
