### ISSUE TITLE
Menu is not keyboard-accessible

### ISSUE THREAD

**Issue by sourcejedi** [bitwarden/clients#4966]
### Steps To Reproduce

Press Alt+F or F10

### Expected Result

Press Alt+F or F10

### Actual Result

The File menu should open (or at least be selected).

### Additional Context

I tested the Flatpak from Flathub, and the current AppImage download.

### Operating System

Linux

### Operating System Version

Fedora Workstation 37

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by patrickhlauke** [comment]
I suspect this is an upstream problem with Electron, though I may be wrong...

**Comment by Adedamola-Aina** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
