### ISSUE TITLE
snap - hangs when opening ADD ITEM -> Type dropdown (for Login, etc.) 

### ISSUE THREAD

**Issue by user706** [bitwarden/clients#4995]
### Steps To Reproduce

I'm using the linux snap, which I installed with `sudo snap install bitwarden`

1. I start it in shell (to see error output) with command `bitwarden` 
2. Login
3. Click My vault
4. Click +
5. under ADD ITEM-> I click the dropdown Type (top item shows Login)

Result: **the window hangs.**

Error message output in shell
```
[[23044:0314/112304.875580:ERROR:command_buffer_proxy_impl.cc(325)] GPU state invalid after WaitForGetOffsetInRange.
[22945:0314/112304.875737:ERROR:command_buffer_proxy_impl.cc(325)] GPU state invalid after WaitForGetOffsetInRange.
[22945:0314/112304.876816:ERROR:gpu_process_host.cc(975)] GPU process exited unexpectedly: exit_code=512
/usr/share/libdrm/amdgpu.ids: No such file or directory
[23208:0314/112304.998026:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[23208:0314/112304.999526:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[23208:0314/112305.003936:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
** Message: 11:23:05.096: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.463" (uid=1000 pid=22945 comm="/snap/bitwarden/83/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.29" (uid=1000 pid=2880 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")
```

Note: `/usr/share/libdrm/amdgpu.ids` does actually exist on my pc. It seems that the safety sandboxing mechanism of the snap is preventing the app from accessing it.

### Expected Result

no hanging

### Actual Result

it hangs

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

Snap

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @user706,

Thank you for your report. I am unable to reproduce this particular behaviour; It has been escalated for further investigation. If you have more information that can help us, please feel free to add it below. 

Thank you.

**Comment by NightStr** [comment]
Hi @SergeantConfused 

I have encountered a bug on a laptop with hybrid AMD/NVIDIA graphics. When running the application using the integrated AMD graphics, I encounter the following errors:

    [19897:1108/104434.093052:ERROR:command_buffer_proxy_impl.cc(325)] GPU state invalid after WaitForGetOffsetInRange.
    [19897:1108/104434.104467:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=512
    /usr/share/libdrm/amdgpu.ids: No such file or directory

However, when running the application on the discrete NVIDIA graphics card, everything works as expected.

Please let me know if you require any additional information to investigate and resolve this issue. Thank you.

**Comment by djsmith85** [comment]
Hi @user706 and @NightStr,

Would you be able to test and report back, if this behaviour is still occurring with the most recent version (2024.5). I'm asking as we have since bumped Electron, which Bitwarden uses to host the desktop application, and we added a fix to disable hardware acceleration on certain GPUs (https://github.com/bitwarden/clients/pull/8427). Hardware acceleration can also now be toggled via the menubar.

Kind regards,
Daniel
