### ISSUE TITLE
File attachments with the same name cannot be distiguished 

### ISSUE THREAD

**Issue by drollinger** [bitwarden/clients#4999]
### Steps To Reproduce

1. Create a new note
2. Upload an attachment to the note
3. Change the content of the file locally
4. Upload it again under the same name
5. Attempt to download both versions of the file from the desktop app (This was tested using the Mac desktop application)

### Expected Result

Both versions should download correctly their respective versions even though they have the same name

### Actual Result

The only file that downloads when attempting to download both is the first file that was uploaded, or the file that's first in the list

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
