### ISSUE TITLE
Exporting twice causes Bitwarden to crash (SIGTRAP)

### ISSUE THREAD

**Issue by sourcejedi** [bitwarden/clients#5008]
### Steps To Reproduce

* File -> Export.
* select json format, without encryption
* enter master password
* press enter
* save to a file

Then repeat the above steps a second time.
It will use a different filename, and it will now try to save somewhere under /var/run/user/1000/doc/
Don't change the directory or filename, just hit save...

### Expected Result

Create a second export file.

### Actual Result

Bitwarden crashes with SIGTRAP.

### Additional Context

Sadly, flatpak-coredumpctl was unable to decode a backtrace for me.

### Operating System

Linux

### Operating System Version

Fedora Workstation 37

### Installation method

Other

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sourcejedi** [comment]
Edited - I realized this is because it tries to save somewhere under /var/run/user/1000/doc/

Maybe that's where it saves temporary files, so it finds that it is trying to move the temporary file to the same pathname, and then it gets confused...

**Comment by joshtrichards** [comment]
Looks like you're running the Desktop client installed via an unofficial Flatpak build of BW from Flathub (which itself appears to be built based of taking the official BW Debian binary). 

This is a third-party build so support from BW directly may be a little hazy I'm guessing.

But to your issue: I think you're encountering an issue with the sandboxed (limited access) environment provided by the Flatpak.
From looking at the Flathub defined manifest[1] the only host directory the app might have access to is whatever your XDG_DOWNLOAD_DIR is set to (e.g. $HOME/Downloads). Even just using that folder I'm not entirely sure what else might be impacting by running the client in the sandboxed environment as defined by the Flathub manifest.

The `/var/run/user/1000/doc` is part of the internal filesystem structure created/provided by Flatpak. It's not something the BW client has any awareness of or control over.

You *may* be able to get things to work better using something like `flatpak run --filesystem=home com.bitwarden.desktop` but honestly that's a wild guess on my part (for the record: that command would give the BW Desktop client access to your home directory).

Have you tried the official Fedora RPM or even AppImage? https://bitwarden.com/download/

[1] https://github.com/flathub/com.bitwarden.desktop/blob/master/com.bitwarden.desktop.yaml

**Comment by sourcejedi** [comment]
Oops!  Thank you very much for your support.

It seems [Firefox' flatpak suffers a similar issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1775497#c27), possibly without the crash.

Of course I'd *like* BW to both adopt the flatpak, and work out why the crash happens on my computer. For free :-).

For now I guess BW will close this github issue.  At least you have provided a helpful answer for these search keywords.

**Comment by joshtrichards** [comment]
Too many package management / deployment solutions and too little time. :)

I suspect BW would happily accept a PR if you (or someone you know/can lean on) feels up to getting the ball rolling. ;)
