### ISSUE TITLE
[error: cannot decrypt] bug 

### ISSUE THREAD

**Issue by irshadelevision** [bitwarden/clients#5023]
### Steps To Reproduce

1. Add multiple bitwarden account to the desktop app
2. Close the bitwarden
3. Open one account
4. click on account icon and select the next account
5. then all the item in app will show [error: cannot decrypt].

### Expected Result

[error: cannot decrypt]

### Actual Result

different items list

### Screenshots or Videos

<img width="334" alt="Screenshot 2023-03-17 at 9 12 11 PM" src="https://user-images.githubusercontent.com/60963739/225952492-b67ee140-6d97-40f3-8892-58d50d0ce83e.png">
<img width="801" alt="Screenshot 2023-03-17 at 9 12 07 PM" src="https://user-images.githubusercontent.com/60963739/225952518-530d024c-eeab-4991-b0d2-04ddeccf4fce.png">

### Additional Context

When clicking the cannot decrypt item the value are showing. but on the list it is showing [error: cannot decrypt].
This is happening on Mac m1.

### Operating System

macOS

### Operating System Version

13.2.1

### Web Browser

Chrome

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by FadyFaheem** [comment]
I am also having the same issue with the same version of Bitwarden. Macbook Air M1, Ventura 13.2.1, on Desktop application for Bitwarden.

**Comment by Adedamola-Aina** [comment]
Hi there!

Thank you for your report, Could you log out then log back into your vault this should resolve the issue. 

If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

This issue will now be closed.

**Comment by FadyFaheem** [comment]
Hello Adedarmola, Yes, this does fix the issue, but it shouldn't have to be done for the application to work. It should work on the first switch.
