### ISSUE TITLE
Accessibility: low contrast for fingerprint phrase in device login

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/clients#5027]
### Steps To Reproduce

1. Trigger the "Log in with device" dialog

### Expected Result

Fingerprint phrase should have text contrast of at least 4.5:1

### Actual Result

Depending on theme, the fingerprint phrase is shown with a foreground/background colour combination that falls below 4.5:1

### Screenshots or Videos

The "Are you trying to log in?" dialog, with the purple/pink fingerprint phrase on dark blue/gray background, with a contrast ratio of 2.63:1

![device login dialog](https://user-images.githubusercontent.com/895831/226211688-21810a87-8dc4-46e7-aacb-f2ecdae8edb8.png)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! I have flagged this to our engineering team.

If you or anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by patrickhlauke** [comment]
Possibly worth looping in the design team /cc @danielleflinn
