### ISSUE TITLE
MacOS doc multiple instances

### ISSUE THREAD

**Issue by deepgray** [bitwarden/clients#5044]
### Steps To Reproduce

using bitwarden creates multiple icons in the dock

### Expected Result

only 1 instance should be seen

### Actual Result

multiple launch icons populate the dock

### Screenshots or Videos

![Screen Shot 2023-03-21 at 7 22 55 PM](https://user-images.githubusercontent.com/14880472/226763643-a4f04b91-4184-41fa-83fc-8f712ec3aa0a.png)

### Operating System

macOS

### Operating System Version

12.6.3

### Installation method

Mac App Store

### Build Version

2023.2.0 (7249)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by david-lev** [comment]
Same issue, any solution?
