### ISSUE TITLE
Error verifying the certificate with the CLI client

### ISSUE THREAD

**Issue by aseques** [bitwarden/clients#5073]
### Steps To Reproduce

I have a local bitwarden install with a certificate bought from GlobalSign nv-sa, the emitter is a certificate provider accepted  in all the major browsers.
I have no issues connecting with the standalone client or via web, but with the CLI i get a validation error.
I looked for the error but haven't found anything useful.
```
$ bw login 
? Email address: xxxx@xxx.com
? Master password: [hidden]
request to https://bw.xxx.com/identity/accounts/prelogin failed, reason: unable to verify the first certificate
```
I can provide any logs needed but I haven't been able to enable the debug.

### Expected Result

Successful connect to bitwarden

### Actual Result

The mentioned error

### Additional Context

Verified that the same issue is present on windows.

### Operating System

Linux

### Shell

Bash

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by keestux** [comment]
@aseques just to mention in case you didn't know. There is an environment variable `NODE_EXTRA_CA_CERTS` that you can set to point at a file with one or more CA certs. Perhaps you can try the follow. I'm guessing it will then succeed. If not, then something else is wrong.
```
NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt bw login
```

**Comment by aseques** [comment]
HI @keestux you're right, thanks. I just added the variable as you mention and bw client started working. I dug a bit more and it seems that alphassl haven't requested their root to be added into the mozilla CA list, so I opened a issue with them to see if it can be fixed.
Meanwhile I'm using the environment variable.

**Comment by almereyda** [comment]
For others arriving here trying to debug the Bitwarden CLI client in Flatpak, it may be necessary to inject the CA root certificate first via a portal, before the file can be used together with `NODE_EXTRA_CA_CERTS`, else the file might not be found. Use Flatseal to manage your Flatpak permissions.

This recently reappeared with

- https://github.com/flatpak/flatpak/issues/6033
- https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/issues/1905
