### ISSUE TITLE
no focus on password field on login page when pressing enter to continue

### ISSUE THREAD

**Issue by stefan0xC** [bitwarden/clients#5078]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com
3. Enter your email address
4. Press <kbd>Enter</kbd> to continue
5. Try to enter your password

### Expected Result

I can input the password for my account (and no error is displayed as I have not entered it yet).

### Actual Result

The error message " Input is required." is displayed for the password field and the field is not in focus.

### Screenshots or Videos

https://user-images.githubusercontent.com/509385/227751538-f0add5bd-b2aa-42d8-81cd-9935c608afcd.mp4

### Additional Context

I'm not sure what changed but this used to work in `web-v2023.2.0`. 

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Firefox

### Browser Version

111.0.1

### Build Version

Version 2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
I am closing this now, as this has been addressed with #5139. The changes will be included in the next release (2023.4)
