### ISSUE TITLE
Bitwarden does not detect logins on any site (Fedora 37/Opera)

### ISSUE THREAD

**Issue by kinekt4** [bitwarden/clients#5081]
### Steps To Reproduce

1. Use Opera Browser on Fedora
2. Login to Bitwarden
3. Open new tab
4. Go to any site with saved login
5. Look at toolbar notification. No login detected
6. Click on bitwarden toolbar icon. No login detected
7. Shortcut (Ctl+Shift+L) does not fill in login details

### Expected Result

When going to a site that I have a saved login:

1. The notification on the toolbar icon should indicate a number (eg. 1)
2. Clicking on toolbar icon should show the saved login
3. Pressing shortcut keys should autofill the login details

### Actual Result

No login details detected for any sites

### Additional Context

- I believe a browser update triggered this issue
- Firefox and Chrome with bitwarden instsalled on the same system does not exhibit this issue
- Browser restart did not resolve this issue
- Removing extension and re-adding to Opera browser did not resolve issue

**Edit**

- Works in pinned tabs! Does not work in normal tabs!  :laughing: 
- If you unpin the tab, it will continue to work
- So the **workaround** for the moment is to pin then unpin the tab

### Operating System

Linux

### Operating System Version

Fedora 37

### Web Browser

Opera

### Browser Version

97.0.4719.28

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @kinekt4,

Thank you for your report. I attempted to reproduce your issue and was unable to do so; I tested this in Fedora 37 with Opera 97.0.4719.28 (installed via DNF) and the Opera (not Chrome) Bitwarden extension version 2023.3.0 by opening multiple tabs in different browser windows, and the extension displayed the counter and matched the vault items as expected. I recommend that you create a support ticket (https://bitwarden.com/help/) so we'd troubleshoot this together (please include a link to this report in your message).

Alternatively, you can seek assistance from other Bitwarden users in our community forums (https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related issues; I will close this report for now.

Thank you again,
