### ISSUE TITLE
Edge Extension - Vault Times Out Despite Being Set to "Never"

### ISSUE THREAD

**Issue by altaiiiir** [bitwarden/clients#5084]
### Steps To Reproduce

1. Open Edge browser with Bitwarden logged in as usual
2. Exit Edge browser
3. Open Edge browser
4. Bitwarden now is randomly logged out

### Expected Result

I expect to never be logged out.

### Actual Result

I get logged out randomly. 

### Additional Context

I've noticed that this usually happens only when my Laptop/Desktop is in sleep (with edge closed)

This happens every now and then with Bitwarden, the browser, and my OS up to date. 
 
I use Bitwarden on both MacOS and Windows 11

I get a similar issue on both devices. 

This issue is also very similar to a previously resolved ticket "#2337"

### Operating System

Windows, macOS

### Operating System Version

Windows 11 Pro Version 22H2, and macOS Ventura 13.2.1

### Web Browser

Microsoft Edge

### Browser Version

Version 111.0.1661.5

### Build Version

Version: 2023.2.0  Server version: 2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @altaiiiir,

1. When you "get logged out randomly.", are you asked to enter your email address, master password, and 2FA (if present) anew in order to log back in?
2. What is your Vault Timeout Action set to within that extension?

Thank you in advance,

**Comment by trmartin4** [comment]
Hello @altaiiiir,

Could you please let us know if you are still seeing this issue?  If you are not, or we don't hear back in 14 days, we plan to close the ticket.

Thank you!

**Comment by altaiiiir** [comment]
Hey, thanks for the follow-up. It hasn't happened for a while but since then, I've gotten a new Macbook using the M1 Max chip. I installed Edge on it as well and I'm still occasionally getting logged out.

To answer your previous questions:

1. When you "get logged out randomly.", are you asked to enter your email address, master password, and 2FA (if present) anew in order to log back in?

Yes, it asks me to enter my email, and then master password, but I use "log in using device" instead. Then it asks for 2FA.

2. What is your Vault Timeout Action set to within that extension? 

"Never"

**Comment by trmartin4** [comment]
@altaiiiir I believe that you may actually be experiencing https://github.com/bitwarden/clients/issues/8873, which we have determined does affect other extensions as well (albeit less consistently).

The fix for this will be released on all extensions in the next release, which will be this week.

**Comment by trmartin4** [comment]
We believe this issue has been resolved with updates that resolved #8873.  Please feel free to re-open if you continue to experience this issue.
