### ISSUE TITLE
Empty black window on startup

### ISSUE THREAD

**Issue by KyleStay** [bitwarden/clients#5103]
### Steps To Reproduce

Launch Bitwarden on Windows V20H2

Notice window is black:
![image](https://user-images.githubusercontent.com/4483057/228371728-7525b80c-0b7b-44a8-b87b-3d4abff3beb5.png)

This can to recreated by quitting and launching Bitwarden again.

### Expected Result

I would expect to see the login window on startup, not a black window.

What I expect:
![image](https://user-images.githubusercontent.com/4483057/228372795-b917d0e6-460e-4991-8aec-76b859d50fdc.png)

Currently I have to close the window that was opened on launch, then select the Bitwarden app from the notification area.

### Actual Result

What I actually see on launch:
![image](https://user-images.githubusercontent.com/4483057/228372052-4e074761-ec3e-4cd0-a8da-90daaa8dbd09.png)

### Screenshots or Videos

What I am currently seeing on launch:
![image](https://user-images.githubusercontent.com/4483057/228372107-b44f7bcf-94a0-4bc5-a26f-7f99ba3f4e75.png)

What I expect:
![image](https://user-images.githubusercontent.com/4483057/228372831-513fe2ca-4c66-498b-a600-2dba6b50dfb3.png)

### Operating System

Windows

### Operating System Version

20H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshtrichards** [comment]
That's a fairly old rev of Windows. :-)

There's a chance some useful error output is provided by the app if you can try starting the desktop app from the command line:

1. Open a Command Prompt (*non*-admin)
2. Change directory to `C:\Users\[username]\AppData\Local\Programs\Bitwarden`
3. Run the Desktop app from there: `.\Bitwarden.exe` 

(make sure you've fully closed the existing app instance from your notification tray before doing the above).

Did this recently start after an update/upgrade or is this the first usage of the desktop app on this device?

Breadcrumbs: 

* Possibly related: #2931
* Also old (and theoretically resolved) but possibly related: #2661
