### ISSUE TITLE
Chrome extension does not autofill username on redhat.com

### ISSUE THREAD

**Issue by jdloft** [bitwarden/clients#5109]
### Steps To Reproduce

1. Go to [Red Hat SSO](https://sso.redhat.com/) (or click Log in on any redhat.com page)
2. Hit Ctrl+Shift+L to attempt autofill and observe no autofill
3. Paste in username and hit enter to go to password prompt
4. Hit Ctrl+Shift+L again and observe that the password is autofilled

### Expected Result

Autofill on username

### Actual Result

Only password field on next step is autofilled

### Additional Context

Username field has `x-autocompletetype="username"` set and password field has `x-autocompletetype="current-password"` set.

### Operating System

Windows, macOS, Linux

### Operating System Version

Windows 10, Fedora 38, macOS 13.3

### Web Browser

Chrome

### Browser Version

111.0.5563.111 (Windows)

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

I was able to replicate this. Could you please provide the details of the site on within this issue #1621 as that is where we track sites that do not autofill.

**Comment by edmundlaugasson** [comment]
Still issue persist on Chromium 123.0.6312.46 (64--bit) on EndeavourOS (Linux). No fields are filled at RH SSO page even I can choose and click on proper entry either in field or extension at top right (where other extension icons are).
