### ISSUE TITLE
The "Settings" > "Options" page's section headers cannot be translated

### ISSUE THREAD

**Issue by olavinto** [bitwarden/clients#5110]
### Steps To Reproduce

Open the extension's "Settings" and then "Options". Note "General" and "Display" sections of the screenshot (they are collapsed).

### Expected Result

The collapsible headers ("General" and "Display") should be available for translation at Crowdin. :)

### Actual Result

The collapsible headers ("General" and "Display") are not available for translation at Crowdin. :)

### Screenshots or Videos

![extension_settings-options](https://user-images.githubusercontent.com/23163218/228664240-691f5591-9c17-44e0-93f0-97bb36f52c7b.png)

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Abhinav-Saxena-dev** [comment]
I'd like to work on this issue

**Comment by djsmith85** [comment]
@Abhinav-Saxena-dev Thank you for your offering your help to fix this.

As a starting guide please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/). These will get you started with setting up your development environment and how to proceed with your contribution.

Please reference this issue when you create a pull request.
