### ISSUE TITLE
Multiple instances appear in MacOS dock

### ISSUE THREAD

**Issue by cpaltenghe** [bitwarden/clients#5119]
### Steps To Reproduce

Just open a chrome browser and perform more than one activity that requires bitwarden

### Expected Result

Multiple instances of bitwarden appear in the dock.  Each new activity still requires bitwarden to authenticate the password.

### Actual Result

Opening either a DuckDuckGo or Chrome browser and using Bitwarden creates multiple instances in the MacOS dock.

### Screenshots or Videos

![Screenshot 2023-03-30 at 10 09 53 AM](https://user-images.githubusercontent.com/39197686/228912901-b36f97c8-3046-42e9-b812-e08e402cb760.png)

### Operating System

macOS

### Operating System Version

Ventura 13.3

### Installation method

Mac App Store

### Build Version

2023.2.0 (7249)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Moe-Hassan-123** [comment]
me too on a brand new Macbook M3, Sonoma 14.4.1 (23E224)

**Comment by mrlinuxfish** [comment]
I have the same issue using arc browser and running desktop client for biometric authentication

Version 2024.4.1
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture arm64

MacOS: 14.5
