### ISSUE TITLE
bitwarden drops passwords

### ISSUE THREAD

**Issue by PavelNiedoba** [bitwarden/clients#5141]
### Steps To Reproduce

1. Go to browser extension
2. Click on
3.  + "+" to add login
4.  + click generate password
5.  + click copy
6.  + paste your passwod (or just click outside extension)
7. your password is lost now

are you aware of:https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470/139

after 4 years it renders bitwarden product manager incompetent

### Expected Result

save and sync every password bitwarden generate before it can be used

### Actual Result

bitwarden UX is actively pushing users to make irreciverable mistakes

### Additional Context

its very old issue

### Operating System

Linux

### Operating System Version

ubuntu 22.10

### Web Browser

Firefox

### Browser Version

111.0 (64-bit)

### Build Version

111.0 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @PavelNiedoba,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request; Please feel free to continue this discussion in the thread that you linked in your report, and please note this comment (https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470/130).

We use GitHub issues as a place to track bugs and other development related issues; This issue will now be closed. 

Thank you,

**Comment by PavelNiedoba** [comment]
I can only help those who want to be helped.
