### ISSUE TITLE
Editing an item can't get saved

### ISSUE THREAD

**Issue by p1nkyy** [bitwarden/clients#5156]
### Steps To Reproduce

1. Go to 'My Vault'
2. Click any credential saved
3. Edit something, be it username or password
4. Click save.

### Expected Result

New edit to the credential should be saved.

### Actual Result

Error message saying it can't be saved due to traffic from my network looks unusual.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7593831/229780717-afa9580b-4d62-4a77-b0db-30ce6bb012cd.png)

### Additional Context

I have a userscript to resolve reCAPTCHA automatically installed in my FF browser.
https://greasyfork.org/en/scripts/439683-all-popups-blocker-and-recaptcha-solver

### Operating System

Windows

### Operating System Version

Win 10

### Web Browser

Firefox

### Browser Version

111.0.1

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello,

We use GitHub issues as a place to track bugs and other development related issues. Please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/
