### ISSUE TITLE
This extension reloaded itself too frequently

### ISSUE THREAD

**Issue by mderazon** [bitwarden/clients#5165]
### Steps To Reproduce

Not sure

### Expected Result

Extension to work

### Actual Result

Extension is disabled

### Screenshots or Videos

Error message:
```
This extension reloaded itself too frequently.
```
![image](https://user-images.githubusercontent.com/717076/230108029-d99e2bc7-b789-4431-ada5-7c63806716f2.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

Version 111.0.1661.62 (Official build) (64-bit)

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mderazon** [comment]
https://stackoverflow.com/questions/29086691/chrome-this-extension-loaded-itself-too-frequently

> You've called [chrome.runtime.reload](https://developer.chrome.com/extensions/runtime#method-reload) too often.

> Chrome considers a reload a "fast reload" when you call chrome.runtime.reload within ten seconds after loading the extension. When your extension triggers more than five "fast reloads", then the following warning will be shown in the UI:

> This extension reloaded itself too frequently.

**Comment by mderazon** [comment]
I am seeing what happens now in real time.
The extension reloads itself - Becomes grey / disabled and then enabled again (and locked) and then the cycle happens again and again.

If It try to click on the extension icon to unlock it, it opens and sometimes as I enter my master password, the cycle happens again.

It is not consistent

**Comment by mderazon** [comment]
@atjbramley I am able to reproduce it now, and also took a screencast.

Steps to reproduce
1. Unlock extension
2. Add a new item
3. Save it
4. Extension will begin the restart cycle

This is serious as it renders the extension unable to save new items.

https://user-images.githubusercontent.com/717076/230576064-0f8b098a-e457-49bb-b828-6d0d82c56444.mp4

**Comment by atjbramley** [comment]
Thanks - the engineering team is aware of this issue, and investigating this internally.

In the meantime, you may wish to try reinstalling the extension.

**Comment by mderazon** [comment]
After reinstalling, problem seems to be fixed

**Comment by kakun45** [comment]
hi! This happens right now on Mac iOS 10

**Comment by rvjagadheesh** [comment]
Still happening

Windows 11
Brave Browser - [Version 1.59.120 Chromium: 118.0.5993.88 (Official Build) (64-bit)]

![image](https://github.com/bitwarden/clients/assets/13398920/190cbe1c-f174-42ef-89eb-7f8b94641207)

**Comment by LegoChicken** [comment]
Still happening:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2023-‎07-‎19
OS build	22621.3737
Experience	Windows Feature Experience Pack 1000.22700.1009.0

Microsoft Edge
Version 126.0.2592.102 (Official build) (64-bit)
![image](https://github.com/user-attachments/assets/fa20db1b-8e9f-415b-8d72-0dcb721f8638)
