### ISSUE TITLE
Extension: "Copy Send Link" Button Gives Out Incomplete Link

### ISSUE THREAD

**Issue by H3arn** [bitwarden/clients#5168]
### Steps To Reproduce

1. Add a send in my bitwarden account. 
2. Open my bitwarden extension in my browser, go to "Send", find the send and click on "Copy Send Link". 

### Expected Result

The link copied should be something like `https://<bitwarden_host>/#/send/<send_id>/<send_token>`

### Actual Result

But it turns out to be `https://<bitwarden_host>/#/send/<send_id>/`, the token is missing. 

When trying to access the incomplete link, I will be redirected to the homepage of bitwarden. 

### Additional Context

The type of send doesn't matter. Both "file" and "text" have the problem. 
But the checkbox of "Copy the Send's link upon save" works properly. 
Didn't get any warning or error message on my server log. 

### Operating System

Windows, Linux

### Operating System Version

Windows 10 / Arch Linux

### Web Browser

Firefox, Vivaldi

### Browser Version

Firefox 111.0.1 / Vivaldi 5.7.2921.65

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @H3arn,

this has previously been reported with https://github.com/bitwarden/clients/issues/4888 and was fixed with https://github.com/bitwarden/clients/pull/5062.
 With release 2023.3.1, which is currently being rolled out, this will be fixed.

Closing this as duplicate.
