### ISSUE TITLE
Desktop - Winx64 - Windows Hello endless auth loop

### ISSUE THREAD

**Issue by iLLHunter** [bitwarden/clients#5180]
### Steps To Reproduce

1. Open Desktop App. Windows Hello initiates
2. Click Cancel on the Windows Hello
3. Desktop app reinitiates Window Hello

### Expected Result

After clicking cancel on Windows Hello, the app should remain open, but locked.
I used to be able to open the application but leave it locked, by clicking cancel when Windows Hello wanted my fingerprint.

### Actual Result

Windows Hello just keeps popping up, endlessly 

### Screenshots or Videos

![Screenshot 2023-04-07 102745](https://user-images.githubusercontent.com/7083042/230626143-82611eb6-3dc7-4436-878d-925eee962f83.png)

### Additional Context

Version 2023.3.2
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by iLLHunter** [comment]
Still occurring in 2023.4.0

Version 2023.4.0
Shell 21.3.1
Renderer 106.0.5249.181
Node 16.16.0
Architecture x64

**Comment by iLLHunter** [comment]
oops not closed

**Comment by janot928** [comment]
I've had the exact same problem. You need to set a pin in in bitwarden in order to have windows hello working.

This need to be better explained to the user

**Comment by jakkalas** [comment]
This is still an issue on version 2023.5.1

**Comment by iLLHunter** [comment]
> 

This is for fingerprint authentication via Windows Hello. PIN is weak.

Issue still occurring, months and versions later.

**Comment by G0ku737** [comment]
Fingerprint loop still happening for me.

Version 2023.7.1
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

**Comment by Eji4h** [comment]
> I've had the exact same problem. You need to set a pin in in bitwarden in order to have windows hello working.
> 
> This need to be better explained to the user

Thank for workaround solution.

**Comment by iLLHunter** [comment]
> > I've had the exact same problem. You need to set a pin in in bitwarden in order to have windows hello working.
> > This need to be better explained to the user
> 
> Thank for workaround solution.

It's not a workaround or solution. It lowers your security, because Bitwarden made a change in code and has not reverted to the working code.
I'm going to keep pushing for a solution from bitwarden.

**Comment by ThaDaVos** [comment]
I am having the same issue - I can't even enable the Windows Hello part as the application goes into a infinite loop, every time the Windows Hello prompt says "Something went wrong" - it seems Bitwarden isn't able to finish up the Auth?

Version 2023.8.2
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

**Comment by djsmith85** [comment]
This was addressed with https://github.com/bitwarden/clients/pull/7350 and the changes are included in `2024.2.0`-release.

Closing this now.
