### ISSUE TITLE
[Bug][Firefox] Using the auto-fill shortcut when the extension is logged out opens the login window in a new container tab

### ISSUE THREAD

**Issue by MahdiNazemi** [bitwarden/clients#5184]
### Steps To Reproduce

1. Log out of the Bitwarden add-on for Firefox.
2. Navigate to a website where Bitwarden has an entry for.
3. Press the shortcut for auto-fill

### Expected Result

Like almost all other extensions, Bitwarden is expected to open the login page in a "No Container" tab. This allows the logged-in vault to be accessible across containers.

I understand some may prefer to log in to different vaults based on the containers (and I have seen a few feature requests about this), but I do not think this should be the default behavior, at least from a UX perspective.

### Actual Result

Bitwarden opens the login window in a container, which makes the vault inaccessible to the other containers.

### Screenshots or Videos

<img width="1440" alt="Login Page" src="https://user-images.githubusercontent.com/11276349/230755273-30db8380-a5a5-4a89-93e3-47b13975d622.png">

### Operating System

macOS

### Operating System Version

13.3.1

### Web Browser

Firefox

### Browser Version

111.0.1

### Build Version

2023.3.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for your report. I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,

**Comment by IetIesAai** [comment]
same issue when you aren't logged out but the vault is locked. If the vault is locked, and I enter the shortcut for filling in a password, it opens a seperate tab, and after authenticating in that tab, the vault is indeed still locked on the originating tab/container and all others. 

Workaround is putting the bitwarden icon in the bar, and clicking and unlocking it from there. This does seem to unlock the vault in all other containers/tabs as well. 
![image](https://user-images.githubusercontent.com/31566631/232101791-d9051936-0203-4523-8199-11eadea0c1c2.png)

**Comment by MahdiNazemi** [comment]
@IetIesAai, you can also define a shortcut for "Open vault in sidebar" or "Open vault popup" if you prefer to use your keyboard for logging in to or unlocking your vault.

**Comment by aamirazad** [comment]
I can confirm this issue is present on both windows and linux for me. This seems to cause #5115. Pull request #5116 would close both of these issues but it is still a work in progress.
