### ISSUE TITLE
"Bitwarden - Free Password Manager is slowing down Firefox. To speed up your browser, stop that extension

### ISSUE THREAD

**Issue by anastrophe** [bitwarden/clients#5188]
### Steps To Reproduce

1. Go to https://en.wikipedia.org
2. Visit an article with a very long history of edits, e.g. "Kitchen". Open the edit history.
3. Scroll down the edit history page at a fast clip. Display of edits stops and you scroll through blank space for a while.
4. Wait a few moments, and the following will pop up briefly:
<img width="655" alt="2023-04-09 15_40_48-NVIDIA GeForce Overlay DT" src="https://user-images.githubusercontent.com/1012545/230799930-fbc92cbe-5965-4656-adbb-35c0f65498d3.png">

### Expected Result

Page history should not stop displaying. Should not receive warning that Bitwarden extension is slowing down Firefox.

### Actual Result

As above under steps to reproduce.

### Additional Context

This only began a short while ago, at least, I only experienced it recently. But that may simply be due to not having viewed edit history of a wikipedia page that is extensive.

Have never seen any warnings about bitwarden extension slowing down FF ever in the past.

### Operating System

Windows

### Operating System Version

Win 10 Pro 22H2 OS build 19045.2788

### Web Browser

Firefox

### Browser Version

111.01  64 bit

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Tipoff4317** [comment]
Maybe related to https://github.com/bitwarden/clients/issues/5107 which has supposedly been address in 2023.3.1.

**Comment by anastrophe** [comment]
Ah, thank  you kindly. It's not a huge deal, just seemed to crop up recently - and the other thread does resemble it.  I'll wait for the extension to auto update.

**Comment by atjbramley** [comment]
Hi @anastrophe, 

Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/5107.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

Thanks!
