### ISSUE TITLE
CLI always defaults to unecrypted json

### ISSUE THREAD

**Issue by ajorgensen** [bitwarden/clients#5194]
### Steps To Reproduce

1. `bw export --output /tmp/test --format asdfasgas; cat /tmp/test`
2. See there is no error from the cli and the output is unencrypted

### Expected Result

I expect the CLI to return an error saying that the format is invalid. Always defaulting to an unencrypted json blob seems like it could have some consequences. For example, this came up when I put in `--format json_encrypted` rather than `--format encrypted_json`. I was surprised when I opened the json blob to see my data unecrypted.

### Actual Result

CLI always defaults to raw unecrypted json even if the format provided is giberish.

### Operating System

macOS

### Shell

Zsh

### Build Version

2023.3.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team. We have also noted the PR you have submitted.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by ajorgensen** [comment]
No worries at all. Please feel free to reach out if you need any more information or have any alterations you'd like me to make to the PR.
