### ISSUE TITLE
CLI error: incompatible architecture

### ISSUE THREAD

**Issue by twio142** [bitwarden/clients#5208]
### Steps To Reproduce

Enter `bw ...` (anything) in terminal.

### Expected Result

Properly functioning.

### Actual Result

```
node:internal/modules/cjs/loader:1196
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/opt/homebrew/Cellar/bitwarden-cli/2023.3.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node, 0x0001): tried: '/opt/homebrew/Cellar/bitwarden-cli/2023.3.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/bitwarden-cli/2023.3.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (no such file), '/opt/homebrew/Cellar/bitwarden-cli/2023.3.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
    at Module._extensions..node (node:internal/modules/cjs/loader:1196:18)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2023.3.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.4.0
```

### Additional Context

bitwarden-cli was installed with Homebrew.

### Operating System

macOS

### Operating System Version

macOS Ventura 13.1

### Shell

Zsh

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by DieterHolvoet** [comment]
I'm having the same issue. My guess is that this only happens on modern macos devices using a M1 chip. See [this thread](https://stackoverflow.com/questions/71882029/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64-i).

**Comment by twio142** [comment]
@DieterHolvoet  I solved the problem by manually switching to node.js 19 installed by Homebrew. By default my terminal uses node.js 18 managed by nvm.

**Comment by DieterHolvoet** [comment]
You're right, that fixes it! My workaround is adding the following to `.zshrc` (or `.bashrc` if you're using a bash terminal):
```
alias bw='fnm exec --using 19 bw'
```
or
```
alias bw='nvm exec 19 bw'
```
