### ISSUE TITLE
Edge/Chrome Bitwarden Extension  error "Cannot read properties of null (reading 'iterations')

### ISSUE THREAD

**Issue by im2c0ol** [bitwarden/clients#5210]
### Issue
**An error has occurred**
Cannot read properties of null (reading 'iterations')

Docker Self-Hosted Environment
Image: bitwardenrs/server:latest
Version 2.25.1

The Extention login on any new Windows devices doesn't work for the last 3 weeks.
Login into the vault through the web works fine.

1. On the existing computer where Extension works, continues to work, but once I sign out of the extension I get the same error.
2. On the Chrome browser that I've not used for months, I was able to log in, but when I manually sync, I get "Syncing failed", log out, and log in again getting the **An error has occurred** Cannot read properties of null (reading 'iterations')

### Things I've tried:
Deleting the extension from Edge/Chrome, clearing all browser history and caches.
Deploy new Bitwarden docker on a brand new Ubuntu 22.04.2 LTS and imported the backup.
Deploy new Bitwarden docker on the new Ubuntu server, without importing data from the backup.

### Expected Result

It had been working fine behind NGINX Proxy Manager 3 weeks ago, now I'm using Caddy for SSL with the same result.

### Actual Result

**An error has occurred**
Cannot read properties of null (reading 'iterations')

### Screenshots or Videos

Chrome logged in, and manually Syncing Failed.
![NS6ByQeHkQ](https://user-images.githubusercontent.com/21378169/231934990-6d5e91ab-82c0-49ab-bb12-c6482867f273.png)
MS Edge/Chrome Extension login error
![sV2CwfESdj](https://user-images.githubusercontent.com/21378169/231935053-5c6e5418-6bf8-4e15-ac23-2d7bc4235dfd.png)

### Operating System

Windows

### Operating System Version

Windows 11 Enterprise 21H2, Windows 10 Enterprise 21H2

### Web Browser

Chrome, Microsoft Edge

### Browser Version

Chrome Version 111.0.5563.149 (Official Build) (64-bit), Edge Version 112.0.1722.39 (Official build) (64-bit)

### Build Version

Edge/Chrome 2023.3.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by im2c0ol** [comment]
Ahh, I didn't notice till you pointed that out. Seems like I used vault warden for quite some time, but not sure why the browser extension stopped working. Now am trying to follow the Linux install guide for Bitwarden, I don't see any option to install without using nginx, as i've migrated to Caddy a few days ago to handle my proxy. With all these containers, I wished they packed them in a stack to be more organized when viewing it in portainer.

**Comment by ssinseeme** [comment]
where you able to find a solution, I wonder why no one else is commenting about this problem. i loged out and now i have the same error.
So how do we get bitwarden on the extension working?
