### ISSUE TITLE
`mac failed.` in `StdErr` while `StdOut` returns proper (but erroneous) output.

### ISSUE THREAD

**Issue by anonymous1184** [bitwarden/clients#5224]
### Steps To Reproduce

1. Login to CLI.
    - Via API or credentials.
2. Set `BW_SESSION`.
3. Issue `bw status`.

### Expected Result

**Unlocked**, from `StdOut`:
```json
{"serverUrl":null,"lastSync":"************************","userEmail":"username@example.com","userId":"************************************","status":"unlocked"}
```
With exit code `0`.

### Actual Result

**Locked**, from `StdOut`:
```json
{"serverUrl":null,"lastSync":"************************","userEmail":"username@example.com","userId":"************************************","status":"locked"}
```
And this from `StdErr`:
```
mac failed.
```
With exit code `0`.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/53758552/232287796-d9f91f2d-74e3-4c49-a9e7-c825d7220743.png)

### Additional Context

Weird thing is that happens pretty randomly. Happens in cmd.exe, (git) bash and PowerShell 5.x/7.x, however I have failed to consistently replicate.

If there is an error, nothing should be in the standard output and the exit code should not be zero.

Or have the output in JSON format with a property indicating that there was an error.

Related #3674

### Operating System

Windows

### Operating System Version

Windows 10 and 11 22H2 (both with latest updates)

### Shell

PowerShell

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

Myself and others attempted to reproduce your issue and were unable to do so. Please log out of the CLI, restart your device, and then log in again and save your session key. You mentioned logging in with the API or credentials, which one specifically are you using?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by anonymous1184** [comment]
> Myself and others attempted to reproduce your issue and were unable to do so

Like I've said, is a non-deterministic thing... I've seen it happen after login in the first unlock and then after the nth unlock.

> restart your device

Not necessary, only by either logging out or deleting `data.json` is enough. After that, a new session key is generated and the problem disappears.

> logging in with the API or credentials, which one specifically are you using?

- Personal API key, in the form of `user.GUID` where `GUID` is my `userId`.
    - The `organization.GUID` is for other purposes.
- Credentials:
    - Without 2fa.
    - Email codes.
    - TOTP code.

---

Another thing I've noticed was that a folder was present, name:

```
undefined\temp\pkg\1dbbe4e44bfbaba29d903bec169002fee25a1f93dff9be292153b745014f3c53\argon2
```

The contents are a npm package (`node-argon2` v0.30.3). I noticed the folder after receiving this error, I don't know if that was actually what added the folder:

```
C:\snapshot\clients\apps\cli\build\bw.js:32966
                return Response.error("Syncing failed: " + e.toString());
                                                             ^
TypeError: Cannot read properties of null (reading 'toString')
    at SyncCommand.<anonymous> (C:\snapshot\clients\apps\cli\build\bw.js:32966:62)
    at Generator.throw (<anonymous>)
    at rejected (C:\snapshot\clients\apps\cli\build\bw.js:32941:65)
```

None of the accounts where I'm doing testing uses Argon2 as key derivation, all of them are still under PBKDF2.

> The issue here will be closed.

Why? This is clearly a *development issue*. There's nothing on the docs or the community about this behavior, yet there is another similar report (`#3674`). Looks like a problem with node/JavaScript and this is the best place for code-related issues.

Hopefully you reconsider forwarding this to the devs rather than closing it.

Thanks.
