### ISSUE TITLE
Captcha in Chrome extension not loading

### ISSUE THREAD

**Issue by rowankinney** [bitwarden/clients#5228]
### Steps To Reproduce

1. open chrome with bitwarden extension installed
2. sign in with remeber email selected (remember email might not be important, but so far has been selected)
3. click enter password
4. captcha shows not loaded sign, not able to sign in

### Expected Result

Normally would just sign in, captcha would load, and it would open the vault to enable autofill in the browser.

### Actual Result

Not allowing sign-in, therefore preventing autofill in chrome. I am trying to set bitwarden up for my partner who has so far been resistant to password managers, currently needing to coopy from the desktop vault.

### Screenshots or Videos

<img width="378" alt="Screenshot 2023-04-17 at 9 32 05 AM" src="https://user-images.githubusercontent.com/28541736/232485700-b6e3a952-2ea5-4410-aa74-def0633bf8e4.png">

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

112.0.5615.121 (arm64 version)

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, could you try:

- Install https://chrome.google.com/webstore/detail/privacy-pass/ajhmfdgkijocedmfjonnpjfojldioehi/related
- Go to https://captcha.website/
- Solve some captchas
- Go to https://vault.bitwarden.com/ and open debugger (F12 in Chrome etc)
- Try logging in - the captcha challenge shows now
- Log in with a browser extension

**Comment by rowankinney** [comment]
It seems I got it working, I signed deleted the extension, signed the account out of chrome, restarted chrome, signed back in, and then reinstalled the extension and now the login is working.
