### ISSUE TITLE
Updating an existing item

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/clients#5231]
### Steps To Reproduce

1. Open the application
2. Click on 'an item'
3. Click on 'the pencil icon' to edit the item
4. Edit the item
5. Click on 'the floppy icon' to save your changes

### Expected Result

The list is updated, and the cursor remains stationary on the newly modified element.

### Actual Result

The list is updated, and the cursor is moved to the top of the list.

### Operating System

macOS

### Operating System Version

13.3.1

### Installation method

Mac App Store

### Build Version

2023.3.2 (8075)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi there,

Thank you for your report! 

I am unable to reproduce this issue,

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by fabriziobagala** [comment]
@Adedamola-Aina I added a recording with the issue I am experiencing. As you can see, once the item is changed, the list is updated.
