### ISSUE TITLE
Activating (Remove individual vault export) Enterprise Policy prevents a Custom-type organizational member from exporting the organizational vault.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#5233]
### Steps To Reproduce

1. Create an Enterprise organization and activate only the (Remove individual vault export) Enterprise policy.
2. Create a Custom-type organizational member and grant them only the (Access import/export) permission.
3. Log into that Custom-type organizational member via the Web Vault (https://vault.bitwarden.com/#/).
4. Attempt to export the organizational vault.

### Expected Result

To be able to export the organizational vault items that this Custom-type organizational member is permitted to access.

### Actual Result

The following error message is shown.

_Vault export removed
One or more organization policies prevents you from exporting your individual vault._

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/73389600/232742655-09ff1d18-bd58-4da5-a596-3872b032842a.png)

### Additional Context

N/A.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2.

### Web Browser

Firefox

### Browser Version

112.0.

### Build Version

2023.3.0.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Closing this, as it got addressed with https://github.com/bitwarden/clients/pull/5014 which was included in the `2023.7`-release.
