### ISSUE TITLE
Bitwarden extension doesn't stay unlocked after page-based unlock

### ISSUE THREAD

**Issue by jedfonner** [bitwarden/clients#5261]
### Steps To Reproduce

When Bitwarden is locked...

1. hit the keyboard shortcut to auto-fill
2. Bitwarden will pop open a new browser tab to prompt me for my password. It appears to be in private mode???
3. After entering my password, Bitwarden will show as unlocked and display my Vault in the web page
4. Closing the Vault page will cause Bitwarden to lock itself again.  It doesn't appear the extension was ever really unlocked.

### Expected Result

Bitwarden remains unlocked

### Actual Result

Bitwarden is still locked

### Screenshots or Videos

https://user-images.githubusercontent.com/344481/233785478-6ac26edc-29cf-4106-aa73-6484df41a77b.mp4

### Operating System

Linux

### Operating System Version

KDE Plasma 5.27.4, Kernel 5.19.0-40

### Web Browser

Firefox

### Browser Version

112.0.1 (64-bit)

### Build Version

Version: 2023.3.1  Server version: 2023.3.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @jedfonner and thank you for your report.

Is this possibly a duplicate of https://github.com/bitwarden/clients/issues/5115?

**Comment by jedfonner** [comment]
Yes, I didn't see 5115 because it talks about Private Mode, but looking at the video it does seem to be the same issue.
