### ISSUE TITLE
Cannot import CSV file.

### ISSUE THREAD

**Issue by ousid** [bitwarden/clients#5271]
### Steps To Reproduce

1. Login into Bitwarden account
2. Go to __Tools__ section
3. Select __Import Data__
4. Select __roboform__ from the dropdown
5. Import the `roboform.csv` file
6. Click __Import data__

### Expected Result

It should import the data, and see the credentials along with the URLs in __Your Vault__ section.

### Actual Result

When Clicking the __Import Data__. Nothing happens. No errors nothing. But when you open the `console log`, multiple errors appears.

### Screenshots or Videos

Chrome Console Log
![image](https://user-images.githubusercontent.com/21012933/233781496-a6bbdb5c-fc66-4426-96e2-b8099ac8e172.png)

Firefox Console Log
![image](https://user-images.githubusercontent.com/21012933/233781559-c6e41033-32b6-4586-89a2-7d0137293fc7.png)

### Additional Context

I tried this process in __Brave Browser__, and in __Firefox__

### Build Version

Version 2023.3.0

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @ousid and thank you for your report.

This was previously reported with https://github.com/bitwarden/clients/issues/5187 and has been addressed with https://github.com/bitwarden/clients/pull/5137. The changes made, will be included in the next release 2023.4

Closing this now.

**Comment by ousid** [comment]
@djsmith85 Ah! I see, sounds good, and thank you for the clarification. 

The problem with roboform, that they locked my account without further notice, and said that my subscription has ended 😕 

I will see what I can do about that to import the data asap.

Thanks again!
