### ISSUE TITLE
Can't move item from folder to 'No Folder'

### ISSUE THREAD

**Issue by GabrielZalisz** [bitwarden/clients#5278]
### Steps To Reproduce

1. Open Bitwarden web vault
2. Create folder
3. Create item in the folder or move some existing item to the folder
4. Select the folder in left pane to see only items in that folder
5. Select the item using the checkbox
6. Click three dots in items list header and click `Move selected`
7. Select `No folder` in the combobox
8. Click `Save`

### Expected Result

Item should be moved to `No folder`. 

### Actual Result

Error `Input is required.` appears and item is not moved. 

### Operating System

Windows

### Operating System Version

Windows 11 22H2 (22621.1555)

### Web Browser

Brave

### Browser Version

Brave: 1.50.121, Chromium: 112.0.5615.138 

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by schang1146** [comment]
Is this open for the community to take?

**Comment by djsmith85** [comment]
@schang1146: Sorry for the late reply, we always appreciate any kind of contribution from our community ❤️

**Comment by jaymehta-g** [comment]
Any workarounds?

**Comment by schang1146** [comment]
There's some other ways to move items around instead of going through the original posts flow:

1. Click on item to open "EDIT ITEM" dialog
2. Select desired "Folder"
3. Click "Save"

Unfortunately it doesn't look like there's a good way of moving multiple items to the "No folder" folder in Web Vault currently.

**Comment by GabrielZalisz** [comment]
Possible workaround is to move the item using any other Bitwarden client,
like browser extension, mobile or desktop app.

Dne út 13. 6. 2023 22:36 uživatel Jay Mehta ***@***.***>
napsal:

**Comment by jaymehta-g** [comment]
> Possible workaround is to move the item using any other Bitwarden client, like browser extension, mobile or desktop app. But this doesn't solve the issue in Web Vault of course.

Are bulk actions even supported on mobile? I can't figure out how to do them

**Comment by sameer-haider** [comment]
Can I be assigned to this?

**Comment by wolf-yuan-6115** [comment]
> Hey there,
> 
> Thank you for your report! 
> 
> I was able to reproduce this issue, and I have flagged this to our engineering team.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.
> 
> Thanks once again!

Hello, may I ask if this is solved or not?

**Comment by maxammann** [comment]
Encountered the same problem today and was redirected here from support.
