### ISSUE TITLE
Microsoft Store Version removed

### ISSUE THREAD

**Issue by gregular-git** [bitwarden/clients#5310]
### Steps To Reproduce

1. Go to bitwarden.com/download
2. Click on 'more desktop installation options'
3. Scroll down to 'Windows Store'
4. Click on the link for store version

Alternatively, search for Bitwarden on Microsoft Store

### Expected Result

The user should be directed to the windows store app for Bitwarden.

### Actual Result

Microsoft store page says
"We are sorry, the page you requested cannot be found.

The URL may be misspelled or the page you're looking for is no longer available."

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/131989636/235124946-556e09fa-572b-4799-88aa-51e0baf8c6b2.png)
![image](https://user-images.githubusercontent.com/131989636/235125097-e409e2da-75ba-4a05-b0d1-ab9f294881f9.png)

### Additional Context

The microsoft store app shows a list of previously and currently stored applications. The list does not show Bitwarden, even though I have installed the app from there.

### Operating System

Windows

### Operating System Version

21H2

### Installation method

Microsoft Store

### Build Version

NA (The last version present was 23.3.1)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@gregular-git: Thank you for your report. I can confirm that the download is currently not available. The team is looking into it.

**Comment by gregular-git** [comment]
Client available on Microsoft Store again, with update to the (currenty) latest version 23.4.0
Issue closed.
