### ISSUE TITLE
Password auto-filling in a not password type input

### ISSUE THREAD

**Issue by Catif** [bitwarden/clients#5314]
### Steps To Reproduce

1. Create account on '[Ankama website](https://account.ankama.com/fr/creer-un-compte)'
2. Save the account in bitwarden
3. Disconnect your account if you are logged
4. Go to '[password recuperation](https://account.ankama.com/fr/compte/recuperation-mot-de-passe-mail)' 
5. See the input form

### Expected Result

Two choice : 
- Don't do anything, no auto-filling
- Auto-filling with the username

### Actual Result

The password save on bitwarden was auto-filling in a not password type input

### Screenshots or Videos

Video :
[chrome_M4UXYC0SRg.webm](https://user-images.githubusercontent.com/84462178/235311659-c62a28d9-7291-4a7e-912e-69cab3ff1f41.webm)

Screenshot : 
```html
<input type="text" class="form-control valid" name="loginpassword" id="loginpassword" placeholder="Identifiant" value="" aria-required="true" aria-invalid="false">
```

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

112.0.5615.138

### Build Version

Build Officiel | 64 Bits

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @Catif,

Thank you for your report. The (Identifiant) field has (loginpassword) as an id value and name value, and that is causing the extension to interpret it as a password field. For this website, please try using only custom fields (https://bitwarden.com/help/custom-fields/) to manually set what string should be entered into each field. If that's not working out as expected, please feel free to get in touch with us (https://bitwarden.com/help/) and include a link to this report and please also try to supply Login credentials to that site so we'd test it.

If you'd like the extension to possibly be tuned specifically to that webpage (URL), you are more than welcome to report it via the (Report autofill failure in browser) form here (https://github.com/bitwarden/clients/issues/new/choose).

To be clear, you can access the relevant forms directly through the links below.
For the Mobile client (https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform)
For the Browser extension (https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform)

In the future, if you encounter another webpage or application where our clients did not perform Auto-Fill as expected, please report that directly via the corresponding form.

This report will now be closed.

Thank you again,

**Comment by Catif** [comment]
Hi @SergeantConfused,

Maybe I'm dumb, but why don't Bitwarden fill only field with type password (by default)?

like : 
```html
<input name="xxx" id="xxx" type="password">
```

---
Should I fill out the Google form, or did you do it for me?
