### ISSUE TITLE
"Browser integration not set up yet" message in browser despite browser integration being setup on desktop app.

### ISSUE THREAD

**Issue by maxwell-martin** [bitwarden/clients#5315]
### Steps To Reproduce

1. Go to browser (in my case, Google Chrome).
2. Click on the Bitwarden extension icon.
3. Click on 'Settings' gear icon within Bitwarden extension GUI.
4. Click on 'Unlock with Biometrics' checkbox.
5. See message pop-up saying "Browser integration is not set up...":

![image](https://user-images.githubusercontent.com/30988157/235360301-55510285-9009-4a00-898a-40c869b2a972.png)

7. Check desktop application settings.

8. Confirm 'Allow browser integration' checkbox is checked:

![image](https://user-images.githubusercontent.com/30988157/235360267-a06e265f-8572-4434-a279-515050008656.png)

### Expected Result

The expected result is that the browser extension successfully confirms that desktop integration is working and then pops up the normal Windows Hello sign-in window upon clicking on the extension for use.

### Actual Result

The actual result is that the browser extension does not allow me to do Windows Hello integration despite the desktop application having it setup properly.

### Operating System

Windows

### Operating System Version

Edition Windows 11 Home, Version 22H2, OS build 22621.1555, Windows Feature Experience Pack 1000.22640.1000.0

### Web Browser

Chrome

### Browser Version

Version 112.0.5615.138 (Official Build) (64-bit)

### Build Version

Version: 2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello Maxwell, 

This issue sometimes stems from the HKEY_CURRENT_USER\Software\[your_browser]\NativeMessagingHosts\com.8bit.bitwarden registry key not being created.  You can try the below steps, with which some users have reported success:

In Bitwarden Desktop:
- Disable Login With Windows Hello
- Disable Browser integration

Restart your machine.

In Bitwarden Desktop:
- Enable Browser Integration
- Enable Windows Hello / Biometrics

In the Browser Extension:
- Enable Biometrics

Let us know how it goes!This issue sometimes stems from the HKEY_CURRENT_USER\Software\[your_browser]\NativeMessagingHosts\com.8bit.bitwarden registry key not being created.  You can try the below steps, with which some users have reported success:

In Bitwarden Desktop:
- Disable Login With Windows Hello
- Disable Browser integration

Restart your machine.

In Bitwarden Desktop:
- Enable Browser Integration
- Enable Windows Hello / Biometrics

In the Browser Extension:
- Enable Biometrics

Let us know how it goes!

**Comment by maxwell-martin** [comment]
That solved the problem. Thanks.

**Comment by CarstenG2** [comment]
This issue is back in 2023.5.0 and 2023.5.1 with Chrome 114 on Win11. The mentioned REG-key does exist, but the error is still popping up as shown above.

**Comment by Paxy** [comment]
Is "Unlock with Biometrics" possible only with the Windows Desktop app? I can't find "Enable Browser Integration" in the Linux Desktop app?!

**Comment by vvirtues** [comment]
I have this issue in a third party firefox fork (Floorp). The mentioned path does not exist, which leads me to believe either the browser doesn't support REG keys/blocks them or you need to configure the extension to work with them

**Comment by vvirtues** [comment]
I tried the above fix and resetting extension permissions with no luck

**Comment by igokhul** [comment]
I have multiple browsers for different purposes. I first setup with chrome and it's working fine now I'm trying with firefox but it doesn't seem to recognize it. Is that because I already used it in chrome?

**Comment by vvirtues** [comment]
I don't think so because I have it set up with multiple chromium (brave) browsers. Just doesn't seem to work with firefox forks

**Comment by lduperval** [comment]
I'm using the Firefox build on Win 11 and it doesn't work either.
