### ISSUE TITLE
BitWarden autofill enters password in CAPTCHA field instead of password field in Chrome browser

### ISSUE THREAD

**Issue by LpCodes** [bitwarden/clients#5344]
### Steps To Reproduce

1. Open the website https://myaccount.tataplayfiber.co.in/Selfcare/Login.html
2. Click on the login button.
3. Wait for BitWarden to offer to autofill the credentials.
4. Click on the BitWarden icon and select the appropriate login entry.'

### Expected Result

The BitWarden should recognize the correct password field on this website and enter the password in the appropriate field.

### Actual Result

The BitWarden enters the password in the CAPTCHA field instead of the password field, making it impossible to log in.

### Screenshots or Videos

No screenshot or video available.

### Additional Context

This issue is causing inconvenience as I have to manually type the long password every time I log in. The website does not support copy and paste, which makes it even more challenging to log in. It is worth noting that this website works with Chrome's built-in password manager and not with Bitwarden. My system information is as follows:

Browser: Google Chrome Version 112.0.5615.138
Operating System: Microsoft Windows 11
OS Version: 10.0.22621
Bitwarden extension version: 2023.4.0
Is there any way to make BitWarden recognize the correct password field on this website?

Thank you for your assistance in resolving this issue. Please let me know if you need any further information or assistance from me.

### Operating System

Windows

### Operating System Version

10.0.22621

### Web Browser

Chrome

### Browser Version

 112.0.5615.138

### Build Version

Bitwarden extension version: 2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

The issue seems to be on the website side. Both the password and Captcha field are set to type-password within HTML which causes the issue. If you can, please contact the website administrator. 

Meanwhile we can offer use of custom fields to bypass this issue - https://help.bitwarden.com/article/custom-fields
