### ISSUE TITLE
Biometric Login - Desktop Communication Interrupted

### ISSUE THREAD

**Issue by tenebris93** [bitwarden/clients#5354]
### Steps To Reproduce

1. Go to the Chrome browser extension.
2. Watch as the Chrome browser extension attempts to open Windows Hello for biometric login. (Silent Fail - No notification)
3. Click on login using biometrics.
4. User is treated with `Desktop communication interrupted` error.

### Expected Result

The user should be prompted to authenticate via their preferred biometric signing method. In my case Windows Hello Face Recognition.

### Actual Result

A new error notification appears instead that informs the user that the: `Desktop application invalidated the secure channel. Please retry this operation.`

### Screenshots or Videos

Error Message:
![image](https://user-images.githubusercontent.com/6475272/236002477-c454ee5f-3a46-483a-aa57-423e07aedb4d.png)

Windows Desktop Client Version:
![image](https://user-images.githubusercontent.com/6475272/236004042-fbc71e92-ab80-45eb-be9f-5d96807c2d2f.png)

Chrome Browser Extension:
![image](https://user-images.githubusercontent.com/6475272/236004228-92378262-2b7c-4766-86e5-0763717b3909.png)

Desktop Settings:
![image](https://user-images.githubusercontent.com/6475272/236004448-e48abc55-901d-4521-8657-edbf6f05ef84.png)

Chrome Browser Settings:
![image](https://user-images.githubusercontent.com/6475272/236004801-a317a3be-0525-4216-b962-38b2433e6056.png)
![image](https://user-images.githubusercontent.com/6475272/236004849-0a0d2392-5aed-4909-bfdf-7a0392ff6e9f.png)

### Additional Context

This was working perfectly fine until I was prompted yesterday to update the desktop client to version 2023.4.0

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

113.0.5672.64

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tenebris93** [comment]
I originally opened an identical ticket to this but then closed it due to thinking it was due to user error. However, after restarting my PC it started happening again. Thus I have remade this ticket.

**Comment by atjbramley** [comment]
Hi @tenebris93 ,

I attempted to reproduce your issue with both Windows 10 and Windows 11 Pro 22H2 and was unable to do so.

I think your error could have its origin in a corruption or conflict isolated to your specific environment, and would encourage you to reinstall the extension to see if this resolves itself.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by nosh56355** [comment]
@atjbramley 
Unhappy that you closed the issue so quickly. I have the same problem on all Browsers (Edge, Chrome, Brave, Firefox) 
w/ Win11 Version 10.0.22621; Bitwarden Version: 2023.4.0 Server version: 2023.4.3.
Suggest to reopen the Ticket.
Thanks, NoSh

**Comment by tenebris93** [comment]
@nosh56355 I was able to mitigate that error after doing a uninstall using the free version of [Revo Uninstaller](https://www.revouninstaller.com/revo-uninstaller-free-download/) and uninstalling the browser extension. After uninstalling, I restarted and then reinstalled the desktop client and then the browser extension. Once reinstalled, I set up the desktop client first and then the browser extension. I still get the error everyone in a while, however, once that happens I just try to unlock it again and then it works. That being said, it seems like every time there is a major update to Bitwarden that changes functionality. It seems to end up getting more and more unstable. Hopefully, in the next patch, they will be able to get someone else to repo it on their side and then push out a stability patch to remove the error entirely.

**Comment by shiloh-nelson** [comment]
I have started having this same issue a few days ago as well

**Comment by nosh56355** [comment]
Gotcha: you need to enable biometric authentication in the desktop app. Otherwise the browser extension throws this error.

**Comment by LeedsCode** [comment]
I've been having this issue too and finally decided to look it up and try to fix it.
What fixed it for me is:
1. Log into the Bitwarden desktop application w/ master password (there was no option to use biometrics for me)
2. Do nothing - let the vault lock from your timeout (mine is set to 1 minute)
3. This time I clicked "Unlock with Windows Hello" - it's probably "biometrics" or "finderprint" on non-windows machines
4. I was successfully able to use my fingerprint to login here
5. Go to a website and login, now it asks for my fingerprint

**Comment by boypt** [comment]
> I've been having this issue too and finally decided to look it up and try to fix it. What fixed it for me is:
> 
> 1. Log into the Bitwarden desktop application w/ master password (there was no option to use biometrics for me)
> 2. Do nothing - let the vault lock from your timeout (mine is set to 1 minute)
> 3. This time I clicked "Unlock with Windows Hello" - it's probably "biometrics" or "fingerprint" on non-windows machines
> 4. I was successfully able to use my fingerprint to login here
> 5. Go to a website and login, now it asks for my fingerprint

On step 2 I lock the Bitwarden desktop by pressing Ctrl+L, also works. The `Unlock with Windows Hello` button shows up after manual triggered lock.

**Comment by TheAdamGalloway** [comment]
Not sure if anyone has got to the bottom of this, but it recently started happening for me on Mac with Brave browser. No doubt I will be able to fix it with a reinstall but still quite frustrating that there's no root cause identified.

**Comment by Lolle2000la** [comment]
I have the same issue and I think this happens on the desktop client side. I don't know how the connection is done, but if you close the app and reopen it, communication will usually fail.

Maybe the code that handles the communication should be put into a Windows service (and the MacOS equivalent) so that auth can work regardless of if the client is open (yet).
