### ISSUE TITLE
Cannot add new item from the extension [Error Code 7]

### ISSUE THREAD

**Issue by isayakmondal** [bitwarden/clients#5361]
### Steps To Reproduce

1. Go to 'Bitwarden chrome extension'
2. Click on 'Add Item'
3. Fill up 'the  name, username, password'
4. Click on 'Save'
password

### Expected Result

It should just be saved.

### Actual Result

Getting an response of 'An Error has occurred, with Error Code 7'

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/51121313/236184728-151ef8a4-2958-475a-81d1-17ea2b2a8413.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

113.0.5672.63 (Official Build) (64-bit)

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hello @isayakmondal

Thank you for bringing this up. 

We use GitHub issues as a place to track bugs and other development related issues. please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/
