### ISSUE TITLE
'Input is required' message shows up before it's supposed to

### ISSUE THREAD

**Issue by Sushants-Git** [bitwarden/clients#5389]
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/login
2. Type in your email and then press **Enter** ( The bug will not be reproduced if you click on the **Continue** button instead of pressing **Enter**)
3. It will take us to the **master password field** but the message **Input is required** will already be present :

![screenshot-20230507-063422Z-selected](https://user-images.githubusercontent.com/100516354/236662623-b5d976e3-49c8-4179-9975-ad20e28634e5.png)

4. The message **Input is required** should show up only after the user tries to login with an empty password. Not when the user has just typed their email and pressed **Enter**.

- In short it would be more appropriate if pressing **Enter**  worked like clicking the  **Continue** button, The **Continue** button takes us to the Master Password field but does not show the **Input is required** message until the user either tries to click out of the **Password** field or tries to login with an empty password.

### Expected Result

It shouldn't show the **Input is required** message when the user first reaches the Master password field since that's not what the user sees if they pressed the **Continue** button. 

### Actual Result

It's showing  **Input is required**  message as soon as the user types their email and presses **Enter**

![screenshot-20230507-063422Z-selected](https://user-images.githubusercontent.com/100516354/236663056-f26dd859-27a0-4ac8-ab59-dbdbb0657a8c.png)

### Screenshots or Videos

https://user-images.githubusercontent.com/100516354/236663027-6c2a8c26-cc8f-47bb-8b8e-be171d946d6c.mp4

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

Version  112.0.2 Firefox Release  April 25, 2023

### Build Version

Version 2023.4.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by souravghosh01** [comment]
I noticed this issue and I am interested in contributing to it. If you are not currently working on it, may I take it up and work on a solution? @Sushants-Git

**Comment by souravghosh01** [comment]
@Sushants-Git I  Tried to reproduce this issue locally but failed. I think this issue is fixed and will be deployed to Production Later 

QA : [https://vault.qa.bitwarden.pw/#/login)](url)

![Recording 2023-05-07 at 22 03 59](https://user-images.githubusercontent.com/37548139/236696224-607d758b-945a-4499-b358-d49e63b52170.gif)

**Comment by SergeantConfused** [comment]
Hi @Sushants-Git,

Thank you for your report. I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.


Thank you once again,

**Comment by djsmith85** [comment]
Hi @Sushants-Git, thank you for your report.

This issue was caught internally and was fixed with https://github.com/bitwarden/clients/pull/5246.

The changes will be included in the next release 2023.5.

Closing this now.

**Comment by Sushants-Git** [comment]
Oh that's good to hear, you folks have created a great app keep up the good work !!
