### ISSUE TITLE
Extension gets immediately logged out with timeout policy action 'logOut' and SSO login

### ISSUE THREAD

**Issue by mvalois** [bitwarden/clients#5391]
### Steps To Reproduce

1. Enable timeout policy and set action to 'logout'
2. log in on the web extension (tested on chromium) with SSO (first time is fine)
3. log out
4. log in again with SSO
5. extension redirects to webvault for SSO, asks then to return to web extension
6. web extension gets logged out

It does not append when the timeout policy action is 'lock' or when login in directly with master password (when SSO is not forced).

### Expected Result

Locked vault asking for master password

### Actual Result

Logged out vault asking for email

### Operating System

Linux

### Web Browser

Chrome

### Build Version

2023.4.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mvalois** [comment]
Disabling views reloading after successful login, by removing this line https://github.com/bitwarden/clients/blob/e13dd1dfefc1ae149c0982facf0c1a5276ca5695/apps/browser/src/auth/popup/sso.component.ts#L64 makes it work.
It sounds like reloading views make the extension lost the authentication state.

**Comment by Adedamola-Aina** [comment]
hi @mvalois 

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by mvalois** [comment]
I found this PR https://github.com/bitwarden/clients/pull/5286 which I tested and it works! I think we can close this when the PR is merged :)
Thank you =)
