### ISSUE TITLE
Bitwarden chrome mac extension locks out right after unlocking

### ISSUE THREAD

**Issue by sachdevasushant** [bitwarden/clients#5397]
### Steps To Reproduce

1. Log in to mac chrome extension

### Expected Result

The extension stays logged in for 15 minutes as per timeout settings

### Actual Result

Often, but unpredictably, the vault locks itself almost immediately after logging in (a few seconds delay)

### Additional Context

This has been happening for several months. Browser and extension updates seem to have not fixed it.

### Operating System

macOS

### Operating System Version

Ventura 13.3.1 (a) (22E772610a)

### Web Browser

Chrome

### Browser Version

 112.0.5615.137 (Official Build) (x86_64)

### Build Version

Version: 2023.4.0  Server version: 2023.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mvalois** [comment]
is it similar to https://github.com/bitwarden/clients/issues/5391?

**Comment by sachdevasushant** [comment]
It's simpler. No SSO involved.
My timeout action is lock after 15 minutes.
I login using my personal email, biometric desktop connection, and often it just locks right after logging in.

**Comment by sachdevasushant** [comment]
Nowhere did I indicate that I close any bitwarden app. 
See this loom video for a demonstration of this issue happening.
https://www.loom.com/share/1802aeef1bfc42059ade3355bfc9c1ad

**Comment by djsmith85** [comment]
@sachdevasushant It sounds like the issue you are describing is similar to https://github.com/bitwarden/clients/issues/3441

If that is the case, then this has been addressed with https://github.com/bitwarden/clients/pull/4835 and will be released with 2023.5.

Kind regards,
Daniel
