### ISSUE TITLE
Failed to fetch - trying to login self-hosted

### ISSUE THREAD

**Issue by XDavidT** [bitwarden/clients#5418]
### Steps To Reproduce

1. Go to the login page
2. Click on setting - set the self-hosted address - Save
3. Put the email address
4. Put the password
5. Trying login

### Expected Result

Logging and see my vault

### Actual Result

Getting error Failed to fetch

### Screenshots or Videos

https://i.imgur.com/JQ2ENrS.png

### Additional Context

Ubuntu 22.04
With BitWarden user it worked great, but now I want to add also my self-hosted vaultwarden.
The HTTPS is not verified ( self-sign )

### Operating System

Linux

### Operating System Version

22.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.11.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @XDavidT, 

It is important to note that vaultwarden (the new name for Bitwarden RS) is not associated with Bitwarden.  vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

Bitwarden also offers a self-hosted option.  You can find information on this here:

https://bitwarden.com/help/install-on-premise-linux/ 
https://bitwarden.com/help/install-and-deploy-offline/ 

I hope you find this helpful.  This issue will now be closed.
