### ISSUE TITLE
Web vault cutting letters with descender in item name

### ISSUE THREAD

**Issue by GabrielZalisz** [bitwarden/clients#5419]
### Steps To Reproduce

1. Create item with name containing any letter with [descender](https://en.wikipedia.org/wiki/Descender) (like g, j, q, p, y) and save the item
2. Look up the item in item list – the bottom part of letters with descender is cut (see screenshot below)

### Expected Result

letters not cut

### Actual Result

letters cut

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/45824535/c08ec9dc-f445-486b-bc1d-bf1cc23e3206)

### Operating System

Windows

### Operating System Version

any

### Web Browser

Brave

### Browser Version

any browser, any version

### Build Version

any

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @GabrielZalisz and thank you for your report.

Just wanted to clarify one thing. Is this behaviour visible in the web vault (https://vault.bitwarden.com), on the browser extension or even both?

For the web vault, https://github.com/bitwarden/clients/pull/5345 has just been merged which addresses the behaviour you described. The changes will be released with `2023.5.`

Kind regards,
Daniel

**Comment by GabrielZalisz** [comment]
Exactly, sorry for wrong tag

**Comment by djsmith85** [comment]
@GabrielZalisz: No problem, I'm going to close this, as the issue has been addressed with #5345. The `2023.5`-release is scheduled for end of the month.
