### ISSUE TITLE
"Salt" file in Home folder

### ISSUE THREAD

**Issue by Odi-3** [bitwarden/clients#5428]
### Steps To Reproduce

1. Open your file manager
2. Go to Home folder

### Expected Result

You wouldn't want to find files that you didn't add on purpose.

### Actual Result

A text file named "salt" appears.

### Operating System

Linux

### Installation method

Other

### Build Version

2023.4.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @Odi-3 

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

**Comment by Odi-3** [comment]
Hi @Adedamola-Aina 
All right. Thank you for taking charge of the problem. I will try to see how it goes when the application has received some other updates. If the problem persists I will contact you in the way you have indicated me.

**Comment by Odi-3** [comment]
Hi @SergeantConfused 

1. Fedora 38, Gnome 44, Linux 6.2
2./3. Bitwarden 2023.4.0 (Flatpak) from Flathub
4. I encountered the issue after installing Bitwarden. Also, if I delete the file, it doesn't reappear until I start Bitwarden again. The very nature of the file seemd to justify my assumption: https://en.wikipedia.org/wiki/Salt_(cryptography)

**Comment by Odi-3** [comment]
It seems that after the last update to version 2023.5.0 the issue no longer exists.
