### ISSUE TITLE
Passphrase generation enforces non-empty word separator 

### ISSUE THREAD

**Issue by climardo** [bitwarden/clients#5437]
### Steps To Reproduce

1. Create new item by pressing +
2. Click the "generate password" button
3. Choose options
4. Choose "Passphrase"
5. Check the "Word Separator" field content. It should be empty. If it is not empty, remove any content from it.

### Expected Result

When the "word separator" field is empty, I'd expect the generated passphrase to have no whitespace or other separator.

### Actual Result

The generated passphrase has whitespace as a word separator.

### Screenshots or Videos

![screenshot](https://user-images.githubusercontent.com/230827/136211524-b5ccf4b7-4e03-4988-88ff-90eca6948939.png "screenshot")

### Additional Context

There seems to be no way to remove the standard whitespace. As tedious as it is, I can still find a lot of websites that don't accept passwords with whitespace in it, so my way-to-go is usually to generate a CamelCasePasswordWith1NumberInIt .

But I cannot remove the whitespace when generating the password with bitwarden.

NOTE: This is a total copy/paste of an issue created by @alanfranz, https://github.com/bitwarden/desktop/issues/1099

### Operating System

macOS

### Operating System Version

10.14.6

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.28.3 (535)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
