### ISSUE TITLE
browser addon resets once mouse hovers away from it

### ISSUE THREAD

**Issue by jenny787** [bitwarden/clients#5440]
### Steps To Reproduce

Often times, you need to search manually and find a login you are looking for.  And then you have to copy and paste the user and password.  However, once you find the right card and copy the user, then you paste it in the browser....then you come back to the addon, and it's all reset.  You need to once again search for, find the right card, and then this time copy password.  And this goes for other things as welll....when the mouse hovers away, it resets.  Can you make it somewhat presistent?  So that we can copy and paste back and forth easily?  At least for a few seconds or a minute or so?

### Expected Result

persistent selection when a card is manually selected.

### Actual Result

the selection resets as soon as the mouse goes away

### Operating System

Windows

### Web Browser

Chrome, Firefox

### Build Version

latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cksapp** [comment]
Hi @jenny787,

What you are describing sounds like the currently intended behavior and not a bug, but would instead a new feature.

For feature requests Bitwarden uses their community forums, which there is a similarity related request you may add your support for.
https://community.bitwarden.com/t/persistent-bitwarden-ui-and-maintain-unsaved-data/5470

**Comment by SergeantConfused** [comment]
Hi @jenny787,

Thank you for your report. As @cksapp mentioned, your issue appears to be describing the intended behaviour. If you want this to be changed, it would be a feature request; The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ and you can also use the link in the comment above.

We use GitHub issues as a place to track bugs and other development related issues; This issue will now be closed. 


Thank you again,
