### ISSUE TITLE
Manually marking and copying the password in the generator inserts a line break character (CR LF) at the beginning

### ISSUE THREAD

**Issue by Hofei90** [bitwarden/clients#5563]
### Steps To Reproduce

1. Go to View - Generator
2. mark the generated password with the left mouse button
3. Press CTRL-C
4. Insert the password at the desired position with CTRL-V, tested in Notepad++

### Expected Result

It is expected that only the marked password, as it was seen in the generator, is inserted into the field

### Actual Result

An additional newline character CR LF is inserted before the password.

### Screenshots or Videos

![bitwarden_crlf](https://github.com/bitwarden/clients/assets/29521028/0ab243c1-ee19-4068-963e-ae846800c78c)

### Additional Context

The error also occurs when using the password generator in the Firefox plugin. Firefox plugin version number: 2023.4.0

### Operating System

Windows

### Operating System Version

Windows 10 22H2 19045.2728

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Hofei90 and thank you for your report.

There's already a community PR with https://github.com/bitwarden/clients/pull/5312, which will likely address this.

Kind regards,
Daniel
