### ISSUE TITLE
Autofill does not work with blank password

### ISSUE THREAD

**Issue by Germs2004** [bitwarden/clients#5567]
### Steps To Reproduce

1. Go to any website with a login form, such as https://myaccount.openvpn.com/signin/as
2. Create an entry in Bitwarden for that site.  Use username "test" and a blank password.
3. Press CTRL-SHIFT-L to autofill.
4. Notice that nothing happens.
5. Click the Bitwarden extension icon and then click the website's entry that appears under Logins to autofill.
6. Notice that you get an error: "Unable to auto-fill the selected item on this page."
7. Now, edit that Bitwarden entry to add a password like "test2".
8. Attempt to autofill and notice that it works correctly.

### Expected Result

Autofill should type the username into the web page if the username is available in Bitwarden, even if the Password field is blank.

### Actual Result

Bitwarden will refuse to autofill the Username, even though it is available, just because the Password is blank.

### Additional Context

Entering just the password is useful for two scenarios:
1) accounts on a local web app that has a blank password
2) when I want to always manually type my password into a website but I still want my username to be autotyped for me.

### Operating System

Windows

### Operating System Version

11 Pro 22H2

### Web Browser

Brave

### Browser Version

Version 1.52.119 Chromium: 114.0.5735.90 (Official Build) (64-bit)

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Germs2004 and thank you for your report.

This should be addressed with https://github.com/bitwarden/clients/pull/5325 which got included in the just released `2023.5.`

Could you please check if you are using the most recent version of the browser extension.

**Comment by Germs2004** [comment]
You're right, it's fixed.  I assumed my browser kept extensions up to date automatically, but I clicked "Update" and it updated to from 2023.4.0 to 2023.5.0.  Now, it autofills the Username when the password is blank.
