### ISSUE TITLE
Selecting 2FA Recovery Code method does not bring up 2FA recovery page

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#5595]
### Steps To Reproduce

1. Use a Bitwarden account that has 2FA enabled.
2. On Web Vault Login page, enter email, then master password, then click "Log in with master password"
3. At the 2FA prompt, click "Use another two-step login method".
4. On the "Two-step login options" page, click the <kbd>Select</kbd> button for the **Recovery code** option.

### Expected Result

The user would expect to be taken directly to the 2FA recovery form at [https://vault.bitwarden.com/#/recover-2fa](https://vault.bitwarden.com/#/recover-2fa), where they can enter their recovery code to disable 2FA.

### Actual Result

Clicking the <kbd>Select</kbd> button launches an article from the Help Center:

https://bitwarden.com/help/lost-two-step-device/

About half-way through this article, the attentive reader will find a statement "Learn more [here](https://bitwarden.com/help/two-step-recovery-code/#use-your-recovery-code)", in which the word "here" is a hyperlink to yet another Help Center article:

https://bitwarden.com/help/two-step-recovery-code/#use-your-recovery-code

Within this Help Center article, the reader will ultimately find the instructions "To use your recovery code, navigate to https://vault.bitwarden.com/#/recover-2fa/", and upon clicking the URL, they will finally be taken to the relevant 2FA recovery form. 

### Additional Context

This feature may be used in two contexts:

* A user has lost access to their 2FA methods, and would therefore be locked out of their vault, but for the existence of the 2FA recovery code.  Such a user will likely be stressed, perhaps even panicked, and may not have the patience and mental concentration required to review all of the presented Help Center articles to find the required links.  There is no good reason why clicking the <kbd>Select</kbd> button shouldn't take this user directly to the [2FA Recovery Form](https://vault.bitwarden.com/#/recover-2fa), instead of requiring them to hunt for two additional links that must be clicked before the form is reached.

* A user who is not locked out of their vault, but does not know about 2FA recovery codes, and selects the "Recovery code" option out of curiosity.  Although such a user may find the linked Help Center articles of interest, it should be noted that the [2FA Recovery Form](https://vault.bitwarden.com/#/recover-2fa) also includes a prominent "[Learn more](https://bitwarden.com/help/lost-two-step-device/)" link that points to the relevant Help Center article.  Because this category of user is unlikely to be hurried or stressed, they will not be negatively affected by the need to make one additional mouse click to get information about 2FA recovery.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
