### ISSUE TITLE
UnhandledPromiseRejectionWarning when running 'bw list items' command

### ISSUE THREAD

**Issue by neogeek23** [bitwarden/clients#5613]
### Steps To Reproduce

1. Install bitwarden CLI tool via npm on a Raspberry Pi 4 running armbian
2. Login via the CLI.
3. Run the command `bw list items --organizationid [Organization ID]`

### Expected Result

A list of items.

### Actual Result

root@atlas00:~# bw list items --organizationid 4f3c7c68-bad7-44f9-95db-d7edb2bc399d
? Master password: [hidden]
(node:1819334) UnhandledPromiseRejectionWarning: Error: error:25066067:DSO support routines:dlfcn_load:could not load the shared library
    at Object.privateDecrypt (internal/crypto/cipher.js:63:12)
    at NodeCryptoFunctionService.rsaDecrypt (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:32286:58)
    at CryptoService.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:14196:47)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:13638:58)
(node:1819334) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1819334) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Screenshots or Videos

N/A

### Additional Context

The Bitwarden server being used is a locally hosted vaultwarden (the Rust rewrite) running on a separate Raspberry Pi 4.

```
root@atlas00:~# cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=rpi4b
BOARD_NAME="Raspberry Pi 4"
BOARDFAMILY=bcm2711
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=1a8daf0
VERSION=23.02.2
LINUXFAMILY=bcm2711
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
BRANCH=current
root@atlas00:~# uname -a
Linux atlas00 5.15.92-bcm2711 #23.02.2 SMP PREEMPT Fri Feb 17 22:42:10 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
root@atlas00:~# bw --version
2023.5.0
root@atlas00:~# k describe deployment -n bitwarden
Name:                   vaultwarden
Namespace:              bitwarden
CreationTimestamp:      Thu, 08 Jun 2023 10:05:00 -0500
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 3
Selector:               app=vaultwarden
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:       app=vaultwarden
  Annotations:  kubectl.kubernetes.io/restartedAt: 2023-06-08T11:14:59-05:00
  Containers:
   vaultwarden:
    Image:      vaultwarden/server:latest
    Port:       80/TCP
    Host Port:  0/TCP
    Environment Variables from:
      vaultwarden-config     ConfigMap  Optional: false
      vaultwarden-db-secret  Secret     Optional: false
    Environment:             <none>
    Mounts:
      /data from vaultwarden-data (rw)
  Volumes:
   vaultwarden-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  vaultwarden-pvc
    ReadOnly:   false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   vaultwarden-b764c6988 (1/1 replicas created)
Events:          <none>
```

If you have some dev build you want me to test against my deployment that I got this error from, let me know.

### Operating System

Linux

### Operating System Version

Linux atlas00 5.15.92-bcm2711 #23.02.2 SMP PREEMPT Fri Feb 17 22:42:10 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

### Shell

Bash

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Thank you for the report but this appears to be hosted with Vaultwarden which is a separate application from Bitwarden that we do not provide support for. 

You can find the contact information for Vaultwarden here: [https://github.com/dani-garcia/vaultwarden#get-in-touch](https://github.com/dani-garcia/vaultwarden#get-in-touch)
