### ISSUE TITLE
not possible to package cli (pkg) starting from version 2023.2.0

### ISSUE THREAD

**Issue by moritzj29** [bitwarden/clients#5615]
### Steps To Reproduce

1. run any node docker container as defined build environment on arm64 platform: `docker run node:lts --rm \bin\bash`
2. install bw cli: `npm install -g @bitwarden/cli`
3. install pkg: `npm install -g pkg`
4. package bw cli: `pkg /usr/local/lib/node_modules/@bitwarden/cli --output ./bw`
5. try to run packaged bw cli: `./bw` -> fails

### Expected Result

packaged bitwarden cli executes

### Actual Result

packaged bitwarden cli does not start, instead throws error that argon2 dependencies cannot be found

### Screenshots or Videos

```
root@09ee5aa9f589:/# ./bw
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: Cannot find module '/snapshot/node_modules/@bitwarden/cli/node_modules/argon2/lib/binding/napi-v3/argon2.node'
Require stack:
- /snapshot/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js
- /snapshot/node_modules/@bitwarden/cli/build/bw.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at Module.require (pkg/prelude/bootstrap.js:1851:31)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snapshot/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js:9:25)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snapshot/node_modules/@bitwarden/cli/node_modules/argon2/argon2.js',
    '/snapshot/node_modules/@bitwarden/cli/build/bw.js'
  ],
  pkg: true
}

Node.js v18.5.0
```

### Additional Context

issue first appears with 2023.2.0. Release 2023.1.0 still runs as package.

Probably related to #4579 . Same problem already described in comment https://github.com/bitwarden/clients/pull/4579#issuecomment-1405408923 but without any details on how this was fixed.

### Operating System

Linux

### Operating System Version

debian bookworm in docker on macOS arm64 host

### Shell

Bash

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @moritzj29,

The bitwarden CLI requires native modules in order to function properly. To that end we don't currently support or have any plans on supporting the pattern of packaging it up yourself using `pkg` without running through our regular `npm scripts`. https://github.com/bitwarden/clients/blob/master/apps/cli/package.json#L31-L34

I will close this issue since it's out of scope. If you want to continue digging, you will have to figure out a way to get pkg to include the native dependencies in it's package. We do that through https://github.com/bitwarden/clients/blob/master/apps/cli/package.json#L43-L48.
