### ISSUE TITLE
When the vault is locked, asking to add the credentials will always add the credentials even if the site exists.

### ISSUE THREAD

**Issue by NiceGuyIT** [bitwarden/clients#5630]
### Steps To Reproduce

1. Have the Bitwarden extension installed and working with your vault.
2. Have the "Ask to add login" or "Ask to update existing login" checked. I didn't to extensive testing to determine which option is causing the problem.
3. Lock the vault.
4. Open a site that already exists in the vault.
5. Enter your credentials.
6. When prompted by the extension, choose the option to add the credentials to the vault.
7. Enter your credentials to unlock the Bitwarden vault.
8. Check the vault and notice there is a new entry for that site.
9. Repeating steps 3-7 will add a new entry to the vault.

### Expected Result

After unlocking the vault, the Bitwarden extension should check if an entry exists and update it, not add a new entry. I.e. the check to add/update an entry should be done _after_ unlocking the vault, not when the vault is locked. If the vault is locked, it will always be "Add new entry" because existing entries are not known.

### Actual Result

Repeating steps 3-7 will add duplicate entries to the vault. One of my clients had about 20 duplicate entries for one site because she was using the Bitwarden desktop app to enter the site credentials, and when prompted by the extension to add the entry, she chose yes and unlocked the vault (in the extension). I'm able to reproduce on my account.

### Operating System

macOS, Linux

### Operating System Version

openSUSE Leap 15.4

### Web Browser

Firefox

### Browser Version

114.0 (64-bit)

### Build Version

Version: 2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

The banner to save or update existing site logins now has the ability to prompt you to save, and if the vault is locked, to prompt you to unlock before saving the entry for you. 

Why are you being prompted to save the website as a new entry, despite already having it saved? Essentially, everything in your vault is encrypted while the vault is locked, including your vault entry URLs, which results in the extension not knowing that the website you're using is already saved.

Our development team is looking into ways to improve this functionality, or at least, consider an option to disable that particular feature. I'd recommend providing feedback in our Community Forum thread about this feature here: https://community.bitwarden.com/t/save-password-while-vault-is-blocked/36114/9

In particular, we'd be interested in hearing about how you're logging into websites if you're leaving the extension locked while doing so. It's possible that there's a use case that hasn't been considered, and your feedback would be very much appreciated.

In the meantime, the best workaround is to check the following options in your extension under Settings > Options:


![aaa](https://github.com/bitwarden/clients/assets/36608718/3c993264-cf5b-496a-9f9d-24d4c5de84fa)


Please note that by disabling those options, you'd need to manually add/update passwords for your sites.

Thank you for your feedback, and if there's anything else I can do for you, please let me know!
