### ISSUE TITLE
Browser extension does not autofill form if proxy requires authentication

### ISSUE THREAD

**Issue by MatteoR23** [bitwarden/clients#5643]
### Steps To Reproduce

1. Connect to a network with a proxy that requires HTTP basic authentication
2. Wait for prompt in a browser (Chrome in my case) with bitwarden add-on unlocked

### Expected Result

The prompt should not appear, unless first proxy authentication is failed

### Actual Result

The prompt appears and it's empty, and I have to fill it manually everytime

### Operating System

Windows

### Operating System Version

Windows 11 22H2 build 22621.1848

### Web Browser

Chrome

### Browser Version

114.0.5735.134

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

I have passed this issue to our QA team for further investigation.

**Comment by MatteoR23** [comment]
Hello,

do you have any news on this?

Thank you very much.
Matteo

**Comment by Krychaz** [comment]
Hello there,

The issue has been vetted and passed to our QA team where it is currently being investigated.

**Comment by MatteoR23** [comment]
Thank you very much!

**Comment by MatteoR23** [comment]
Hello there,

Any news?

**Comment by MatteoR23** [comment]
Closed since it's stale
