### ISSUE TITLE
Flatpak Desktop Program Doesn't Allow Selection of Server Before Login

### ISSUE THREAD

**Issue by AncientMicrowave** [bitwarden/clients#5655]
### Steps To Reproduce

1. Open the Bitwarden Flatpak program on Linux
2. Click on File to set custom server
3. Settings menu is grayed out

### Expected Result

I expected to be able to open the File menu to set my own server where my password database is contained.

### Actual Result

The settings menu is grayed out, presumably pending login

### Screenshots or Videos

![Screenshot from 2023-06-21 22-33-00](https://github.com/bitwarden/clients/assets/81876730/c9831dd1-8961-4a9c-8454-c6105c0c2a47)

### Operating System

Linux

### Operating System Version

Linux Mint 21.1

### Installation method

Other

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
@AncientMicrowave thanks for this report.

For the information of anyone coming across this in the future, the Flatpak package is not supported or built by Bitwarden:
https://flathub.org/apps/com.bitwarden.desktop

The official Bitwarden apps are listed at our Downloads page:
https://bitwarden.com/download/
