### ISSUE TITLE
Doubt about current security of authentication protocol and master password protection

### ISSUE THREAD

**Issue by bitwarden-question** [bitwarden/clients#5673]
### Steps To Reproduce

Hello!

By looking at the implementation and the available documentation i read that argon2id is only used for deriving the key used to decrypt the keychain but that pbkdf2 is still used for authentication.

would you please clarify which is the added value of using argon2id if the server still stores an hash of the key? What does present an attacker seizing the server to run a bruteforce attack on pbkdf2?

Thank you so much for your work!!

### Expected Result

...

### Actual Result

...

### Operating System

Windows

### Shell

Bash

### Build Version

-

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bitwarden-question** [comment]
Thank you.

Actually i've read the whitepaper.
Authentication seems to be made deriving a key from the user password using pbkdf2 and the hash is save on the server.
Encryption keys are encrypted  with a key derived from the same password using argon2id

In my opinion regardless argon2id is used, the security remains the security of pbkdf2. 

What am i missing?

**Comment by djsmith85** [comment]
Hi @bitwarden-question and thank you for your interest in Bitwarden. 

As @bwbug has mentioned, we use GitHub issues as a place to track bugs and other development-related issues, and has also pointed to other places where this discussion would be better suited. 

I'm closing this now.

Kind regards,
Daniel
