### ISSUE TITLE
Prompt to save new login credentials silently drops data on network error

### ISSUE THREAD

**Issue by sdht0** [bitwarden/clients#5677]
### Steps To Reproduce

1. Go to a website and create a new account with user name and self generated password.
2. Click "Save" when prompted to save login credentials.
3. (Internet connection issues)

### Expected Result

I know offline edit is not available yet, so Bitwarden should show an error warning the user that credentials could not be saved.

### Actual Result

Credentials are silently dropped. Later it'd be very surprising that credentials were not saved and the user would not be able to login again without resetting the password.

### Additional Context

I am self hosting the server and it was down, but I imagine this issue will occur even normally if the Bitwarden server is inaccessible.

### Operating System

Linux

### Operating System Version

Archlinux

### Web Browser

Firefox

### Browser Version

115.0b8

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @sdht0,

Thank you for your report; I was able to reproduce this behaviour, and I have flagged it to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,
