### ISSUE TITLE
Unable to import data "cannot import this much data at once."

### ISSUE THREAD

**Issue by githubtar** [bitwarden/clients#5679]
### Steps To Reproduce

1. Export data from Roboform to .csv
2. https://vault.bitwarden.com/#/tools/import

### Expected Result

Import that data

### Actual Result

Import error
There was a problem with the data you tried to import. Please resolve the errors listed below in your source file and try again.

You cannot import this much data at once.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

Version 2023.5.0 

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @githubtar this is currently expected as a single import is limited in the following ways:

Individual vault import:
6000 items
1000 folders
6000 folder-item relationships

Individual vault import:
6000 items
1000 collections
6000 collection-item relationships

Please check your import file for any of the above-mentioned limitations. Alternatively, you can split/chunk the csv-file into multiple imports.
