### ISSUE TITLE
Bitwarden MacOS App 2FA Panel Frozen

### ISSUE THREAD

**Issue by bhjolly** [bitwarden/clients#5680]
### Steps To Reproduce

1. Start Bitwarden
2. Enter username
3. Enter password
4. 2FA step shows a Duo panel (as expected), but I can't click on anything in it (push button, enter code text box, enter code button, links to Duo help, etc)

<img width="959" alt="image" src="https://github.com/bitwarden/clients/assets/15041759/d0d5d5d8-6ad6-43a8-8edb-6a47be5d47ae">

### Expected Result

Being able to use Duo 2FA to authenticate

### Actual Result

Unable to use Duo 2FA to authenticate

### Additional Context

MacOS just updated to Ventura 13.4.1

### Operating System

macOS

### Operating System Version

13.4.1

### Installation method

Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment]
Hi there @bhjolly 

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by klhtxt** [comment]
I am also seeing this issue and found this ticket after a Google search on "Bitwarden Duo cannot click on login screen Mac". To add to the original ticket, the only clickable links on the 2FA popup are the "Remember email" checkbox and the "Cancel" button; as noted, nothing else is clickable.

I did want to add that the Firefox Bitwarden extension is working properly with Duo 2FA on the latest MacOS and Firefox versions.

**Comment by bsod-haunted** [comment]
I'm running into this issue to.

Operating System
macOS

Operating System Version
12.6.7 (21G651)

Installation method
Mac App Store

Build Version
Version 2023.5.1 (9424)

**Comment by klhtxt** [comment]
I found a nice workaround. I wanted to see if the issue had been fixed as of July 6, and it's not, but for some reason I figured let me try the tab key to see if I could get access to at least select the option I wanted, and that worked. 

SO, if you cannot click on the Bitwarden Duo 2FA screen on your Mac, use the tab key and continue to tab until you get the Duo Push option and then hit enter, you will get the Duo push on your phone!

**Comment by bhjolly** [comment]
Awesome, good tip, thanks!

@SaabirahMohamed are there any progress updates available?

**Comment by cooeyau** [comment]
Thanks for the tab tip lol cant believe I did not think to do that hahahaha, I do it every where else 🤦

**Comment by stride314** [comment]
MacOS just updated to Ventura 13.4.1
Operating System

macOS
Operating System Version

13.4.1
Installation method

Mac App Store
Build Version

2023.5.1

 I've got the same issue.  Thanks for the workaround klhtxt.

**Comment by aj0413** [comment]
add me to list of people running into this :/

**Comment by gravshort** [comment]
I'm also encountering this issue on:

- a 2020 M1 MacBook Air
- running MacOS Ventura 13.4.1
- with a freshly installed Bitwarden 2023.7.0 (9969).

Thanks klhtxt for the workaround.

**Comment by jdg0928** [comment]
@klhtxt Great call on the workaround. Not having biometrics was super annoying!

+1 to having the issue

Hardware: **MacBook Pro 14-inch 2021 (M1 Pro)**
OS: **macOS 13.4.1 (c) (22F770820d)**
Bitwarden app: **Version 2023.7.0 (9969)**

**Comment by bujordan** [comment]
+1, same issue, 
OS: macOS ventura 13.4.1(c), 
hardware: Macbook Air M2
Bitwarden App: 2023.7.0 (9969)

was able to use the tab workaround but c'mon, not being able to log in via 2FA for a password app is not confidence-inspiring, and neither is the fact that this issue was opened a month ago. If a simple and rather obvious UI bug makes it past testing..what else is slipping by?

**Comment by ryusko2** [comment]
+1 
same issue _except_ when I tab to get the push, I always get "An error has occurred. Expired Authorization" and I can't log in anyway :(
Bitwarden Desktop app completely broken for me :(

OS: macOS Big Sur 11.7.9
hardware: Macbook Pro 2017
Bitwarden 2023.7.0 (9969)

**Comment by mattijsf** [comment]
+1

OS: 13.5 (22G74)
Hardware: Apple M1
Bitwarden: 2023.7.0 (9969)

**Comment by eighteentee** [comment]
+1

Still occurring on 13.5, Apple M1 Max, Bitwarden 2023.7.0

**Comment by zacbre** [comment]
bump. I am running into this on a M1 Macbook Air, 13.4.1.
