### ISSUE TITLE
Bitwarden window rule set to "keep above others" by default on Kubuntu 22.04

### ISSUE THREAD

**Issue by Matthis-M** [bitwarden/clients#5691]
### Steps To Reproduce

1. Download Bitwarden Linux desktop client AppImage
2. Execute the AppImage

### Expected Result

Bitwarden opens normally with default windows behavior.

### Actual Result

Bitwarden opens and its window is always set as "keep above others" by default.

### Screenshots or Videos

![Peek 27-06-2023 15-44](https://github.com/bitwarden/clients/assets/23255646/d366aef0-f22b-4458-b9ce-632bc27d2547)

### Additional Context

- The "keep above others" option can be deactivated normally but will be reactivated next time the application is started
- The only way I found to override this behavior is to modify the "Window Rules" and set the "keep above others" option to "no" with "forced" behavior. The drawback is that the option is then unusable in all situations:
![image](https://github.com/bitwarden/clients/assets/23255646/44a951be-64d5-4475-92b6-73e453e75492)

(sorry my system is configured in French, I can add a translation if that could help).

Even though it is really not critical, I report this issue since I guess it isn't a wanted behavior.
Thank you for your work and let me know if you need more information!

### Operating System

Linux

### Operating System Version

Operating System: Kubuntu 22.04 KDE Plasma Version: 5.24.7 KDE Frameworks Version: 5.92.0 Qt Version: 5.15.3 Kernel Version: 5.19.0-45-generic (64-bit)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.5.1 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rrrrrraa** [comment]
I am using Kubuntu 24.04 KDE/Plasma and I have this same issue. I am always turning off the "keep above others" window option, but each time I restart the app it is enabled again.

Version 2025.1.2
SDK 'main (28c7e29)'
Shell 33.2.1
Renderer 130.0.6723.137
Node 20.18.1
Architecture x64
