### ISSUE TITLE
Bitwarden don't copy passwords in Linux

### ISSUE THREAD

**Issue by rl13ce** [bitwarden/clients#5716]
### Steps To Reproduce

1. Use OpenSUSE Leap 15.5 or NixOS
2. Install flatpak
3. Add flathub to the user side
4. Install bitwarden in userwide flathub
5. Set minimize when copy passwords to the clipboard
6. Try to copy a password with the button to do so.

### Expected Result

Password in the clipboard, and window minimized

### Actual Result

Nothing in the clipboard and window minimized

### Operating System

Linux

### Operating System Version

OpenSUSE Leap 15.5

### Installation method

Other

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @rl13ce , 

Thank you for your bug report.

I am afraid that the flatpak distribution is not supported by Bitwarden:
https://flathub.org/apps/com.bitwarden.desktop

As such, I am afraid that I am unable to investigate this report any further.
