### ISSUE TITLE
Clipboard not cleared when closing the application

### ISSUE THREAD

**Issue by ioqy** [bitwarden/clients#5717]
### Steps To Reproduce

1. Go to a login item
2. Click on copy username or password
3. Close the application

### Expected Result

Clearing of the clipboard, like the timer or locking of the vault does.

### Actual Result

The copied usrname or password stays in the clipboard.

### Additional Context

The windows clipboard history is not active.

The clipboard is cleared like expected when the timer runs out or the vault is locked either automatically or manually via the menu or the keyboard shortcut.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 22H2

### Installation method

Microsoft Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@ioqy You previously reported this with https://github.com/bitwarden/clients/issues/3117

Please check before creating new issues.

Closing this now.

**Comment by ioqy** [comment]
@djsmith85 I know. But my old issue is stale for a year now and no one cares or even looked into the issue. What else should I do?
