### ISSUE TITLE
Don't allow establishing 0 length PINs by accident

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#5726]
### Steps To Reproduce

They said https://community.bitwarden.com/t/dont-allow-establishing-0-length-pins-by-accident/55846 is a bug.

### Expected Result

Please see the above URL.

### Actual Result

Please see the above URL.

### Screenshots or Videos

Please see the above URL.

### Operating System

Linux

### Web Browser

Chrome

### Build Version

Newest on Chrome store.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @jidanni,

Thank you for your report. I was able to reproduce this and have flagged it to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thank you again,

**Comment by arnabrahman** [comment]
@SergeantConfused By reproducing the bug, did you mean this?  I didn't type a pin & pressed `ok`. And when I click `Lock now`, it shows me this, which is unexpected as I didn't give a pin. If this is the issue, then I can work on this.
![Screenshot from 2023-07-09 22-23-11](https://github.com/bitwarden/clients/assets/12469224/ccb41c2b-4560-4fe1-8c93-08112978e0dd)

**Comment by jidanni** [comment]
Yes. Users can accidentally create null pins that can never be used.

**Comment by arnabrahman** [comment]
I have opened a PR for this.

**Comment by prithvi2k2** [comment]
> I have opened a PR for this.

Can you please mention this issue in your PR or put a link to navigate

**Comment by SaunakNandi** [comment]
Hi Newbie here, Does this issue still exist?

**Comment by targatonica** [comment]
Hi, is this issue still available?

**Comment by jidanni** [comment]
I don't know if the problem still exists, because my computer is not at home right now.
