### ISSUE TITLE
SweetAlert2 loads Ukraine anthem

### ISSUE THREAD

**Issue by DarkCat09** [bitwarden/clients#5734]
### Steps To Reproduce

SweetAlert2 loads ukraine anthem if browser language is set to Russian or web vault is hosted on RU/РФ domain.  
It is used as dependency: https://github.com/bitwarden/clients/blob/master/package.json#L198

See also https://github.com/dani-garcia/bw_web_builds/issues/132

I've downloaded the latest release of web vault and checked with grep:
```
$ grep -i -o -r ukraina.mp3 build/
build/app/vendor.d6556a6abd8a862bb28c.js.map:Ukraina.mp3
build/app/vendor.d6556a6abd8a862bb28c.js:Ukraina.mp3
```

### Expected Result

Expected Result: no politics.

### Actual Result

Actual Result: error while loading ukraine anthem in DevTools console.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

v2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by DarkCat09** [comment]
I've read the conversation in https://github.com/bitwarden/clients/pull/5011 and the related issue https://github.com/bitwarden/clients/issues/4540, and now I don't think that developers will do anything...

**Comment by pepa65** [comment]
Definitely switch to Vaultwarden...

**Comment by atjbramley** [comment]
Hi @DarkCat09, 

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Tipoff4317** [comment]
https://github.com/sweetalert2/sweetalert2/commits/c4dd5dcaf08e24c334f4ce62079d3234f193b2d9/README.md

* 2022-11-24 Became a protestware, disabling plugin for the `.ru`, `.su`, and `.рф` domain zones and playing Ukrainian national anthem
* 2023-06-06 Added .by domain zone to the above

**Comment by DarkCat09** [comment]
@atjbramley,

Thanks for your fast response.

If you are not going to use another JavaScript library, take a look at https://github.com/lofcz/sweetalert2-neutral

**Comment by Hinton** [comment]
Hi @DarkCat09,

I've looked into the issue, and Bitwarden does not use a vulnerable version of SweetAlert2. We've intentionally not upgraded to newer major versions to avoid this issue.

I took a quick look at VaultWarden's build process, and they run `npm audit --fix` which seems to bump SweetAlert2 to a new major version. Since Bitwarden does not provide support for unofficial builds this issue will be closed.

**Comment by DarkCat09** [comment]
Here is the SHA256 sum of the release file I downloaded:
```
d918f0f8cbddc398353dddaac7821322fba4f33c722c8821a8c9132e6df53f57  web-2023.5.1-selfhosted-open-source.zip
```

**Comment by DarkCat09** [comment]
SweetAlert2 10.16.1 specified in package.json was released before 24.02.2022, so there should be no malicious code. But there is (at least, in the pre-built web vault).

**Comment by DarkCat09** [comment]
**GitHub Actions build-web config:**

https://github.com/bitwarden/clients/blob/db2427e05c46c0ba5f77cacebba2c82c7c3b2421/.github/workflows/build-web.yml#L73-L76

https://github.com/bitwarden/clients/blob/db2427e05c46c0ba5f77cacebba2c82c7c3b2421/.github/workflows/build-web.yml#L122-L124

***

**Build command in apps/web/package.json:**

https://github.com/bitwarden/clients/blob/db2427e05c46c0ba5f77cacebba2c82c7c3b2421/apps/web/package.json#L18

**Comment by DarkCat09** [comment]
That's weird. Where CI updates packages?

**Comment by Hinton** [comment]
I took a second look and you are right, it seems the dependency was updated to a newer patch release recently which seems to bring in this issue. We're partially in the process of replacing SweetAlert2 with our own dialogs already though.

**Comment by DarkCat09** [comment]
@Hinton, I'm sorry to bother you, but could I ask are there any progress?

I still see swal2 in package(-lock).json, `grep` still finds "ukraina.mp3" in the latest web vault build.

If rewriting UI to custom dialogs takes much time, why don't use [`npm i sweetalert2-neutral`](https://github.com/lofcz/sweetalert2-neutral) for now?

I moved to KeePassXC + Syncthing, because I didn't want to wait for the fix and realized that serverless password storage is more secure. But I just want to be sure that Bitwarden does **not** support neither Ukraine, nor Russia, so I'll be glad to hear about updates on removing sweetalert2.

**Comment by sguryev** [comment]
It has taken 2 months to remove MIR options (request: https://github.com/bitwarden/clients/pull/5011 and PR: https://github.com/bitwarden/clients/issues/4540)
2 months has been passed for this issue to remove Ukraine anthem 🤞🏼

**Comment by sguryev** [comment]
Does it mean that workaround is to block flag-gimn.ru domain completely and ignore console errors and missing allerts?

**Comment by DarkCat09** [comment]
@sguryev, also, you need to start a script that reverses `pointerEvents = "none"`, i.e.
```js
window.addEventListener('load', () => { document.body.style.pointerEvents = "auto" })
```

But I hope this will be fixed soon.

**Comment by yanalunaterra** [comment]
[v2023.5.0](https://github.com/bitwarden/clients/releases/tag/web-v2023.5.0) is the earliest release affected.

**Comment by limonte** [comment]
Thank you for years of using my small OSS plugin <3 and apologies for bringing this hassle to your project.

I hope to see one day that Bitwarden Inc. stands with Ukraine ([something similar to this](https://www.atlassian.com/blog/announcements/atlassian-stands-with-ukraine)). Not restricting your service to ruzzians might negatively affect the reputation of the business.

Sincerely, happy Bitwarden user and the author of @sweetalert2

**Comment by sguryev** [comment]
@limonte 
> Not restricting your service to ruzzians might negatively affect the reputation of the business.
Is it the threat?

**Comment by reysonk** [comment]
> Not restricting your service to ruzzians might negatively affect the reputation of the business.

Look around when you walk in the evenings.
