### ISSUE TITLE
Improper region handling during login

### ISSUE THREAD

**Issue by FedericoCioschi** [bitwarden/clients#5738]
### Steps To Reproduce

1. Open the Linux Desktop application (tested on both AppImage and Snap builds). Also, you must already have a logged-in account pointing to a "self-hosted" (on-premise) region.
2. Now you want to login to another account on the US region. So you set the Region Flag to "US".
3. Enter master password or "login with another device"
4. Enter 2FA

### Expected Result

App logs in without any issue.

### Actual Result

Login succeeds but app immediately logs out since "session expired".

### Additional Context

I think this problem is strongly related to the region flag set by the user at the beginning of the login process.
I was able bypass this issue by setting a self-hosted region with an empty server URL. In this way the client automatically sets the region to US (for real this time!) and the login succeeds without any immediate logout.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

Other

### Build Version

Versione 2023.5.1 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @FedericoCioschi, 

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by trmartin4** [comment]
Hi @FedericoCioschi.  This issue will be resolved in the upcoming desktop release.  Thank you for your help in identifying and scoping it for us.
