### ISSUE TITLE
The Remember me toggles for the 2FA stage in the desktop clients and browser extensions do not work.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#5771]
### Steps To Reproduce

1. Open the Bitwarden desktop client or browser extension.
2. Enter your email address and master password.
3. Toggle the (Remember me) function during the 2FA stage, and complete 2FA.
4. Log out.
5. Log in anew.

### Expected Result

To be able to log in using your email address and master password only.

### Actual Result

You are asked for your email address, master password, and 2FA.

### Screenshots or Videos

N/A.

### Additional Context

N/A.

### Operating System

macOS

### Operating System Version

13.4.1

### Installation method

Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarcelMWS** [comment]
Could you kindly address this issue? It's quite bothersome

**Comment by wowscortcher** [comment]
Besides being bothersome, the fact that I need to take out the security key from the drawer every time represents a security risk. I can forget it plugged in or I can break it by mistake when crossing by. It's not a tool to wave out like a football flag.

**Comment by MarcelMWS** [comment]
> Could you kindly address this issue? It's quite bothersome

It's working perfectly on my end now! Thanks a lot for fixing this issue. 👍
