### ISSUE TITLE
The error «Two-step token is invalid. Try again.» is returned when trying to log in using SSO + Yubico OTP

### ISSUE THREAD

**Issue by Greenderella** [bitwarden/clients#5788]
### Steps To Reproduce

Preconditions: A user with SSO + Yubico OTP as their 2FA method.

1. Navigate to the web vault and enter the email.
2. Select SSO and complete the flow until reaching the page where the YubiKey is required.
3. Press the YubiKey button and wait.

### Expected Result

User should be logged in.

### Actual Result

The error `Two-step token is invalid. Try again.` is displayed.

### Additional Context

- This was reproduced on Web, Desktop and browser.
- Screen recording is available on the internal issue.

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Safari, Firefox

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here.

**Comment by trmartin4** [comment]
This issue has been resolved.  Users are now able to use their Yubikey 2FA with SSO without issues.
