### ISSUE TITLE
"Inactive two-step login" duplicates entries with more than one URI

### ISSUE THREAD

**Issue by My-Random-Thoughts** [bitwarden/clients#5789]
### Steps To Reproduce

- Using the Web Vault, create a new login vault entry for a site that uses 2FA (github.com for example)
- Add more than one URI
- Go to the reports, Inactive two-step login page

### Expected Result

- Only one entry should be shown.

### Actual Result

- The entry has more than one listing, throwing off the count and confusing users

### Screenshots or Videos

![vw0](https://github.com/bitwarden/clients/assets/21334396/c6a2f0e6-71f6-4cb9-8e2f-4abfaa330665)
![vw1](https://github.com/bitwarden/clients/assets/21334396/2181f909-a20c-45a3-9c82-d4035db49386)

### Operating System

Linux

### Operating System Version

Docker On Synology NAS

### Web Browser

Firefox

### Browser Version

115

### Build Version

Version 2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
