### ISSUE TITLE
Unable to unlock with pin code in edge browser extension

### ISSUE THREAD

**Issue by Sublease3919** [bitwarden/clients#5849]
### Steps To Reproduce

1. Go to bitwarden edge browser extension
2. Click on Settings - check unlock with pin 
3. Set pin and un check Lock with master password on browser restart 
4. Close and restart the Edge browser

### Expected Result

bitwarden edge extension can be unlocked with a pin

### Actual Result

Unlock with pin option is automatically turned off
You will be asked for your master password.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge

### Browser Version

114.0.1823.86

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
@Sublease3919 

Thank you for contacting Bitwarden. 

I attempted to reproduce your issue and was unable to do so. could you reinstall the extension and let us know if the issue persists. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.
