### ISSUE TITLE
Support Chrome Side Panel.

### ISSUE THREAD

**Issue by rokejulianlockhart** [bitwarden/clients#5971]
### Steps To Reproduce

```pwsh
If ($IsWindows) {
	# https://reg2ps.azurewebsites.net/
	If ((Test-Path -LiteralPath 'HKCU:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist') -NE $True) { New-Item 'HKCU:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist' -Force -EA SilentlyContinue }
	New-ItemProperty -LiteralPath 'HKCU:\SOFTWARE\Policies\Google\Chrome\ExtensionInstallForcelist' -Name '1' -Value 'nngceckbapebfimnlniiiahkandclblb' -PropertyType String -Force -EA SilentlyContinue }

ElseIf ($IsLinux) { Start-Process 'https://bitwarden.com/help/getting-started-browserext/' }


```

### Expected Result

Bitwarden should be available in the Side Panel.

### Actual Result

It is not.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/42837531/efc1fa82-2ee5-4d09-b7da-f2ceb4b763a7)

### Additional Context

https://9to5google.com/2023/05/26/chrome-extensions-side-panel/

### Operating System

Windows, macOS, Linux

### Operating System Version

cpe:/o:opensuse:tumbleweed:20230803

### Web Browser

Chrome

### Browser Version

Version 117.0.5927.0 (Official Build) dev (64-bit)

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rokejulianlockhart** [comment]
https://github.com/bitwarden/clients/issues/5971#issuecomment-1666900513

> We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests](https://community.bitwarden.com/c/feature-requests) section for submitting, voting for, and discussing requests like this one.

https://community.bitwarden.com/t/support-chrome-side-panel/56864?u=rokejulianlockhart

**Comment by image72** [comment]
@djsmith85 hi, master, have any plan support this feature?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/5971#issuecomment-2263320704

@image72, best to ask in response to https://community.bitwarden.com/t/support-chrome-side-panel/56864/1?u=rokejulianlockhart.

**Comment by image72** [comment]
> > [#5971 (comment)](https://github.com/bitwarden/clients/issues/5971#issuecomment-2263320704)
> 
> @image72, best to ask in response to https://community.bitwarden.com/t/support-chrome-side-panel/56864/1?u=rokejulianlockhart.

current not supported sidePanel, do you mean  `[023.7.0 CRX File - Crx4Chrome 9](https://www.crx4chrome.com/crx/31978/)` ?
that almost outdated 1 years ago

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/5971#issuecomment-2263417531

@image72, your syntax is nigh incomprehensible. I suggest you choose a spell checker. Because I can't answer that, I'll elaborate what I meant in https://github.com/bitwarden/clients/issues/5971#issuecomment-2263327463 - this hasn't been and isn't yet supported, so any questions about this FR should directed at the aforementioned URI.

**Comment by image72** [comment]
@RokeJulianLockhart ok, understood. I just tested in latest Chrome browser. 
may official sidePanel API support plan.
& sorry, I'm not good at english.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/bitwarden/clients/issues/5971#issuecomment-2263529934

@image72, no worries. In future, just use your original language, and whoever you're talking to should put it through a translator unless they're incredibly lazy.
