### ISSUE TITLE
Passphrase generator seem broken in 2023.7.0

### ISSUE THREAD

**Issue by invisibleninja06** [bitwarden/clients#6052]
### Steps To Reproduce

1. Run `bw generate --passphrase --words 4`

### Expected Result

Outputs a passphrase like Three-Doggies-Something

### Actual Result

Outputs a random password

Example `xU4ABGf2h5RiP8`

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/56641995/91f5c554-40ad-4fd9-898f-df63a112e7d4)

### Additional Context

This command used to work properly but now seems broken.

I know that 2023.8.0 just came out but the windows download still only gives 2023.7.0 and I see no notes saying this would have been fixed.

### Operating System

Windows

### Operating System Version

Windows 11

### Shell

PowerShell

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by invisibleninja06** [comment]
just tried with 2023.8.2 and same issue

**Comment by rituraj00** [comment]
Hi @invisibleninja06 
I tried replicating the issue but it ran correctly for me 
![Uploading Screenshot 2023-08-31 223128.png…]()

**Comment by rituraj00** [comment]
Hi @invisibleninja06 
I tried replicating the issue but it ran correctly for me 
![Uploading Screenshot 2023-08-31 223128.png…]()

**Comment by rituraj00** [comment]
Hi @invisibleninja06 
I tried replicating the issue but it ran correctly for me 
![Uploading Screenshot 2023-08-31 223128.png…]()

**Comment by invisibleninja06** [comment]
Still not working for me are you using 2023.7 or greater for bw cli?
![image](https://github.com/bitwarden/clients/assets/56641995/ea887c6e-7c5e-4435-a5f6-51759522e13c)

**Comment by rituraj00** [comment]
@invisibleninja06  I used the 2023.8.2 version,
![image](https://github.com/bitwarden/clients/assets/77140528/f8029670-0d33-46fe-b03d-a777b4affe37)

**Comment by rituraj00** [comment]
I tried the bw cli in WSL, PowerShell 7 too, and it worked fine.

**Comment by invisibleninja06** [comment]
Ok so I tried bw cli in sandbox and wsl and both work fine but on my local machine its broken, I completely removed the bw executable (which was installed by winget) and than manually downloaded the latest windows zip and manually added it and the path var and still not generating passphrases.

Really weird but clearly an issue on my machine.
If you have any thoughts on anything i could try I would appreciate them.

**Comment by djsmith85** [comment]
The likely reason for this, is the way that Powershell handles options/arguments.

Unfortunately I do not know if this is a setting or a change introduced in a certain version:

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_command_syntax?view=powershell-7.3

https://stackoverflow.com/questions/15780174/powershell-command-line-parameters-and

**Comment by invisibleninja06** [comment]
The issue occurs in powershell 7, windows powershell 5.1 and cmd so not sure its the arguments per say.

**Comment by invisibleninja06** [comment]
Also it seems like parameters are working in other cases for example I tried generating a long password with only uppercase and lowercase and worked fine
![image](https://github.com/bitwarden/clients/assets/56641995/8f46cab0-b5eb-43d2-b37f-5e18239e7c7c)
