### ISSUE TITLE
Flatpak version does not respect system dark mode

### ISSUE THREAD

**Issue by SlowNicoFish** [bitwarden/clients#6101]
### Steps To Reproduce

1. Start Bitwarden Flatpak on Fedora 38

### Expected Result

Bitwarden to switch to dark mode

### Actual Result

Titlebar gets dark but the app stays in light mode

### Screenshots or Videos

![bitwarden_bug](https://github.com/bitwarden/clients/assets/19305293/6d04145a-3a76-40d0-828a-68d930de16a9)

### Operating System

Linux

### Operating System Version

Fedora 38

### Installation method

Other

### Build Version

Version 2023.7.0 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by quexten** [comment]
The flatpak is an unofficial wrapper. You'll have better luck reporting this issue here: https://github.com/flathub/com.bitwarden.desktop

**Comment by SlowNicoFish** [comment]
https://github.com/flathub/com.bitwarden.desktop/issues/150
