### ISSUE TITLE
Some inactive two-step login recommendations are false/wrong

### ISSUE THREAD

**Issue by koitsu** [bitwarden/clients#6122]
### Steps To Reproduce

# Details

Bitwarden Vault at vault.bitwarden.com has a feature under **Reports -> Inactive two-step login** which lets you review your vault entries to see if 2FA/TOTP could be enabled on a per-site basis.

I've found multiple sites that are recommended to me for 2FA which actually cannot be used for 2FA -- in other words, these recommendations need to be removed.  Justification is provided for each below.

# List of erroneous recommendations

## Kickstarter

Recommendation link per Bitwarden: https://help.kickstarter.com/hc/en-us/articles/115005127094

The recommendation link for Kickstarter claims to support 2FA via TOTP.  **However, I verified tonight that the only option you can select is SMS/text.**  I then went and found documentation from Authy -- https://authy.com/guides/kickstarter/ -- which has screenshots of the semi-old Kickstarter UI.  The radio button labelled "Generate codes with a mobile app" is completely missing.

What MAY be happening is that Kickstarter only shows this option if you're logged in to Kickstarter **using a mobile device** (which I am not), and I am not really willing to try.  But if true, as we all know, there is no technical reason for it; 2FA is universal and has nothing to do with mobile exclusively.

## Wikipedia

Recommendation link per Bitwarden: https://meta.wikimedia.org/wiki/Help:Two-factor_authentication

Wikipedia/Wikimedia only lets you enable 2FA on your Wikipedia account if you are "super special".  Most users and generic contributors **do not** fall into this category.  The referenced instructions tell you to visit https://meta.wikimedia.org/wiki/Special:Manage_Two-factor_authentication (what they call "Special:OATH" -- which is badly named (it should be OAUTH not OATH).  Upon doing so, you will be greeted with this error:

> Unauthorized
> You do not have permission to enable two-factor authentication, for the following reason:
> The action you have requested is limited to users in one of the groups: [Administrators](https://meta.wikimedia.org/wiki/Meta:Administrators), [Interface administrators](https://meta.wikimedia.org/wiki/Meta:Interface_administrators), [Bureaucrats](https://meta.wikimedia.org/wiki/Meta:Bureaucrats), [Oversighters](https://meta.wikimedia.org/wiki/Meta:Oversighters), [Importers](https://meta.wikimedia.org/wiki/Help:Import), [Transwiki importers](https://meta.wikimedia.org/wiki/Meta:Transwiki_importers), [Central notice administrators](https://meta.wikimedia.org/wiki/Meta:Central_notice_administrators), [Global renamers](https://meta.wikimedia.org/wiki/Special:MyLanguage/Global_renamers), [OAuth administrators](https://meta.wikimedia.org/wiki/Meta:OAuth_administrators), [Translation administrators](https://meta.wikimedia.org/wiki/Meta:Translation_administrators), [WMF Office IT](https://meta.wikimedia.org/wiki/Meta:WMF_Office_IT), [WMF Trust and Safety](https://meta.wikimedia.org/wiki/Meta:WMF_Trust_and_Safety), [CheckUsers](https://meta.wikimedia.org/wiki/Meta:CheckUsers).

### Expected Result

n/a

### Actual Result

n/a

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

116.0.5845.111

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @koitsu  thank you for your report.

The list of sites used to compare for the inactive 2FA is provided by 2fa.directory (https://github.com/2factorauth/twofactorauth)

Could you please open a change or pull request there.

Kind regards,
Daniel

**Comment by koitsu** [comment]
@djsmith85 Yep, can do!  On the Bitwarden side, it would useful if the following banner message across that part of the vault site could include a link the 2fa.directory GitHub repository or https://2fa.directory/ (not sure which).  Had I noticed that, I would've not opened a ticket there instead.

In other words, I'd propose changing your messaging to something like this:

> LOGINS WITHOUT TWO-STEP LOGIN FOUND
> We found XXXXX website(s) in your vault that may not be configured with two-step login (according to [2fa.directory](https://2fa.directory/)). To further protect these accounts, you should set up two-step login. To report any inaccuracies with 2fa.directory, please open a [change request on GitHub](https://github.com/2factorauth/twofactorauth/issues).

Thanks!

**Comment by koitsu** [comment]
Actually, the core issue here is that **Reports -> Inactive two-step login** is incorrectly treating https://2fa.directory/ results like a boolean (i.e. "If there's any match in the API/DB, assume it's usable").  The 2fa.directory site itself presents highly relevant information under an "Exceptions/Restrictions" icon.

* Kickstarter: Software 2FA requires setting up SMS 2FA as a fallback.
* Wikipedia: Currently limited to administrators (and users with admin-like permissions like interface editors), bureaucrats, checkusers, oversighters, stewards, edit filter managers and the OATH-testers global group.

As such, Bitwarden should really show Exceptions/Restrictions indicators (and mouseover/hover text) in the "Inactive two-step login" part of the site so that users can make the judgement call from that.

I wouldn't have bothered with this Issue **nor** the other 2 issues (for 2fa.directory) had this information been presented to begin with.

I can/will open a new GitHub issue for that feature request rather than repurpose this one.

**Comment by SergeantConfused** [comment]
Hi @koitsu,

Thank you for your detailed report. In this case, I'd recommend that you join our Community and submit this as a Feature Request/Improvement Suggestion there (https://community.bitwarden.com/c/feature-requests/pm-feature-requests/55).

We use GitHub to track bugs and other development-related issues; This report would remain closed. Please note that the Closed status is for internal tracking purposes only; Please do not hesitate to send us your suggestions via the forums.


Thank you again,

**Comment by koitsu** [comment]
I'm sorry to say I have moved on from BitWarden, however.  Best wishes.
