### ISSUE TITLE
User preferences lost after logout

### ISSUE THREAD

**Issue by fabiobeoni** [bitwarden/clients#6146]
### Steps To Reproduce

1. Go to Account Settings / Preferences
2. Click on Vault Timeout
3. Set custom timeout to 10 min
4. Click on Save

OR...

3. Set "Display full width layout" to true
4. Click on Save

### Expected Result

My preferences are saved and preserved across logout/logins.

### Actual Result

Preferences are lost after logout.

### Operating System

Linux

### Operating System Version

22.*

### Web Browser

Chrome

### Browser Version

Latest

### Build Version

Latest

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @fabiobeoni 

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
