### ISSUE TITLE
Todays monthly update fails on Windows Hello authentification popup

### ISSUE THREAD

**Issue by M0fafahrer** [bitwarden/clients#6159]
### Steps To Reproduce

Program start

### Expected Result

Popup Window Fingerprint for me

### Actual Result

nothing

### Screenshots or Videos

nothing to see

### Additional Context

every couple month the same mess after monthly update 

### Operating System

Windows

### Operating System Version

22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by shoddyguard** [comment]
I'm also seeing this too after just updating today.

In my case I can auth via Windows Hello fingerprint to the desktop app but when using the browser extension for Firefox it doesn't unlock my vault (despite the Windows Hello pop-up appearing and seeming to accept my fingerprint)

**Comment by cili7** [comment]
Same with me.... installed update on both my netbook (Win11) and home pc (Win10) and same problem exists on both systems.
Both use different fingerprint ID hardware, both have same problem.

How do they release an update without checking this first!?!

**Comment by jtodddd** [comment]
Hi there,

Thank you for this report.

We have made some changes to the way that biometrics work in this release.  Please wait until both your desktop app and your client apps are updated to 2023.8.2 - this will restore biometric functionality.

In the meantime, please unlock your client apps using the master password or PIN.

I apologize for the inconvenience.

If your issue persists, after both the desktop app and browser extension are both on 2023.8.2 please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by M0fafahrer** [comment]
Update to 2023.8.3

Problem still exists.

**Comment by ewokee** [comment]
still no more hello login... welll .... very bad

**Comment by M0fafahrer** [comment]
Update to 2023.8.4

Problem still exists.

**Comment by ewokee** [comment]
yeah its ridiculous. but its only about passwords... who in the world would expect a working app there.

**Comment by Macbiz01** [comment]
I have: 
Version 2023.8.4
Shell 24.8.3
Renderer 112.0.5615.204
Node 18.14.0
Architecture x64

Bitwarden consistently launches Windows Hello in the background behind my Chrome browser. Appears to accept fingerprint or PIN but does not unlock the vault or gives a Desktop App communication error even after rebooting the computer. Gets stuck in a loop and will not accept PIN for Desktop app login.

**Comment by xxhh1112** [comment]
q

**Comment by ewokee** [comment]
crazy. combined with their ignorance. a new level... months with no solution

**Comment by M0fafahrer** [comment]
Update to 2023.9.1

Problem still exists.

**Comment by ewokee** [comment]
wow... still nothing. fascinating ignorance

**Comment by M0fafahrer** [comment]
Update to 2023.9.2

Problem still exists.

**Comment by Macbiz01** [comment]
It's working for me now

**Comment by M0fafahrer** [comment]
Update to 2023.9.3

Problem still exists.

**Comment by Tipoff4317** [comment]
@Macbiz01 

> It's working for me now

With desktop app 2023.9.3 and browser addon 2023.9.2?

**Comment by M0fafahrer** [comment]
not for me

**Comment by gaiking-uk** [comment]
Not working for me either on 2023.9.3

I emailed BitWarden support about this 2 weeks ago, they said they would look into it and get back to me but still waiting ☹️

> For the record, in fairness to BitWarden they are usually quite responsive and helpful when you contact them; I think this one just fell through the cracks somehow.

**Comment by Macbiz01** [comment]
2023.9.2

Mike

**Comment by gaiking-uk** [comment]
> 2023.9.2
> 
> Mike

@Macbiz01 -- Did you mean to post this? (It looks like a re-post of your message a week ago) 🤔

**Comment by Tipoff4317** [comment]
> Did you mean to post this? (It looks like a re-post of your message a week ago) 

He answered a question I posted and deleted, realizing I didn't need the answer.

**Comment by M0fafahrer** [comment]
Update to 2024.1.0

Problem still exists.

should be fixed, but it ain't, 

"It's not a bug, it's a feature" 
I've heard it somewhere before !

**Comment by M0fafahrer** [comment]
Update to 2025.3.0

Same problem again.
Was running fine almost one year ;(

**Comment by M0fafahrer** [comment]
Update to 2025.3.0

Same problem again.

Was running fine almost one year ;(
