### ISSUE TITLE
Desktop updates with breaking changes should block until addons are updated

### ISSUE THREAD

**Issue by cunneen** [bitwarden/clients#6185]
### Steps To Reproduce

Using Firefox 117.0 on Mac OS Ventura 13.5.1 (22G90) on an Apple Silicon M1

1. Install BitWarden Desktop 2023.7.0 (the immediate previous release at the time of writing) via the Mac App Store
2. Configure BitWarden Desktop to "Unlock with Touch ID" 
3. Install the Firefox Addon 2023.7.1 from [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/) (the latest Addon at the time of writing)
4. Configure the Firefox Addon to Unlock with Biometrics

This works and is amazing. Thank you!

5. Now update BitWarden Desktop to the latest, 2023.8.2 (11197).
6. Firefox Addon "Unlock with Biometrics" is broken as per #6169 ; no updated Firefox Addon has yet been published via the Firefox Addons site.
    - a zip download is available on the GitHub site but is unsigned by mozilla and hence can't be installed or distributed via normal mechanisms

(Looking at [this comment](https://github.com/bitwarden/clients/issues/6169#issuecomment-1703263963) , this breakage was intentional ?)

### Expected Result

The Desktop update should not have occurred without first checking that installed browser plugins were compatible, or at the very least provided a generic warning to the user that browser plugins would break, allowing the user to defer updating until the browser plugins were ready.

Since so many (most?) users use browser plugins, perhaps Desktop updates with breaking changes should not be published until the various browser plugin channels are all updated (at which point the Desktop app could even automatically direct the user to the appropriate update sites)

### Actual Result

Described in #6169 

### Operating System

macOS

### Operating System Version

Mac OS Ventura 13.5.1 (22G90) on an Apple Silicon M1

### Installation method

Mac App Store

### Build Version

2023.8.2 (11197)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by leftbrake** [comment]
> ### Steps To Reproduce
> 
> Using Firefox 117.0 on Mac OS Ventura 13.5.1 (22G90) on an Apple Silicon M1
> 
>     1. Install BitWarden Desktop 2023.7.0 (the immediate previous release at the time of writing) via the Mac App Store
> 
>     2. Configure BitWarden Desktop to "Unlock with Touch ID"
> 
>     3. Install the Firefox Addon 2023.7.1 from [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/) (the latest Addon at the time of writing)
> 
>     4. Configure the Firefox Addon to Unlock with Biometrics
> 
> 
> This works and is amazing. Thank you!
> 
>     5. Now update BitWarden Desktop to the latest, 2023.8.2 (11197).
> 
>     6. Firefox Addon "Unlock with Biometrics" is broken as per [Biometrics Not Working On Firefox #6169](https://github.com/bitwarden/clients/issues/6169) ; no updated Firefox Addon has yet been published via the Firefox Addons site.
>        
>        * a zip download is available on the GitHub site but is unsigned by mozilla and hence can't be installed or distributed via normal mechanisms
> 
> 
> (Looking at [this comment](https://github.com/bitwarden/clients/issues/6169#issuecomment-1703263963) , this breakage was intentional ?)
> ### Expected Result
> 
> The Desktop update should not have occurred without first checking that installed browser plugins were compatible, or at the very least provided a generic warning to the user that browser plugins would break, allowing the user to defer updating until the browser plugins were ready.
> 
> Since so many (most?) users use browser plugins, perhaps Desktop updates with breaking changes should not be published until the various browser plugin channels are all updated (at which point the Desktop app could even automatically direct the user to the appropriate update sites)
> ### Actual Result
> 
> Described in #6169
> ### Screenshots or Videos
> 
> _No response_
> ### Additional Context
> 
> _No response_
> ### Operating System
> 
> macOS
> ### Operating System Version
> 
> Mac OS Ventura 13.5.1 (22G90) on an Apple Silicon M1
> ### Installation method
> 
> Mac App Store
> ### Build Version
> 
> 2023.8.2 (11197)
> ### Issue Tracking Info
> 
>     * [x]  I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

I literally came here to report this!

**Comment by Moonstone3010** [comment]
> I've found a workaround, thanks to a suggestion from @spreeni151. I'm using Firefox Developer Edition and have temporarily enabled unsigned add-ons by toggling `xpinstall.signatures.required`. Version 2023.8.2 can be downloaded [here](https://github.com/bitwarden/clients/releases/download/browser-v2023.8.2/dist-firefox-2023.8.2.zip).

It's worth noting that this will only work for beta, dev and nightly versions.
I think for those using the standard version of Firefox (release channel), the easiest way is to temporary downgrade the desktop application to the previous version, which you can pick up from here:
[https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.1](https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.1)

**Comment by blxckbxrd** [comment]
Hi @rvsit, thanks for your reply. My thoughts on the Firefox signing process were based on two things. Firstly, the add-on was released on 26 August and seems to be working fine on other browsers now, and secondly, there's chatter I've picked up from other users mentioning delays in Firefox signing add-ons. I could be wrong, and your experience certainly suggests that not all add-ons are treated the same.

I stand by my point that if there are delays, it's not beneficial for developers to slow down their own processes to accommodate them. It doesn't solve the problem, it just allows it to continue.

However, I have no evidence that Firefox is dragging its heels, and there could be something else causing a delay in making the add-on available in vanilla Firefox. I should have been more careful with my opinion. In my defence, two weeks seems like a long time for a signing process, and I really want Firefox and Bitwarden to work well together.

**Comment by cunneen** [comment]
> > I've found a workaround, thanks to a suggestion from @spreeni151. I'm using Firefox Developer Edition and have temporarily enabled unsigned add-ons by toggling `xpinstall.signatures.required`. Version 2023.8.2 can be downloaded [here](https://github.com/bitwarden/clients/releases/download/browser-v2023.8.2/dist-firefox-2023.8.2.zip).
> 
> It's worth noting that this will only work for beta, dev and nightly versions. I think for those using the standard version of Firefox (release channel), the easiest way is to temporarily downgrade the desktop application to the previous version, which you can pick up from here: https://github.com/bitwarden/clients/releases/tag/desktop-v2023.7.1

For anyone hoping that downgrading will solve the issue with "unlock with biometrics" on MacOS, I'm sorry to bring you bad news: only signed MacOS App Store releases support this "unlock with biometrics", and once you've updated the MacOS App Store release, you can't downgrade. So don't bother with the above.

For Firefox users on MacOS (at least), Bitwarden has pushed out half a release, breaking their users' browser add-on with no recourse.

**Comment by Silent-Remux** [comment]
This is an incredibly stupid issue to have and shows a complete lack of competence in the QA process. This should never have happened to begin with.

**Comment by blxckbxrd** [comment]
@Silent-Remux, I don't think this is Bitwarden's fault. The last two versions of the add-on work fine on Firefox Developer Edition. I don't want to put my foot in it again, but it seems to be related to a delay in the add-on signing process, and I don't think Bitwarden has any control over that.

@cunneen, if you want to give it a try, I can recommend Firefox Developer Edition. It's never been unstable for me. The only inconvenience with this version of Firefox is that some telemetry is enabled by default, which is kind of nasty, but you can harden it all away and it will end up being a better browser. You won't have to downgrade your Bitwarden desktop client.

**Comment by cunneen** [comment]
@rvsit I agree. Also, BitWarden could also have released an updated desktop client to revert the problem until the browser extension is ready.

@blxckbxrd thanks you've convinced me to give the developer edition a try.

**Comment by Greenderella** [comment]
We very much appreciate everyone's feedback here, this issue has been resolved, please make sure all clients are updated to version 2023.8.3

The cause of the issue was a version discrepancy and backward compatibility challenge between the extension and the desktop client. The Firefox extension was delayed by the store approval process and resulted in the desktop app being released ahead of the extension. Because of the delay, the desktop client did not have the appropriate key to provide to the old version of the Firefox extension. We will continue to focus our efforts to keep the client releases in sequence.
