### ISSUE TITLE
Mac client will not log in, password screen shows "__$1__" for username

### ISSUE THREAD

**Issue by d-quintal** [bitwarden/clients#6226]
### Steps To Reproduce

Attempting to log in to bitwarden.com using saved email and 2FA (Duo is 2FA method)

1. Open Bitwarden app. Icon shows in menu bar but password prompt does not appear.
2. Click Bitwarden icon in menu bar. Password prompt window appears but displays "Logged in as __$1__ on bitwarden.com."
<img width="1062" alt="bitwarden1" src="https://github.com/bitwarden/clients/assets/30932636/a82cea8d-9a19-4b12-ba3e-60df749e1483">
3. Enter password (remaining behavior is the same regardless of whether password is correct).
4. Click "Unlock".

### Expected Result

1. User opens Bitwarden app
2. Bitwarden login screen pops up, displaying "Logged in as <previously logged in email> on bitwarden.com." and prompting for password
3. When user clicks "Unlock", user receives error message indicating incorrect password or password field empty, or if the password is correct then is logged in to Bitwarden 

### Actual Result

User opens Bitwarden app. The icon appears in the menu bar, but no window appears. User left-clicks the icon to bring up the login window.
When user enters password (correct or incorrect) and clicks "Unlock", the window freezes with "Unlock" button 'pressed' (shaded background, orange border).
<img width="1062" alt="bitwarden2" src="https://github.com/bitwarden/clients/assets/30932636/a26a1de3-18de-472b-87d9-3f481081bc4d">

Once frozen:
* Left-clicking the Bitwarden icon shows/hides the frozen window
* Right-clicking the Bitwarden icon shows menu with "Show / Hide", "Lock vault" (disabled) and "Exit", as expected
* All other menus have all Bitwarden-specific options disabled (only the MacOS defaults like "Window" -> "Minimize" enabled)
* The app will exit cleanly but the issue returns on reopen

Adding a new account in a newly-logged-in (not frozen) app session, using the previously logged in email, solves the problem. It prompts for email and password, then hands off to Duo and returns with a logged in session as expected.

### Operating System

macOS

### Operating System Version

13.4.1 (c) (22F770820d)

### Installation method

Mac App Store

### Build Version

2023.8.3 (11485)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by d-quintal** [comment]
Password length also does not appear to matter. Tested 8-50+ characters.

**Comment by djsmith85** [comment]
@d-quintal; Thank you for your report. 

Could you please try logging out of all accounts or if that does not work deleting the [existing data.json](https://bitwarden.com/help/data-storage/#on-your-local-machine). This seems like an issue with some corrupted data on launch. This would also explain why a second login with the same account works

**Comment by d-quintal** [comment]
No way to reproduce since it's already resolved. Sorry.

If you have steps to reproduce, I'm happy to try it out!

/dq

**Comment by d-quintal** [comment]
So no attempt to address the underlying bug at all??

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
