### ISSUE TITLE
BitWarden Windows client resets scrollbar after idle for some time

### ISSUE THREAD

**Issue by koitsu** [bitwarden/clients#6247]
### Steps To Reproduce

1. Launch the BitWarden desktop app
2. Pick a folder and scroll the item list scrollbar down to the very bottom (you must have many items for this to work)
3. Switch focus to some other application and do whatever you want
4. Wait some time -- I have yet to figure out how long to wait.  **Yes, this matters tremendously!**  The problem is not quickly reproducible, and I have not managed to figure out the exact interval at which this happens
5. Restore focus to the BitWarden client (click on it, alt-tab to it, whatever)
6. Start to do something with the items present in the list (scrollbar still at bottom) -- suddenly, its as if the item list refreshes, and the scrollbar is back at the top

### Expected Result

See Steps to Reproduce

### Actual Result

See Steps to Reproduce

### Screenshots or Videos

I can probably make one of these if desired, but two major problems:

1. The odds of me disclosing information in my Vault(s) is very high and I don't think that's a very smart thing to do
2. Because I have yet to be able to determine the interval of time required for this to happen, for all I know the video could be 30 minutes long

I hope/pray one of your developers knows what kinds of "background tasks" there are in this client which might affect/trigger the items list to refresh in such a way that the scrollbar is reset to the top.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 22H2, OS build 19045.3324

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @koitsu,

Thank you for your report. I was able to reproduce this after waiting 30 minutes, and I have flagged it to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.


Thank you again,

**Comment by koitsu** [comment]
Glad I could help.  I'm sorry to say I have moved on from BitWarden, however.  Best wishes.
