### ISSUE TITLE
Anthem of Russian Federation doesn't play in Donetsk and Lugansk regions, also Kiev

### ISSUE THREAD

**Issue by asand3r** [bitwarden/clients#6256]
### Steps To Reproduce

1. Went to Donetsk or Lugansk regions
2. Set your browser to Russian language
3. Russian anthem doesn't play =(

### Expected Result

Russian anthem playing and everybody stands to hear it. Optionally, everyone sings.

### Actual Result

Nothing happening

### Operating System

Linux

### Operating System Version

Astra Linux 1.7.4 Smolensk

### Web Browser

Chrome

### Browser Version

Version 116.0

### Build Version

5845.179

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by asand3r** [comment]
Related to #5734

**Comment by Hinton** [comment]
Closing this.

**Comment by asand3r** [comment]
Why?.. It's not fair. =(
