### ISSUE TITLE
MS Edge Crashing / Running out of memory after Bitwarden extension ver.2023.9.0 update

### ISSUE THREAD

**Issue by fara99** [bitwarden/clients#6347]
### Steps To Reproduce

1. Go to www.seznam.cz with Bitwarden extension enabled
2. Keep the tab open in background / scroll the site for a while

### Expected Result

Not to crash the browser with extension enabled

### Actual Result

Very high cpu usage and memory leak eventually leading to a browser crash or out of memory error. Does not happen on all sites. Happens every time on www.seznam.cz

### Screenshots or Videos

![bitwarden](https://github.com/bitwarden/clients/assets/22475372/3279a07c-0836-4f3c-a64b-a7011c2f7e0a)

### Operating System

Windows

### Operating System Version

22H2 22621.2283

### Web Browser

Microsoft Edge

### Build Version

117.0.2045.31

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: [https://bitwarden.com/help/data-storage/#on-your-local-machine](https://bitwarden.com/help/article/data-storage/#on-your-local-machine)

**Comment by cagonzalezcs** [comment]
A fix for this issue has been tested and will be released soon. 

https://github.com/bitwarden/clients/pull/6348

I'm closing this issue now, but if other problems arise please let me know.
