### ISSUE TITLE
Localization error in de_de identity card drivers license number

### ISSUE THREAD

**Issue by BingeCode** [bitwarden/clients#6388]
### Steps To Reproduce

In the macOS client, create new identity, see field drivers license number (_Führerscheinnummer_ in German).
In the Browser extension (Chromium) it is translated as _Lizenznummer_ (which translates to license number, which is not the correct term in German - it's too generic).

### Expected Result

It should read _Führerscheinnummer_ as well in the browser extension

### Actual Result

It reads _Lizenznummer_

### Operating System

macOS

### Web Browser

Brave

### Build Version

Version: 2023.8.3  Server-Version: 2023.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @BingeCode thank you for your report.

We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌
Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/#localization-l10n) for further information.

Here are the links to the specific translation across our clients:

https://crowdin.com/translate/bitwarden-browser/26/en-de#1695
https://crowdin.com/translate/bitwarden-web/58/en-de#2243
https://crowdin.com/translate/bitwarden-desktop/53/en-de#1861

New translations can be added or existing one can be up-/down-voted

Greetings from Germany

Closing this now.
