### ISSUE TITLE
stucks when loading without user interaction when tryin to login

### ISSUE THREAD

**Issue by promiseibe** [bitwarden/clients#6395]
### Steps To Reproduce

4. Click on '...'

### Expected Result

registration screen displays smoot;hly

### Actual Result

it gets stuck in a loading screen without user interaction

### Operating System

Windows

### Operating System Version

6.5.2-arch1-1

### Shell

Bash

### Build Version

Version 2023.8.4 Shell 24.8.3 Renderer 112.0.5615.204 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @promiseibe,

Thank you for your report. You mention that the expected result is "registration screen displays smoot;hly"; However, you also state that "it gets stuck in a loading screen without user interaction" whilst the title is referring to "when tryin to login".

1. Could you please detail the steps that you are taking?
2. How did you install the Bitwarden Linux desktop client on your Arch Linux machine?
3. How did you launch that Bitwarden desktop client?
4. Could you please include screenshot of your entire screen that shows what you see when it's stuck?

Thank you in advance,
