### ISSUE TITLE
Master password re-prompt does not work anymore (Desktop/Firefox Addon/Android App)

### ISSUE THREAD

**Issue by rgbweb** [bitwarden/clients#6406]
### Steps To Reproduce

Note:  I have exactly the same problem in the current Windows Desktop Application, Firefox Addon and the Android App.

1. Go to any entry where the checkbox to re-prompt for master password has been enabled
2. Click on 'Edit' or 'Copy password' or 'Show password' (anything which triggers the password prompt)
3. Enter the correct password in the input field of the prompt dialog
4. Click on 'Ok' or hit 'Enter'
5. ... nothing happens

### Expected Result

The password prompt dialog should close itself and the desired action should be performed.

### Actual Result

Nothing happens. The dialog keeps visible. No error message or something else is shown. The dialog can be closed by using the 'Cancel' button.

In Windows Desktop App the F12 Console shows the following error when I click 'Ok' :
```
ERROR Error: Uncaught (in promise): Error: Invalid parameters.
Error: Invalid parameters.
    at useClass.<anonymous> (crypto.service.ts:244:13)
    at Generator.next (<anonymous>)
    at r (main.js:1:188749)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:456407)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
```

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.8.4
Shell 24.8.3
Renderer 112.0.5615.204
Node 18.14.0
Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @rgbweb

This seems to have previously been reported with https://github.com/bitwarden/clients/issues/6153(Web/browser/desktop) and https://github.com/bitwarden/mobile/issues/2733 (mobile) and fixes have been issued which are included in `2023.9`-release. The release has already been pushed out to the stores and awaiting approval from them. It should be available soon.

This issue will now be closed.

Thanks!
