### ISSUE TITLE
Desktop use sensible defaults

### ISSUE THREAD

**Issue by juniz-dm** [bitwarden/clients#6411]
### Steps To Reproduce

1. Install Bitwarden
2. Check defaults, two immediadetly come to mind: 
 - Clear clipboard: "Never"
 - Vault timeout: "On Restart"

### Expected Result

Clear Clipboard within a reasonable time. Vault Timeout within a reasonable time.

### Actual Result

Accidental pasting my password everywhere.
No timeout even though this program holds my whole online identity.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/135123717/40cea3df-b7a8-462b-87dc-cc3ebba8f0ee)

### Operating System

Windows

### Operating System Version

10

### Installation method

Other

### Build Version

2023.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
duplicate of #2621

**Comment by juniz-dm** [comment]
No this is not a duplicate



David Messingschlager

IT Admin
[juniz_Energy_balanced_blue.jpg]
***@***.***<https://www.linkedin.com/company/juniz/>
ju:niz Energy GmbH
Einsteinring 43 | 85609 Aschheim
H: +49 (151) 15046657
E-Mail: ***@***.***
Web: www.juniz.com

**Comment by juniz-dm** [comment]
@NovaSilentium this is not a duplicate, please reopen.

**Comment by dm-nm** [comment]
https://github.com/bitwarden/clients/issues/21015
