### ISSUE TITLE
Firefox Extension not connecting to desktop.

### ISSUE THREAD

**Issue by zkanda** [bitwarden/clients#6452]
### Steps To Reproduce

1. Install and login to firefox extension, and allow permission to connect to app outside of firefox.
2. Go to settings and check unlock with biometrics

### Expected Result

It should connect to my desktop application

### Actual Result

It's giving me an error.

### Screenshots or Videos

<img width="467" alt="Screenshot 2023-09-29 at 1 16 05 PM" src="https://github.com/bitwarden/clients/assets/5354184/8d27a0e4-e3a4-4479-9302-f9787c10b3b5">

### Additional Context

It works in Google Chrome

### Operating System

macOS

### Operating System Version

MacOS Sonoma

### Web Browser

Firefox

### Browser Version

118

### Build Version

118.0.1 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Do you have the “Touch ID” box checked in the desktop app settings as well? If so, here are some steps below to follow that should resolve it for you. 

We recommend uninstalling and reinstalling the application to get started (don’t worry, you won’t lose any data: https://bitwarden.com/help/product-faqs/#q-does-uninstalling-or-deleting-my-bitwarden-app-also-delete-my-vault-data).

After that, follow these steps and let me know the results:

1. Open Finder.
2. Press Shift + ⌘ + G 
3. Enter ~/Library/Application Support/Mozilla in the box that appears.
4. Is there a folder named NativeMessagingHosts inside the Mozilla folder?
5. If not, right click, select “New folder” and title it NativeMessagingHosts (it has to be exactly how it is typed here, with the caps and no spaces).
6. Close your Firefox browser.
7. Open the Bitwarden desktop app.
8. Check off the option Enable Browser Integration then back on, and make sure the option Unlock with Touch ID is checked as well.
9. Launch Firefox (ensure in the browser extension Unlock with biometrics is checked also).

If the previous steps don't solve your issue, you'll want to make sure that the “Native Messaging” permission is enabled. It is an optional permission; however, it is required to function on Firefox:
![ff](https://github.com/bitwarden/clients/assets/36608718/35472cc4-2ea9-499e-ab14-24c5515c84b6)

Other users have also reported that disabling the "Run in Private Windows" function from the browser allowed it to connect properly on the next attempt.

**Comment by zkanda** [comment]
I followed the instruction, the folder `NativeMessagingHosts` wasn't there, so I created it, followed the rest and it works now. Thank you, closing this.
