### ISSUE TITLE
Password re-prompt no longer works in browser

### ISSUE THREAD

**Issue by dstmar** [bitwarden/clients#6454]
### Steps To Reproduce

1. Click on browser extension
2. Unlock vault
3. Search for a login with master password re-prompt enabled
4. Attempt to copy password for this login
5. Enter master password when prompted
6. Click OK

### Expected Result

The password re-prompt dialog should check if the password is valid, and either copy the password to clipboard, or give an error if the password is incorrect.  The same also occurs if simply trying to view or edit the login info.

### Actual Result

Password re-prompt window remains open, giving no feedback on-screen.  Looking at the debug console, seeing an error from angular javascript when I click OK on re-prompt window (see attached screenshot)

### Screenshots or Videos

![firefox console](https://github.com/bitwarden/clients/assets/5498292/0f4191a3-6beb-49b4-ab5e-04ed5ba84842)

### Additional Context

Version 2023.7.1 of the Firefox extension did not have this issue.  Running latest docker self-hosted installation of Bitwarden.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

118.0.1

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello this,

We have fixed this with our latest version of 2023.9.1 This version has been released on all platforms. Unfortunately we are still awaiting for Mozilla approval before it will get the Mozilla Store
