### ISSUE TITLE
Can't unlock vault if user tried to unlock it with a wrong password once

### ISSUE THREAD

**Issue by mtaciano** [bitwarden/clients#6472]
### Steps To Reproduce

1. Go to any website
2. Click on the extension (Or Ctrl + Shift + L)
3. Fill the master password input box with a wrong password
4. Click on unlock
5. Fill the master password input box with the correct password
6. Click on unlock

### Expected Result

The vault is not unlocked with the wrong password (error box is shown), and is unlocked after the correct password is given.

### Actual Result

The vault is not unlocked with the wrong password (error box is shown). But after that, the unlock button does not have any effect, even with the correct password, clicking it does nothing.

### Additional Context

The only way to make the button work again is after a browser restart, and the only way to unlock the vault is to input the correct password first try.

### Operating System

Windows, Linux

### Operating System Version

Windows 10, Linux 6.4.12 and Linux 6.5.5

### Web Browser

Firefox

### Browser Version

108 and 108.0.1

### Build Version

2023.8.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Nyabinary** [comment]
Can reproduce here as well as random crashing occurring when I interact with the Bitwarden extension (crashing the whole browser not just the extension) in Firefox Beta & Firefox Nightly

**Comment by mtaciano** [comment]
This is indeed not reproducible in version 2023.9.1, tested on Firefox in Windows 10.
Closing this issue as it was fixed with version 2023.9.1.
