### ISSUE TITLE
Unlock with PIN Option Not Persisting

### ISSUE THREAD

**Issue by crespire** [bitwarden/clients#6495]
### Steps To Reproduce

1. Authenticate the browser addon
2. Change Vault Timeout to 5 minutes
3. Set the option to unlock with PIN and set up with a PIN, leaving default options.
4. Confirm settings
5. Click on "Lock now"

### Expected Result

Extension should prompt to unlock with PIN, as we just set it up.

### Actual Result

Bitwarden asks for Master Password.

### Additional Context

I suspect this has to do with the change to launching new windows on prompts. Something about this change has messed with unlock preferences not persisting.

### Operating System

Windows

### Operating System Version

Windows 10 Pro, 22H2, 19045.3448

### Web Browser

Firefox

### Browser Version

118.0.1

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pwseo** [comment]
Cannot reproduce it here. Using Firefox 118.0.1 on Linux (openSUSE Tumbleweed), extension version 2023.9.1.
Have you tried reinstalling the extension?

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, please try reinstalling your extension and if that does not fix the issue, please contact us at https://bitwarden.com/contact/

Thanks!

**Comment by crespire** [comment]
A re-install seemed to have fixed the issue after also restarting the browser. Thanks @pwseo @Krychaz
