### ISSUE TITLE
Bitwarden extension spam opening new windows on locked credentials

### ISSUE THREAD

**Issue by Ostantia** [bitwarden/clients#6505]
### Steps To Reproduce

1. Go to a web page for which you've saved your credentials and configured bitwarden to ask for the master password to use/modify.
2. It will open a bitwarden extension window multiple times in a row demanding your master password for the configured account, and each time the web page/website is reloaded. (and even if the actual web page isn't the login page)

### Expected Result

Bitwarden just showing how many credentials it has on the visited website, without doing anything more until a login page is shown/login credentials are detected.

### Actual Result

It opens up a window demanding the master password on the website's account, multiple times in a row.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/113256480/d3b8d623-4537-469e-8e7d-59aafa985f9c)

### Operating System

Linux

### Operating System Version

Linux Mint 21.2 Cinnamon

### Web Browser

Firefox

### Browser Version

118.0.1 (64 bits)

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Ostantia** [comment]
An adittion to the topic : 
- The same problem happens on Firefow "118.0.1 (64 bits)" and Opera with Windows 10.

**Comment by pwseo** [comment]
Cannot reproduce this issue on Firefox 118.0.1 with version 2023.9.1 of the Bitwarden extension (using Linux, openSUSE Tumbleweed).

Just to be clear, these are the steps I took (in this order):
1. modified my GitHub entry to require master password reprompt
2. opened a new tab with GitHub, already logged in (ie. with no user/pass input fields): no popups appeared
3. refreshed the page: no popus appeared
4. invoked autofill (via Ctrl+Shift+L and by clicking the entry on the extension): a popup appeared, and rightly so
5. attemped to view the GitHub entry: popup appeared
6. clicked "Edit" while viewing the entry: popup appeared

On this end, popups appeared only when they should have. Perhaps the update isn't the only culprit.
Perhaps try reinstalling the extension or try to reproduce your bug in a newly created Firefox profile with no other extensions.

**Comment by gencer** [comment]
Happening here.

- Windows 11 23H2
- Edge 117.0.2045.47

and

- Windows 11 22H2
- Edge 117.0.2045.47

(To different PCs)

I have few locked (re-prompt for master password) items and when I open their websites EVEN, I'm not in login page at all (For example github.com and I opened this issue page. No login form at all) popups keeps coming and multiple times (Just like the OP says, spamming me)

My Bitwarden is set to only ask master password "on browser restart".

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/6389
