### ISSUE TITLE
Cannot log into Firefox Add-on on Android if email address is not verified (Captcha issue).

### ISSUE THREAD

**Issue by cefiar** [bitwarden/clients#6540]
### Steps To Reproduce

1. Create a new account on bitwarden.com, but do not verify the email address.
2. Install Firefox on Android, then within Firefox install the Bitwarden Add On.
3. Open a tab to a website then go to the > to the right of Add Ons (within the Firefox Settings) and select Bitwarden.
4. Try to log into the above account using the Master Password.
5. Once you click the "Log in with master password" button, an extra screen element appears that is blank (surrounded by red box in attached screenshot), but you cannot log in. Clicking "Log in with master password" again does nothing.

### Expected Result

Either displaying the captcha (in another firefox tab?), or present a message telling the user that they will need to verify their email address before they can use the Firefox Add On. I suspect that this could also be a problem for self hosted setups with any sort of integrated captcha-based system.

### Actual Result

You simply cannot log into the Add On currently until you verify your email. There is no other way to complete the captcha.

The most annoying thing about this is that there is no error presented, so you don't know it's caused by a captcha, nor do you know that verifying your email will solve the problem.

### Screenshots or Videos

![bitwarden-captcha-fail](https://github.com/bitwarden/clients/assets/2454991/21c94c7a-4872-46b6-9142-dfbdb5464716)

I've hidden the login used and obfuscated the real length of the master password in the image. I've surrounded the extra screen element that appears with a red box, to make it obvious what I'm referring to.

### Additional Context

Once you verify the email for the account (eg: logging into the bitwarden.com web vault without the extension, clicking on the dialog to verify your email address and then verifying the email address via the link that bitwarden.com sends you), you no longer get the extra box and you are logged in immediately upon clicking the "Log in with master password" button. It appears to be 100% related to the captcha that appears for verifying the account, as the captcha always appears when you log into the web vault too, until you verify your email address.

Note that doing either of the following does not help or change the situation:
1. Logging into the web vault (and verifying the captcha there), then attempting to log into the Add On.
2. Installing the Bitwarden Mobile client for Android, logging in with it, then attempting to log in with the Firefox Add-on.

### Operating System

Android

### Operating System Version

13

### Web Browser

Firefox

### Browser Version

118.1.1

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @cefiar, 

Thanks for your report!  Please see Bitwarden's stance on the Bitwarden for Firefox for Android Browser Extension here:
https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile

Bitwarden recommends that you use the officially supported Android extension instead.

This issue will now be closed. 

Thanks!
