### ISSUE TITLE
Can't accept emergency access invite when SSO login is required

### ISSUE THREAD

**Issue by skizzerz** [bitwarden/clients#6581]
### Steps To Reproduce

1. Enable the "Require single sign-on authentication" policy.
2. I additionally had SSO configured to use Open ID Connect and member decryption options set to "Trusted devices". I am not sure if this issue is specific to that configuration or if it happens with SSO in general.
3. Invite a non-owner/non-admin organization member to be an emergency contact.
4. That member clicks the link sent to their email and signs in with Enterprise SSO.
5. Invite is not accepted, and there is no way for the member to accept the invite by browsing around the vault.

### Expected Result

Emergency contact invite is accepted upon logging in at step 4, just like it would be when logging in with a master password instead of Enterprise SSO.

### Actual Result

Invite is not accepted, clicking the email link again doesn't work, and there is no UI in the vault to view or accept the invite.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @skizzerz,

Thank you for your report. We were able to reproduce this behaviour and have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by Hinton** [comment]
This should be resolved with https://github.com/bitwarden/clients/pull/5733.

In the meanwhile you can do the following workaround:

1. Login and unlock the vault in a web browser.
2. Copy and paste the accept url into the address bar on the unlocked vault. This should accept the invite without having to go through the login flow again.

**Comment by trmartin4** [comment]
The deep-linking to pre-login URLs has been fixed with #5733.  I'm going to close this issue.  If you continue to have problems please feel free to re-open or enter another issue.  Thank you!
