### ISSUE TITLE
Cannot change email address

### ISSUE THREAD

**Issue by ihesham** [bitwarden/clients#6582]
### Steps To Reproduce

1. Log into Bitwarden 'Web Vault'
2. Go to 'Settings'
3. Click on 'My account'
4. Scroll down to 'Change email'
5. Enter 'Master Password'
6. Enter 'New email' e.g. `***.***@hotmail.com`

### Expected Result

Current email is replaced with New email

### Actual Result

Changing email address is failed!
A message at the upper right corner displays in red:
"An error has occurred. The NewEmail" field is not supported e-mail address format"

### Screenshots or Videos

![Untitled](https://github.com/bitwarden/clients/assets/62292276/b13f4818-2947-4fd4-965a-418e8735c292)

### Operating System

Windows

### Operating System Version

Windows 10 Version 22H2

### Web Browser

Firefox

### Browser Version

118.0.2 (64-bit)

### Build Version

Bitwarden Web Version 2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @ihesham,

Thank you for this report. At which point exactly do you encounter that error message; Do you see it once you press on (Continue) after entering your master password and the new email address, or do you see after you enter the 6-digit code and click on (Change email)?

Thank you in advance,

**Comment by ihesham** [comment]
@SergeantConfused Hi. Thank you for your comment.
Actually the BW account with that issue does not have 2sv enabled. It is secured by the master password only. So I see the error on the page once I press on "Continue" after filling the MP and the new email address.

**Comment by ihesham** [comment]
I just tried now to create a new BW account with the same email address (for which I previously received an error message). 

This time  on the Create account page below the entered email address I received the error ` Input is not an email address` just before filling anything else. Changing the email address in the Create account page resulted in the same message. 

However (strangely), after changing the email address back and forth several times, I could see the message disappears, and the email field accepted in the Create account page. (I didn't go further creating any actual new accounts, everything was tested in the Create account page in the 'email address' field just to check the issue)

Going back again to my original account where I want to change my email, the same error message is received again `An error has occurred. The NewEmail field is not supported e-mail address format`.

**Comment by ihesham** [comment]
The error was not related to Bitwarden.

Unfortunately, the change email address was copied from another app, but it had hidden characters which were not visible. These characters of course was not a correct email address format, which naturally induced the above error.

Everything is OK. The email address was changed successfully.

**Comment by brenneran** [comment]
Have the same issue with the email address @brenner.space

This my private domain. Why I cannot use it? It gives you to register but not to change the master password.
