### ISSUE TITLE
The extension now opens a new window on firefox

### ISSUE THREAD

**Issue by blastrock** [bitwarden/clients#6583]
### Steps To Reproduce

1. Go to a website
2. Press ctrl shift L

### Expected Result

Anything but a new window

### Actual Result

A new window

### Additional Context

First of all, I have seen all the "bug" reports and how this is actually intended behavior. Still I have an issue with this behavior that was not discussed before. Apologies if a new issue is not the correct way to report this, and please point me to the right place.

I have two issues with bitwarden opening a new window. The first one is that my browser is configured to keep the window open when the last tab is closed. So after entering my password for the autofill, the tab closes but the window stays open with my home page.

The second issue is that I use a tiling window manager, so opening a new window (and not a popup) moves all the other windows and is very disturbing.

I saw [this comment](https://github.com/bitwarden/clients/issues/6412#issuecomment-1739853982) pointed as an explanation about the decision, but it doesn't go into details about the programmatic limitations when trying to open the normal extension popup window. Ctrl+shift+U does open the bitwarden window just fine. I am curious about what are those technical limitations and would appreciate more details.

So in the end, I understand that I don't see the whole picture that led to this new window behavior, but I ask that you reconsider your decision. This is a major drawback to me (and possibly other users), considering that even the previous behavior (opening a new tab) was suboptimal. Maybe you could make the behavior configurable?

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

117.0

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @blastrock,

Thank you for your input. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one (https://community.bitwarden.com/c/feature-requests/).

We use GitHub to track bugs and other development related issues; This report will now be closed. Please note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions via the forum.

As a side note, please clarify in your forum post how you've set up Firefox to remain open after the last tab has been closed, and which window manager you're using exactly; This can help in reproduction and testing.


Thank you again,
