### ISSUE TITLE
Ask for Touch ID on launch ignored

### ISSUE THREAD

**Issue by sebsch1337** [bitwarden/clients#6586]
### Steps To Reproduce

1. Go to settings > security
2. Click on "Ask for Touch ID on launch"
3. Restart the App => No Touch ID is asked. You have to click the button "Unlock with Touch ID" manually, which makes the settings option to ask for it useless.

### Expected Result

Touch ID will be asked on launch, without clicking an extra button in launch screen.

<img width="415" alt="image" src="https://github.com/bitwarden/clients/assets/75478893/f14fbc2d-7793-4fb7-829f-1c7652261949">

### Actual Result

I'm not asked for touch ID on launch, instead i have many ways to login.

<img width="439" alt="image" src="https://github.com/bitwarden/clients/assets/75478893/d5265290-cfbd-4c44-bd31-46b8acb729de">

### Operating System

macOS

### Operating System Version

14.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.1 Shell 24.8.5 Renderer 112.0.5615.204 Node 18.14.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @sebsch1337,

Thank you for your report. It seems like it's a duplicate of this one (https://github.com/bitwarden/clients/issues/6134).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thank you again,
