### ISSUE TITLE
It is possible to see password history on logins with "Master password re-prompt" enabled.

### ISSUE THREAD

**Issue by TheCosmic04** [bitwarden/clients#6632]
### Steps To Reproduce

1. Create a login field.
2. Enable "Master password re-prompt".
3. Change the password of the login.
4. By clicking the on "Password history" at the bottom.

(Note: step 2 and 3 can also be swapped)

### Expected Result

It should ask to reprompt the master password to view the password history as "Master password re-prompt" is enabled.

### Actual Result

It shows all previous passwords without asking for a password re-prompt.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @TheCosmic04, 

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by TheCosmic04** [comment]
Hi,

yea I also wanna add that I've also noticed that this bug is also present on the mobile client but I'm not sure if I should make a separate report considering that there is another repository for the mobile client specifically.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/2577

Hi @TheCosmic04,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/2577

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
