### ISSUE TITLE
The "Login with device" button doesn't appear when you try to log for the first time

### ISSUE THREAD

**Issue by adriancuadrado** [bitwarden/clients#6656]
### Steps To Reproduce

1. Install the Bitwarden's plugin in chrome for the first time
2. Enter your email address

### Expected Result

You should be given the option to log in with a device

### Actual Result

The option doesn't appear until you logout and try to log in again

### Operating System

Linux

### Operating System Version

Ubuntu 22.0.4.1

### Web Browser

Chrome

### Browser Version

Version 118.0.5993.88 (Official Build) (64-bit)

### Build Version

Version: 2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @adriancuadrado,

Thank you for your report. Your report appears to be describing the intended behaviour of the software, as outlined here (https://bitwarden.com/help/log-in-with-device/#prepare-to-log-in-with-a-device); If you want this to be changed, it would be considered a feature request and the Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one (https://community.bitwarden.com/c/feature-requests/).

We use GitHub Issues to track bugs and other development related issues; This report will now be closed. 

Thank you again,

**Comment by adriancuadrado** [comment]
Just for reference, here is a link to the Bitwarden's community post to discuss this:
https://community.bitwarden.com/t/login-with-new-device-not-available-on-new-laptop/53959
