### ISSUE TITLE
[macOS] app not loading

### ISSUE THREAD

**Issue by mahoghanij** [bitwarden/clients#6691]
### Steps To Reproduce

1. Click on bitwarden app to open

### Expected Result

App open and shows list of all saved passwords

### Actual Result

Spinning wheel of death.
<img width="1121" alt="image" src="https://github.com/bitwarden/clients/assets/143857081/a7116a94-a88c-46aa-83d8-9213a5485f10">

### Operating System

macOS

### Operating System Version

14.0 (23A344)

### Installation method

Mac App Store

### Build Version

Version 2023.9.3 (12828)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pc-bastler** [comment]
I can confirm this issue.
I also can confirm that the issue was persistent with the previous version of the Bitwarden App (2023.9.1).

The Edge Plugin works fine on macOS Sonoma.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I can confirm this issue is reproducible, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by longbdrdr** [comment]
I also have this issue.  I tried uninstalling and reinstalling the app to no avail.  Very aggravating.  The browser extension still works.  I'm using an Intel Mac with OS Monterrey Ver. 12.7.1

**Comment by marcushanssoninnofactor** [comment]
I have the same issue on Windows 11 with the desktop application. Browser extension works fine.
I've previous had this on an eariler version but uninstalled Bitwarden och installed a new version, but this issue appeared again.

**Comment by SergeantConfused** [comment]
Hello everyone,

Could you please let me know if adjusting the size of the window of the macOS desktop client after it shows the spinning wheel helps? To be clear, you'd hover the mouse cursor over the lower right corner and then make the window larger or smaller.


Thank you in advance,

**Comment by longbdrdr** [comment]
Thanks for the inquiry, but no it does not.  I tried going full screen also
with no change.

**Comment by pc-bastler** [comment]
Also a "no" from me. I tried resizing the windows from all egdes in all directions, no change.

**Comment by RoganGrant** [comment]
I have the same issue. It has persisted for at least 2 weeks now.

**Comment by kk17** [comment]
same issue

**Comment by Amndeep7** [comment]
I'm experiencing the same issue but on 2023.10.1, installed via brew, on macos 13.6.1

**Comment by SergeantConfused** [comment]
Hello everyone,

We received reports that deleting the contents of this folder (~/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden) on macOS and rebooting helped. If anyone tries that, please let me know how it goes.

All the best,

**Comment by pc-bastler** [comment]
Hi,

I do not even have this folder:

￼

**Comment by longbdrdr** [comment]
It works! This suggestion has fixed the issue on my system.  Thankyou.

**Comment by longbdrdr** [comment]
This suggestion has fixed the issue on my system.  Thank you!

D. Eaton

**Comment by RoganGrant** [comment]
@SergeantConfused this fixed my issue as well! Thank you!

@pc-bastler if you are deleting from the command line, beware the space: `~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden`

**Comment by MashMathias** [comment]
As a paying customer for this service I was expecting Bitwarden to fix this annoying bug ASAP. Now several weeks later this issue has still not been resolved. What is going on? Do you expect your customers to fix your problems by temporary workarounds?

**Comment by candlerb** [comment]
Same problem here. Bitwarden was working OK on my old Intel Macbook Pro running macOS 12, but after I upgraded to a Macbook Pro M3 Pro running latest macOS Sonoma 14.1.2, Bitwarden would only show the spinning beachball.

Thanks to finding this github issue, I renamed the folder:

```
mv ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden{,.xxx}
```

Restarting Bitwarden it asked for a new login, and then works fine.

I still have the old folder available if required. The new one is smaller:

```
% du -sck ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden
1196	/Users/brian/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden
1196	total
% du -sck ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden.xxx
2500	/Users/brian/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden.xxx
2500	total
```

The old folder has some files which the new one doesn't. These are the differences:

```
--- /tmp/aaa	2023-12-09 16:29:49
+++ /tmp/bbb	2023-12-09 16:29:45
@@ -1,3 +1,39 @@
+Cache/Cache_Data/001634fec700d35d_0
+Cache/Cache_Data/04ee32ff6681abd5_0
+Cache/Cache_Data/401d6876ce6ce84c_0
+Cache/Cache_Data/45e60f2e73586870_0
+Cache/Cache_Data/4f19701eb7d9cc84_0
+Cache/Cache_Data/6a0196a88a7113a6_0
+Cache/Cache_Data/934c8a69295da830_0
+Cache/Cache_Data/9c0c3396f0833be6_0
+Cache/Cache_Data/a90fe372eac8c294_0
+Cache/Cache_Data/beadaced23014314_0
+Cache/Cache_Data/d3ec92c0856b7a22_0
+Cache/Cache_Data/index
+Cache/Cache_Data/index-dir/the-real-index
+Code Cache/js/index
+Code Cache/js/index-dir/the-real-index
+Code Cache/wasm/index
+Code Cache/wasm/index-dir/the-real-index
+Cookies
+Cookies-journal
+DawnCache/data_0
+DawnCache/data_1
+DawnCache/data_2
+DawnCache/data_3
+DawnCache/index
+GPUCache/data_0
+GPUCache/data_1
+GPUCache/data_2
+GPUCache/data_3
+GPUCache/index
+Local Storage/leveldb/000003.log
+Local Storage/leveldb/CURRENT
+Local Storage/leveldb/LOCK
+Local Storage/leveldb/LOG
+Local Storage/leveldb/LOG.old
+Local Storage/leveldb/MANIFEST-000001
+Network Persistent State
 Partitions/bitwarden/Code Cache/js/index
 Partitions/bitwarden/Code Cache/js/index-dir/the-real-index
 Partitions/bitwarden/Code Cache/wasm/index
@@ -18,8 +54,24 @@
 Partitions/bitwarden/Local Storage/leveldb/CURRENT
 Partitions/bitwarden/Local Storage/leveldb/LOCK
 Partitions/bitwarden/Local Storage/leveldb/LOG
+Partitions/bitwarden/Local Storage/leveldb/LOG.old
 Partitions/bitwarden/Local Storage/leveldb/MANIFEST-000001
 Partitions/bitwarden/Network Persistent State
 Partitions/bitwarden/Preferences
+Partitions/bitwarden/Session Storage/000003.log
+Partitions/bitwarden/Session Storage/CURRENT
+Partitions/bitwarden/Session Storage/LOCK
+Partitions/bitwarden/Session Storage/LOG
+Partitions/bitwarden/Session Storage/LOG.old
+Partitions/bitwarden/Session Storage/MANIFEST-000001
 Partitions/bitwarden/TransportSecurity
+Preferences
+Session Storage/000003.log
+Session Storage/CURRENT
+Session Storage/LOCK
+Session Storage/LOG
+Session Storage/LOG.old
+Session Storage/MANIFEST-000001
+TransportSecurity
+app.log
 data.json
```

**Comment by MicaxJ** [comment]
I can confirm that we have the same problem, we have on three machines, 2 Ventura 13.6.x and one Sonoma 14.x, M1 and M2, as well as the Bitwarden app Version 2023.10.1 (13648) the same problem, a completely "gray" box, via the browser and iOS it works. If I delete the Json file with the path mentioned before, i can log in again.

**Comment by rfog** [comment]
I expected a faster resolution from Bitwarden for pay users.

**Comment by MashMathias** [comment]
You got to be kidding. Have been waiting several weeks for Bitwarden to fix this issue. Then finally there's an update and guess what. The app is still stuck on startup. Version 2023.12.0 on Sonoma 14.2 is still a broken product.

**Comment by rfog** [comment]
I've reactivated my 1Password account and I'm moving away from Bitwarden for second time. I prefer to pay more and have a lot better service.

**Comment by xxxzzz33** [comment]
I also decided to leave Bitwarden. If there is such a problem, then even more serious problems may appear. It’s very surprising that they can’t solve it for 2 months

**Comment by Gandulf78** [comment]
I was considering moving from Enpass to Bitwarden but finally it doesn't seem so robust. I made my choice with Strongbox. Build on Keepass with database stored on my cloud server, not exposed to the internet. I can share it easily with my family. Seems pretty solid.

**Comment by trmartin4** [comment]
Hello. The Engineering team is actively researching this issue.  We would like to gather some information from anyone who would be willing to provide it so that we can more accurately pinpoint the problem.

1. Are there any instances where this recurs for the same account, **even after** clearing the local files referenced in the workaround above?  
2. When you encounter this problem, could you examine the Network tab of the DevTools (View | Toggle developer tools) to see if there are any errors there?

Thank you for your assistance and patience as we work on a resolution to the problem.

**Comment by MashMathias** [comment]
Looks like posting to https://identity.bitwarden.com/connect/token gives error 400. The the application can't login because of the failing token request and we can logout because we are not logged in. Maybe this has made the configuration files  corrupted.

**Comment by MashMathias** [comment]
BTW I managed to fix the problem myself by selecting **Add Account** in the upper right corner. The application then went blank. Then **View->Reload** in the menu and boom I got back to the login. Now everything is back to normal.

**Comment by hiroo916** [comment]
> BTW I managed to fix the problem myself by selecting **Add Account** in the upper right corner. The application then went blank. Then **View->Reload** in the menu and boom I got back to the login. Now everything is back to normal.

 I couldn't find any of the directories or files referenced above to delete.  They just didn't exist.


This worked for me.  It makes no sense but clicking the add account went to black screen and then I quit the app and restarted and it went to the account login screen and then worked normally after that.

**Comment by danielgerigk** [comment]
(I am using a Mac, Sonoma 14.2.1)

For me, killing the `Bitwarden` process solved the issue:
```
ps -p $(pgrep -x Bitwarden)
kill -KILL <PID>
```
After that, the Bitwarden Desktop App started, but there is still no app menu on the top, and the running app is also not shown in the Dock.

**Comment by rrik** [comment]
I had this issue as well on:
Bitwarden mac app 2024.3.0
Sonoma 14.4.1

What worked for me:

click the top right, "+Add account"
close the app
open the app
worked as expected

**Comment by trmartin4** [comment]
Hello @mahoghanij,

We have introduced some significant refactoring of the application initialization logic on the desktop client, and we would like to see if you (or any other reporters) are still experiencing this.

If not, we will close this issue as resolved.

Thank you!

**Comment by longbdrdr** [comment]
Thank you for the follow-up.  The app is doing fine.D. EatonSent from my iPhoneOn Jul 3, 2024, at 17:32, Todd Martin ***@***.***> wrote:﻿
Hello @mahoghanij,
We have introduced some significant refactoring of the application initialization logic on the desktop client, and we would like to see if you (or any other reporters) are still experiencing this.
If not, we will close this issue as resolved.
Thank you!

**Comment by AlecKinnear** [comment]
> I expected a faster resolution from Bitwarden for pay users.
> 
> In my case, I have TWO Bitwarden folders inside Containers:

I had two Bitwarden folders here ~/Library/Containers/ here as well. After deleting both of them and reopening the latest Bitwarden client for macOS (2024.11.2), I was able to access my passwords again. Half an hour of work time lost on this today, solving it. Fifteen minutes, lost once (first encounter), ten minutes lost another time (second encounter). Finally after just under an hour total of wasted work time, the issue is solved.

Not cool, macOS Bitwarden coders.

**Comment by iamhaseebiqbal** [comment]
I am facing the same issue. Safari extension keep showing loading indicator. Mac App works fine.
Tried following but nothing helped so far.
1. Update Safari
2. Update MacOS
3. Removed all Bitwarden related directories under ~/Library/Container
4. Uninstall and re-install Bitwarden

Any idea?

**Comment by nickheller** [comment]
Same issue here too.

Tried all the setps discribed above.

Occured after I updated to macOS 26.2.

**Comment by pamperer562580892423** [comment]
@iamhaseebiqbal and @nickheller I think you should be joining this current issue instead: https://github.com/bitwarden/clients/issues/17399
