### ISSUE TITLE
Importing a password with a \\ sequence from csv removes one \

### ISSUE THREAD

**Issue by LuckyLuke-n** [bitwarden/clients#6725]
### Steps To Reproduce

1. Import passwords from a csv file. In my case one exported by KeePass, imported in NordPass and again exported.
2. One password has to have a sequence of two backshlashes like `my-secret\\password`.

### Expected Result

Expected result is that the imported password in the Bitwarden Vault is `my-secret\\password`.

### Actual Result

- The result of the import process is `my-secret\password`.
- One backslash is missing.

### Operating System

Windows

### Operating System Version

Windows 11 22H2

### Web Browser

Firefox

### Browser Version

119.0

### Build Version

Version 2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @LuckyLuke-n,

Thank you for reporting this. I tested this twice and in both cases the password value (my-secret\\password) in my vault was identical to the one in the .csv file; I suspect that some characters could have been dropped earlier in the process through the Import/Export functions of the other applications that you've used. If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
