### ISSUE TITLE
Organization import failed on CLI 2023.9.1

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#6731]
### Steps To Reproduce

1. Import into organization using CLI

bw import --organizationid xxxx-xxx-xx bitwardencsv 99999143108.csv

Tested importing into the personal vault. It works.

### Expected Result

Imported successfully

### Actual Result

No error message, data is not imported

### Operating System

Linux

### Shell

Bash

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by 73VW** [comment]
I can confirm the bug in V2023.10.0.

I could import a json file with my local version (2023.5.0) but not with the one on a remote server.

I have copied my local `bw` to my home directory on the remote server and I could import the same file without changes.

**Comment by 73VW** [comment]
Tested: 
- 2023.9.0: Same bug
- 2023.8.2: Same bug
- 2023.7.0: No bug

**Comment by djsmith85** [comment]
@sso-bitwarden, @73VW Based on internal feedback this should be resolved with 2024.2.0.

Closing this now. Please feel free to report if this is not resolved after upgrading to 2024.2.

Kind regards,
Daniel
