### ISSUE TITLE
Card expiration date autofills incorrectly on websites using Klarna payment solutions

### ISSUE THREAD

**Issue by Beet4** [bitwarden/clients#6734]
### Steps To Reproduce

90% of all Swedish online retailers use Klarna Payments solutions and recently Bitwarden autofills the card expiration date incorrectly on Klarnas forms. For example 10/2025 is filled as 20/10 when it should be 10/25. This has worked well before, but since some time ago it no longer works.

1. Go to for example https://www.apotea.se/
2. Add something to the cart (Köp)
3. Go to card (Till kassan)
![image](https://github.com/bitwarden/clients/assets/38279393/e4586b63-40a9-47da-a0f7-552e2f8ce63e)
4. Enter some e-mail and postal code and click on Fortsätt
![image](https://github.com/bitwarden/clients/assets/38279393/ac93aa82-fc82-48c5-be12-5650c9501a66)
6. Enter some phone number and click Privatperson (private person)
![image](https://github.com/bitwarden/clients/assets/38279393/8ef6e390-1555-43d5-b277-fa4baf3bb4e0)
7. Select "Betala med kort" (Pay with card)
![image](https://github.com/bitwarden/clients/assets/38279393/3efbacca-5075-42cb-b04c-b0452295e5c7)
8. Try to autofill card information from Bitwarden, expiration date will be filled in incorrectly.
![image](https://github.com/bitwarden/clients/assets/38279393/cab0f851-7515-4fcb-baed-052af6e1e122)

### Expected Result

The expiration date should be filled as MM/YY.

### Actual Result

 The expiration date is filled as first two numbers of the year/month

### Additional Context

Tested on Bitwarden Extension for Brave and Edge.

Expiration date HTML-code for Klarna:
`<input aria-label="MM/ÅÅ" id="expire" autocomplete="cc-exp" name="expire" spellcheck="false" type="tel" pattern="[0-9]*" config="[object Object]" data-cid="card-expire-field" value="20 / 10" style="background-color: rgba(0, 0, 0, 0); border: none; box-sizing: border-box; outline: none; width: 100%; box-shadow: none; caret-color: rgb(14, 14, 15); color: rgb(14, 14, 15); -webkit-text-fill-color: rgb(14, 14, 15); opacity: 1; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Arial, sans-serif; font-size: 16px; font-weight: 500; letter-spacing: 0px; height: 60px; overflow: hidden; padding-left: 0px; padding-top: 18px; position: absolute; text-overflow: ellipsis; top: 0px; margin-left: -1px; margin-top: 2px; white-space: nowrap; -webkit-font-smoothing: antialiased; text-rendering: geometricprecision; line-height: 17px;" class="">`

### Operating System

Windows

### Operating System Version

Windows 10/11

### Web Browser

Brave

### Browser Version

1.59.124

### Build Version

Version: 2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there!

We appreciate you letting us know of this issue. Due to the nature of autofill issues, we track them internally using different Forms depending on the platform:

mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform

browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In this case, we will go ahead and file an autofill report for you with the information you added here.

In the future, if you encounter any other page or app that doesn't autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed. 

Thanks!
