### ISSUE TITLE
Change Master Password does not redirect to configured server

### ISSUE THREAD

**Issue by rupak-sinha** [bitwarden/clients#6750]
### Steps To Reproduce

When using the Windows desktop app *and* if using bitwarden.eu servers,
1. Go to 'Accounts' menu
2. Click on 'Change master password'
3. On 'Change master password' dialog box, click on 'Yes'

### Expected Result

The default web browser should be opened up on the bitwarden.eu web vault page as the account requesting it is logged into the bitwarden.eu servers.

### Actual Result

The default web browser is opened up on the bitwarden.com web vault even though the account requesting it is logged into the bitwarden.eu servers.

### Screenshots or Videos

!['Change master password' dialog box](https://github.com/bitwarden/clients/assets/37274359/317183c0-cc22-46ca-9f24-89a04b78457e)

### Additional Context

In the 'Change master password' dialog box, the message shows:
_________________________________
Change master password
You can change your master password on the bitwarden.com web vault. Do you want to visit the website now?
_________________________________

The click of the button is hard coded to open the .com web vault.

Ideally, it should just show:
_________________________________
Change master password
You can change your master password on the bitwarden web vault. Do you want to visit the website now?
_________________________________

There should be a logic set to check where the logged in server is (EU or US) and open the corresponding web vault.

### Operating System

Windows

### Operating System Version

Windows 11 Pro version 22H2, build 22621.2506

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by rupak-sinha** [comment]
@NovaSilentium Thank you for putting it forward to the engineering team, much appreciated.

I have nothing further to add to this issue.

There are other requests (not bugs/issues), which I will be putting on the Community Forum.

Regards,
Rupak
