### ISSUE TITLE
Problem with Flathub version and Fedora

### ISSUE THREAD

**Issue by jereromero** [bitwarden/clients#6782]
### Steps To Reproduce

Im using version 2023.10.0 in Fedora 38 (updated). Everything was working well but few days ago stop working.
Currently when I open BW, shows the windows but full blank without showing anything but blinking cursor.

### Expected Result

It should show login main screen

### Actual Result

Does not show anything at all but blinking cursor

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/64384331/adfee674-7900-40fb-a6bf-21229b8790df)

### Operating System

Linux

### Operating System Version

Fedora 38

### Installation method

Other

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

The flatpak is maintained by the community, not Bitwarden. You can use the [official .AppImage installer](https://bitwarden.com/download) from the Bitwarden website as an alternative while updates are pending for the flatpak application or try this suggestion from another user: https://github.com/bitwarden/clients/issues/6757#issuecomment-1790380477

This issue will now be closed.

Thanks!
