### ISSUE TITLE
Blank screen on Linux Mint

### ISSUE THREAD

**Issue by Tektrold** [bitwarden/clients#6785]
### Steps To Reproduce

1. Open Bitwarden Desktop Client.
2. Screen is blank. I can see the cursor which moves if I type anything.
3. I think I can login, but I still can't see anything.

### Expected Result

1. Open Bitwarden Desktop Client.
2. Screen is blank. I can see the cursor which moves if I type anything.
3. I think I can login, but I still can't see anything.

### Actual Result

1. Open Bitwarden Desktop Client.
2. Screen is blank. I can see the cursor which moves if I type anything.
3. I think I can login, but I still can't see anything.

### Screenshots or Videos

![Screenshot from 2023-11-03 11-26-09](https://github.com/bitwarden/clients/assets/72400271/b45d5b8f-c956-440a-9ba5-6643bb50cb35)

### Operating System

Linux

### Operating System Version

21.2 Victoria

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.3 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dontfreakout** [comment]
Dev Tools in Bitwarden are unreadable too.


### Operating System 
Linux, Fedora 38

### Installation method
Flatpak

### Build Version
Version 2023.10.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

![image](https://github.com/bitwarden/clients/assets/1829574/2516fc0e-cb1d-4d57-98f8-5dd7b0bfea79)

**Comment by AlexSBlackburn** [comment]
I had the same issue, this fixed it for me: https://github.com/bitwarden/clients/issues/6757#issuecomment-1790380477

**Comment by Jack-Balcombe** [comment]
I have the same issue on Linux Mint 21.2 as well, but with the Flatpak version. It seems to come and go. It gets broken by updates every once in a while, gets fixed a few updates later, and then breaks again a few updates later.

Removing the GPU cache seems to work for me as well, but it would be nice to get this fixed properly so that it doesn't happen again in the future.

By the way, I think there is a typo in this bug report. Expected result should not be the same as the actual result.

**Comment by Jack-Balcombe** [comment]
I wonder if it has anything to do with what GPU you're using. I have Intel integrated graphics and Nvidia discrete graphics.

**Comment by dontfreakout** [comment]
> I wonder if it has anything to do with what GPU you're using. I have Intel integrated graphics and Nvidia discrete graphics.

Same for me.
**Intel® UHD Graphics 630** and **Nvidia GeForce GTX 1650**

**Comment by Adedamola-Aina** [comment]
Hi there,
The flatpak is maintained by the community, not Bitwarden. You can use the [official .AppImage installer](https://bitwarden.com/download) from the Bitwarden website as an alternative while updates are pending for the flatpak application.
This issue will now be closed.
Thanks!
