### ISSUE TITLE
Bitwarden opens a new window on each webauthn request

### ISSUE THREAD

**Issue by jankaifer** [bitwarden/clients#6788]
### Steps To Reproduce

1. Have Bitwarden extension installed.
2. Open this codesandbox: https://codesandbox.io/s/bold-merkle-sf2cy6?file=/src/index.mjs
3. click the button to try to authenticate

### Expected Result

I want to authenticate using yubikey. So I
1. start the authentication
2. I touch my yubikey and it works.

### Actual Result

Bitwarden window gets triggered, which I need to manually close. It's annoying and it slows us down.

Right now the flow is:
1. start the authentication
2. click `use browser` button on bitwarden popup
3. touch yubikey and it works

### Additional Context

This got probably introduced in 2023.10.0 as part of this change:
> Add support for saving and using passkeys to log in to apps and services

It was not present on previous release `2023.9.2`

### Operating System

Linux

### Operating System Version

ubuntu 22.04

### Web Browser

Chrome

### Browser Version

Version 118.0.5993.70 (Official Build) (64-bit)

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jankaifer** [comment]
Maybe we are doing something wrong and it's possible to craft the authentication request in a way so it doesn't trigger bitwarden. If it's not possible to do so, we will need a way to disable this feature of bitwarden, otherwise we need to stay on the old version / not use the extension at all.

**Comment by xWTF** [comment]
It's the passkey feature inteferening with webauthn, should be mitigated in https://github.com/bitwarden/clients/pull/6787.
See the community post: https://community.bitwarden.com/t/add-setting-to-disable-bitwarden-passkey-prompt/59668/3

I do hope they add an option to fully disable it. People with hardware authenticators (yubikeys, DIY webauthn chips, mooltipass, etc.) may not use this feature at all anyway.

BTW there're sites use WebAuthn as 2FA instead of passkeys, it makes no (or very little) sense to save your 2FA in bitwarden instead of a yubikey.

**Comment by jankaifer** [comment]
That PR helps, but you will still need to unlock your store before you can start singing webauth normally.

Leaving this issue open as we want to use yubikey without unlocking the store first.

**Comment by Adedamola-Aina** [comment]
hello @jankaifer 

Thank you for bringing this to our attention. Your issue appears to be describing the intended behavior of the software. 

At present, you can simply click on the "use browser button" 

Improvements will be forthcoming in future releases.


![image](https://github.com/bitwarden/clients/assets/91448810/a7212f6f-b4d8-459c-a7d5-fe1a19c1595a)

**Comment by jankaifer** [comment]
Thanks for the quick response. As noted in the issues description. I know that you can click this. But we authenticate a lot and this extra click is a huge regression for us.

It won't be as severe if it won't ask after authenticating but still not optimal. And my colleagues will probably still enable the extension in mode "after clicking the icon".

**Comment by xWTF** [comment]
Take a look at this feature request: https://community.bitwarden.com/t/add-setting-to-disable-bitwarden-passkey-prompt/59668
Have an option to disable this feature globally really helps.

**Comment by aryklein** [comment]
Having the same issue here. It's totally annoying to click `use browser` button on bitwarden popup
