### ISSUE TITLE
Firefox Extension on addons.mozilla.org still on version 2023.9.2

### ISSUE THREAD

**Issue by Justus-D** [bitwarden/clients#6793]
### Steps To Reproduce

1. Go to https://addons.mozilla.org/firefox/addon/bitwarden-password-manager/
2. Scroll to "more information"
3. See the version info

### Expected Result

I expect the version to be the current version of the extension (2023.10.1).

### Actual Result

The version is two releases older than the current version (2023.9.2).

### Additional Context

I was waiting for the release of the new version of the extension and noticed that the new version is only available on Chrome, not on Firefox.
I know from my own experience that it can take some time for extension updates to get approved on amo, but just in case there is a different issue with the Firefox release, I opened an issue. Maybe I'm just impatient.

I will close this issue, should the current version become available on addons.mozilla.org.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

119.0

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ich777** [comment]
Also see the same over here on Firefox `115.3.0esr` and on `119.0`

**Comment by eternaltyro** [comment]
I was hoping to test Passkeys and noticed this.

**Comment by kspearrin** [comment]
Mozilla takes a lot longer to review updates than the other stores. We are waiting for their review before the update rolls out. Expect this for every update vs what you see on the releases page here and the other stores.

**Comment by felschr** [comment]
Would it be possible for you to include signed Firefox xpi's in GitHub releases?

**Comment by ich777** [comment]
@kspearrin are you really sure that this is the case here because the Mozilla Addon shows that the last update was pushed on Novmeber 2nd:
![grafik](https://github.com/bitwarden/clients/assets/28066518/0d2d7745-73ee-49f2-a61c-c3efc204a2ed)

I can't imagine that Mozilla would show the new update date when the addon is still in review or do they?

Could it be the case that a wrong version was pushed to Mozilla?

**Comment by Justus-D** [comment]
> I can't imagine that Mozilla would show the new update date when the addon is still in review or do they?
@ich777 
The version that's shown in the settings and on addons.mozilla.org is the latest accepted and reviewed verison. So if a version is still under review, nothing is shown to the end-user. I just opened this issue because in my experience it only takes a day or so for the review to be completed. Maybe it takes a little longer with larger, more popular extensions.

**Comment by Zeik0s** [comment]
@ich777 the date shown under "last updated" is the date where your firefox updated the addon, not when it was published in the addon-store. 

Example here is the multi-account-container addon (published on 25th october, updated in my firefox at 26th october)

![grafik](https://github.com/bitwarden/clients/assets/35345686/901aa111-086e-44f0-b75e-5ac9d9199115)

**Comment by Justus-D** [comment]
The extension update was just published. The current version on addons.mozilla.org is now 2023.10.1.
