### ISSUE TITLE
Chrome browser extension blocks touchId prompts

### ISSUE THREAD

**Issue by TiansuYu** [bitwarden/clients#6800]
### Steps To Reproduce

When I am trying to login company SSO (Okta), there is one last step (2FA) which will prompt touchId on MacOs to verify myself. However, before this being prompt, the bitwarden chrome extension will be prompted and block this. 

### Expected Result

Bitwarden will not be prompted when a touchId is called. 

### Actual Result

Bitwarden prompt blocks touchId prompt. 

### Operating System

macOS

### Operating System Version

MacOS 13.6

### Web Browser

Chrome

### Browser Version

Version 118.0.5993.117 (Official Build) (arm64)

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hello @TiansuYu 

We are aware of this issue. We are currently looking at the possibility of releasing a hotfix for this issue.

You can click on the "use browser" at this time. 

![image](https://github.com/bitwarden/clients/assets/91448810/d459734d-4c66-4eb3-ad68-a4116e532c75)

**Comment by TiansuYu** [comment]
Trying Bitwarden today, notice the passphrase is already matching. Great work! (Though notice the lead time from confirm to login on browser end still bit long.)
