### ISSUE TITLE
Apple/iCloud Login on Chrome gets interrupted by Bitwarden 

### ISSUE THREAD

**Issue by cytostatic** [bitwarden/clients#6802]
### Steps To Reproduce

Bitwardens 'Use Browser' button is not working on apple account log in. It just interrupts the log in process complettely.

1. Go to 'https://www.icloud.com/'
2. Click on 'log in'
3. Enter E-Mail
4. Click on 'Log in with Passkey'
5. Bitwarden opens
6. Click on 'use Browser'

### Expected Result

Bitwardens 'Use Browser' button should trigger the native Browser popup

### Actual Result

Login process is interrupted. Nothing happens.

### Operating System

macOS

### Web Browser

Chrome

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

We are aware of this issue. We are currently looking to bring improvements to this area with next releases.
