### ISSUE TITLE
Left Navigation Edit Folder Icon does not display on very long folder names

### ISSUE THREAD

**Issue by foxinSOCKS5** [bitwarden/clients#6811]
### Description of Issue

On MacOS desktop client Version 2023.9.1 (12289), if a very long folder name(especially with wide characters) appear in the `left-nav` DIV, `Edit Folder` icon does not display in the navigation bar.

1. Create a new folder with a name like `5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D5D`
2. Select the newly created folder in the Left Navigation bar and observe that the `Edit Folder` icon is not visible

### Expected Result

Edit Folder Icon is visible to users when any folder is selected under the FOLDERS filter in the left navigation.

### Actual Result

<img width="254" alt="no-edit-folder-icon" src="https://github.com/bitwarden/clients/assets/49213179/7a2d28ab-8175-4586-a3cc-e42697637f2a">

### Additional Context

Potential workaround for the issue:

1. While desktop client is open, hit F12 key to bring up developer tools
2. Select the inspector icon from the top left corner (or hit CMD+Shift+c)
3. Highlight the left navigation bar to expose `<div class="left-nav">` HTML tag under the `Elements` tab and then select it
4. From the Styles window on the right locate `.left-nav {` CSS properties and uncheck `width` and `max-width` properties
<img width="322" alt="css-edit" src="https://github.com/bitwarden/clients/assets/49213179/196ad733-7ec9-4e4a-8ab2-207d3f90e409">

5. Left navigation bar will expand to display the full name of the longest folder
6. Locate the edge of the Edit Folder icon in the navigation bar and click it to expose the Edit Folder modal
<img width="274" alt="expanded-nav" src="https://github.com/bitwarden/clients/assets/49213179/304bbd06-5b11-474e-b27d-4d38c90f0052">

7. Click Delete icon in the modal
<img width="303" alt="edit-folder-modal" src="https://github.com/bitwarden/clients/assets/49213179/29bf0690-e698-4bd5-96f4-bd371ce4eee2">

### Operating System

macOS

### Operating System Version

Sonoma 14.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.1 (12289)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
