### ISSUE TITLE
Copying to clipboard is broken on Wayland

### ISSUE THREAD

**Issue by mirenradia** [bitwarden/clients#6812]
### Steps To Reproduce

1. Launch with the flags `--enable-features=UseOzonePlatform --ozone-platform=wayland` (to enable native Wayland mode)
2. Log in.
3. Open an entry in Bitwarden.
4. Click the button to copy something (e.g. username/password).
5. Inspect system clipboard or attempt to paste copied item.

### Expected Result

The item is successfully copied to clipboard.

### Actual Result

The item is not copied to the clipboard.

### Additional Context

This was not a problem before I updated to 2023.10.0 (e.g. on 2023.9.3). I have tested the downgrading fixes the problem.

Here is some information about my system:

KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.11
Kernel Version: 6.5.9-200.fc38.x86_64 (64-bit)
Graphics Platform: Wayland

I am using the RPM package downloaded from the release tab in this repo.

### Operating System

Linux

### Operating System Version

Fedora Linux 38 (KDE)

### Installation method

Other

### Build Version

2023.10.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by pffont** [comment]
Not sure if it's related, but in my case I can copy to clipboard but can't paste using mouse wheel, only with CRLT+V.
I noticed it after upgrade to version 2023.10.1

**Comment by mirenradia** [comment]
Still broken on 2023.10.1 for me.

**Comment by wpost** [comment]
For what it's worth, I see the same behavior (items are not copied to the clipboard) using 2023.10.0 and 2023.10.1 even though I'm on X11 (openSUSE 15.3, using AppImage). Like the original reporter, downgrading to 2023.9.3 fixes it for me.

**Comment by solopasha** [comment]
Works for me after enabling the wayland-data-control feature of the arboard crate. https://github.com/solopasha/bitwarden_flatpak/blob/build-from-source/wayland-clipboard.patch

**Comment by almereyda** [comment]
@solopasha Could you provide some instructions on how to build a release from your FlatPak, or offer those changes upstream in a Pull Request?

Else I can only confirm that downgrading helped.

When looking at the commit log, it also became visible that there were many changes in the Wayland-related area, which each on their own could explain the regression observed here (https://github.com/flathub/com.bitwarden.desktop/commits/master).

1. 2023-10-20 updated Flatpak runtime upgrade from 22.08 to 23.08 https://github.com/flathub/com.bitwarden.desktop/commit/0ba81cb4e4e66d6c3eec9b9a7c8941790decc39a
2. 2023-11-02 Bitwarden upgrade to 2023.10.0 https://github.com/flathub/com.bitwarden.desktop/commit/e18bf457307c4087e261a705eaa2e3633578ae13
3. 2023-11-07 Bitwarden upgrade to 2023.10.1 https://github.com/flathub/com.bitwarden.desktop/commit/58755aedca2b569ace54d43256bb95af4f332b0c
4. 2023-12-12 Wayland by default, disable X11 socket, activate fallback-X11 https://github.com/flathub/com.bitwarden.desktop/commit/1eef6b23aa11d0229ae25156bd192430fbe12794

Any of these could have gone wrong, and two come with environmental side-effects, especially the Flatpak upgrade. I suspect it is a combination of the recent change of the underlying platform, and some misconfiguration in the Flatpak sockets.

**Comment by ghisvail** [comment]
> Works for me after enabling the wayland-data-control feature of the arboard crate. https://github.com/solopasha/bitwarden_flatpak/blob/build-from-source/wayland-clipboard.patch

Did you forward the proposed changes upstream?

**Comment by justin13888** [comment]
I use Bitwarden with a completely different way. I use Fedora on Wayland Gnome, running Bitwarden installed through Flatpak. But it works. So could it be some bug for your particular setup?

**Comment by amadeushaessler** [comment]
Same issue here on Arch with Wayland (Hyprland). I'm using the official package from the Arch Repository (2024.1.0).

**Comment by cmvanb** [comment]
I also have this issue on Arch (river wm). It's a must-have feature IMO. I downgraded to `2023.9.2-1`, the last version which works.

> I use Bitwarden with a completely different way. I use Fedora on Wayland Gnome, running Bitwarden installed through Flatpak. But it works. So could it be some bug for your particular setup?

The flatpak is not an official distribution of Bitwarden, it's community maintained.

**Comment by justin13888** [comment]
My Bitwarden client version (distributed as through that community-maintained Flatpak) is 2024.1.0. I haven't been on Arch for a while so can't say about the state of the package. OP says they are on KDE Fedora. Regardless, I'm unable to replicate the issue, and so I was wondering if it could be an issue particular to only some Wayland setups.

**Comment by flaviocamilo** [comment]
Same issue here, on `Wayland`, but using `Sway` (`--ozone-platform-hint=auto` and verified by `swaymsg -t get_tree` that it is correctly on `Wayland`) on `Gentoo`. Bitwarden version `2023.12.0`. Previous (and working) version installed was `2023.7.1`, so I can't say in which version between the bug was introduced. Official package from the distribution (`no Flatpak`).

Getting the following error in log:
```
Error occurred in handler for 'clipboard.read': [Error: The clipboard contents were not available in the requested format or the clipboard is empty.] {
  code: 'GenericFailure'
}
```

**Comment by Duckrinium** [comment]
## [small workaround for now]
I tried to drag and drop username/password blocks into app fields and that did fill fields, so if you can do this, here is that workaround while issue is up, if you don't want whole ctrtl+c & ctrtl+v action, which I feel is unsafe if you got clipboard history. Make sure you remove password clipboard entries :)

**Comment by rodhfr** [comment]
The issue persists with the Flatpak, however, today I successfully installed the Bitwarden package version 2024.2.0-1 via pacman, and the copy-paste functionality is now working. I'm using Hyprland 0.24.0.

**Comment by kristanner2015** [comment]
I'm still having this problem with 2024.2.0 on gentoo KDE Plasma Wayland.  I use the AppImage and copy-paste has been broken since 2023.10.  I wasn't even aware you could drag-and-drop fields from the app.  That does appear to work.

**Comment by dani-garcia** [comment]
Hey everyone, the Wayland fix mentioned here and in PR #7508 is merged now and should be available in release 2024.3.0, which should fix all the wayland clipboard copy issues.

**Comment by bzar** [comment]
Just installed 2024.3.0 from flathub, copy still not working on Sway.

**Comment by mirenradia** [comment]
I know the flatpak isn't officially supported but FWIW it works for me on KDE Plasma 5.27.10.

**Comment by kristanner2015** [comment]
Confirm the copy paste functionality is working now with AppImage client under KDE Plasma on Wayland with latest 2024.3.0 release.

**Comment by bzar** [comment]
Okay, tested 2024.3.0 from pacman and it works. :+1:

**Comment by Techognito** [comment]
Also using flatpak 2024.11.2 and it works fine for me.
I'm on Fedora 41 with KDE 6.2.3

**Comment by complexspaces** [comment]
Hi everyone, `arboard` maintainer here (the Rust library Bitwarden uses for the clipboard). If you're running the Flatpak and having problems, please see https://github.com/bitwarden/clients/issues/13431#issuecomment-2974706750 and follow that issue instead.
