### ISSUE TITLE
Disable Automatic Passkey Prompt at Organizational Level

### ISSUE THREAD

**Issue by cesar-semiotic** [bitwarden/clients#6814]
### Steps To Reproduce

1. Open a web browser and go to a site with a saved log in that prompts for a passkey

### Expected Result

You should be defautling to your normal passkey (ie yubikey, touchID etc)

### Actual Result

The prompt for bitwarden passkeys pops up, and there is no way to turn it off besides clicking the button to go to browser

### Screenshots or Videos

![Screenshot 2023-11-06 at 4 31 27 PM](https://github.com/bitwarden/clients/assets/149401430/0441751b-a077-436d-96eb-75bca75eae88)

### Operating System

macOS

### Operating System Version

14.1

### Web Browser

Chrome, Brave

### Browser Version

1.60.110

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sllynn** [comment]
+1

**Comment by atjbramley** [comment]
Hi @cesar-semiotic,

Thanks for your feedback.  Referring to the title of this issue, _Disable Automatic Passkey Prompt at Organizational Level_, this is a feature request, which we request you to handle via our Community Forums.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

There is an existing discussion on this here:
https://community.bitwarden.com/t/add-setting-to-disable-bitwarden-passkey-prompt/59668

Please feel free to create a new topic if you feel that disabling this on an Organisational Level represents a seperate feature request.

Please also look out for ongoing additional improvements to Passkey support in Bitwarden in future releases.

This GitHub issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by vlcw** [comment]
Just unsubbed premium. Waited almost a month for this "feature" to go away. The prompt interfering somehow causes sites to ask for fido pin when they never did before. Exceeded attempts by bruteforcing my own yubikey. I am fully done with bitwarden.
