### ISSUE TITLE
Not prompting for Google Passkey

### ISSUE THREAD

**Issue by a-pir1** [bitwarden/clients#6840]
### Steps To Reproduce

1. Go to Google Login, and go through the workflow until you reach the password screen.
2. Select "Use your passkey" on the "Try another way" screen.

### Expected Result

Bitwarden will come up and offer the stored Google Passkey, or come up and say no passkeys saved.

### Actual Result

The OS "Making sure it's you" prompt appears, and no Bitwarden prompts appear whatsoever.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/35549787/9e70c58d-517a-4c23-affc-7f8e473ab074)

### Operating System

Windows

### Operating System Version

Windows 10 Enterprise 22H2, Windows 11 Education 22H2

### Web Browser

Chrome, Microsoft Edge, Opera

### Browser Version

(Latest of All)

### Build Version

Version 2023.10.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. You might try disabling Edge's ability to save passwords. 

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Zoran-B** [comment]
Actually, I'm having a similar issue. I've created a passkey for Google in Bitwarden, but when I try to use Passkey during Google Login. Bitwarden will ask me to log in (if I'm not logged in), and then it will open a Windows Security popup offering me my mobile device and QR code. It looks like a system (Windows) popup. Same in Edge and Chrome. Can't get the Bitwarden popup to confirm the passkey option.

It works on GitHub....
![image](https://github.com/bitwarden/clients/assets/80095198/da6595b3-6aac-4e5b-ad0f-d04997d71e55)

**Comment by a-pir1** [comment]
This is also occurring in opera, and safari on my mac.  I have no problems using my passkey on other websites with bitwarden.  I implore you to reopen this issue.

**Comment by schmud** [comment]
Same problem over here.

**Comment by jonaskello** [comment]
Same problem for me in chrome. It is possible to save the google account passkey in bitwarden but when trying to login google asks to scan QR code of device with passkey and just ignores bitwarden. 

Can we re-open this issue?

**Comment by siffreinsg** [comment]
I have the same problem on Brave on Windows 11. Connecting with passkey goes straight to Windows Hello instead of Bitwarden.

**Comment by kopcink** [comment]
I have the same problem - Chrome 119.0.6045.200, Windows 10 - after connecting with passkey, I am redirected to Windows Hello. I have generated passkeys for other websites - the issue is only with google account

**Comment by samstill** [comment]
Same Issue

**Comment by jonaskello** [comment]
I can confirmed it is solved for me too with version 2023.12.1.

**Comment by Havoc85** [comment]
On MacOS 14.2.1 (Apple Silicon) with Chrome 120.0.6099.216 and 2023.12.1 it is NOT fixed. Trying to login via Passkey to Nextcloud is not working.

**Comment by kriswilk** [comment]
I'm having what seems to be the same problem on ebay.com. Reported in #7785 just in case it turns out to be something else. But the symptoms are identical.

**Comment by eldijomo** [comment]
I have the same problem in Brave
Brave is up-to-date
[Version 1.62.162 Chromium: 121.0.6167.164 (Official build) (64-bits)](https://brave.com/latest/)
Bitwarden extension Version 2024.1.1
Also, Not working on Mobile version.

**Comment by alangrainger** [comment]
I had this issue on Fedora with 2024.4.2 with both Firefox and Chromium. Google logins would not show the passkey popup, yet other sites functioned without issues.

The solution for me was to uninstall the extension and re-install.

**Comment by felixoswald** [comment]
Had the same problem. The fix was to enable the following option: (settings > notifications)

![image](https://github.com/user-attachments/assets/e36fa889-48dd-4970-a119-8082972ac83f)

**Comment by rehannali** [comment]
I'm having an issue in mobile using browser. I'm using S21 Ultra.

**Comment by ryouzue** [comment]
Reviving 'cus issue persists at least for me when I get prompted for passkey, bitwarden does not autofill the passkey it got saved, on phone: Samsung Galaxy Flip3 5G

**Comment by callum-playside** [comment]
I also have this issue on firefox on a new laptop i have formatted
Old laptop worked fine, not sure what the issue could be 🤷‍♂️

**Comment by pamperer562580892423** [comment]
@callum-playside The issue is Firefox extension 2025.11.1 - see here: https://github.com/bitwarden/clients/issues/17598 and/or more important: update to 2025.11.2, which is available now in the Mozilla extension store.
