### ISSUE TITLE
Autofill shortcut fails for all URLs using Firefox on both MacOS and Windows

### ISSUE THREAD

**Issue by mkoninx** [bitwarden/clients#6857]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Shortcuts to autofill credentials in Firefox were working on both my MacOS and Windows laptop until late last night, that is

On Windows: Ctrl + Shift + L
On macOS: Cmd + Shift + L

### Actual Result

No response

### Operating System

Windows, macOS

### Operating System Version

Ventura / Windows 10

### Web Browser

Firefox

### Browser Version

119.0.1

### Build Version

 Version 2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Can you please go to your extension shortcuts and see if the shortcuts for Bitwarden autofill are actually assigned? https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

**Comment by zjtalia** [comment]
I am seeing the same behavior. It looks like an issue with the shortcut `Ctrl+Shift+L` specifically. Other extension shortcuts work as expected, and changing the shortcut for auto-filling passwords restores functionality.

**Comment by mkoninx** [comment]
Thank you for commenting, the issue seems to have resolved itself (possibly a patch in Firefox?) Will close the issue

**Comment by zjtalia** [comment]
Just confirmed that upgrading FF to the newest version (119.0.1) has fixed the issue.
