### ISSUE TITLE
DuckDuckGo integration not working

### ISSUE THREAD

**Issue by fd8tr276** [bitwarden/clients#6869]
### Steps To Reproduce

1. Set up DuckDuckGo browser integration for Bitwarden
2. Go to any webpage with a login
3. Bitwarden does not recognize the username/password fields to provide autofill option

### Expected Result

Bitwarden should recognize the username/password fields and put a Bitwarden icon into those fields when the page loads.  The user should be able to click on the field and (so long as Bitwarden is unlocked) select the option to autofill the fields.  If Bitwarden is locked, clicking on the field should prompt the user to unlock Bitwarden, then allow autofill.

### Actual Result

Bitwarden does not recognize fillable fields when a page loads.  There is no Bitwarden icon showing, and clicking on the field does not prompt an autofill option.

### Operating System

macOS

### Operating System Version

12.6.1 (21G217)

### Web Browser

Chrome

### Browser Version

NOT CHROME - DuckDuckGo Version 1.62.3 (1.62.3)

### Build Version

Version 2023.10.0 (13355)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @fd8tr276,

Thank you for reporting this. I tested this on macOS 14.1.1 and DuckDuckGo 1.62.3 and Bitwarden 2023.10.1 at [Vimeo.com](https://vimeo.com/), and I was prompted to perform Auto-Fill via the key icon in the Email and Password fields. At this point, I recommend that you proceed with a fresh new installation; Please deactivate the integration within the Bitwarden Settings menu, uninstall the DuckDuckGo browser off your machine, reboot your computer, install DuckDuckGo anew and activate the integration again and give this another try.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
