### ISSUE TITLE
Firefox Android extension doesn't autofill

### ISSUE THREAD

**Issue by KeithLRobertson** [bitwarden/clients#6870]
### Steps To Reproduce

1. Go to a web site login form with credentials in Bitwarden.
2. Expected page should autofill if enabled, otherwise
3. Open Bitwarden Add-On from menu.
4. Login entry for current site will appear, click on it.

### Expected Result

Page should autofill on load if enabled. Otherwise should autofill when clicked from Bitwarden. (This worked until a few months ago!)

### Actual Result

Page does not autofill. First click on Login entry in BW does nothing. Second click shows a pink banner with text: "Unable to auto-fill the selected item on this page. Copy and paste the information instead."

### Additional Context

Samsung Galaxy S20 FE 5G, Model SM-G781U

### Operating System

Android

### Operating System Version

13, Android Kernel 4.19.113-27223811

### Web Browser

Firefox

### Browser Version

119.1.1 (Build #2015984795)

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @KeithLRobertson,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for [desktop environments](https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated [Android client](https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

Thank you again,

**Comment by KeithLRobertson** [comment]
Hi @SergeantConfused.  Well, crud. The plugin used to work perfectly until it didn't. I finally figured out how to turn on auto-fill on the Bitwarden mobile app (contrary to the online instructions), but it's not nearly as seamless. :-(
