### ISSUE TITLE
Not saved to clipboard

### ISSUE THREAD

**Issue by G1ndry** [bitwarden/clients#6871]
### Steps To Reproduce

1. press the Copy Username or Password button
2. Check the clipboard
3. The data is not saved.

### Expected Result

When a copy is made, it is saved to the clipboard.
（This worked until a few months ago.）

### Actual Result

The data is not saved. 
And since pasting can be done with ctl+v, it is simply not saved to the clipboard.

### Operating System

Windows

### Operating System Version

win11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.10.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by undrivendev** [comment]
I'm getting the same error in the Linux version.

I'm using Arch Linux and the KDE desktop environment.

**Comment by SergeantConfused** [comment]
Hi @G1ndry,

Thank you for reporting this. I tested this in Windows 11 Pro with Bitwarden desktop 2023.10.1 and the Username and Password values were successfully copied to the clipboard and I was able to paste them to Notepad. I recommend that you proceed and perform a clean new installation; Please uninstall Bitwarden off your machine, remove any leftover data (https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot, and install it anew.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket. @undrivendev, could you please get in touch and clarify in your message how you installed Bitwarden on your machine?

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you both again,

**Comment by undrivendev** [comment]
@SergeantConfused I followed the reinstallation steps, still not working.

I installed the application from the package manager's standard repos: [here](https://archlinux.org/packages/extra/x86_64/bitwarden/).

I investigated some more, and it seems that, in my case, it's a dupe of #6812 .

**Comment by G1ndry** [comment]
@SergeantConfused 
I have one confirmation. I was also able to copy and paste and stick it in notepad. The issue this time is that it is not saved to the Windows clipboard (win+v). Are you sure it was saved to the clipboard?

**Comment by G1ndry** [comment]
This is not just one machine, but sub-machines have the same problem.
I have done a complete reinstallation but no improvement.

**Comment by rendhalver** [comment]
I am seeing the same problem in Fedora 38.
Is there any reason this issue is closed when it is still a problem?

**Comment by SergeantConfused** [comment]
Hi @G1ndry,

_I have one confirmation. I was also able to copy and paste and stick it in notepad. The issue this time is that it is not saved to the Windows clipboard (win+v). Are you sure it was saved to the clipboard?_

Thank you for that clarification. That is the excepted behaviour in our latest release of the desktop client; More information here (https://github.com/bitwarden/clients/issues/2621) and here (https://github.com/bitwarden/clients/pull/4516).

@rendhalver, could you please check if what you're experiencing is related to (https://github.com/bitwarden/clients/issues/6812)? If it is not, please feel free to create a new GitHub report for what you're experiencing.


All the best,

**Comment by G1ndry** [comment]
@SergeantConfused 

Thanks for the reply. I didn't realize there was a change in the specs... 
I understand.

I understand that this is better for security, but I often use the clipboard, so I would like to be able to choose whether or not the user can save to the clipboard.

**Comment by G1ndry** [comment]
@SergeantConfused 
I feel there are others like that, so I would like to see this released with a user choice (to save to clipboard or not).

**Comment by LeeRoyManea** [comment]
> @SergeantConfused I feel there are others like that, so I would like to see this released with a user choice (to save to clipboard or not).

I feel with you.

**Comment by SergeantConfused** [comment]
Hello @G1ndry and @LeeRoyManea,

The Bitwarden Community Forums have a [Feature Requests](https://community.bitwarden.com/c/feature-requests/) section; I recommend you submit that as a new feature request or improvement suggestion, and hopefully it'll be incorporated in the future.


All the best,

**Comment by G1ndry** [comment]
@SergeantConfused 
i see. thx <3
