### ISSUE TITLE
Blured fonts

### ISSUE THREAD

**Issue by bigkrp** [bitwarden/clients#6876]
### Steps To Reproduce

1. Open BitWarden Desktop Client

### Expected Result

The text has a clear display

### Actual Result

The text is blurred.

### Screenshots or Videos

screenshot is not an illustrative

### Operating System

Linux

### Operating System Version

Fedora Linux 39 (Workstation Edition)

### Installation method

Other

### Build Version

Version 2023.10.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @bigkrp 

I attempted to reproduce what you have described, and it seem to be working as expected on my end. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).
