### ISSUE TITLE
WebAuthN fails on localhost because it expects an HTTPS origin

### ISSUE THREAD

**Issue by allezxandre** [bitwarden/clients#6882]
### Steps To Reproduce

1. Go to a localhost website with WebAuthN (using unencrypted `http` protocol)
2. Use WebAuthN authentication

### Expected Result

WebAuthN UI opens, mimicking browser behavior on localhost

### Actual Result

WebAuthN fails silently on the UI but an error is logged to the console:

> Error: 'origin' is not a valid https origin

The error is correct, http://localhost is indeed not https, but I expected localhost to still be a valid origin.

### Operating System

macOS

### Web Browser

Chrome, Safari

### Browser Version

Safari 17.0 and Arc 1.15.2

### Build Version

Chromium Engine Version 119.0.6045.123 (arm64) 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gregorvand** [comment]
+1

since BitWarden jumps in ahead of native browser (why?) it stops all localhost development using WebAuthn being workable, unless in a browser where the BitWarden chrome extension has been disabled

**Comment by SDAChess** [comment]
This also made me go insane debugging today to find out this was Bitwarden related and not my own WebAuthn code. Please at least update the error message so that it's easy to know that it is related to Bitwarden ;)

**Comment by Jhoscy** [comment]
> +1
> 
> since BitWarden jumps in ahead of native browser (why?) it stops all localhost development using WebAuthn being workable, unless in a browser where the BitWarden chrome extension has been disabled

I agree, after disabling BitWarden webauthn works as expected

**Comment by barryp** [comment]
I just ran into this too.  Seems like it's coming from 

https://github.com/bitwarden/clients/blob/a141890b0989736cfa8ee5aab5ce1804f9c138bd/libs/common/src/vault/services/fido2/fido2-client.service.ts#L95-L98

There's a simple `window.isSecureContext` it could check, but maybe it doesn't have access to the `window` 

At the very least, maybe something like

    if (parsedOrigin.hostname == undefined 
        || !(
            params.origin.startsWith("https://") 
            || (params.origin === 'localhost') 
            || params.origin.endsWith('.localhost')
        )
    ) ...

**Comment by taylorjdawson** [comment]
If @barryp's solution is acceptable could we put this into a PR or is further consideration necessary? I have to enable & disable bitwarden when developing locally

**Comment by SDAChess** [comment]
I might need some tweaking such as adding `127.0.0.1` and `.local` domains maybe? Either way there some to be little to no interest from the Bitwarden team on this issue.

**Comment by abergs** [comment]
Hey, while I mostly work on [Bitwarden passwordless.dev](https://bitwarden.com/products/passwordless/) I'm just updating that we're looking to fix this in a way that aligns with the WebAuthn specification.

**Comment by acewings27** [comment]
This started being an issue for me today.

**Comment by carlos-menezes** [comment]
> Hey, while I mostly work on [Bitwarden passwordless.dev](https://bitwarden.com/products/passwordless/) I'm just updating that we're looking to fix this in a way that aligns with the WebAuthn specification.

Awesome. Any news on this?

**Comment by Aeases** [comment]
+1 this sucks ass

**Comment by abergs** [comment]
@carlos-menezes and others: Since https://github.com/w3c/webauthn/pull/2018 was merged in the spec we will move forward and allow `http://localhost:*` for passkeys in bitwarden. I don't have a date, but my guess is that it won't be long.

Thanks for reporting this.

**Comment by carlos-menezes** [comment]
Awesome, great to hear!

**Comment by coroiu** [comment]
@shahradelahi I haven't used Next.js in a while but it seems like they added experimental HTTPS support https://vercel.com/guides/access-nextjs-localhost-https-certificate-self-signed, could that also be a viable workaround while we wait for https://github.com/bitwarden/clients/pull/9236 to get released?
