### ISSUE TITLE
Copy password no longer copys password

### ISSUE THREAD

**Issue by dengg-ximes** [bitwarden/clients#6883]
### Steps To Reproduce

1. Select Entry
2. Use the "Copy password" button to copy password
3. try to paste password

### Expected Result

Both Paste buffer (select/middle click and Ctrl+C) are filed with password

### Actual Result

The select buffer is unchanged
(the other one seems to be handled correctly, but that breaks a lot of my usecases not to be able to middle-click paste the password)

### Additional Context

* installed via debian packaged downloaded from bitwarden/github
* used to work until at least 2023.9.x versions, not 100% shure aboute 2023.10.0
* as a workaround viewing the password and selecting it works but that is cumbersome and also not ideal as it means unessecarily displaying the password which is not ideal in all circumstances

### Operating System

Linux

### Operating System Version

Debian 12 (Bookworm)

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by GregDuhamel** [comment]
same issue on Fedora 39 using flatpak version : 

```yaml
Version: 2023.10.1
Shell: 25.9.1
Renderer: 114.0.5735.289
Node: 18.15.0
Architecture: x64
```
Thanks for your work guys.

**Comment by symbn** [comment]
Same issue on Nobara 38:
Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by rendhalver** [comment]
Same problem on Fedora 38 with the flatpack version.
```
Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64
```

**Comment by Lazerbeak12345** [comment]
I found in some cases, manually selecting the text then using the context menu to copy is a viable workaround (or at least one better than typing it manually)

**Comment by pmcneil** [comment]
Same problem Fedora 38 snap version, Cinnamon.
```
Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64
```

**Comment by AimVaguely** [comment]
Same on Arch Linux with flatpak in KDE plasma.
```
Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64
```

I think I might have been having trouble for a couple of days with this.

It does report an error when running it from a terminal, which happens whenever I click the copy button:
```
Error occurred in handler for 'clipboard.write': [Error: Unknown error while interacting with the clipboard: Display parsing error] {
  code: 'GenericFailure'
}
```

**Comment by dengg-ximes** [comment]
@AimVaguely hm....i don't see that, might it be that you are running wayland (KDE works both with X11 as well as with wayland ATM if i remeber correctly) and that creates additional error (messages)?

for me i see some other messages, but none at the time i copy the password.

as for system enviroment for completnes sake:
Debian Stable (12/bookworm)
X11 with i3 window manager

**Comment by AimVaguely** [comment]
> @AimVaguely hm....i don't see that, might it be that you are running wayland (KDE works both with X11 as well as with wayland ATM if i remeber correctly) and that creates additional error (messages)?
> 
> for me i see some other messages, but none at the time i copy the password.
> 
> as for system enviroment for completnes sake: Debian Stable (12/bookworm) X11 with i3 window manager

Yes, I am on Wayland. I forgot that might be relevant. My issue might not be the same one as this, but the symptoms look similar. I'll have a dig though the other reported issues later and see if any of them match my environment more closely.

**Comment by Lazerbeak12345** [comment]
In the Wayland cases, such as mine, it might be a dupe of #6812

**Comment by douglasthiel** [comment]
Same issue here. Was struggling to understand this for the past hour:

# System Details Report
---

## Report details
- **Date generated:**                              2023-11-16 11:55:56

## Hardware Information:
- **Hardware Model:**                              Apple Inc. Macmini7,1
- **Memory:**                                      16.0 GiB
- **Processor:**                                   Intel® Core™ i7-4578U × 4
- **Graphics:**                                    Intel® Iris® Graphics 5100 (HSW GT3)
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            481.0.0.0.0
- **OS Name:**                                     Fedora Linux 39 (Workstation Edition)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.1
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.5.11-300.fc39.x86_64

**Comment by Adedamola-Aina** [comment]
Hi there,

Thank you for your additional report!

I can confirm I was also able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Lazerbeak12345** [comment]
Why was this closed? Was it fixed? Was it actually a dupe?

**Comment by douglasthiel** [comment]
I just retested on Fedora Workstation 39 and it has not been resolved. Thanks for asking. :-) 
I used the copy button on Bitwarden and pasted into Typora. I got what was previously on the clipboard and not what I expected from Bitwardent.

**Comment by almereyda** [comment]
@Adedamola-Aina Is the engineering team aware of the solution that was presented in https://github.com/bitwarden/clients/issues/6812#issuecomment-1806830091 with:

- https://github.com/solopasha/bitwarden_flatpak/blob/build-from-source/wayland-clipboard.patch

**Comment by dMopp** [comment]
2026, still present ? at least i cant copy paste from the desktop app (flatpack)

**Comment by pamperer562580892423** [comment]
@dMopp:

> 2026, still present ? at least i cant copy paste from the desktop app (flatpack)

That is tracked here, I think: https://github.com/bitwarden/clients/issues/13431
