### ISSUE TITLE
Poor clarity of flatpak app on high resolution screens

### ISSUE THREAD

**Issue by qenaoa** [bitwarden/clients#6894]
### Steps To Reproduce

Gnome Wayland with HiDPI screen

### Expected Result

Higher resolution

### Actual Result

Blurred window of the Bitwarden application on Linux (Flatpak)

### Screenshots or Videos

![Screenshot from ](https://github.com/bitwarden/clients/assets/150185367/008d6bea-850d-48cb-a97b-f3d053c32d6e)

### Additional Context

I don’t really understand why, because some applications (not all) are also blurry, but it seems that there was no such problem in previous versions of Bitwarden

### Operating System

Linux

### Installation method

Other

### Build Version

Version 2023.10.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

The flatpak is maintained by the community, not Bitwarden. You can use the official .AppImage installer from the Bitwarden website as an alternative while updates are pending for the flatpak application.

This issue will now be closed.

Thank you.
