### ISSUE TITLE
Desktop app freezes after inputting a single character

### ISSUE THREAD

**Issue by brechtgermis** [bitwarden/clients#6904]
### Steps To Reproduce

1. Open the bitwarden desktop app
2. Enter your email address (or do anything else basically)

### Expected Result

Your email address is entered and you can proceed to log in

### Actual Result

After you typed the first character, the entire screen freezes, next a pop-up from the OS shows up stating the app is not responsive.

The same thing happens if you try to go to the About page to get the build number.

### Additional Context

This is on a clean fedora install with wayland

When launching bitwarden from the terminal, I get following output:

`
(node:146969) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 16:03:07.634: Failed to load module "pk-gtk-module"
Gtk-Message: 16:03:07.635: Failed to load module "pk-gtk-module"
(node:146969) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/snap/bitwarden/100/resources/app.asar/main.js:47305:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/100/resources/app.asar/main.js:47271:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/100/resources/app.asar/main.js:47267:12)
    at BiometricsService.init (/snap/bitwarden/100/resources/app.asar/main.js:47304:16)
    at Main.<anonymous> (/snap/bitwarden/100/resources/app.asar/main.js:54050:46)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/100/resources/app.asar/main.js:53942:58)
(node:146969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
(node:146969) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/snap/bitwarden/100/resources/app.asar/main.js:45647:131)
    at MenuMain.<anonymous> (/snap/bitwarden/100/resources/app.asar/main.js:45701:56)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/100/resources/app.asar/main.js:45671:58)
(node:146969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
`

### Operating System

Linux

### Operating System Version

Fedora 39

### Installation method

Snap

### Build Version

2023.10.1 (I cannot read the actual build number because of this bug)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Melmoth-the-Wanderer** [comment]
I have the same issue now after freshly installing Ubuntu 24.4

**Comment by Regressor** [comment]
I have same issue after installing it on Ubuntu 24.04.1 LTS. One symbol in any input field and freeeeeze

**Comment by foneboy** [comment]
I just had the same problem with Bitwarden after installing Ubuntu 24.04.1 LTS....after entering one character at the login screen the program froze and no more characters could be added to the login line.  I found that the number lock was engaged....I was able to login normally after turning off the number lock on the keyboard.

**Comment by stuntguy3000** [comment]
@jtodddd I also have this issue as the above, but unable to solve using @foneboy's comments.

Contacting Bitwarden Support for a bump.

**Comment by bhennlich** [comment]
Same here,  after installing it on Ubuntu 24.04.1 LTS. One symbol in any input field and app freezes

**Comment by cirrusflyer** [comment]
Same here.  Any solution?

**Comment by DeanLongmire** [comment]
Same issue with me. I am using Ubuntu 24.04.2 and installed through the app center
