### ISSUE TITLE
Browser addon - Firefox for android: Logout does not work + settings loss.

### ISSUE THREAD

**Issue by gB2BtSPm23DX2a** [bitwarden/clients#6914]
### Steps To Reproduce

1) Enter login credentials
2) Enter self-hosted settings.
3) Check "remember e-mail"
4) Log in.
5) Set settings:
    Security:
        Vault timeout - On browser restart
        Vault timeout action - Log out
6) Exit from Firefox using: Firefox \ Menu \ Quit
7) Open Firefox again.
8) Check Bitwarden addon.

### Expected Result

Previously, when logging out of the account, addon settings, login, self-hosted server settings were saved.

### Actual Result

 - Addon has not logged out of the account.
 - If you use "log out" from addon settings - it will quit from account and shows login screen with previously entered e-mail,
   but lost all self-hosted settings and change default server to bitwarden.com (selected server will not be displayed).
   After the next login, you must configure self-hosted settings and Bitwarden addon settings (Vault timeout action - Log out, etc) again.
 - Automatic Log out will work if you "force stop" the app via the android app menu, but the consequences of logging out will be the same as manual logout.

### Additional Context

A similar problem appeared in firefox addon for windows, but with the latest 2~ updates it has been fixed, while for android the problem remains.

### Operating System

Android

### Operating System Version

13

### Web Browser

Firefox

### Browser Version

119

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by micahblut** [comment]
The use of the firefox add-on on mobile is not a supported use-case. We support the use of our mobile app on the Android platform.
