### ISSUE TITLE
Punctuation error on Bitwarden's privacy page

### ISSUE THREAD

**Issue by timotheeMM** [bitwarden/clients#6919]
### Steps To Reproduce

1. Go to [https://bitwarden.com/privacy/](https://bitwarden.com/privacy/#eu-u-s-data-privacy-framework)

### Expected Result

An extra point should be removed in the explanatory text.

### Actual Result

On the page https://bitwarden.com/privacy/ in the part #eu-u-s-data-privacy-framework, there is a small typing error (see screenshot, in red).

### Screenshots or Videos

![Image](https://github.com/bitwarden/clients/assets/143833750/39bde178-9804-4e65-bed1-ce12a271f352)

### Operating System

Linux

### Operating System Version

Linux Mint 20.3

### Web Browser

Chrome

### Browser Version

115.0.5790.170 (Build officiel) (64 bits)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Thanks for bringing this to our attention! 

For future reference, we use GitHub issues as a place to track bugs and other development-related issues. If you come across another typo in a published article/blog post, please reach out to us directly from our contact page: https://bitwarden.com/contact/

Thanks again and have a great day!
