### ISSUE TITLE
Export command doesn't include passkeys

### ISSUE THREAD

**Issue by jessicah** [bitwarden/clients#6925]
### Steps To Reproduce

With an account with a passkey added (GitHub in this example):
1. `bw export --format json --output bitwarden.json`
2. `cat bitwarden.json | jq '.items[] | select(.name=="github.com")'`

The 'login.fido2Credentials' array is empty.

The same export from the browser extension includes the passkey under the 'login.fido2Credentials' array.

### Expected Result

A JSON export that includes the passkey data:

```json
{
  "otherKeys": "omitted",
  "name": "github.com",
  "login": {
    "fido2Credentials": [
      {
        "credentialId": "...",
        "keyType": "public-key",
        "keyAlgorithm": "ECDSA",
        "keyCurve": "P-256",
        "keyValue": "....",
        "rpId": "github.com",
        "userHandle": "...",
        "counter": "0",
        "rpName": "GitHub",
        "userDisplayName": "...",
        "discoverable": "true",
        "creationDate": "..."
      }
    ],
    "uris": [
      {
        "match": null,
        "uri": "https://github.com/login"
      }
    ],
    "username": "...",
    "password": "...",
  },
  "collectionIds": null
}
```

### Actual Result

A JSON export without the passkey data:

```json
{
  "otherKeys": "omitted",
  "name": "github.com",
  "login": {
    "fido2Credentials": [],
    "uris": [
      {
        "match": null,
        "uri": "https://github.com/login"
      }
    ],
    "username": "...",
    "password": "...",
  },
  "collectionIds": null
}
```

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.6 LTS

### Shell

Bash

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below.

Thanks!

**Comment by djsmith85** [comment]
Hi @jessicah,

multiple people have tried to reproduce this internally and have not been able to.

Could you please check if this is still happening for you with a recent version of the CLI. 

I'm going to close this issue, but if you are still experiencing the above mentioned behaviour, please comment and we'll happily re-open. 

Kind regards,
Daniel

**Comment by gitgizmo7** [comment]
This has been happening for a while for me on iOS (it never worked in the first place). Is this related or should I open a new issue for that?

**Comment by djsmith85** [comment]
> This has been happening for a while for me on iOS (it never worked in the first place). Is this related or should I open a new issue for that?

Hi @BionicBison05 this isn't related. The repository for the mobile clients are: [ios](https://github.com/bitwarden/ios/issues) and [android](https://github.com/bitwarden/android/issues). Please open a new issue on the respective repository.

**Comment by dskudi** [comment]
I'm seeing the same issue. When exporting my vault (this is on iOS/iPhone), my passkeys are not included in the JSON file. Is this a known issue?
