### ISSUE TITLE
Microsoft Edge InPrivate window still shows unlock vault 

### ISSUE THREAD

**Issue by LukaszRobertKlimkiewicz** [bitwarden/clients#6946]
### Steps To Reproduce

1. Go to '...' your Microsoft Edge browser, open InPrivate window   
2. Click on '....' Bitwarden and you can see that Bitwarden not asking for vault password it's still unlock
4. Click on '...'

### Expected Result

Lock vault

### Actual Result

Unlock Vault

### Operating System

Windows

### Operating System Version

11 23H2

### Web Browser

Microsoft Edge

### Browser Version

Version 119.0.2151.72 (Official build) (64-bit)

### Build Version

22631.2715

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. This is the expected behavior in all browsers, except Firefox. The vault session will persist even in incognito/InPrivate windows.

The issue here will be closed.

Thanks!
