### ISSUE TITLE
Addon intercepts Yubikey on Firefox

### ISSUE THREAD

**Issue by ctron** [bitwarden/clients#6956]
### Steps To Reproduce

1. Go to some website requiring 2FA

### Expected Result

Previously the browser's dialog for the Yubikey showed up. Using the Yubikey worked out of the box. This is super annoying!

### Actual Result

Bitwarden pops up and asks to unlock the vault. There's an additional link "back to the browser", which brings back the original functionality. But only for this request.

### Operating System

Linux

### Operating System Version

39

### Web Browser

Firefox

### Browser Version

120

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @ctron 

We are aware of this issue. We are currently looking at a possibility of releasing a hotfix for this issue.
