### ISSUE TITLE
Passkey authentication not working on Firefox (Android)

### ISSUE THREAD

**Issue by CharlesCanlom** [bitwarden/clients#6968]
### Steps To Reproduce

1. Download the add-on on the browser and login
2. Go to a website that supports Passkeys
3. Create/login using passkeys

### Expected Result

It's supposed to open a pop-up, saying to use or create this passkey 

### Actual Result

It's just give an error message in the website.

### Operating System

Android

### Web Browser

Firefox

### Browser Version

120.0

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @CharlesCanlom,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for [desktop environments](https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated [Android client](https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions, such as [passkeys](https://bitwarden.com/help/storing-passkeys/), may not operate as expected in a mobile environment.

Thank you again,
