### ISSUE TITLE
Auto-fill does not work for the page login.app.holvi.com

### ISSUE THREAD

**Issue by jarimustonen** [bitwarden/clients#6996]
### Steps To Reproduce

1. Store username and password that matches "holvi.com"
2. Go to https://login.app.holvi.com/
3. Note that the username and password are available on the Bitwarden plugin (the red badge is there)
4. Try auto-fill with keyboard shortcut and by clicking the entry in plugin menu
5. Nothing happens

### Expected Result

We expect the username and the password to be filled automatically.

### Actual Result

The username and password are not filled.

### Operating System

macOS

### Web Browser

Chrome, Safari, Brave

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

The team is aware that some sites' login forms aren't been autofilled by our extension. This is something we are actively working on, so if you could please follow this link and complete the form: https://github.com/bitwarden/clients/issues/1621 that would help us a lot.

**Comment by jarimustonen** [comment]
Thank you. The report is now filled. I have a suggestions:

Make this available directly in the browser plugin. The option should be presented if the user clicks the shortcut and nothing gets filled. In that case, you could offer a dialog to redirect the user to this form.
