### ISSUE TITLE
Error while adding passkey on aws console

### ISSUE THREAD

**Issue by maheshrjl** [bitwarden/clients#6997]
### Steps To Reproduce

1. Login to AWS console
2. Navigate to username in the top right section of the screen then go to [Security credentials](https://console.aws.amazon.com/iam/home?#security_credential)
3. Scroll down to 'Multi-factor authentication (MFA)'
4. Click on 'Assign MFA Device'
5. Give a device name, then select 'Security Key'
6. Click Next
7. Choose the AWS Account and save passkey

### Expected Result

Security key should be enrolled. 
![image](https://github.com/bitwarden/clients/assets/62394512/4d41b8fd-c208-4f4d-93e0-02ca09f33975)

### Actual Result

Security key is not enrolled. 
![image](https://github.com/bitwarden/clients/assets/62394512/c05a9dd3-66a5-4159-8135-9666edd8e675)

### Operating System

Windows

### Operating System Version

Windows 10 19045

### Web Browser

Brave

### Browser Version

1.60.118 Chromium: 119.0.6045.163

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @maheshrjl 

Thank you for your report! 

I was able to reproduce this issue, it highly possible that the AWS console doesn't yet support passkey, which is the reason you are getting this error message. You can try again using YubiKeys and that should work without any error message. 

The issue here will be closed.
