### ISSUE TITLE
Unlock with Pin, Lock with Master Password on Restart not working

### ISSUE THREAD

**Issue by GrizzlyAK** [bitwarden/clients#7075]
### Steps To Reproduce

1. Use BW in FF in full-time Private Browsing Mode (not private tabs), set allow in private mode in BW settings
2. Go to Bitwarden Plugin > Settings
3. Click on _Unlock with Pin_
4. Enable _Lock with Master Password on Browser Restart_
5. Enter Pin, <return>
6. Note that _Unlock with Pin_ is UNTICKED

### Expected Result

I expect BW to unlock with PIN until I restart the browser, at which time it would require the Master PW

Note that this functionality has worked for me for several years as described, but usually breaks for a few days following every  update. This time, however, it has not allowed me to set this up again and you have two options:

Always use a PIN (even after restart, if you leave _Lock with Master PW on Browser Restart_ unchecked when setting PIN), or
Always use a very long, secure Master Password.

The intended functionality of using a PIN and requiring the Master PW upon restart does not work in FF in Private Browsing Mode.

### Actual Result

If you enter a PIN and tick _Lock with Master PW on Browser Restart_, the check box for _Lock with PIN_ is no longer checked upon return to settings. This is unexpected behavior.

### Additional Context

Bitwarden not having full functionality in FF Private Browsing Mode is counter to the larger security issues being accommodated by Bitwarden.

### Operating System

Windows, iOS

### Operating System Version

Win 10 22H2, iOS 17

### Web Browser

Firefox

### Browser Version

119

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @GrizzlyAK,

Thank you for reporting this. I tested this with Firefox 120.0.1 and Bitwarden browser extension 2023.10.2 whilst having (Always use private browsing mode) under (History) in Firefox's (Privacy & Security) section activated; The (Unlock with PIN) function in the Bitwarden browser extension worked as expected and the checkmark (tick) was there after activating the function and after navigating through the different menus in the extension, and this was tested with and without requiring master password on browser restart. I recommend that you first update your browser and if that does not help, please proceed and uninstall the Bitwarden browser extension off that browser, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), and then install it anew.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by Bassetts** [comment]
I am also having this issue. I can set a PIN if "Lock with master password on restart" is unticked, but if I tick it then the PIN setting does not persist.

I am on build 2023.10.2 and Firefox version 120.0.1. I tried removing the extension and all leftover data and re-installing but the problem persisted.

**Comment by GrizzlyAK** [comment]
@Bassetts, agreed. I just updated FF to 120.0.1 and BW was already at its latest version. It is NOT resolved. When I tick Use Master Password upon Browser Restart, enter a PIN, and return, the check mark Unlock with PIN is checked. But if I exit out of the BW plugin and then re-enter it, the Unlock with PIN is _unchecked_ and I have to enter the MP every time. Unless I leave Use Master Password unchecked when I enter a PIN, forcing me to use a PIN ALWAYS, this functionality is BROKEN. I really wish they'd get this fixed. I've been reporting it for well over a year now and still it is "not planned". In one such encounter with tech support, he was able to reproduce it repeatedly (_finally_,... I guess the devs never actually use this functionality themselves). Doesn't say much BWs thinksing about security, does it? 

I do realize that working with Mozilla in any form is a nightmare, which may be part of the problem here. I despise the organization myself. But we are all forced to deal with it if we want to continue using their products. As soon as there is a viable alternative...
