### ISSUE TITLE
The words "and complete two step login setup" are wrong

### ISSUE THREAD

**Issue by jidanni** [bitwarden/clients#7084]
The words "and complete two-step login **setup**" are wrong.
![20231116T085755](https://github.com/bitwarden/server/assets/1230959/32c08b65-ccce-4a7e-9151-3f8759c8c737)
They should be "and complete two-step **login**, **if any**."

(Seen on the Low KDF iterations warning on https://vault.bitwarden.com/#/vault .)

**Comment by djsmith85** [comment]
Hi @Emmanu3l, 

Thank you for offering your help with this. Github issues, don't get assigned, but feel free to open a Pull Request with your changes and [link to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/), these will help you with getting your environment set up and offer further information in regards to contributing.

Kind regards,
Daniel
