### ISSUE TITLE
BUG: CLI list item error 

### ISSUE THREAD

**Issue by bxb100** [bitwarden/clients#7126]
### Steps To Reproduce

1. brew install latest Bitwaden-cli 2023.12.0
2. login in
3. run `bw list items --session xxxxx`

### Expected Result

show data without error

### Actual Result

correct show vault data but returns an error

### Screenshots or Videos

<img width="931" alt="image" src="https://github.com/bitwarden/clients/assets/20685961/af82b7c8-c930-484f-80d9-2543c5f33767">

### Operating System

macOS

### Shell

Zsh

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bxb100** [comment]
That fix will also reduce the lock retry and wait-for timeout cost, so it improves the CLI list load time

**Comment by luckman212** [comment]
When will this fix be pushed, this broke a lot of my workflows :(

**Comment by bxb100** [comment]
> When will this fix be pushed, this broke a lot of my workflows :(

I don't know, there none employee's response.
but I know the time is tick-tock, drive me to the 1pass : )

**Comment by r0hin** [comment]
The PR is an important fix for a breaking bug that destroys BW users' workflows @krychaz @cd-bitwarden

**Comment by ttalty** [comment]
> > When will this fix be pushed, this broke a lot of my workflows :(
> 
> I don't know, there none employee's response. but I know the time is tick-tock, drive me to the 1pass : )

The PR @bxb100 created I approved and it is currently being tested. We really appreciate the contribution and this is going to be fixed quickly.

**Comment by Geezus42** [comment]
It's already been a week. Also, this should have been tested before the release of whatever changes caused the breakage. 

I don't mean to be rude, but I expect better from a for-profit company that I am paying for a service.

**Comment by Geezus42** [comment]
> The PR @bxb100 created I approved and it is currently being tested. We really appreciate the contribution and this is going to be fixed quickly.

It's already been a week. Also, this should have been tested before the release of whatever changes caused the breakage.

I don't mean to be rude, but I expect better from a for-profit company that I am paying for a service.

**Comment by nachobazz** [comment]
I have the same issue and see this closed, but no updated version to install in Brew 2023.12.0:

Error when running bw list items:

`Error: Lock file is already being held
    at /opt/homebrew/Cellar/bitwarden-cli/2023.12.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/opt/homebrew/Cellar/bitwarden-cli/2023.12.0/libexec/lib/node_modules/@bitwarden/cli/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:202:5) {
  code: 'ELOCKED',
  file: '/Users/[my-user]/Library/Application Support/Bitwarden CLI/data.json'
}
` 
Brew upgrade result:

`brew upgrade bitwarden-cli
Warning: bitwarden-cli 2023.12.0 already installed
`

**Comment by ttalty** [comment]
The hotfix for this has been released.

**Comment by nachobazz** [comment]
I just updated the Brew formulae and worked like a charm. Thanks folks! 🙏
