### ISSUE TITLE
Layout overlay when storing a passkey 

### ISSUE THREAD

**Issue by GabrielZalisz** [bitwarden/clients#7136]
### Steps To Reproduce

1. Pick any web that supports passkeys and for which you have mulitple (3 or more) credentials stored in Bitwarden.
2. Try to create passkey. Bitwarden will prompt you to save the passkey.
3. "Use browser" overlays "Save passkey" button. Button is only clickable on the very top. 

### Expected Result

"Save passkey" button should be easily clickable, "Use browser" should be either above it or below it. 

### Actual Result

"Use browser" overlays "Save passkey" button.

### Screenshots or Videos

![Snímek obrazovky 2023-12-06 074741 - kopie](https://github.com/bitwarden/clients/assets/45824535/8460139d-86f5-4fdd-a651-8b11b7dfe9f6)

### Operating System

Windows

### Web Browser

Brave

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

In the meantime, you can extend the passkey prompt window by clicking and dragging the bottom edge of the window. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by trmartin4** [comment]
Hi @GabrielZalisz!  We have made some adjustments to the UI of the passkey prompt on the extension, and we are no longer able to replicate the issue.  Could you please attempt to reproduce on the latest browser extension version?

**Comment by GabrielZalisz** [comment]
Hi @trmartin4! According to my observation, the issue still exists in Bitwarden browser extension ver. 2023.12.1. This is the newest version available in Chrome Web Store.

**Comment by GabrielZalisz** [comment]
@trmartin4, the issue is fixed in Bitwarden browser extension ver. 2024.1.1.
