### ISSUE TITLE
When inviting a new organizational member, Input is required is shown below the email address field after pressing return (Enter).

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#7156]
### Steps To Reproduce

1. Navigate to the organizational (Members) menu and press on (Invite member).
2. Use the mouse to click on the (Email) field and type the email address.
3. Press Return (Enter) on the keyboard.

### Expected Result

To invite that email address into the organization.

### Actual Result

The modal remains on screen and (Input is required.) is shown below the (Email) field in red.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/73389600/1ced1676-aeda-4096-adaa-e29d4a63cd5d)

### Additional Context

If you ignore the (Input is required.) message and press on (Save), the invitation is sent.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by frederikprijck** [comment]
I was able to reproduce this and have a fix ready in my fork, just needs some clean up. I will open a PR by end of day!
