### ISSUE TITLE
bw sync and bw export fails

### ISSUE THREAD

**Issue by tendervittles** [bitwarden/clients#7158]
### Steps To Reproduce

Unlock and export BW_SESSION.

Issue `bw sync`:
```
~$ bw sync
Syncing failed: TypeError: Cannot read properties of undefined (reading 'trustedDeviceOption')
~$ 
```
Issue `bw export`:

```
~$ bw export --format json 
Cannot save file to /home/tendervittles/bitwarden_export_20231210150019.json
~$ 
```

### Expected Result

These commands used to work.

### Actual Result

Now they error.

### Operating System

Linux

### Operating System Version

Linux dev 6.2.0-37-generic #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Shell

Bash

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by flyin** [comment]
@tendervittles I've faced the same issue. Did you manage to fix it?

**Comment by flyin** [comment]
@tendervittles thanks for your response. it seems `bw logout` and `bw login` can be also used as workaround

**Comment by philpennock** [comment]
Confirm that I encountered this following a `snap` update last week, and that @flyin's fix above -- log out and in again -- was sufficient to resolve.
