### ISSUE TITLE
Plugin not loading in context menu

### ISSUE THREAD

**Issue by mr-manuel** [bitwarden/clients#7171]
### Steps To Reproduce

1. Open Firefox
2. Go to any login page
3. Right click on the username field
4. Now the Bitwarden entry in the context menu is missing
    ![grafik](https://github.com/bitwarden/clients/assets/12592765/19baf5f6-7f02-4ae3-9858-33bdc6d4c047)

This is a big issue when you have login forms in a popup (like PayPal) where the Bitwarden icon in the upper bar is not displayed.

### Expected Result

Bitwarden should show in the right click context menu as before.

### Actual Result

The Bitwarden entry in the context menu is missing

### Screenshots or Videos

Provided aboe

### Operating System

Windows

### Operating System Version

Windows 11 22H2

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team. 

As a workaround, we recommend using the keyboard shortcut to autofill: https://bitwarden.com/help/keyboard-shortcuts/

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by mr-manuel** [comment]
Unfortunately the keyboard shortcut does not work, if you have to choose between multiple entries.

**Comment by sarah-vo** [comment]
Hi @mr-manuel! I was not able to reproduce the issue at client version 2023.12.0. This was on a clean Firefox install.

<img width="1512" alt="image" src="https://github.com/bitwarden/clients/assets/66108082/07b5c9fa-8e48-41c2-824b-5e3eba722e5d">

**Comment by mr-manuel** [comment]
Very strange. I completely wiped my Firefox profile and tried again. Same issue. Is there something I can check somewhere?

![grafik](https://github.com/bitwarden/clients/assets/12592765/a0927210-fc17-49d5-8814-6ab938bb28d3)

**Comment by mr-manuel** [comment]
After the last Firefox update this issue solved itself.
