### ISSUE TITLE
Syncing Issue with Bitwarden Add-on in Firefox

### ISSUE THREAD

**Issue by fiver22** [bitwarden/clients#7243]
### Steps To Reproduce

1.  Open Firefox with Bitwarden add-on installed.
2.  Navigate to Bitwarden add-on settings.
3.  Attempt to manually sync via "Settings > Sync > Sync Vault Now".

### Expected Result

The Bitwarden add-on should successfully sync data between Firefox and other devices.

### Actual Result

The manual sync fails, displaying a “Syncing failed” error message. 

### Additional Context

- Manually logging out and back in fixes the issue for, at least, some users.
- new items created in the Firefox add-on sync to other devices.

Troubleshooting Performed by Original Poster:

1.     Verified updates for both Firefox and Bitwarden add-on.
2.     Checked stable internet connection.
3.     Restarted Firefox.
4.     Inspected Firefox Console Logs with no relevant output during sync issue.

Additional Community Insights:
 (via https://community.bitwarden.com/t/syncing-issue-with-bitwarden-firefox-add-on-syncing-failed-error/61105)

    User "Dax" reported a similar issue, resolved by logging out and back into Bitwarden on both Windows desktop and Firefox add-on.
    User "Doogie" experienced the same issue; however, inspecting the pop-out add-on window for console and network errors showed no logs.
    User "Dax" (in a second reply) indicated that changing the account settings (increasing KDF iterations in the Bitwarden Web Vault) resolved the issue after it re-initiated a login session.
    
   

### Operating System

Linux

### Operating System Version

6.6.5-arch1-1

### Web Browser

Firefox

### Browser Version

120.01 (64bit)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by github-luciano** [comment]
Logging out and back in fixed the issue for me. 

Firefox 120.0.1
Bitwarden version 2023.12.0

**Comment by basking2** [comment]
The same problem and work-around is present in Brave 1.61 on Linux and MacOS.

**Comment by henriklund** [comment]
Win11, Chrome and 2023.12 shows this problem (2023.10.1 does no). Changing the KDF resolved the issue for me

**Comment by fxzxmicah** [comment]
Same on MS Edge.

**Comment by wereii** [comment]
Firefox 120.0.1, Windows 11 Pro, I can see the new credential in the web vault but the extension fails to sync it, forcing it thru settings results in the same “Syncing failed” error message.

Inspecting the extension and watching console does not show any errors.

**Comment by bluppfisk** [comment]
Same here, logging out and back in works. I would have a look at the issue itself if someone could kindly point me in the direction of the code responsible for session management (and if there's some guidance on how to test and get logging info, that would also help).

**Comment by miohsu** [comment]
您的邮件已收到，谢谢。

**Comment by lflaurflorin** [comment]
Directed here from a duplicate report.
The issue persists now from the desktop app as well.

Version 2023.12.0
Windows 11 x64 build 22631.2861
Shell 25.9.1
Renderer 114.5735.289
Node 18.5.0
Architecture x64

**Comment by lflaurflorin** [comment]
> Win11, Chrome and 2023.12 shows this problem (2023.10.1 does no). Changing the KDF resolved the issue for me

Thank you for this ❤️

**Comment by fiver22** [comment]
Where my KDF iterations were already within suggested range I did NOT change mine. I simply logged out manually and logged back in.
Is it possible that changing the iterations forces logout and login and that is what is causing the 'fix'? 
By all means, update to recommended number of KDF iterations! Just not certain it is THAT that is causing the 'fix'

**Comment by henriklund** [comment]
Interestingly enough, I have recently started using an old laptop again (+6months sinve last logged in). Changing the KDF was the resolution there. At work I have another one (selfhosted as well) where I have never been logged in (ie. been able to) using the desktop client. Same error. I guess tomorrow is going to be the day where I change the KDF to see if I manage to log in for the first time.

**Comment by danhawkes** [comment]
I've started seeing this on multiple devices. Tried logging out, and back in on one device, and that resolved it there.

On another device, I see the error caught in `sync.service.ts` is:

![image](https://github.com/bitwarden/clients/assets/3388897/55d6660b-6f2c-4a96-aa2e-6a8d5b6785fa)

```log
message: 
"t is undefined"

stack:
"25494/setForceSetPasswordReasonIfNeeded/<@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:414277
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407608
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
25494/$a/<@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407784
$a@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407551
setForceSetPasswordReasonIfNeeded@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:413913
25494/syncProfile/<@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:413466
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407608
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
25494/$a/<@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407784
$a@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407551
syncProfile@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:412605
25494/fullSync/<@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:408993
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407608
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
promise callback*l@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407773
o@moz-extension://f0fc39fe-3856-458f-aa90-cb74386b13be/background.js:1:407605
```

**Comment by grahammitchell** [comment]
I had the same issue, and logging out and logging back in fixed it.

Google Chrome: Version 120.0.6099.129 (Official Build) (arm64)
macOS: Sonoma v14.1.1
Bitwarden extension: Version 2023.12.1
Server version: 2023.12.1

The "last sync" shown in the extension menu seemed reasonable, but there were new entries I'd created on my other machine that weren't showing up, and when I clicked "Sync vault now" it just gave me the syncing failed error.

Glad I have a workaround and hopefully y'all can figure out the root cause of the bad UX.

**Comment by michaelkvance** [comment]
> The Bitwarden add-on should successfully sync data between Firefox and other devices.
There's a secondary issue which is that the sync failure displays no useful information to indicate what has gone wrong, nor is it obvious as to how to perform any diagnostics. In addition to the root cause this poor UX should be rectified.

**Comment by LunNova** [comment]
This issue was closed but the linked issue is described as a bandaid which doesn't fix the root cause. Should it be reopened?

**Comment by Orgoth** [comment]
I have the same issue and logging in and out does not solve the issue.
How can we help when there is now error-message or log for the cause of the issue and to provide you with data?!
At least add a option within the extension, where we can open the error log, to see what happened, to help you solve the issue.

Windows 10 Pro 22H2 19045.3803
Chrome 120.0.6099.130 (Offizieller Build) (64-Bit)
Extension/Server: 2023.12.1

**Comment by michaelkvance** [comment]
> This issue was closed but the linked issue is described as a bandaid which doesn't fix the root cause. Should it be reopened?

I don't think it's clear that the workaround pushed last week has reached retail. @JaredSnider-Bitwarden would be able to say as he pushed the change.

**Comment by trmartin4** [comment]
@michaelkvance this will be included in our next client release, which will be later this month.

**Comment by vladimirgluten** [comment]
Still broken for me as of 1/3/24.  Logging out and back in seems to work but it's completely bullshit that we have to do that.  I have at least 2 different browser extensions (firefox and chrome and/or Edge) on at least 5 computers.  Having to log out and back in 10+ times is unacceptable for something that has been working FLAWLESSLY for over 2 years since I switched to Bitwarden.

**Comment by vladimirgluten** [comment]
> Where my KDF iterations were already within suggested range I did NOT change mine. I simply logged out manually and logged back in. Is it possible that changing the iterations forces logout and login and that is what is causing the 'fix'? By all means, update to recommended number of KDF iterations! Just not certain it is THAT that is causing the 'fix'

Maybe the act of changing the KDF does something, but just having it set to a higher number doesn't work.  I had mine already set to 600000 and I am currently having the sync issue.

**Comment by mgscreativa** [comment]
Confirm that logging out and then log back in works!

**Comment by LunNova** [comment]
This can cause some data to be lost or hard to recover since there's no way to export what's failing to sync before logging out and in, and due to lack of notification you might not even know nothing is being synced.

Ideally the fix should be released faster than the normal release schedule as a hotfix since password manager sync issues are the sort of issue that can cause people to swap to a different product.

**Comment by Orgoth** [comment]
> @michaelkvance this will be included in our next client release, which will be later this month.

If the logout variant leads to data loss without the user being directly aware of it, this is actually an unacceptable situation that must be rectified as quickly as possible.
On some days it can happen that I save several logins, and if the logins are lost the next day when I log in on the other PC, it's a disaster.

Then to be told that the next update will come sometime during the month or the following month is a disaster.

I understand that it is an open source project, but data loss should be considered critical and it must be fixed immediately!

**Comment by luckydonald** [comment]
The last two monthly `*.0` versions were released on day 6. and 7. of the month, so hopefully a new version lands the next two days.

**Comment by McNutnut** [comment]
Starting to have our users reporting oddity with their vaults; items not being saved/updated/disappearing.  An extension update ASAP would be preferred than globally requesting all our users to sign-out and back in.  By the time the issue is noticed by end-users, the data is already at risk of being lost.  Especially given that there's no notification to the user that syncing is failing, unless they attempt a manual sync.  Vaults that haven't been syncing for 5 days and users had no idea.

**Comment by Orgoth** [comment]
Please get the problem fixed, it is getting worse.
I have now to write down new accounts and passwords to insert them on the other PCs since the workaround does not work and I am missing saved data on each pc and have to add these back manual.

@Krychaz @trmartin4 @cagonzalezcs

**Comment by trmartin4** [comment]
@Orgoth we will be submitting version `2024.1.0` of the extensions to stores within the next day.  This has a fix for the sync problem that you and other have described.  We do not control all of the release timing as we do submit to stores first for approval.

We appreciate your patience as we found a resolution for this issue, we realize the impact that it had on affected users and hope that the new version resolves any problems you were seeing.

**Comment by jimmyj352** [comment]
I was one of the lucky ones where logging out and logging back in fixed the problem and no data was lost.

Would it make sense to show a banner or change the extension icon to a different color or something to notify the user when syncing fails or when it fails multiple times within x amount of time? Maybe clicking on the extension icon would then take you right to the syncing failed screen? This would help users at least be in the know that there's a problem.

Just a thought.

**Comment by T2MWorks-Mitch** [comment]
changing the KDF settings worked for me

**Comment by fxzxmicah** [comment]
All problems have been fixed. Please update to the latest version if you still have problems. Stop talking about temporary solutions.
