### ISSUE TITLE
Invasive when not even in use

### ISSUE THREAD

**Issue by garygreen** [bitwarden/clients#725]
When using the Chrome browser extension, when you click on a checkbox on the page the element gets a:

> data-com.bitwarden.browser.user-edited="yes"

Attribute added to it.

![image](https://user-images.githubusercontent.com/1702638/45427680-565c3300-b697-11e8-8f49-818f712c0aed.png)

This page has:

* NO credentials on it (no password input, it's a contact form, not a login form)
* Bitwarden is not in use or been interacted with manually at all.

So my question is, isn't this a bit invasive? Why is Bitwarden seemingly interested in form elements on a page that it should have no business in? It get's me worried.

IMO, Bitwarden should only ever initialise MINIMAL code in order to determine if the page contains a form with credentials. In all other instances, there should be no code or invasive elements or listeners added to the page.

**Comment by kspearrin** [comment]
You can view the autofill code that does this here:
https://github.com/bitwarden/browser/blob/master/src/content/autofill.js

**Comment by garygreen** [comment]
It even does it when your using something like CodePen:

![image](https://user-images.githubusercontent.com/1702638/45428389-0e3e1000-b699-11e8-8cad-b72f630b1afc.png)

https://codepen.io/garygreen/pen/aaGBbV

It's pretty ridiculous that it's this invasive.

**Comment by mirraj2** [comment]
I agree this is super annoying.  I'm developing a website and bitwarden is modifying my html when I haven't even clicked on the bitwarden plugin and the page itself has zero password fields on it.

**Comment by garygreen** [comment]
@kspearrin any news on this? I still find it a bit concerning how much Bitwarden chrome extension interferes with all pages. It should only inject/enable the most minimal amount of code when it needs to, not on every page load.

**Comment by ianling** [comment]
This leaks the fact that the user is using Bitwarden as their password manager to the server.

**Comment by ScalaWilliam** [comment]
Had this just now as well, this is quite a serious issue, especially when using `contenteditable`.

**Comment by sleepyArpan** [comment]
![bitwarden](https://user-images.githubusercontent.com/50901152/114710612-8dad8780-9d4b-11eb-8951-81a388a4d102.png)

Just came across this issue while development, in the image theres a radio button in checked state but it looks like its not checked and upon inspecting I found out that the input type had the above mentioned data attribute on it.

**Comment by NOVATechnocrat** [comment]
> This leaks the fact that the user is using Bitwarden as their password manager to the server.

How so? Does this not just manipulate data on the DOM, locally?

**Comment by climbTheStairs** [comment]
> > This leaks the fact that the user is using Bitwarden as their password manager to the server.
> 
> How so? Does this not just manipulate data on the DOM, locally?

Yes, that's what it does. And JavaScript running locally can easily detect this and send it to the server.

**Comment by emericv** [comment]
Extension interferes, example here :
![image](https://user-images.githubusercontent.com/1727636/163038018-725413ec-6ccb-4add-954d-0a0bb1f84598.png)

Nextcloud extension https://github.com/shiningw/ncdownloader

**Comment by pkkid** [comment]
This issue should still be addressed as it also breaks functionality on some websites. Mainly when Bitwarden tries to make a  contenteditable input as user-edited, it causes an Index Error. See https://github.com/ueberdosis/tiptap/issues/2697

**Comment by SarcevicAntonio** [comment]
I'd love for my password manager to not break my websites ✌️

Please fix this!

**Comment by 666-flexxx-666** [comment]
Would love to see fix for this BitWarden.

**Comment by dbosompem** [comment]
Hi all, thank you for bringing this to our notice; looks like this has been lingering for a while. I'd pass this on to the team and we will make time to take a look!

**Comment by suchintan** [comment]
@dbosompem Do you know when this will be resolved??

**Comment by hkbertoson** [comment]
@dbosompem Do you know if this issue is on any type of roadmap? It causes issues on certain sites for me.

**Comment by flexagoon** [comment]
@dbosompem please "take a look". While this is not *the most* serious issue, it is pretty serious.

**Comment by hkbertoson** [comment]
> Hi all, apologies nearly missed this. Thanks for the callout. I'd have a discussion with the team on when we can resolve this, as we might have to take a look at the autofill script. Apologies for the inconvenience caused and thank you for your patience so far. I'd reply to this thread once there's a known ETA for this fix.

This would be great! If we could even just blacklist certain sites. That would be great.

**Comment by flexagoon** [comment]
@dbosompem I looked at the autofill source code and it doesn't look like the userEdited variable is even used anywhere in the code.

**Comment by hkbertoson** [comment]
@dbosompem I believe I fixed the issue with #4001 I tested it out and nothing seemed to be broken.

**Comment by dbosompem** [comment]
@hkbertoson thank you for the kind consideration. The team will make time and take a look at the PR.

**Comment by hkbertoson** [comment]
@dbosompem Any updates on this?
