### ISSUE TITLE
Opera extension window doesn't close after logging in when ctrl+shift+L are used

### ISSUE THREAD

**Issue by vasiliev123** [bitwarden/clients#7251]
### Steps To Reproduce

1. The vault must be locked
2. Use Ctrl+Shift+L to log on any site
3. The second window with bitwarden pops up
4. Type in your master password
5. The credentials are successfully being typed on your site by bitwarden but the second window with extension doesn't close automatically and stays open until you close it manually.

### Expected Result

The second window with bitwarden extension should close automatically after typing in master password. It works in for example Chrome

### Actual Result

The second windows with bitwarden extension stays open eternally after typing in master password and we need to close it manually.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Opera

### Browser Version

Opera GX 104.0.4944.85

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @vasiliev123,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by cagonzalezcs** [comment]
Hello @vasiliev123 

Thank you for the bug report details.

We recently merged in some [work for the context menu](https://github.com/bitwarden/clients/pull/7724) that was likely causing this problem. It was an issue in other browsers, not just Opera.

I've tested the described behavior with the extension built from our `main` branch, and the problem doesn't seem to exist any longer.

These changes should be coming with the next release of the extension. As a result, I'm closing this thread. Please feel free to continue discussion if that is necessary.
