### ISSUE TITLE
Extension sometimes shows empty vault after logging in

### ISSUE THREAD

**Issue by warwickmm** [bitwarden/clients#7253]
### Steps To Reproduce

1. Log out of the extension.
2. Hit Ctrl + Shift + L to bring up the login page.
3. Log in.
4. Notice that the vault is empty.

### Expected Result

The vault should show all the saved entries.

### Actual Result

The vault is sometimes empty after logging in.

### Additional Context

I'm not sure how to reproduce this reliably, but it feels like it happens around 50% of the time I'm trying to use the extension.  When this does happen, there are 2 remedies that seem to work.

1. Log out and log back in.

or

2. Go to Settings -> Sync and manually trigger a sync.

### Operating System

Linux

### Operating System Version

Arch Linux with 6.6.7 kernel

### Web Browser

Brave

### Browser Version

Version 1.61.100 Chromium: 120.0.6099.62 (Official Build) (64-bit)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @warwickmm,

Thank you for reporting this. I would recommend proceeding with a fresh new installation; Please uninstall that extension, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the machine, and install it anew. Also, you can create a new browser profile and test it there to check if a non-default browser setting/configuration or possibly another extension if affecting this. I state that as I was unable to reproduce this behaviour.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket. As a side note, I'd recommend also mentioning how many vault items you have in your vault, and the [KDF Settings](https://bitwarden.com/help/kdf-algorithms/) that you have set in your account.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues as a place to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
