### ISSUE TITLE
"Syncing failed" in AppImage

### ISSUE THREAD

**Issue by tnonate** [bitwarden/clients#7254]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Sync Vault'

### Expected Result

The vault syncs

### Actual Result

I get an error message in the top right corner saying "Syncing failed."

### Screenshots or Videos

![bitwarden](https://github.com/bitwarden/clients/assets/133825060/f3c83778-51ae-46f8-a15b-253225691449)

### Additional Context

I am using Qubes, Fedora 38. However, all other apps are working as expected, only Bitwarden is misbehaving. I have tried routing through Mullvad VPN, clearnet, and Whonix, all with the same result. I have tried different wifi networks. To my knowledge, nothing has been updated or changed recently (as in "within the last week or so") that would affect this (and again, everything else is working as expected). Happy to share any logs or answer any questions to help troubleshoot.

### Operating System

Linux

### Operating System Version

Fedora 38

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Hi @tnonate.  This appears to be related to the issue documented here: https://github.com/bitwarden/clients/issues/7243, which does not appear to be limited to just the Firefox extension.  We are currently investigating the root cause.

**Comment by AFwcxx** [comment]
Also using Fedora 38.
Had this issue on both desktop and Firefox addon.
Seemed to work on both after log out and log back in.

**Comment by tnonate** [comment]
> Also using Fedora 38. Had this issue on both desktop and Firefox addon. Seemed to work on both after log out and log back in.

Can confirm this worked for me. Not a great solution IMO, but I guess we mark this closed if that's the best we got since it does seem to work.

**Comment by aldehydkrotonowy** [comment]
I have same error. (Ubuntu 22.04.4 LTS, Bitwarden-2024.4.1-x86_64.AppImage) . Moreover when I try to create new item and save it I have error: "Failed to decode access token. JWT must have 3 parts"
