### ISSUE TITLE
WebAuthn API violation

### ISSUE THREAD

**Issue by zacknewman** [bitwarden/clients#7259]
### Steps To Reproduce

Register a WebAuthn key and look at the raw HTTP JSON payload.

### Expected Result

The JSON to conform to the WebAuthn spec.

### Actual Result

The JSON for `deviceResponse` is invalid. Both `AttestationObject` and `clientDataJson` violate the WebAuthn spec. [`AuthenticatorAttestationResponse`](https://www.w3.org/TR/webauthn-2/#authenticatorattestationresponse) requires the first field to be `attestationObject`, and [`AuthenticatorResponse`](https://www.w3.org/TR/webauthn-2/#authenticatorresponse) requires the latter to be `clientDataJSON`.

### Additional Context

After replacing all instances of `AttestationObject` with `attestationObject` and `clientDataJson` with `clientDataJSON` in the below files, the correct payload was sent:

`apps/web/src/app/main.b193f247301cc37bf60b.js`
`apps/web/src/app/main.b193f247301cc37bf60b.js.map`
`apps/web/src/connectors/webauthn.b50e3a9527b3e4de41eb.js`
`apps/web/src/connectors/webauthn.b50e3a9527b3e4de41eb.js.map`
`apps/web/src/connectors/webauthn-fallback.4c0785415d6ab725a060.js`
`apps/web/src/connectors/webauthn-fallback.4c0785415d6ab725a060.js.map`

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Thanks for reporting this to us - as this communication would relate specifically to the Bitwarden client and server, do you have a particular requirement or need for Bitwarden to adhere to the standard here?

**Comment by sammbw** [comment]
Since compatibility with 3rd party servers is unfortunately not something that we officially support, addressing this issue is not going to be high on our prioritization. Please keep in mind that the design of our web API used by our clients favors flexibility and can change without any prior warning as we work to bring our users the latest features as quick as possible.

**Comment by coroiu** [comment]
I just want to start out by saying that we do not view this as a violation of the WebAuthn specification. Applications are free to choose whatever format they want when communicating with their backend.

-----------------------------------------

My understaing is that you are referring to the WebAuthn L3 Working Draft document (https://www.w3.org/TR/webauthn-3/)  , specifically the `toJSON` method (https://www.w3.org/TR/webauthn-3/#dom-publickeycredential-tojson) that was added as part of https://github.com/w3c/webauthn/pull/1703 which specifies how browsers must implement JSON serialization of WebAuthn related objects.

The important point here is that the WebAuthn standard defines the interface between javascript applications and the browser. It does not define how RPs (e.g. Bitwarden) should send data to their respective backends. Not taking advantage of certain parts of that interface does not result in a violation of the specification.

Please also keep in mind that the `toJSON` method is currently marked as experimental https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/toJSON#browser_compatibility

**Comment by Hinton** [comment]
Hi,

As @coroiu wrote the specification doesn't cover internal communication within a web application. I've cited some relevant sections below explicitly clarifying this.

> A [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) implementation typically consists of both some client-side script that invokes the [Web Authentication API](https://www.w3.org/TR/webauthn-3/#web-authentication-api) in the [client](https://www.w3.org/TR/webauthn-3/#client), and a server-side component that executes the [Relying Party operations](https://www.w3.org/TR/webauthn-3/#sctn-rp-operations) and other application logic. Communication between the two components MUST use HTTPS or equivalent transport security, but is otherwise beyond the scope of this specification.
>
> <cite>https://www.w3.org/TR/webauthn-3/#web-application</cite>

> It must then deliver the contents of this structure to the [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) server, using methods outside the scope of this specification.
>
> <cite>https://www.w3.org/TR/webauthn-3/#sctn-rp-operations</cite>

Closing this.
