### ISSUE TITLE
synchronization failed

### ISSUE THREAD

**Issue by andersoneriksson** [bitwarden/clients#7261]
### Steps To Reproduce

I can't synchronized. Showed the message: ![BitWarden_Support](https://github.com/bitwarden/clients/assets/91257919/be024ce3-454d-4bc3-aa9a-64f5af99410e)

### Expected Result

Synchronization with success.

### Actual Result

Synchronization failed.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/91257919/ec67e63a-3dda-436a-8e95-68bd75d0029f)

### Operating System

Windows

### Operating System Version

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @andersoneriksson. This appears to be related to the issue documented here: https://github.com/bitwarden/clients/issues/7243, which does not appear to be limited to just the Firefox extension. We are currently investigating the root cause.
