### ISSUE TITLE
Bitwardin 2023.12.1 Auto-Fill not working correctly (Part 2)

### ISSUE THREAD

**Issue by DjKilla2** [bitwarden/clients#7315]
### Steps To Reproduce

1. Go to many websites and use Auto-Fill to fill forms

### Expected Result

Auto-Fill worked with Autofill v1 flag.

### Actual Result

https://reesespecialtyfoods.com/sweepstakes/  (form doesn't fill)
https://apfco.com/Secured/S9133/AgeGate?returnURL=https://apfco.com/Secured/S9133/  ((after entering birthdate, form doesn't fill)
https://www.littlepotatoes.com/holiday-happiness/  (form doesn't fill)
https://woobox.com/i8h43m  (form doesn't fill)
https://www.visitomaha.com/giveaway/  (form doesn't fill)
https://woobox.com/k66y9m  (form doesn't fill)
https://microperfumes.com/?page=land/xmas12/  (form doesn't fill)
https://jenniferhudsonshow.com/2023/12/15/the-color-purple-giveaway-bundle/  (form doesn't fill)
https://apfco.com/Secured/WB1811/S9187  (form doesn't fill)
https://www.cricketsweepstakes.com/wwe  (form doesn't fill)
https://app.viralsweep.com/sweeps/full/7007b9-149195  (form doesn't fill)

### Additional Context

Autofill no longer works correctly with Autofill v2 flag (v1 flag worked).

Expected fix either doesn't work or hasn't been implemented yet. Please see the following:
https://github.com/bitwarden/clients/issues/7202
https://github.com/bitwarden/clients/pull/7209

***Forms will fill in if you refresh/reload the page ONLY if form is in view on the screen.

### Operating System

Windows

### Operating System Version

Windows 10 22H2 build 19045.3803 (64-bit)

### Web Browser

Firefox

### Browser Version

Firefox 121.0 (64-bit)

### Build Version

Firefox 121.0 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@DjKilla2 

I tested several of these forms using the latest build within the recently cut release branch. These are filling effectively with the changes in that branch. These likely were facing the same issue found within https://github.com/bitwarden/clients/pull/7209 

I'm closing this thread for now, as the upcoming release of Bitwarden should resolve these autofill issues conclusively.
