### ISSUE TITLE
TOTP to clipboard does not work with "Show auto-fill menu on form fields"

### ISSUE THREAD

**Issue by Sector6759** [bitwarden/clients#7354]
### Steps To Reproduce

1. Open the browser extension
2. Select "Settings"
3. Select "Auto-fill"
4. Check "Override browser auto-fill settings"
5. Set "Show auto-fill menu on form fields" to "When field is selected (on focus)" or "When auto-fill icon is selected"
6. Browse to a website for which you have a Bitwarden login entry with TOTP
7. Go to the login page
8. Click into the username/email or password field
9. Select the Bitwarden auto-fill entry next to the input field
10. Proceed with login
11. When asked to insert TOTP, try to paste the TOTP with `CTRL` + `V`

### Expected Result

TOTP being copied to the clipboard.

### Actual Result

TOTP is not copied to the clipboard.

### Additional Context

Auto-filling by pressing the keyboard shortcut or manually selecting the login entry in the browser extension is not affected.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

120.0.6099.130 (Official Build) (64-bit)

### Build Version

2023.12.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment]
@Sector6759 Thank you for your bug report.

We have merged in a fix for this issue within https://github.com/bitwarden/clients/pull/7427 

The fix for this will be present in the Bitwarden extension release for v2024.2.0
