### ISSUE TITLE
Authentik - Unable to identify a valid form element. Try inspecting the HTML instead.

### ISSUE THREAD

**Issue by modem7** [bitwarden/clients#7358]
### Steps To Reproduce

Visit to Authentik login page
Select "Bitwarden | Copy custom field name"
Paste buffer now contains "Unable to identify a valid form element. Try inspecting the HTML instead."

### Expected Result

A copy of the form element should be in the paste buffer.

### Actual Result

Paste buffer contains "Unable to identify a valid form element. Try inspecting the HTML instead."

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/4349962/a37a9693-668a-4393-9752-28dec9c5d8c8)

### Additional Context

Happy to share my Authetik instance URL privately for further diagnosis.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023-12-1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @modem7 

Could you please provide us with the URL you visited on the first step?
_Visit to Authentik login page_

**Comment by modem7** [comment]
Resolved in https://github.com/goauthentik/authentik/issues/7993#issuecomment-1870380183
