### ISSUE TITLE
No View event is logged in the Event Logs when an Admin-type or Owner-type with no direct access to the relevant collection views an item's password.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#7362]
### Steps To Reproduce

1. Create a dummy Login-type vault item in an organization vault.
2. Invite and confirm a new member as an Owner-type.
3. In that new organizational member's (Edit member) modal, keep (Grant access to all current and future collections.) unticked under the (Collections) tab, and do not assign them any permissions to collections.
4. Log in as that new Owner-type and view the dummy vault item's password.
5. Check the event logs.

### Expected Result

The event logs should log that as action as ([Viewed password for item](https://bitwarden.com/help/event-logs/#item-events)).

### Actual Result

That action is not logged the event logs.

### Screenshots or Videos

N/A

### Additional Context

Related to (https://github.com/bitwarden/web/issues/885).

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

121.0

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Thanks for the report @SergeantConfused

If anybody else wishes to add any further information/screenshots/recordings etc., please feel free to do it here - Bitwarden's engineering team will be happy to review these.

**Comment by atjbramley** [comment]
This has been fixed by the following Pulls:

https://github.com/bitwarden/server/pull/4705
https://github.com/bitwarden/clients/pull/10678

If anyone continues to experience this, please do not hesitate to open a _new_ report on GitHub, or contact the support team via the normal channels.
