### ISSUE TITLE
Mac desktop app failing sync request

### ISSUE THREAD

**Issue by djhau** [bitwarden/clients#7376]
### Steps To Reproduce

1/ Go to File menu
2/ Sync Vault

### Expected Result

Sync working and message says it worked ok.

### Actual Result

Sync is failing

### Operating System

macOS

### Installation method

Mac App Store

### Build Version

Version 2023.12.1 (16254)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
Thank you for checking up on this. Could you please log out (File/Settings > Log Out) and log back in to refresh your session and let me know if that helps? We've received reports about this behaviour (https://github.com/bitwarden/clients/issues/7243) and are looking into it.

I thank you in advance for your understanding.

**Comment by djhau** [comment]
This has sorted this issue out as you described.

**Comment by luckydonald** [comment]
Please note that logging out can lead to data loss, if you didn't fully sync before.
