### ISSUE TITLE
Doesn't minimize to systray on boot

### ISSUE THREAD

**Issue by TheCableGuy99** [bitwarden/clients#7392]
### Steps To Reproduce

1. Go to "File > Settings > App Settings (All Accounts)"
2. Enable "Show Tray Icon, Minimise to tray icon, Close to tray icon, Start to tray icon and Start automatically on login"
3. Reboot PC

### Expected Result

That the app is launched, nothing on the taskbar and minimised to the systray

### Actual Result

It's minimised to the Taskbar, can't be opened clicking on the taskbar icon, nor can it be closed by right clicking on it and selecting close. You have to open it from the systray and close/minimse for it to behave as expected. It's only on the initial boot up.

### Screenshots or Videos

![Screenshot 2023-12-29 070204](https://github.com/bitwarden/clients/assets/39552752/0a1decaa-db6d-4d13-a4c0-dae4800aedb0)
![Screenshot 2023-12-29 070706](https://github.com/bitwarden/clients/assets/39552752/64ea1e1f-d973-4945-8700-067ac003d180)

### Operating System

Windows

### Operating System Version

Brand new install of Windows 11 Pro (all updates installed)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @TheCableGuy99,

Thank you for reporting this. I set up the Bitwarden desktop client, version 2024.1.0 via the .exe file, as shown in your screenshot and when I tested this, the Bitwarden desktop client was present only in the System Tray and no Bitwarden icon was shown on the taskbar; When I pinned that client to the taskbar and rebooted, the icon in the task was present as expected but it did not have a dot underneath it and clicking on it launched the desktop client as expected. I would recommend that you proceed and uninstall the Bitwarden desktop client off your machine, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), install it anew (in my testing, I installed it only that Windows User Account), and give this another try.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by drakebyte** [comment]
same problem on macbook. it always starts as a pop up, and also the menu bar on the top doesn't change context to bitwarden. i have to press cmd+, to open pereferences. this is for a long time, please fix this.
