### ISSUE TITLE
unable to complete WebAuthn login workflow in Fennec

### ISSUE THREAD

**Issue by Be-ing** [bitwarden/clients#7393]
### Steps To Reproduce

1. Install [Fennec](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) from F-Droid on [LineageOS + microG](https://lineage.microg.org/)
2. In Fennec, install Bitwarden browser extension from https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/
3. In Fennec, go to Menu > Add-ons > Bitwarden. Enter username and password.
4. Bitwarden extension says "To start the WebAuthn 2FA verification. Click the button below to open a new tab and follow the instructions provided in the new tab." Tap the "Open new tab" button.
5. Nothing appears to happen. Fennec does not show any UI for exiting the browser extension settings and going back to web pages; the browser extension settings take the whole screen.
6. Press back button until web pages are viewable again.
7. A new tab has indeed opened now with an "Authenticate WebAuthn" button. Click that button and insert Yubikey to authenticate. Web page says authenticating worked.
8. Go back to Menu > Add-ons > Bitwarden. Bitwarden is not logged in because pressing back in step 6 stopped the authentication process of the browser extension.

### Expected Result

Pressing the "Open new tab" button in step 4 switches to the newly opened tab without restarting the browser extension's authentication process.

### Actual Result

There is no way to use the opened web page to log in because viewing the web page requires pressing back in the browser extension settings, which exits the authentication process.

### Operating System

Android

### Web Browser

Firefox

### Build Version

LieageOS 20-20231203-microG-channel

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Be-ing,

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for [desktop environments](https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated [Android client](https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions, such as [passkeys](https://bitwarden.com/help/storing-passkeys/), may not operate as expected in a mobile environment.

Thank you again,

**Comment by Be-ing** [comment]
Is it anticipated that in the future the Android application will be able to use stored passkeys to login to websites in mobile Firefox?

**Comment by Anutrix** [comment]
Facing exact same issue on latest(Fenix iirc) Firefox.
