### ISSUE TITLE
Saving passkeys ignores period in username

### ISSUE THREAD

**Issue by asdflkjasdfasdf** [bitwarden/clients#7401]
### Steps To Reproduce

1. Go to an email provider like Microsoft or Apple where periods matter.
2. Create an email "johnqpublic@outlook.com" and another "john.q.public@outlook.com" as distinct accounts.
3. Save a Bitwarden passkey on one, it works.
4. Now try to save a Bitwarden passkey on the second account, you cannot. It appears BW is assuming they are the same account, as they would be with Gmail, for instance.

### Expected Result

Since they are distinct accounts, you should be able to create a passkey on each one.

### Actual Result

You cannot create a passkey on whichever one you do second.

### Operating System

Windows

### Operating System Version

Win10 22H2, 19045.3803

### Web Browser

Brave

### Browser Version

Brave v.1.61.109; Chromium: 120.0.6099.144

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by asdflkjasdfasdf** [comment]
mistake, it was something else

**Comment by SergeantConfused** [comment]
Hi @asdflkjasdfasdf,

Just to confirm, is it working as expected? Can I proceed and close this report?


Thank you in advance,

**Comment by SergeantConfused** [comment]
Hi @asdflkjasdfasdf,

I will proceed and close this GitHub report at this stage; Please feel free to [get in touch](https://bitwarden.com/help/) with us if you'd like to follow up on this topic.


All the best,
