### ISSUE TITLE
Firefox pin not saved

### ISSUE THREAD

**Issue by mrlinuxfish** [bitwarden/clients#7404]
### Steps To Reproduce

1. Check "use pin to unlock" and set pin
2. Navigate away from settings tab
3. Navigate back to settings tab
4. Pin is no longer set and setting is unchecked

### Expected Result

Setting a pin should be saved until the extension is logged out (as specified by the tooltips in the settings)

### Actual Result

Navigating away from the settings tab unsets the use pin to unlock setting. Pin is not remembered and extension requests the master password

### Screenshots or Videos

[Video](https://github.com/bitwarden/clients/assets/444722/b80085c9-95f0-4e94-bfc1-e496a2031ebf)

### Operating System

Windows

### Operating System Version

11 23h2

### Web Browser

Firefox

### Browser Version

121.0

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @mrlinuxfish,

Thank you for this report. Could you please uninstall the Bitwarden browser extension from Firefox, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), then install it anew and let me know if this behaviour continues?


Thank you in advance,

**Comment by mrlinuxfish** [comment]
I'm reasonably confident I cleared the extension data. You need to have the extension installed to view the UUID, so it's possible I only cleared out data for one instance of it being installed.

Still has the same issue after reinstalling

**Comment by SergeantConfused** [comment]
Hi @mrlinuxfish,

Thank you.
1. Could you please detail how your browser is set up? Screenshots of the Settings menus would be very helpful.
2. What other extensions are installed on Firefox?
3. Do you encounter the same behaviour in a new [Firefox Profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles)?

I'd like to gather more information as I am unable to reproduce this myself; If you would like to share that information directly with us instead of publicly on GitHub, please feel free to create a [support ticket](https://bitwarden.com/help/) and please include a link to this GitHub report in it and we'll proceed.


Thank you in advance,

**Comment by lugoazul** [comment]
Hello. I have the same problem and I had already opened a ticket for your support more than month ago. I tried all the suggested described here, as well as testing with a new profile. Nothing worked.

**Comment by cbrand-ludlums** [comment]
I think I've come across a solution for this.  In Firefox, the Bitwarden browser extension may need the "Read and modify privacy settings".

I had this same issue and I've uninstalled/reinstalled the extension and still had the same issue.  I checked the extension permissions and thought I'd enable the permission for "Read and modify privacy settings"
![image](https://github.com/bitwarden/clients/assets/45399214/4a773657-9be4-43e6-91e4-2b2b9f4b7ced)
After I enabled this permission, the Unlock with Pin setting stayed.
Could also be a coincidence too that it stayed.

**Comment by lugoazul** [comment]
> I think I've come across a solution for this. In Firefox, the Bitwarden browser extension may need the "Read and modify privacy settings".
> 
> I had this same issue and I've uninstalled/reinstalled the extension and still had the same issue. I checked the extension permissions and thought I'd enable the permission for "Read and modify privacy settings" ![image](https://private-user-images.githubusercontent.com/45399214/293736785-4a773657-9be4-43e6-91e4-2b2b9f4b7ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyNDQ0MTEsIm5iZiI6MTcwNDI0NDExMSwicGF0aCI6Ii80NTM5OTIxNC8yOTM3MzY3ODUtNGE3NzM2NTctOWJlNC00M2U2LTkxZTQtMmIyYjlmNGI3Y2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDAxMDgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2M3NzI0NmIzOTRkNmJmOWZkODZkMDE4YjIwNDI2OGM3Zjc1YmQ2MzQ5YjNjYzU3MjI4OTFjODE0NGNiMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSjhO9eala5XthZEyIiwp3NoT8k2Qnx6UhVTkoxL6HQ) After I enabled this permission, the Unlock with Pin setting stayed. Could also be a coincidence too that it stayed.

Well, thank you! That worked for me as well. I just hope it holds until this issue is fixed as I am really tired of entering the password.

**Comment by mrlinuxfish** [comment]
I tried the settings change and a new profile, but it's still not saving.

**Comment by lugoazul** [comment]
> I tried the settings change and a new profile, but it's still not saving.

Well, that was short. Neither for me... One day after and it no longer works....

**Comment by gfairchild** [comment]
I'm experiencing this same issue. FF 121.0, BW extension 2023.12.1.

**Comment by Brefar** [comment]
I tried to set the pin from sidebar and it retained it. None of the other methods worked for me. So give that a try. I couldn't figure out how to open the sidebar for it again, but when I disabled and re-enabled it, the sidebar opened and I added the pin there. Good luck!

**Comment by gfairchild** [comment]
> I tried to set the pin from sidebar and it retained it. None of the other methods worked for me. So give that a try. I couldn't figure out how to open the sidebar for it again, but when I disabled and re-enabled it, the sidebar opened and I added the pin there. Good luck!

I just tried this, and it unfortunately didn't work for me.

**Comment by gfairchild** [comment]
I just got it to work. I first checked the "Unlock with PIN" box and set the PIN. Then, I hit "Lock Now", which is just below the "Unlock with PIN" checkbox. This immediately showed me the PIN unlock prompt, and it seems to be working now. I suspect that the setting isn't being properly saved automatically, but forcing BW to lock does properly save the setting.

**Comment by Yoldark34** [comment]
Hello,
I failed too many times the pin code, i got log out, i used the master password and the 2FA to log in, i tried re enabling the pin code without success.
I can only enable the pin code if i uncheck "Lock with the master password after browser restart" (from the pin code popup).

I tried the solutions from the thread without success, i tried removing and installing back the extension and i tried rebooting FF 121.0.

Thanks :P

**Comment by mrlinuxfish** [comment]
Update, I found I can set the pin if I uncheck "Lock with master password on browser reset".

I won't use it this way as it seems to be less secure though

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you for your patience and input. I am now able to reproduce this behaviour with Bitwarden 2023.12.1 on Firefox 121.0, and I've routed this internally.

Reproduction steps:
1. Open the Bitwarden browser extension in Firefox, and navigate to the (Settings) menu and click on (Unlock with PIN).
2. Enter a 4 digit PIN code and keep the (Lock with master password on browser restart) option activated and click on (Ok).
3. Navigate to the (Generator) menu and then navigate back to the (Settings) menu.
At this point you will see that the (Unlock with PIN) function is deactivated.

Notes:
1. @gfairchild's workaround [here](https://github.com/bitwarden/clients/issues/7404#issuecomment-1879463546) works. Thank you for sharing that.
2. The (Unlock with PIN) function also works as expected if you deactivate the (Lock with master password on browser restart) option when setting the PIN, as @mrlinuxfish mentioned.

If anyone wishes to add further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you all again,

**Comment by sleepyh34d** [comment]
Running Windows 11 23H2, Firefox 121.0.1, and Bitwarden 2023.12.1. @gfairchild's workaround solved the issue for me. 

After applying the workaround, I noticed that when disabling 'Unlock with PIN', navigating away from Bitwarden, then going back and re-enabling it, the setting worked as expected. However, if I disabled 'Unlock with PIN' and selected 'Lock Now', then unlocked it and attempted to re-enable 'Unlock with PIN', the setting wouldn't save until applying the workaround once again. Hope this helps!

**Comment by mrlinuxfish** [comment]
This issue appears to be fixed on 2024.1.0

**Comment by mrlinuxfish** [comment]
This issue appears to be fixed on 2024.1.0

**Comment by lugoazul** [comment]
Indeed it seems, although there's no mention about it in release notes.

**Comment by alkaris2** [comment]
This is still an issue, forced logged out when Pin + Biometrics enabled. This issue has been marked as Solved/Completed, but clearly not, because the issue is still there.
