### ISSUE TITLE
Upgrade sometimes fails

### ISSUE THREAD

**Issue by Freddan-67** [bitwarden/clients#7407]
### Steps To Reproduce

Windows 11 client
Upgrade from old version to 2023.10.1 or 2023.11.1
On one machine the upgrade worked as expected, on the other machine it was just an eternal hour glass in the application.
The old version was more than 6 month old.
Work around: Uninstall the client, then reinstall

### Expected Result

Upgrade from old version works

### Actual Result

Upgrade from old version don't work

### Screenshots or Videos

![bitwarden_do_not_start](https://github.com/bitwarden/clients/assets/7888909/1f3283a9-275b-4ee5-9764-2d75e7cb6d3f)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Freddan-67,

Thank you for your report. 

It's unclear what might have caused this issue, and as Bitwarden does not back-port changes to older versions, there is no current action for this specific issue to be taken by engineering other than trying to avoid it in the future.

I'm closing this now.

Kind regards,
Daniel
