### ISSUE TITLE
Web vault reports - False negatives

### ISSUE THREAD

**Issue by Voyage7082** [bitwarden/clients#7444]
### Steps To Reproduce

1. From the reports page of the web vault (https://vault.bitwarden.com/#/reports) in the user's browser, right click on any report and open that report in a new tab.
2. The user will likely be prompted to re-login with their username and master password.
3. Upon re-logging in (as required), the report will appear to run and report back that no issues have been found (e.g. "GOOD NEWS: No items in your vault have passwords that have been exposed in known data breaches.")

### Expected Result

When running a report from the Reports page of the Bitwarden web vault, the relevant report will run and provide results.

### Actual Result

Possible false negative in certain scenarios.

When running a report from the Reports page of the Bitwarden web vault and the user opens the report in a new tab/window of their browser, the report will provide "Good News" and that there are no adverse findings of the report in all cases.

When opening the same report in the same tab/window from the Reports page, the report will run properly.

### Screenshots or Videos

![252568209-ffe31e8e-e69a-4b5b-b638-cfc377fe3edd](https://github.com/bitwarden/clients/assets/139205775/e79cad00-456c-4bd5-bb58-faff124eaa70)
![252568221-d06e271b-2843-48d1-b835-de7843d82292](https://github.com/bitwarden/clients/assets/139205775/a721b713-c899-4fb5-9021-ff1fdd6e9c52)
![Screenshot 2024-01-04 123313](https://github.com/bitwarden/clients/assets/139205775/5fc4dbe9-52da-4968-a60d-54e6880083e1)

### Additional Context

**Likely Scenario**
A user wants to run multiple reports and does so by opening each in a new tab from the Reports page of the web vault. The user may then be provided with false negative reports.

**Issue History**
First tested/reported in July 2023 in #5782 but my account was flagged at the time of posting so the Issue was not visible publicly.
The issue persists as at 4 January 2024 in web-vault version 2023.12.0. 

### Operating System

Windows, macOS

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Voyage7082** [comment]
Issue is fixed at (or before) Browser version 2024.12.0
