### ISSUE TITLE
PC Client will not open: stays on progress spinner

### ISSUE THREAD

**Issue by batmite-ab** [bitwarden/clients#7458]
### Steps To Reproduce

1. Go to Bitwarden icon in Windows 11
2. Click on Bitwarden icon
![image](https://github.com/bitwarden/clients/assets/155743836/d7978377-2a5d-4fd9-801d-66e76ee107a4)

### Expected Result

Vault should open up

### Actual Result

Vault never appears, it stays stuck on the progress spinner and never presents the vault.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/155743836/5b7046f1-d9ac-4505-b4fd-0193ce9c1e1e)

### Additional Context

I can't remember how I installed the Windows app, but I think it was directly from Bitwarden.

### Operating System

Windows

### Operating System Version

Windows 11 Home 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by McNutnut** [comment]
> Note my browser plugin on this machine works, but it doesn't appear be syncing regularly. When I try to force synch, I get a, "Synching failed," error message.

See https://github.com/bitwarden/clients/issues/7243 for the Browser Extension error

**Comment by Adedamola-Aina** [comment]
hello @McNutnut 

Thank you for checking up on this. Could you please log out (File/Settings > Log Out) and log back in to refresh your session and let me know if that helps? We've received reports about this behavior (https://github.com/bitwarden/clients/issues/7243) and are looking into it.

I thank you in advance for your understanding.
