### ISSUE TITLE
Login issue on Desktop application

### ISSUE THREAD

**Issue by MiroslavTonev** [bitwarden/clients#7468]
### Steps To Reproduce

The app stuck in a logging screen even after reinstall. Only the rolling icon is seen.

### Expected Result

to successfully login in the application

### Actual Result

The application keeps trying to loging without success.

### Operating System

Linux

### Installation method

Other

### Build Version

Version 2023.12.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MiroslavTonev** [comment]
the OS details:
System:
  Kernel: 5.15.0-91-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4
    tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

**Comment by daniellbw** [comment]
Hi There,

Thank you for your report!
Please could you add more information such as screenshots.
Please note that this is a 'duplicate' of the below bugs (for macOS and Windows) on Linux:

https://github.com/bitwarden/clients/issues/6691
https://github.com/bitwarden/clients/issues/6878

As such the same workaround should also apply:

close Bitwarden
delete the contents of local storage (https://bitwarden.com/help/data-storage/)
re-launch Bitwarden
I can confirm that the team is still looking into this, despite the existence of the workaround.

Thanks once again!
