### ISSUE TITLE
New AutoFill Function: Icon Background Not Transparent in Dark Mode

### ISSUE THREAD

**Issue by SchneiderSam** [bitwarden/clients#7502]
### Steps To Reproduce

1. Enable dark mode in your browser or on a website (e.g., GitHub).
2. Visit a login page where the Bitwarden icon for autofill appears.
3. Notice that the icon has a white background, which is incongruent with the dark mode.

### Expected Result

I would expect the icon to have a transparent background to seamlessly blend into the dark mode design. This would make the overall appearance more harmonious and professional.

### Actual Result

The Bitwarden icon used for autofilling login information has a white background. This clashes with the dark mode design of many websites, resulting in an inconsistent and visually disruptive appearance.

### Screenshots or Videos

<img width="386" alt="image" src="https://github.com/bitwarden/clients/assets/9355398/9a4f7d44-c567-47d4-95bc-a7ef6f1b132e">

### Operating System

Windows

### Web Browser

Chrome

### Build Version

Version 120.0.6099.200 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @SchneiderSam, 

Thank you for your report. 

This was implemented with https://github.com/bitwarden/clients/pull/7415 and will be included in future release.

Closing this now.
