### ISSUE TITLE
Autofill Still not working in 2024.01.0

### ISSUE THREAD

**Issue by chungr** [bitwarden/clients#7513]
### Steps To Reproduce

1. Go to 'https://disneyworld.disney.go.com/login/?returnUrl=/plan/'
2. Type in a valid email address
3. Click Continue
4. Autofill of password will not work, clicking on the login in the extension, right clicking and using context to autofill - nothing works.

### Expected Result

Autofill of password should work and used to work in 2023.9.2.

### Actual Result

Since 2023.10.1, Autofill of password does not work, Copy/Paste of Password is the workaround but is much less convenient.

### Screenshots or Videos

I took a video that was too large to attach to this ticket of the problem.

In this video using Bitwarden 2024.1.0, Autofill does not work: https://youtu.be/GP9vbAyOW_Y

Here is the same website, same Bitwarden login (a test account that I created), same configuration but with Bitwarden 2023.9.2 showing that this used to work: https://youtu.be/jy5lh7_p-P4

### Additional Context

Autofill of passwords on this website WAS working in 2023.9.2 and still works if you downgrade to the older version.  But every version since then, it does not work including 2024.1.0.

This is not simply an issue where autofill isn't working correclty with a website, this is something that used to work and now has stopped working in all recent versions of Bitwarden including the latest version 2024.1.0

Note: The videos were recorded using Microsoft Edge but the problem happens with Google Chrome (latest version) as well.

### Operating System

macOS

### Operating System Version

13.6.3

### Web Browser

Chrome, Microsoft Edge

### Browser Version

120.0.2210.121

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chungr** [comment]
Upon Autofill in the JavaScript Console, the following errors are also reported each time an autofill is attempted:

`
(anonymous) @ bootstrap-autofill-overlay.js:5017
InsertAutofillContentService.runFillScriptAction @ bootstrap-autofill-overlay.js:5017
(anonymous) @ bootstrap-autofill-overlay.js:5041
(anonymous) @ bootstrap-autofill-overlay.js:4987
insert_autofill_content_service_awaiter @ bootstrap-autofill-overlay.js:4983
fillForm @ bootstrap-autofill-overlay.js:5034
(anonymous) @ bootstrap-autofill-overlay.js:5395
(anonymous) @ bootstrap-autofill-overlay.js:5298
autofill_init_awaiter @ bootstrap-autofill-overlay.js:5294
fillForm @ bootstrap-autofill-overlay.js:5390
fillForm @ bootstrap-autofill-overlay.js:5315
AutofillInit.handleExtensionMessage @ bootstrap-autofill-overlay.js:5338
`

**Comment by cagonzalezcs** [comment]
@chungr Thank you for this bug report.

I've identified the reason why autofill isn't working on this website, and have implemented a fix for the issue which is currently in review. 

https://github.com/bitwarden/clients/pull/7518

One thing to note here, the newly created inline auto-fill menu feature still won't work on this website. The website is enacting some form of programmatic focus routing that disallows click or keyboard events outside of specific DOM elements. 

We have a ticket to resolve an issue with iframes that might also resolve the problems that this website is showing for the inline menu, but for now just wanted to inform you about this known bug. 

Closing this issue for now, but please feel free to comment if anything seems to be missing in the implemented fix.

**Comment by cagonzalezcs** [comment]
@chungr 

The fix will be present in v2024.2.0, the version release yesterday was a hotfix to remove some console logging that was used to debug an issue.
