### ISSUE TITLE
Major performance issues with new Bitwarden autofill when simply using web apps with complex DOMs

### ISSUE THREAD

**Issue by timabbott** [bitwarden/clients#7522]
### Steps To Reproduce

I've been a long time user of the Bitwarden project and the lead developer of [Zulip](https://github.com/zulip/zulip). I've noticed that using Zulip in Chrome got very slow for me sometimes in the last few weeks -- navigating to the next conversation has a visible lag. Profiling why, I've carefully isolated that Bitwarden is responsible.

1. Go to https://chat.zulip.org in Chrome with the Bitwarden Chrome extension enabled. I expect you can just use the logged-out mode to reproduce Bitwarden consuming a lot of resources, but have only tested logged-in. There will be more data in the DOM if you create an account, though, so I suspect the effect will be amplified if you log in, visit all the settings panels, etc., and thus potentially have more stuff in the DOM.
2. Start the Chrome profiler in the Performance tab.
3. Click on different streams/conversations in the left sidebar.
4. Stop the profiler and look at how much of the time was consumed by the Bitwarden extension.
5. Repeat with Bitwarden disabled and observe that Bitwarden was responsible for a >2x slowdown in the time required (I observed 2-5x in my different tests).

I expect the issue affects all other browsers that you have the extension for as well.

### Expected Result

A password manager being enabled should have no performance impact on web applications.

### Actual Result

Having Bitwarden enabled on the Zulip site makes it painfully slow to use our product. I imagine this likely affects lots of other software with large DOMs containing forms as well.

I have reproduced using the Chrome browser developer tools "Performance" tab and by toggling Bitwarden on/off in my browser that Bitwarden is responsible for a multiplicative increase in the time required for the browser to navigate between different conversations in Zulip with a large organization like chat.zulip.org.

### Screenshots or Videos

Here's a screenshot showing Bitwarden slowing an important interactive operation in Zulip by at least 1.5s on a 12-core laptop with 64GB of RAM:

![image](https://github.com/bitwarden/clients/assets/2746074/e0b5c6e1-3c35-4a6f-8ccb-b707990ee2d9)

I'm not sure if the "Microtasks" at that lasts even longer is also the extension's code.

### Additional Context

It's fairly visible in the profile screenshot, but I think the core problem is that Bitwarden's autofill logic inefficiently walks the entire DOM tree whenever we update the DOM (possibly including the URL fragment/hash?), and this is very expensive because Zulip in a large organization has a TON of stuff in the DOM. 

There are no visible forms presented to the user at the time that this occurs. So one thing that Bitwarden could look at doing is limiting this behavior. But I think even if that was done, it would be awful for Bitwarden to eat 1.5s of CPU on a fast computer whenever we show a form in the Zulip web app, either.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### Web Browser

Chrome

### Browser Version

120.0.6099.109

### Build Version

Extension version 2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@timabbott 

Thank you for putting in the time and effort into this bug report. 

So we're aware that something like this is happening, and your web application gives us some extra context for our investigation. 

The issue we're seeing on our side has to do with an implementation we put forth for allowing autofill of ShadowDOM elements. We're using the PageWalkerAPI to facilitate querying elements and piercing through closed ShadowDOM roots using extension-specific APIs. 

For most websites, this doesn't seem to cause any major performance hiccups, but as you've mentioned on applications with complex DOM interactions issues present themselves.

I'll be digging into this using https://chat.zulip.org/ to identify a path forward for a resolution. Will update on this ticket when I've got some more concrete details on how we are going to resolve the issue.

**Comment by timabbott** [comment]
Awesome! Feel free to DM me on chat.zulip.org if I can help out interactively with debugging this.

**Comment by timabbott** [comment]
Hmm, did you creating an account, visiting all the settings panels in the gear menu (they get saved in the DOM rather than removed when exiting). That should result in more DOM elements than the logged-out view. I observed about 4x longer times in my first profile vs. after a fresh reload.

There must be some other variable about my system here that is increasing the cost of these operations. The Chrome "task managers" shows a significant amount of persistent load in the main "Browser" process (no specific tab) and the "GPU worker" -- I'm not sure what is causing that and have ~70 Chrome tabs open, mostly GitHub windows but I guess Pandora is playing music. I don't see how those could explain a 10x+ difference here.

**Comment by cagonzalezcs** [comment]
Firefox on MacOS presents a larger impact, about 10x what is experienced in the Chrome example above. Still not the massive 1.4s spike shown within Ubuntu, but yeah the process each time takes about ~280ms. 

https://github.com/bitwarden/clients/assets/16629865/935b41ad-59ee-4b1d-8253-8c4e2d4cf353

I'll create an account and re-review with both of these browsers before checking out Chrome on Linux. As for system specific issues... yeah, I'm not sure. I'm willing to bet that it's a minimal reason for why the problem might exist on your side, and rather than the number of nodes that the PageWalkerAPI has to traverse. We saw this before with a community PR that replaced all document.querySelctor calls with the PageWalkerAPI... There may be further bottlenecks that we need to consider in the implementation.

**Comment by cagonzalezcs** [comment]
One of our developers created an arbitrary reproducible example which has given some insight into the problem. The example is a simple html page with ~65,000 HTML tags.

In tracing the problem down, it seems that the TreeWalkerAPI can handle a large set of DOM nodes fairly efficiently. What's creating our bottle neck is the `chrome.dom.openOrClosedShadowRoot` method call.

We depend on that API to ensure we can fill closed shadow DOM elements... but removing it does have an incredibly significant impact. Parsing the ~65,000 DOM nodes takes roughly 35 seconds with the call in place, and without it that drops down to about 150ms...

Continuing to dig into how to resolve this....

**Comment by cagonzalezcs** [comment]
Figured out a resolution, was surprisingly simple and obvious. 

The issue we're seeing is that passing a node with a large number of nested children to  `chrome.dom.openOrClosedShadowRoot` is creating a bottleneck. I'm not sure on the underlying reason why, but I imagine that this method call is recursively attempting to identify if any of the elements within a passed Node contain a ShadowRoot.

Any Node element that has a ShadowRoot should contain no children. When accessing `Node.childNodes` for an element with a ShadowRoot, an empty NodeList is returned. Modifying the call to retrieve the ShadowRoot for an element such that we only do the retrieval on Nodes with no children fixes the issue.

Working on a PR for this now.

**Comment by cagonzalezcs** [comment]
A PR for this issue is now in code review. 

https://github.com/bitwarden/clients/pull/7542

I'm seeing performance improvements overall within the execution of our `collectPageDetails` method on your website, especially on Firefox. We went from having each call to collect page details take around  ~250ms to having them take ~85ms each time it's called through the mutation observer. 

You should be expect to see this within the `v2024.2.0` version of the extension. Please feel free to comment further, but I'll be closing this ticket for now.

**Comment by timabbott** [comment]
Wow that was fast! I'll try reproducing again when I've got a chance and let you know if I still see anything of note.
