### ISSUE TITLE
[OSX Desktop] Latest Version 2024.1.0 (18112) forces fingerprint unlock even when Cancel is clicked

### ISSUE THREAD

**Issue by philippeboyd** [bitwarden/clients#7541]
### Steps To Reproduce

1. Open Bitwarden
2. Fingerprint popup to unlock your Vault should open
3. Press cancel
4. Fingerprint popup to unlock your Vault reopens (app seems to reload)

### Expected Result

When pressing Cancel, App should not reload and re-ask to unlock your Vault

### Actual Result

Fingerprint popup keeps reappearing after Cancel is clicked

### Screenshots or Videos

<img width="485" alt="image" src="https://github.com/bitwarden/clients/assets/3239656/fa7d72d2-5b48-4219-9755-b176b22854f1">

### Operating System

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0 (18112)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Thank you @philippeboyd for your report. This should be solved once https://github.com/bitwarden/clients/pull/7350 gets deployed.
