### ISSUE TITLE
macOS Desktop App wants to connect to chrome.cloudflare-dns.com

### ISSUE THREAD

**Issue by vordenken** [bitwarden/clients#7552]
### Steps To Reproduce

1. I just opened the bitwarden desktop app and got informed about the connection by my macOS software firewall LittleSnitch

You need to have litteSnitch to see this of course...

### Expected Result

The app should use (and only use) the DNS server I set system/networkwide.

### Actual Result

Bitwarden wants to use an alternative (encrypted) dns server.

### Screenshots or Videos

<img width="515" alt="Bildschirmfoto 2024-01-15 um 11 09 01" src="https://github.com/bitwarden/clients/assets/62395860/3c2463a9-34b7-4cd7-835e-221de2fa7df7">

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.2.1

### Installation method

Mac App Store

### Build Version

Version 2023.12.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Cloudflare is part of our SaaS product infrastructure. In part, this is to prevent DNS-based attacks, by enforcing DNSSEC. Bitwarden also connects to Cloudflare's content delivery network (CDN) to speed up downloads of [website icons](https://bitwarden.com/help/website-icons/#about-the-icon-server). 

I hope this information was helpful.
