### ISSUE TITLE
bootstrap-content-message-handler.js prints to browser console on every window message, even those made by other extensions

### ISSUE THREAD

**Issue by OneNot** [bitwarden/clients#7575]
### Steps To Reproduce

Example of when the issue would happen:
Using both [this addon](https://addons.mozilla.org/en-GB/firefox/addon/webnowplaying/) and Bitwarden's Firefox addon and navigating to youtube.com, the browser console gets flooded with constant debug messages.

### Expected Result

bootstrap-content-message-handler.js should probably only log messages that originate from Bitwarden's own scripts.

### Actual Result

bootstrap-content-message-handler.js floods the console with debug messages for every window message made by any addon.

### Additional Context

Anything that uses window messages is caught by Bitwarden's bootstrap-content-message-handler.js.
As an example navigating to youtube.com with [this addon](https://addons.mozilla.org/en-GB/firefox/addon/webnowplaying/) and Bitwarden's addon enabled, the console gets constantly spammed with these two debug messages:
```
Handling window message [bootstrap-content-message-handler.js:167:21](moz-extension://ab53cc0e-d7fc-4dfe-8d84-71c9e7ffc4e0/content/bootstrap-content-message-handler.js)
Bad source or badly formatted message, skipping. [bootstrap-content-message-handler.js:171:25](moz-extension://ab53cc0e-d7fc-4dfe-8d84-71c9e7ffc4e0/content/bootstrap-content-message-handler.js)
```
by Bitwarden's bootstrap-content-message-handler.js

I only marked Windows 11 and Firefox in the issue template as that was where I saw the issue, but I assume the issue isn't exclusive to either.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

121.0.1

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by freelock** [comment]
Same issue in Firefox Linux -- and others are saying it also affects Chrome, Mac, everywhere - https://community.bitwarden.com/t/looping-infinitely-bootstrap-content-message-handler-js-is-looping-infinitely-on-almost-every-website/62270

**Comment by Neonwarden** [comment]
Hi there,

Thank you for your report! 

I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by hkbertoson** [comment]
I turned off every other extension that I have and only had Bitwarden running. Not even logged in and it seems like anything I do triggers this error message. 


https://github.com/bitwarden/clients/assets/44106297/18f01e30-c640-4ea1-b0f0-09d9f0d6b701

**Comment by grafficmedia** [comment]
As a web dev, this is an extremely annoying bug, as it clogs up my console which I need in order to do my job. I will most likely have to uninstall the extension if this is not resolved promptly.

**Comment by oliver139** [comment]
This is super URGENT to be fixed. As said on above, it is highly affecting web dev to do their job.

https://github.com/bitwarden/clients/assets/45283723/b3b9f8ce-e695-4ddf-98b3-c2f060535f8e

**Comment by oliver139** [comment]
For those who are not working on React project, please consider to disable the React Dev Tools. It stops looping the message on my machine.

**Comment by DJDavid98** [comment]
I happen to be working on a React app and use Debug logs specifically because the other types tend to be clogged up, this is an extremely disrupting issue.

**Comment by pensono** [comment]
This issue isn't related to react, I've found the same thing in a Svelte project.

As a workaround, enter the following string into the filter box of your console to filter out the messages:
`-/Bad source or badly formatted message, skipping|Handling window message/`

![image](https://github.com/bitwarden/clients/assets/9586990/aab16def-96a6-4a17-bfc7-0b7190c5befb)

**Comment by tfilo** [comment]
I have this issue as well with Firefox plugin. Console full of this messages, it really make development of web apps really hard. Hope it will be fixed soon. For now I am disabling this plugin.

![image](https://github.com/bitwarden/clients/assets/16336763/7234cb3d-a98f-40dc-b995-fc107a221718)

**Comment by mean-cj** [comment]
Google Chrome Windows 10 / Version 120.0.6099.217 (Official Build) (64-bit)

Same Issue
![image](https://github.com/bitwarden/clients/assets/1191385/647da1ba-32e7-43ba-9237-3e9f48093fc4)

**Comment by alike03** [comment]
For people who need the console, a temporary solution is to disable debug logging on Firefox.
You will still get errors, warnings, logs and info.

![image](https://github.com/bitwarden/clients/assets/8145921/2b554b01-4982-44af-b617-8eeba59b8f5d)

**Comment by jan-paulus** [comment]
I'm having the same issue in Brave Version 1.61.116 Chromium: 120.0.6099.217 (Official Build) (arm64)

**Comment by reduckted** [comment]
If you follow the link in the browser console that takes you to the source of the console statement, it shows the source as:

```js
    init() {
        // eslint-disable-next-line no-console -- In content script
        console.debug("Attaching message event listener.");
        window.addEventListener("message", this.handleWindowMessage, false);
        chrome.runtime.onMessage.addListener(this.handleExtensionMessage);
    }
```

That doesn't match what was committed to this repository:
https://github.com/bitwarden/clients/blob/5906a3633554206e6e17e5b93beb9c7585605384/apps/browser/src/autofill/content/content-message-handler.ts#L16-L19

Is the extension not being built from the committed code? That seems less than ideal.

**Comment by rcursaru** [comment]
same behaviour on Fedora 39/Firefox 121.0.1

**Comment by Devconte** [comment]
Same behaviour on Firefox 121.0.1 (64 bits), as suggested in [this topic ](https://community.bitwarden.com/t/looping-infinitely-bootstrap-content-message-handler-js-is-looping-infinitely-on-almost-every-website/62270/9)on bitwarden forum, i disabled React Dev Tools and no more spam error in console.

**Comment by schulzjona** [comment]
https://github.com/bitwarden/clients/commit/e8a54a70a5d136d4e0d7ccdb15d5056d681c3f47

Seems to be related to this commit

**Comment by justindbaur** [comment]
Hey folks! We apologize for the flood of logging. That logging was added to our release candidate code to help pin down an issue that was very intermittent. The logging is not in `main` and therefor will not be included in the next release which is slated to start February 7th. The logs are in the debug channel so if able, you can disable the `Debug`/`Verbose` channel, which is off by default in chrome. If you still need debug logs here are a few suggestions:

The filter provided by @pensono is a good one. `-/Bad source or badly formatted message, skipping|Handling window message/`. 

My personal recommendation is to use a different browser/profile to develop in separate from your personal extensions/data. This allows me access to newer chrome API's since I use Chrome Canary to develop vs Firefox personally. It also means I can enable all the other developer goodies in `chrome://flags` that I wouldn't want on normally. It also means I can close and reopen chrome with different command line arguments like my personal fave `--auto-open-devtools-for-tabs`. 

If the logs you care about come from an iframe by chance you can change your devtools to only show messages from that context. In firefox that is done by clicking `Top` at the far right of the console input line and switching contexts.
![Screenshot 2024-01-17 at 8 11 07 AM](https://github.com/bitwarden/clients/assets/19896123/b2f3eaab-6b9b-4053-b70a-769ecbceeac4)

Or in chrome that same button in at the top of the console tab. 
![Screenshot 2024-01-17 at 8 15 13 AM](https://github.com/bitwarden/clients/assets/19896123/814e2c94-292a-4fb4-95e5-5075576efc26)

**Comment by Xanax-C-137** [comment]
Everyone using Chromium-based browsers should be able to right-click and select "Hide messages from bootstrap-content-message-handler.js" for now.
![Screenshot](https://github.com/bitwarden/clients/assets/20140992/4fec6f69-f8d8-4ef1-bca5-78efadf076de)

**Comment by VAggrippino** [comment]
> Hey folks! We apologize for the flood of logging. That logging was added to our release candidate code to help pin down an issue that was very intermittent. The logging is not in `main` and therefore will not be included in the next release which is slated to start February 7th.

I just want to make sure I understand...
1. Was this issue from a release candidate that was pushed to the official extensions sites for both Chrome and Firefox?
2. This won't be corrected until the next full release on February 7th?

I have no problem with either of these details. Like I said, I'm just tryin' to make sure I understand.

**Comment by nook24** [comment]
Same for me on Firefox on Windows. I had to remove Bitwarden from Firefox so I can work again

**Comment by DJDavid98** [comment]
With all due respect, fixing this shouldn't take ~3 weeks, and a change like this should really be behind some kind of feature flag that the person testing the extension can enable for themselves, not on by default.

If this is the current situation and it's expected to be handled as described, please use this as a learning opportunity how not to do this in the future.

**Comment by robbyphillips** [comment]
> Hey folks! We apologize for the flood of logging. That logging was added to our release candidate code to help pin down an issue that was very intermittent.

Sorry, but how does filling my console help you debug this issue?

Why was this version pushed out to everyone if it's only a release candidate, not a mainline release?

**Comment by daveidivide** [comment]
Another react dev here with the issue on Firefox.

I can't find how to permanently hide these messages on Firefox so I've found that filtering by `-hand` hides them for me.

**Comment by szamanr** [comment]
you can install an older version of the extension. 

1. find one here: https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org
2. download the file
3. run it, which will install and overwrite the current version

**Comment by vad99lord** [comment]
Possible to introduce a flag in the options section of the extension? Something like enable logs. So we can easily turn it off, and debugging still will be available? really annoying thing, since I'm using filtering of logs for personal purposes

**Comment by ragnese** [comment]
> With all due respect, fixing this shouldn't take ~3 weeks, and a change like this should really be behind some kind of feature flag that the person testing the extension can enable for themselves, not on by default.
> 
> If this is the current situation and it's expected to be handled as described, please use this as a learning opportunity how not to do this in the future.

@justindbaur, I agree with @DJDavid98 that this isn't the kind of thing that should wait until the next normal release. This is a bug that is quite frustrating for the users who notice it and as such should warrant a bugfix release ASAP. 

I know you're being flooded right now because of this issue (which is also a hint that it needs to be fixed ASAP), but I do want to say that I'm a huge fan of Bitwarden and appreciate your hard work.

**Comment by justindbaur** [comment]
Hi All, I am not the one that makes the go/no-go call on a release but I can assure you the people who do are aware of this issue and the comments you are making. It's not off the table but as of now we aren't planning on another release for this. 

As far as a feature flag for this, we do use feature flags for various things but it would not have been the place for this particular issue. We were dealing with a race condition of a message being sent before the listener was ready for it. Anything that tampered with those timings would have made the logging moot.

This will not be a regular thing for us, we pretty sparingly use logging and especially don't generally use it in any content scripts but the specifics around this issue called for it. There are extra headaches around packaging and deploying a safari browser extension that I made the call that I needed logs in the hands of our QA people to help me figure out an issue. We try to very minimally change our release candidate code between the time it's cut and our release and we extra don't want to change it between the time QA has finished testing and release. That is why the logging didn't get reverted.

**Comment by robbyphillips** [comment]
> We try to very minimally change our release candidate code between the time it's cut and our release

What is the difference between a release candidate and the mainline release if they are both distributed by the main channel?

**Comment by grafficmedia** [comment]
Something really isn't adding up here. If this change isn't in your main branch, how did it get pushed out to the extension store and into all of our hands? Agree with @robbyphillips, have run a few release processes myself and this one really has me scratching my head. 

Clarity on this issue is going to be necessary to quell my nerves about using this product, to be honest. If y'all are just releasing code into the wild that shouldn't be, that seems like a pretty major security risk.

**Comment by nook24** [comment]
> Hey folks! We apologize for the flood of logging. That logging was added to our release candidate code to help pin down an issue that was very intermittent. The logging is not in `main` and therefore will not be included in the next release which is slated to start February 7th. The logs are in the debug channel so if able, you can disable the `Debug`/`Verbose` channel, which is off by default in chrome.

I use Bitwarden with Firefox on Windows. I never switched to a beta channel or anything like that. Honestly I don't even find a switch in the settings of the extension to do so.
The issue is within the current version you get, if you install the Bitwarden extension from the Mozilla Addons page. (Version 2024.1.0)

Hope this helps

**Comment by hugoattal** [comment]
@robbyphillips @grafficmedia @nook24 Here's the timing of the events to my understanding
- Logs are introduced to debug some race conditions
- The `release candidate` of 2024.1 is fixed and QA start testing it
- The logs get removed in the `dev` version, but they don't want to push it on the `release candidate` as testing has already started
- They shipped this current version (2024.1) with the logs as main
- The dev version with log removal gets moved to `release candidate`
- They will ship the next `release candidate` as 2024.2

(Good luck with everything to the BitWarden Team)

**Comment by daveidivide** [comment]
Thanks for the explanation @justindbaur.

I'm sure 99% of users have no idea about this. Obviously it's all devs here that work in the console regularly. (Why else would other users be on GitHub anyway).

But yeah, turns out we get pretty irate when you mess with our console logs 🤣

**Comment by grafficmedia** [comment]
Thank you for explaining how this issue ended up in production. Confidence restored.

**Comment by juanozorio** [comment]
I have the "React Dev Tools" extension, I disabled it and reloaded the page, and it stopped having the "console.log" flood.

Thanks, @oliver139

**Comment by htr3n** [comment]
+1 with this issue on Firefox and Chrome. Disabling React Developer Tools stops the messages.

**Comment by jfvillablanca** [comment]
+1 on Firefox Developer Edition. Thanks for the explanation

**Comment by noc2spam** [comment]
Daaaang... I totally thought my code was doing it, at first. LOL. Please remove trhe message as soon as you can guys. Its pretty annoying. :(

**Comment by leonardoboch** [comment]
It also happens with Vue Dev Tools.

**Comment by hichxm** [comment]
Same here with Laravel project (Jetstream stack)

![image](https://github.com/bitwarden/clients/assets/12587585/8388eaa8-d5ab-4236-8130-d28182d0a7be)

**Comment by sneakers-the-rat** [comment]
I'm still trying to understand this:

> I spent hours trying to recreate the issue but was unable to. In a desperation attempt I requested, internally (to my manager, our QA team, and our devops team), approval to cherry pick a commit adding only logging to rc. That commit can be found [here](https://github.com/bitwarden/clients/commit/e8a54a70a5d136d4e0d7ccdb15d5056d681c3f47). It was decided to do it there because we didn't want it in main and to become a regular part of our code.

so because a bug couldn't be recreated in the dev environment, the goal was to deploy something with the logging so that when the bug appeared in the wild you could collect the logs? am I reading that right? and adding that resolved the release-blocking bug? I am just not sure I understand the reasoning there.

I also get that QA is a thing, but don't understand why it's impossible to push an update that just removes those debug log calls until the next release. 

Ordinarily I wouldn't care but since this is a password manager, sloppy dev practices (not blaming you, i get you're just trying to make something work and don't run the whole show) make me nervous, and i'm trying to understand what exactly broke down here and why a fix isn't forthcoming.

**Comment by saevarb** [comment]
@justindbaur 

It's great that you have your own preferred way of developing with a separate profile and whatnot, but that seems like a rather poor argument to justify flooding the logs with messages because it works for you.

I experienced some pretty serious performance degradation due to these logs and had to restart the browser (this was before I knew which extension was the culprit). I also happen to use debug logs and rather frequently use the filter functionality of the console, the react dev tools *and* my password manager, to, you know, log in to stuff. 

What is the best way to install a version of the extension that doesn't suffer from this issue? Providing a way to actually fix this issue -- not just get around it using your own preferred methods of doing whatever -- seems like the least thing you folks could do here.

**Comment by ashooner** [comment]
So this was intentional?

**Comment by ronyclau** [comment]
Not sure about other browsers. If you are using Firefox, you can installed a previous version here:
https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/

You may need to downgrade again when auto-update kicks in, or disable auto-update (NOT RECOMMENDED) for the time being.

**Comment by lil5** [comment]
@justindbaur Next time you try this, make it check if you have debug flag enabled for bitwarden on a localstorage kv. The argument that it needed to be in RC thus it was in Production is confusing.

Best of luck with Apple SSO!

**Comment by oliver139** [comment]
> Daaaang... I totally thought my code was doing it, at first. LOL. Please remove the message as soon as you can guys. Its pretty annoying. :(

Me too LOL
Especially I am working on a bootstrap project

**Comment by JannesMeyer** [comment]
# Downgrade instructions for Firefox

1. Go to [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/versions/), look for version **2023.12.1** and click "Download file":

    <img width="832" alt="image" src="https://github.com/bitwarden/clients/assets/704336/6647f756-75ef-4992-a96d-ac009d9985d9">

2. After the download finishes click on "Add":

    <img width="436" alt="image" src="https://github.com/bitwarden/clients/assets/704336/3816f135-4507-4d0b-8ff5-bc76bb1df192">

3. Go to the extension settings and disable automatic updates:

    <img width="675" alt="image" src="https://github.com/bitwarden/clients/assets/704336/87721ab3-2424-447c-9ec7-0b83e49019db">

**Comment by mousedownmike** [comment]
This seems like a valid reason to report the extension to Mozilla.  I can't wrap my head around a February 7 fix fo this.

![image](https://github.com/bitwarden/clients/assets/47116171/320f343e-784f-4509-a763-95bdf5a08c23)

**Comment by MidnightTinge** [comment]
when you get to the point people are suggesting to downgrade and **disable auto updates** I really do gotta question some of the logic being thrown around to justify not reverting. I love the tool, but this makes me question whether or not I trust updates in the future to not disrupt my daily flow. the fact that this wasn't even considered to be put behind a flag is weird, doubly so considering this is in an "RC" that somehow got pushed out to the general public? or maybe I missed some context there.

regardless, the fact that this won't be disabled until February is incredibly annoying, especially for a tool that I'm paying for. my options are to either disable bitwarden, disable my framework's devtools, or downgrade and disable updates. none of those are appealing options.

**Comment by schulzjona** [comment]
> when you get to the point people are suggesting to downgrade and **disable auto updates** I really do gotta question some of the logic being thrown around to justify not reverting. I love the tool, but this makes me question whether or not I trust updates in the future to not disrupt my daily flow. the fact that this wasn't even considered to be put behind a flag is weird, doubly so considering this is in an "RC" that somehow got pushed out to the general public? or maybe I missed some context there.
> 
> regardless, the fact that this won't be disabled until February is incredibly annoying, especially for a tool that I'm paying for. my options are to either disable bitwarden, disable my framework's devtools, or downgrade and disable updates. none of those are appealing options.

Filtering is not an option for you?

**Comment by MidnightTinge** [comment]
> > when you get to the point people are suggesting to downgrade and **disable auto updates** I really do gotta question some of the logic being thrown around to justify not reverting. I love the tool, but this makes me question whether or not I trust updates in the future to not disrupt my daily flow. the fact that this wasn't even considered to be put behind a flag is weird, doubly so considering this is in an "RC" that somehow got pushed out to the general public? or maybe I missed some context there.
> > regardless, the fact that this won't be disabled until February is incredibly annoying, especially for a tool that I'm paying for. my options are to either disable bitwarden, disable my framework's devtools, or downgrade and disable updates. none of those are appealing options.
> 
> Filtering is not an option for you?

I need to be able to filter other logs (which makes the regex exclusion disruptive, I'm either filtering for one thing or filtering OUT the bitwarden stuff), and we log out to the debug channel (so I can't just exclude that channel). I'm in that group of people that are just altogether screwed 😄 while there are workarounds, it's incredibly disruptive to my flow either way unfortunately hence my frustration

**Comment by rathpc** [comment]
This issue actually just started interfering with how github was loading some of my repositories (stalling to the point of an unresponsive script where I couldn't even open dev tools). I have chosen the option of downgrading for now but I am really surprised that this was ever pushed into production and upon seeing that it has had a large impact that an urgent hotfix is not yet being considered.

**Comment by aminomancer** [comment]
Hello, I'm wondering if this is known to have a performance impact. I noticed the logs while debugging some of my own code, but ignored it for a while by filtering it out. When I closed the tab, my browser froze for several seconds. Now everything's a bit laggy and stuttery. I'll restart of course (which I normally wouldn't do for weeks at a time 😛), and I've rolled back the update myself, so it's not the end of the world. And I'll most likely remember to re-enable updates.

But if this does have a major performance impact, which my experience at least hints at, I think that might be a reasonable justification for shipping a dot release ahead of schedule. If that is the case, then I believe filtering is not a solution to the performance issues.

Also, it's risky to have users roll back and disable automatic updates. They may forget to ever re-enable it, and then a segment of users will be unreachable by updates.

With that said, I don't know anything about your processes so I can't guess how disruptive a dot release would be for your release schedule. I just wanted to register my personal experience, as I'm not sure the performance impact for users has been considered.

**Comment by CodeF53** [comment]
If you do roll back and disable automatic updates, just subscribe to the issue so you see it close so you get reminded to turn them back on.

**Comment by laurengore42** [comment]
There's no way it doesn't have a performance impact - I'm seeing a debug log roughly every second (when I'm trying to work on my own code). Yes I have the debug channel turned off so I don't see the flood of messages, but the information is still in my browser.

**Comment by aspiers** [comment]
Tangential to the problem at hand, but I just wanted to say how refreshing it is to see such consistently polite and constructive discussion in this issue, despite the clearly significant amount of irritation this has caused a number of web developers (including myself).  So many other communities would descend into mud-slinging and insults, so this speaks volumes to the quality of the Bitwarden user community I guess :heart:

And thanks a lot to @justindbaur for his transparent and honest communication "under fire" - this is great to see :clap: 

That said, I will add my voice to the list of people who really think that an emergency hotfix release is warranted.  We're talking about literally removing a single line of code, which surely could have been done with less time and effort than this whole issue has required?  So @justindbaur, I would suggest you go back to the people referred to here:  

> Hi All, I am not the one that makes the go/no-go call on a release but I can assure you the people who do are aware of this issue and the comments you are making. It's not off the table but as of now we aren't planning on another release for this.

and ask them to think again.  Or if there is some reason why cutting an emergency hotfix release to remove one line of code isn't as straightforward as it seems, then explaining that to the community would go a long way towards making people more patient with the status quo.

**Comment by gammons** [comment]
hi @justindbaur could you set our expectations for when this will be fixed?  Thank you!

**Comment by bacf5** [comment]
> There's no way it doesn't have a performance impact - I'm seeing a debug log roughly every second (when I'm trying to work on my own code). Yes I have the debug channel turned off so I don't see the flood of messages, but the information is still in my browser.

Yep, definitely had a performance impact on my computer, had a few crashes. My mistake was leaving too many tabs open but who doesn't?

I hope they solve it soon.

**Comment by CodeF53** [comment]
> Or if there is some reason why cutting an emergency hotfix release to remove one line of code isn't as straightforward as it seems, then explaining that to the community would go a long way towards making people more patient with the status quo.

From what I have seen with extensions, they can take weeks to months to get updates approved. But that probably can be fast tracked given how big bitwarden is.

**Comment by ITedInnovator** [comment]
> We are constantly developing and pushing code to `main`. When we are preparing for release we create a branch called `rc`. From that point on, that branch is only to be updated with the express approval of our QA, essentially only critical bug fixes. We were encountering what we consider a release blocking bug where our SSO flow in our Safari browser extension was not working. I spent hours trying to recreate the issue but was unable to. In a desperation attempt I requested, internally (to my manager, our QA team, and our devops team), approval to cherry pick a commit adding only logging to `rc`. That commit can be found [here](https://github.com/bitwarden/clients/commit/e8a54a70a5d136d4e0d7ccdb15d5056d681c3f47). It was decided to do it there _because_ we didn't want it in `main` and to become a regular part of our code.
> 
> We knew the logging would be in released code, my manager asked me if it would be okay to release and I said yes it would be fine to release since we don't actually log any of the payloads of any message sent through the window messaging API, which I would have considered an issue. I admittedly underestimated the differing extensions that heavily utilize `window.postMessage` on websites and how many people utilize the debug channel of logs in dev tools.

Did your manager check with the security team that it isn't leaking any information it shouldn't? For a password manager I would expect more thorough procedures before logging to the live app.

**Comment by fergalmoran** [comment]
Hey all, give @justindbaur a break.
He's being _incredibly_ earnest and honest here, _way_ more than I've personally come to expect from maintainers of commercial open source software. 

I know it's disappointing that it's taking this long for a fix but we don't know the internal workings of the Bitwarden team. There are enough workarounds posted for the time being and it will be fixed when it's fixed.

**Comment by aspiers** [comment]
> > Or if there is some reason why cutting an emergency hotfix release to remove one line of code isn't as straightforward as it seems, then explaining that to the community would go a long way towards making people more patient with the status quo.
> 
> From what I have seen with extensions, they can take weeks to months to get updates approved.

If true, that would not be a reason to avoid doing a quick hotfix; in fact, if anything it would be a reason to do one ASAP instead of waiting for the next normal release.

**Comment by noelhibbard** [comment]
For those saying this extra logging should only apply to people testing. It's possible that the bug they are trying to catch with the extra logging is so rare that they couldn't restrict the logging to just a subset of testers. They probably needed a larger pool. Also, the average user isn't in the dev console and developers should already know how to filter unwanted messages from the console without hand holding. The outrage here is a little overblown.

**Comment by laurengore42** [comment]
'If you accidentally push code to production, you should take it out again' is not really outrage. I was pleased to find a thread that explained why my browser console was doing that.

**Comment by therealstein** [comment]
Especially when dealing with iframes and window messages, this extension causes the browser to crash.
![Screenshot 2024-01-22 at 11 12 59](https://github.com/bitwarden/clients/assets/31182980/db4efc09-9dc7-4e2f-81de-1bda237cb7eb)

**Comment by nick-shmyrev** [comment]
> I know it's disappointing that it's taking this long for a fix but we don't know the internal workings of the Bitwarden team. There are enough workarounds posted for the time being and it will be fixed when it's fixed.

True, there are workarounds, and "fixed when it's fixed" is probably good enough for a free product. But is "waiting 3 weeks to fix a known issue caused by a single line of code" good enough for a paid tier? For me, the answer is no.

**Comment by JDuchniewicz** [comment]
Very interesting finding, launched my app and was dumbstruck but then I remembered installing this extension.

**Comment by JxEngel** [comment]
Not sure if this helps others or has been mentioned above... I was experiencing this and found that if I login to the extension it goes away.

**Comment by justindbaur** [comment]
Hey all, happy update, we are preparing a release that will remove the logging. You can see the diff from our previous release [here](https://github.com/bitwarden/clients/compare/browser-v2024.1.0...hotfix-rc-browser). This should remove all the logging you see from us on your various sites. Please note that updates to browser extensions go through a review on their respective stores. This process can sometimes take several days but we will be pushing this update to 100% of users right away so you should get the update soon after approval. 

If we are to ever release any logging in the content scripts we will be sure to make it opt-in so that none of our fellow developers have to have this affect them but I also assure you that is was a very one-off scenario and I don't foresee the need for logging in this part of the application to needed ever again.

**Comment by JannesMeyer** [comment]
Thank you, @justindbaur. I really appreciate your hard work on Bitwarden

**Comment by sneakers-the-rat** [comment]
hell ya ty. appreciate your responsiveness, thx for handling this <3

**Comment by Akila-I** [comment]
just came across this issue, and read through the whole thread. Appreciate the hard work on open source. Happily waiting for the update.

**Comment by raelgc** [comment]
Any ETA for the Firefox extension update?

**Comment by schulzjona** [comment]
> Any ETA for the Firefox extension update?

soon

**Comment by oieeaaaa** [comment]
i uninstalled bitwarden - problem solved lol

**Comment by raelgc** [comment]
It's published for Firefox. Thanks guys!
Happy to continue contributing as a Premium user!

**Comment by NotSaviru** [comment]
![image](https://github.com/bitwarden/clients/assets/147316385/e2a384f7-5166-447d-9398-8a731e328a2e)

**Comment by Xanax-C-137** [comment]
@NotSaviru Update to 2024.1.1

**Comment by NotSaviru** [comment]
updated but sometime it appears

**Comment by noc2spam** [comment]
> Hey all, happy update, we are preparing a release that will remove the logging. You can see the diff from our previous release [here](https://github.com/bitwarden/clients/compare/browser-v2024.1.0...browser-v2024.1.1). This should remove all the logging you see from us on your various sites. Please note that updates to browser extensions go through a review on their respective stores. This process can sometimes take several days but we will be pushing this update to 100% of users right away so you should get the update soon after approval.
> 
> If we are to ever release any logging in the content scripts we will be sure to make it opt-in so that none of our fellow developers have to have this affect them but I also assure you that is was a very one-off scenario and I don't foresee the need for logging in this part of the application to be needed ever again.

Thank you so much for the update! Really appreciated.
