### ISSUE TITLE
Input fields aren't recognized by browser extension

### ISSUE THREAD

**Issue by X58hFBt5** [bitwarden/clients#7587]
### Steps To Reproduce

0. Add credentials for aalto.fi in Bitwarden Firefox Browser Extension
1. Go to https://idp.aalto.fi/idp/profile/SAML2/Redirect/SSO?execution=e1s2 which should show a log-in page with two input fields
2. Click on Browser extension icon
3. Click on Credentials in browser extension to fill input fields

### Expected Result

Saved credentials should get filled to the input field for username and password

### Actual Result

Browser extension window closes, but input fields stay empty

### Screenshots or Videos

<img width="1438" alt="grafik" src="https://github.com/bitwarden/clients/assets/156921823/1a33bc6d-6ccf-4c5e-bf66-22193104eb07">

### Additional Context

HTML tags should make the input field discoverable for the browser extension

### Operating System

macOS

### Web Browser

Firefox

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

The team is aware that some sites' login forms aren't been autofilled by our extension. This is something we are actively working on, so if you could please follow this link and complete the form: https://github.com/bitwarden/clients/issues/1621 that would help us a lot.

Thank you for your cooperation and understanding.
