### ISSUE TITLE
2024 releases are missing binaries

### ISSUE THREAD

**Issue by thisismygitrepo** [bitwarden/clients#7599]
### Steps To Reproduce

We used to have the binaries for every architecture and OS, but not anymore. Is this setback deliberate?

Thanks.

### Expected Result

NA

### Actual Result

NA

### Operating System

Windows, macOS, Linux

### Shell

Bash, Zsh, PowerShell

### Build Version

NA

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @thisismygitrepo,

Do you mean the assets on the [CLI releases](https://github.com/bitwarden/clients/releases?q=cli&expanded=true), because those are all there? Same as in all the previous releases.

Kind regards,
Daniel

**Comment by thisismygitrepo** [comment]
Hmmm, I was either dreaming or I looked while they were being published.
This is embarassing.
