### ISSUE TITLE
[Major bug] Master password reprompt option not available for new pwd entries/as well as not honored for existing entries on browser extension

### ISSUE THREAD

**Issue by ashutoshsaboo** [bitwarden/clients#7614]
### Steps To Reproduce

1. Save few entries with master pwd enabled on mobile/BW webapp. Browser extension autofills the same without asking for master pwd. When you go to edit item of previously saved entry, you wouldn't even see master pwd reprompt option - hence you can't even create new entries with master pwd enabled on browser extension. This is a major bug and should be fixed soon. 

### Expected Result

Should prompt for master pwd for previously enabled entries (as expectedly handled by the mobile apps/BW webapp vault), also should show option to enable/disable master pwd for pwd entries. 

### Actual Result

Mentioned above already

### Operating System

macOS

### Web Browser

Brave

### Browser Version

1.61.109 Chromium: 120.0.6099.144 (Official Build) (arm64) 

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/7405

**Comment by djsmith85** [comment]
Hi @ashutoshsaboo,

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/7405.

This issue will now be closed.

Thanks!

**Comment by ashutoshsaboo** [comment]
Thank @djsmith85 , given this is a major bug for the browser extensions - is a release planned anytime soon for the browser extensions? It's almost kind of a security bug for the browser extensions in some sense.
