### ISSUE TITLE
Dynamic fido2 content script injection alters XML responses

### ISSUE THREAD

**Issue by prettybits** [bitwarden/clients#7618]
### Steps To Reproduce

1. Go to any page serving XML (with fitting content-type header, e.g. `application/xml` as on https://earksip.dilcis.eu/profile/E-ARK-SIP.xml where I noticed first)
2. Save the page, i.e. the XML file, to disk
3. Open the saved XML file in an editor
4. Observe that a `<script xmlns="" id="bw-fido2-page-script"/>` element has been appended to the XML root's content (noticeable especially in XML files referencing a corresponding schema and thus likely being shown as invalid in a validating environment)

In Firefox' _General_ settings I have the "Extensible Markup Language (XML)" content type set to "Always ask", I suspect setting this to "Open in Firefox" would be the most reliable way to reproduce. I didn't test this on other browsers.

### Expected Result

The XML file is saved to disk unmodified.

### Actual Result

The XML file has a `<script xmlns="" id="bw-fido2-page-script"/>` element appended to the XML root's content, potentially invalidating XML bound to a schema.

### Additional Context

Introduced with pull request #6845.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by prettybits** [comment]
Hello @Adedamola-Aina , thanks for confirming and working on a solution. While I'm aware that work is tracked elsewhere I didn't take that to mean that issues that aren't fixed yet in a referenceable commit would be closed here? Could you please reopen so affected users are more easily aware?

**Comment by SimonVanacco** [comment]
Hi @Adedamola-Aina, just wanted to add to this : SVG files are impacted by this bug too !
(open .svg in the browser, the script is appended by bitwarden)

**Comment by porl** [comment]
Seconding SimonVanacco - trying to download SVG files results in a corrupted file. The ending `</svg>` tag gets replaced with `<script xmlns="" id="bw-fido2-page-script"/></a0:svg>` even though the "Show Source" page shows it correctly.

**Comment by trmartin4** [comment]
This issue is also described [here](https://github.com/bitwarden/clients/issues/6865) and is being tracked there as we investigate a fix.
