### ISSUE TITLE
Bitwarden treats Google Translate input field as password.

### ISSUE THREAD

**Issue by grundmanise** [bitwarden/clients#7628]
### Steps To Reproduce

1. Go to https://translate.google.com/
2. Paste long text containing word "email" into the translate input:
"""
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. 
Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur? email
"""

### Expected Result

Password autofill should not be triggered

### Actual Result

Password autofill is triggered and overlays the input

### Screenshots or Videos

<img width="1302" alt="Google Translate 20-01-24 12-06-26" src="https://github.com/bitwarden/clients/assets/19417672/97a5da8b-051c-44f4-9309-b53fa8b6ad22">

### Additional Context

Prerequisites:
- Enable show autofill "When field is selected (on focus)" + URI Match by base domain
- Have password saved for google.com

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Web Browser

Chrome

### Browser Version

Version 120.0.6099.129 (Official Build) (arm64)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @grundmanise,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,
