### ISSUE TITLE
When required to enter verification codes 2x in a row, same code is sent to email both times and is not accepted in second prompt

### ISSUE THREAD

**Issue by niole** [bitwarden/clients#7630]
### Steps To Reproduce

prerequisites:
- have 2 factor enabled with email
- have ubuntu desktop app

repro
- login for the first time on desktop app
- follow prompt to enter 2-factor verification code from email
- go to edit 2-factor verification settings in desktop app
- follow prompt to continue the process in the bitwarden web app
- try to log into the web app
- follow prompt for sending a new verification email for completing 2-factor login form via the web app
- 2-factor code sent to email is the same as the code sent for completing 2-factor from the desktop app, which the web app will not accept, because the code has already been used

### Expected Result

2-factor login process from desktop and then subsequently from web app should complete successfully even when done within a 15 minute span of each other

### Actual Result

The same code is sent to my email for authenticating from the web app., This code was previously used to authenticate in the desktop app. The web app does not accept this code, because it was already used. Therefore, I cannot edit my 2-factor auth settings, like I was planning to do.

### Operating System

Linux

### Operating System Version

ubuntu 22:04.3 LTS

### Web Browser

Firefox

### Browser Version

119.0 (64-bit) Mozilla Firefox Snap for Ubuntu

### Build Version

web: 2024.1.1, desktop: 2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @niole,

Thank you for this report. Yes, we are aware of this behaviour and it is the expected behaviour at this stage, and we are working to improve this in a future release. I will keep this GitHub report open for now.

Please remember that the timeout is set to 5 minutes, so a new TOTP code will be generated after 5 minutes which would allow a new Login attempt to take place.

Thank you again,

**Comment by trmartin4** [comment]
Hello,

This issue will be addressed in our next release candidate.  I will close the issue when the release is complete.

Thank you for your patience!

**Comment by trmartin4** [comment]
This issue has been addressed with the latest Bitwarden server release.  If you continue to experience this behavior, please re-open the ticket or submit a new issue.

Thank you.
