### ISSUE TITLE
[Firefox addon] Codecamp tests fail with Bitwarden enabled

### ISSUE THREAD

**Issue by scheinercc** [bitwarden/clients#7632]
### Steps To Reproduce

1. Go to https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-html-by-building-a-cat-photo-app/step-1
2. Follow the steps
3. Click on "Check your code"

### Expected Result

The test passes

### Actual Result

Message is "Sorry, your code does not pass."

### Screenshots or Videos

<img width="632" alt="image" src="https://github.com/bitwarden/clients/assets/817856/32dd9548-1802-4dd4-b0a9-765ce09248b0">

### Additional Context

Disabled all other add-ons. Bitwarden needs to be disabled for the test to pass (for me*).
Checked Developer console and Browser console, but nothing stood out.

*seems to work for anther user, who already flagged an issues with tests passing previously: https://forum.freecodecamp.org/t/test-does-not-pass-with-bitwarden-add-on-active-in-firefox/665353/6

### Operating System

macOS

### Operating System Version

14.2.1

### Web Browser

Firefox

### Browser Version

121.0.1, 122.0b9

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @scheinercc,

Thank you for this report. Can you please add that URL to the extension's [Excluded Domains](https://bitwarden.com/help/exclude-domains/) list, reload the webpage, and let me know if that helps?


Thank you in advance,

**Comment by scheinercc** [comment]
Perfect! Thanks SergeantConfused. That worked.
