### ISSUE TITLE
chromium managed policy updates trigger logout

### ISSUE THREAD

**Issue by daaku** [bitwarden/clients#7650]
### Steps To Reproduce

1. Install a chromium managed policy. BitWarden is installed via this managed policy. Sample policy file (for Linux):
```json
{
  "ExtensionSettings": {
    "nngceckbapebfimnlniiiahkandclblb": {
      "installation_mode": "force_installed",
      "toolbar_pin": "force_pinned",
      "update_url": "https://clients2.google.com/service/update2/crx"
    },
    "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
      "installation_mode": "force_installed",
      "toolbar_pin": "force_pinned",
      "update_url": "https://clients2.google.com/service/update2/crx"
    }
  },
  "3rdparty": {
    "extensions": {
      "cjpalhdlnbpafiamejdnhcphjbkeiagm": {
        "adminSettings": "{\"userSettings\":{\"colorBlindFriendly\":true}}"
      }
    }
  }
}
```
2. Sign into BitWarden.
3. Do **not** quit the browser. This issue does not happen if the policy update is deployed while the browser is not running.
4. Deploy an updated managed policy. For example change the `colorBlindFriendly` to `false` above (this is unrelated, but triggers a change).

### Expected Result

The BitWarden browser extension state should be preserved and not lost.

### Actual Result

The BitWarden browser extension state is lost and the user is signed out.

### Operating System

Linux

### Operating System Version

Linux 6.7.0

### Web Browser

Chrome

### Browser Version

121.0.6167.71

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

After reviewing this report with the engineering team, I can confirm that Bitwarden doesn't really have control over this triggered logout, as the settings changed live on Chrome's extension policies and not on the Bitwarden client setting. Bitwarden doesn't intentionally trigger a logout action in cases like this.

We use GitHub issues as a place to track bugs and other development related issues. This issue will now be closed. 

Thanks!
