### ISSUE TITLE
Firefox extension constantly logs out

### ISSUE THREAD

**Issue by juarez-spa3** [bitwarden/clients#7661]
### Steps To Reproduce

1. Open Firefox incognito mode
2. Log in to Bitwarden extension
3. After 1-2 seconds click on the extension again. The session will close by itself in as little as 1 second.

This works as expected in Chrome incognito mode.

### Expected Result

The session must remain open unless the user closes the browser.

### Actual Result

The session logs out automatically and you are asked to log in again. (I'm talking about the vault locking itself.)

### Screenshots or Videos

<details open>
<summary>Screenshot</summary>

![ffbug](https://github.com/bitwarden/clients/assets/153795294/e4f45d45-b6ae-420c-9bd1-c677b6ef61fb)

</details>

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Web Browser

Firefox

### Browser Version

122

### Build Version

22H2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin with Firefox limitations within Private windows. https://bitwarden.com/help/private-mode/

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
