### ISSUE TITLE
No passkeys found for this application.

### ISSUE THREAD

**Issue by janmashat** [bitwarden/clients#7663]
### Steps To Reproduce

With the Bitwarden browser extension enabled, try to login on a site that utilizes FIDO2 for MFA.

### Expected Result

Receive the browser's default prompt for the FIDO2 security key: 
<img width="920" alt="Screenshot 2024-01-24 at 11 35 12" src="https://github.com/bitwarden/clients/assets/12157479/138d21bc-8d37-4d47-b7ab-5b5b3cf6edc6">

### Actual Result

Bitwarden states "No passkeys found for this application." 
<img width="1244" alt="Screenshot 2024-01-24 at 11 21 48" src="https://github.com/bitwarden/clients/assets/12157479/265fef42-4185-4d2e-a824-90382eab4f55">

### Additional Context

As convenient as storing passkeys in bitwarden may seem, it practically bypasses the "something you have" factor that's recommended for [MFA](https://csrc.nist.gov/glossary/term/multi_factor_authentication). We've been requiring FIDO2 security keys on most of our services for 5+ years now, so I find it troubling that Bitwarden has decided users should jump through hoops in order to find the authentication screens that have automagically appeared up until now. In other words, this "authentication flow hijacking" should have been added as an OPT-IN feature.

### Operating System

macOS

### Operating System Version

13.6

### Web Browser

Chrome

### Build Version

120.0.6099.234

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @janmashat 

What you are describing seems to be the intended behaviour of the software.

In the most recent update, https://bitwarden.com/help/releasenotes/#2023-12-0

If you don't want to use the Bitwarden browser extension to prompt you to save and use passkeys for specific sites, you can set [excluded domains] (https://bitwarden.com/help/exclude-domains/). You can also turn off the prompt entirely by:

Navigating to the Settings tab.

Selecting Options.

Unchecking the Ask to save and use passkeys option.

**Comment by jan--m** [comment]
Can these "excluded domains" or turning off the prompt entirely be configured on the server level for enterprise on-prem customers?

**Comment by janmashat** [comment]
Can these "excluded domains" or turning off the prompt entirely be configured on the server level for enterprise on-prem customers?
