### ISSUE TITLE
Contents Flickering

### ISSUE THREAD

**Issue by Pondering133** [bitwarden/clients#7702]
### Steps To Reproduce

1. Open Bitwarden Desktop App
2. Try to interact with it at all
3. Elements flicker, or wont show up until mouse-over

### Expected Result

Not flickering constantly

### Actual Result

Flickers constantly

### Operating System

Windows

### Operating System Version

11 Pro - 10.0.22621 Build 22621

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0 Shell 27.2.0 Renderer 118.0.2993.159 Node 18.17.1 x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ericlau-solid** [comment]
I have this issue as well. Only happens when bitwarden app is open. Happens on all recent nvidia drivers, including the latest one 551.75 on windows 11 pro.

**Comment by Pondering133** [comment]
I have g-sync (with 140fps limit) and Fastsync (vsync option) enabled in my Nvidia control panel. What settings are @matthlsile and @ericlau-solid using?

**Comment by ericlau-solid** [comment]
I resolved the issue on my computer. It's g-sync. It was enabled for windowed and full screen mode. As soon as I set it so G-Sync is only enabled for full screen mode, bitwarden no longer flickers.

**Comment by Pondering133** [comment]
That's good you found the root cause. Disabling a feature used for all other apps isn't resolving that issue within bitwarden. @jtodddd can you reproduce the issue?
