### ISSUE TITLE
Serbian Translation

### ISSUE THREAD

**Issue by crnobog69** [bitwarden/clients#7704]
### Steps To Reproduce

1. Go to settings
2. Change the language to "sr - Српски"

### Expected Result

Letter "Љ, њ"

Letter "Њ, њ"

### Actual Result

Letter "Лј, лј"

Letter "Нј, нј"

![image](https://github.com/bitwarden/clients/assets/79972075/9d5f8300-b85f-4a50-b4ed-ef530d92bee3)

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/79972075/4441d60a-c2c5-4673-89d4-bda577330394)

![image](https://github.com/bitwarden/clients/assets/79972075/cde1e68a-b814-43fe-a6bf-1a9a2d28dbac)

### Additional Context

I know you might not care for this small thing but I thought I should mention it.

The Serbian language uses the alphabets Latinic (Abeceda) and Cyrillic (Азбука), but they are used at the same time, you either use latinic or only Cyrillic when writing something

The letter "Lj" in Latinic is indeed "Lj" but in Cyrillic is "Љ"

The Serbian Cyrillic translation for the letter "Lj (Latin alphabet)" is "Љ"  not "Лј".

Same goes for the letter "Nj", Cyrillic is "Њ".

For example the word "locked" on Serbian latinic is "zaključano", on Serbian Cyrillic is "закључано".

Now for letter "Nj" ("Њ"), let's take the word "sleeping", latinic is "spavanje" but cyrillic is "спавање".

Note: This is not constant in the application, somewhere is indeed written "Њ, њ" and "Љ, љ" but in some places is not, like in places that i provided the screenshot for.

### Operating System

Windows

### Operating System Version

11

### Installation method

Microsoft Store

### Build Version

Верзија (Version) 2024.1.0 Shell 27.2.0 Renderer 118.0.5993.159 Node 18.17.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @crnobog69 and thank you for your report.

We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌
Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/#localization-l10n) for further information.

New translations can be added or existing ones can be up-/down-voted

Closing this now.
