### ISSUE TITLE
An Instance of Vault Corruption on Key Rotation

### ISSUE THREAD

**Issue by quexten** [bitwarden/clients#7709]
### Steps To Reproduce

This is a case of vault corruption when using the "rotate-key" feature. 
Under some circumstances (bad network, or https://github.com/bitwarden/clients/issues/5770, https://github.com/bitwarden/clients/issues/8274, https://community.bitwarden.com/t/my-vault-is-empty-urgent-help/64270/1 or others that have not yet been triaged), the vault fails to sync and is empty. The web client lets the user rotate the key in this state, rendering their entire vault corrupted, since the vault stays encrypted under the old encryption key.

To reproduce reliably:

**WARNING: THIS WILL RENDER THE ACCOUNTS ENTRIES UNDECRYPTABLE, ONLY DO THIS WITH A TEST ACCOUNT**

1. Login in to your vault
2. Block the /api/sync url (to simulate sync failure reliably)
3. Log out
4. Log back in
5. Your vault is now empty
6. Rotate your encryption key
7. Log out
8. Unblock the /api/sync url
9. Log in
10. Your vaults contents are now undecryptable

### Expected Result

Rotating the encryption key should be prevented when there was a sync failure. It should not be possible to corrupt your vault.

### Actual Result

Rotating your encryption key causes your vault to get corrupted.

### Screenshots or Videos

[Screencast from 2024-01-27 14-32-47.webm](https://github.com/bitwarden/clients/assets/11866552/4c58205c-9487-4140-bcdf-174630b2d508)

### Additional Context

The root cause:
The key rotation works by the web vault taking the local state of the vault (ciphers/folders), and re-encrypting them using the new key. It then submits the newly encrypted vault in one request to the backend. Since the web vault has no ciphers upon sync failure, nothing gets re-encrypted, but the key gets changed. Thus, all old ciphers become unreadable.

To fix this, we should:
1.) Prevent key rotation after a sync failure in the web vault
2.) **Have the backend validate the number of ciphers in the key rotation request against the backend-stored ciphers**

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Safari, Microsoft Edge, Firefox, Opera, Brave, Vivaldi

### Build Version

2024.1.2 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for the report, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by quexten** [comment]
Fixed by the referenced PR's.
