### ISSUE TITLE
If the Bitwarden browser extension and the Send to Kindle extension are active in the browser, drop-down menus may appear unexpectedly on some sites.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#7743]
### Steps To Reproduce

1. Install Bitwarden browser extension on Chrome and log into a Bitwarden account through the extension.
2. Install the [Send to Kindle](https://chromewebstore.google.com/detail/send-to-kindle-for-google/cgdjpilhipecahhcilnafpblkieebhea) extension on the same browser.
3. Navigate to (https://dbrl.bibliocommons.com/user/login).

### Expected Result

The webpage should be displayed correctly.

### Actual Result

The webpage includes drop-down menus at the bottom which seem to do nothing.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/73389600/55470051-5139-4b02-ac85-e222a42889d3)

### Additional Context

If you deactivate either the Bitwarden browser extension or the Send to Kindle extension, those drop-down menus would not appear. Also, if you add that URL to the Bitwarden browser extension's Excluded Domains function, those drop-down menus would not appear.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Chrome

### Browser Version

120.0

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@SergeantConfused 

Thank you for your bug report.

This issue should be fixed in the next extension release. The fix for this behavior should be resolved by https://github.com/bitwarden/clients/pull/7464 

I'm closing this as a result, if the problem persists past the next extension release we can re-open this to investigate.
