### ISSUE TITLE
The Firefox browser extension causes a web page to not load products

### ISSUE THREAD

**Issue by meyou69** [bitwarden/clients#7755]
### Steps To Reproduce

1. Activate the Bitwarden - Free Password Manager extension in the latest version of firefox.
2. Load the following web page: https://www.tuxedocomputers.com/en/Linux-Hardware/Linux-Notebooks/Alle.tuxedo
3. Notice that nothing gets loaded on that page. This is a products page that you can view to order laptops from. This page should have been populated with a lot of results

### Expected Result

The page should have contained many laptop products on it

### Actual Result

No products get loaded at all, and the page is mostly blank

### Additional Context

Disabling the extension and reloading the same page afterwards yields products actually appearing.

Also, please keep in mind that I already reported this bug to Tuxedo computers devs so that they will take a look at it as well. If the issue is from their side, chances are that they'll fix the bug on their end and you won't be able to reproduce it anymore. Please be aware of that

### Operating System

Linux

### Operating System Version

Fedora version 39

### Web Browser

Firefox

### Browser Version

122 (64-bit)

### Build Version

2024.01.01

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adaorajr** [comment]
I have exactly the same problem, but with another website, in my case it is a website belonging to a service provider for the company I work for.
When I uninstall Bitwarden, or go into the anonymous tab, it works normally..
In other browsers, like Chrome, it works normally even with the extension.

Below is a print of the error that appears in the console.
![unnamed](https://github.com/bitwarden/clients/assets/52392256/730786e9-be24-4502-b2c7-3dbaaba60d52)

**Comment by NovaSilentium** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Adaorajr** [comment]
any update on this?

**Comment by meyou69** [comment]
At least for my case, the cause seems to have been Tuxedo's website having a very strange bug.

I believe that they have solved and fixed the bug, since then. I cannot speak for other websites, though

**Comment by Adaorajr** [comment]
Just to update, the website I had was having problems, today I tried to log in, and it just worked! I don't know what changed, but now my problem has been solved, I won't need to go into anonymous tabs anymore :)))
