### ISSUE TITLE
Desktop app creates ~/tmp on launch

### ISSUE THREAD

**Issue by daeh** [bitwarden/clients#7758]
### Steps To Reproduce

1. Remove `~/tmp` if it exists
2. open Bitwarden desktop app

### Expected Result

Desktop app should not create the directory `~/tmp`

### Actual Result

Desktop app creates the directory `tmp` in the home folder.

### Screenshots or Videos

![CleanShot 2024-01-31 at 15 02 47](https://github.com/bitwarden/clients/assets/12652166/4ed17287-0ce0-479d-a510-a139a1baf8e9)

### Additional Context

I’ve been trying to track down why a folder named “tmp” keeps being created in my home directory. I finally set up a `launchd` process and it turns out that the Bitwarden desktop application is the culprit. The `~/tmp` directory seems to be created every time the app launches. It has been happening for around a year.

macOS applications should not be writing to `~/tmp` — it should be `/tmp`, `/private/tmp`, `/var/tmp`, etc.).

I initially reported the issue on the forms based on:
Bitwarden Desktop Version 2023.12.1 (16254)
macOS Ventura 13.6.3

I am not using the following and still experiencing the issues:
Bitwarden Desktop Version 2024.1.0 (18112)
macOS Ventura 13.6.3

### Operating System

macOS

### Operating System Version

13.6.3

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0 (18112)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software that is downloaded directly from the Bitwarden downloads page. If you would prefer no tmp folder is created, I recommend installing the Bitwarden app directly from the Mac App Store: https://apps.apple.com/us/app/bitwarden/id1352778147?mt=12?browser=macos

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by michaelvanstraten** [comment]
> Your issue appears to be describing the intended behavior

How is this intended behavior?

**Comment by michaelvanstraten** [comment]
Why cant this be `os.tmpdir()`?
https://github.com/bitwarden/clients/blob/f3beb71d6de6f8ed6c51b16045406619ad30d92a/apps/desktop/src/proxy/ipc.ts#L14

**Comment by daeh** [comment]
> macOS applications should not be writing to `~/tmp` — it should be `/tmp`, `/private/tmp`, `/var/tmp`, etc.).

@Neonwarden If that's the intended behavior, it shouldn't be. There are various MacOS tmp directories but `~/tmp` is not one.

**Comment by michaelvanstraten** [comment]
If something within the user directory is required maybe `~/.local/state/bitwarden` is the right path here.

**Comment by michaelvanstraten** [comment]
@Neonwarden could you please reopen the issue.

**Comment by michaelvanstraten** [comment]
@onjonjo, I would make a PR, can you give some insight why this was implemented this way?

**Comment by amsterford** [comment]
Have the same issue. Just caught BW on making directory ‘~/tmp’. It’s rather annoying to see that folder to be created every time BW starts. I don’t need such folder in my Home directory. I find it pointless, it should be created somewhere around ‘~/Library/Application Support/Bitwarden/’ I guess.
![CleanShot 2024-02-19 at 17 50 54](https://github.com/bitwarden/clients/assets/94016340/cb058d0f-870c-4edc-b82d-9e9063bc3bd3)

**Comment by michaelvanstraten** [comment]
> Why cant this be `os.tmpdir()`?
> 
> https://github.com/bitwarden/clients/blob/f3beb71d6de6f8ed6c51b16045406619ad30d92a/apps/desktop/src/proxy/ipc.ts#L14
> 
> 
> 
> It should return the same directory on every call even on seperate node processes, so it should be deterministic.

This referenced line is responsible, apparently this is „intended behavior".

**Comment by daeh** [comment]
Maybe worth opening a new issue to try to raise the concern that this _shouldn't_ be the intended behavior? Seems hard to get @Neonwarden's or anyone else's attention on a closed issue.

**Comment by michaelvanstraten** [comment]
> I believe turning off browser integration and/or ddg integration will resolve this issue without needing to modify any code.

If you are referring to the preferences option than no, it does not resolve the issue for me.
