### ISSUE TITLE
How to have Passkey date written in DDMMYYYY format and time in 24h format ?

### ISSUE THREAD

**Issue by oeloo** [bitwarden/clients#7764]
### Steps To Reproduce

1. Go to a website using PassKey (example ebay.fr)
2. Create a Passkey for this website if you do not already have one
3. Just open Bitwarden Chrome extension, you can see the passkey date is in a weird format (MMDDYYYY time in 12h format actually) despite Windows 11 OS in DDMMYYYY and 24h format and all other apps using this format.

### Expected Result

The expected result is a date written in DDMMYYYY format and time in 24h format:
Created 01/02/2024, 11h24

### Actual Result

A date written in MMDDYYYY format and time in 12h format:
Created 2/1/24, 11:24 AM

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/98819304/90d48a82-3ffe-4f18-8b2b-761677689a31)

### Additional Context

It is very a misleading bug: people using date in DDMMYYYY format everywhere on their PC interpret this as the 2nd of January. So it can have bad consequences.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Version 121.0.6167.86 (Official Build) (64-bit)

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Currently there is no way to change the format of the date.

**Comment by oeloo** [comment]
Why do you not even put this in the backlog for the future?
Not everyone is living in the US.
There are lots of people using DDMMYYYY and time in 24h. Furthermore having a date displayed in MMDDYYYY when all your other application use MMDDYYYY can lead to false date interpretation by users.

**Comment by unikitty37** [comment]
If having locale-based dates isn't an option, at least use YYYY-MM-DD, which is unambiguous.
