### ISSUE TITLE
rename top level folder breaks folder structure

### ISSUE THREAD

**Issue by MannCaveDistillIng** [bitwarden/clients#7766]
### Steps To Reproduce

go to folders either in the web client or the desktop client, create a folder, then create 5 or so folders under that, then create 5 or so folders under each of those.
go to the first folder you created at the top, rename it.  all subfolders you created are no longer under the renamed folder.

who links folders by display name???? this is a rookie mistake.. Really?  create an internal ID for each folder to link to!

### Expected Result

subfolders should stay under the renamed folder, like every other system out there.

### Actual Result

subfolders do not stay under renamed folder

### Operating System

Windows, macOS, Linux

### Operating System Version

any

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

This is expected behaviour at this time. Renaming the parent folder will break the overall structure. A solution to this will come in the future with better folder management.
