### ISSUE TITLE
Password generator missing technical details (estimates are not trustworthy)

### ISSUE THREAD

**Issue by polarathene** [bitwarden/clients#7782]
### Steps To Reproduce

- Access the password generator
- Choose passphrase
- Notice no clear source of entropy documented, nor how the time to crack estimate is calculated.

**Reference:**
- Browser: https://bitwarden.com/password-generator/
- Should be applicable to other clients: https://bitwarden.com/help/generator/

### Expected Result

It should be possible to know the bits of entropy the configured generator represents, ideally with source.

### Actual Result

No meaningful entropy is given. No source of words is provided (_which could be used to derive the entropy_). Only blind trust.

---

Worse, the estimated time to crack is changing from "centuries" to "33 years" for two 3 word examples:

![image](https://github.com/bitwarden/clients/assets/5098581/54752002-4b49-42a3-9c8d-c55614010e00)

![image](https://github.com/bitwarden/clients/assets/5098581/c7d74755-b610-4dcd-ace7-a87d6bc6a26e)

That is inaccurate, it should be based on [Kerckhoff's Principle](https://en.wikipedia.org/wiki/Kerckhoffs%27s_principle), meaning calculated against the actual entropy of the generator (pattern).

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5098581/390d6408-de88-4899-88aa-ee81313e728b)

The passphrase example:
- "Capitalize" contributes no entropy.
- "Include Number" contributes a small amount of additional entropy, but generally diminishes the UX value at that expense.
- "Word separator" contributes no entropy.
- "Words" is the main entropy factor. The word pool size is unknown.

It looks like the generator is fairly simple and all word items take from the same pool of words. That should be fairly easy to document or link source to. Ideally the UI would also convey the entropy in bits.

Alternatively allow generation of passphrase in bits [as `getapassphrase.com` does](https://getapassphrase.com/generate/).

### Additional Context

`getapassphrase.com` has a more memorable (albeit longer) passphrase generator, [where it's rules to generate the passphrase aren't as simple](https://github.com/openidauthority/getapassphrase/blob/817c28a871c9b9af612b99b4e5287f35bb8a4a69/web/js/passphrasegenerator.js#L87-L119), but the entropy calculation is.

Example (_44-bit passphrase, bcrypt `wf=10` vs single Nvidia RTX 4080_):
- `puzzled pro has light minnow` (_[44-bit](https://github.com/openidauthority/getapassphrase/blob/817c28a871c9b9af612b99b4e5287f35bb8a4a69/web/js/passphrasegenerator.js#L88), aka `9 + 9 + 8 + 9 + 9 = 44 bits`, a subset from the 1024 / 512 word sets used_)
- Time to attack 50% keyspace coverage: `(([entropy] / [hashrate]) / [seconds of compute]) / 2 = [time required]`
  - [Nvidia RTX 4080 bcrypt hash rate](https://gist.github.com/bigpick/cfa22947c884f7a3fc1431475e345427) as compute example
    - 131,000 H/sec (`Hash-Mode 3200`) => bcrypt work-factor 5 (_32 iterations_)
    - 4,700 H/sec (`Hash-Mode 30600`) => bcrypt work-factor 10 (_1024 iterations_)
  - `((2^44 / 4.7e3) / (60*60*24*365)) / 2 == 59.3 years` => 44 bits of entropy attacked at a rate of 4,700 attempts per second, divided by seconds in a year.

If Bitwardens generator was using a pattern of random words from a pool of 2048 words (11-bit), four words would be equivalent to the 44-bit entropy as demonstrated above, with the same 59 year time for an attacker (_with that compute power against the target hash, details also missing from the "Estimated time to crack" result_).

I get that these are details that are generally noise to most users, but there should be a visible resource available to those that care about it if the generator is to establish verifiable trust. It's estimator is not a helpful indicator as demonstrated above.

### Operating System

Windows

### Operating System Version

W11 23H2

### Web Browser

Chrome

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,
We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this(In your case the lack of entropy documentation) : 
onehttps://community.bitwarden.com/c/feature-requests/ 
Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.
Thanks!
