### ISSUE TITLE
Dropdown panels on combobox selector won't open if there is not enough space in the viewport

### ISSUE THREAD

**Issue by stefan0xC** [bitwarden/clients#7836]
### Steps To Reproduce

1. Go to Organizations -> Settings -> Import data
2. Reduce viewport height to 400px and click on File format combobox when it is in the middle of the viewport
3. Click outside to reset the selector
4. Scroll down so that the combox box is at the top
5. Click again and see the dropdown panel

### Expected Result

I expect the drop down panel to show up even if there's not enough space in the view port.

### Actual Result

Nothing is happening (the state of the arrow changes and you have to click outside the combobox to reset)

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/509385/0104a002-fd77-4c6c-87c6-61befed1c26b

### Additional Context

I noticed when I had the browser console open and was wondering why my collections did not show up. (Since you need to have a lot of collections it's easier to reproduce with the list of file formats.)

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Firefox

### Browser Version

122.0

### Build Version

Version 2024.2.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by stefan0xC** [comment]
The issue is possible related to https://github.com/bitwarden/clients/pull/6682

**Comment by stefan0xC** [comment]
I think I found the issue. From the [ng-select](https://github.com/ng-select/ng-select/tree/v10.0.4) README:
> For correct positioning `body` should have `position:relative`

**Comment by willmartian** [comment]
Thanks a lot @stefan0xC! I missed that note in the ng-select docs. 😮‍💨
