### ISSUE TITLE
Unable to edit passwords of vault items in browser extension

### ISSUE THREAD

**Issue by linuxkn1ght** [bitwarden/clients#7944]
### Steps To Reproduce

Go to browser extension.
Search for a vault item.
Click on vault item.
Click EDIT.
Highlight saved password, delete, paste new one.
This no longer works.

Previous to version 2024.2.0, I was able to do this.
I do not know when the extension was updated.
But now with this most recent version, I am unable to edit or delete the password.

In order to be able to edit a saved password, now I have to click on the "eye" icon to make it visible.

### Expected Result

Able to edit a saved password.

### Actual Result

Unable to edit a saved password, must click on "eye" icon to make it visible first, then I can edit.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

Chrome 121.0.6167.161

### Build Version

Bitwarden extension version 2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
Thanks for reporting this to us, the issue is currently under investigation.

To workaround this, you can use the password generator button to over-write the existing password and generate a new one, or toggling the eye button to view the password will also allow you to edit it.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/7889
