### ISSUE TITLE
Chromium global settings don’t work as expected

### ISSUE THREAD

**Issue by VeldoraTheDragon** [bitwarden/clients#7945]
### Steps To Reproduce

1. Configure chromium as described in the wiki: https://bitwarden.com/help/configure-clients/#chrome-and-chromium
2. Open Chromium, go to Extensions, click on Bitwarden
3. Select 'Self-Hosted'
4. See message: "Settings have been edited"
5. Click on "Click here" to reset.
6. Save

### Expected Result

The global config should works flawlessly, as it does in Firefox.

### Actual Result

The extension in chromium requires me to reset the settings, which then sets the URL to the configured value.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/127216238/3a8814ba-5ea3-40aa-83db-d541c89574bc

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Chrome

### Browser Version

121.0.6167.160, update to 121.0.6167.184 pending

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Maas1337** [comment]
Same here with Edge. 

We enrolled a gpo  at HKLM\SOFTWARE\Policies\Microsoft\Edge\3rdparty\extensionid\policy\environment\      base -> url 

After first opening edge ->  a new browser tab opens  (installed bitwarden plugin)

navigating into bitwarden settings and see the same as Veldora.
