### ISSUE TITLE
BitWarden extension automatically open a browser popup on installation

### ISSUE THREAD

**Issue by Zoddo** [bitwarden/clients#7955]
### Steps To Reproduce

1. Configure Chrome or Edge to install the extension automatically like documented in https://bitwarden.com/help/browserext-deploy/
2. Wait until the policy applies (do a "gpupdate" then force refresh policies in chrome://policy to apply it faster)
3. A pop-up pointing to https://bitwarden.com/browser-start/ is automatically opened

### Expected Result

No pop-up is opened when the extension is installed

### Actual Result

A unwanted pop-up pointing to https://bitwarden.com/browser-start/ appears

### Additional Context

We are in the process of deploying BitLocker company-wide, but this issue is a no-go. Users will start calling helpdesk about a random website opening automatically in their browser. New users will get prompted with this popup when they open their browser for the first time.

A browser extension (especially one that officially support to be automatically deployed) shouldn't open pop-ups on installation.

This issue was already reported by someone else on the [community forums](https://community.bitwarden.com/t/deploy-extension-silently/45330) on october 2022 but no response was provided.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, you should upvote the feature request that you found.

I will create an internal note, so someone from engineering can investigate this.

We use GitHub issues as a place to track bugs and other development related issues. This issue will now be closed. 

Thanks!

**Comment by vladgames228** [comment]
Hi there.

Stuck with the same problem here, is there any reg key or something that can disable browser-start page?
