### ISSUE TITLE
New UI on the web extension logs users out, and requires 2FA

### ISSUE THREAD

**Issue by amogusussy** [bitwarden/clients#7971]
### Steps To Reproduce

- Open the web extension. Make sure it's updated.

### Expected Result

The extension should keep the email, and let you log on without 2FA.

### Actual Result

You need to be logged into your email to get the 2FA code to be able to sign in.

This is an issue because I, and likely many others, have their email logins stored in their Bitwarden, and aren't actively signed in on any other platform. 
Because you need a 2FA code, in order to get into your account, you must have access to your email. To get into my email, I need Bitwarden. To get into Bitwarden, I need my email. And it's just an endless loop like that.
Luckily, I have access to my account on my phone, so was able to get into my email to get the 2FA code.

### Operating System

Linux

### Web Browser

Firefox

### Build Version

Librewolf 122.0-1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. The Bitwarden Password Manager provides many different 2FA options, and in this situation, I would recommend using an alternative 2FA option, such an authenticator app. 

If you'd like to discuss the issue with or get help from others Bitwarden users, please join our community forums (https://community.bitwarden.com/c/support/). 

If additional assistance is needed, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

This issue will now be closed. 

Thanks!

**Comment by djsmith85** [comment]
@amogusussy This [article](https://bitwarden.com/events/2021-06-11-introducing-the-triangle-of-security-success/) and the linked crowdcast session, might help educate about protecting your account.

**Comment by amogusussy** [comment]
It may be expected behaviour, but it shouldn't be.

You shouldn't have 2fa enabled without the users knowledge. Especially if the only means of 2fa likely uses your service.
