### ISSUE TITLE
Dutch translation for cardnumber is wrong

### ISSUE THREAD

**Issue by RoyvanEmpel** [bitwarden/clients#7992]
### Steps To Reproduce

1. Add new card or Edit existing card
2. The dutch translation for "cardnumber" is wrong.

### Expected Result

The dutch translation should be "Kaartnummer" instead of "Kaartummer"

### Actual Result

It shows "Kaartummer" missing the N in "Kaartnummer"

### Screenshots or Videos

![Screenshot_20240218_155344](https://github.com/bitwarden/clients/assets/47390057/9eb5bc48-47e7-433e-b8a7-ef3decfa0fd0)

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Web Browser

Brave

### Browser Version

Versie 1.61.116 Chromium: 120.0.6099.217

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @RoyvanEmpel and thank you for your report.

We use Crowdin to manage our translations and these are commonly done by our amazing translation community 🚀 🙌
Please have a look at the localization section [here](https://contributing.bitwarden.com/contributing/#localization-l10n) for further information.

New translations can be added or existing ones can be up-/down-voted

Closing this now.

**Comment by djsmith85** [comment]
The one you mentioned can be found [here](https://crowdin.com/editor/bitwarden-browser/26/en-nl?view=comfortable#1664)

As it does differ from the other clients I have gone ahead and replaced it. The changes will be seen within the next browser extension release.

Kind regards,
Daniel
