### ISSUE TITLE
NextDNS Login Bug

### ISSUE THREAD

**Issue by KnownStormChaser** [bitwarden/clients#7995]
### Steps To Reproduce

1. Go to 'https://my.nextdns.io/login'
2. Have “show auto-fill menu on form fields” set to “when field is selected (on focus)”

### Expected Result

The login page should show as normal.

### Actual Result

A message saying (Permission denied to access property “then”) appears.

### Screenshots or Videos

![Screenshot 2024-02-18 162117](https://github.com/bitwarden/clients/assets/59132294/a6de2ac9-db08-4a19-b2a3-6b39f5d0c9cf)

### Additional Context

To temporarily resolve the issue, “show auto-fill menu on form fields” must be set to Off.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

122.0.1

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so:

![nextdns](https://github.com/bitwarden/clients/assets/5418577/c76e2268-3443-4da5-b59b-83e969d675e1)

If you have performed a clean installation of the browser extension already by removing any leftover data (https://bitwarden.com/help/data-storage/#on-your-local-machine), I suggest you try to refresh your Firefox's profile following their instructions: https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by KnownStormChaser** [comment]
@Greenderella I did perform a Firefox refresh, that is what caused the issue. I recently switched back from Brave to Firefox, and the first thing I did was refresh Firefox. And then this issue came up which I have never experienced before.

**Comment by KnownStormChaser** [comment]
@Greenderella Actually I just found the conflict, you have to have the dark reader extension enabled at the same time, then the error comes up.

**Comment by Greenderella** [comment]
Thanks for letting me know about that extension interference, I will document it, so the team can be aware.

Have a nice day!

**Comment by patin-osu** [comment]
It's seems like it's a extension confliction between Dark Reader extension and Bitwarden (For some reason) and i can reproduce it on my end, Here's the screen capture of what happen:

Dark Reader + Bitwarden
![firefox_PGYMWpqeQR](https://github.com/bitwarden/clients/assets/75104667/72ee1dee-71b5-4a7b-beb9-adcf5326b6cf)

Dark Reader (Disabled) + Bitwarden
![firefox_mby2POMhMZ](https://github.com/bitwarden/clients/assets/75104667/0ebbccfa-1ae5-4195-a4a8-b384ddd841ca)
Looking forward for a fix!

**Comment by n3kr0X** [comment]
> It's seems like it's a extension confliction between Dark Reader extension and Bitwarden (For some reason) and i can reproduce it on my end, Here's the screen capture of what happen:
> 
> Dark Reader + Bitwarden ![firefox_PGYMWpqeQR](https://private-user-images.githubusercontent.com/75104667/306901368-72ee1dee-71b5-4a7b-beb9-adcf5326b6cf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDEzNjgtNzJlZTFkZWUtNzFiNS00YTdiLWJlYjktYWRjZjUzMjZiNmNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWQ5ODZmYmU0Mjc2MjYwZWI1OWIzMDNiMDFiNzQ5NTlkZTg5NTZmZjNmZTU3MjJiMTIxMmIwMmUzOGE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezMCXjWAs0-hvb59axTzvhiHEW4cam_JIUQQYgG_F1M) [ ![firefox_PGYMWpqeQR](https://private-user-images.githubusercontent.com/75104667/306901368-72ee1dee-71b5-4a7b-beb9-adcf5326b6cf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDEzNjgtNzJlZTFkZWUtNzFiNS00YTdiLWJlYjktYWRjZjUzMjZiNmNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWQ5ODZmYmU0Mjc2MjYwZWI1OWIzMDNiMDFiNzQ5NTlkZTg5NTZmZjNmZTU3MjJiMTIxMmIwMmUzOGE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezMCXjWAs0-hvb59axTzvhiHEW4cam_JIUQQYgG_F1M) ](https://private-user-images.githubusercontent.com/75104667/306901368-72ee1dee-71b5-4a7b-beb9-adcf5326b6cf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDEzNjgtNzJlZTFkZWUtNzFiNS00YTdiLWJlYjktYWRjZjUzMjZiNmNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWQ5ODZmYmU0Mjc2MjYwZWI1OWIzMDNiMDFiNzQ5NTlkZTg5NTZmZjNmZTU3MjJiMTIxMmIwMmUzOGE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezMCXjWAs0-hvb59axTzvhiHEW4cam_JIUQQYgG_F1M) [ ](https://private-user-images.githubusercontent.com/75104667/306901368-72ee1dee-71b5-4a7b-beb9-adcf5326b6cf.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDEzNjgtNzJlZTFkZWUtNzFiNS00YTdiLWJlYjktYWRjZjUzMjZiNmNmLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2ZWQ5ODZmYmU0Mjc2MjYwZWI1OWIzMDNiMDFiNzQ5NTlkZTg5NTZmZjNmZTU3MjJiMTIxMmIwMmUzOGE4OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ezMCXjWAs0-hvb59axTzvhiHEW4cam_JIUQQYgG_F1M)
> 
> Dark Reader (Disabled) + Bitwarden ![firefox_mby2POMhMZ](https://private-user-images.githubusercontent.com/75104667/306901544-0ebbccfa-1ae5-4195-a4a8-b384ddd841ca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDE1NDQtMGViYmNjZmEtMWFlNS00MTk1LWE0YTgtYjM4NGRkZDg0MWNhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGIwZThlMDA0MTE5NjZmZjRiNTk3NmJiOTcwMDlmNjAzNDk1OTdiY2RkZDM4ODM0NjdiYTkyMWU2YjU5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poImtZDegyp9H4CnstPbHZ2m4WMYF8VEkLvACwlpwrk) [ ![firefox_mby2POMhMZ](https://private-user-images.githubusercontent.com/75104667/306901544-0ebbccfa-1ae5-4195-a4a8-b384ddd841ca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDE1NDQtMGViYmNjZmEtMWFlNS00MTk1LWE0YTgtYjM4NGRkZDg0MWNhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGIwZThlMDA0MTE5NjZmZjRiNTk3NmJiOTcwMDlmNjAzNDk1OTdiY2RkZDM4ODM0NjdiYTkyMWU2YjU5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poImtZDegyp9H4CnstPbHZ2m4WMYF8VEkLvACwlpwrk) ](https://private-user-images.githubusercontent.com/75104667/306901544-0ebbccfa-1ae5-4195-a4a8-b384ddd841ca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDE1NDQtMGViYmNjZmEtMWFlNS00MTk1LWE0YTgtYjM4NGRkZDg0MWNhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGIwZThlMDA0MTE5NjZmZjRiNTk3NmJiOTcwMDlmNjAzNDk1OTdiY2RkZDM4ODM0NjdiYTkyMWU2YjU5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poImtZDegyp9H4CnstPbHZ2m4WMYF8VEkLvACwlpwrk) [ ](https://private-user-images.githubusercontent.com/75104667/306901544-0ebbccfa-1ae5-4195-a4a8-b384ddd841ca.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODM5NDAsIm5iZiI6MTcwODY4MzY0MCwicGF0aCI6Ii83NTEwNDY2Ny8zMDY5MDE1NDQtMGViYmNjZmEtMWFlNS00MTk1LWE0YTgtYjM4NGRkZDg0MWNhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDEwMjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGIwZThlMDA0MTE5NjZmZjRiNTk3NmJiOTcwMDlmNjAzNDk1OTdiY2RkZDM4ODM0NjdiYTkyMWU2YjU5OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.poImtZDegyp9H4CnstPbHZ2m4WMYF8VEkLvACwlpwrk) Looking forward for a fix!

I had the same issue /w Firefox + Dark Reader + BW (perhaps). When I disabled the dark reader for the site and refreshed, I could login again.
