### ISSUE TITLE
nodejs-lts-hydrogen dependency is out-of-date

### ISSUE THREAD

**Issue by fabianmuehlberger** [bitwarden/clients#8039]
### Steps To Reproduce

On Arch Linux, while installing bitwarden-cli, the dependency "nodejs-lts-hydrogen" conflicted with "nodejs"
After checking [archlinux packages](https://archlinux.org/packages/extra/x86_64/nodejs-lts-hydrogen/) I noticed that the package is flagged out-of-date (Flagged out-of-date on 2023-11-29), since it is a LTS release, it cannot be assumed that it will receive an update.

I am not familiar with the security side of Bitwarden or node, but I see a potential flaw. 

### Expected Result

-does not apply

### Actual Result

-does not apply

### Operating System

Linux

### Shell

Bash

### Build Version

2024.2.0-1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by fabianmuehlberger** [comment]
I checked [nodejs end of life](https://endoflife.date/nodejs).

Support for Node v18 ended 4 months ago, but will receive security updates.

**Comment by djsmith85** [comment]
Hi @fabianmuehlberger and thank you for your report.

As you already checked Node 18 is still an maintained LTS release.

The EOL and bump to a newer Node version is something Bitwarden is aware of and will be likely tackling with the move to Electron 29. See my recent comment here: https://github.com/bitwarden/clients/pull/8016#issuecomment-1956664591

Closing this now.

Kind regards,
Daniel
