### ISSUE TITLE
Fields with type="search" break Chrome autofill

### ISSUE THREAD

**Issue by Mart124** [bitwarden/clients#8064]
### Steps To Reproduce

Bitwarden Chrome extension does not fill fields which have `type="search"` property.
Removing this property from the HTML code of the field makes Username (or custom field) to be properly completed.
Adding this property manually to a field breaks its completion.
Note that issue does not occur with (for example) Safari.
Thank you 👍 

### Expected Result

Field filled.

### Actual Result

Field not filled.

### Operating System

Windows, macOS

### Web Browser

Chrome

### Build Version

2024.2.0

**Comment by Krychaz** [comment]
Hello there, 

I was able to replicate this issue using simple HTML fields with the reported property. However I see this issue happening on all browsers. Can you please share a site where this issue is happening on Chromium browser but not on Safari.

**Comment by Mart124** [comment]
Hi @Krychaz
I did further testing with Safari, you're right it does not work with _Username_. But if you define a _custom field_, then it works (I was initially testing with custom fields).
With Chrome, both _Username_ and _custom fields_ do not work.
Thank you again !

**Comment by Krychaz** [comment]
Hi,

After discussing this with our engineering team, this behaviour is to be expected. We expect to always disqualify search field inputs from autofill, even if one matches a custom field pattern.

Filling search could be considered a security/safety concern as well (for example, sites that use external search services)
