### ISSUE TITLE
Psono Import Bug

### ISSUE THREAD

**Issue by Ryeera** [bitwarden/clients#8069]
### Steps To Reproduce

1. Export Passwords from Psono. I have provided a json-file that can replicate this issue: https://pastebin.com/s07ZiAqg
2. Import this file into Bitwarden. I tested this in the Web-Client as well as the Chrome-Extension.
3. Check the imported passwords.

### Expected Result

Each password is imported into its correct folder.

### Actual Result

Only the first password of each folder is imported into the correct folder. All remaining passwords are imported into "No Folder" and have to be moved manually.
This is not limited to one folder, but will happen with as many folders and sub-folders as needed. I tested this with Up to 100 folders, up to 4 levels deep and it happened with every folder.

### Screenshots or Videos

<img width="753" alt="image" src="https://github.com/bitwarden/clients/assets/79052127/7c397b19-7a88-4c8e-ad07-54045d4744fb">

<img width="356" alt="image" src="https://github.com/bitwarden/clients/assets/79052127/3bc529b3-7d4c-4d62-bf3f-9983ecf34434">

<img width="556" alt="image" src="https://github.com/bitwarden/clients/assets/79052127/e588b211-b2b4-4f3f-91eb-35d3221f956e">

<img width="561" alt="image" src="https://github.com/bitwarden/clients/assets/79052127/d733c684-1892-4c4c-8b3e-5c9d6a5f9376">

### Operating System

Windows, Android

### Web Browser

Chrome, Microsoft Edge

### Build Version

Version 2024.2.0, Server Version 2024.2.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @Ryeera and thank you for your report.

This was caught internally and has been addressed with #7984, which will be included in the next release. Scheduled to be released in ˜2 weeks time.

Closing this now.

Kind regards,
Daniel

**Comment by Ryeera** [comment]
Ah yes, that should work. Thanks a lot! <3
