### ISSUE TITLE
vault columns too small: enlarge it or possibility to do it manually in the desktopapp

### ISSUE THREAD

**Issue by DroidBV8** [bitwarden/clients#8083]
### Steps To Reproduce

Hello, 

But why did you make such small columns, especially for the files in the trunk and an empty DIV for information (login, password)

Personally, I have endless names and I can't read them all. This may be the only thing that makes me not switch.

### Expected Result

A larger column. It's just CSS or the ability to expand it with the mouse

.left-nav {
    max-width: 330px;
}

### Actual Result

.left-nav so small

### Operating System

Windows

### Operating System Version

win1123h2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024 2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @DroidBV8,

Thank you for this report. Please feel free to join the Bitwarden Community and to vote for this [feature request](https://community.bitwarden.com/t/allow-adjusting-column-width-to-avoid-wrapping-text/17613) which relates to the Bitwarden Web App and the Bitwarden desktop client; Hopefully we'd be able to support that in the future.

We use GitHub to track bugs and other development related issues; This report will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to join the discussion in the forums.

Thank you again,

**Comment by DroidBV8** [comment]
Hi @SergeantConfused 
You have nothing to do with it but I think that if a simple CSS would have wanted to be implemented since 2021 (date of the first post of your link), I believe that it would have been implemented a long time ago.

So I'm not going to bother creating an account on the forum when this simple and basic request will never be taken into account by the development team.

Simply amazing for a paid service.

I will therefore stay with the competition for the moment because the application is almost unusable as it stands.

I am very disappointed that a company like Bitwarden does not listen to its community.

best regards
