### ISSUE TITLE
I cannot receive the email to get master password

### ISSUE THREAD

**Issue by cerbhe** [bitwarden/clients#8107]
### Steps To Reproduce

create account with password
try to login
never happend
try to get  master password
not receive the email with next steps

### Expected Result

to be able to login

### Actual Result

New account doesn't work

### Screenshots or Videos

![Captura de pantalla 2024-02-27 013853](https://github.com/bitwarden/clients/assets/13489602/a9aa4597-0ef6-4e9b-a642-40b11f27074f)
![Captura de pantalla 2024-02-27 014149](https://github.com/bitwarden/clients/assets/13489602/37adb3c5-4784-423c-9fb6-e3a53508c739)

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

During account creation, have you created your master password hint? 

<img width="582" alt="SCR-20240227-iitr" src="https://github.com/bitwarden/clients/assets/36608718/80f463a6-f9dc-4eb6-b0da-604cf1cca4b2">

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
