### ISSUE TITLE
Firefox extension is cannot proper show an login entry with PassKey in Traditional Chinese

### ISSUE THREAD

**Issue by leeyc0** [bitwarden/clients#8127]
### Steps To Reproduce

Step to reproduce:
Environment: Firefox 123 in Windows 10, need configured in Traditional Chinese interface (You may directly install Traditional Chinese language pack.)
Need A google login entry, with PassKey saved.

### Expected Result

The login entry can show properly

### Actual Result

The login entry display is corrupted, see screenshot

### Screenshots or Videos

![screenshot](https://github.com/bitwarden/clients/assets/2221335/6cee0184-8159-4373-8bc1-f77cdcafef6c)

### Operating System

Windows

### Operating System Version

10 22H2

### Web Browser

Firefox

### Browser Version

123

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @leeyc0 and thank you for your report. Is this possibly a duplicate of https://github.com/bitwarden/clients/issues/6821 ?

**Comment by leeyc0** [comment]
Seems so. I will close this as a duplicate
