### ISSUE TITLE
Extension login allows viewing of password

### ISSUE THREAD

**Issue by kingwill101** [bitwarden/clients#815]
on opening the bitwarden  extension in firefox it allows anyone to view the saved master email and password without an option to disable.

**Comment by kspearrin** [comment]
I am confused. We don't save your master password anywhere...

Perhaps you are still using the built in password manager in Firefox or something?

**Comment by glenfordwilliams** [comment]
disabled the firefox manager  and that seemed to have solved my problem. it should be probably documented somewhere to warn new users.
