### ISSUE TITLE
Compilaton of "web" image fails due to missing "patch-package" and resource limits

### ISSUE THREAD

**Issue by sincerelysaucy** [bitwarden/clients#8162]
### Steps To Reproduce

1. Go to 'apps/web'
2. Follow npm build steps for "web" from .github/workflow/build-web.yml

### Expected Result

Successful npm compilation expected. 

### Actual Result

Build fails by default on "npm ci" command
   *"npm clean" and "npm init" are needed to get past "npm ci" step and make "patch-package" available locally
Forther "npm" steps fail on memory limitations on 4 GB RHEL 8 host.
    ( Set environment with " export NODE_OPTIONS=--max-old-space-size=4096" to allow compilation to complete

### Additional Context

The build host is a modest, 4 GB, RHEL 8 VM.

### Operating System

Linux

### Operating System Version

RHEL 8

### Web Browser

Chrome

### Build Version

web-v2024.2.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment]
Hi @sincerelysaucy,

Please follow the instructions on our contributing docs. https://contributing.bitwarden.com/getting-started/clients/ and https://contributing.bitwarden.com/getting-started/clients/web-vault/

`npm ci` should only be run in the root of the repository, not in the different application directories due to the mono repository nature. Regarding resource limits, the application is fairly large and may require more ram to complete, you can try enabling swap and use it to allocate more memory although the performance will be slower.

**Comment by sincerelysaucy** [comment]
Thank you for clarifying that. Performing 'npm ci' in the root directory, rather than locally, does seem to address the 'patch-package' issue.

I'll note that I strongly dislike the mono repository setup. The git repo has become far too large with the bulky history of so many different pieces, and the ".git" directory alone takes up 845 MBytes on RHEL 8. That's not merely unwieldy, it causes timeouts when downloading git clones and can overwhelm the space and bandwidth resources for distributed builds when building new build environments.

The build on RHEL 8 with modest resources not only requires more RAM. It requires the increased "export NODE_OPTIONS=--max-old-space-size=4096" to overrule the default run-time settings for NodeJS, which are set based on available RAM, not RAM including swap space. Not all of us can afford quite as large of cloud-based ephemeral VMs for our build environments, this is a way to support smaller such environments.  Some of us have hard-coded limits in maximum VM size we can deploy and need to work within that. It would be *very* helpful to such people to mention the approximate size of the VM needed more explicitly, or include this note to work around that limit.

Thank you for that kind of documentation help.

**Comment by Hinton** [comment]
We currently don't have any plans to abandon the monorepository since our workflows are optimized for efficiency over repository size.

Closing this since the problem was resolved.
