### ISSUE TITLE
Bug - Bitwarden extension errors with Bootstrap

### ISSUE THREAD

**Issue by dinbtechit** [bitwarden/clients#8168]
### Steps To Reproduce

1. create a simple website with bootstrap or go to https://formio.github.io/angular-demo/#/forms/builder
2. make sure you have bitwarden extension installed on your browser
3. Perform an operation on the site.

https://github.com/bitwarden/clients/assets/17984781/670876e6-dd7e-4fb1-8b5e-e3961115200b

4. Following error appears on the console:
![image](https://github.com/bitwarden/clients/assets/17984781/24c07e84-17df-4276-a72e-d70665623923)
5. Disable bitwarden extension - the error will go away.

### Expected Result

There should be no errors in the console

### Actual Result

Displays this error

![image](https://github.com/bitwarden/clients/assets/17984781/bafdb3fb-9cb8-42dd-8690-2043f34276b4)

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

Version 122.0.6261.94 (Official Build) (arm64)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment]
@dinbtechit 

Thank you for the report, we'll get a fix in for this and link the changes to this PR.

**Comment by cagonzalezcs** [comment]
While replication of this is easy to do, the actual reason for why this triggers an error is a bit weird. We're essentially referencing an injection DOM element that was somehow injected outside of the rest of the DOM structure (at a top level). 

Creating a Jest test to verify this is kind of a challenge, as a result.... regardless [a fix for this is now in review](https://github.com/bitwarden/clients/pull/8169). Closing this tread.
