### ISSUE TITLE
Fingerprint Phrase Mismatch Between Web Browser Extension and Mobile

### ISSUE THREAD

**Issue by YTKme** [bitwarden/clients#8171]
### Steps To Reproduce

I am getting a mismatch Fingerprint Phrase when authenticating with mobile device:

Some information:
* Windows 11 22H2, 22621.3155
* Brave Browser: v1.63.165
* Firefox Browser: 123.0
* Extension: 2024.2.0, Server: 2024.2.2
* Phone: iPhone 13, iOS 17.3.1
* App: Version 2024.2.0 (6100)

1. Launch browser and try logging in to Bitwarden extension.
2. Click "Log in with device"
3. Unlocked Bitwarden on mobile device, got notification for device login
4. Check "Fingerprint phrase" and they are not the same (though I can tell it is coming from the current IP I have)

### Expected Result

Fingerprint Phrase match between Browser Extension and Mobile App

### Actual Result

Fingerprint Phrase does not match between Browser Extension and Mobile App

### Screenshots or Videos

![firefox-extension](https://github.com/bitwarden/clients/assets/3649725/e7e45c2b-6a76-42a9-a002-90c3ddaf279a)
![ios-app](https://github.com/bitwarden/clients/assets/3649725/b6f1c89e-924a-4e7e-85b1-49c67eabb092)

### Operating System

Windows

### Operating System Version

Windows 11 22H2, 22621.3155

### Web Browser

Firefox, Brave

### Browser Version

Brave Browser: v1.63.165, Firefox Browser: 123.0

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
@YTKme thank you for the report!

Could you check to see if the casing of the email address you entered during the Log In with Device process matches the casing of the email address that you have on your account?  The email is used to generate your fingerprint and a different casing would cause this behavior.  We have identified this as a problem and are working on a fix, so it would be helpful to know if this is the same issue here.

Thank you!

**Comment by YTKme** [comment]
> @YTKme thank you for the report!
> 
> Could you check to see if the casing of the email address you entered during the Log In with Device process matches the casing of the email address that you have on your account? The email is used to generate your fingerprint and a different casing would cause this behavior. We have identified this as a problem and are working on a fix, so it would be helpful to know if this is the same issue here.
> 
> Thank you!

Ah @trmartin4, you are correct, the casing is different. I tend to type my email with different casing, but i think Bitwarden changes everything to lower case.

I tried matching the case of the email and the Fingerprint Phrase seem to match now.

But I guess I would argue that email shouldn't be case sensitive?
