### ISSUE TITLE
Vault Export in Tools or Settings

### ISSUE THREAD

**Issue by markdp123** [bitwarden/clients#8174]
### Steps To Reproduce

In the main / individual vault:

1. Go to Tools
2. Click on Export Vault to do so.  
3. Click on Organizations 
4. Go to Tools again (to export) and it takes you back to Main Vault. 
5. go back to Organizations again
6. Click on Settings tab - oddly enough this is where the Export is for Organizations. 

### Expected Result

For both an individual vault, and organization vault, I would expect to find Export under Tools. 

Not under Settings tab, and not in different tabs and menus for either vault.  

Not when Tools is till an top menu item that will mislead the user.  

### Actual Result

When exporting an individual vault, you find the Export button under Tools. 
When exporting an organization vault, you find the Export button under Settings - even though Tools is still a menu at top of page.  

That Tools menu will always take you to the individual vault export, even from the Organizations page.  

### Screenshots or Videos

<img width="598" alt="BW_Main" src="https://github.com/bitwarden/clients/assets/34987411/ead83d39-c075-4e09-83d9-e8310dc878dc">
<img width="583" alt="BW_Org" src="https://github.com/bitwarden/clients/assets/34987411/1ceabbbe-d253-4d6d-ba93-15ebaf8a0fb2">

### Additional Context

The UI is inconsistent and counterintuitive in its tab and menu labels, depending on whether you're in the main vault or organization vault. 

### Operating System

macOS

### Operating System Version

13.6.4

### Web Browser

Safari

### Browser Version

17.3.1

### Build Version

18617.2.4.11.12, 18617

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!

**Comment by djsmith85** [comment]
Hi @markdp123, 

Within the next release there is going to be some changes to the layout of the vault. It doesn't quite address your request, but there will be a better distinction between Password Manger (Vault) and Admin Console (Org settings).

A preview can be seen here: https://github.com/bitwarden/clients/pull/6957

Kind regards,
Daniel

**Comment by markdp123** [comment]
I didn't think this fell under "feature request" unless an obvious UI inconsistency in the Export tool is considered a feature. 

It's also not so much a distinction between main vault and organizations - as that is quite clear right now. 

It's that the path to export is completely different and lacks the same logic when used under main vault vs org. 

The Bitwarden Reddit seemed to have knowledgeable moderators & Bitwarden gurus in agreement on this and suggested I post it to GitHub.  Clearly that wasn't as helpful as I would have hoped it was to any efforts Bitwarden has to improving UX. 

All good here, I'm still a fan. 

Cheers,
Mark Doering-Powell
