### ISSUE TITLE
AWS and Amazon root account logins are considered the same

### ISSUE THREAD

**Issue by nch0w** [bitwarden/clients#819]
I understand that the Bitwarden browser extension uses the highest level domain name to differentiate logins. For example, logins to abc.example.com, xyz.ijk.example.com, and www.example.com will all be considered as logins to example.com.

Would it be possible to differentiate between logins to signin.aws.amazon.com (AWS) and amazon.com (Amazon)? I have to constantly switch between the two and as they are considered the same category, Autofill fills in the site I used last, which is not always the login I intend to use.

**Comment by kspearrin** [comment]
This should help

https://help.bitwarden.com/article/uri-match-detection/
