### ISSUE TITLE
Loading circle on startup

### ISSUE THREAD

**Issue by DDavid5** [bitwarden/clients#8201]
### Steps To Reproduce

After I start Bitwarden, there is loading circle. Im not able to login/out. I can only see Help 

### Expected Result

Should normaly open and should be able to see my login page/eventualy my passwords

### Actual Result

Loading circle, Im not able to logout, switch account, nothing. Im using latest version

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/104031136/0c001a89-9083-4e33-a449-9410ddece38f)
version. 

### Operating System

Windows

### Operating System Version

Windows 11 Pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.2.0 Shell 28.1.3 Renderer 120.0.6099.199 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by itzallan** [comment]
I'm getting the exact same problem where the app gets stuck at the loading wheel. It starting happening when I upgraded to the latest current version this evening. The Bitwarden browser extension still works properly. It's only the Bitwarden Windows Desktop app that has the problem.

**Comment by DDavid5** [comment]
Yes same trouble, browser extension works well, problem is only on desktop app

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by DDavid5** [comment]
It is possible to somehow check the logs of application?

**Comment by SvenSchneiderDVAG** [comment]
Had the same issue - couldn't but could'nt fix it as @itzallan described. I've been ending up deinstalling the app and re-installing it from Microsoft Store. It works again.

**Comment by TheQuos** [comment]
I encountered the same issue on Linux, 'fixed it' by purging the config. In my case it started when I was switching (kinda rapidly) between accounts. Maybe it has something to do with it, since there are other bugs related to switching?

**Comment by MGCommander** [comment]
![Screenshot 2024-03-11 122739](https://github.com/bitwarden/clients/assets/101991319/5726a991-41a2-4c46-b759-841c8a598c90)

Same problem for me.

**Comment by MGCommander** [comment]
![Screenshot 2024-03-17 142340](https://github.com/bitwarden/clients/assets/101991319/03de35de-e08e-4215-b840-3291bcaa52e2)
 Same Problem for me.

**Comment by AndrewZamora** [comment]
This solution worked for me https://github.com/bitwarden/clients/issues/8651#issuecomment-2047961821

**Comment by DDavid5** [comment]
Thx but I
