### ISSUE TITLE
Native client: OSX: TypeError: Cannot read properties of undefined (reading 'keys')

### ISSUE THREAD

**Issue by notjames** [bitwarden/clients#8208]
### Steps To Reproduce

1. Open the application

I get a blank screen with the spinning gif

Developer tools shows the following:
```
error_handler.ts:45 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'keys')
TypeError: Cannot read properties of undefined (reading 'keys')
    at useClass.<anonymous> (state.service.ts:629:13)
    at Generator.next (<anonymous>)
    at o (main.js:1:339986)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:10:230800)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
```

### Expected Result

a properly working application

### Actual Result

blank screen with spinning gif

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/77161/d0d81d31-e91a-49f4-b3b1-b73297168096)

### Additional Context

when I first installed this application it worked for a good while. Starting recently, it just started doing this.

### Operating System

macOS

### Operating System Version

14.3.1 (23D60)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

20587

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @notjames 

Thanks for reaching out. 
I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in cached info being loaded.

Could you run this command using your terminal - 
rm -r ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/*
​Following that, please re-launch Bitwarden again and let me know if you can get signed in as expected!

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 
The issue here will be closed.

Thanks!

**Comment by notjames** [comment]
> rm -r ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/*

@daniellbw 
The above-referenced path does not exist on my machine. This is what I have:

```
at 18:21:53 ❯ rm -r ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/*
rm: /Users/jimconner/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden/*: No such file or directory

at 10:19:24 ❯ rm -r ~Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/*
rm: ~Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden/*: No such file or directory

at 10:19:35 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden
lsd: /Users/jimconner/Library/Containers/com.bitwarden.desktop/Data/Library/Application Support/Bitwarden: No such file or directory (os error 2).


at 10:19:45 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop/Data/Library
lsd: /Users/jimconner/Library/Containers/com.bitwarden.desktop/Data/Library: No such file or directory (os error 2).


at 10:19:47 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop/Data
lsd: /Users/jimconner/Library/Containers/com.bitwarden.desktop/Data: No such file or directory (os error 2).


at 10:19:50 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop.safari/
.com.apple.containermanagerd.metadata.plist  Data/

at 10:19:50 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop.safari/
.com.apple.containermanagerd.metadata.plist  Data/

at 10:19:50 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop.safari/Data/
.CFUserTextEncoding  Documents/           Library/             Music/               SystemData/
Desktop/             Downloads/           Movies/              Pictures/            tmp/

at 10:19:50 ❯ ls -ltr ~/Library/Containers/com.bitwarden.desktop.safari/Data/Library/Application\ Support/
AddressBook/  SyncServices  iCloud/
```

I have no idea what I should delete. The directories in the path you specified do not seem appropriate to contain anything related to cache.
