### ISSUE TITLE
Password copy button not working on Flatpack Desktop client

### ISSUE THREAD

**Issue by metius** [bitwarden/clients#8233]
### Steps To Reproduce

1. Go to an entry
2. Click on 'copy button next to password field

Password is not copy.
To get the password, it is necessary to click on the "Toggle visibility" button, manually select the password and copy it.

### Expected Result

Password to be copied when clicked on the copy button.

### Actual Result

Password is not copied.
To get the password, it is necessary to click on the "Toggle visibility" button, manually select the password and copy it.

### Operating System

Linux

### Installation method

Other

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

The FlatPak version of Bitwarden is community-managed and is not officially supported by Bitwarden.

The issue here will be closed.

Thank you.
