### ISSUE TITLE
The self hosted address in the top right corner of the app is the last used one and not the one associated to the account

### ISSUE THREAD

**Issue by farfalk** [bitwarden/clients#8237]
### Steps To Reproduce

1. Add a new account (**ACC1** from now on)
2. Set a self-hosted server
3. Succesfully login -> **ACC1** is shown correctly on the top right corner with the correct email address and self-hosted url
4. Add another new account (**ACC2** from now on), on A DIFFERENT self-hosted server
5. Succesfully login -> **ACC2** is shown correctly on the top right corner with the right email address and the right self-hosted url
6. In the dropdown selector, the previously added account **ACC1** is correctly shown, with the correct email address and self-hosted url
7. select the **ACC1** from the drop down, and ..... (go to expected results)

### Expected Result

The expected result is that the now selected **ACC1** gets displayed correctly in the top right corner, with the correct email address and its specific self-hosted address

### Actual Result

The actual result is that the selected account **ACC1** is displayed with the correct email ***BUT the self-hosted address is the one associated with ACC2!***
I made some attempts and it's just a UI mistake, the servers are not functionally mixed up.
The UI mistake doesn't happen in the dropdown menu.

### Screenshots or Videos

I'm sorry, I can't post the images because both the account email and the self-hosted address are sensible info.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Microsoft Store

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by peacepenguin** [comment]
This issue started occurring for me recently too. Right after i updated after putting off updates for awhile.
