### ISSUE TITLE
osx bitwarden client stuck at spinning circles logo

### ISSUE THREAD

**Issue by chmorgan** [bitwarden/clients#8256]
### Steps To Reproduce

1. Start 'bitwarden' client
2. Spinning wheel logo continues without interruption

### Expected Result

GUI would load up correctly?

### Actual Result

Hang at spinning wheel.

### Operating System

macOS

### Operating System Version

14.4

### Installation method

Mac App Store

### Build Version

Version 2024.2.0 (20587)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment]
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6691. 

can you please open a Terminal window, then paste the command below into it and press Enter.

rm -r ~/Library/Containers/com.bitwarden.desktop/Data/Library/Application\ Support/Bitwarden/*

​Following that, please re-launch Bitwarden

This issue will now be closed.

Thanks!

**Comment by chmorgan** [comment]
@bjacksonbit this resolved the issue, thanks!
