### ISSUE TITLE
2024.2.1-x86_64.AppImage and 2024.2.1-amd64.deb do not run on debian bullseye

### ISSUE THREAD

**Issue by DeadliestCache** [bitwarden/clients#8266]
### Steps To Reproduce

1. Install 2024.2.1-amd64.deb, 2024.2.1-x86_64.AppImage, or let 2024.2.0-x86_64.AppImage autoupdate to 2024.2.1
2. Try to run them

### Expected Result

App should run

### Actual Result

App does not run

### Additional Context

2024.2.0-amd64.deb works as expected

### Operating System

Linux

### Operating System Version

Debian bullseye

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!
