### ISSUE TITLE
Unlock with PIN code not working in Linux Desktop version

### ISSUE THREAD

**Issue by whilcayangyang** [bitwarden/clients#8270]
### Steps To Reproduce

1. Open Bitwarden Desktop App and go to setting
2. Check "Unlock with PIN code"

### Expected Result

Another window should pop-up to set your PIN code

### Actual Result

It's not working. Nothing happened when checking the setting.

### Operating System

Linux

### Operating System Version

Debian 12

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by whilcayangyang** [comment]
A temporary fix is to downgrade to 2024.2.0, set your PIN code then upgrade to 2024.2.1. The issue happened on fresh installed package.

**Comment by whilcayangyang** [comment]
2024.2.3 the issue not fix. When I click to check the "Unlock with PIN" still nothing happened.

**Comment by threadcraft** [comment]
I'm on 2024.3.0 appimage version, "Unlock with PIN" does nothing and changing the "Vault Timeout" does nothing. 

Version 2024.3.0
Shell 28.2.4
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

**Comment by whilcayangyang** [comment]
Correct. Both .deb and appimage have the same problem.

**Comment by badbadbee** [comment]
Same issue still happening in version 2024.3.0, tried fresh install with both Flatpak and Snap.

**Comment by TheQuos** [comment]
Vault timeout action also cannot be changed. "Approve login requests" seems to be the only _working_ security setting in 2024.3.0.

**Comment by RainShinotsu** [comment]
Having this issue too.

Version 2024.3.0
Shell 28.2.7
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

OS: EndeavourOS; Installation method: `pacman` from Arch Linux repositories

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you, @whilcayangyang, for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If anyone wishes to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.


Thank you all,
