### ISSUE TITLE
Version 2024.2.1 of the Bitwarden browser extension deactivates the (Copy TOTP automatically) function.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#8277]
### Steps To Reproduce

1. Install version 2024.2.0 of the Bitwarden browser extension in Chrome.
2. Log in and confirm that (Copy TOTP automatically) is activated, under Settings > Options.
3. Update the extension to version 2024.2.1
4. Check if (Copy TOTP automatically) is still activated.

### Expected Result

The (Copy TOTP automatically) function should still be activated.

### Actual Result

The (Copy TOTP automatically) function is deactivated.

### Screenshots or Videos

N/A

### Additional Context

N/A

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Chrome

### Browser Version

122.0

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by abysso2** [comment]
+1

**Comment by damonbrangers** [comment]
Seeing this behavior with this 2024.2.1 in Chrome (122.0.6261.112) as well. Incidentally, not sure if it's related or not but have also had the extension auto-copy different verification codes (which don't work, but could be a timing issue), or copy different strings entirely (most commonly seeing 'Verifi'...).

**Comment by DouglasAR01** [comment]
It happens on Edge 122.0.2365.80. I guess it's related to all Chromium based browsers.

**Comment by DJAlPee** [comment]
Had this issue with FireFox 123.0.1 on MacOS

**Comment by ctastad** [comment]
+1 in Firefox 115.8.0esr on Debian 12

**Comment by rneighbors-syn** [comment]
For me, BW version 2024.2.1 in MS Edge, this only happens when using the in-field fill box.  TOTP copies just fine when using the toolbar button to fill fields.
