### ISSUE TITLE
Not able to close Bitwarden (MacOS)

### ISSUE THREAD

**Issue by glomme** [bitwarden/clients#8292]
### Steps To Reproduce

1. Open Bitwarden
2. Try to close Bitwarden 
3. Make right mouse click on Bitwarden and say "close"

2+3 are not working only if you close it over the task manager

If you shutdown your computer the process will be interrupted because MacOS tells me that Bitwarden interrupted the shutdown process.

### Expected Result

Close Bitwarden. 

### Actual Result

It stay open and must be closed by task manager

### Screenshots or Videos

[2024-03-11_17-25-14.webm](https://github.com/bitwarden/clients/assets/39823647/1123f90c-66e3-4072-b2bf-2d5d465a5c2a)

### Operating System

macOS

### Operating System Version

14.4

### Installation method

Direct Download (from bitwarden.com)

### Build Version

21689

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by RemcodM** [comment]
I just experienced exact the same issue, also macOS 14.4.

**Comment by kotaromiyasaka** [comment]
I'm on madOS 12.7.4 and have the same problem - every time I turn off the mac I have to exit Bitwarden from the menu bar.
Awaiting a prompt update.

**Comment by jdferron** [comment]
Same here on MacOS 14.4.  This also impacts the App Store as it is unable to update the desktop app to a newer version.   The only way to update the app is to force kill the Bitwarden process via Activity Monitor, update the app, then re-start the app.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. For those of you that are using macOS 14, could you please test version 2024.3.0 from the Mac App Store and let me know how it goes?


Thank you in advance,

**Comment by glomme** [comment]
> Hello everyone,
> 
> Thank you all for your input. For those of you that are using macOS 14, could you please test version 2024.3.0 from the Mac App Store and let me know how it goes?

Sorry to disappoint you, here already is installed 2024.3.0 out of the AppStore and still have the same issue. Doesn't matter if you login or not, the only way to quit Bitwarden is to end the task under macOS 14

**Comment by lneyra** [comment]
Experiencing the same issue as well. 
Was hoping that the update Version 2024.3.0 (21897) would fix this issue. 

I've tried uninstalling the app and removing all leftovers as well.
Still experiencing the same issue

**Comment by jdferron** [comment]
> Hello everyone,
> 
> Thank you all for your input. For those of you that are using macOS 14, could you please test version 2024.3.0 from the Mac App Store and let me know how it goes?
> 
> Thank you in advance,

Does not fix the issue.

**Comment by DavidRGrant** [comment]
Experiencing the same issue in Sonoma 14.4 version 23E214

**Comment by alroberts** [comment]
It seems that the "quit" no longer ends the process. Instead, it's necessary to right-click the BitWarden icon in the notification area and select "exit"

![Screenshot 2024-03-19 at 18 12 28](https://github.com/bitwarden/clients/assets/21023684/fdf54994-2760-4181-a7de-739705d465aa)

**Comment by glomme** [comment]
> It seems that the "quit" no longer ends the process. Instead, it's necessary to right-click the BitWarden icon in the notification area and select "exit"

Yes you are right that works beside the task manager.

**Comment by tbrlpld** [comment]
> It seems that the "quit" no longer ends the process. Instead, it's necessary to right-click the BitWarden icon in the notification area and select "exit"
> 
> 
> 
> ![Screenshot 2024-03-19 at 18 12 28](https://github.com/bitwarden/clients/assets/21023684/fdf54994-2760-4181-a7de-739705d465aa)
> 
> 

Just found that today as well 👍

**Comment by akluttz** [comment]
Same here

**Comment by gigacee** [comment]
Same issue, on Sonoma 14.4

**Comment by ispiropoulos** [comment]
Same here, Sonoma 14.4

**Comment by growlocally** [comment]
same here

**Comment by circlesmiler** [comment]
Works for me a little bit better, with following settings:

<img width="443" alt="image" src="https://github.com/bitwarden/clients/assets/22213841/d86abc77-9550-4050-9270-f69aff7320d1">

The problem seems to be that - if you choose to use the tray icon in any way - quitting of the application only works by quitting the tray icon. But if the window is open, quitting only closes the window and activates the tray icon.

On shutdown the system only sends one "quit signal", which results in moving to the tray but did not quit the app.

**Comment by glomme** [comment]
> Works for me a little bit better, with following settings:
> 
> <img alt="image" width="443" src="https://private-user-images.githubusercontent.com/22213841/316772972-d86abc77-9550-4050-9270-f69aff7320d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MTU4MDUsIm5iZiI6MTcxMTYxNTUwNSwicGF0aCI6Ii8yMjIxMzg0MS8zMTY3NzI5NzItZDg2YWJjNzctOTU1MC00MDUwLTkyNzAtZjY5YWZmNzMyMGQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDA4NDUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYWI3ZDYwYzMyNjJiNzc1ZjQwMzk3OGMzMDhkM2ZiNTM5NTc1NTljOGRjMDkzYjgwMGQ2ZDY5YTBiNWM1ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53S_LsdfdA4PypLNrtcNi4qfNKjvGsG9zu8BaagGrDc">
> The problem seems to be that - if you choose to use the tray icon in any way - quitting of the application only works by quitting the tray icon. But if the window is open, quitting only closes the window and activates the tray icon.

Checked my settings, and can not confirm this. The only way right now is to close Bitwarden with a right click at the menu bar or over the task manager. So I hope there is soon a solution for this problem.

**Comment by danieletorelli** [comment]
This is becoming extremely annoying. Like many other people, I have to manually close Bitwarden every day before shutdown, from a month, otherwise shutdown will be prevented.

Can you please make an effort to fix this quickly?

**Comment by alroberts** [comment]
Honestly, this whole previous update has been a pain in the butt. As a paying customer, I would have hoped for more rapid fixes too. I've noticed that fingerprint prompts aren't coming up automatically, TOTP codes are not copied automatically (although sometimes are) and then of course, this issue with the application not being as simple to close.

**Comment by tnorman42** [comment]
Same here Sonoma 14.4.1

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. This matter is being examined internally by the Engineering department; If you wish to add any further information, please feel free to do so at any time - the engineering team will be happy to review that information.

Thank you all in advance for your understanding and patience,

**Comment by schtocker** [comment]
Having the same issue back on Monterey 12.3.1 as well. MacOS fails to shut down citing Bitwarden as refusing to quit. Quitting from the dock doesn't work. Cmd+Shift+Esc to Force Quit doesn't work either. Both methods simply close the window without killing the process.

**Comment by Anilo1990** [comment]
I've the same issue macOS Sonoma 14.4.1 (23E224) and Bitwarden 2024.3.0 (21897). Closing the application with right-click over the Taskbar works without issue.

**Comment by infinitepower18** [comment]
I had to disable the menu bar icon in order to get the app to fully close so it can be updated by the App Store.

<img width="562" alt="Screenshot 2024-04-08 at 9 47 06 PM" src="https://github.com/bitwarden/clients/assets/44692189/c96209ca-d4ed-4634-a135-337a1aa5c598">

**Comment by imyelmo** [comment]
Correct, that behavior is as expected taking into account the bug. The update seems to fix the issue.

**Comment by alroberts** [comment]
The update today from the macOS App Store seems to resolve this issue.

**Comment by toinic1** [comment]
Yes ! The update resolves this problem, thank you !

**Comment by Anilo1990** [comment]
I can confirm that the Update resolved the issue. Thank you very much!

**Comment by glomme** [comment]
It seems the update fix the problem.

**Comment by aeharding** [comment]
I have been stuck on 2024.2.1 from the app store, biometric stopped working, old as hell, no auto update, FINALLY found this issue and clicked exit as per https://github.com/bitwarden/clients/issues/8292#issuecomment-2007596906 and it was able to update! 🤦‍♂️ Bitwarden broke app store update, wonderful.
