### ISSUE TITLE
bw generate ignores the --special option

### ISSUE THREAD

**Issue by neiljackson1984** [bitwarden/clients#8297]
### Steps To Reproduce

Attempt to use the `bw generate` command to generate a password containing no special characters.  Observe that, regardless of the command-line options you give, `bw generate` always seems to include at least one special character in the password that it generates.

### Expected Result

I would expect that, when passed the correct command line options, the `bw generate` command should generate a password that does not contain any special characters.  Specifically, I would expect that either omitting the "--special" option altogether from the command line, or passing some explicitly false variant of the option (perhaps "--no-special" or "--special=0"), would do the trick.

### Actual Result

It seems that every password generated by the `bw generate` command contains at least one special character, regardless of which command line options are given.

In an attempt to generate a password not containing special characters, I have tried the following commands, each of which either generates a password containing special characters or throws an "unknown option" error:
* `bw generate`
* `bw generate --lowercase`
* `bw generate --number`
* `bw generate --no-special`
* `bw generate --special false`
* `bw generate --special=false`
* `bw generate --special:false`
* `bw generate --special 0`
* `bw generate --special=0`
* `bw generate --special:0`

### Operating System

Windows

### Operating System Version

Windows 11

### Shell

PowerShell

### Build Version

2024.2.1

**Comment by djsmith85** [comment]
Hi @neiljackson1984,

Thank you for your report!

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
