### ISSUE TITLE
Error: EIO: i/o error using appimage 2024.02 and later (including latest 2024.03*)

### ISSUE THREAD

**Issue by curiousbarbarian** [bitwarden/clients#8307]
### Steps To Reproduce

1. Open AppImage
2. See error

### Expected Result

No error. Usable app.

### Actual Result

See screenshot.

No matter how many times I click OK, the error window doesn't disappear, interface is unclickable.

### Screenshots or Videos

![bitwarden_appimage_error](https://github.com/bitwarden/clients/assets/163163341/006f4bfc-b3e6-4964-90fb-d6b2075e9886)

See above

### Additional Context

Hello, folks. Found this issue and it was a "surprise" for me.

1. I haven't received messages about updates of appimage version since January until today (I skipped 3? version).
2. Due to the fact that there is no option NOT to upgrade appimage in settings I was forced to upgrade. In case I click "Later" I find that appimage disappears and nothing appears instead (how is it possible?).
3. As far as new versions (2024.2.0+) don't work and previous versions don't load because of auto upgrade function I can't use bitwarden.

I even tried to turn off network not to allow bitwarden start appimage upgrade, but it just leads to eternal loading on start screen with login/password prompt.

I think it's of utmost importance to allow to turn off auto upgrade of appimage and turn this feature off by default.

### Operating System

Linux

### Operating System Version

Slackware 15.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0 and all next releases

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

I think this error may be related to [https://github.com/bitwarden/clients/issues/8257](https://github.com/bitwarden/clients/issues/8257), and if so, it should be resolved with version 2024.3.0. 

If you are still seeing this issue, please leave a comment. Otherwise, this will issue now be closed.
Thanks!
