### ISSUE TITLE
On Add new Item the Collections are not loading

### ISSUE THREAD

**Issue by BetoMees** [bitwarden/clients#8359]
### Steps To Reproduce

Go to a Collections folder and try to add a new item.
The cause for this is in the `add-edit.component.ts` you are calling `super.load()` inside of the `ngOnChanges()` so it execute before the `ngOnInit()` where load the `writeableCollections`

### Expected Result

The expected result would be a list of collections

### Actual Result

The message _**There are no collections to list.**_

![image](https://github.com/bitwarden/clients/assets/15331041/fc29badc-6285-4e73-8c66-f7a22c87db6b)

### Additional Context

You could just remove the `ngOnChanges` and move the code to `ngOnInit`

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @BetoMees,

Thank you for this report. This sounds similar to this [existing report](https://github.com/bitwarden/clients/issues/8258), and thus I will now proceed and close this one as a duplicate.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that existing thread - our engineering team will be happy to review those.

Thank you again,
