### ISSUE TITLE
Switching to an unlocked account logs out of it

### ISSUE THREAD

**Issue by TheQuos** [bitwarden/clients#8361]
### Steps To Reproduce

1. Add a second account
2. Switch back to the first, unlocked one

### Expected Result

Switching without logging out.

### Actual Result

"**Logged out** Your login session has expired." After a moment I'm back in the account I was switching from, and the first one is no longer on the list.

### Additional Context

The app.log shows a wall of `[error] encType unavailable.` with two `[error] Error: Cannot start a HubConnection that is not in the 'Disconnected' state.` below it.
I also experience all the bugs mentioned in issue #8270.

### Operating System

Linux

### Operating System Version

Kubuntu 23.10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0 (AppImage, deb)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @TheQuos,

Thank you for your report. Just to make sure that you and I are on the same page, in your testing, were those two Bitwarden accounts hosted on the same Bitwarden server?

I was able to reproduce this on macOS after logging into a self-hosted Bitwarden account and then attempting to switch back to a cloud-hosted Bitwarden account; With two cloud-hosted Bitwarden accounts, the account switcher functioned as expected.


Thank you in advance,

**Comment by appcoders** [comment]
The same issue occurs when you switch between different self-hosted servers.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you. This has been highlighted internally to the Engineering department.


Thank you again,

**Comment by trmartin4** [comment]
This has been fixed with #8040 and will be included in the next release of the desktop application.
