### ISSUE TITLE
Secure Storage is not saving the accessToken correctly due to its length

### ISSUE THREAD

**Issue by BetoMees** [bitwarden/clients#8363]
### Steps To Reproduce

After the [last](https://github.com/bitwarden/clients/commit/ca8628880bf674fc24a6263c7f557cfceb1a7e2b) commit I was unable to log in to the application as discussed [here](https://github.com/bitwarden/clients/pull/8356#issuecomment-2002288384)](https://github.com/bitwarden/clients/pull/8356#issuecomment-2002288384)

### Expected Result

The accessToken should be saved into the Windows Credentials

### Actual Result

The refreshToken will be saved but not the accessToken

### Additional Context

Due to the conversion of the accessToken to U16CString the CredentialBlob the length becomes to high throwing an exception on CredWriteW

### Operating System

Windows

### Installation method

Other

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @BetoMees,

Thank you for your report. This has been highlighted internally to the Engineering department. If you have more information that can help us, please feel free to add it below.


Thank you again,
