### ISSUE TITLE
libatk-1.0.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by jmswick** [bitwarden/clients#8452]
### Steps To Reproduce

Attempt to launch the bitwarden desktop client

### Expected Result

Client should launch normally

### Actual Result

Client does not launch, and if attempted to launch from a terminal returns the following error:
```
/snap/bitwarden/106/bitwarden: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
```

### Additional Context

```
$ snap list bitwarden
Name       Version   Rev  Tracking       Publisher   Notes
bitwarden  2024.3.0  106  latest/stable  bitwarden✓  -
```

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Installation method

Snap

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @jmswick,

Thank you for reporting this. I tested this using a fresh installation of Ubuntu 2023.10 with Bitwarden (Snap) 2024.3.0, and was able to launch that desktop Bitwarden client as expected. It sounds like a certain [library](https://docs.oracle.com/cd/E88353_01/html/E37842/libatk-1-0-3lib.html) is missing from that machine; Do you recall removing anything like that? This [third-party guide](https://www.masmasit.com/2021/08/how-to-install-package-libatk-10so0-on_01058658241.html) may help address this in your environment.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by jmswick** [comment]
Completely removing the Bitwarden snap and reinstalling it resolved the issue.  I was not missing the `libatk1.0-0` package.
