### ISSUE TITLE
Browser plugin flickers with the TOTP animation.

### ISSUE THREAD

**Issue by sumohax0r** [bitwarden/clients#8455]
### Steps To Reproduce

1. Go to 'Bitwarden Chrome Extension'
2. Click on 'Any Section of Extension'
3. Be signed into an bitwarden account that has TOTP active on at least 1 saved account in vault.
4. Entire Extension will flicker at same pace / style as TOTP entry

The example I gave here is my personal account which does not have TOTP support, however I'm signed into two profiles, whereas the business does have TOTP support with multiple accounts having that filed filled out.

This bug happened before the Extension supported dual accounts, if I went to my personal account without TOTP saved logins it would not happen, when I logged into business account with them it would show this flicker, the CSS/JS animation is attaching itself to the entire body of the Extension or something.

### Expected Result

No background flicker outside of the TOTP field in a saved entry.

### Actual Result

Entire Extension flickers if there is a single TOTP entry in your vault.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/2405995/67c3b6f4-0edf-475a-b2ab-a5bd8dd51343

### Operating System

Windows, macOS

### Operating System Version

14.4 (23E214)

### Web Browser

Chrome

### Browser Version

123

### Build Version

123.0.6312.59

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @sumohax0r,

Thank you for reporting this. I tested this on macOS 14.4 with Chrome 123 and Bitwarden extension 2024.2.1, after adding a vault item with a TOTP value, and did not encounter that flicker in any of the 4 themes, including when the entire operating system was set to Dark. I would recommend that you consider uninstalling that Chrome extension, rebooting the machine, and installing it anew; If this continues, you can test this in a fresh new Chrome Profile to see it's related to any other browser settings and/or browser extensions.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub issues to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
