### ISSUE TITLE
Passkey window opens in weird places

### ISSUE THREAD

**Issue by Ectalite** [bitwarden/clients#8462]
### Steps To Reproduce

1. Go to x website which uses a passkey
2. Login with passkey
3. Passkey opens in the middle of the two screens and at the top, or sometimes appears off-screen.

### Expected Result

Passkey window should appear in a clickable place, middle of the screen for example.

### Actual Result

Passkey window appears off-screen sometimes so I can't click on it, or appears in the middle top of my two screens.

### Screenshots or Videos

![Screenshot 2024-03-25 093907](https://github.com/bitwarden/clients/assets/31344054/8823a115-9cf8-4ccb-84f1-5f85a5f93104)

### Operating System

Windows

### Operating System Version

Windows 10 22H2 19045

### Web Browser

Firefox

### Browser Version

115.9.1 ESR

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @Ectalite 

I attempted to reproduce this issue and was unable to do so.

What you are describing is the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

**Comment by Ectalite** [comment]
For me it's clearly a bug if the window is offscreen and can't even click on it on to confirm.

**Comment by Adagis-MC** [comment]
I'm sorry, but how can this be intended behaviour? I have the same issue where the Passkey window opens halfway off my second monitor and I have to right-click on the task bar to manually move it before I can use the screen. This is a defect (and I am a Test Manager).

**Comment by Ectalite** [comment]
I opened a [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1901199) on the firefox bug tracker.
I also found out that if you set the dpi of all screens in the windows settings to 100%, it will then open properly.
