### ISSUE TITLE
CLI crashes on any command

### ISSUE THREAD

**Issue by LandazuriPaul** [bitwarden/clients#8506]
### Steps To Reproduce

1. Install bitwarden-cli from Homebrew: `brew install bitwarden-cli`
2. Run any command: `bw login`
3. The CLI crashes

### Expected Result

The normal behaviour of the CLI (login, sync, etc.)

### Actual Result

This is the error I get, whatever the command I run:

```
/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:18708
        const toStore = structuredClone(obj);
                        ^

ReferenceError: structuredClone is not defined
    at MemoryStorageService.save (/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:18708:25)
    at StateService.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:24046:45)
    at Generator.next (<anonymous>)
    at /opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:21988:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:21984:12)
    at StateService.setState (/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:24045:16)
    at StateService.<anonymous> (/opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:22071:32)
    at Generator.next (<anonymous>)
    at /opt/homebrew/Cellar/bitwarden-cli/2024.2.1/libexec/lib/node_modules/@bitwarden/cli/build/bw.js:21988:71
```

### Additional Context

I tried removing the package (`brew remove bitwarden-cli`) and reinstalling it. I restarted my laptop many times. To no avail.

Happy to try other things if this is something due to my local setup. But so far I can't think of anything obvious.

### Operating System

macOS

### Operating System Version

14.3.1

### Shell

Zsh

### Build Version

I can't run this command as explained above but from the Homebrew path, it looks like it's `2024.2.1`

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by alessandrolandi** [comment]
Are you using an arm based mac? If so, I'd suggest downloading the CLI using npm (it works for me). There are more instructions in the documentation seen here https://bitwarden.com/help/cli/#tab-npm-bI3gMs3A3z4pl0fwvRie9.

**Comment by LandazuriPaul** [comment]
Thank you for the response @alessandrolandi. I'm indeed using an arm64 mac.

But so far it's never been an issue, neither with the bitwarden-cli, nor any other package which is released in multiple architectures.

When installing bitwarden-cli with Homebrew, it downloads the arm version. Below are the logs of the installation from Homebrew:

```
brew install bitwarden-cli                                                                                                                                                                             ✔
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################### 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################### 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/bitwarden-cli/manifests/2024.2.1
############################################################################################################################################################################################################### 100.0%
==> Fetching bitwarden-cli
==> Downloading https://ghcr.io/v2/homebrew/core/bitwarden-cli/blobs/sha256:ebe7b536c3d150b2a7ea2bec82e4810bccfec95674789f4c7e4d7ccca8e8d7b2
############################################################################################################################################################################################################### 100.0%
==> Pouring bitwarden-cli--2024.2.1.arm64_sonoma.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Summary
🍺  /opt/homebrew/Cellar/bitwarden-cli/2024.2.1: 8,203 files, 45.9MB
==> Running `brew cleanup bitwarden-cli`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

So it seems fine finding the arm64 version.

**Comment by alessandrolandi** [comment]
Hey,

I removed my npm install and followed the homebrew install to reproduce the problem. The homebrew install of the bitwarden cli works on my setup (macOS, arm64). It seems to me like it's more of a local setup issue--although I'm not sure what it could be.

**Comment by LandazuriPaul** [comment]
Oh ok, thank you very much for the reproduction and response @alessandrolandi!

Interesting to know it has to do with my local setup. I'll try to understand where it's coming from. I'll post any update here. For now it's still broken on my laptop. 😶

**Comment by avishefi** [comment]
Check your node version, it should be v18.18.0+

**Comment by LandazuriPaul** [comment]
Oh great, indeed, that was it! I was using v.16.14.0. Using the latest v18, it's all working fine.

Thank you very much @avishefi!

Closing the issue as reolved.
