### ISSUE TITLE
Desktop app cannot properly close connection during account switch when multiple accounts are unlocked

### ISSUE THREAD

**Issue by xJayMorex** [bitwarden/clients#8547]
### Steps To Reproduce

1. Unlock account A
2. Unlock account B
3. Return to account A
4. (optional) swap between the two unlocked accounts until the issue arises

### Expected Result

When switching to account A, the desktop app should close the connection to account B reliably.

### Actual Result

Upon returning to account A, the desktop app tries to close the HTTP connection to account B but sends the wrong token (it probably sends the one which belongs to account A). This process fails (as it should, if an invalid token was provided) and the connection stays live between the desktop app and both account A and account B.

From this point onwards, the Desktop app seems to communicate with either account A or account B randomly (probably race condition determines). If the connection with the "wrong" account (account B) persists, icons (along with possibly attachments etc) for account A will be requested and received from account B.

The collections are not loading (`[error: cannot decrypt]`) for account A.

The websocket connection with account B on the other hand seems to close successfully despite this issue.

Observations:

1. Possibly sending account A's token to account B seems like a serious security risk (live token leak).
2. Possibly returning the wrong attachments also seems like a moderate security risk (data leakage).
3. Leaking saved sites from account A to account B through `icon_cache` icon files also seems bad (data leakage).

### Screenshots or Videos

Here is a screenshot of the issue. This is account A, but data is loaded from account B.

![image](https://github.com/bitwarden/clients/assets/3513159/5af5c045-170d-4117-904b-4ad2db559fd4)

NOTE: I have swapped all of the icon files to the wordpress icon on my selfhosted Bitwarden instance (account B in my example) to prove my point. None of the sites are actually Wordpress.

### Additional Context

Verzió: 2024.3.0
Shell 28.2.4
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

### Operating System

Windows

### Operating System Version

Windows 11 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by xJayMorex** [comment]
Spam swapping between account A and account B when they are both unlocked might help in reproducing the issue. It seems random.

**Comment by crhiles** [comment]
I believe I experienced this same issue today on the ios app version 2024.4.0.
Account A worked fine but Account B shows up as the screenshot below.  It does not have anywhere close to 665 logins as shown in the screenshot.  The only way to recover was to log out and back in.
![IMG_9784](https://github.com/bitwarden/clients/assets/25908960/e2527394-a0bd-4bba-bb05-75fe5ed78d0d)

**Comment by Greenderella** [comment]
Hi @xJayMorex 

It seems this report is a duplicate of https://github.com/bitwarden/clients/issues/3057, which was recently closed due to a lack of replies. Could you please confirm if you are still able to reproduce this issue using the Desktop client version v2024.6.4?

Thank you!
