### ISSUE TITLE
Folder names are aligned, depending if subfolders are present or not

### ISSUE THREAD

**Issue by probain** [bitwarden/clients#8553]
### Steps To Reproduce

1. Go to Vault
2. Look on the folder tree
3. Notice that Folder names aren't aligned, depending if there are subsequent subfolders in underlying objects.
This makes it quite difficult to quickly look over larger amount of folders, due to uneven visual structures. See screenshot for simple example.

This is present in the Desktop version of the app too.

### Expected Result

Folder names should all start in the same "column". Making it easier to see and look over any sort of structure.
I'm guessing this is due to the icons `>` and the one for a single folder. Have different width. 

### Actual Result

Folder names start unevenly. Making it visually jarring and difficult to quickly look things over. 

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/165313617/9ee12052-ca8c-4514-b22c-a3e1078eb1b0)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.03.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @probain,

Thank you for your report. I see what you mean, and have flagged this internally to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by SamFrank234** [comment]
I believe I have figured this one out. It looks like a simple style fix. Can I open a PR for this?

**Comment by djsmith85** [comment]
Hi @SamFrank234 ,

Thank you for offering your help with this. Feel free to open a Pull Request with your changes and [link to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue).

Please have a look at our [Contribution Guidelines](https://contributing.bitwarden.com/), these will help you with getting your environment set up and offer further information in regards to contributing.

Kind regards,
Daniel
