### ISSUE TITLE
Safari plugin showing all entries in the vault when only one is appropriate for the current URL

### ISSUE THREAD

**Issue by pmhausen** [bitwarden/clients#8635]
### Steps To Reproduce

I activated the Safari plugin on Mac OS 14.4.1. I am trying to get back control of my saved passwords switching from the Mac OS keychain to Bitwarden.

I have at the moment a handful of password entries in my vault.

When I navigate to e.g. gitea.hausen.com I can click on the Bitwarden icon for autofill but I am presented with all entries and I have to manually pick the one applicable. This is going to be a major nuisance once I hit about 100 username/password entries that I currently manage with the Mac OS keychain.

Isn't the "URI 1" entry in the Bitwarden settings supposed to match database records with the website you are currently trying to login to?

Please see screenshot for what I think is a problem.

Thank you,
Patrick

### Expected Result

I'd prefer the plugin to automatically fill in the credentials matching the current URL.

### Actual Result

See screenshot.

### Screenshots or Videos

![Bildschirmfoto 2024-04-06 um 00 07 34](https://github.com/bitwarden/clients/assets/27051716/0f18f0fd-90d9-4f5d-9f57-7d785d543d90)

### Operating System

macOS

### Operating System Version

Mac OS 14.4.1

### Web Browser

Safari

### Browser Version

Safari 17.4.1

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by stefan0xC** [comment]
You can change the default match detection from base to host in your extension.
Cf. https://bitwarden.com/help/uri-match-detection/#default-match-detection

**Comment by pmhausen** [comment]
Insanely great! Thank you so much.

Apple's keychain manages to overwrite two completely unrelated entries whenever I update one of this group of three for whatever reasons. That lead me to looking for alternatives.

**Comment by pmhausen** [comment]
Could someone please change the label from bug to support or what is appropriate. Thanks.
