### ISSUE TITLE
Bitwarden Desktop does not save settings inside "Security" topic on Arch Linux.

### ISSUE THREAD

**Issue by BoxedLight** [bitwarden/clients#8637]
### Steps To Reproduce

1. Open Bitwarden on Arch Linux
2. Change the settings in "Security" like "vault timeout" or "unlock with PIN"
3. Restart Bitwarden
4. The settings have not been saved.

### Expected Result

Bitwarden should save the settings such as the vault timeout or a PIN to unlock.

### Actual Result

Bitwarden fails to save the settings and resets the settings inside "Security"

### Additional Context

It is also worth to note that when ticking "unlock with PIN" Bitwarden fails to prompt the user for setting up a PIN.

### Operating System

Linux

### Operating System Version

OS: Arch Linux x86_64 | Kernel: 6.8.2-arch2-1 | DE: Plasma 6.0.3

### Installation method

Other

### Build Version

Version 2024.3.0 Shell 28.2.10 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @BoxedLight,

Thank you for your report. This sounds like a duplicate of this [one](https://github.com/bitwarden/clients/issues/8270), which should be resolved by [this](https://github.com/bitwarden/clients/pull/8520) in an upcoming release; I will now proceed and close this new GitHub report.

If you have any questions or concerns, please feel free to get in touch with us using the form [here](https://bitwarden.com/help/).

Thank you again,
