### ISSUE TITLE
0x80070057 error when installing/updating Bitwarden via MS Store

### ISSUE THREAD

**Issue by infinitepower18** [bitwarden/clients#8653]
### Steps To Reproduce

Install/update Bitwarden via Microsoft Store

### Expected Result

The app should have installed successfully

### Actual Result

Whenever I try to update Bitwarden it fails with the 0x80070057 error code. Now that I tried uninstalling and reinstalling it, it won't install anymore.

All other apps update fine. Tried wsreset as well.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/44692189/f884ae6c-ed8e-4461-b17a-5ee9a722a878

### Operating System

Windows

### Operating System Version

Windows 11 23H2 22631.3447

### Installation method

Microsoft Store

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by o-l-a-v** [comment]
Some more info that might be relevant:

I used <https://store.rg-adguard.net/> to download the APPX file of v2024.3.2.0 and tried installing it manually. It failed too, but this error message had some more details:

```
App installation failed with error message: 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy : error 0x80070057 : Cannot register the 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy package because the specified resource language 'sr' is not a valid language. (0x80070057)
```

Seems Rufus faced a similar issue in 2022:

* <https://github.com/pbatard/rufus/issues/2015>

**Comment by infinitepower18** [comment]
So it means the MS Store reviewers don’t even test apps. How did this get through the review process?

**Comment by o-l-a-v** [comment]
Here's a list of supported languages:

* <https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/supported-languages#list-of-supported-languages>

`sr` is not there, but `Serbian (Latin) | sr-Latn, sr-latn-cs, sr, sr-latn-ba, sr-latn-me, sr-latn-rs` and `Serbian (Cyrillic) | sr-cyrl, sr-cyrl-ba, sr-cyrl-cs, sr-cyrl-me, sr-cyrl-rs` is.

**Comment by SwissJerry** [comment]
> Some more info that might be relevant:
> 
> I used https://store.rg-adguard.net/ to download the APPX file of v2024.3.2.0 and tried installing it manually. It failed too, but this error message had some more details:
> 
> `App installation failed with error message: 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy : error 0x80070057 : Cannot register the 8bitSolutionsLLC.bitwardendesktop_2024.3.2.0_x64__h4e712dmw3xyy package because the specified resource language 'sr' is not a valid language. (0x80070057)`
> 
> Seems Rufus faced a similar issue in 2022:
> 
>     * [Windows store version install fails with error 0x80070057 pbatard/rufus#2015](https://github.com/pbatard/rufus/issues/2015)
> 
> 
> From there ^ I learned that more details about the error can be found with:
> 
>     * Event Viewer: Applications and Services Logs → Microsoft → Windows → AppXDeployment-Server → Microsoft-Windows-AppXDeploymentServer/Operational
> 
>     * Windows PowerShell -> `Get-AppxLog`

I can confirm this bug: that the specified resource language 'sr' is not a valid language. (0x80070057)

So we have to wait until it's fixed. Thank you o-l-a-v for your input.

**Comment by dani-garcia** [comment]
Hey everyone, thanks for helpful comments and reproduction steps!

I've merged https://github.com/bitwarden/clients/pull/8665 into main now, and we will start the process of making a hotfix release ASAP

In the meantime we can keep this issue open to provide some visibility to other users having this same problem

**Comment by FrayxRulez** [comment]
`sr` is not supported and Partner Center used to reject that with a generic error message a few years ago. You want to replace it with `sr-cyrl`.

**Comment by infinitepower18** [comment]
Seems to be fixed now. Thanks.
