### ISSUE TITLE
Linux (Ubuntu) Desktop client fails to sync

### ISSUE THREAD

**Issue by NominePatris** [bitwarden/clients#8679]
### Steps To Reproduce

1. Login on the desktop client 
2. My vault will not load (continuous loading symbol)
3. Press File->Sync vault
4. ¨Synching failed¨ error message.

### Expected Result

Items in my vault are loaded within a few second. Pressing Sync Vault results in items being loaded without issue.

### Actual Result

The vault will not load and just shows the loading symbol. Pressing sync vault results in an "Synching failed" message to be displayed (without further info as to why it fails).

### Additional Context

I have already reinstalled Bitwarden Client, with the same result. 
I have access to bitwarden through the webbrowser. 

### Operating System

Linux

### Operating System Version

Linux 6.5.0-27-generic(x86_64), Ubuntu 23.10

### Installation method

Snap

### Build Version

2024.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by woshidafengzi** [comment]
my macbookpro  Desktop client fails to sync

**Comment by NominePatris** [comment]
> Duplicate of #8651
This solution works, thank you.

**Comment by woshidafengzi** [comment]
Versione 2024.4.1

**Comment by woshidafengzi** [comment]
bitwarden Versione 2024.4.1

**Comment by woshidafengzi** [comment]
bitwarden Version: 2024.4.1
Operating System : macOs Ventura13.1
It's the same problem
 #8651 insolubility
