### ISSUE TITLE
can not save more than 6 entries inside card section

### ISSUE THREAD

**Issue by masterlf** [bitwarden/clients#8690]
### Steps To Reproduce

1 go to card section in the desktop app
2 create a new entry (already have 6)
3 click save en see the green confirmation
4 see that the entry is not in the list on the card section (search does not find it too)

### Expected Result

I should find a new entry in the search section

### Actual Result

the new entry is confirmed saved but actually does not add up in the list under card section

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.03.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

I was unable to replicate this issue. On my end I was able to add as many cards as I wanted. Would you be able to provide a recording of this behaviour to help me replicate this on my end?
