### ISSUE TITLE
Gigantic white bar appears on Google.com after clicking on a a search result

### ISSUE THREAD

**Issue by julianw10** [bitwarden/clients#8710]
### Steps To Reproduce

1. Use a Chromium based browser (in normal window full screen mode. Let's say Chrome Version 123.0.6312.106)
2. Windows 11 (e.g. 22631.3447)
3. Nvidia or Intel iGPU, doesn't matter
4. Have the Bitwarden extension enabled with 1. autofill when field is in focus and 2. autofill on page load enabled
5. Go to google.com (or any localised version, doesn't matter)
6. Search for anything (e.g. foo)
7. Click on any search result link

### Expected Result

The website you clicked on should load normally, and the google search results should stay visible in entireness until the new website renders. There should be zero render bugs on the old page you just were, which was Google. Especially in dark mode, the old Google page should stay in dark mode without different color render artifacts.

So the workflow should be:
1. Google page 
2. Click on link 
3. Google page is still visible entirely
4. After x seconds the new page loads. And until then, the google page doesn't change looks

### Actual Result

Sometimes, **after** clicking a link, and **before** the website you clicked on loads: **a large white bar will cover some google search results in the middle of the screen** from left to right. This is especially visible in dark mode

(see the attached pictures. Please be aware that the attached pictures show a recreation of the render bug. It doesn't show an actual occurence of the bug. It's merely an illustration. The reason is the bug happens very randomly and is hard to capture. But it happens, and it's quite annoying in dark mode. And it looks exactly like the picture shows)

### Screenshots or Videos

![render bug](https://github.com/bitwarden/clients/assets/35012016/21f176ae-a038-4dee-9d72-14177f46683d)
![render bug dark mode](https://github.com/bitwarden/clients/assets/35012016/6db8211e-8da9-4e7e-a2d7-51782bbc1403)

### Additional Context

I tried different scenarios to narrow the render issue down to Bitwarden and a Chromium browser:

1. Different Chromium browser, with all my extensions (bitwarden, adblock etc.): Issue appears
2. Chrome with only Bitwarden extension: Issue appears
3. Other Chromium browser with only Bitwarden extension: Issue appears
4. Chrome with Bitwarden and a different rendering engine (Opengl, D3D11onD12): Issues still appears
5. Step 4 but with another chromium browser: Issue still appears
6. All from 1-5. Nvidia graphics card: Issue still appears
7. All from 1-5. with Intel iGPU: Issue still appears
8. All from 1-7. with hardware acceleration off: Issue still appears 

9. Any Chromium browser *without* Bitwarden extension and 1.-8. settings above: Issue does not appear
10. Firefox and Bitwarden extension: Issue does not appear

So from my heuristic approach the issue appears in any Chromium browser with the Bitwarden extension enabled, autifill when field is in focus and autofill on page load (I did not try all of the above without autofill settings off since that would have led to even more test cases). My theory is that it has something to do with autofill perhaps interfering with something (?). But this is just a very unfounded theory.

You might wonder why something so specific might be an issue? Who cares about how an old web page behaves? I first noticed in dark mode. Because in dark mode, the Google page is, well, dark. And then when you click on a link sometimes a gigantic white bar appears in the middle of the screen out of nowhere (see attachments). Very annoying.

If you need any further details let me know

### Operating System

Windows

### Operating System Version

22631.3447

### Web Browser

Chrome, Microsoft Edge, Brave, Vivaldi

### Browser Version

Brave: Version 1.64.116 Chromium: 123.0.6312.105 Chrome: Version 123.0.6312.106 Edge: Version 123.0.2420.81 

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I've tried with a pc with a dedicated graphic card and a laptop with an integrated one, and both devices perform as expected while searching on Google, no white bars.

You may want to try uninstalling the application, removing any leftover data, powering off and on your device and re-installing the extension to see if the issue persists. Here is a guide to find the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
