### ISSUE TITLE
Navigation bar not showing up with scaled display

### ISSUE THREAD

**Issue by Arktos-cpu** [bitwarden/clients#8730]
### Steps To Reproduce

1. Set Windows display scaling to 150% (of course i think this value depends on my resolution and display size)
2. Open firefox
3. Unlock bitwarden extension

### Expected Result

<img width="280" alt="Screenshot 2024-04-13 190308" src="https://github.com/bitwarden/clients/assets/53445555/d3b974bc-38ac-4fb7-a139-fd9490edf32f">

### Actual Result

The navigation bar doesn't show up
<img width="284" alt="Screenshot 2024-04-13 190437" src="https://github.com/bitwarden/clients/assets/53445555/dc695b3c-53cb-4015-a748-204ad5ae741b">

### Additional Context

Downgrading the extension to 2024.2.1 version fixes the problem.

### Operating System

Windows

### Operating System Version

22621.3447

### Web Browser

Firefox

### Browser Version

124.0.2

### Build Version

2024.3.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Arktos-cpu,

Thank you for reporting this. I tested this with Firefox 124.0.2 and Bitwarden extension 2024.3.1 on Windows 11 Pro and the top bar of the Bitwarden browser extension remained visible and the search field was accessible; To be clear, I set the scaling to 150% on a 2560*1440 (QHD) monitor. Please check if uninstalling the extension, rebooting the computer, and installing the extension anew helps; Also check if there are any settings within Firefox that affect the size of the extension/text.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
