### ISSUE TITLE
On Browser Restart and System Lock options no longer working in Edge extension

### ISSUE THREAD

**Issue by prohidium** [bitwarden/clients#8744]
### Steps To Reproduce

A couple of days ago, my Bitwarden Edge Extension stopped working with the setting On Browser Restart with the Vault Timeout Security option. It also appears to have stopped working with On System Lock. Edge was recently updated to Version 123.0.2420.81 (Official build) (64-bit) and running on Windows 10 22H2. I uninstalled and reinstalled the extension with no change. I then went to another computer and installed the extension on Edge and it also has the same issue. I tested with Chrome and it does not seem to have this problem and it works as expected. I have reverted to using a timeout lock which is working. This appears to be a bug. FYI, it could be related to Copilot and when I run task manager, there are quite a few Edge instances running in the background even with the browser closed so possibly one of the background edge instances is interfering?? I do believe it is from the recent update to Edge. As it can be reproduced on two different computers running the same versions of Edge, Windows and the BW extension, this appears to be a new bug. FYI I have resorted to using a 15 minute time out Vault Timeout which is working as expected. 

### Expected Result

With the vault timeout setting of On Browser Restart, the extension should be locked. This is the way it has been working for a long period of time. Also, the BW extension should be locked after initiating a System Lock ( lock screen from Win/L )

### Actual Result

Upon closing the browser and relaunching the browser, the BW extension is not locked and is freely accessible. This actually carries through with sleep mode so when the computer is woken up hours later and Edge is launched, the BW extension is still in unlocked mode.

### Additional Context

I believe this started happening for me with the latest Edge update with CoPilot which my computer recently received from Microsoft. My wife's computer received this update a while ago now but she uses Chrome and would not have noticed this if it was occurring with Edge. I installed the BW extension for the first time on Edge on her computer to test the situation so it was a native install. On my computer I did try uninstalling and reinstalling but the issue still remains. I use my computer daily and the option for BW to be locked on browser restart is an important security feature for me. NOTE: I am using a PIN to unlock the extension with the the Master Password requirement unchecked.

### Operating System

Windows

### Operating System Version

Win10 22H2 build 19045.4291

### Web Browser

Microsoft Edge

### Browser Version

Version 123.0.2420.97 (Official build) (64-bit)

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,

This issue appears to be the intended behavior in Edge when the vault timeout is set to "On browser restart". By default, Edge by default is set to remain active in the background: (https://www.microsoft.com/en-us/edge/learning-center/microsoft-edge-running-in-background?form=MA13I2).

For "On system lock" I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

**Comment by artpoli** [comment]
I noticed the same issue in Brave - vault timeout "On browser restart doesn't work".
However, I didn't notice this issue with Chrome, while both have an active option to continue work in the background.
