### ISSUE TITLE
Endless loading spinner

### ISSUE THREAD

**Issue by staroks3** [bitwarden/clients#8753]
### Install Bitwarden

1. Install bitwarden through CLI
2. sudo snap install bitwarden

### My system

1. Description: Ubuntu 22.04.4 LTS (Kubuntu)

### Version Bitwarden installed

- Version 2024.4.0
- Shell 28.2.8
- Renderer 120.0.6099.291
- Node 18.18.2
- Architecture x64

### Change password

The problems started after I changed the password through browser in my bitwarden account. After this I can't save changes or create new cards through application desktop - GUI.

When I tried to do this I received this message:
![1](https://github.com/bitwarden/clients/assets/167122409/64cec600-034d-4183-a62f-37dccc41f444)

### Change KDF

I try to solve the issue following this path: Settings -> Security -> Keys -> "Change KDF"

### Expected Result

Work properly. I can save and edit the data through GUI application - bitwarden.

### Through GUI

When I open the software through icon, introduce the email and password and get the normal GUI but with a endless loading spinner. After I waited five minutes nothing changed.

![2](https://github.com/bitwarden/clients/assets/167122409/277dadba-98b8-49cc-a801-47bd34540705)

### Through terminal

I open the terminal and executed this command:

`bitwarden`

After I introduced email and password (normal procedure with same result mentioned above) I checked the message on terminal and catch this errors messages:

```
Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Error: The name org.freedesktop.secrets was not provided by any .service files

Error: Failed to decode access token: JWT must have 3 parts

Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Error: The name org.freedesktop.secrets was not provided by any .service files

Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Error: The name org.freedesktop.secrets was not provided by any .service files 
```

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS (Kubuntu)

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by christophe-kamphaus-jemmic** [comment]
This is probably related to https://github.com/bitwarden/clients/issues/8722.

I had the same issue. Following the instructions of https://github.com/bitwarden/clients/issues/8722#issuecomment-2053866276 fixed it for me.

**Comment by staroks3** [comment]
> This is probably related to #8722.
> 
> I had the same issue. Following the instructions of [#8722 (comment)](https://github.com/bitwarden/clients/issues/8722#issuecomment-2053866276) fixed it for me.

Thank you for your answer.
However I found this command in this link: https://community.bitwarden.com/t/bitwarden-flatpak-stuck-opening-vault-failed-to-decode-access-token-jwt-must-have-3-parts/65554/5

I followed this path again:

1. sudo snap install bitwarden
2. sudo snap connect bitwarden:password-manager-service

I got the same issue:
![1](https://github.com/bitwarden/clients/assets/167122409/277dadba-98b8-49cc-a801-47bd34540705)

**Comment by uplifted-mauve** [comment]
I'm having the same problem on Windows Desktop app. I initially had the JWT decode error when trying to save an item in my vault. Logged out and logged back in, now facing the endless loading.

**Comment by staroks3** [comment]
What do you think about downgrade the version?

This issue is about a different problem but my doubt is if revert to a previous version is good idea:

`sudo snap revert bitwarden`

https://community.bitwarden.com/t/bitwarden-flatpak-stuck-opening-vault-failed-to-decode-access-token-jwt-must-have-3-parts/65554/5

**Comment by trmartin4** [comment]
Hello!  We are tracking and investigating reports of JWT errors in a few issue already.  In order to direct and consolidate feedback, I would like to close this ticket and direct feedback to these tickets:

- Windows desktop "endless loading" or JWT errors in `2024.4.0` or `2024.4.1` versions
  - https://github.com/bitwarden/clients/issues/8673
- **Non-snap** Linux desktop "endless loading" or JWT errors in `2024.4.0` or `2024.4.1` versions
  - https://github.com/bitwarden/clients/issues/8722
- Snap-related Linux desktop "endless loading" or JWT errors in `2024.4.0` or `2024.4.1` versions
  - https://github.com/bitwarden/clients/issues/8673

**Comment by staroks3** [comment]
Hello,

Sound good for me.
I checked all releases about bitwarden: https://github.com/bitwarden/clients/releases

### Install new release 2024.4.1

I check there is a new versions, released by twelve hours ago `2024.4.1`. I did this:

1. sudo snap remove --purge bitwarden
2. sudo apt-get update
3. sudo snap refresh
4. sudo snap install bitwarden

The version installed was the same `2024.4.0` How can I install the new release `2024.4.1`?

### Install oldest release 2024.3.1

I use this command but without sucess:

1. sudo snap revert bitwarden
2. Output: error: cannot revert "bitwarden": no revision to revert to

I think the reason is because I don't have oldest versions installed on my system.

**Comment by uplifted-mauve** [comment]
@trmartin4 sure here's the info

- Running Windows 10 19045.4291
- Bitwarden version 2024.4.1 obtained via auto-update
- Vault timeout 1_5 minutes_, action _lock_, 
- No PIN or biometric on the Windows desktop app. Only master password and 2FA

Additionally, I tried uninstalling the app and installing 2024.3.0 from github releases. I was able to use my vault again. After getting an auto-update to 2024.4.1 I'm back to the same issue.

The problem begins with a "Failed to decode access token. JWT must have 3 parts" error message when saving an item. When logging out, I can't log back in.

**Comment by uplifted-mauve** [comment]
@trmartin4 I have created a test Bitwarden account and I hit the same bug. I intercepted the GET request on launch, I can share it with you if it can be of any help. There is no personal or confidential data on that test account and I won't mind sharing the details.

**Comment by staroks3** [comment]
The version installed from snap is 2024.4.0 2024-04-11 (108) 97MB 

According to this webpage: https://github.com/bitwarden/clients/releases
The bitwarden already has Desktop v2024.4.1 version.

**My question is**: how can I install this new version on desktop (ubuntu) or how can I install the previous version, like "v2024.3.2"?

Until now I can't handle/solve the issues from desktop version 2024.4.0 on desktop, like I mention on first comment on this thread.

**Comment by staroks3** [comment]
I installed a new version 2024.4.3 2024-05-06 (109) 97MB

### Commands CLI

1. sudo snap install bitwarden
2. sudo snap connect bitwarden:password-manager-service

I opened bitwarden through CLI with command: bitwarden and I got this messages error:

- Error: The name org.freedesktop.secrets was not provided by any .service files
- Error: Failed to decode access token: JWT must have 3 parts

I got the same screen with endless circle loading I reported here: https://github.com/bitwarden/clients/issues/8753#issuecomment-2057643713

What can I do to solve this issue?
Thank you
