### ISSUE TITLE
CLI `bw serve` is killed after few minutes on arm64 

### ISSUE THREAD

**Issue by psalkowski** [bitwarden/clients#8762]
### Steps To Reproduce

I have a Dockerfile that build bitwarden-cli image from NPM and run `bw serve`. I tried to use NodeJS 18.18 with Alpine 3.18 and Alpine 3.19. The bitwarden-cli is used on Kubernetes cluster with have Raspberry PI 4B (arm64) nodes in it.

The `bw serve` works fine, but after about 8-10 minutes it crash all the time. I checked, and there is enough memory. Also I set a hard 2GB memory on containers, to make sure there is no OOM. Anyway, the docker exists with **137 status code**, which is out of memory.

Dockerfile: https://github.com/psalkowski/git-ops/tree/45567796a8557f50ce0060bec4c567b7945a14bb/docker/bitwarden-cli
Deployment: https://github.com/psalkowski/git-ops/blob/45567796a8557f50ce0060bec4c567b7945a14bb/clusters/home/vault/bitwarden-cli/app/deployment.yaml

### Expected Result

The `bw serve` should not crash due to OOM.

### Actual Result

`bw serve` crash after about 8-10 minutes due to OOM

### Screenshots or Videos

Pod memory usage:
![image](https://github.com/bitwarden/clients/assets/1153631/5d2841dc-55ad-4f2b-aad7-52481c4325fe)

Pod CPU usage:
![image](https://github.com/bitwarden/clients/assets/1153631/b6b6332b-69a9-4d2e-b010-e4ed00e900be)

### Operating System

Linux

### Operating System Version

k3s

### Shell

Bash

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by psalkowski** [comment]
Issue was on my side. After few days already I just found, that it livenessProbe with does `sync` via REST API fails after each cycle. After few tries it restarts the pod. I wasn't aware, that such restart will be treated as 137 exit code!

**Comment by luckman212** [comment]
@psalkowski Can I ask what you've done to generate those screenshots? just curious.

**Comment by psalkowski** [comment]
Sure. It's Grafana dashboard for kubernetes

W dniu sob., 11.05.2024 o 21:41 Luke Hamburg ***@***.***>
napisał(a):

**Comment by acolombier** [comment]
Looks like you might have the same issue than me - in this case `127` doesn't mean OOM but it's the error code returned by the JS server when it gets stopped.
It is likely getting stopped after 3 liveness failure due to wget timeout [here](https://github.com/psalkowski/git-ops/blob/45567796a8557f50ce0060bec4c567b7945a14bb/clusters/home/vault/bitwarden-cli/app/deployment.yaml#L48). I suggest a value somewhere between 10 and 20, which should work better.
