### ISSUE TITLE
Bitwardin Firefox extension/addon fill-form doesn't fill forms

### ISSUE THREAD

**Issue by DjKilla2** [bitwarden/clients#8774]
### Steps To Reproduce

1. Go to any website with a form
2. Use Bitwardin extension/addon to fill form

### Expected Result

Previous Bitwardin Firefox extension/addon would fill the form

### Actual Result

Latest Bitwardin extension/addon v2024.3.1 doesn't fill any forms

### Screenshots or Videos

When clicking on any identity, forms do not fill.

![Fill1](https://github.com/bitwarden/clients/assets/107418638/e0af34b3-68b2-499c-a253-57b62caeab23)

When using the right-click menu, identities do fill in forms correctly.

![Fill2](https://github.com/bitwarden/clients/assets/107418638/5389c27d-19f5-4362-b267-f9cf5c197565)

My fill-form settings are always the same with every version.

![Fill3](https://github.com/bitwarden/clients/assets/107418638/0a080db6-df7a-492b-af6b-b4764d81531f)

### Additional Context

The following sites do not fill when clicking any identity in the extension/addon (right-click menu works correctly filling forms):

https://thebeat.us/20240425.html
https://www.ebfamilysweeps.com/contest
https://app.viralsweep.com/sweeps/full/e9538d-156428?framed=1
https://usatoday.gannettcontests.com/2024-Home-and-Garden-Refresh/
https://liquiddeathpromos.com/
https://hp2win.com/the-beast-unleashed-mini-fridge-sweepstakes-beastminifridge-04302024/
https://www.tecatebeerusa.com/beerforayear24
https://sweepstakes.e360.mobi/en/verifyage
https://www.heineken.com/ca/en/agegateway?returnurl=/us/en/promos/beerforayear24

**There's many more website forms. These are just a few for reference.

### Operating System

Windows

### Operating System Version

Windows 10 22H2 (64-bit)

### Web Browser

Firefox

### Browser Version

tested on 124.02 and 125.0

### Build Version

Bitwardin 2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MrDoh** [comment]
Same problem on macOS with Firefox, latest macOS, latest Firefox, latest Bit Warden extension. Autofill into web page login widgets doesn't work. About to leave Bit Warden because of this breakage, hopefully it can be fixed SOON! Tired of having to drop down the Bit Warden extension widget to do manual "autofill". 

Kind of makes me wonder how much these new versions are tested before being deployed. This is basic functionality on both macOS and Windows, how could it be missed? I guess that Firefox has become a niche browser?

**Comment by cagonzalezcs** [comment]
@DjKilla2 

Thank you for this bug report. A fix for this has been implemented and verified by QA. https://github.com/bitwarden/clients/pull/8670

This should be available in the next extension release, for now usage of the right-click context menu autofill of identities and credit cards should function as a workaround.

**Comment by DjKilla2** [comment]
cagonzalezcs - Can you tell me which version this issue will be fixed. Version 2024.4.1 firefox extension/addon just came out today (April 18)  so I updated to this version but just like the last version 2024.3.1, neither have fixed the issue.

**Comment by Tipoff4317** [comment]
@DjKilla2 I am not ca.... It looks like the fix (#8670) didn't get into the 2024.4.1 (see https://github.com/bitwarden/clients/compare/web-v2024.4.0...browser-v2024.4.1 ).  But since he already merged it into main, theoretically it would get into the next release build.

**Comment by DjKilla2** [comment]
Tipoff4317 - Thanks for the reply! At least I know what happened now. I'll keep an eye out for the next version which is probably farther out since they just released version 2024.4.1.
