### ISSUE TITLE
New folder will be created in personal vault

### ISSUE THREAD

**Issue by Basecatcherz** [bitwarden/clients#8798]
### Steps To Reproduce

1. Select a organization vault
2. Click on + next to folders
3. Choose a name and hit save

### Expected Result

The new folder will be created in the selected organization.

### Actual Result

The new folder will be created in the personal vault.

### Operating System

Windows

### Operating System Version

11 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.4.1 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Your issue appears to be describing the intended behaviour of the software.

A folder can only be created in a personal vault(https://bitwarden.com/help/folders/). If you are looking for a way to organise data in your Organization I would recommend looking at collections(https://bitwarden.com/help/about-collections/)

This issue will now be closed. 

Thanks!
