### ISSUE TITLE
Username generator saves wrong website to description

### ISSUE THREAD

**Issue by lynara** [bitwarden/clients#8828]
### Steps To Reproduce

1. Open the Bitwarden extension in Chrome based browser while on the website that you want to generate a username for
2. Click on "Generator" along the bottom
3. Create a forwarded email alias for your custom domain (API access token already applied) by clicking on the "Regenerate Username" icon in the top right
4. Login to your account on e.g. SimpleLogin and check the description for the newly created alias

### Expected Result

If I am on github.com when generating a username, I expect that the description would read "Website: github.com. Generated by Bitwarden." when I check the alias on AnonAddy

### Actual Result

Instead the description reads "Website: some.website.I.visited.a.month.ago.com. Generated by Bitwarden." it is always the same website.

### Additional Context

If I generate a username from the "Tab" menu along the bottom (and have remembered to click refresh in the top-left) then create a new login using the plus icon in the top-right and use the username generator from within that menu, the description is saved correctly. It is only the standalone generator that is giving the wrong description.

See: https://github.com/bitwarden/clients/issues/3199#issuecomment-2032716864

I know this is a duplicate of https://github.com/bitwarden/clients/issues/3199
but this issue was closed a while ago and is still not fixed an no one was willing to reopen it until now.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome, Microsoft Edge, Brave

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by lynara** [comment]
Hi @SergeantConfused,

seems like I missed that bug report.
Looks to me like the one you linked is about the same issue.

**Comment by SergeantConfused** [comment]
Hi @lynara,

Thank you. In this case, I will proceed and close this thread in order to consolidate this matter into that thread; If you wish to add any further information, such as screenshots or video recordings, please feel free to do so at any time in that thread - the Engineering team will be happy to review that additional information.

Thank you again,
