### ISSUE TITLE
export failed when using "Log in with passkey"

### ISSUE THREAD

**Issue by chenn1u** [bitwarden/clients#8846]
### Steps To Reproduce

1. Go to 'https://vault.bitwarden.com/#/login'
2. Click on 'Log in With passkey'
3. Scroll down to 'Tools-Export vault'
4. An error message pops up after entering the password

### Expected Result

Export the file normally after entering the password

### Actual Result

Prompt 'Invalid master password'

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

123.0.6312.124

### Build Version

2024.4.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - the Engineering team will be happy to review them.

Thank you again,

**Comment by pamperer562580892423** [comment]
Well, since it's already "reproduced", it maybe doesn't matter, but I experienced the same problem a few days ago in the web vault (Windows 11, Brave, everything up-to-date).
