### ISSUE TITLE
macOS Client cannot select bitwarden.eu

### ISSUE THREAD

**Issue by flo-f** [bitwarden/clients#8848]
### Steps To Reproduce

1. Start Bitwarden macOS client
2. (optionally) enter Email address
3. At `Logging in on:` click `bitwarden.com` input and select `bitwarden.eu`
4. App reverts to `bitwarden.com`

Side Note: selecting `self-hosted` actually works but `bitwarden.eu` does not seem to have any effect.

### Expected Result

After selecting `bitwarden.eu` the EU platform should be rendered as selected.

### Actual Result

After selecting `bitwarden.eu` the US platform at `bitwarden.com` is still selected.

### Screenshots or Videos

<img width="680" alt="image" src="https://github.com/bitwarden/clients/assets/1405446/7cee2095-9bac-4930-9b6d-94cf54810f2d">

### Additional Context

Maybe related to the outdated macOS version? 
On another computer running macOS Sonoma I cannot reproduce this issue.

### Operating System

macOS

### Operating System Version

Catalina 10.15.7 (19H2026)

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

Version 2024.4.1 (23269)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @flo-f,

Thank you for reporting this. We tested this on macOS 10.15.7 with Bitwarden 2024.4.1 from the Mac App Store, and the server selection persisted as expected. I recommend that you consider uninstalling it, removing any [leftover](https://bitwarden.com/help/data-storage/#on-your-local-machine) data, rebooting the machine, and installing it anew via the Mac App Store.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by zzattack** [comment]
I'm experiencing the exact same issue after updating the client to 2024.4.1 on a Windows desktop. Normally after updates I do not get a prompt to provide login details again, but this time I did. After uninstall + reinstall, issue is resolved.

**Comment by keithnorm** [comment]
This is happening for me on 2024.6.1 and MacOS 12.6.2. Can't select eu or self-hosted, the dropdown selection doesn't take and stays on bitwarden.com. I've uninstalled, restarted, and re-installed to no avail.

**Comment by nicx** [comment]
Any news to this? Any workaround? I have the same error on MacOS. Reinstalling did not help.

**Comment by danielblom** [comment]
Experiencing this issue on macOS 14.6.1 with Bitwarden 2024.8.2. I'm in contact with their helpdesk, whom cannot reproduce the issue with the same version but also aren't able to make any good suggestion to bypass this problem.
