### ISSUE TITLE
Chrome Extension Bug - Missing login field 

### ISSUE THREAD

**Issue by tracer8** [bitwarden/clients#8850]
### Steps To Reproduce

Missing login field after restart browse and require login back

### Expected Result

Login field show up to fill 

### Actual Result

Missing login field 

### Screenshots or Videos

![Screenshot_2024-04-20 18 40 12_001](https://github.com/bitwarden/clients/assets/15725821/ecf3aa9c-d7e9-4257-b5bb-e39973a405c3)

### Additional Context

I logout, then login, it will be back, until i restart the browse, the login field is disappear again.
I did it before, but when logout and login again, it will require 2FA and much more steps to be back on track.
But i think this is not the “fix” , just work around. That why i report this bug for Bitwarden.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

124.0.6367.60

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @tracer8,

Thank you for reporting this. I tested this with Bitwarden 2024.4.1 on Chrome 124.0.6367.60 running on Windows 11 Pro, and the (Master Password) field within the extension's pop-up was visible and usable after closing the browser and opening it anew, and I was able to unlock the Bitwarden browser extension using the master password. I recommend that you proceed with a fresh new installation; Please uninstall the Bitwarden browser extension off Chrome, clear any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the computer, and install the Bitwarden browser extension anew.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
