### ISSUE TITLE
Closing the Windows app locks vault instead of logging out.

### ISSUE THREAD

**Issue by VonSparq** [bitwarden/clients#8853]
### Steps To Reproduce

1. Log into your vault on the Bitwarden Windows desktop app
2. Go to File > Settings
3. Under "Vault timeout action" select Log out
4. Click on Close
5. Close the app with the X on the top right
6. Launch the app again

### Expected Result

After launching the app again my vault should be logged out, this was the behavior ever since I started using Bitwarden.

### Actual Result

The vault is only locked, not fully logged out.
This only started happening after one of the recent updates, less than a month ago.

### Screenshots or Videos

![a](https://github.com/bitwarden/clients/assets/78357458/8fb14a9a-338e-492a-9197-0d98bd3e4992)

### Additional Context

I don't know if this is an intended change or a bug, but I really don't like it.
I know the setting is called "Vault timeout action" and not app close action, but it used to apply for both the timeout and closing the app.
If this change was intentional, please add an option to restore the previous behavior.

### Operating System

Windows

### Operating System Version

10 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by VonSparq** [comment]
Well, I think best I can do is show you that this really happens and how it looks like.
Since it's a password manager we're talking about here I tried to block as much sensitive information as I could, apologies if it makes your job harder.

https://github.com/bitwarden/clients/assets/78357458/bcf0a5fe-4a27-4c4e-a3bd-3db53f59cc59

As per (I think) your advice on Reddit I have uninstalled Bitwarden and downloaded and installed a fresh copy from

**Comment by VonSparq** [comment]
First of all I'm sorry about this^ I don't use Github much and I clicked close accidentally...

Well, I think best I can do is show you that this really happens and how it looks like.
Since it's a password manager we're talking about here I tried to block as much sensitive information as I could, apologies if it makes your job harder.

https://github.com/bitwarden/clients/assets/78357458/bcf0a5fe-4a27-4c4e-a3bd-3db53f59cc59

As per (I think) your advice on Reddit I have uninstalled Bitwarden and downloaded and installed a fresh copy from https://bitwarden.com/download/, the issue persists.

**Comment by SergeantConfused** [comment]
Hello @VonSparq,

Thank you for reporting this. I tested this on Windows 10 Pro 22H2 with Bitwarden 2024.4.1 and was unable to reproduce it. Bitwarden 2024.4.1 (.exe) was installed Per User, the Vault Timeout was set to On Restart, and the Vault Timeout Action was set to Log out, and I closed the Bitwarden desktop client’s window via the X button in the top right; After opening it anew, it was logged out. I recommend testing this in a fresh new installation; Uninstall Bitwarden off your machine, clear any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot, and install it anew.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
