### ISSUE TITLE
critism about Exposed Passwords Checker on online vault

### ISSUE THREAD

**Issue by somethingstarted** [bitwarden/clients#8892]
### Steps To Reproduce

1. Go to '(https://vault.bitwarden.com/#/reports/exposed-passwords-report)' or vault.bitwarden > reports > exposed passwords
2. DONT Click on anything yet... 

notice how right as you land on the page, since there aren't any passwords or accounts showing up on it (because you didn't yet press "run through my account") the other part of the page thinks you're fine. i know for sure i'm not fine as i have hundreds of accounts that have been compromised 0.0 

i feel like this is unthoughtful UI. - the conditions should be more like (pseudo code) "has user clicked the button yet? no? banner should say 'please click the button to analyze your saved accounts'" because i bet you that folks will go there, see that, assume bitwarden has already processed their account info and leave thinking they're fine. 

then if nothing comes back as failed, and they're all good, then it shows the banner "you're all set!" that it shows when loading the page

### Expected Result

i think it should say nothing until the data has been examined 

### Actual Result

says everything's fine when it doesn't yet know because nothing's yet been processed

### Screenshots or Videos

![no bitwarden no](https://github.com/bitwarden/clients/assets/19464532/8c0d0f6b-42ad-432c-8e7a-c9fea2dbe468)

### Additional Context

thanks. 

### Operating System

Windows

### Operating System Version

10 2hsomething

### Web Browser

Firefox

### Browser Version

124.0.2 (64-bit

### Build Version

latest stable? not sure. it's bitwarden hosted

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by MGibson1** [comment]
@somethingstarted, when you click the button do new items populate?

The reason it immediately shows no exposed is because just loading the page actually runs the report, as well. I agree that the name of the button is misleading. It should probably include 're' in some form to indicate that it has indeed been checked by the time you see both the button and the result.

If the result _changes_ when you click the the button to rerun, we may indeed have a bug we need to work out. If so, please reopen this ticket and we'll get things figured out.
