### ISSUE TITLE
Not retrieving saved passwords

### ISSUE THREAD

**Issue by d85** [bitwarden/clients#8942]
### Steps To Reproduce

1. Open Bitwarden
2. Enter master password
3. Observe infinite loading icon and passwords not retrieved

### Expected Result

Should see all previously saved entries

### Actual Result

Infinite loading icon

### Screenshots or Videos

![Screenshot from 2024-04-27 05-42-25](https://github.com/bitwarden/clients/assets/8790207/174ad37e-8ca4-493c-8def-253ebd1e8d48)

### Additional Context

I'm getting this after uninstalling and re-installing bitwarden from the snap store.
The reason I uninstalled and re-installed was, it had stopped working in a different way - it was complaining of some kind of token error whenever I tried to save a new entry.
I tried uninstalling and reinstalling to fix that error and am now getting this one.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Duplicate of https://github.com/bitwarden/clients/issues/8651
