### ISSUE TITLE
Bug? Different behavior in Card Auto-fill

### ISSUE THREAD

**Issue by 54m4d** [bitwarden/clients#8947]
### Steps To Reproduce

Hello,

On several websites, I've observed that when I attempt to Auto-fill a card from the Tab page, I encounter the error message `"Unable to auto-fill the selected item on this page. Copy and paste the information instead."` However, when I click on "view item" and then scroll down to choose Auto-fill, it functions as expected.

My question is: why does this behavior occur, and what differentiates clicking "Auto-fill" from the Tab page versus clicking "Auto-fill" from the view item page?

### Expected Result

Clicking Auto-fill on the Tab page should fill out the card form/fields.

### Actual Result

Error: `Unable to auto-fill the selected item on this page. Copy and paste the information instead.` See video for details.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/52612348/2abc851e-d1ac-41f6-b44f-365d220b0b31

### Additional Context

Easily reproducible @ https://fill.dev/form/credit-card-simple

### Operating System

Windows

### Operating System Version

Win 10

### Web Browser

Chrome

### Browser Version

124.0.6367.92

### Build Version

2024.4.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by romanshein** [comment]
I observe the same behaviour with the auto-filling form from the Identities. 

A form gets filled via OP's method ""view item" and then scroll down to choose Auto-fill" in the Extension Tab window. AND It also works with right-click on a form ->Bitwarden ->Auto-fill Identity ->YourIdentity. 
**Yet the auto-fill doesn't work via direct auto-fill click on the same Identity in the Extension Tab window.**

For example,**a problematic form URL is https://www.absolutereports.com/enquiry/request-sample/19223294?utm_source=LN_QY21_Dvijay.**

My setup: Win11 21H2, Vivaldi 6.7 (latest release) with Bitwarden Chrome extension 2024.4.1.

**Comment by SergeantConfused** [comment]
Hello @54m4d,

Thank you for this report. Yes, this behaviour has been reported and it should be addressed in the [upcoming extension release](https://github.com/bitwarden/clients/issues/8774#issuecomment-2061950588). I will keep this GitHub report open for now so that others would see it.

All the best,
