### ISSUE TITLE
Bug: Dark mode colors on organization collection user permissions

### ISSUE THREAD

**Issue by real-general-iroh** [bitwarden/clients#8952]
### Steps To Reproduce

1. Go to the web vault
2. Ensure you have dark mode enabled
3. Click on Admin Console
4. Click on `New` > `Collection`
5. Click on `Access`
6. Add a user to the collection
7. Click on the permissions for the newly added user
8. Notice the colors are very difficult to see

### Expected Result

Normal dark mode expected.

### Actual Result

The colors are wrong.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/103866867/cee934d7-7f19-4a29-aaf6-ca22984d4c3c)

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Microsoft Edge, Firefox, Vivaldi

### Build Version

Version 2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @real-general-iroh,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - the Engineering team will be happy to review them.

Thank you again,

**Comment by vincentsalucci** [comment]
This issue duplicates #4787.
--
Closing this issue - feel free to follow along with the above link for updates.
--
Thank you!
