### ISSUE TITLE
Bitwareden does not autofill when launching website

### ISSUE THREAD

**Issue by Robinphillipsza** [bitwarden/clients#8959]
### Steps To Reproduce

4. Click on '...'
I have an entry in Bitwarden with the URL, Username and Password correctly entered.
When tested it worked, autofilled the fields and pressed enter.

### Expected Result

Expect that the autofill works consistently in every version.

### Actual Result

Now it works intermittently.  Some days on starting my Windows version it does not autofill on launch
On other days, using the Web version, no autofill.
On Android, works some times not on others.

### Operating System

Windows

### Operating System Version

Windows 11. 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

OS Build 22621.3447

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @Robinphillipsza,

Thank you for this report. Let's take this from the top, please.
1. Launching a webpage via the Bitwarden browser extension is separate from performing Auto-Fill; The Launch function only opens a browser and points it to that URL.
2. You mentioned the desktop client in this GitHub report, and you also added the (desktop) tag; However, the desktop client does not perform Auto-Fill.

Could you please create a support ticket using the [form in the Help Centre](https://bitwarden.com/help/) so we'd have a look at this together? If needed, we can create a new GitHub report. In your ticket, please clarify what the matter seems to be, and also include a link to this GitHub report.

Thank you again,
