### ISSUE TITLE
Linux desktop app does not log out of vault when closed with Ctrl-Q

### ISSUE THREAD

**Issue by sylerner** [bitwarden/clients#8960]
### Steps To Reproduce

1. Log in to Linux Bitwarden desktop app
2. Type Ctrl-Q - the app completely closes but leaves the vault locked instead of logged out/closed
3. Restart desktop app
4. Locked vault login is displayed - bypassing entry of email before and second factor afterwards.

### Expected Result

When hitting Ctrl-Q, the Linux desktop app should completely log out and close the vault.

### Actual Result

When hitting Ctrl-Q, the vault is only locked, allowing easier access to the vault the next time the desktop app is started.

### Screenshots or Videos

![Screenshot_20240428_094923](https://github.com/bitwarden/clients/assets/20540525/21e0563e-85ad-4158-8db9-7d597d080728)
![Screenshot_20240428_095453](https://github.com/bitwarden/clients/assets/20540525/287bd8c5-ed27-46b3-9760-dc5b5081d69c)

### Additional Context

This issue should also apply to exiting with Ctrl-W.

### Operating System

Linux

### Operating System Version

openSUSE Tumbleweed KDE

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @sylerner,

Thank you for this report. Just to make sure that you and I are on the same page, what is the [Vault Timeout Action](https://bitwarden.com/help/vault-timeout/) in that Bitwarden desktop client set to?

Thank you,

**Comment by sylerner** [comment]
I have it set to Logout.

**Comment by SergeantConfused** [comment]
Hello @sylerner,

Thank you for reporting this. I tested this on openSUSE Tumbleweed 20240503 with KDE Plasma 6.0.4 using Bitwarden 2024.4.1 (.AppImage) and closing the window (CTRL+W) or quitting the application (CTRL+Q) caused the client to log out, when the Vault Timeout Action was set to Log out. I recommend checking if certain permissions are preventing that Bitwarden client from clearing its data after it's closed; Alternatively, you can try uninstalling it, rebooting, and installing it anew to check if a fresh installation behaves as expected in this regard.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
