### ISSUE TITLE
MV3 Beta: HTTP Basic Auth autofill not working

### ISSUE THREAD

**Issue by Brawl345** [bitwarden/clients#9001]
### Steps To Reproduce

1. Go to a site with HTTP Basic Auth (f.e. https://authenticationtest.com/)
2. Create a new login item with the credentials (for the above URL: "user" and "pass")
3. Click on HTTP/NTLM Auth on the website

### Expected Result

The HTTP Basic Auth prompt should be "skipped"/autofilled like explained in https://bitwarden.com/help/basic-auth-autofill/ and working in the stable version of the extension

### Actual Result

The HTTP Basic Auth prompt gets shown

### Screenshots or Videos

<img width="1105" alt="image" src="https://github.com/bitwarden/clients/assets/5049892/46b241b0-c180-4dc4-abbb-1783a8600fd1">

### Additional Context

I am using the BETA Manifest v3 version from https://chromewebstore.google.com/detail/bitwarden-password-manage/hccnnhgbibccigepcmlgppchkpfdophk

It works in the stable version.

### Operating System

macOS

### Operating System Version

Sonoma 14.4.1

### Web Browser

Chrome

### Browser Version

124.0.6367.119

### Build Version

2024.4.4471.46045 beta - 443da7f6

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Brawl345** [comment]
Looking through the commit log this will work with https://github.com/bitwarden/clients/commit/3acbffa0726d8b4bda5c410d2ad98cf226a8ab7a but this release is not published yet. Sorry!

**Comment by djsmith85** [comment]
Closing, as this was added with #8975.
