### ISSUE TITLE
Browser extension: bottom menu does not fit in popup

### ISSUE THREAD

**Issue by pashynskykh** [bitwarden/clients#9007]
### Steps To Reproduce

1. Open any Chromium-based browser.
2. Set default page zoom more then 100%.
3. Open Bitwarden extension popup.

### Expected Result

Extension fits the popup and menu bar is accessible.

### Actual Result

Extension DOES NOT fit into the popup and menu bar is NOT easily accessible (you need to use scroll bar). Other extensions with popups does not have this issue.

### Screenshots or Videos

![Screenshot from 2024-05-02 09-01-44](https://github.com/bitwarden/clients/assets/14852335/c403403a-79cd-4550-ad2e-fded243b4570)

### Operating System

Linux

### Operating System Version

Debian Bookworm (but the same on other OSes)

### Web Browser

Brave

### Browser Version

Versjon 1.65.123 Chromium: 124.0.6367.91 (but the same for other Chromium-based browsers, such as Vivaldi)

### Build Version

2023.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by pashynskykh** [comment]
Hi @Greenderella,

Thanks for the update! I hope this issue will be addressed, as it is painful to use the Bitwarden extension while the default page zoom is increased.

This issue is easily reproducible, so I guess nothing else to add here. But if there will be a need for additional screenshots/recordings/logs - I would be happy to provide them.

Thanks again!

Best regards,
Vladyslav

**Comment by bllngr** [comment]
There is another report at #9909 containing a suggestion for a fix.

**Comment by ramprasathasokan** [comment]
Hi @Greenderella,

Please prioritize this, it's really painful for folks with external monitor and MacOS as we have to zoom the browser individually.

**Comment by k2vi** [comment]
I am having this, or a very similar, issue in Windows 10 with Vivaldi (chromium-based) browser. I can't access my identities or the bottom menu either by scrolling or by adjusting the zoom level. 

![Screenshot 2024-09-02 182644-2](https://github.com/user-attachments/assets/0ed15304-6a85-4a5f-9286-52c880ffa626)

**Comment by vleague2** [comment]
@pashynskykh This has been addressed with #12427 and is included in the 2025.1.0 release!
