### ISSUE TITLE
Web vault backup export isn't working with "Login with Device"

### ISSUE THREAD

**Issue by Jack15911** [bitwarden/clients#9016]
### Steps To Reproduce

1. Using MacOS Firefox or Safari enter UID/email address
2. Choose Login with Device - not password
3. Authenticate MFA using Yubikey
4. Choose Tools/Export Vault
5. Choose My Vault, .json encrypted, password protected
6. Enter previously selected and used successfully File Password and Confirm Password, and Confirm Format
7. Confirm Export Vault box pops up - insert Master Password manually or from the normal menu bar icon, (but not the new dropdown offers, as this will also change your File Password underneath the box to Master Password) and select Export Vault
8. Note the error box - Invalid Master Password

### Expected Result

I expect to see the Export Vault function work and offer me the option as to where to save the export, but it does not.

Export works fine when logging in with password.

### Actual Result

Error box - Invalid Master Password

### Additional Context

I think what's happening is that I did not enter a master password to log in, so there is no master password (probably hashed) to compare with the master password I entered during the export process. Because there is nothing to compare I get an "invalid password" failure.

I previously opened an issue on this as #8738, but had not realized the relationship with "Login with Device," so it could not be replicated and was closed. I attempted to re-open the earlier bug report with additional info but was unsuccessful and am therefore opening a new bug report.

### Operating System

macOS

### Operating System Version

Sonoma 14.1.1

### Web Browser

Firefox

### Browser Version

125.0.3 also Safari 17.1

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Jack15911** [comment]
I have not enrolled a Passkey to login to Bitwarden, but it's possible that it might suffer from the same effect on Export as Login with Device.

**Comment by gitgotgatcat** [comment]
Yes, it is a very bad user experience.

Login with device
Export (password protected)
Enter file password
Enter file password (for confirmation of mistype)
Enter master password (rejected)
Enter master password (again rejected)
Enter master password (yet again rejected)
Realize what is going on. 
start all over, enter 2 more file passwords and a single master password to finish the job. 

Even a dumb guy like me can figure out that something is wrong after a few rejects. But seriously that's a bad user experience.

**Comment by djsmith85** [comment]
This has been addressed with #9523 and will be included in the next release (`2024.7`).

Closing this now.
