### ISSUE TITLE
Autofill Menu is not shown when form is inside a dialog html tag

### ISSUE THREAD

**Issue by imattferreira** [bitwarden/clients#9073]
### Steps To Reproduce

1. Configure Bitwarden autofill when input is selected (`Settings->autofill->show autofill menu on form fields->When field is selected (focus)`)
2. Access the reproduction code in browser
3. Click on "Open Dialog" to open the dialog
4. Attempt to use the autofill menu with the form that in inside the dialog (e.g.: focus the input to see the Bitwarden button inside the input)

### Expected Result

 The autofill menu should be shown inside the form input.

### Actual Result

The autofill menu is not shown when a input is focused that is inside a dialog 

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/52766091/65955624-ba0d-44ac-b781-2ad09155f5c3

### Additional Context

Reproduction code: https://github.com/imattferreira/bitwarden-autofill-dialog-repro

### Operating System

macOS

### Operating System Version

14.4.1

### Web Browser

Chrome

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

This has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!
