### ISSUE TITLE
`Bitwarden-2024.4.3-x86_64.AppImage` fails with `SUID sandbox helper binary` error on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by jtherrmann** [bitwarden/clients#9105]
### Steps To Reproduce

1. Use Ubuntu 24.04 LTS
2. Download `Bitwarden-2024.4.3-x86_64.AppImage` and make it executable with `chmod +x`
3. Run `./Bitwarden-2024.4.3-x86_64.AppImage`. There might be a dependency error, perhaps related to `libfuse`, but I don't remember for sure.
4. After installing any required dependencies via `apt`, running the AppImage results in the following error:

```
[325156:0509/102335.519347:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_BitwarNfStY1/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

5. Run `sysctl kernel.unprivileged_userns_clone` and confirm that the output shows `kernel.unprivileged_userns_clone = 1` (see the docs on [Electron sandboxing](https://docs.appimage.org/user-guide/troubleshooting/electron-sandboxing.html)).
6. Run `./Bitwarden-2024.4.3-x86_64.AppImage --no-sandbox`. The Bitwarden Desktop app should launch successfully.

### Expected Result

Running `./Bitwarden-2024.4.3-x86_64.AppImage` should successfully launch the desktop app.

### Actual Result

The app fails to launch due to the `SUID sandbox helper binary` error unless the `--no-sandbox` option is supplied.

### Additional Context

Relevant discussions:
* https://community.bitwarden.com/t/linux-installer-appimage-error-suid-sandbox-helper-not-configured-correctly-and-libffmpeg-so-not-found/46132
* https://github.com/electron/electron/issues/17972

### Operating System

Linux

### Operating System Version

Ubuntu 24.04 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtherrmann** [comment]
I may be misunderstanding the `kernel.unprivileged_userns_clone = 1` option and the `--no-sandbox` option. I'm simply looking for the recommended solution to this problem that follows recommended security best practices.

**Comment by Greenderella** [comment]
Hi there,

Currently, this behavior is expected due to the constraints of an Electron application. However, our team is actively investigating ways to improve this as part of our work on this issue: [#5153.](https://github.com/bitwarden/clients/issues/5153)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by jtherrmann** [comment]
I posted my workaround in the issue you linked.
