### ISSUE TITLE
Cannot reverse choice of "never" when asked to store passkeys in Bitwarden

### ISSUE THREAD

**Issue by unikitty37** [bitwarden/clients#9123]
### Steps To Reproduce

1. Create a passkey as 2FA on a supporting site (for example: github.com). Store the passkey in the browser, not BitWarden.
2. Log out of the site.
3. Log in to the site, invoking the BitWarden browser extension.
4. When prompted whether to use BitWarden to retrieve the passkey, choose Never.
5. Decide to use BitWarden after all (say, because iOS app support for passkeys has just been released :) and try to change the setting back to using BitWarden.

### Expected Result

Editing the github.com entry in the macOS app has a visible setting for whether passkeys should be filled from BitWarden, and I can reset this to "always" or "ask each time". The same goes for the web interface.

### Actual Result

I cannot find any way of changing this setting from "never" once it has been set.

### Operating System

macOS

### Operating System Version

macOS 14.4.1 (23E224)

### Installation method

Mac App Store

### Build Version

2024.4.1 (23240)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Drumering** [comment]
I'm getting the same behavior.

**Comment by subhangmall** [comment]
Same behavior on Windows

**Comment by sacker4u** [comment]
I think I found a solution. Download the browser extension, go to settings -> notifications -> excluded domains. Delete the domains that you want and it worked for me.

**Comment by SergeantConfused** [comment]
Hello everyone,

Thank you all for your input. @unikitty37, could you please follow the steps that @sacker4u [posted](https://github.com/bitwarden/clients/issues/9123#issuecomment-2204634354) and let me know if they help? To be clear, when you select (Never) in that prompt, it essentially adds that URL to the [excluded domains](https://bitwarden.com/help/exclude-domains/) function in the browser extension.

Thank you in advance,

**Comment by Drumering** [comment]
> I think I found a solution. Download the browser extension, go to settings -> notifications -> excluded domains. Delete the domains that you want and it worked for me.

tks @sacker4u ! works fine for me.
