### ISSUE TITLE
Browser extension: Vault export adds additional quote symbol in password

### ISSUE THREAD

**Issue by keteague** [bitwarden/clients#9124]
### Steps To Reproduce

1. In the Chrome extension
2. Settings > Export vault > CSV format
3. Settings > Export vault > .json format
4. Copy the password from the BitWarden extension for Chrome and Firefox into a text editor
5. Open the exported CSV file, locate the password entry, and copy it from the export file to the other text editor for a top/bottom comparison.  Here, we see the exported password is 1 character longer than the (correct) password that's still in the BitWarden vault, and we see an extra quotation mark added.
6. Open the exported JSON file, locate the password, and copy it to the other text editor for a top/bottom comparison - there is not an extra quotation mark, but there is an added backslash symbol.
7. Repeat all of the above steps with the Firefox extension and get the same result.

### Expected Result

Original/correct password that is in the Bitwarden vault
n3:X]*c}~(bq5ng{jprd=E6.hS+9Y?_Ask/x@g<atmW>Ru,)y4Jfq}%#B?Yrt&Z9yX(,d6gK*M_3h4FPLV[p5D;.Cbzu7"/^8+@c

### Actual Result

Oddly enough, I can't post my result here because GitHub's parser is jacking it up, too.  You can view the original (correct) and exported results here: https://text.is/0N60

### Additional Context

- I submitted this problem yesterday with insufficient data and passed it off as a problem with viewing the exported CSV file in LibreOffice Calc.  Today, I have more data to submit this as a bug report.
- Tested this in both Chrome 124.0.6367.118 (Official Build) (64-bit) and Firefox 115.8.0esr (64-bit)
- Reviewing my JSON export for other passwords, I have one other password that contains quotation marks separated far apart from each other, and each of them are prefixed with a \ symbol, while the original/correct password in the vault does not have them.
- It seems there's a problem with handling the export of passwords that contains quotation marks.

### Operating System

Linux

### Operating System Version

Debian GNU/Linux

### Web Browser

Chrome

### Browser Version

124.0.6367.118

### Build Version

(Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by keteague** [comment]
Which characters have you found to be a problem.

I may be incorrect, but I suspect the issue is related to BitWarden
encasing the password, in full, within quotes.  As such, if the password
contains quotes, it has to escape them so it doesn't end the password
string prematurely.  Programmatically, that can be done using an extra
quote or a backslash.

**Comment by keteague** [comment]
If I may respectfully suggest, review your reply.  I'm not sure if what is
in that reply makes sense (to me).  I had a problem submitting this issue
because github's message parser was butchering my password making my
comparison look the same

**Comment by keteague** [comment]
I exported my vault in CSV format using the BitWarden app from the Apple App Store and it doesn't contain any additional characters in the two examples that I posted previously.  The exported passwords appear to be exactly the same as what is currently in my vault.

**Comment by aj-rosado** [comment]
I have tested this functionality and it seems correct to me.
We are creating a standard csv file and if we change it, removing the escape double quotes (") or not enclosing the field, it would break in some scenarios, for example Bitwarden import would not work properly.

[RFC-4180](https://www.ietf.org/rfc/rfc4180.txt) says

```
6. Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.
       
7. If double-quotes are used to enclose fields, then a double-quote appearing inside a field must be escaped by preceding it with another double quote.
```

As we are following the recommendations and standards, I do not think we should change it.

Thank you for the feedback.
