### ISSUE TITLE
`sha256sum --ignore-missing -c sha256-checksums.txt` fails due to trailing whitespace on each line

### ISSUE THREAD

**Issue by font** [bitwarden/clients#9139]
### Steps To Reproduce

1. Download desktop client binary e.g. [`Bitwarden-2024.4.3-x86_64.AppImage`](https://github.com/bitwarden/clients/releases/download/desktop-v2024.4.3/Bitwarden-2024.4.3-x86_64.AppImage)
2. Download sha256 checksum file corresponding to the same release binary [`sha256-checksums.txt`](https://github.com/bitwarden/clients/releases/download/desktop-v2024.4.3/sha256-checksums.txt)
3. The below commands show the error along with the fix that corrects it. Run the commands in the same directory you downloaded the files:
```shell
→ ls Bitwarden-2024.4.3-x86_64.AppImage
Bitwarden-2024.4.3-x86_64.AppImage
→ sha256sum --ignore-missing -c sha256-checksums.txt 
sha256sum: sha256-checksums.txt: no file was verified
```

### Expected Result

```shell
→ sha256sum --ignore-missing -c sha256-checksums.txt 
Bitwarden-2024.4.3-x86_64.AppImage: OK
```

### Actual Result

```shell
→ sha256sum --ignore-missing -c sha256-checksums.txt 
sha256sum: sha256-checksums.txt: no file was verified
```

### Screenshots or Videos

The below commands show the error along with the fix that corrects it. Run the commands in the same directory you downloaded the files:
```shell
→ grep 'Bitwarden-2024.4.3-x86_64.AppImage ' sha256-checksums.txt 
7f4fbda395de27e1a2686b07fad717b3d6b73e469ebedc6875d8515ab7b4ef09 Bitwarden-2024.4.3-x86_64.AppImage 
→ grep -Pzo 'Bitwarden-2024.4.3-x86_64.AppImage\n' sha256-checksums.txt 
→ ls Bitwarden-2024.4.3-x86_64.AppImage
Bitwarden-2024.4.3-x86_64.AppImage
→ sha256sum --ignore-missing -c sha256-checksums.txt 
sha256sum: sha256-checksums.txt: no file was verified
→ sed -i 's/ $//' sha256-checksums.txt 
→ grep 'Bitwarden-2024.4.3-x86_64.AppImage ' sha256-checksums.txt 
→ grep -Pzo 'Bitwarden-2024.4.3-x86_64.AppImage\n' sha256-checksums.txt 
Bitwarden-2024.4.3-x86_64.AppImage
→ sha256sum --ignore-missing -c sha256-checksums.txt 
Bitwarden-2024.4.3-x86_64.AppImage: OK
```

### Additional Context

Remove trailing whitespace from `sha256-checksums.txt` to fix the problem.

### Operating System

Linux

### Operating System Version

Fedora 38

### Installation method

Other

### Build Version

4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @font,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by SergeantConfused** [comment]
Hello,

This matter is being examined here (https://github.com/bitwarden/gh-actions/pull/280).


All the best,
