### ISSUE TITLE
Unable to generate forwarded email aliases via Firefox Relay in generator tool

### ISSUE THREAD

**Issue by dvejmz** [bitwarden/clients#9143]
### Steps To Reproduce

1. Go to the generator tool on the web client -> https://vault.bitwarden.eu/#/tools/generator
2. Select the radio buttons 'Username' and 'Forwarded email alias'
3. Select 'Firefox Relay' in the 'Service' dropdown
4. Enter a valid Firefox Relay API Access Token in the corresponding field
5. Click on 'Regenerate username'

### Expected Result

The generator generates a new, valid Firefox Relay email alias linked with my Firefox Relay account and displays it on screen.

### Actual Result

The generator doesn't generate anything. Instead, the following error toast appears: "Unknown Firefox Relay error occurred.".

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/9487006/44ff1283-1d7a-431d-9537-42498c9d0584)

### Additional Context

Upon inspection on my browser devtools network tab, I can see the web client sends the following request to the Firefox Relay API servers.

```json
// POST https://relay.firefox.com/api/v1/relayaddresses/
{"enabled":true,"generated_for":null,"description":"Generated by Bitwarden."}
```

And the response it gets back from the Firefox Relay servers is a HTTP 400 with the following message
```json
{"generated_for":["This field may not be null."]}
```

### Operating System

Linux

### Web Browser

Firefox

### Browser Version

125.0.3

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @dvejmz,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by jotiheranbnach** [comment]
I have the same error

**Comment by ZaneBartlett1** [comment]
I'm able to reproduce the error through the bitwarden extension as well. I really loved the integration there!

**Comment by knox203** [comment]
Same error here as well. Use it a lot, and the Bitwarden extension is a big convenience and makes it really easy. Would love to see this fixed!

**Comment by ZaneBartlett1** [comment]
Something that I've realized is that in Firefox at least, it looks like in most text boxes when you right click have the option for "Use Relay Email Mask" which automatically generates and fills the line with a mask.

Seems like a pretty nice stop gap, although I do like the idea of having a more universal option through Bitwarden.

**Comment by SergeantConfused** [comment]
Hello everyone,

Is any still able to reproduce this in [Web App](https://vault.bitwarden.com/) version 2024.6.2?

Thank you in advance,

**Comment by knox203** [comment]
Just tried it for the first time in awhile, and it appears to be work again! Confirmed running version 2024.6.2.

**Comment by dvejmz** [comment]
I can confirm this issue is resolved on `2024.6.2` and am happy to close this issue now. Thank you for fixing this, Bitwarden team!

**Comment by amalinda** [comment]
The same error is back for me though..

**Comment by bsolca** [comment]
Same for me. Error is back

**Comment by lucasako** [comment]
Same error message

**Comment by PsychoSanchez** [comment]
It seem that Firefox Relay API imposed more restrictions on the request payload: https://github.com/bitwarden/clients/issues/14140
