### ISSUE TITLE
Bitwarden failing to upgrade in choco

### ISSUE THREAD

**Issue by Destroy666x** [bitwarden/clients#9144]
### Steps To Reproduce

1. Upgrade to version 2024.4.3 in choco

### Expected Result

Software gets upgraded

### Actual Result

This eror gets shown:
![image](https://github.com/bitwarden/clients/assets/3606072/9aa5f2b0-d046-4bdb-8904-bf17146193ff)

### Operating System

Windows

### Operating System Version

10

### Installation method

Chocolatey

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Destroy666x,

Thank you for reporting this. I tested this by installing Bitwarden 2024.4.0 ```choco install bitwarden --version=2024.4.0```, launching that Bitwarden desktop client on Windows 11 Pro, and then running ```choco upgrade bitwarden```, and this worked as expected and I was able to launch version 2024.4.3 of the Bitwarden desktop client for Windows. I recommend that you try starting with a fresh new installation of the desktop client by uninstalling the current one, rebooting, and installing version 2024.4.3 from scratch.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Comment by Destroy666x** [comment]
Uninstalling in choco didn't work either...

Obvious bug of (un)uninstaller, both of which don't close the app first.
