### ISSUE TITLE
Mac OS App (installed from App Store) 

### ISSUE THREAD

**Issue by nagydavid** [bitwarden/clients#9151]
### Steps To Reproduce

1. Go to 'APP'
2. Click on 'Logging on : bitwarden.com'
3. Change to self hosted.
5. Urls is saved (green notification)
6. but the server address remained not desktop on Bitwarden.com

### Expected Result

Able to login.

### Actual Result

Not able to login

### Additional Context

I am able to login to my self-hosted system with the extgension. I also able to login with the brew installation instead of App Store.

### Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Installation method

Mac App Store

### Build Version

Version 2024.4.1 (23240)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Running 2024.4.1  on MacOS I was not able to replicate this behaviour. After the self-hosted URL is saved and I quit the Bitwarden app, the URL is still there and functional after app is launched again. Could you please try reinstalling the desktop app?

**Comment by adfrench** [comment]
I am running version 2024.4.1 on macOS 14.4.1 and am seeing this exact same issue.  I downloaded the application from the Apple Store.  I can access my vault from the browser and via the chrome extension.  My vault is secured behind a firewall and requires a VPN connection.

**Comment by djsmith85** [comment]
@nagydavid, @adfrench This should be addressed in recent updates with https://github.com/bitwarden/clients/pull/8040 and https://github.com/bitwarden/clients/pull/8046.

Could you please test with `2024.4.3 or higher` and report back.

Kind regards,
Daniel

**Comment by adfrench** [comment]
@djsmith85 The dmg for 2024.4.3 worked.  Thank you!  Hopefully that version will get propagated to the App Store soon.
