### ISSUE TITLE
Swapped Colors on Inline

### ISSUE THREAD

**Issue by Larsmeneer** [bitwarden/clients#9198]
### Steps To Reproduce

Google to: Bitwarden Logo. Keep in mind how to colors are, white on the left, blue on the right.

Now open anywhere you can see the inline logo( I have attached a link to preview down below) then you will see that blue is on the left, and white on the right.

### Expected Result

See the colors the right way it is displayed everywhere.

### Actual Result

The colors are swapped on the inline logo.

### Screenshots or Videos

Here is a link to preview the logo's, down below is the logo that is used everywhere exept the inline. https://imgur.com/a/O6aYFx2

### Additional Context

Any issues, feel free to contact me about it.

### Operating System

Windows

### Operating System Version

Windows 11 / 22635.3575 (this doesnt matter it is every browser extention, chrome firefox etc.)

### Web Browser

Firefox

### Browser Version

Doenst matter

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

This is as designed. Inverting logo colors is a common marketing practice to accommodate different colored backgrounds. 

The issue here will be closed.

Thanks!
