### ISSUE TITLE
Password generator policy doesn't apply when opening tool via link

### ISSUE THREAD

**Issue by kolja1507** [bitwarden/clients#9207]
### Steps To Reproduce

1. Set password generator policy
1. Go to https://vault.bitwarden.com/#/tools/generator or self-hosted variant
1. Log in

### Expected Result

Organization policy affects generator settings

### Actual Result

Organization policy doesn't affect generator settings

### Additional Context

Issue has been occurring for quite some time now, so doesn't seem to be a recent regression.

Workarounds:

1. Set password generator policy
1. Go to https://vault.bitwarden.com/#/tools/generator or self-hosted variant
1. Log in
1. Reload page
1. Unlock

or

1. Set password generator policy
1. Go to https://vault.bitwarden.com/#/login or self-hosted variant
1. Log in
1. Paste `https://vault.bitwarden.com/#/tools/generator` or self-hosted variant in web browser's address bar

or

1. Set password generator policy
1. Go to https://vault.bitwarden.com/#/login or self-hosted variant
1. Log in
1. Click on **Tools** (redirects to **Generator**)

### Operating System

macOS, iOS

### Operating System Version

macOS 14.5, iOS 17.5

### Web Browser

Safari, Firefox, Brave

### Browser Version

Safari 17.5, Firefox 126.0, Brave 1.65.133

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by kolja1507** [comment]
@Krychaz Thanks for looking into this issue! It has stopped occurring for our organization in the meantime, so I'm closing this…
