### ISSUE TITLE
Endless loading spinner 2024.4.3

### ISSUE THREAD

**Issue by staroks3** [bitwarden/clients#9247]
### Steps To Reproduce

I installed a new version 2024.4.3 2024-05-06 (109) 97MB

### Commands CLI

1. sudo snap install bitwarden
2. sudo snap connect bitwarden:password-manager-service

I opened bitwarden through CLI with command: bitwarden and I got this messages error:

- Error: The name org.freedesktop.secrets was not provided by any .service files
- Error: Failed to decode access token: JWT must have 3 parts

I got the same screen with endless circle loading I reported here: https://github.com/bitwarden/clients/issues/8753#issuecomment-2057643713

What can I do to solve this issue?
Thank you

### Expected Result

The result is equal this one: 

![1](https://github.com/bitwarden/clients/assets/167122409/277dadba-98b8-49cc-a801-47bd34540705)

### Actual Result

The result is equal this one: 

![1](https://github.com/bitwarden/clients/assets/167122409/277dadba-98b8-49cc-a801-47bd34540705)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS (Kubuntu)

### Installation method

Snap

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @staroks3,

Thank you for this report. Could you please install [gnome-keyring](https://en.wikipedia.org/wiki/GNOME_Keyring) and let me know if that helps in this Kubuntu environment? More about [this here](https://github.com/bitwarden/clients/issues/8651#issuecomment-2071060754); There is no need to use the .AppImage for this, as I successfully tested this with the Snap installation.


Thank you in advance,

**Comment by webbo96** [comment]
I am also having this exact same issue on Ubuntu 23.10 with the snap install. I have tried uninstalling and purging the app data but it is still broken. I also already have gnome-keyring installed.

**Comment by SergeantConfused** [comment]
Hi @webbo96,

If you're using Ubuntu, please follow the instructions in the [Bitwarden documentation](https://bitwarden.com/help/getting-started-desktop/#tab-3-6vQUhrVotSKFarA3cqyESG); This thread is regarding Kubuntu specifically, and you do not need to install gnome-keyring when using Ubuntu. As a side note, what you're encountering is [discussed here](https://github.com/bitwarden/clients/issues/8651).

All the best,

**Comment by webbo96** [comment]
My apologies. Thanks for the help and redirection. This resolved my issue.
