### ISSUE TITLE
Browser Extension asks for biometrical key after locking vault when not frontmost

### ISSUE THREAD

**Issue by Xytronix** [bitwarden/clients#9248]
### Steps To Reproduce

Requirements:
1. Install desktop version for mac
2. Login on both
3. Navigate to options inside the extension
4. Activate unlock by biometrics.
5. Close browser and login via biometrics.

Steps to Reproduce:
Extension pops up a message to unlock the vault via biometrics whenever the timer runs out after first logging in. Note the extension isn't actively opened. This happens on multiple occasions when the vault closes itself and you want to open the vault again.

### Expected Result

Application doesn't automatically ask for biometrics to unlock

### Actual Result

Extension ask for biometrics even though not needed.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/32957125/f274474e-a2cf-4936-95a7-a2d1c8813188)

### Operating System

macOS

### Operating System Version

2024.4.1

### Web Browser

Chrome

### Build Version

2024.4.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @Xytronix,

Thank you for reporting this. I tested this on macOS 14.5 with Bitwarden extension 2024.4.2 in Chrome 124.0 and I was not prompted to unlock the extension via Touch ID after the [Vault Timeout](https://bitwarden.com/help/vault-timeout/) was met, without interacting with the extension. I recommend that you consider beginning with a fresh new installation; Please uninstall the Bitwarden browser extension off Chrome, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the computer, and install it anew.

If this behaviour persists, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
