### ISSUE TITLE
ERROR: Unable to find "popup/fonts/bwi-font.svg" in the extension’s resources.

### ISSUE THREAD

**Issue by PapiPeppers** [bitwarden/clients#9297]
https://github.com/bitwarden/clients/assets/57047860/3f46db88-490a-485c-a4e0-f1f673b113af

### Steps To Reproduce

1. Click on browser extension icon in title bar

### Expected Result

Login dialog displays for user to input email and password

### Actual Result

First, a blank box with no text or images will display. After that initial click and blank display, clicking the extension icon will do nothing.

### Additional Context

The extension works properly on the standard Safari browser version. It does not work on the Safari Technology Preview.

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Web Browser

Safari

### Browser Version

Safari Technology Preview Release 194 (Safari 17.4, WebKit 19619.1.11.111.2)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by PapiPeppers** [comment]
Issue resolved with upgrade to version 2024.5.0

**Comment by owl70** [comment]
I'm getting this error with 2024.9.1

**Comment by AndreasLueck** [comment]
I'm getting it with Version 2024.6.2
