### ISSUE TITLE
Error "Failed to decode access token: JWT must have 3 parts"

### ISSUE THREAD

**Issue by tiagofunk** [bitwarden/clients#9328]
### Steps To Reproduce

1. Go to 'File'
2. Click on 'New Login'
3. Write a name on name field
4. Click on 'Save'

### Expected Result

Create a new login item

### Actual Result

Error: "Failed to decode access token: JWT must have 3 parts"

### Screenshots or Videos

![Captura de tela de 2024-05-22 23-45-17](https://github.com/bitwarden/clients/assets/19240101/e92e748a-0aee-464b-84f3-e69a50cd89f1)

### Operating System

Linux

### Operating System Version

Linux 6.5.0-35-generic 22.04.1-Ubuntu x86_64 x86_64

### Installation method

Snap

### Build Version

Version 2024.5.0 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment]
Could you please review and perform the steps outlined in the Bitwarden Help Centre (https://bitwarden.com/help/getting-started-desktop/#tab-3-6vQUhrVotSKFarA3cqyESG) to allow the Snap Bitwarden desktop client to access Secure Storage

As a side note, you can learn more about this matter here (https://github.com/bitwarden/clients/issues/8651), if you wish.

**Comment by tiagofunk** [comment]
Thank you for attention. My problem has been resolved. I suggest leaving this information linked to the error message. A few days ago I looked for a solution and didn't find an effective solution looking for the error message that appears in the application.
