### ISSUE TITLE
Unable to fetch ServerConfig

### ISSUE THREAD

**Issue by zoechi** [bitwarden/clients#9330]
### Steps To Reproduce

`bw login` or any other `bw` command

```
bw login
Unable to fetch ServerConfig: request to https://api.bitwarden.com/config failed, reason: connect ECONNREFUSED 64:ff9b::9765:415b:443
? Email address: user@example.com
? Master password: [hidden]
request to https://identity.bitwarden.com/accounts/prelogin failed, reason: connect ECONNREFUSED 64:ff9b::9765:15b:443
```

### Expected Result

No error

### Actual Result

Error: 
```
request to https://identity.bitwarden.com/accounts/prelogin failed, reason: connect ECONNREFUSED 64:ff9b::9765:15b:443
```

### Operating System

Linux

### Operating System Version

Linux ops 6.6.30 #1-NixOS SMP PREEMPT_DYNAMIC Thu May  2 14:32:50 UTC 2024 x86_64 GNU/Linux

### Shell

Bash

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by zoechi** [comment]
I have no idea if this helps but I tried

```sh
curl  https://identity.bitwarden.com/accounts/prelogin
{"kdf":0,"kdfIterations":600000,"kdfMemory":null,"kdfParallelism":null}⏎  
```

**Comment by daniellbw** [comment]
Hi @zoechi 


Could you please run `bw status` and let me know what the output is. 

This should either be https://vault.bitwarden.eu, https://vault.bitwarden.com or https://your.bw.domain.com
Depending on whether you are on the EU, US or whether you are self hosting Bitwarden(https://bitwarden.com/help/cli/)

**Comment by zoechi** [comment]
```sh
bw status
Unable to fetch ServerConfig: request to https://api.bitwarden.com/config failed, reason: connect ECONNREFUSED 64:ff9b::9765:415b:443
{"serverUrl":null,"lastSync":null,"status":"unauthenticated"}
```

This time when I tried `bw login` I got to the MFA method selection prompt. With the previous attempts I didn't get that far.

**Comment by daniellbw** [comment]
Hi @zoechi 

I've attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a network issue, could you try using the CLI tool from a different network.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by zoechi** [comment]
Are there known issues with IPv6?
Besides that my network isn't doing anything special.

A `curl https://api.bitwarden.com/config` seems to connect fine but gets "bad request" as far as I remember (only on the phone right now).
The only site I have troubles with is GitHub, because DNS returns IPv4 and IPv6 addresses, but the services don't listen on IPv6 yet, so I prevent IPv6 for this domain. This is a well known issue with GitHub.

This is  why IPv6 is a suspicion.

**Comment by zoechi** [comment]
I still think this is a bug and I think it's an issue with your IPv6 setup.
See also https://community.bitwarden.com/t/enable-ipv6-for-vault-domains/66730/2

**Comment by zoechi** [comment]
While investigating I found out that identity.bitwarden.com has the same IPv6 network IP as GitHub. Removing the IPv6 firewall block rule didn't fix bitwarden cli though.

The hack that works for now is, to add this to `/etc/hosts` to force it to use IPv4

```
151.101.129.91 identity.bitwarden.com api.bitwarden.com
151.101.193.91 identity.bitwarden.com api.bitwarden.com
151.101.1.91   identity.bitwarden.com api.bitwarden.com
151.101.65.91  identity.bitwarden.com api.bitwarden.com
```
