### ISSUE TITLE
Bitwarden wont open on both desktop and app (iphone)

### ISSUE THREAD

**Issue by colibricontent** [bitwarden/clients#9331]
### Steps To Reproduce

Onlye have to try opening the app on both services, and I dont get access to anything. Just the wheel spinning and then, after some time, kicking me out of the program/app again. 

<img width="747" alt="Skjermbilde 2024-05-23 kl  11 05 51" src="https://github.com/bitwarden/clients/assets/107485612/f668f3e8-9dc0-4603-baa5-e7b9ecea878a">

### Expected Result

Would like access to mye passwords😅

### Actual Result

No access to passwords.

### Screenshots or Videos

<img width="784" alt="Skjermbilde 2024-05-23 kl  11 06 20" src="https://github.com/bitwarden/clients/assets/107485612/c05da088-fa09-4a64-a63f-80ae7979f0fc">

### Operating System

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Versjon 2024.4.1 (23240)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.
