### ISSUE TITLE
TOTP wrong vs. mobile app / Linux

### ISSUE THREAD

**Issue by hnpc2** [bitwarden/clients#9358]
### Steps To Reproduce

1. Go to Linux 2024.4.3 Bitwarden and open an item that has a verfification code
2. Compare TOTP, verification code with mobile app and see that it is different

### Expected Result

Same verification codes (TOTP) on all devices for the same item

### Actual Result

Different verification codes (TOTP) on all devices for the same item

I could not login into some of my account.

### Operating System

Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.3

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sedlund** [comment]
verify the time is correct on both devices

**Comment by djsmith85** [comment]
Hi @hnpc2,

As @sedlund mentioned you'll need to check the time and timezones on your devices. TOTP codes are time-based.

Please have a look at https://bitwarden.com/help/integrated-authenticator/#troubleshooting and change the time and timezone of the device that is out of sync.

Closing this now.

Kind regards,
Daniel
