### ISSUE TITLE
No collections appear when adding a new item to organizatiol vault

### ISSUE THREAD

**Issue by dhon-rh** [bitwarden/clients#9367]
### Steps To Reproduce

1. Go to an organizational vault
2. Click on Add Item
3. Scroll down to Collections

### Expected Result

Collection section should be populated
![image](https://github.com/bitwarden/clients/assets/86488977/35d989ce-4db9-4e14-be62-aa2afc5187ea)

### Actual Result

"There are no collections to list" message appears in collections section.
![image](https://github.com/bitwarden/clients/assets/86488977/012ca2d3-b581-4d38-8925-0be33530440b)

### Additional Context

Workaround:
Change ownership away and back to organization to trigger collections section to repopulate.
![image](https://github.com/bitwarden/clients/assets/86488977/d5382a2b-9a53-439e-854c-efdf1e591139)

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.4.1 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @dhon-rh,

Thank you for this report. Could you please update to [2024.5.0](https://github.com/bitwarden/clients/releases/tag/desktop-v2024.5.0) and let me know if you continue to experience this?


Thank you in advance,

**Comment by dhon-rh** [comment]
Hello @SergeantConfused ,
Confirmed, issue is not present in Version 2024.5.0.

Thank you for your hard work and have a great day!
-Darryl
