### ISSUE TITLE
Azure Portal not accessible - CredentialsContainer issue

### ISSUE THREAD

**Issue by tobidemski** [bitwarden/clients#9382]
### Steps To Reproduce

1. Go to https://portal.azure.com
2. Login with your credentials
3. Wait for the x redirects
4. See this error

### Expected Result

Login and redirects to the start page of the azure portal works and does not throw an error.

### Actual Result

When the Bitwarden extension is enabled (logged in) and tested it in locked  / unlocked state (entered master password)
After selecting my account to login I get redirected and I see the error "A potentially dangerous Request.QueryString value was detected from the client (src="... object '#<CredentialsContaine...")."

Also the page-scripts.js file throws an error about the Credentials Container.
"TypeError: Cannot assign to read only property 'create' of object '#<CredentialsContainer>'"

### Screenshots or Videos

Error after login:
![image](https://github.com/bitwarden/clients/assets/17470007/428189ff-f62d-4a28-8ba2-cd0130b3d988)

### Additional Context

When I disable the extension the login and redirect works as intended and Im able to navigate through the page.
I also haven't used the Bitwarden extension to login to azure itself, it was just running in the background.

### Operating System

Windows

### Operating System Version

Windows 11 Enterprise 23H2  | OS Build: 22631.3593

### Web Browser

Chrome

### Browser Version

Version 125.0.6422.113 (Official Build) (64-bit)

### Build Version

Extension: 2024.4.2 | Server version (self hosted): 2024.2.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hello @tobidemski 

I attempted to reproduce your issue and was unable to do so, i am using chrome browser with the extension version Version: 2024.5.0

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.
Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/).

**Comment by tobidemski** [comment]
Oh I wasn't aware there were a new version "2024.5.0" I updated the extension and it seems the login issue disappreared.
Thanks for the fast response!

**Comment by martijnvanschie** [comment]
Running into the same issue as described above. But in my case on Edge.
I see that the Edge version is still 2024.4.2. Are there plans to release the new version to Edge soon?

Regards,
Martijn

**Comment by JPLumiCan** [comment]
> Running into the same issue as described above. But in my case on Edge. I see that the Edge version is still 2024.4.2. Are there plans to release the new version to Edge soon?
> 
> Regards, Martijn

FYI, you can install [directly ](https://chromewebstore.google.com/detail/bitwarden-password-manage/nngceckbapebfimnlniiiahkandclblb) from the Chrome web store to get the newer version. That's what I did (also on Edge) and it cleared the issue up for me right away.

**Comment by martijnvanschie** [comment]
Thank you for pointing that out @JPLumiCan. I was not aware of that method.

Strangely i was already on the latest version (2024.6.0). The version in the Edge store is one day earlier than the chrome store but not recognized as the same. Chrome store allows me to install it.

**Edge version i currently have**
![image](https://github.com/bitwarden/clients/assets/8370550/5eb5df70-c98f-4550-a6eb-513f28487f01)

**Chrome store**
![image](https://github.com/bitwarden/clients/assets/8370550/b8b79d16-ea19-4330-a586-e22b6a4536a8)

I updated to the Chrome store version. The issue occurs less than before but it is still there, unfortunately.
![image](https://github.com/bitwarden/clients/assets/8370550/2443204b-391f-47a8-bfd1-e464c1378094)

One step closer :)

**Comment by TRoZZNL** [comment]
I have the same issue, this issue seem to come from the fact that i have two password managers installed, Bitwarden and Dashlane. 
When i disable Dashlane the error disappears. But unfortunately i have to use Dashlane for work, so that's not really an option.
