### ISSUE TITLE
bw list items is slow to return items

### ISSUE THREAD

**Issue by gabrielrighi** [bitwarden/clients#9403]
### Steps To Reproduce

Run `bw list items --collectionid <collection-id>`

### Expected Result

Return the vault items in a timely manner.

### Actual Result

It takes around 20 minutes to return all the 5300 items in the vault.

### Additional Context

We have a Python program, which integrates Bitwarden passwords with another documentation software. 

With the CLI running on version 1.19.1, all the items are returned in less than 20 seconds.
With the version 2024.4.1, it hangs and eventually fails if the `bw list items --organizationid <org-id>` command is run, similar to 1.21.1 reports back in 2022.

The only way to get all items is to run `bw list items --collectionid <collection-id>` for each collection, but it still takes almost 20 minutes to return all 5300 items. By using multiprocessing, it reduces to 17 minutes.

One particular collection takes 2m45s to return its 700 items by querying from any source without any processing (Powershell, Python, Postman, either CLI or API via bw serve), but we have 155 collections.

### Operating System

Windows

### Shell

PowerShell

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by gabrielrighi** [comment]
Hello!

I tested again with the most recent build 2024.6.0 and the symptom is still present. Is there any advice to improve the password list return time?
