### ISSUE TITLE
Polling Interruption in Web Applications with Bitwarden Chrome Extension Enabled

### ISSUE THREAD

**Issue by rmhsh** [bitwarden/clients#9425]
### Steps To Reproduce

Open Google Chrome.
Ensure the Bitwarden extension is enabled.
Access any web application that periodically polls data from an API endpoint every few seconds.
Observe the network requests and polling behavior.

### Expected Result

The web application should continuously poll the API endpoint at regular intervals (e.g., every few seconds) without any interruptions, ensuring up-to-date data is displayed promptly.

### Actual Result

When the Bitwarden extension is enabled, the polling mechanism is disrupted, resulting in significant pauses. The polling intervals can be delayed by up to 54 seconds, causing the web application to appear slow and laggy as it fails to display the latest data from the API.

### Screenshots or Videos

1. With Bitwarden Enabled:
In this screenshot, you can observe the prolonged pause in the polling mechanism, leading to delayed data fetching.
2. With Bitwarden Disabled:
Here, the polling mechanism works as expected, with regular intervals and no significant pauses.

![image (1)](https://github.com/bitwarden/clients/assets/106551100/932db8e9-5a0d-49f4-a4d1-d0beb495c0ad)
![image](https://github.com/bitwarden/clients/assets/106551100/f83e7e7d-ea1d-4b5c-9a52-462be8e4c31c)

### Additional Context

The issue only occurs when the Bitwarden extension is enabled. Disabling the extension resolves the problem, and the web application performs as expected. We have ruled out other potential causes, and the correlation between enabling the Bitwarden extension and the polling disruption is consistent and reproducible.

Impact:
This bug significantly affects the usability of web applications, leading to delays in data updates and a degraded user experience.

### Operating System

macOS

### Operating System Version

macOS 14.5

### Web Browser

Chrome

### Browser Version

125.0.6422.113 (Official Build) (arm64)

### Build Version

2024.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Hi @rmhsh, can you provide us with a minimal reproducible example so that we can investigate this further?
