### ISSUE TITLE
Firefox, Private Browsing window, Bitwarden pop-up blank

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#9467]
### Steps To Reproduce

1. Launch Firefox on Linux (126.0.1 (64-bit), Mozilla build).
2. Bitwarden plugin (2024.4.1) installed, configured to be allowed in Private Browsing windows, configured not to lock, and logged in.
3. Launch Private Browsing window.
4. Click on Bitwarden icon in top bar. Note that the pop-up is blank.

Note that if you browse in the private browsing window to the home page of a site that you have logins for, the badge on the Bitwarden icon changes, so the extension is doing _something_ in the Private Browsing window, it just fails to render its window contents properly.

### Expected Result

Contents of Bitwarden pop-up window are drawn.

### Actual Result

Window is empty.

### Operating System

Linux

### Operating System Version

Debian testing

### Web Browser

Firefox

### Browser Version

126.0.1

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @jikamens,

Thank you for your report. It sounds like you're experiencing [this](https://github.com/bitwarden/clients/issues/8729), which has been addressed in [version 2024.4.2](https://github.com/bitwarden/clients/issues/8729#issuecomment-2119062606). Please check if you're able to update to that version at this point; If not, please stand by, as it'd be only a [matter of time](https://bitwarden.com/help/releasenotes/#release-announcements).

I will now close this GitHub report; If you have any questions of concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report if you do so.

Thank you again,
