### ISSUE TITLE
If you type # of vault timeout hours and then close pop-up quickly, last character doesn't register

### ISSUE THREAD

**Issue by jikamens** [bitwarden/clients#9468]
### Steps To Reproduce

1. Click the top bar icon to open the browser pop-up.
2. Click Settings.
3. Choose Custom vault timeout.
4. Click into the hours field and type "24" quickly, then quickly click outside the pop-up so it closes.
5. Open the pop-up again and go back to the settings.
6. Observe that the number of hours is set to "2" instead of "24".

### Expected Result

The captured value is 24.

### Actual Result

The captured value is 2.

### Operating System

Linux

### Operating System Version

Debian testing

### Web Browser

Firefox

### Browser Version

126.0.1

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @jikamens,

Thank you for this report. I tested this with Bitwarden browser extension 2024.4.2 within Firefox 126.0.1 on Windows 11 Pro and Ubuntu 24.04 LTS, and entering 24 hours and then immediately clicking outside the extension's pop-up resulted in an extension that did capture the 24 hours value for the [Vault Timeout](https://bitwarden.com/help/vault-timeout/) function. I recommend that you begin with a fresh new installation of the Bitwarden browser extension; Uninstall it, remove any [leftover data](https://bitwarden.com/help/data-storage/#on-your-local-machine), reboot the computer, and install it anew. If you continue to experience this, I would imagine that it could be related to the operating system as it's not a Stable release.

If you wish, please feel free to create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you'd like to.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
