### ISSUE TITLE
Error on Saving Passwords

### ISSUE THREAD

**Issue by JGageSATX** [bitwarden/clients#9497]
### Steps To Reproduce

2. Click on '..save..'
4. Click on '...'

### Expected Result

Cannot save password or password changes

### Actual Result

Error message 
![Error Bitwarden](https://github.com/bitwarden/clients/assets/155118372/11e8319f-057f-462e-a022-9951b9e558d5)

### Screenshots or Videos

![Error Bitwarden](https://github.com/bitwarden/clients/assets/155118372/eafef2c9-b9fb-46e2-961d-d621e64d2ad2)

### Additional Context

Can't save, nor add anything in Bitwarden

### Operating System

Windows

### Operating System Version

10 pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

This issue will be closed now.
