### ISSUE TITLE
Cannot enable Biometics (Unlock with Windows Hello) in v2024.5.0 (Windows, Desktop).

### ISSUE THREAD

**Issue by BJReplay** [bitwarden/clients#9516]
### Steps To Reproduce

1. Go to `File, Settings`
2. Click on `Unlock with Windows Hello`
3. Complete the Biometrics Challenge (e.g. Facial Recognition)
4. Note that the check mark next to `Unlock with Windows Hello` is not checked.

The sequence of events looks exactly like the screen recording in this issue on the community forums: https://community.bitwarden.com/t/windows-hello-keeps-unchecking-itself-in-desktop-settings/55828

### Expected Result

The check mark next to `Unlock with Windows Hello` should remain checked after completing the Biometric challenge.

### Actual Result

The biometric challenge completes, but the check mark isn't checked.

### Screenshots or Videos

The sequence of events looks exactly like the screen recording in this issue on the community forums: https://community.bitwarden.com/t/windows-hello-keeps-unchecking-itself-in-desktop-settings/55828

### Additional Context

I have reproduced on two installs: Windows 11 Enterprise and Windows 11 Pro.  Windows 11 Enterprise was a Surface 7 that was Reset.

Windows 11 Pro was a brand-new User Profile.

Both were new installs of v2024.5.0 as the current Desktop Release.

Both worked properly (I was able to turn on `Unlock with Windows Hello` when I uninstalled v2024.5.0 and installed v2024.4.3 and refused the prompt to upgrade.

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

v2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by charmarkk** [comment]
Have been having the same problems on 2024.4.2, Firefox 126.0.1, and Windows 11 AND Windows 10.

For me, it actually ticks the checkbox, but it doesn't actually prompt for biometrics (AND I have to "login" again with my email).

![image](https://github.com/bitwarden/clients/assets/22264269/9f9c0880-40ae-469b-95f0-925c64600c5c)

**Comment by BJReplay** [comment]
No, this is different. The Unlock with Biometric checkmark would not stay ticked.

Different issues.

**Comment by Krychaz** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by BJReplay** [comment]
Seems to be working ok with 2024.6.1 desktop and 2024.6.0 edge browser extension, so OK to close.
