### ISSUE TITLE
Passkeys not being accepted for Playstation mobile app

### ISSUE THREAD

**Issue by Khameleon05** [bitwarden/clients#9529]
### Steps To Reproduce

1. Go to PS App
2. Click on Sign in
3. Click on Sign in with Passkey

### Expected Result

Account should log in like norrmal.

### Actual Result

It brings up the Bitwarden popup allowing you to select the passkey, but when you select it and hit continue you're met with a "Error reading passkey: Passkeys not supported for this app"

### Additional Context

Passkeys clearly are accepted because they literally added the entire passkey process specifically to the app so I can only guess this isn't what's supposed to happen. When they first added passkey support Bitwarden also had a problem creating passkeys on their website itself (see https://github.com/bitwarden/clients/issues/8049) so I don't know if it's an extension of that or what.

### Operating System

Android

### Operating System Version

14

### Web Browser

Brave

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by muzuzum** [comment]
The error I get is: "Passkey operation failed because app not found in asset links"

**Comment by Mello7sh3i** [comment]
> The error I get is: "Passkey operation failed because app not found in asset links"

Same here. Pixel phone, android 14. The passkey works on website in browser on android, but not on the mobile app.

**Comment by Krychaz** [comment]
Hello there,

Please note that the first beta builds only supports passkeys in web browser. A follow-up beta build is coming soon that adds support for native app passkeys.

**Comment by chiypg** [comment]
For PS App, the workaround is to click cannot sign-in passkey, and then use the qr code or email to get the link and sign in in browser.

**Comment by NotoriousNico** [comment]
I have the exact same issue on my Galaxy S24 Ultra using Bitwarden 2024.7.1 and PS App version 24.9.0.
I'm on Android 14 and have all the latest updates installed.
