### ISSUE TITLE
"Passkey operation failed because browser is not privileged" error in Android Firefox Nightly.

### ISSUE THREAD

**Issue by segln** [bitwarden/clients#9562]
### Steps To Reproduce

1. Navigate to a website that supports passkey.
2. The passkey list is shown.
3. Select a passkey.

### Expected Result

Bitwarden shows (fingerprint)authentication form and continues to website.

### Actual Result

An error occurred. "Passkey operation failed because browser is not privileged" 

### Additional Context

FF Nightly recovered passkey support on 128.0a1.
This works well with Proton Pass (tested) so maybe this is not FF's problem.

Works well with Chrome.

### Operating System

Android

### Operating System Version

14

### Web Browser

Firefox

### Browser Version

Nightly 128.0a1

### Build Version

2024.5.1 (10574)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @segln 

Thank you for your report. I understand that you are using the Bitwarden browser extension within your mobile Firefox browser; Please bear in mind that that client is designed for desktop environments (https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile) and browsers, and on Android you should use our dedicated Android client (https://bitwarden.com/help/getting-started-mobile/).

If you wish, you can continue using that client in the mobile Firefox browser, but you'd be doing so at your own risk as some of its functions may not operate as expected in a mobile environment.

This issue will now be closed. 
Thanks!

**Comment by golightlygl** [comment]
I am using the Bitwarden dedicated Android client.  However, when navigating to a site using Firefox Nightly and attempting to use a passkey, I get the above error.

The website asks me to select my Passkey provider (as per below) 

![Screenshot_20240930_150429_Credential Manager](https://github.com/user-attachments/assets/ea618b60-2dd3-408f-a2bd-45ba78d9f323)

I selecet Bitwarden with the correct account but then I get the error reported by the OP

![Screenshot_20240930_150439](https://github.com/user-attachments/assets/abf93192-d76a-429d-a132-6910f485547e)

**Comment by sudoxnym** [comment]
oh cute, same issue, looks like its new too. and yes, using the android client

**Comment by Doomsdayrs** [comment]
experienced this today as well with the new beta client too.
