### ISSUE TITLE
Chase banking website autofill stopped working on one of the login pages

### ISSUE THREAD

**Issue by Amoeba00** [bitwarden/clients#9566]
### Steps To Reproduce

1. Go to https://secure.chase.com/web/auth/#/logon/logon/chaseOnline?treatment=chase&lang=en
2. Click on the Autofill icon

### Expected Result

Autofill password.
This used to work a few weeks ago.
However, what does work is the main website login page: https://www.chase.com/

### Actual Result

The autofill functionality stopped working.

### Additional Context

While the main login page works, if you happen to click on login without a password - then that "broken" login page appears - which used to work just fine, but now it does not.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

The latest non-beta versions every time

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by andrewda** [comment]
I've noticed this across quite a few websites as well, with extension version 2024.5.2. If I find some time, I'll try to dig around and see what's up, unless someone beats me to it.

```
Error: Did not auto-fill.
    at KS.<anonymous> (background.js:2:1644742)
    at Generator.next (<anonymous>)
    at s (background.js:2:1640035)
```

**Comment by jtodddd** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment]
This issue was resolved with work incorporated for https://github.com/bitwarden/clients/pull/9063

Closing this thread for now.

**Comment by Amoeba00** [comment]
Perfect - thanks for prompt resolution.  Have a great week!

**Comment by timkgh** [comment]
This is broken again, it seems to break on a regular basis ...
