### ISSUE TITLE
Firefox extension logout everyday automatically

### ISSUE THREAD

**Issue by navid-ahrary** [bitwarden/clients#9577]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Everyday the extension is logout

### Actual Result

--

### Operating System

Linux

### Operating System Version

openSUSE 15.5

### Web Browser

Firefox

### Build Version

126.0.1 (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Duplicate: https://github.com/bitwarden/clients/issues/8873
