### ISSUE TITLE
Bitwarden Web Vault login page not loading in Edge

### ISSUE THREAD

**Issue by vbn-gerbrand** [bitwarden/clients#9580]
### Steps To Reproduce

Submitting this for a colleague of mine. The login page at https://vault.bitwarden.eu/#/login will not load in Edge on his laptop. Doesn't work in an InPrivate window either. It does work in Chrome.

### Expected Result

Expected behavior is for the login page to display.

### Actual Result

Page doesn't load, console shows the following:

<img width="671" alt="afbeelding" src="https://github.com/bitwarden/clients/assets/172400040/6f5c468b-e91c-49ea-b603-a29736cd915b">

### Operating System

Windows

### Operating System Version

10

### Web Browser

Microsoft Edge

### Build Version

unknown

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,
I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
