### ISSUE TITLE
Firefox Bitwarden extension blank when opened

### ISSUE THREAD

**Issue by AnsonCNS** [bitwarden/clients#9582]
### Steps To Reproduce

1. Go to Firefox browser
2. Click on Bitwarden extension

### Expected Result

Opens Bitwarden extension UI with the login screen or the Bitwarden vault

### Actual Result

Empty box

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/63702682/580cb3ad-47c1-404d-9b7e-e91e16dbf296)

### Additional Context

The Bitwarden Firefox extension has been logging out frequently as reported by [others](https://github.com/bitwarden/clients/issues/9577). 

However, since today, clicking on the extension just opens up an empty box.

I have tried reinstalling the extension and clearing cache.

### Operating System

Windows

### Operating System Version

22H2

### Web Browser

Firefox

### Browser Version

126.0.1 (64-bit)

### Build Version

2024.4.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AnsonCNS** [comment]
Seems to have been resolved just as I posted this issue!

**Comment by rsulli55** [comment]
@AnsonCNS Did you do anything to fix the issue? I am also running into this issue, on Linux with Firefox version 127.0.1

**Comment by pwnorbpwnd** [comment]
Hi I also have this issue appear within the past day
Windows 10 22H2 19045.4529
Firefox 127.0.2
Bitwarden  2024.6.3

**Comment by AnsonCNS** [comment]
@rsulli55 I attempted to resolve the issue by reinstalling the Bitwarden extension on firefox, it did not work. The issue resolved itself after a few a hours, which is why I closed the Issue 3 weeks ago.

I have not encountered this issue since.

**Comment by mrlinnth** [comment]
I have encountered this issue quite a lot of time in past weeks/months.  Still cannot find the fix. Only workaround I can use is using the auto fill from the right click menu. 

I have encountered this on both my Linux (POP_OS) and Windows 10. Happened on all the browsers that I mainly use which are Brave, Firefox, Edge.

So maybe we should keep this open for the devs to notice.

**Comment by adrianj12** [comment]
![bitwarden_broken](https://github.com/user-attachments/assets/9c50efbe-dcee-4f40-9f2f-6853f29380e9)
Also running into this issue within the past few days. Have never had this happen before. 

Bitwarden Version
2024.6.3

Firefox Version
128.0

**Comment by agmalpartida** [comment]
This behavior happened to me on Windows 11.

Bitwarden Version
2024.6.3

Firefox Version
128.0

This occurs when I am unable to reach my self-hosted instance; if I am connected to my instance, this issue does not occur.

**Comment by dominikheinz** [comment]
Same issue here. Hope this gets fixed soon.
The issue is present on both, Firefox and Chromium for me.

**Comment by dieeisenefaust** [comment]
Same issue on Firefox (130.0) and Chrome (128.0.6613.85).

**Comment by mrlinnth** [comment]
I think I found the root cause. VPN. My country has blocked quite a few online entities and services. Without VPN, I face blank modal box. With VPN connection, I can access Bitwarden as normal.

**Comment by mselchow** [comment]
Also having this issue on Firefox on both Mac and Windows. The issue is persistent regardless of VPN usage (I do not use a VPN regularly, and have the bug beforehand and afterwards).

**Comment by gotofritz** [comment]
Happens occasionally on FF on OS X, logging out and then back has fixed the problem so far

**Comment by bartvdbraak** [comment]
I have this issue currently as well

**Comment by fluffy-critter** [comment]
This happens to me sometimes and the usual fix is to uninstall and reinstall the extension.
