### ISSUE TITLE
Bitwarden Firefox-Extension suggesting to fill passwords in the Gmail search field

### ISSUE THREAD

**Issue by SmilingGit** [bitwarden/clients#9591]
### Steps To Reproduce

1. Go to Gmail in Firefox
2. Click on the search bar in Gmail
Bitwarden will show a list of possible logins for Google / Gmail. But I’m already logged in! And it’s not a username / password field! 

### Expected Result

Bitwarden not interfering with Gmail’s search option

### Actual Result

Bitwarden suggests logins, therefore messing up many of my searches. When selecting one of the logins, it fills in the username.

### Operating System

macOS

### Operating System Version

14.5

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by SmilingGit** [comment]
Hi there,

Thank you for your message. I understand the process you want me to go through. In the meantime, I thought I’d share some screenshots with you, in case someone else is experiencing the same issue:

<img width="922" alt="SCR-20240613-oxib" src="https://github.com/bitwarden/clients/assets/117445491/d1cbf59a-3103-4c98-9e28-05785a4c2869">

When Bitwarden is unlocked (i.e. most of the time in my case), it’s even more annoying, since I can’t use the keys to select search results. 

I also noticed that Bitwarden wants to fill in the e-mail section of the contacts-sidebar.

<img width="329" alt="SCR-20240613-oxky" src="https://github.com/bitwarden/clients/assets/117445491/bbe7bd8f-3157-474b-b484-c2e8d30f3c90">

Have a nice day!

**Comment by SmilingGit** [comment]
Bitwarden support answered that it’s a known issue.

For anyone stumbling on this, the workaround is to deactivate the Autofill-Menu on Form Entries in the Settings. Here is how it looks like in my German setup:

<img width="350" alt="grafik" src="https://github.com/bitwarden/clients/assets/117445491/759d8a7b-4b53-47bd-a99f-3de18ec63765">

**Comment by josch87** [comment]
I have the same problem and it is really nerve-racking. As deactivating "Autofill-Menu on form entries" is a global setting and effects all websites, switching to the english UI of Gmail is a better workaround for me at the moment. The problem only occurs with the German UI.
