### ISSUE TITLE
Android app does not allow to select anymore .EU domain - European users can not use anymore the android app

### ISSUE THREAD

**Issue by acaratel** [bitwarden/clients#9619]
### Steps To Reproduce

4. Click on '...'

### Expected Result

Expect to be able to select and login to bitwarden.eu from the Android app

### Actual Result

I can select only bitwarden.com and self-hosted, therefore it is impossible to login for EU users

### Operating System

Android

### Web Browser

Chrome

### Build Version

Latest available on play store

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by nyrokx** [comment]
I can also not see it in the IOS app. I can also only select bitwarden.com and self-hosted.

**Comment by Krychaz** [comment]
Hello,

Thanks for taking the time to report this today. The Engineering department is aware of it, and a fix has been submited already. 

For the time being, please enter vault.bitwarden.eu in the self-host flow: https://bitwarden.com/help/change-client-environment/#tab-mobile-app-4dQ4hW1QAwVBuReXk2Txx0

Thank you for your patience.
