### ISSUE TITLE
AN error has occured 

### ISSUE THREAD

**Issue by RichardEJason** [bitwarden/clients#9620]
### Steps To Reproduce

4. Click on '...'

### Expected Result

when changing my password it gives me this error.

### Actual Result

cannot save new password

### Screenshots or Videos

screenshot redacted

### Operating System

Windows

### Operating System Version

23h2

### Web Browser

Chrome

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by RichardEJason** [comment]
I cannot even put in a new user name and password in to save it

**Comment by Neonwarden** [comment]
Hello there,

We use GitHub issues as a place to track bugs and other development-related issues. Please write us back using our “Contact Support” form located on our Help Center (https://bitwarden.com/help/).

Thanks!

This issue will be closed.
