### ISSUE TITLE
Azure Portal not accessible again (v. 2024.6.0)

### ISSUE THREAD

**Issue by tobidemski** [bitwarden/clients#9648]
### Steps To Reproduce

Go to https://portal.azure.com/
Login with your credentials
Wait for the x redirects
See an error: old ticket: https://github.com/bitwarden/clients/issues/9382

It worked after I updated to "2024.5.0" but since there is a new update "2024.6.0" which got installed automatically I'm facing the same issue again.

### Expected Result

Login and redirects to the start page of the azure portal works and does not throw an error.

### Actual Result

When the Bitwarden extension is enabled (logged in) and tested it in locked / unlocked state (entered master password)
After selecting my account to login I get redirected and I see the error "A potentially dangerous Request.QueryString value was detected from the client (src="... object '#<CredentialsContaine...")."

Also the page-scripts.js file throws an error about the Credentials Container.
"TypeError: Cannot assign to read only property 'create' of object '#'"

### Additional Context

When I disable the extension the login and redirect works as intended and Im able to navigate through the page.
I also haven't used the Bitwarden extension to login to azure itself, it was just running in the background.

### Operating System

Windows

### Operating System Version

Windows 11 Enterprise 23H2 | OS Build: 22631.3593

### Web Browser

Chrome

### Browser Version

Version 125.0.6422.142 (Official Build) (64-bit)
also updated afterwards to newer version of chrome
Version 126.0.6478.62 (Official Build) (64-bit)

### Build Version

Extension: 2024.6.0 | Server version (self hosted): 2024.2.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by martijnvanschie** [comment]
Same here

![image](https://github.com/bitwarden/clients/assets/8370550/5016f4ee-2120-47e8-acc8-9fbc953d0653)


![image](https://github.com/bitwarden/clients/assets/8370550/876ade72-85fa-46e0-aca0-61dee78e732d)

**Comment by jtodddd** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Greenderella** [comment]
Hi @tobidemski,

I'm unable to reproduce this issue, are you able to log in if you update your Chrome extension to the latest version (2024.6.1)?

**Comment by tobidemski** [comment]
After doing an upgrade one more time (2024.6.1) it worked again! Thanks for the help.
