### ISSUE TITLE
GPO Force Installed - Default auto-fill menu enabled

### ISSUE THREAD

**Issue by Valiantiam** [bitwarden/clients#9650]
### Steps To Reproduce

Deploy Bitwarden extenion over GPO as a force installed and allowed extension

### Expected Result

Users that aren't actively using the extension, should not be forced to deal with this popup if possible and can either disable the setting that auto-fills inline on the page form fields, or not have it enable until they login the first time to the extension.

### Actual Result

Every browser by default has a bitwarden in-line autofil button popup even if they are not logged in and never have.
They cannot access settings unless they create an account, log in, and disable that setting for Form field auto-fill.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5394853/add09986-b6cf-4e90-9caf-58e8f27945d0)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.6.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Valiantiam** [comment]
This seems to only be happening on chrome actually... I can't get it to reproduce on Edge.

**Comment by cagonzalezcs** [comment]
@Valiantiam 

Thank you for providing this bug report. [This issue has been resolved recently](https://github.com/bitwarden/clients/pull/9273) and a fix for it should be rolling out soon.

If you have any other questions, please let me know.
