### ISSUE TITLE
Error during the 

### ISSUE THREAD

**Issue by Freeky-del** [bitwarden/clients#9670]
### Steps To Reproduce

1. Go to 'https://bitwarden.com/download/'
2. Click on 'Windows'
3. Open the installer
4. Click on 'Install'
5. Wait for the error

### Expected Result

The bitwarden desktop app

### Actual Result

An error during the installation that said: ```Unable to download application package from https://artifacts.bitwarden.com/desktop/bitwarden-2024.6.1-x 64.nsis.7z (status: File Not Found (404)).
Please check your internet connection and retry```

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/84967777/dad4f23d-279d-4e8d-94da-c7eb75487288)

### Operating System

Windows

### Shell

Bash

### Build Version

latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @Freeky-del,

Thank you for this report. Could you please let me know if you're still encountering this behaviour?


Thank you in advance,

**Comment by Freeky-del** [comment]
Hi @SergeantConfused,
luckily i'm not still encountering this behaviour.
Thank for support.
