### ISSUE TITLE
“Remember email” function is not working in Google Chrome Bitwarden extension. Bitwarden extension is NOT remembering my email address.

### ISSUE THREAD

**Issue by VanillaTwilight123** [bitwarden/clients#9680]
### Steps To Reproduce

Steps to reproduce:

[Operating System: Windows 11 version 23H2]

Step 1: Update Google Chrome to the latest version. Right now, it is version 126.

Step 2: Download the Bitwarden Password Manager extension from the Chrome Web Store.

Step 3: In the Bitwarden extension, put your email address.

Step 4: Check the “Remember Email” box.

Step 5: Then, complete your login as per the usual process.

Step 6: After that, “Log out” your account from the Bitwarden extension.

Step 7: Now you can see that the Bitwarden extension has not remembered your email address. The Email address box is empty.

But the “Remember Email” function is working perfectly fine on both the Bitwarden Firefox extension and the Bitwarden desktop app for Windows 11.

### Expected Result

The Google Chrome Bitwarden extension should remember my email address so that I do not need to type it again.

### Actual Result

The Google Chrome Bitwarden extension has not remembered your email address. The Email address box is empty.

### Screenshots or Videos

![Screenshot 2024-06-17 113348](https://github.com/bitwarden/clients/assets/168930789/2f6044a9-094e-4033-b97a-b7a28645dbdc)

### Operating System

Windows

### Operating System Version

Windows 11 version 23H2

### Web Browser

Chrome

### Browser Version

Version 126.0.6478.62 (Official Build) (64-bit)

### Build Version

Version 126.0.6478.62 (Official Build) (64-bit)

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by SergeantConfused** [comment]
Hello everyone,

For added context, this also affects version 2024.6.1 of the Bitwarden Edge extension on Edge 126.0.2592.56.

All the best,

**Comment by VanillaTwilight123** [comment]
> Hello everyone,
> 
> For added context, this also affects version 2024.6.1 of the Bitwarden Edge extension on Edge 126.0.2592.56.
> 
> All the best,

Bitwarden Opera extension is also affected the same way. So it seems like Chromium based Bitwarden browser extensions are having this issue.

**Comment by bhartshorn** [comment]
Same issue occurring on Firefox:
Extension Version: 2024.6.2
Firefox Version: 127.0

I can confirm the issue in Edge also.

**Comment by VanillaTwilight123** [comment]
> Same issue occurring on Firefox: Extension Version: 2024.6.2 Firefox Version: 127.0
> 
> I can confirm the issue in Edge also.

Thanks for the confirmation. 
But in my case Bitwarden Firefox extension was working fine.

**Comment by scooby52** [comment]
> > Same issue occurring on Firefox: Extension Version: 2024.6.2 Firefox Version: 127.0
> > I can confirm the issue in Edge also.
> 
> Thanks for the confirmation. But in my case Bitwarden Firefox extension was working fine.

I am also having this problem with Firefox v127 on Win 11, started several days ago. Bitwarden extension version 2024.6.2

**Comment by NaabKing** [comment]
Same thing here, at first it stopped remembering "Master Password" for a few weeks and for a few days now, e-mail is not remembered anymore. It logs you out like every 24 hours, basically, every time i wake up, i have to re-enter E-Mail and Master Password now.

Firefox v127.0.2
Bitwarden v2024.6.2

**Comment by e33et** [comment]
Same happens to me after being inactive after a while with the Mozilla Firefox extension Add-On!
