### ISSUE TITLE
Chrome Extension will not open if dev tools is open in any Chrome window / tab

### ISSUE THREAD

**Issue by jkibble** [bitwarden/clients#9692]
### Steps To Reproduce

Pin extension (or not) to Chrome tool bar
Right click on any web page and select "inspect"
Click on Bitwarden icon to open vault drop down

### Expected Result

The drop down opens

### Actual Result

The drop down will not activate

### Operating System

Linux

### Operating System Version

125.0.6422.169 ChromeOS

### Web Browser

Chrome

### Browser Version

125.0.6422.169

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment]
Hi there,
Thanks for your report!

I attempted to reproduce your issue and was unable to do so.
Please update Chrome browser to the latest version, and test again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
