### ISSUE TITLE
Firefox browser extension does not update beyond 2024.4.2

### ISSUE THREAD

**Issue by msiqx9** [bitwarden/clients#9711]
### Steps To Reproduce

Both the Windows Desktop app and my Chrome browser extension are on 2024.6.1 but the Firefox browser extension remains on 2024.4.2

### Expected Result

Update Firefox extension to 2024.6.1

### Actual Result

Firefox extension remains at 2024.4.2

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

127.0 (64-bit)

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
The extension has been submitted to the browser stores (end of last week) and will become available once it has been reviewed. 

Closing this now.

**Comment by msiqx9** [comment]
> The extension has been submitted to the browser stores (end of last week) and will become available once it has been reviewed.

Today the Firefox extension has updated to 2024.6.2
