### ISSUE TITLE
Failed to decode access token

### ISSUE THREAD

**Issue by IanAmp52** [bitwarden/clients#9728]
### Steps To Reproduce

1. Edit any existing entry 
2. Click on the <Save> icon
3. Entry does not save 
4. Red message box appears “An error has occurred. Failed to access token: Access token not found.
![Screenshot of Bitwarden at 19 Jun 2024 at 09_29_01](https://github.com/bitwarden/clients/assets/173245441/75d9ba14-12d6-4297-b173-12596c1e16d6)

### Expected Result

I expect the entry update to save.

### Actual Result

As described above.

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Installation method

Mac App Store

### Build Version

Version 2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Can you please fully logout from the desktop app and login again. Does that change anything?

**Comment by IanAmp52** [comment]
> Hello there,
> 
> Can you please fully logout from the desktop app and login again. Does that change anything?

This cured the fault. Many thanks.

**Comment by IanAmp52** [comment]
This cured the fault. Many thanks.

**Comment by shimabkt** [comment]
I'm having this same issue.  Logging out of the desktop app then login in again doesn't help.

**Comment by TheQuos** [comment]
Relogging only fixes the issue for a while. I had to log out and log in every other day, for weeks or months at this point.
I'm using the apt version for Ubuntu. I have a single account in .com and 1 in .eu domain, with vault timeout locking enabled. I think in my case the problem only applies to bitwarden.com, although I use it far more than the other one.
