### ISSUE TITLE
Failed to make build for aarch64-linux on fedora asahi linux

### ISSUE THREAD

**Issue by warmachinesocial** [bitwarden/clients#9735]
### Steps To Reproduce

1. Clone the project
2. Follow same steps as the contributing guide
3. Try running desktop app after you made the desktop native module
4. Error cannot find module @bitwarden/desktop-native-linux-arm64-musl

### Expected Result

Run the app and use it

### Actual Result

Main process was throwing error so nothing shows up

### Additional Context

However I'm not sure at this stage if it's the correct way to make the build, would raise the pr soon.. up review

### Operating System

Linux

### Operating System Version

Fedora Asahi Remix

### Installation method

Other

### Build Version

2024.6.5

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Closing this, based on the comments on the linked PR.
