### ISSUE TITLE
Deploying Bitwarden with EU region as default

### ISSUE THREAD

**Issue by Mikaela** [bitwarden/clients#9745]
### Steps To Reproduce

1. Deploy Bitwarden with the following configuration on Chrome

```json
{
  "3rdparty": {
    "extensions": {
      "nngceckbapebfimnlniiiahkandclblb": {
        "environment": {
          "base": "https://bitwarden.eu"
        }
      },
    }
  },
  "ExtensionSettings": {
    "nngceckbapebfimnlniiiahkandclblb": {
      "installation_mode": "force_installed",
      "override_update_url": true,
      "toolbar_pin": "force_pinned",
      "update_url": "https://clients2.google.com/service/update2/crx"
    }
  }
}
```

2. Open a fresh Chrome profile
3. Attempt to login to the extension

### Expected Result

I expected the extension to say that I am logging in to bitwarden.eu and just work.

### Actual Result

When I open the extension, I see it thinks I am logging in to self-hosted instance and when I enter my username and password, it will load for a long time and then fill the extension window with error message about timeout.

### Additional Context

I wonder if having a separate option for official bitwarden.eu in the browser policy would work. I personally just migrated to it (and ordered family plan) today, while my family started using Bitwarden with it last week.

My goal as family IT support is to reduce confusion by having the extension default to the correct instance while I keep telling them and wrote on paper to ensure they are logging onto bitwarden.eu instead of the default bitwarden.com.

### Operating System

Linux

### Operating System Version

"Fedora Linux 40 (Forty)"

### Web Browser

Chrome

### Browser Version

Google Chrome 126.0.6478.114 

### Build Version

I cannot access the extension settings without logging in.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Mikaela** [comment]
Extension version is 2024.6.2.

![bitwarden-extension-eu](https://github.com/bitwarden/clients/assets/831184/81f6eb15-be6c-4c4e-ad08-dd21dc504875)

Screenshot looks like Cloudflare error, so I think my policy might be wrong, but I am just trying to follow https://bitwarden.com/help/deploy-clients/

**Comment by Greenderella** [comment]
Hi there,

You should be able to accomplish that with these settings:
— base URL as https://**vault.**bitwarden.eu  
— notifications URL as https://notifications.bitwarden.eu

The Chrome configuration you posted has “base”: “https://bitwarden.eu”, not sure if this is the actual error or just a typo.

If after changing your configuration with these values your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by Mikaela** [comment]
Thank you, my issue was that I didn't understand I was supposed to be using the vault URL as base instead of the top level domain. I also added the notifications URL now.

However the extension still says that I am logging in to self-hosted instance, but as it works, I am not going to start seeking for support with such a minor issue. It can enforce me teaching my family to always set login URL to bitwarden.eu even if it works at home.

**Comment by Greenderella** [comment]
Thank you for the clarification, I will open an internal bug linked to this report, so engineering can take a look at that wrong labeling of the server.

Have a great week!
