### ISSUE TITLE
CLI version 2024.6.0 session key unlock randomly fails

### ISSUE THREAD

**Issue by heaio9v2** [bitwarden/clients#9762]
### Steps To Reproduce

I can reproduce using the following within PowerShell:
1. Login to the vault using email address, master password, and two-step (TOTP) and store session in variable.
2. Search for a record in the vault using the session variable.

Sample code:
```
$emailAddress = "valid@email.address"
$masterpassword = "validMasterPassword"
$search = "google.com"
# Will be prompted for TOTP code at login
$sessionKey = &"bw.exe" login $emailAddress $masterPassword --raw
# Repeat the next line a couple of times. Randomly within 10 attempts or so I receive "Vault is locked." error. Running the command again might result in the vault unlocking as expected until it doesn't.
&"bw.exe" --session $sessionKey --nointeraction list items --search $search
```

### Expected Result

Vault stays unlocked when valid session key is presented.

### Actual Result

Vault does not unlock consistently when a valid session key is provided to the CLI. 

### Additional Context

PowerShell version 7.4.2

### Operating System

Windows

### Operating System Version

11 (10.0.26100)

### Shell

PowerShell

### Build Version

2024.6.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by maekawatoshiki** [comment]
Same here on macOS

**Comment by heaio9v2** [comment]
As a stop gap, I've had to create a retry loop within my code to detect when the vault fails to unlock. After one to two retries it will unlock as expected and the code will proceed fine for a seemingly random time.

**Comment by TroyBW** [comment]
Hi there!

Thank you for your report. We are tracking a similar issue here: https://github.com/bitwarden/clients/issues/9919

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
