### ISSUE TITLE
Firefox Extension: Incorrectly forgetting second account

### ISSUE THREAD

**Issue by cwchristerw** [bitwarden/clients#9792]
### Steps To Reproduce

1. Go to Firefox
2. Click on Bitwarden Extension
3. Look account you're logging in
4. Type your master password
5. Click on Account in the top right corner.
6. See list of accounts

### Expected Result

I will be asked to login to latest account I have used, have all my accounts in "switch accounts" and extension will remember latest account.

### Actual Result

Bitwarden extension is removing second account and I can see only first account in "switch accounts" and extension will remember only first account.

### Additional Context

I suspect its related to extension update because it happens "randomly".

### Operating System

Linux

### Operating System Version

Linux Mint 21.3

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @cwchristerw,

Thank you for reporting this. I tested this in Firefox 127.0.1 with Bitwarden 2024.6.2; I launched Firefox, logged into two different Bitwarden accounts via the extension, closed the browser, launched Firefox anew, unlocked the first account using its master password and checked my [Account Switcher](https://bitwarden.com/help/account-switching/) and saw that the second account was still available and I was able to unlock it using its master password as well. There is an upcoming release for Firefox, version 2024.6.3, and it should be approved in a few days and it'll resolve [this behaviour](https://github.com/bitwarden/clients/issues/8873) which could be the underlying cause. 

If you continue to experience this past version 2024.6.3, please feel free to get in touch using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

I will now close GitHub report.

Thank you again,

**Comment by coreyworrell** [comment]
This still happens very often for me, latest in Ubuntu 24.04 and Firefox 138.0.4. Firefox will remember for one session, several sessions, then randomly the second account is gone and I have to login, set PIN again, etc.

**Comment by netbrothers-tr** [comment]
Confirming this bug for BitWarden Firefox Extension version 2025.12.1 and Firefox version 147.0.1 (both latest available stable versions). @coreyworrell, I assume the problem persists for you as well?

**Comment by coreyworrell** [comment]
@netbrothers-tr I'm on same versions you mentioned now, and thankfully I haven't noticed the issue in several months. Hopefully this reply doesn't change that 😆

**Comment by netbrothers-tr** [comment]
Good for you, @coreyworrell! Fingers-crossed that it doesn't bother you anymore. 😃 I'm hopeful, it will go away on my machine as well at some point.

**Comment by ristein** [comment]
same here, tried on latest windows app 2026.2.1 and firefox extension 2026.2.0
