### ISSUE TITLE
Unable to return to site from extension on Firefox mobile

### ISSUE THREAD

**Issue by schnittchen** [bitwarden/clients#9793]
### Steps To Reproduce

To unlock the vault, I go to the extension via
* the kebap menu top right
* -> Extensions
* -> Bitwarden

I enter the password and unlock the vault.

From there, there is no way to get back to the web site tab.

The only way is to send Firefox to the background and bring it up again, which unlocks the vault again. This makes the extension completely unusable.

In the attached image, I've tried tapping the left arrow at the top, as well as the "pop out" icon right below it.

![1000009506](https://github.com/bitwarden/clients/assets/166765/89f5cf83-dfd6-48d1-bdaa-9d46800db635)

### Expected Result

I expect to be able to return from the extension after unlocking, with the vault staying unlocked for some time.

### Actual Result

No way at all to return to the tabs, except by sending the application to the background, which locks the vault.

### Operating System

Android

### Operating System Version

Android 13

### Web Browser

Firefox

### Browser Version

Fennec 127.0.0

### Build Version

1270020

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi there,

Thank you for this report. Could you please remove that Bitwarden browser extension from the mobile Firefox browser and install the Bitwarden mobile client from the [Google Play Store](https://bitwarden.com/download/)? More about this matter [here](https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile).

I will now close this GitHub report. If you have any questions or concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report if you do so.

Thank you again,

**Comment by schnittchen** [comment]
Eh so I must resort to copying credentials through the Android clipboard?
That sounds like far from ideal from a security perspective!

**Comment by schnittchen** [comment]
For anyone coming across this... Bitwarden can be configured as the AutoFill provider on Android, which makes filling in form credentials seamless and without touching the clipboard.

**Comment by aranapatona** [comment]
> Hi there,
> 
> Thank you for this report. Could you please remove that Bitwarden browser extension from the mobile Firefox browser and install the Bitwarden mobile client from the [Google Play Store](https://bitwarden.com/download/)? More about this matter [here](https://bitwarden.com/help/product-faqs/#q-does-bitwarden-manage-the-firefox-browser-extension-on-android-mobile).
> 
> I will now close this GitHub report. If you have any questions or concerns, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/), and please include a link to this GitHub report if you do so.
> 
> Thank you again,

Si hoy alnowledge this problem and solution is instalo the app renove the extensión? WOW. 
 
I hace todo problem too, nos justo android 13, algo ok 10 and 11, happens after vault locked, sometimes tapping manu times in the topleft back arrow returns to the site, but almost 1 out of 8 times.
