### ISSUE TITLE
Firefox doesn't remember login email (self-hosted)

### ISSUE THREAD

**Issue by jessicah** [bitwarden/clients#9815]
### Steps To Reproduce

After reboots, extension doesn't remember my login email.

### Expected Result

Expect extension to remember my login email.

### Actual Result

Extension requires entering my login email.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

127.0.1

### Build Version

Version: 2024.6.2  Server version (self-hosted): 2024.2.2 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JP95Git** [comment]
I think this is related to #8873 because some people described the same problem. Bitwarden pushed version 2024.6.3 to Mozilla and we have to wait until Mozilla has released it.

**Comment by e33et** [comment]
Happen to me as well!

**Comment by SearingEchoes** [comment]
Same issue here.

**Comment by djsmith85** [comment]
> I think this is related to #8873 because some people described the same problem. Bitwarden pushed version 2024.6.3 to Mozilla and we have to wait until Mozilla has released it.

I just checked now and `2024.6.3` is available in the Firefox Addons Store.

Please report back, if updating solves this for you

**Comment by e33et** [comment]
> > I think this is related to #8873 because some people described the same problem. Bitwarden pushed version 2024.6.3 to Mozilla and we have to wait until Mozilla has released it.
> 
> I just checked now and `2024.6.3` is available in the Firefox Addons Store.
> 
> Please report back, if updating solves this for you

Yes it seems that it has been solved now at least for me!
