### ISSUE TITLE
"Never" timeout warning stuck in infinite loop

### ISSUE THREAD

**Issue by bwbug** [bitwarden/clients#9836]
### Steps To Reproduce

1. Go to **Settings > Account Security**.
2. Set Vault Timeout period to "Never", and click <kbd>Yes</kbd> on modal pop-up with "Are you sure" warning.
3. Click <kbd>< Back</kbd>, or close browser extension window.
4. Go to **Settings > Account Security**.
5. Click <kbd>No</kbd>.

### Expected Result

* At Step &sharp;4, expect the Account Security settings to be displayed (showing the value "Never" for the Vault Timeout), with no modal pop-up warning.
* At Step &sharp;5, expect the modal pop-up warning to close, and the value of the Vault Timeout period to revert to the most recent value that was _not_ "Never", or revert to the default value.

### Actual Result

* At Step &sharp;4, the modal pop-up warning ("Are you sure") is displayed as soon as the Account Settings page is opened (without user interaction), as shown in the screenshot below.

* At Step &sharp;5, the modal pop-up warning briefly closes when clicking <kbd>No</kbd>, but then immediately re-opens; the same thing happens if clicking outside the modal pop-up, or if pressing the <kbd>Esc</kbd> key.   There is an infinite loop, which can only be broken by clicking <kbd>Yes</kbd>.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/109386143/77bfa132-e0c6-4f4f-a744-31f7e8f9662a)

### Additional Context

The modal pop-up with the "Are you sure" warning should only be displayed if the user has just changed the Vault Timeout value from a value other than "Never" to a new value of "Never".  If the value has previously been set to "Never", then the warning should not be displayed when opening the Account Security page.  

If developers deem it essential for users to re-affirm their choice to use a Vault Timeout of "Never" each time that they open the Account Security page, then users must be given a meaningful choice (i.e., it should be possible to dismiss the warning by clicking <kbd>No</kbd>.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Hello!  This has been identified internally and is currently fixed in our `main` branch (https://github.com/bitwarden/clients/pull/9579).  It will be included in our next release.

**Comment by trmartin4** [comment]
This issue was resolved with the 2024.7.1 release of the Bitwarden extension, which has been submitted to stores for approval and will be released as soon as approved by each store.

We are closing this issue, but please feel free to re-open or create a new issue if you continue to experience problems. We want to make sure that these frustrating issues can be identified and resolved as quickly as possible.
