### ISSUE TITLE
Update available

### ISSUE THREAD

**Issue by rcbebo82** [bitwarden/clients#9853]
### Steps To Reproduce

1. If a update for the client is available
2. Start Bitwarden Desktop Client
3. Start typing password
4. The update message pops up in between you type the password

That is really annoying. Mostly i then click later and have to renter my password because i dont know where it stopped counting my keys. Could you add a option to enable update check only on exiting the app. Or at least add a delay upon start before the message appears. Or maybe check if the user is typing in the password field and dont display it then.

### Expected Result

Update message should not interrupt login process.

### Actual Result

Update message stops login process.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

It looks like an existing request exists for this, as bwbug mentioned above: https://community.bitwarden.com/t/bitwarden-desktop-make-update-notification-not-steal-the-focus-during-startup/14815

Please sign up on our forums (https://community.bitwarden.com/signup) and you can vote for it and contribute to any discussions about it.

This issue will now be closed. 

Thanks!
