### ISSUE TITLE
Browser extension doesnt unlock vault when using desktop integration 

### ISSUE THREAD

**Issue by c3JpbmkK** [bitwarden/clients#9887]
### Steps To Reproduce

1. Have Vault timeout with lock on browser extension (1m) and desktop app (5m)
2. Let the browser extension first lock after timeout (it can still be unlocked, as the desktop app is unlocked)
3. Let the desktop app lock after timeout, do not unlock it when the biometrics prompt pops up automatically (see #9885)
4. Try to unlock the vault from the browser extension
5. Fail

### Expected Result

Vault is unlocked in the browser extension

### Actual Result

Vault is not unlocked, it doesnt even try to unlock. See screenshot below 

 

### Screenshots or Videos

<img width="338" alt="Screenshot 2024-07-01 at 07 27 38" src="https://github.com/bitwarden/clients/assets/90177512/1fd90c1f-71ad-414a-bcb0-b47ae2e96313">

### Additional Context

I have Vault timeout with lock on the browser extension (30m) and the desktop app (5m), and prior to last week's update, the browser extension would unlock the desktop vault using biometrics when the desktop app is locked (correct me if im wrong here, I've never checked if desktop app is unlocked when i unlock the browser extension). Now it just shows "User locked or logged out" and doesnt attempt to unlock the vault. After I unlock the desktop app (also using biometrics), the "Unlock with biometrics" option works as expected.

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.5 (23F79)

### Web Browser

Firefox

### Browser Version

Firefox 127.0.2 (64-bit)

### Build Version

Version 2024.6.3 Shell 29.4.2 Renderer 122.0.6261.156 Node 20.9.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi @c3JpbmkK ,

Your issue appears to be describing the intended behaviour of the software. 
This is done to protect the encryption key stored by the desktop app, which is used for biometrics, from being used unexpectedly. So it is now required for the desktop app to be unlocked before you can unlock the extension. The team is discussing solutions to allow this flow in a secure way. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Comment by ptoump** [comment]
> Hi @c3JpbmkK ,
> 
> Your issue appears to be describing the intended behaviour of the software. This is done to protect the encryption key stored by the desktop app, which is used for biometrics, from being used unexpectedly. So it is now required for the desktop app to be unlocked before you can unlock the extension. The team is discussing solutions to allow this flow in a secure way.
> 
> We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/
> 
> Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.
> 
> This issue will now be closed.
> 
> Thanks!

Hi @daniellbw 

That makes a lot of sense security wise, but from an ease of use perspective we shouldn't need to open the desktop app each time we need to unlock the extension. 
This will lead to keeping the desktop app unlocked for much longer periods which beats the purpose. 
I would suggest finding a way to do this "automatically" for example automatically requiring  2 biometric unlocks, one for the app and one for the extension in succession, without the user having to try to unlock the extension, fail, open the app, unlock it and then try again to unlock the extension. 
If the app is locked, then automatically prompt to unlock it.. 

I hope it makes sense..

Thanks,
Panos

**Comment by daniellbw** [comment]
Hi Panos,

Thank you for your response.
I understand completely, could you please consider adding to the discussion there as well!

This issue is a duplicate of #9539
