### ISSUE TITLE
CLI (macOS) generate does not exit

### ISSUE THREAD

**Issue by jvalteren** [bitwarden/clients#9890]
### Steps To Reproduce

1. login using `bw login --apikey``
2. unlock with `bw unlock`
3. set BW_SESSION environment variable using `export BW_SESSION="***"`
4. run the `bw generate` command

### Expected Result

The generated password is printed as output and the command returns (with exit code 0).

### Actual Result

The generated password is printed, but control is 'stuck', i.e. the command doesn't exit. Using Ctrl+C, the command can be terminated. This prevents the generate command to be used in scripting, which sort of beats its purpose ;-)

### Additional Context

Doesn't work with either server bitwarden.com or custom on-premise enterprise server.
Macbook Pro is running an Apple M3 Pro chip.

### Operating System

macOS

### Operating System Version

Sonoma 14.4.1

### Shell

Zsh

### Build Version

2024.6.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jvalteren** [comment]
PS the option `--cleanexit` doesn't change the outcome.

**Comment by Lee-Yarbrough** [comment]
I can also confirm that I am seeing this issue with the same setup as the reporter.

![Screenshot 2024-07-01 at 11 10 28](https://github.com/bitwarden/clients/assets/54289317/f22b7bbf-c39a-4538-aff7-ee521565403c)

The command **_does_** eventually exit but it takes about 1 minute to do so every single time. Downgrading to the previous release does not have this issue.

**Comment by cbw23** [comment]
Hi there,
Thank you for your report. 

I was able to reproduce this issue. The command eventually exits after a while. I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment]
Closing this, as the issue was addressed with #9807 and the changes are included in `2024.7.1`
