### ISSUE TITLE
(Google Chrome) Navigation bar is not visible

### ISSUE THREAD

**Issue by sattellite** [bitwarden/clients#9909]
### Steps To Reproduce

1. Account must have some vaults
2. Open extension in Google Chrome browser
3. Navigation bar under visible area (scrollbar on the right side)

### Expected Result

navigation bar always visible at bottom of the extension page

### Actual Result

navigation bar under visible area of the extension page and I must scroll to it.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/322910/1c9dc8c6-ccec-4d68-89dd-1daeb69f5b3f)
![image](https://github.com/bitwarden/clients/assets/322910/2b21a303-9b79-44d2-ae43-01599bd94fb6)

### Additional Context

Inspected some css loaded for background.html and found some fix for that:
 - remove `height` for `body` in base.scss
 - add `max-height` for `app-root`

little diff looks like this:

```diff
--- /pseudo/original
+++ /pseudo/new
@@ -0,0 +0,0 @@
body {
  width: 375px !important;
-  height: 600px !important;
  position: relative;
  min-height: 100vh;
  overflow: hidden;
  color: #000;
  background-color: #f0f0f0;
}
app-root {
  position: absolute;
  width: 100%;
  height: 100%;
+  max-height: 600px;
  z-index: 980;
}
```

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

126.0.6478.127

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
Hello!  Thank you for your contribution.

We are completing a UI redesign of our browser extension, and this issue will be addressed separately in that rewrite.

We appreciate you taking the time to propose this solution as well, but we were not able to use it in the updated version.
