### ISSUE TITLE
errorr

### ISSUE THREAD

**Issue by jimymonter** [bitwarden/clients#9930]
### Steps To Reproduce

4. Click on '...'

### Expected Result

sad

### Actual Result

asd

### Screenshots or Videos

sad

### Additional Context

sad

### Operating System

Windows

### Operating System Version

sad

### Web Browser

Safari, Firefox

### Browser Version

sad

### Build Version

sad

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hackayuda** [comment]
COMO HACKEAR WHATSAPP 2024 - Software Espiar Whatsapp | ParentalProtect™️|   Como Hackear WHATSAPP DE OTROS - CLONAR WHATSAPP A DISTANCIA


👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/  👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.comoespiarwsp.xyz/    👈🏻👈🏻


Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.comoespiarwsp.xyz/    👈🏻👈🏻


👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/  👈🏻👈🏻

Publicado hace 4 minutos:


TELEGRAM Chat Directo:
https://telegram.me/ParentalProtect 


Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/ 👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/  👈🏻


Como hackear WhatsApp España - EEUU - Chile - Perú - Ecuador - Mexico - Colombia - Guatemala - El Salvador - Republica Dominicana - Bolivia. TODOS LOS PAISES DISPONIBLE


Somos lideres en el sector de CyberSeguridad y EthicalHack con mas de 10 años de experiencia en diferentes tipos servicios

¿Tiene sospechas de infidelidad?
Entérese de lo que esta pasando!

Como Hackear WhatsApp en tiempo real
Recuperación de mensajes Eliminados

GARANTIZAMOS TOTAL SEGURIDAD Y DISCRECION

NUESTROS SERVICIOS ESTAN DISPONIBLES EN TODOS LOS PAISES


Copyright © 2024



SERVICIO -  Como Hackear WhatsApp 2024 de manera efectiva y Real.

![ParentalProtect](https://github.com/bitwarden/clients/assets/174574260/3a64839e-7607-4696-bce5-b4ad80eddad0)

**Comment by WspieMobile7** [comment]
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)
 
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)
 

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)

 
![IMG_7352](https://github.com/microsoft/vscode/assets/173863764/09278df0-083f-4b94-aa77-f8c380ba6ab4)

 
TELEGRAM Chat Directo: https://telegram.me/WspieMobile
 
[WHITE HAT]
OFRECEMOS SERVICIOS INFORMATICOS PROFESIONALES 
COBERTURA A NIVEL MUNDIAL 
TOTAL DISCRECION Y CONFIDENCIALIDAD
NO ES UN SERVICIO GRATUITO

**Comment by katieannn** [comment]
Todo gracias a Vladimir, pude espiar el iPhone de mi marido con la ayuda de Vladimirhacks en Instagram desde Francia, para ver cómo me engañaba y mentía.
