### ISSUE TITLE
error

### ISSUE THREAD

**Issue by amelioas** [bitwarden/clients#9934]
### Steps To Reproduce

4. Click on '...'

### Expected Result

dsa

### Actual Result

sad

### Screenshots or Videos

sad

### Additional Context

asd

### Operating System

macOS

### Operating System Version

sad

### Web Browser

Safari

### Browser Version

sad

### Build Version

sad

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AyudaHack** [comment]
Como Hackear WhatsApp lo que hace tu pareja en WhatsApp? Con el Modo Oculto & Indetectable - HACKEAR WHATSAPP | Espiar WhatsApp DE MI PAREJA | NUEVO TRUCO


👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp 
ahora : https://www.ayudahacker.info/ 👈🏻👈🏻

Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora :   https://www.comoespiarwsp.xyz/    👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/  👈🏻👈🏻

Publicado hace 14 minutos:

TELEGRAM Chat Directo:
[https://telegram.me/ParentalProtect ](https://telegram.me/ParentalProtect)


Chat Directo:
https://chatting.page/ayudahacker

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora : https://www.ayudahacker.info/ 👈🏻👈🏻

👉🏻👉🏻 Haga clic aquí para comenzar a hackear WhatsApp ahora :   https://www.comoespiarwsp.xyz/    👈🏻👈🏻


Publicado hace 10 minutos:



Como hackear WhatsApp España - EEUU - Chile - Perú - Ecuador - Mexico - Colombia - Guatemala - El Salvador - Republica Dominicana - Bolivia. TODOS LOS PAISES DISPONIBLE



Somos lideres en el sector de CyberSeguridad y EthicalHack con mas de 10 años de experiencia en diferentes tipos servicios

¿Tiene sospechas de infidelidad?
Entérese de lo que esta pasando!

Como Hackear WhatsApp en tiempo real
Recuperación de mensajes Eliminados

GARANTIZAMOS TOTAL SEGURIDAD Y DISCRECION

NUESTROS SERVICIOS ESTAN DISPONIBLES EN TODOS LOS PAISES


Copyright © 2024


SERVICIO -  Como Hackear WhatsApp 2024 de manera efectiva y Real.
![IMG_7729](https://github.com/bitwarden/clients/assets/174455736/cbc960f0-ffbd-403b-8882-d562b677f618)

**Comment by WspieMobile7** [comment]
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)
 
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)
 

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)

 
![IMG_7352](https://github.com/microsoft/vscode/assets/173863764/09278df0-083f-4b94-aa77-f8c380ba6ab4)

 
TELEGRAM Chat Directo: https://telegram.me/WspieMobile
 
[WHITE HAT]
OFRECEMOS SERVICIOS INFORMATICOS PROFESIONALES 
COBERTURA A NIVEL MUNDIAL 
TOTAL DISCRECION Y CONFIDENCIALIDAD
NO ES UN SERVICIO GRATUITO### ###

**Comment by katieannn** [comment]
Me lo agradecerás más tarde. Puedo ayudarte a espiar el teléfono de tu marido, envía un DM a Vladimirhacks en Instagram desde Francia. Puedo pillarlo haciendo trampa y mintiendo.
