### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by matiashufert** [bitwarden/clients#9955]
### Steps To Reproduce

4. Click on '...'

### Expected Result

D

### Actual Result

D

### Screenshots or Videos

D

### Additional Context

D

### Operating System

macOS

### Operating System Version

D

### Web Browser

Safari

### Browser Version

D

### Build Version

D

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Darbeider** [comment]
No vale

**Comment by Darbeider** [comment]
No vale

**Comment by Darbeider** [comment]
No funciona
