### ISSUE TITLE
Brave (chromium) extension logs out everyday

### ISSUE THREAD

**Issue by ElRocha** [bitwarden/clients#9961]
### Steps To Reproduce

1. Have the extension unlocked and the browser running.
2. Put pc (M2 Mac in this case) to sleep.
3. Return the next day (not sure what minimum time is required to trigger) and the extension has logged out.

### Expected Result

Session should remain logged in, with at most a lock requiring fingerprint or pin.

### Actual Result

Session logs out requiring to input email and password to login again.

### Additional Context

I saw that a similar issue was fixed for Firefox with the version 2024.6.3, but the latest version for chrome extensions is only 2024.6.2.

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Web Browser

Brave

### Browser Version

1.67.123

### Build Version

2024.6.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by trmartin4** [comment]
@ElRocha,

Thank you for the report.  The issue does appear to be the same one reported on Firefox.  The logout problems were reported exclusively (or nearly so) on Firefox and so we released that extension separately to address them.  We will be incorporating the same changes in our next full extension release cycle.  I can't commit to an exact date for that yet, but it will be soon.

**Comment by ElRocha** [comment]
@trmartin4 Update: IDK why or what changed, but over the last few days the behaviour has disappeared and the extension has been keeping the login session alive.

**Comment by krasen1234** [comment]
same issue, keeps logging out on brave and chrome.

**Comment by rdslw** [comment]
same issue here on chrome. started around may.

**Comment by piotrpalek** [comment]
same issue on Arc browser

**Comment by trmartin4** [comment]
This issue has been resolved in the `2024.7.1` release of the extensions, which have been submitted to the extension stores this week.

Thank you for your patience as we diagnosed and addressed it.  We are closing this issue since the fix has been pushed to stores for approval.  If you continue to experience unexpected logouts with the updated version, please feel free to re-open or create a new issue.

Thank you.
